Added alternative method for environment variables in Cloudflare adapter docs
withastro/docs pull request #10001
Opened 2024-11-12 22:05 UTC by NameIsHiki

#### Description

This PR adds an alternative approach for managing environment variables in the Cloudflare adapter documentation.

For developers transitioning from local development or preferring consistency with `import.meta.env` pattern, there's an alternative approach that could be documented.

#### Related issues & labels

- Closes #9984
- Suggested label: add new content

2024-11-12 22:05 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| File                                                                                                                                                                                                    | Note                                               |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [en/guides/integrations-guide/cloudflare.mdx](https://github.com/withastro/docs/blob/70876201cee897badced4a4c2544921348426c39/src%2Fcontent%2Fdocs%2Fen%2Fguides%2Fintegrations-guide%2Fcloudflare.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-11-12 22:05 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🥳.

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-11-13 12:38 UTC, sarah11918 commented
Thank you for contributing to the docs @NameIsHiki !

I will ask @florian-lefebvre and / or @alexanderniebuhr to take a look at this and see what they think about recommending this alternative pattern in docs!

2024-11-13 12:40 UTC, alexanderniebuhr reviewed
I'm not really sure if we should document this, however I'll wait for other opinions.

2024-11-13 14:44 UTC, florian-lefebvre requested changes
I agree with Alex, I don't think we should encourage this usage. The secret ends up in the build output, which can be unsafe. Also, I think there are some quircks with how the cloudflare adapter handles this kind of things (Alex knows better).

Maybe that could be a tip on https://astro-tips.dev/ instead.

2024-11-13 14:48 UTC, sarah11918 commented
OK, it sounds like this is not something for official docs so I will close this! Thank you everyone! :raised_hands:

2024-11-13 14:48 UTC, closed without merging

2024-11-13 19:42 UTC, NameIsHiki commented
Thanks for the feedback, everyone! I understand now why it makes sense to prioritize the official method and keep things as clear and secure as possible.

**Just to add context:** I initially proposed this because in the main Astro docs for environment variables, I got accustomed to using the `import.meta.env` pattern, and when I started using the Cloudflare adapter, I noticed the different approach there. I found the workaround for `import.meta.env` helpful for consistency and thought it might be useful for others in a similar situation.

I see now how it could potentially cause confusion or security issues—thanks again for the guidance!