docs: Add information about dynamic static split server islands
withastro/docs pull request #10106
Opened 2024-11-25 22:23 UTC by Jacob-Roberts

#### Description (required)

This PR is the documentation follow-on to [this PR](https://github.com/withastro/astro/pull/12320) which adds the ability to serve the server islands from a separate domain.

#### For Astro version: `5.0`. See astro PR [12320](https://github.com/withastro/astro/pull/12320).

#### First-time contributor to Astro Docs?

jake_roberts

2024-11-25 22:24 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| File                                                                                                                                                                                          | Note                                                       |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| [en/reference/integrations-reference.mdx](https://github.com/withastro/docs/blob/e9ae88bcc49473304026258ffd64edb560176382/src%2Fcontent%2Fdocs%2Fen%2Freference%2Fintegrations-reference.mdx) | Source changed, localizations will be marked as outdated.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-11-25 23:36 UTC, sarah11918 reviewed
Hi @Jacob-Roberts , thanks for submitting documentation for your feature! 🚀 

I took a look at the initial PR, and I haven't seen the code approved yet, and docs can never be edited before we know that the feature is complete and approved anyway, in case some details or implementation change during the code review process. So just letting you know this will have to sit and wait on the feature being accepted. (And, it's possible being so close to a v5 release that there may not yet be another beta release, in which case I don't know whether devs would accept a new feature without being able to at least release it in a beta first? Just a heads up on that, too! This is cutting it SUPER close for comfort! But, I'll wait and see what happens there!)

In the mean time, I've left a comment about needing an example though!

2024-11-25 23:36 UTC, sarah11918 commented on src/content/docs/en/reference/integrations-reference.mdx
> +For example, the astro config [`serverIslandDynamicBase`](https://github.com/withastro/astro/blob/30d720f519f991720ee0b7c328a4bf4bbf31760d/packages/astro/src/types/public/config.ts#L1979-L1986)
Heads up that we do not typically link to code outside of docs. Everything in docs should be fully explained so people don't have to leave the page. A full example would have to be provided here.

2024-11-27 20:58 UTC, sarah11918 requested changes
Just putting a block on this PR so it doesn't accidentally get merged as this feature will not be released before v5.

2024-12-03 11:19 UTC, closed without merging

2024-12-03 11:57 UTC, sarah11918 commented
Ooh, it's letting me reopen... let me try this

2024-12-04 17:02 UTC, Jacob-Roberts commented
Thanks @sarah11918! I'll submit a new PR