I18n(fr) : Update `guides/cms/*` from #9240
withastro/docs pull request #10191
Opened 2024-12-04 15:36 UTC by thomasbnt

#### Description (required)
 Update `guides/cms/*` from #9240

#### Related issues & labels (optional)

- Suggested label: i18n

2024-12-04 15:37 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| File                                                                                                                                                                                | Note                                               |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [fr/guides/cms/apostrophecms.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fapostrophecms.mdx)     | Localization changed, will be marked as complete.  |
| [fr/guides/cms/builderio.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fbuilderio.mdx)             | Localization changed, will be marked as complete.  |
| [fr/guides/cms/buttercms.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fbuttercms.mdx)             | Localization changed, will be marked as complete.  |
| [fr/guides/cms/caisy.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fcaisy.mdx)                     | Localization changed, will be marked as complete.  |
| [fr/guides/cms/cloudcannon.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fcloudcannon.mdx)         | Localization changed, will be marked as complete.  |
| [fr/guides/cms/contentful.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fcontentful.mdx)           | Localization changed, will be marked as complete.  |
| [fr/guides/cms/cosmic.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fcosmic.mdx)                   | Localization changed, will be marked as complete.  |
| [fr/guides/cms/craft-cms.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fcraft-cms.mdx)             | Localization changed, will be marked as complete.  |
| [fr/guides/cms/crystallize.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fcrystallize.mdx)         | Localization changed, will be marked as complete.  |
| [fr/guides/cms/datocms.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fdatocms.mdx)                 | Localization changed, will be marked as complete.  |
| [fr/guides/cms/decap-cms.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fdecap-cms.mdx)             | Localization changed, will be marked as complete.  |
| [fr/guides/cms/directus.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fdirectus.mdx)               | Localization changed, will be marked as complete.  |
| [fr/guides/cms/drupal.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fdrupal.mdx)                   | Localization changed, will be marked as complete.  |
| [fr/guides/cms/flotiq.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fflotiq.mdx)                   | Localization changed, will be marked as complete.  |
| [fr/guides/cms/frontmatter-cms.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Ffrontmatter-cms.mdx) | Localization changed, will be marked as complete.  |
| [fr/guides/cms/ghost.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fghost.mdx)                     | Localization changed, will be marked as complete.  |
| [fr/guides/cms/hashnode.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fhashnode.mdx)               | Localization changed, will be marked as complete.  |
| [fr/guides/cms/hygraph.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fhygraph.mdx)                 | Localization changed, will be marked as complete.  |
| [fr/guides/cms/index.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Findex.mdx)                     | Localization changed, will be marked as complete.  |
| [fr/guides/cms/keystatic.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fkeystatic.mdx)             | Localization changed, will be marked as complete.  |
| [fr/guides/cms/keystonejs.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fkeystonejs.mdx)           | Localization changed, will be marked as complete.  |
| [fr/guides/cms/kontent-ai.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fkontent-ai.mdx)           | Localization changed, will be marked as complete.  |
| [fr/guides/cms/microcms.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fmicrocms.mdx)               | Localization changed, will be marked as complete.  |
| [fr/guides/cms/payload.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fpayload.mdx)                 | Localization changed, will be marked as complete.  |
| [fr/guides/cms/preprcms.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fpreprcms.mdx)               | Localization changed, will be marked as complete.  |
| [fr/guides/cms/prismic.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fprismic.mdx)                 | Localization changed, will be marked as complete.  |
| [fr/guides/cms/sanity.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fsanity.mdx)                   | Localization changed, will be marked as complete.  |
| [fr/guides/cms/sitecore.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fcms%2Fsitecore.mdx)               | Localization changed, will be marked as complete.  |
| [fr/guides/cms/spinal.mdx](https://github.com/withastro/docs/blob/042b89d96d57572c52561d9315ae0141ed98fcaf/src%2Fcontent%2 [...]

2024-12-04 16:11 UTC, ArmandPhilippot requested changes
Two broken links, but after that it looks good!

2024-12-04 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/cms/keystatic.mdx
> +Si vous utilisez déjà [content collections](/fr/guides/content-collections) dans votre projet Astro, mettez à jour le schéma ci-dessus pour qu'il corresponde exactement à la (aux) collection(s) défin
fix:
```suggestion
Si vous utilisez déjà [content collections](/fr/guides/content-collections/) dans votre projet Astro, mettez à jour le schéma ci-dessus pour qu'il corresponde exactement à la (aux) collection(s) définie(s) dans votre schéma existant.
```

2024-12-04 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/cms/keystatic.mdx
> +Pour afficher le contenu d'un article individuel, vous pouvez importer et utiliser le composant `<Content />` pour [rendre votre contenu en HTML](/fr/guides/content-collections/#rendre-le-contenu-du-
We should keep the previous anchor in the meantime:
```suggestion
Pour afficher le contenu d'un article individuel, vous pouvez importer et utiliser le composant `<Content />` pour [rendre votre contenu en HTML](/fr/guides/content-collections/#rendre-le-contenu-en-html) :
```
(I updated the section in #10145 and the anchor will be `restitution-du-contenu` but with the broken links... I guess this PR will be merged later)

2024-12-04 16:36 UTC, ArmandPhilippot approved these changes
LGTM!

2024-12-05 20:26 UTC, yanthomasdev approved these changes
Nice work, LGTM!

2024-12-05 20:26 UTC, merged