i18n(ja) update banners
withastro/docs pull request #10272
Opened 2024-12-07 17:28 UTC by hayatosc

#### Description (required)

banners on `getting-started.mdx` and `upgrade-astro.mdx` was updated on #9240 , but ja version doesn't follow it.

This PR resolve this problem.

- Closes #
- Suggested label:

2024-12-07 17:29 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| File                                                                                                                                                      | Note                                               |
| --------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [ja/getting-started.mdx](https://github.com/withastro/docs/blob/2c4a6e867eb31f61dcc193853b0d224d70ecc717/src%2Fcontent%2Fdocs%2Fja%2Fgetting-started.mdx) | Localization changed, will be marked as complete.  |
| [ja/upgrade-astro.mdx](https://github.com/withastro/docs/blob/2c4a6e867eb31f61dcc193853b0d224d70ecc717/src%2Fcontent%2Fdocs%2Fja%2Fupgrade-astro.mdx)     | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-12-07 17:29 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🥳.

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-12-07 22:45 UTC, staticWagomU requested changes
`src/content/docs/en/`以下で検索を掛けたところ、こちらにもバナーを追加する必要がありそうです。→https://github.com/withastro/docs/blob/main/src/content/docs/ja/install-and-setup.mdx

2024-12-09 00:04 UTC, hayatosc commented
@staticWagomU `install-and-setip.mdx`のほうも修正しました。再度ご確認お願いします。

2024-12-09 05:42 UTC, SnowDingo approved these changes
@hayatosc さん、翻訳ありがとうございます。
一通り変更を確認しましたが、特に問題点はなさそうです。また、install-and-setup.mdxに行った変更も確認しておきました。
問題は無いので承認しておきます。ありがとうございました。

2024-12-09 08:55 UTC, staticWagomU approved these changes
ありがとうございます！！！
LGTMです！！！！！

2024-12-09 15:21 UTC, merged