i18n(fr) Up and Add french translation for `upgrade-astro.mdx` and `v5.mdx`
withastro/docs pull request #10314
Opened 2024-12-09 14:16 UTC by McFlyPartages

#### Description (required)
Tranlation for french doc

Update `upgrade-astro` file and add `v5` astro file

2024-12-09 14:17 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| File                                                                                                                                                                    | Note                                               |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [fr/guides/upgrade-to/v5.mdx](https://github.com/withastro/docs/blob/f557bb2f851096b04da6f3b1370b17fdd0270e4b/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fupgrade-to%2Fv5.mdx) | Localization added, will be marked as complete.    |
| [fr/upgrade-astro.mdx](https://github.com/withastro/docs/blob/f557bb2f851096b04da6f3b1370b17fdd0270e4b/src%2Fcontent%2Fdocs%2Ffr%2Fupgrade-astro.mdx)                   | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-12-09 16:11 UTC, ArmandPhilippot requested changes
Thanks for tackling this big file! I suggested some changes:
* mostly nitpicks (missing space, double dot...)
* some untranslated strings
* some malformed inline codes
* some malformed links

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +<ReadMore>En savoir plus sur [TypeScript configuration in Astro](/fr/guides/typescript/#configuration).</ReadMore>
```suggestion
<ReadMore>En savoir plus sur la [configuration de TypeScript dans Astro](/fr/guides/typescript/#configuration).</ReadMore>
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Si l'action de votre formulaire HTML est dirigée vers une route différente (c'est-à-dire `action={« /success-page » + actions.name}`), Astro ne redirigera plus vers la route précédente en cas d'erreu
```suggestion
Si l'action de votre formulaire HTML est dirigée vers une route différente (c'est-à-dire `action={"/success-page" + actions.name}`), Astro ne redirigera plus vers la route précédente en cas d'erreur. Vous pouvez implémenter ce comportement manuellement en utilisant les redirections de votre composant Astro. Cet exemple redirige plutôt vers une nouvelle route en cas de succès, et gère les erreurs sur la page courante dans le cas contraire :
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Pour résoudre le problème de la boîte de dialogue « Confirmation de la resoumission du formulaire ? » lors de l'actualisation, ou pour conserver les résultats des actions entre les sessions, vous pou
```suggestion
Pour résoudre le problème de la boîte de dialogue « Confirmation de la resoumission du formulaire ? » lors de l'actualisation, ou pour conserver les résultats des actions entre les sessions, vous pouvez désormais [personnaliser la gestion des résultats des actions à partir d'un middleware](/fr/guides/actions/#avancé-persistance-des-résultats-daction-avec-une-session).
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Astro v5.0 les renomme respectivement en `--astro-code-foreground` et `--astro-code-background` pour mieux s'aligner sur les valeurs par défaut de Shiki v1..
```suggestion
Astro v5.0 les renomme respectivement en `--astro-code-foreground` et `--astro-code-background` pour mieux s'aligner sur les valeurs par défaut de Shiki v1.
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Astro 5.0 met à jour ce comportement en ajoutant la balise `<meta charset=« utf-8 »>` à la place, et seulement pour les pages qui n'utilisent pas la propriété spéciale `layout` dans le frontmatter d'
```suggestion
Astro 5.0 met à jour ce comportement en ajoutant la balise `<meta charset="utf-8">` à la place, et seulement pour les pages qui n'utilisent pas la propriété spéciale `layout` dans le frontmatter d'Astro. De même pour les pages MDX, Astro n'ajoutera la balise que si le contenu MDX n'importe pas un composant `Layout`.
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Si vos pages Markdown ou MDX utilisent la propriété `layout` dans le frontmatter, ou si le contenu de la page MDX importe un composant `Layout`, alors l'encodage HTML sera géré par le composant layou
```suggestion
Si vos pages Markdown ou MDX utilisent la propriété `layout` dans le frontmatter, ou si le contenu de la page MDX importe un composant `Layout`, alors l'encodage HTML sera géré par le composant layout désigné à la place, et la balise `<meta charset="utf-8">` ne sera pas ajoutée à votre page par défaut.
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Si vous avez besoin de `charset=utf-8` pour rendre votre page correctement, assurez-vous que vos composants de mise en page contiennent la balise `<meta charset=« utf-8 »>`. Vous devrez peut-être l'a
```suggestion
Si vous avez besoin de `charset=utf-8` pour rendre votre page correctement, assurez-vous que vos composants de mise en page contiennent la balise `<meta charset="utf-8">`. Vous devrez peut-être l'ajouter si vous ne l'avez pas encore fait.
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +### Changed: URLs returned by `paginate()`
```suggestion
### Modifié : les URL renvoyées par `paginate()`
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Astro v5.0 rend les valeurs explicites comme `=« true »` ou `=« false »`, ce qui correspond à la gestion correcte des attributs dans les navigateurs.
```suggestion
Astro v5.0 rend les valeurs explicites comme `="true"` ou `="false"`, ce qui correspond à la gestion correcte des attributs dans les navigateurs.
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +<ReadMore>Voir la [Référence API pour `IntegrationRouteData`](/fr/reference/integrations-reference/#référence-du-type-integrationroutedata).</ReadMore>
```suggestion
<ReadMore>Voir la [référence de l'API pour `IntegrationRouteData`](/fr/reference/integrations-reference/#référence-du-type-integrationroutedata).</ReadMore>
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +<ReadMore>Voir la [Référence API pour `IntegrationRouteData`](/fr/reference/integrations-reference/#référence-du-type-integrationroutedata).</ReadMore>
```suggestion
<ReadMore>Voir la [référence de l'API pour `IntegrationRouteData`](/fr/reference/integrations-reference/#référence-du-type-integrationroutedata).</ReadMore>
```

2024-12-09 16:11 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +## Community Resources
```suggestion
## Ressources communautaires
```

2024-12-09 16:12 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Dans Astro v4.x, les attributs HTML non [booléens] (https://developer.mozilla.org/fr-FR/docs/Glossary/Boolean/HTML) pouvaient ne pas inclure leurs valeurs lorsqu'ils étaient rendus en HTML.
Oh good catch, I missed that one!

2024-12-10 16:27 UTC, McFlyPartages commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Consultez le changelog d'Astro](https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md) pour les notes de version complètes.
Thanks i see

2024-12-10 16:30 UTC, McFlyPartages commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Consultez le changelog d'Astro](https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md) pour les notes de version complètes.
Thanks to you for the review, it takes as long as translating hahaha

2024-12-10 16:57 UTC, ArmandPhilippot requested changes
This should fix the broken links!

2024-12-10 16:57 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Si vous ne pouvez apporter aucune modification à vos collections pour le moment, vous pouvez [activer l'option `legacy.collections`](#activation-de-l-option-legacy.collections) qui vous permettra de
```suggestion
Si vous ne pouvez apporter aucune modification à vos collections pour le moment, vous pouvez [activer l'option `legacy.collections`](#activation-de-loption-legacycollections) qui vous permettra de conserver vos collections dans leur état actuel jusqu'à ce que le drapeau hérité ne soit plus pris en charge.
```

2024-12-10 16:57 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/integrations-reference.mdx
> +Cette propriété est obsolète depuis la version 5.0. Consultez le [guide de migration](/fr/guides/upgrade-to/v5/#déprécié-routes-sur-le-hook-astrobuilddoneapi-dintégration).
```suggestion
Cette propriété est obsolète depuis la version 5.0. Consultez le [guide de migration](/fr/guides/upgrade-to/v5/#déprécié--routes-sur-le-hook-astrobuilddoneapi-dintégration).
```

2024-12-11 07:24 UTC, McFlyPartages commented
Hey thanks for your review. It's good now 

Thanks Thanks Thanks and good job

2024-12-11 13:23 UTC, thomasbnt approved these changes
LGTM!

2024-12-11 13:35 UTC, ArmandPhilippot approved these changes
Two tiny nits, otherwise LGTM!

2024-12-11 13:35 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Si votre projet inclut des fichiers .mdx, vous devez mettre à jour @astrojs/mdx vers la dernière version (v4.0.0) afin que votre JSX soit correctement géré par l'intégration.
nit:
```suggestion
Si votre projet inclut des fichiers `.mdx`, vous devez mettre à jour @astrojs/mdx vers la dernière version (v4.0.0) afin que votre JSX soit correctement géré par l'intégration.
```

2024-12-11 13:35 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +Voir les instructions ci-dessous pour mettre à jour une collection de contenu existante (`type : 'content'` ou `type : 'data'`) afin d'utiliser l'API de la couche de contenu.
nit, inline code no space before colon:
```suggestion
Voir les instructions ci-dessous pour mettre à jour une collection de contenu existante (`type: 'content'` ou `type: 'data'`) afin d'utiliser l'API de la couche de contenu.
```

2024-12-11 21:56 UTC, ArmandPhilippot approved these changes
LGTM!

2024-12-11 22:06 UTC, thomasbnt requested changes
Miss one link #importmetaglob and LGTM!

2024-12-11 22:06 UTC, thomasbnt commented on src/content/docs/fr/guides/upgrade-to/v5.mdx
> +<ReadMore>En savoir plus sur [l'importation de fichiers avec `import.meta.glob`](/fr/guides/imports/#astroglob).</ReadMore>
```suggestion
<ReadMore>En savoir plus sur [l'importation de fichiers avec `import.meta.glob`](/fr/guides/imports/#importmetaglob).</ReadMore>
```

2024-12-11 22:07 UTC, thomasbnt approved these changes
LGTM!

2024-12-11 22:33 UTC, merged