i18n(fr): update all the `migrate-to` guides
withastro/docs pull request #10331
Opened 2024-12-10 17:49 UTC by ArmandPhilippot

#### Description (required)

Adds changes from #9240 to the French translation of `migrate-to` guides.

> [!NOTE]
> I haven't updated some links to avoid broken links:
> * those targeting `api-reference.mdx` 
> * those targeting `install-and-setup.mdx`
>
> I think it's better to do it while updating these files, but I can update them here if needed...

#### Related issues & labels (optional)

- Suggested label: i18n

2024-12-10 18:17 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/migrate-to-astro/from-create-react-app.mdx
> +En savoir plus sur l'importation de fichiers locaux avec [`import.meta.glob()`](/en/guides/imports/#importmetaglob), [l'interrogation à l'aide de l'API Collections](/fr/guides/content-collections/#in
Wrong locale...
```suggestion
En savoir plus sur l'importation de fichiers locaux avec [`import.meta.glob()`](/fr/guides/imports/#importmetaglob), [l'interrogation à l'aide de l'API Collections](/fr/guides/content-collections/#interroger-les-collections) ou [la récupération de données distantes](/fr/guides/data-fetching/).
```

2024-12-10 19:02 UTC, thomasbnt requested changes
Bold text is missing

2024-12-10 20:49 UTC, ArmandPhilippot commented
@thomasbnt I also added the changes from #10332 which is not yet merged! This will avoid having to re-edit these files... So check if the other one is merged before this one. 😅

2024-12-10 21:03 UTC, thomasbnt commented
> @thomasbnt I also added the changes from #10332 which is not yet merged! This will avoid having to re-edit these files... So check if the other one is merged before this one. 😅
> 
> Edit: all good, this is merged! 😄

Oh good!

2024-12-11 13:41 UTC, thomasbnt approved these changes
LGTM! Thanks @ArmandPhilippot for your contribution!

2024-12-11 13:41 UTC, merged