i18n(fr): update `guides/typescript.mdx`
withastro/docs pull request #10366
Opened 2024-12-13 21:22 UTC by ArmandPhilippot

#### Description (required)

Updates the French translation of `guides/typescript.mdx`:
* add changes from #9240, #10148 and #10197
* fix some inline codes (no space before colon)

#### Related issues & labels (optional)

- Suggested label: i18n

2024-12-13 21:23 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| File                                                                                                                                                            | Note                                               |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [fr/guides/typescript.mdx](https://github.com/withastro/docs/blob/fd8cf0c12c2f74c6016885fc87709c43a4c58b4d/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Ftypescript.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-12-14 14:40 UTC, thomasbnt requested changes
Miss one translation, LGTM for the rest!

2024-12-14 14:40 UTC, thomasbnt commented on src/content/docs/fr/guides/typescript.mdx
> +// Astro types, not necessary if you already have a tsconfig.json
```suggestion
// Types d'Astro, non nécessaire si vous avez déjà un tsconfig.json
```

2024-12-14 14:45 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/typescript.mdx
> +// Custom types declarations
This one too to be consistent:
```suggestion
Déclarations de types personnalisés
```

2024-12-14 14:46 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/typescript.mdx
> +Déclarations de types personnalisés
Sorry, too quick... 😅 
```suggestion
// Déclarations de types personnalisés
```

2024-12-14 15:31 UTC, thomasbnt approved these changes
LGTM!

2024-12-14 15:33 UTC, merged