i18n(zh-cn): Update `configuration-reference.mdx`
withastro/docs pull request #10401
Opened 2024-12-17 02:22 UTC by liruifengv

#### Description (required)

Update `configuration-reference.mdx`

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/9240

2024-12-17 02:22 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| File                                                                                                                                                                                                  | Note                                               |
| ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [zh-cn/reference/configuration-reference.mdx](https://github.com/withastro/docs/blob/3ca19f28b4e67acaef4d7d105eb0dff7a5e44331/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Fconfiguration-reference.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-12-17 06:34 UTC, liruifengv commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +- `static`- 默认预渲染你的所有页面，如果没有页面选择退出预渲染的话，将输出一个完全静态的站点。
```suggestion
- `static` - 默认预渲染你的所有页面，如果没有页面选择退出预渲染的话，将输出一个完全静态的站点。
```

2024-12-18 02:16 UTC, Nin3lee requested changes

2024-12-18 02:16 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
>  **类型**：`string`<br />
```suggestion
**类型：**`string`<br />
```

2024-12-18 02:16 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +**默认值**：`'./client'`
```suggestion
**默认值：**`'./client'`
```

2024-12-18 02:16 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
>  **类型**：`string`<br />
```suggestion
**类型：**`string`<br />
```

2024-12-18 02:16 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +**默认值**：`'./server'`
```suggestion
**默认值：**`'./server'`
```

2024-12-18 02:16 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
- [第796行](https://github.com/withastro/docs/pull/10401/files#diff-f004fc3d5617d91ddb493d5066491dccbdd7bce550f7610468ee8be511dfd78eR796)的 `<ViewTransitions />` 也被替换成 `<ClientRouter />` 了。
- [第1091行](https://github.com/withastro/docs/pull/10401/files#diff-f004fc3d5617d91ddb493d5066491dccbdd7bce550f7610468ee8be511dfd78eR1091)有一个缩进的[修改](https://github.com/withastro/docs/pull/9240/files#diff-6b0ed61bf17daf5f370edd2d5a46be46cb8ef5321ac7537a17e71236f0c9028bR1101)。

2024-12-18 02:59 UTC, liruifengv commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
那个缩进我觉得不用修改

2024-12-18 06:25 UTC, Nin3lee approved these changes
LGTM! Amazing work!

2024-12-18 07:10 UTC, merged