i18n(zh-cn): Update some integrations guides
withastro/docs pull request #10431
Opened 2024-12-18 03:21 UTC by liruifengv

#### Description (required)

Update some integrations guides

#### Related issues & labels (optional)

- #9240

2024-12-18 03:22 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| File                                                                                                                                                                                                          | Note                                               |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| [zh-cn/guides/integrations-guide/alpinejs.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Falpinejs.mdx)     | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/cloudflare.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fcloudflare.mdx) | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/db.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fdb.mdx)                 | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/deno.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fdeno.mdx)             | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/index.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Findex.mdx)           | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/mdx.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fmdx.mdx)               | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/netlify.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fnetlify.mdx)       | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/node.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fnode.mdx)             | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/partytown.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fpartytown.mdx)   | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/preact.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fpreact.mdx)         | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/prefetch.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fprefetch.mdx)     | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/react.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Freact.mdx)           | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/sitemap.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fsitemap.mdx)       | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/solid-js.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fsolid-js.mdx)     | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/svelte.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fsvelte.mdx)         | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/tailwind.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Ftailwind.mdx)     | Localization changed, will be marked as complete.  |
| [zh-cn/guides/integrations-guide/vue.mdx](https://github.com/withastro/docs/blob/f12b5cd5a1ce583f2571cab3cf1c623459954a76/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Fintegrations-guide%2Fvue.mdx)               | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-12-18 06:57 UTC, Nin3lee requested changes

2024-12-18 06:57 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
`integrations-guide/mdx.mdx` 落后了几次 commit：
- #10187
- #10312
- #10344

2024-12-18 09:27 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
MDX 页面有关联的 broken link，不放在这次更新里了，我还原了

2024-12-19 01:36 UTC, Nin3lee approved these changes
LGTM!

2024-12-19 03:17 UTC, merged