I18n(zh-cn): page guide images
withastro/docs pull request #1285
Opened 2022-08-13 19:16 UTC by KyomuAoi

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

This PR adds translation of Guides/Image in Simplified Chinese.

2022-08-16 06:49 UTC, delucis commented
Thanks so much for this PR @KyomuAoi! I’ve asked our other translators to take a look so we can get you some feedback.

If you use Discord, we would be happy to have you join us in our #docs-i18n channel where we have dedicated threads for all languages and translators can discuss: https://astro.build/chat

2022-08-16 07:25 UTC, kecrily requested changes

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +在 Astro 项目中，你有许多方法把图片放上自己的网站。无论是用项目中的图片文件、是链接到别处的图片，还是从像 CMS（内容管理系统）或 CDN（内容分发网络）这样的地方加载，都没问题！
```suggestion
在 Astro 项目中，有很多种在网站中使用图片的方式。无论是用存储在项目中的图片，还是链接外部图片，亦或从像 CMS（内容管理系统）或 CDN（内容分发网络）这样的地方加载图片，都没问题！
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +<!-- 存放在项目中 public/assets/stars.png 路径的图片 -->
```suggestion
<!-- 存储在 public/assets/stars.png 的本地图片 -->
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +除了官方的 [`@astrojs/image`](/zh-cn/guides/integrations-guide/image/) 集成，还有着一些[社区开发的用于图片的集成](https://astro.build/integrations/css+ui/?q=image)，也能用于在你的 Astro 项目中处理和优化图片。
```suggestion
除了官方的 [`@astrojs/image`](/zh-cn/guides/integrations-guide/image/) 集成外，社区还开发了[一些用于图片的集成](https://astro.build/integrations/css+ui/?q=image)，它们能够帮你处理并优化 Astro 项目中的图片。
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +Astro 与 CMS 或 CDN 等协作流畅。通过 `<img>` 的话，只需将 URL 用作图片的 `src` 属性即可，就像你写 HTML 或者 JSX 时一样。若是使用 Astro 的「图片」集成，即 `<Image />` 组件与 `<Picture />` 组件，就按远端图片的方式，将 URL 作为 `src` 属性填入。
```suggestion
Astro 与图片 CDN 可以无缝集成。就像写 HTML 或者 JSX 一样，只需将图片链接用作  `<img>` 的 `src` 属性即可。若使用 `<Image />` 组件与 `<Picture />` 组件，则是将原创链接填入 `src` 属性。
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +#### 位于远端的图片
```suggestion
#### 远程图片
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +存放在 `src` 文件夹中的本地图片可以在主页中导入并用在 `<Picture />` 组件。`<Picture />` 组件的 `src`，`widths` 和 `sizes` 属性都必须设定。
```suggestion
可以在 frontmatter 中导入存储在 `src` 文件夹中的本地图片，并将其用于 `<Picture />` 组件。但 `<Picture />` 组件的 `src`，`widths` 和 `sizes` 属性不能为空。
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +`<Picture />` 组件默认会在图片的原始格式之外，再包括 `avif` 和 `webp` 两种格式。
```suggestion
除图片原始格式外，`<Picture />` 组件还会生成 `avif` 和 `webp` 两种格式的图片。
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +// 若为本地图片则可以 inline 导入
```suggestion
// 若为本地图片则可以在行内导入
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +// 请注意，仅当加载本地图片时，「基于原始图片的长宽比」计算方法才适用。
```suggestion
// 请注意，仅当加载本地图片时，”基于原始图片的长宽比“计算方法才适用。
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +### 作为 UI 框架中的组件
```suggestion
### UI 框架中的组件
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +以符合需要的恰当语法，将图片添加为 [UI 框架中的组件](/zh-cn/core-concepts/framework-components/) （例如在 React 或 Svelte 中）。
```suggestion
需要与之对应的语法将图片转化为 [UI 框架中的组件](/zh-cn/core-concepts/framework-components/) （例如在 React 或 Svelte 中）。
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +![Astro 的 logo](https://astro.build/assets/logo.png)
```suggestion
![Astro 的图标](https://astro.build/assets/logo.png)
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +在 `src/` 下存放的图片需要先以**相对路径**或[别名](/zh-cn/guides/aliases/)导入，然后通过图片的 `src` 属性来引用。
```suggestion

在 `src/` 下存放的图片需要先以**相对路径**或[别名](/zh-cn/guides/aliases/)导入，然后通过图片的 `src` 属性来引用。 
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +<img src={logo} width="40" alt="Astro 的 logo" />
```suggestion
<img src={logo} width="40" alt="Astro 的图标" />
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +Astro 项目树中的 [`public/` 目录](/zh-cn/core-concepts/project-structure/#public) 为无需在 Astro 构建过程中处理的文件与资源设置，存放于其中的图片将会被原样拷贝到构建出的文件夹中。请注意，这些图片不以导入到你的 `.astro` 文件中的方式使用（即，应直接以相对路径方式使用），且它们的 `src` 属性应填写为**对于
```suggestion
Astro 项目树中的 [`public/` 目录](/zh-cn/core-concepts/project-structure/#public) 为无需在 Astro 构建过程中处理的文件与资源设置，存放于其中的图片将会被原样拷贝到构建出的文件夹中。请注意，这些图片不以导入到你的 `.astro` 文件中的方式使用（即，应直接以相对路径方式使用），且它们的 `src` 属性应填写为**基于 public/ 目录的相对路径**。
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +[「图片」集成指南](/zh-cn/guides/integrations-guide/image/)中有更多关于这个崭新的实验性功能的内容。
```suggestion
[图片集成指南](/zh-cn/guides/integrations-guide/image/)中有更多关于这个崭新的实验性功能的内容。
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +## Astro 的「图片」集成（Astro's Image Integration）
```suggestion
## Astro 的图片集成
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +Astro 的 [`<Image />` 组件](/zh-cn/guides/integrations-guide/image/#image-) 使你可以优化图片，并指定宽度、长度和/或长宽比。它甚至能协助你将图片转为某一特定格式，使你无需专门处理不同类型的图片。
```suggestion
Astro 的 [`<Image />` 组件](/zh-cn/guides/integrations-guide/image/#image-) 可以帮助帮你优化图片，并指定宽度、长度和/或长宽比。它甚至能协助你将图片转为某一特定格式，使你无需专门处理不同类型的图片。
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +#### 存放在本地的图片
```suggestion
#### 本地图片
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +#### 位于远端的图片
```suggestion
#### 远程图片
```

2022-08-16 07:25 UTC, kecrily commented on src/pages/zh-cn/guides/images.md
> +使用位于远端的图片时，`<Image />` 的 `src` 属性需要一个完整的 URL。除此之外，你还需要：同时提供 `width` 和 `height` 属性，或同时提供以上二者之一和 `aspectRatio` 属性。
```suggestion
使用位于远端的图片时，`<Image />` 的 `src` 属性需要一个完整的链接。除此之外，你还需要：同时提供 `width` 和 `height` 属性，或同时提供以上二者之一和 `aspectRatio` 属性。
```

2022-08-16 07:36 UTC, kecrily commented
There are a few points that may need attention:

- The translation of frontmatter to 主页 is a complete mistranslation. It is a proprietary term and there is no common translation for it in Chinese
- Words such as URL(链接) and logo(图标) should be translated to noon if possible when there is a Chinese equivalent for them.
- Instead of using square quotes(“”), curved quotes(「」) are generally used in Simplified Chinese. (Although many people use square quotes for typographic beauty, including myself, this is a translation, so let's use the standard curved quotation marks)
- Respect the original text as much as possible as well as short translations (e.g. where quotation marks are not used in the original text, do not add new quotation marks if you do not really have to use them)

2022-08-16 20:24 UTC, KyomuAoi commented
Thanks for your respectable work @kecrily ! It's really a useful lesson : )
I'd like to immediately merge most of your changes, but the translation of "Astro's Image Integration" still makes me torn since I first considered it.
While the text "Astro 的图片集成" is really good—plain and simple, in my opinion it might cause a misunderstanding that the text means "The Integration (which is a process or action, rather than something like a plugin or component) of Images in Astro".
I comes from backend field and am only familiar with "module", "package" or so, so the confusion about "integration"/"集成" might not be a common situation among Astro's users? I'm not sure.
Please let me know your idea.(And sorry for my poor English.)

2022-08-16 21:24 UTC, delucis commented
Thank you so much for your care @KyomuAoi! ❤️ 

I’ll let @kecrily reply, but if you use Discord, you’re very welcome to also join us at https://astro.build/chat where we have a dedicated `#i18n-gang-zh` thread to discuss as well (and you can chat in Chinese if it’s easier too!)

2022-08-17 02:57 UTC, kecrily commented
Considering that there is context, and its frequent occurrence in the documentation. I don't think integration is hard to understand.

Also, considering that 集成 acts as a noun component in the utterance rather than a verb component, it should not be easily misinterpreted as a process. (In Chinese, as in English, the verb is usually placed before the noun)

2022-08-17 22:55 UTC, delucis commented
@KyomuAoi Just saw your comment in the commit message!

> There is a little error in https://github.com/withastro/docs/pull/1285#discussion_r946422587 that says "……可以帮助帮你优化……".
Please make this suggestion again with correct text. Thanks!
(I have little knowledge about GitHub so please tell me if there is a better way to do so.)

@kecrily Do you have a suggestion? Otherwise, @KyomuAoi you can also add your own suggestion in the comment box below the existing suggestion:

<img width="821" alt="image" src="https://user-images.githubusercontent.com/357379/185257621-fb7a8c09-cdb3-428a-addc-ba85d8ae34b3.png">

2022-08-18 03:03 UTC, kecrily commented
I typed wrongly. I will modify

2022-08-18 03:03 UTC, kecrily commented
I typed wrongly. I will modify

2022-08-18 17:08 UTC, delucis approved these changes
Thanks so much for the contribution @KyomuAoi! Great team work with @kecrily ❤️ 

Really appreciate the care you both put into this 🙌

2022-08-18 17:08 UTC, merged