Update configuration-reference.md
withastro/docs pull request #131
Opened 2022-02-14 22:07 UTC by leoj3n

Add more info about draft pages, and other default values.

2022-02-17 13:11 UTC, jonathantneal commented on src/pages/en/reference/configuration-reference.md
> +- `buildOptions.site`: Used to generate sitemaps and canonical URLs.
I like this. Would this voicing update be acceptable?
```suggestion
- `buildOptions.site`: Public [origin](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Origin) used to generate sitemaps and canonical URLs.
```

2022-02-17 13:12 UTC, jonathantneal commented on src/pages/en/reference/configuration-reference.md
> +- `buildOptions.sitemap`: Generate an automatically-generated sitemap for your build.
Voicing suggestion.
```suggestion
- `buildOptions.sitemap`: Whether to automatically generate a sitemap.
```

2022-02-17 13:14 UTC, jonathantneal commented on src/pages/en/reference/configuration-reference.md
> +- `buildOptions.pageUrlFormat`: Control the output file URL format of each page.
```suggestion
- `buildOptions.pageUrlFormat`: Determines how files built from pages are written.
```

2022-02-17 13:14 UTC, jonathantneal commented on src/pages/en/reference/configuration-reference.md
> +- `buildOptions.drafts`: Control if markdown draft pages should be included in the build.
```suggestion
- `buildOptions.drafts`: Determines whether markdown draft pages are included in the build.
```

2022-02-17 13:14 UTC, jonathantneal commented on src/pages/en/reference/configuration-reference.md
> +Read more about [markdown draft pages][markdown-draft-pages].
❤️

2022-02-17 13:17 UTC, jonathantneal requested changes
This is another helpful addition. Thank you, @leoj3n.

I’ve left some suggestions to change how a few lines are written for your consideration. I’m happy to work with you on these, if you feel there’s more to be done. Would you please take a look?

2022-03-01 20:13 UTC, FredKSchott commented
Thanks @leoj3n! This is a nice improvement over what we have 👍 

If you're interested in contributing more, the rough plan is to start auto-generating a lot of this page contents from the codebase itself. I'd love your help in https://github.com/withastro/docs/pull/172 if you're interested.

2022-03-01 20:13 UTC, merged