docs(zh-CN): :memo: update ui translations
withastro/docs pull request #1320
Opened 2022-08-16 19:47 UTC by Byacrya

Update UI translations (navbar, ui, and docsearch bar)

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content
- Translated content

#### Description

Update some of the UI translations.

2022-08-16 21:30 UTC, delucis requested changes
Hi @Byacrya — thanks for opening a PR for the Astro Docs!

I’ll let some of our other Chinese translators give feedback on the language here but I’ve left a few notes on the format of the `nav.ts` and `ui.ts` files.

If you like, please do also join our Discord server at https://astro.build/chat — we have a dedicated translation channel and a `i18n-gang-zh` thread for our Chinese translators to chat in.

2022-08-16 21:30 UTC, delucis commented on src/i18n/zh-cn/nav.ts
> -export default NavDictionary({
We do want to keep using the `NavDictionary` function like this — it helps us check all the entries match up with the English navigation menu. Also means you don’t need all the `slug`, `key`,  etc. just the translation as this file had it before.

2022-08-16 21:30 UTC, delucis commented on src/i18n/zh-cn/ui.ts
> -export default UIDictionary({
Same here! `UIDictionary` makes sure we don’t accidentally write `site.descripton` instead of `site.description` for example.

2022-08-17 07:49 UTC, kecrily requested changes
The last point is that in the rest of the document we use you(你) instead of you with respect(您), please stick to this point.

2022-08-17 07:49 UTC, kecrily commented on src/i18n/zh-cn/ui.ts
> +	'leftSidebar.a11yTitle': '主要内容',
```suggestion
	'leftSidebar.a11yTitle': '站点导航',
```

This is a contextualization. Combined with the accessibility feature tree, we may see that it is not the main content(主要内容), but the navigation (站点导航).

![image](https://user-images.githubusercontent.com/45708948/185060952-807188cc-cefa-4f18-9d5a-5e8bfa1c2a1e.png)

2022-08-17 07:49 UTC, kecrily commented on src/i18n/zh-cn/ui.ts
> +	'themeToggle.useDark': '使用暗色主题',
This is entirely a difference caused by personal preference, and there is nothing wrong with the original translation.

2022-08-17 07:49 UTC, kecrily commented on src/i18n/zh-cn/ui.ts
> +	'since.new': '新版本',
This is a badge, so it shouldn't be too long

2022-08-17 07:49 UTC, kecrily commented on src/i18n/zh-cn/ui.ts
> +	'install.manualTab': '手动安装',
The CLI has an accurate translation (命令行) and we should use Chinese whenever possible.

And setup (设置) and installation (安装) do not mean the same thing, so please respect the original text. The setup is something that needs to be done after the installation (`npm install`) is complete.

2022-08-17 07:49 UTC, kecrily commented on src/i18n/zh-cn/ui.ts
> +	'fallbackContent.notice': '此页面尚未被翻译，我们将为您展示未翻译的英文版本。请帮助我们翻译此页！',
```suggestion
	'fallbackContent.notice': '此页面尚未被翻译，我们将为您展示英文版本。请帮助我们翻译此页！',
```
The meaning of the untranslated (未翻译) and English versions (英文版本) is duplicated. People who see this message are definitely not English users, so the English version is the untranslated meaning.

2022-08-17 07:49 UTC, kecrily commented on src/i18n/zh-cn/ui.ts
> +	'404.linkText': '带我回家',
```suggestion
	'404.content': '该页面不在我们的星系中。',
	'404.linkText': '返回主页',
```

Please stick to being as concise and objective as possible without compromising the fluency of your statement. Here, home refers not to home (家), which is an emotional thing, but to the home page of the website.

2022-08-17 07:49 UTC, kecrily commented on src/i18n/zh-cn/ui.ts
> +	'rightSidebar.a11yTitle': '次要内容',
```suggestion
	'rightSidebar.a11yTitle': '目录',
```

Id. 
![image](https://user-images.githubusercontent.com/45708948/185061632-c5961909-d11c-4e91-8af1-0e8349f7cdc9.png)

2022-08-26 23:26 UTC, Yan-Thomas commented
Hello @Byacrya, thanks for this! I'm jumping in after seeing that you have not yet applied nor discussed the suggestions made here, is there something impeding you from continuing this PR? Anything we might be able to help you out with?

2022-09-03 19:22 UTC, delucis commented
I’m going to close this as there hasn’t been any activity. Happy to re-open or for someone else to tackle anything that still needs updating in these files.

2022-09-03 19:22 UTC, closed without merging