Added array example to getStaticPaths()
withastro/docs pull request #137
Opened 2022-02-16 16:46 UTC by lostra01

Added a quick array example to getStaticPaths() for those who want to generate data based on a set of locally available ones, but do not use fetch or other functions to retrieve them.

2022-02-16 17:51 UTC, aFuzzyBear approved these changes
lgtm

2022-02-17 15:13 UTC, jonathantneal requested changes
I would like to add this. Thank you, @lostra01!

I left a small editorial comment. Would you please take a look?

2022-02-17 15:13 UTC, jonathantneal commented on src/pages/en/reference/api-reference.md
> +Alongside of using `await fetch()` you can also pass manually constructed or generated arrays to a `map` function, and let Astro generate all the pages for you, based on the data you have provided.
I like this example. May we shorten this phrase?

```suggestion
You can also pass a regular array, which may be helpful when generating or stubbing a known list of routes.
```

2022-02-17 20:06 UTC, jonathantneal commented on src/pages/en/reference/api-reference.md
> +Alongside of using `await fetch()` you can also pass manually constructed or generated arrays to a `map` function, and let Astro generate all the pages for you, based on the data you have provided.
From discussion:
> Thanks for the edit! Actually makes it more readable! 🙂

Committing the suggestion and merging :)

2022-02-17 20:06 UTC, merged

2022-02-17 20:06 UTC, jonathantneal commented
Merged, @lostra01. 🎉