Create fonts.md
withastro/docs pull request #1384
Opened 2022-08-22 20:13 UTC by EBits00

Added fonts.md French Translation

#### What kind of changes does this PR include?

- Translated content

#### Description

- What does this PR change? Give us a brief description.
 Added fonts.md French Translation

2022-09-03 19:53 UTC, thomasbnt requested changes

2022-09-08 18:11 UTC, delucis commented on src/pages/fr/guides/fonts.md
> +    L'importation ajoutera automatiquement les déclarations `@font-face` nécéssaire pour la police.
```suggestion
    L'importation ajoutera automatiquement les déclarations `@font-face` nécessaires pour la police.
```

2022-09-10 15:12 UTC, Yan-Thomas commented
Thanks for this @EBits00, just a thing: the labels for the pages in the sidebar are inside the language's `nav.ts` file, mind adding the `'guides/fonts'` label to it with the proper translation for "Fonts"? Thank you!

2022-10-01 09:35 UTC, delucis approved these changes
I just added the `nav.ts` entry as Yan requested.

Thanks so much for this addition to the Astro docs @EBits00! Welcome to the team 💜

2022-10-01 09:35 UTC, merged