i18n(es): Update remaining files
withastro/docs pull request #1387
Opened 2022-08-23 00:59 UTC by agustinmulet

#### What kind of changes does this PR include?

- New or updated content

#### Description

Puts the remaining files up to date, in spanish:

- guides/typescript.md
- install/auto.md
- install/manual.md
- integrations/integrations.md
- reference/api-reference.md
- reference/configuration-reference.md

2022-08-23 11:06 UTC, kevinzunigacuellar reviewed
amazing work! I left a few comments 🚀

2022-08-23 12:43 UTC, agustinmulet commented on src/pages/es/guides/deploy.md
> +    - [agregó el adaptador](/es/reference/configuration-reference/#integraciones) a la importación y exportación predeterminada de su archivo `astro.config.mjs`
I'll add this changes but this file needs a complete review, it has some serious redaction issues

2022-08-24 00:34 UTC, fredoist commented on src/pages/es/guides/typescript.md
> +**Solución**: Aún no hay una forma confiable de solucionar este error, sin embargo algunas soluciones y discusiones pueden encontrarse en [esta discusión en GitHub](https://github.com/johnsoncodehk/v
```suggestion
**Solución**: Aún no hay una forma confiable de solucionar este error, sin embargo, algunas soluciones y discusiones pueden encontrarse en [esta discusión en GitHub](https://github.com/johnsoncodehk/volar/discussions/592).
```

2022-08-24 00:49 UTC, fredoist requested changes
Una ultima corrección.

2022-08-24 00:49 UTC, fredoist commented on src/pages/es/reference/api-reference.md
> +- No necesitas cargar cada archivo de inmediatamente. `import.meta.glob()` puede devolver funciones que importan el contenido del archivo, en vez de devolver el contenido en sí.
```suggestion
- No necesitas cargar cada archivo de inmediato. `import.meta.glob()` puede devolver funciones que importan el contenido del archivo, en vez de devolver el contenido en sí.
```

2022-08-24 19:02 UTC, kevinzunigacuellar commented
✅ ready to merge

2022-08-24 19:23 UTC, fredoist approved these changes

2022-08-24 21:28 UTC, Yan-Thomas commented
Good job everyone! I'll merge this PR once you have resolved the merge conflicts and got a final LGTM so I know everything is in place, thank you!

2022-08-24 23:28 UTC, fredoist commented
Great work @agustinmulet 🤝

LGTM ✅

2022-08-24 23:34 UTC, Yan-Thomas commented
Thanks again, everyone! Really an amazing job y'all are doing here 💜

2022-08-24 23:34 UTC, merged