i18n(es): Update deploy.md
withastro/docs pull request #1392
Opened 2022-08-23 14:55 UTC by kevinzunigacuellar

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)

#### Description

- fix typos

2022-08-23 23:59 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +Puedes crear y desplegar tu proyecto de Astro en varios hosts rápidamente utilizando la UI en su página web o la CLI.
```suggestion
Puedes crear y desplegar tu proyecto de Astro en varias plataformas rápidamente utilizando la interfaz de usuario (UI) en su página web o la interfaz de línea de comando (CLI).
```
Debería mantenerse la definición completa inicialmente, a partir de aquí ya se puede referenciar como "UI" o "CLI" en el resto del documento.

2022-08-24 00:08 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +1. Agregue su repositorio a un repositorio remoto de Git (por ejemplo, en GitHub, GitLab, Bitbucket)
```suggestion
1. Agrega tu repositorio a un repositorio remoto de Git (por ejemplo, en GitHub, GitLab, Bitbucket)
```

2022-08-24 00:08 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +1. Elija un host que admita **continuous integration** (por ejemplo, [Netlify](/es/guides/deploy/netlify/) o [Vercel](/es/guides/deploy/vercel/)) e importa tu repositorio Git como un nuevo sitio/proy
```suggestion
1. Elije un host que admita **continuous integration** (por ejemplo, [Netlify](/es/guides/deploy/netlify/) o [Vercel](/es/guides/deploy/vercel/)) e importa tu repositorio Git como un nuevo sitio/proyecto.
```

2022-08-24 00:09 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +1. Haga clic en "Desplegar" y tu nuevo sitio web se creará en una URL única para ese host (por ejemplo, `new-astro-site.netlify.app`).
```suggestion
1. Haz clic en "Desplegar" y tu nuevo sitio web se creará en una URL única para ese host (por ejemplo, `new-astro-site.netlify.app`).
```

2022-08-24 00:10 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +Algunos hosts tendrán su propia interfaz de línea de comandos (CLI) que puedes instalar globalmente en su máquina usando npm. A menudo, el uso de una CLI para desplegar se parece a lo siguiente:
```suggestion
Algunos hosts tendrán su propia interfaz de línea de comandos (CLI) que puedes instalar globalmente en tu máquina usando npm. A menudo, el uso de una CLI para desplegar se parece a lo siguiente:
```

2022-08-24 00:11 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +1. Instale la CLI del host globalmente, por ejemplo:
```suggestion
1. Instala la CLI del host globalmente, por ejemplo:
```

2022-08-24 00:11 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +    Muchos proveedores de hosting construirán e desplegarán tu proyecto por ti. Por lo general, reconocerán tu proyecto como un sitio de Astro y elegirán los ajustes de configuración apropiados para
```suggestion
    Muchos proveedores de hosting construirán y desplegarán tu proyecto por ti. Por lo general, reconocerán tu proyecto como un sitio de Astro y elegirán los ajustes de configuración apropiados para construir y desplegar como se muestra a continuación. (De lo contrario, estos ajustes se pueden cambiar).
```

2022-08-24 00:13 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +    Otros proveedores de hosting requerirán que [construyas tu sitio localmente](#construyendo-tu-proyecto-localmente) y deplegarás usando la línea de comando.
```suggestion
    Otros proveedores de hosting requerirán que [construyas tu sitio localmente](#construyendo-tu-proyecto-localmente) y realizes el despliegue usando la línea de comandos.
```

2022-08-24 00:14 UTC, fredoist commented on src/pages/es/guides/deploy.md
>  Ejecute el comando `npm run build` para construir su sitio Astro.
```suggestion
Ejecuta el comando `npm run build` para construir su sitio Astro.
```

2022-08-24 00:15 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +Antes de implementar tu proyecto de Astro con [SSR (renderizado en el servidor)](/es/guides/server-side-rendering/) habilitado, asegúrese de tener:
```suggestion
Antes de implementar tu proyecto de Astro con [SSR (renderizado en el servidor)](/es/guides/server-side-rendering/) habilitado, asegúrate de tener:
```

2022-08-24 00:16 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +    - El [adaptador apropiado](/es/guides/server-side-rendering/#habilitando-ssr-en-su-proyecto) a las dependencias de su proyecto
```suggestion
    - El [adaptador apropiado](/es/guides/server-side-rendering/#habilitando-ssr-en-su-proyecto) en las dependencias de tu proyecto
```

2022-08-24 00:17 UTC, fredoist requested changes
Añadí algunas sugerencias, puedes revisarlas y adaptar las que consideres adecuadas.

2022-08-24 01:17 UTC, kevinzunigacuellar commented on src/pages/es/guides/deploy.md
>  Ejecute el comando `npm run build` para construir su sitio Astro.
```suggestion
Ejecute el comando `npm run build` para construir tu proyecto Astro.
```

2022-08-24 01:48 UTC, fredoist requested changes
Sorry, missed these. 😝

2022-08-24 01:48 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +**¿Listo para construir e implementar tu proyecto Astro?** Siga una de nuestras guías para diferentes servicios de implementación o desplácese hacia abajo para obtener orientación general sobre el de
```suggestion
**¿Listo para construir y desplegar tu proyecto Astro?** Sigue una de nuestras guías para diferentes servicios de despliegue o desplázate hacia abajo para obtener orientación general sobre el despliegue de un proyecto de Astro.
```

2022-08-24 01:48 UTC, fredoist commented on src/pages/es/guides/deploy.md
> +## Opciones de despliegue rápida
```suggestion
## Opciones de despliegue rápido
```

2022-08-24 02:46 UTC, fredoist approved these changes
LGTM ✅

2022-08-24 08:56 UTC, Yan-Thomas commented
Good job @kevinzunigacuellar, @fredoist 💜

2022-08-24 08:56 UTC, merged