Create aws.md
withastro/docs pull request #1431
Opened 2022-08-29 22:48 UTC by favanso

#### What kind of changes does this PR include?

- Translated content

#### Description

- Closes # 
- What does this PR change? It is the translation of the aws.md file from English to Portuguese-pt.
- Did you change something visual? No, I did not.

2022-09-03 18:53 UTC, delucis commented on src/pages/pt-br/guides/deploy/aws.md
> +descrição: Como fazer o deploy do seu Astro Site na web usando AWS.
Thanks for this @favanso!

We don’t need to translate the `title` and `description` keys here, only the text"

```suggestion
title: Deploy seu Site Astro na AWS
description: Como fazer o deploy do seu Astro Site na web usando AWS.
```

2022-09-03 18:57 UTC, delucis requested changes
Some more things that didn’t need translating — I’ll leave @Yan-Thomas & co to check the language :-)

2022-09-03 18:57 UTC, delucis commented on src/pages/pt-br/guides/deploy/aws.md
> +    :::Dica:
Ah, same here — `tip` tells us to use some special formatting and will automatically get the correct translation from `src/i18n/pt-br/ui.ts`

```suggestion
    :::tip
```

2022-09-03 18:57 UTC, delucis commented on src/pages/pt-br/guides/deploy/aws.md
> +    :::atenção
Same idea here

```suggestion
    :::caution
```

2022-09-03 18:57 UTC, delucis commented on src/pages/pt-br/guides/deploy/aws.md
> +    :::nota
```suggestion
    :::note
```

2022-09-03 18:57 UTC, delucis commented on src/pages/pt-br/guides/deploy/aws.md
> +    :::Dica:
```suggestion
    :::tip
```

2022-09-03 18:57 UTC, delucis commented on src/pages/pt-br/guides/deploy/aws.md
> +    :::atenção
```suggestion
    :::caution
```

2022-09-03 18:57 UTC, delucis commented on src/pages/pt-br/guides/deploy/aws.md
> +    :::atenção
```suggestion
    :::caution
```

2022-09-03 18:57 UTC, delucis commented on src/pages/pt-br/guides/deploy/aws.md
> +    :::nota
```suggestion
    :::note
```

2022-09-04 16:11 UTC, Yan-Thomas reviewed
Thanks @favanso, great work! I added suggestions to your PR, let me know what you think.

2022-09-04 16:11 UTC, Yan-Thomas commented on src/pages/pt-br/guides/deploy/aws.md
> +1. Crie uma nova política em sua conta AWS usando [IAM](https://aws.amazon.com/iam/) com as seguintes permissões. Esta política permitirá que você carregue arquivos _buildados_ para seu S3 _bucket_ e
Nas outras páginas que aparece CI/CD estamos mantendo o termo em inglês, por uma questão de consistência acredito que faça mais sentido manter assim.

```suggestion
## Continuous deployment com GitHub Actions

Há muitas maneiras de configurar continuous deployment com a AWS. Uma possibilidade de código hospedado no GitHub é usar [GitHub Actions](https://github.com/features/actions) para fazer deploy do seu website toda vez que você fizer push de um commit.

1. Crie uma nova política em sua conta AWS usando [IAM](https://aws.amazon.com/iam/) com as seguintes permissões. Esta política permitirá que você faça upload dos arquivos da sua build para seu S3 bucket e invalide os arquivos de distribuição do CloudFront quando você fizer push de um commit.
```

2022-09-04 16:11 UTC, Yan-Thomas commented on src/pages/pt-br/guides/deploy/aws.md
> +                  "arn:aws:s3:::<BUCKET_NAME>"
```suggestion
                  "<ARN_DISTRIBUICAO>",
                  "arn:aws:s3:::<NOME_DO_BUCKET>/*",
                  "arn:aws:s3:::<NOME_DO_BUCKET>"
```

2022-09-04 16:11 UTC, Yan-Thomas commented on src/pages/pt-br/guides/deploy/aws.md
> +    Não se esqueça de substituir `<DISTRIBUTION_ARN>` e `<BUCKET_NAME>`. Você pode encontrar o ARN em **CloudFront > Distributions > Details**.
```suggestion
    Não se esqueça de substituir `<ARN_DISTRIBUICAO>` e `<NOME_DO_BUCKET>`. Você pode encontrar o ARN em **CloudFront > Distribuições > Detalhes**.
```

2022-09-04 16:11 UTC, Yan-Thomas commented on src/pages/pt-br/guides/deploy/aws.md
> +2. Criar um novo usuário IAM e anexar a política ao usuário. Isto disponibilizará seu `AWS_SECRET_ACCESS_KEY` e `AWS_ACCESS_KEY_ID`.
```suggestion
2. Crie um novo usuário IAM e anexe a política ao usuário. Isto disponibilizará seu `AWS_SECRET_ACCESS_KEY` e `AWS_ACCESS_KEY_ID`.
```

2022-09-04 16:11 UTC, Yan-Thomas commented on src/pages/pt-br/guides/deploy/aws.md
> +3. Adicione este exemplo de fluxo de trabalho ao seu repositório em `.github/workflows/deploy.yml` e faça o _push_ no GitHub. Você precisará acrescentar `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`,
```suggestion
3. Adicione este exemplo de fluxo de trabalho ao seu repositório em `.github/workflows/deploy.yml` e faça push no GitHub. Você precisará acrescentar `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `BUCKET_ID` e `DISTRIBUTION_ID` como “secrets” no seu repositório no GitHub em **Settings** > **Secrets** > **Actions**. Clique em <kbd>New repository secret</kbd> para adicionar cada um deles.
```

2022-09-04 16:11 UTC, Yan-Thomas commented on src/pages/pt-br/guides/deploy/aws.md
> +    Seu `BUCKET_ID` é o nome do seu S3 _bucket_. Seu `DISTRIBUTION_ID` é o seu _CloudFront distribution ID_. Você pode encontrar seu _CloudFront distribution ID_ em **CloudFront > Distributions > ID*
```suggestion
    Seu `BUCKET_ID` é o nome do seu S3 bucket. Seu `DISTRIBUTION_ID` é o seu CloudFront distribution ID (ID de distribuição do CloudFront). Você pode encontrar seu CloudFront distribution ID em **CloudFront > Distribuições > ID**
```

2022-09-04 19:42 UTC, favanso commented
Obrigado Yan, eu fiz o commit de todas as sugestões.

2022-09-04 19:54 UTC, Yan-Thomas reviewed
Thanks again for the dedication @favanso, can you apply these two suggestions I added now? After this, it's good to merge! 🙌

2022-09-04 19:54 UTC, Yan-Thomas commented on src/pages/pt-br/guides/deploy/aws.md
> +description: Como fazer o deploy do seu Astro Site na web usando AWS.
Parece que essa sugestão sem querer foi sobrescrita, poderia adicionar ela novamente?
```suggestion
title: Faça Deploy do seu Site Astro na AWS
description: Como fazer o deploy do seu site Astro para web na AWS.
```

2022-09-04 19:54 UTC, Yan-Thomas commented on src/pages/pt-br/guides/deploy/aws.md
> +3. Modifique seu diretório de saída da _build_ de `baseDirectory` para `/dist`.
Aqui esqueci de remover "_" na primeira sugestão.
```suggestion
3. Modifique seu diretório de saída da build de `baseDirectory` para `/dist`.
```

2022-09-04 20:28 UTC, favanso commented
Done, @Yan-Thomas! Obrigado pelas sugestões. Vou tentar colaborar com mais páginas no projeto.

2022-09-04 20:34 UTC, Yan-Thomas commented
> Done, @Yan-Thomas! Obrigado pelas sugestões. Vou tentar colaborar com mais páginas no projeto.

Valeu por tudo @favanso, recomendo você entrar no nosso Discord (https://astro.build/chat), lá temos um canal específico só para traduções com threads para cada língua e é onde nosso maior esforço e organização relacionado à traduções acontece, ficaria feliz de tê-lo lá. Inclusive, temos várias traduções abertas para revisão, pesquise por "i18n(pt-BR)" na aba Pull Requests que você vai ver todos os PRs de tradução para PT-BR 🙌 

Uma dica, você pode usar "Add suggestion to batch" para aplicar várias sugestões ao mesmo tempo na aba "Files changed", o que evita ter que fazer commit e push para cada uma das mudanças sugeridas.

2022-09-04 20:36 UTC, Yan-Thomas approved these changes

2022-09-04 20:37 UTC, merged