i18n(es): Add endpoints.md translation
withastro/docs pull request #1665
Opened 2022-10-01 21:17 UTC by AbrahamX3

#### What kind of changes does this PR include?

- Translated content

#### Description

Translates [Endpoints](https://docs.astro.build/en/core-concepts/endpoints/) to es.

I'm participating in Hacktoberfest, please label this PR as `hacktoberfest-accepted if accepted!

2022-10-02 02:15 UTC, fredoist requested changes
Amazing work @Abraham, deje algunas sugerencias en la review, además de algunas correcciones para los enlaces a páginas relacionadas.

Por favor revísalas y modifícalas según consideres pertinente. En este caso considero que es mejor mantener el nombre original de lo que sería un endpoint, además que facilitaría al usuario a buscar más información relacionada al llamarlos así.

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +Todo lo descrito en la sección de puntos finales de archivos estáticos también se puede usar en modo SSR: los archivos se pueden exportar con una función `get` que recibe un objeto con las propiedade
```suggestion
Todo lo descrito en la sección de endpoints de archivos estáticos también se puede usar en modo SSR: los archivos pueden exportar una función `get` que recibe un objeto con las propiedades `params` y `request`.
```

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +Pero, a diferencia del modo `static`, cuando se configura el modo `server`, los puntos finales se construirán cuando se soliciten. Esto desbloquea nuevas funciones que no están disponibles al momento
```suggestion
Pero, a diferencia del modo `static`, cuando configuras el modo `server`, los endpoints se construirán cuando se soliciten. Esto desbloquea nuevas funciones que no están disponibles al momento de la compilación y permite crear rutas de API que escuchan solicitudes y ejecutan código de forma segura en el servidor en tiempo de ejecución.
```

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +Asegúrese de [habilitar SSR](/es/guides/server-side-rendering/#enabling-ssr-in-your-project) antes de probar estos ejemplos.
```suggestion
Asegúrese de [habilitar SSR](/es/guides/server-side-rendering/#habilitando-ssr-en-su-proyecto) antes de probar estos ejemplos.
```

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +Los puntos finales del servidor pueden acceder a `params` sin exportar `getStaticPaths`, y pueden devolver un objeto [`Response`](https://developer.mozilla.org/en-US/docs/Web/API/Response), lo que le
```suggestion
Los endpoints del servidor pueden acceder a `params` sin exportar `getStaticPaths`, y pueden devolver un objeto [`Response`](https://developer.mozilla.org/es/docs/Web/API/Response), lo que te permite establecer códigos de estado y encabezados:
```

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +Además de la función `get`, puede exportar una función con el nombre de cualquier [método HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods). Cuando llega una solicitud, Astro verificar
```suggestion
Además de la función `get`, puede exportar una función con el nombre de cualquier [método HTTP](https://developer.mozilla.org/es/docs/Web/HTTP/Methods). Cuando llega una solicitud, Astro verificará el método y llamará a la función correspondiente.
```

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +Esto responderá a cualquier solicitud que coincida con la ruta dinámica. Por ejemplo, si navegamos a `/helmet.json`, `params.id` se establecerá en `helmet`. Si el `helmet` existe en la base de datos
```suggestion
Esto responderá a cualquier solicitud que coincida con la ruta dinámica. Por ejemplo, si navegamos a `/helmet.json`, `params.id` se establecerá en `helmet`. Si el `helmet` existe en la base de datos del producto simulado, el punto final usará la creación del objeto `Response` para responder con JSON y devolver un [código de estado HTTP](https://developer.mozilla.org/es/docs/Web/API/Response/status) exitoso. Si no, utilizará un objeto `Response` para responder con un `404`.
```

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +También puede exportar una función `all` para que coincida con cualquier método que no tenga una función exportada correspondiente. Si hay una solicitud sin método de coincidencia, se redirigirá a la
```suggestion
También puede exportar una función `all` para que coincida con cualquier método que no tenga una función exportada correspondiente. Si hay una solicitud sin método de coincidencia, se redirigirá a la [página 404](/en/core-concepts/astro-pages/#página-de-error-404-personalizada) de su sitio.
```

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +En modo SSR, la propiedad `request` devuelve un objeto [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request) totalmente utilizable que hace referencia a la solicitud actual. Esto perm
```suggestion
En modo SSR, la propiedad `request` devuelve un objeto [`Request`](https://developer.mozilla.org/es/docs/Web/API/Request) totalmente utilizable que hace referencia a la solicitud actual. Esto permite aceptar datos y verificar encabezados:
```

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +Los puntos finales del servidor se pueden usar como puntos finales del API REST para ejecutar funciones como autenticaciones, acceso a bases de datos y verificaciones sin exponer datos confidenciales
```suggestion
Los endpoints del servidor se pueden usar como endpoints del API REST para ejecutar funciones como autenticaciones, acceso a bases de datos y verificaciones sin exponer datos confidenciales al cliente.
```

2022-10-02 02:15 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +Luego, accedemos a nuestro punto final usando `fetch` desde un script de cliente:
```suggestion
Luego, accedemos a nuestro endpoint usando `fetch` desde un script de cliente:
```

2022-10-02 02:52 UTC, AbrahamX3 commented
Me parece perfecto dejar el término como endpoint y gracias por corregir los enlaces!!

2022-10-02 03:00 UTC, AbrahamX3 reviewed
Me parece perfecto dejar el término como endpoint

2022-10-02 03:02 UTC, AbrahamX3 reviewed
Gracias por corregir los enlaces y el termino de endpoint!

2022-10-02 03:04 UTC, agustinmulet reviewed
Dejé algunas sugerencias, algunas sobre el trabajo de fredoist. Muy buen trabajo! 💪

2022-10-02 03:04 UTC, agustinmulet commented on src/pages/es/core-concepts/endpoints.md
> +Dado que `delete` es una palabra reservada en JavaScript, exporte una función `del` para que coincida con el método de eliminación.
```suggestion
Dado que `delete` es una palabra reservada en JavaScript, exporta una función `del` para que coincida con el método de eliminación.
```

2022-10-02 03:04 UTC, agustinmulet commented on src/pages/es/core-concepts/endpoints.md
> +      message: `Esto fue un ${request.method}!`
```suggestion
      message: `¡Esto fue un ${request.method}!`
```

2022-10-02 03:04 UTC, agustinmulet commented on src/pages/es/core-concepts/endpoints.md
> +En modo SSR, la propiedad `request` devuelve un objeto [`Request`](https://developer.mozilla.org/en-US/docs/Web/API/Request) totalmente utilizable que hace referencia a la solicitud actual. Esto perm
```suggestion
En modo SSR, la propiedad `request` retorna un objeto [`Request`](https://developer.mozilla.org/es/docs/Web/API/Request) totalmente utilizable que hace referencia a la solicitud actual. Esto permite aceptar datos y verificar encabezados:
```

2022-10-02 03:04 UTC, agustinmulet commented on src/pages/es/core-concepts/endpoints.md
> +Dado que `Astro.redirect` no está disponible para las rutas API, se puede usar [`Response.redirect`](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect) para redirigir:
```suggestion
Dado que `Astro.redirect` no está disponible para las rutas API, puedes [`Response.redirect`](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect) para redirigir:
```

2022-10-02 14:41 UTC, AbrahamX3 reviewed
Update

2022-10-02 14:56 UTC, AbrahamX3 reviewed
Suggestion changes

2022-10-02 23:16 UTC, fredoist commented on src/pages/es/core-concepts/endpoints.md
> +Esto responderá a cualquier solicitud que coincida con la ruta dinámica. Por ejemplo, si navegamos a `/helmet.json`, `params.id` se establecerá en `helmet`. Si el `helmet` existe en la base de datos
La última corrección y está ok para mí. ✅ 

```suggestion
Esto responderá a cualquier solicitud que coincida con la ruta dinámica. Por ejemplo, si navegamos a `/helmet.json`, `params.id` se establecerá en `helmet`. Si el `helmet` existe en la base de datos del producto simulado, el endpoint usará la creación del objeto `Response` para responder con JSON y devolver un [código de estado HTTP](https://developer.mozilla.org/es/docs/Web/API/Response/status) exitoso. Si no, utilizará un objeto `Response` para responder con un `404`.
```

2022-10-03 00:06 UTC, fredoist approved these changes

2022-10-03 01:45 UTC, kevinzunigacuellar reviewed
esto deberia arreglar el link roto

2022-10-03 01:45 UTC, kevinzunigacuellar commented on src/pages/es/core-concepts/endpoints.md
> +También puedes exportar una función `all` para que coincida con cualquier método que no tenga una función exportada correspondiente. Si hay una solicitud sin método de coincidencia, se redirigirá a l
```suggestion
También puedes exportar una función `all` para que coincida con cualquier método que no tenga una función exportada correspondiente. Si hay una solicitud sin método de coincidencia, se redirigirá a la [página 404](/es/core-concepts/astro-pages/#página-de-error-404-personalizada) de su sitio.
```

2022-10-03 01:52 UTC, kevinzunigacuellar commented
Gracias @fredoist, @AbrahamX3 y @agustinmulet por los reviews!

2022-10-03 01:52 UTC, merged