i18n(zh-cn): Update the translation of `astro-components.md` and `typescript.md`
withastro/docs pull request #1670
Opened 2022-10-01 23:07 UTC by mogeko

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

I updated the Chinese translations of `astro-components.md` and `typescript.md` to catch up with the English version.

`typescript.md` in particular, it is so behind the English version that I almost rewrote it with this update.

For `astro-components.md`, I removed `export` requirement for `Props` #1632.

By the way, `hacktoberfest-accepted` please. 

<img width="150px" alt="IMG_51D0DB182093-1" src="https://user-images.githubusercontent.com/26341224/193431374-e10a027a-2df1-47eb-9eb4-e816e1f0eb6f.jpeg">

2022-10-21 09:33 UTC, delucis requested changes
Hi @mogeko! Sorry to only get to this now. There have been a few more changes to the English versions, would you be able to update this PR with those?

- astro-components: https://github.com/withastro/docs/commit/b34822eb26f396fe6e6e2c08822122a0cf295766#diff-2cea51d918d3ae4fedfce864624f37591ca58c59140f2f60c55e53641e91a661
- typscript: https://github.com/withastro/docs/commit/1e4d6f86cca3fd2d82dcab14f89566a3dfe14ebf#diff-8bd9acd482c1c173d693abf42692979a226d6c46a9ca5f3980214d168e85a076

2022-10-21 09:36 UTC, mogeko commented
Of course! I will update this PR after I finish it.

2022-10-21 10:07 UTC, delucis commented
Thank you!

2022-11-27 21:49 UTC, mogeko commented
Hi @delucis!

As you can see, I retranslated `astro-components.md` and `typscript.md` according to the latest English version of the document. (`astro-components.md` to #2102, `typscript.md` to #2030)

It seems that there is also an article [`client-side-scripts.md`](src/pages/en/guides/client-side-scripts.md) related to part of `astro-components.md`. There is no Chinese translation yet. But please merge it first. After I prepare the translation of `client-side-scripts.md`, I will submit a new PR.

2022-11-28 16:13 UTC, delucis reviewed
Thanks @mogeko! Spotted a few small details to clean up and then this should be ready to merge 🎊

2022-11-28 16:13 UTC, delucis commented on src/pages/zh-cn/guides/typescript.md
> +Astro 为常见的组件参数的类型模式准备了一些实用的类型工具集。这些可以通过在代码中引入 `astro/types` 来使用。
Looks like the original English text got left in here:

```suggestion
Astro 为常见的组件参数的类型模式准备了一些实用的类型工具集。这些可以通过在代码中引入 `astro/types` 来使用。
```

2022-11-28 16:13 UTC, delucis commented on src/pages/zh-cn/guides/typescript.md
> +```
I think this code example is still showing the old version. The new example looks more like this:

````suggestion
```astro title="src/components/Link.astro" ins="HTMLAttributes" ins="HTMLAttributes<'a'>"
---
import { HTMLAttributes } from 'astro/types'
// use a `type`
type Props = HTMLAttributes<'a'>;
// or extend with an `interface`
interface Props extends HTMLAttributes<'a'> {
  myProp?: boolean;
}
const { href, ...attrs } = Astro.props;
---
<a {href} {...attrs}>
  <slot />
</a>
```
````

Would be good to translate the “use a `type`” and “or extend with and `interface`” comments.

2022-11-28 16:13 UTC, delucis commented on src/pages/zh-cn/guides/typescript.md
> +对于默认设置 `jsxImportSource: react`，你可以使用：
Duplicate English sentence here:

```suggestion
对于默认设置 `jsxImportSource: react`，你可以使用：
```

2022-11-28 17:56 UTC, mogeko commented
@delucis There should be fine now! Please check.

2022-11-29 10:59 UTC, delucis approved these changes
Thanks @mogeko! Excellent contribution ❤️

2022-11-29 11:03 UTC, merged