i18n(pt-BR): Add `endpoints.md` translation
withastro/docs pull request #1678
Opened 2022-10-02 16:44 UTC by peterfritz

#### What kind of changes does this PR include?
- Translated content

#### Description
Translates [Endpoints](https://docs.astro.build/en/core-concepts/endpoints/) to pt-BR.

I am taking part in Hacktoberfest so if everything is ok with the PR, I would appreciate it beign labeled with `hacktoberfest-accepted`.

By the way, Astro is amazing. I could not thank you enough for maintaining and constantly improving it ❤️

Copy of #1661 with corrections suggested by @wtchnm.

2022-10-02 16:51 UTC, wtchnm approved these changes

2022-10-02 21:39 UTC, Yan-Thomas requested changes
Thanks @peterfritz, good job! I added some suggestions to improve your work. 

Note that changes to the content itself the way you did in some parts (like adding new links or changing phrases with different information) must be suggested to the main docs in English first. Translations shouldn't change the original content, as this makes it harder for future translators to update the page and also can make important information be missed.

2022-10-02 21:39 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +Assim, se `rick-astley` existir no banco de dados, o endpoint irá criar um objeto `Response` para responder com seu respectivo conteúdo e retornar um código de resposta de sucesso. Caso contrário, el
Algumas alterações para manter próximo da versão original.
```suggestion
Esse código responderá a qualquer requisição que corresponda à rota dinâmica. Por exemplo, se navegarmos para `/capacete.json`, `params.id` será `capacete`. Se `capacete` existir no banco de dados, o endpoint irá criar um objeto `Response` para responder com JSON e retornar um [código de status HTTP](https://developer.mozilla.org/en-US/docs/Web/API/Response/status) de sucesso. Caso contrário, ele usará o objeto `Response` para responder com um erro `404`.
```

2022-10-02 21:39 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +### HTTP methods
Esse título faltou ser traduzido.
```suggestion
### Métodos HTTP
```

2022-10-02 21:39 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +Se não houver um método correspondente exportado para uma requisição, ela será redirecionada para a sua [página de 404](/pt-br/core-concepts/astro-pages/#página-customizada-de-erro-404).
```suggestion
Também é possível exportar uma função `all` para corresponder a todos os métodos que já não tenham suas respectivas funções exportadas. Se houver uma requisição sem método correspondente, ela será redirecionada para a sua [página de 404](/pt-br/core-concepts/astro-pages/#página-customizada-de-erro-404).
```

2022-10-02 21:39 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +:::
```suggestion
:::note
Como `delete` é uma palavra reservada do JavaScript, exporte uma função chamada `del` para corresponder ao método delete.
:::
```

2022-10-02 21:39 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +No modo SSR, a propriedade `request` retorna um objeto [`Request`](https://developer.mozilla.org/pt-BR/docs/Web/API/Request) que se refere a requisição atual, isso permite que você aceite dados e che
```suggestion
No modo SSR, a propriedade `request` retorna um objeto [`Request`](https://developer.mozilla.org/pt-BR/docs/Web/API/Request) completamente utilizável que se refere a requisição atual. Isso permite que você aceite dados e cheque cabeçalhos:
```

2022-10-02 21:39 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +Endpoints dinâmicos podem ser usados como uma API REST para desempenhar funções como autenticação, acesso ao banco de dados e validações sem expor dados sensíveis ao usuário.
```suggestion
Endpoints do servidor podem ser usados como uma API REST para executar funções de autenticação, acesso ao banco de dados e verificação sem expor dados sensíveis ao cliente.
```

2022-10-02 21:39 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +No servidor nós definimos uma função correspondente ao método POST que aceita dados do desafio e então verifica seu resultado com a API do reCAPTCHA. Aqui nós podemos ler as [variáveis de ambiente](/
```suggestion
No servidor nós definimos uma função correspondente ao método POST que aceita os dados do desafio e então verifica seu resultado com a API do reCAPTCHA. Aqui nós podemos definir valores secretos ou ler variáveis de ambiente de maneira segura.
```

2022-10-03 00:19 UTC, peterfritz commented on src/pages/pt-br/core-concepts/endpoints.md
> +## Endpoints estáticos
Oi @Yan-Thomas, boa noite, tudo bem?
Achei essa tradução para esse nome um pouco confusa. Mesmo que o endpoint se transforme em um arquivo durante o build, para o desenvolvedor ele continuaria sendo um endpoint, já que para editar o conteúdo do arquivo, o que deve ser editado é o endpoint em si.
E em português a interpretação de um `endpoint de arquivos estáticos` não me pareceu apropriada para descrever o processo de gerar arquivos, mas sim de servi-los ou mapeá-los a URLs.
Consegue pensar em alguma tradução alternativa ou seria possível manter o nome `endpoints estáticos` e adicionar um parágrafo abaixo descrevendo em maiores detalhes essa funcionalidade?

2022-10-03 00:36 UTC, peterfritz commented on src/pages/pt-br/core-concepts/endpoints.md
> +Seus endpoints devem exportar uma função `get` (opcionalmente assíncrona) e ela recebe um objeto com duas propriedades (`param` e `request`) como seu único parâmetro. Retornando um objeto contendo a
Concordo perfeitamente com as mudanças no texto com algumas modificações para evitar a repetição da conjunção "e" na frase. Porém `opcionalmente async` me parece estranho já que a palavra `async` é apenas uma palavra reservada responsável por declarar o comportamento de assincronia, não descrevê-lo.
Sugiro a alteração do parágrafo para algo como:
```suggestion
Seus endpoints devem exportar uma função `get` (opcionalmente assíncrona) que recebe um objeto com as propriedades (`param` e `request`) como único parâmetro e retorna um objeto contendo a propriedade `body`. Essa função será chamada pelo Astro durante a build, que utilizará os conteúdos da propriedade `body` para gerar o arquivo.
```

2022-10-03 00:42 UTC, peterfritz commented on src/pages/pt-br/core-concepts/endpoints.md
> +Para utilizá-las, nomeie sua rota utilizando a notação de `[colchetes]` e exporte uma função chamada [`getStaticPaths()`](/pt-br/reference/api-reference/#getstaticpaths). Assim será possível acessar
Perfeito, sugiro apenas uma pequena modificação na primeira frase:
```suggestion
Os endpoints suportam as mesmas funcionalidades de [roteamento dinâmico](/pt-br/core-concepts/routing/#rotas-dinâmicas) que as páginas. Nomeie seu arquivo com um nome de parâmetro entre colchetes e exporte uma função chamada [`getStaticPaths()`](/pt-br/reference/api-reference/#getstaticpaths). Assim será possível acessar o parâmetro utilizando a propriedade `params` passada para a função do endpoint.
```

2022-10-03 00:52 UTC, peterfritz commented on src/pages/pt-br/core-concepts/endpoints.md
> +O roteamento dinâmico com endpoints funciona da mesma forma que com as páginas com exceção da propriedade [props](/pt-br/reference/api-reference/#passagem-de-dados-com-props) que não é suportada pela
Como disse antes, acho confuso o uso intercambiável das palavras endpoint e arquivo, já que um endpoint nesse caso é o que gera um ou mais arquivos. Dessa forma acho que seria mais correto descrever o comportamento como a geração de três arquivos JSON e não de três endpoints JSON.
Também acho justo um espaço entre as frases já que se referem a coisas diferentes.
```suggestion
Dessa forma serão gerados três arquivos JSON durante a build: `/api/1.json`, `/api/2.json` e `/api/3.json`.

O roteamento dinâmico com endpoints funciona da mesma forma que nas páginas, porém, como um endpoint é uma função e não uma página, [props](/pt-br/reference/api-reference/#passagem-de-dados-com-props) não são suportadas.
```

2022-10-03 01:02 UTC, peterfritz commented on src/pages/pt-br/core-concepts/endpoints.md
> +Isso permite que você tenha acesso a novas funcionalidades indisponíveis durante o build e permite que você crie rotas que esperam por requisições e executam código de forma segura no servidor.
O nome `Endpoints do Servidor` me parece inapropriado para descrever o comportamento mas concordo que devido a função `getStaticPaths()`, endpoints estáticos também podem ser dinâmicos.
Ademais o significado das palavras static e server não ficaram claros, já que dependem de contexto que só está disponível na página de habilitar o modo SSR. Seria possível adicionar um link para uma descrição do significado e das diferenças entre os modos?

2022-10-03 18:40 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +## Endpoints estáticos
Eu prefiro evitar traduções que desviem do que está escrito na versão original, ainda mais adicionar parágrafos extras, o que tornaria mais difícil manter a tradução. Se você realmente for contra a nomenclatura, você pode fazer um PR sugerindo essa alteração para a página em inglês e depois podemos atualizar essa tradução posteriormente.

A nomenclatura se deve ao fato de que cada endpoint **É** um arquivo no diretório `/pages`, e a página deixa (ao menos para mim) bem claro de que estamos gerando o conteúdo dos endpoints ao invés de servir um arquivo já existente, por assim dizer.

2022-10-03 18:44 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +Isso permite que você tenha acesso a novas funcionalidades indisponíveis durante o build e permite que você crie rotas que esperam por requisições e executam código de forma segura no servidor.
Isso entra no meu argumento anterior de não fazer mudanças ao conteúdo da página ou as nomenclaturas utilizadas, é quase como se estivéssemos escrevendo uma outra documentação em português do que uma tradução.

2022-10-03 18:49 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +O roteamento dinâmico com endpoints funciona da mesma forma que com as páginas com exceção da propriedade [props](/pt-br/reference/api-reference/#passagem-de-dados-com-props) que não é suportada pela
O meu entendimento é que endpoints são como o próprio nome disse, pontas para outros tipos de aplicações e estruturas, que nesse caso são arquivos JSON, então não vejo porquê mudar a nomenclatura, além disso ser uma mudança de conteúdo, que deve ser primeiro sugerida na versão original antes de ser modificada na tradução.

2022-10-03 19:54 UTC, Yan-Thomas commented on src/pages/pt-br/core-concepts/endpoints.md
> +O roteamento dinâmico com endpoints funciona da mesma forma que com as páginas com exceção da propriedade [props](/pt-br/reference/api-reference/#passagem-de-dados-com-props) que não é suportada pela
Perfeito!

2022-10-03 20:00 UTC, Yan-Thomas commented
LGTM!

2022-10-03 20:00 UTC, Yan-Thomas approved these changes

2022-10-03 20:06 UTC, merged