i18n(es): improve gitlab deploy documentation
withastro/docs pull request #1706
Opened 2022-10-03 19:24 UTC by fredoist

#### What kind of changes does this PR include?
- New or updated content
- Translated content

#### Description
- What does this PR change? Give us a brief description. Updates GitLab guide with #1693

2022-10-03 20:01 UTC, AbrahamX3 requested changes
Hola, deje algunas sugerencias en la review, me gustaría ver que opinas. Me basé en la [documentación](https://docs.astro.build/es/core-concepts/project-structure/#carpetas-y-archivos) para el término usado.

2022-10-03 20:01 UTC, AbrahamX3 commented on src/pages/es/guides/deploy/gitlab.md
> +         # El folder que contiene los archivos compilados para publicarse.
```suggestion
         # La carpeta que contiene los archivos compilados para publicarse.
```

2022-10-04 00:59 UTC, marsidev approved these changes
lgtm 👍🏼

2022-10-04 03:20 UTC, AbrahamX3 approved these changes

2022-10-04 03:32 UTC, merged