i18n(es): revise and elaborate typescript intro
withastro/docs pull request #1707
Opened 2022-10-03 19:33 UTC by fredoist

#### What kind of changes does this PR include?
- New or updated content
- Translated content

#### Description
- What does this PR change? Give us a brief description. Update TypeScript guide to #1699

2022-10-03 20:23 UTC, AbrahamX3 requested changes
Hola, deje algunas sugerencias en la review, me gustaría ver que opinas 🙌

2022-10-03 20:23 UTC, AbrahamX3 commented on src/pages/es/guides/typescript.md
> +Usando TypeScript, puedes prevenir errores en tiempo de ejecución al definir las formas de los objetos y componentes en tu código. Por ejemplo, si usas TypeScript para [tipar las props de tu componen
```suggestion
Usando TypeScript, puedes prevenir errores en tiempo de ejecución al definir las formas de los objetos y componentes en tu código. Por ejemplo, si utilizas TypeScript para [tipar las props de tu componente](#props-de-componentes), obtendrás un error en tu editor si estableces una prop que tu componente no acepta.
```

2022-10-03 20:26 UTC, AbrahamX3 requested changes

2022-10-03 20:26 UTC, AbrahamX3 commented on src/pages/es/guides/typescript.md
> +No necesitas escribir código de TypeScript en tus proyectos de Astro para obtener beneficios de éste. Astro siempre trata el código de tu componente como TypeScript, y la [Estensión de Astro para VSC
```suggestion
No necesitas escribir código de TypeScript en tus proyectos de Astro para obtener beneficios de este. Astro siempre trata el código de tu componente como TypeScript, y la [Extensión de Astro para VSCode](/es/editor-setup/) inferirá todo lo que pueda para proporcionar autocompletado, sugerencias, y errores en tu editor.
```

2022-10-03 20:26 UTC, AbrahamX3 commented on src/pages/es/guides/typescript.md
> +El servidor de desarrollo de Astro no realizará ningún chequeo de tipado, pero puedes usar un [script aparte](#verificación-de-tipos) para verificar errores de tipado desde la linea de comandos.
```suggestion
El servidor de desarrollo de Astro no realizará ningún chequeo de tipado, pero puedes usar un [script aparte](#verificación-de-tipos) para verificar errores de tipado desde la línea de comandos.
```

2022-10-04 00:58 UTC, marsidev approved these changes
lgtm 👍🏼

2022-10-04 03:19 UTC, AbrahamX3 approved these changes

2022-10-04 03:40 UTC, merged