i18n(es): update `install/auto.md` and `install/manual.md`
withastro/docs pull request #1711
Opened 2022-10-03 22:58 UTC by marsidev

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content

#### Description

- What does this PR change? Give us a brief description.
  - Minimal changes to keep it similar to the english version
  - Minimal changes to keep `install/auto.md` and `install/manual.md` similar
    - Like the `auto` version using the word `comenzar` and the `manual` one using `empezar`. Now both uses the same word
  - Change `Typescript` with `TypeScript`
  - Added missing punctuation marks
  - Minimal fixes

Please label this PR with `hacktoberfest-accepted` if get approved. 🎃

2022-10-03 23:17 UTC, AbrahamX3 requested changes
¡Buen trabajo! Solo tengo una pequeña sugerencia, me gustaría ver que opinas 🙌

2022-10-03 23:17 UTC, AbrahamX3 commented on src/pages/es/install/manual.md
> +TypeScript es configurado usando `tsconfig.json`. Aún si tú no escribes código en TypeScript, este archivo es importante para que herramientas como Astro y VS Code sepan cómo comprender tu proyecto.
```suggestion
TypeScript es configurado usando `tsconfig.json`. Aun si tú no escribes código en TypeScript, este archivo es importante para que herramientas como Astro y VS Code sepan cómo comprender tu proyecto. Algunas características (como importaciones de paquetes npm) no tienen un soporte completo en el editor sin el archivo `tsconfig.json`.
```

2022-10-03 23:53 UTC, marsidev commented on src/pages/es/install/manual.md
> +TypeScript es configurado usando `tsconfig.json`. Aún si tú no escribes código en TypeScript, este archivo es importante para que herramientas como Astro y VS Code sepan cómo comprender tu proyecto.
Me parece genial la corrección, no me había fijado del error. Muchas gracias!

2022-10-04 00:19 UTC, fredoist approved these changes
LGTM ✅

Buen trabajo @marsidev

2022-10-04 00:23 UTC, marsidev commented
Gracias @fredoist 👌🏼

2022-10-04 03:19 UTC, AbrahamX3 approved these changes

2022-10-04 04:08 UTC, merged