i18n(es): update `github.md`
withastro/docs pull request #1725
Opened 2022-10-05 14:31 UTC by dreyfus92

#### What kind of changes does this PR include?

- Translated content

#### Description

What does this PR change? 
- Made a few changes to the previous translation of integrations-guide.md.

Please labeled this PR with `hacktoberfest-accepted`.

2022-10-05 19:11 UTC, agustinmulet requested changes
Buen trabajo! Dejé sugerencias y me parece que la traducción está incompleta, faltarían estas líneas con lo nuevo https://github.com/withastro/docs/commit/c4db30c5b8f3cfa11e02a7c890e6cac872b950da#diff-48ec7bc5f7f0031502eaf6f7a0946de61038a47cc354aa5407f54ce5f11b2feaR71-R75

2022-10-05 19:11 UTC, agustinmulet commented on src/pages/es/guides/deploy/github.md
> +2. Crea un nuevo archivo en tu proyecto en `.github/workflows/deploy.yml` y pega el siguiente archivo YAML.
Me parece más clara la traducción anterior, no me parece que tenga mucho sentido **crear un archivo y pegar el archivo**

2022-10-05 19:11 UTC, agustinmulet commented on src/pages/es/guides/deploy/github.md
> +Puedes desplegar un proyecto de Astro en páginas de GitHub usando [GitHub Actions](https://github.com/features/actions) para construir y desplegar tu proyecto automáticamente. Para hacer esto, tu cód
A mi parecer dejaría GitHub Pages ya que es el nombre del producto, qué te parece?

2022-10-05 19:11 UTC, agustinmulet commented on src/pages/es/guides/deploy/github.md
> +Astro mantiene la acción oficial `withastro/action` para desplegar tu proyecto con muy poca configuración. Sigue las instrucciones a continuación para desplegar tu proyecto de Astro en páginas de Git
Mismo comentario que antes sobre GitHub Pages, qué te parece? De preferir la traducción, dejo una sugerencia de cambio

```suggestion
Astro mantiene la acción oficial `withastro/action` para desplegar tu proyecto con muy poca configuración. Sigue las instrucciones a continuación para desplegar tu proyecto de Astro en páginas de GitHub y consulta el [README](https://github.com/withastro/action) si necesitas más información.
```

2022-10-05 19:15 UTC, fredoist commented on src/pages/es/guides/deploy/github.md
> +2. Crea un nuevo archivo en tu proyecto en `.github/workflows/deploy.yml` y pega el siguiente archivo YAML.
```suggestion
2. Crea un nuevo archivo en tu proyecto en `.github/workflows/deploy.yml` y pega el siguiente código YAML.
```

2022-10-05 21:28 UTC, dreyfus92 commented on src/pages/es/guides/deploy/github.md
> +Astro mantiene la acción oficial `withastro/action` para desplegar tu proyecto con muy poca configuración. Sigue las instrucciones a continuación para desplegar tu proyecto de Astro en páginas de Git
Yo creo que si voy a cambiarlo a "acción de GitHub oficial".

2022-10-05 21:31 UTC, dreyfus92 commented
Gracias por sus observaciones @fredoist  y @agustinmulet en unos momentos subo los cambios.

2022-10-05 21:59 UTC, fredoist requested changes
Mantengamos "Pages" en mayúscula :)

2022-10-05 21:59 UTC, fredoist commented on src/pages/es/guides/deploy/github.md
> +Astro mantiene la acción oficial `withastro/action` para desplegar tu proyecto con muy poca configuración. Sigue las instrucciones a continuación para desplegar tu proyecto de Astro en GitHub pages y
```suggestion
Astro mantiene la acción oficial `withastro/action` para desplegar tu proyecto con muy poca configuración. Sigue las instrucciones a continuación para desplegar tu proyecto de Astro en GitHub Pages y consulta el [README](https://github.com/withastro/action) si necesitas más información.
```

2022-10-05 22:35 UTC, dreyfus92 commented on src/pages/es/guides/deploy/github.md
> +    La acción de astro toma algunas cuantas entradas opcionales. Estas pueden ser proporcionadas mediante descomentar la línea de `with:` y la entrada que quieras utilizar.
Listo, muchas gracias @fredoist

2022-10-05 23:08 UTC, fredoist commented
Perfecto @dreyfus92 , únicamente faltaría añadir los últimos cambios como menciono @agustinmulet 

https://github.com/withastro/docs/commit/c4db30c5b8f3cfa11e02a7c890e6cac872b950da#diff-48ec7bc5f7f0031502eaf6f7a0946de61038a47cc354aa5407f54ce5f11b2feaR71-R75

2022-10-05 23:58 UTC, fredoist requested changes
Algunas ultimas sugerencias @dreyfus92

2022-10-05 23:58 UTC, fredoist commented on src/pages/es/guides/deploy/github.md
> +                # node-version: 16 # La version específica de Node que debe utilizarse para compilar tu sitio. La que está por defecto es la 16. (opcional)
```suggestion
                # node-version: 16 # La versión específica de Node que debe utilizarse para compilar tu proyecto. Por defecto es la 16. (opcional)
```

2022-10-05 23:58 UTC, fredoist commented on src/pages/es/guides/deploy/github.md
> +                # package-manager: yarn # El gestor de paquetes de Node que debe instalar las dependencias y compilar tu sitio. Automáticamente detectadas en base tu archivo lockfile. (opcional)
```suggestion
                # package-manager: yarn # El gestor de paquetes de Node que debe instalar las dependencias y compilar tu proyecto. Automáticamente detectadas con base en tu archivo lockfile. (opcional)
```

2022-10-06 00:00 UTC, dreyfus92 commented on src/pages/es/guides/deploy/github.md
> +                # package-manager: yarn # El gestor de paquetes de Node que debe instalar las dependencias y compilar tu sitio. Automáticamente detectadas en base tu archivo lockfile. (opcional)
Lo voy a cambiar "con base a tu archivo".

2022-10-06 00:01 UTC, dreyfus92 commented on src/pages/es/guides/deploy/github.md
> +                # node-version: 16 # La version específica de Node que debe utilizarse para compilar tu sitio. La que está por defecto es la 16. (opcional)
`build your site` te suena a `compilar tu proyecto`?

2022-10-06 00:15 UTC, fredoist commented on src/pages/es/guides/deploy/github.md
> +                # node-version: 16 # La version específica de Node que debe utilizarse para compilar tu sitio. La que está por defecto es la 16. (opcional)
Sé que no es la traducción literal, pero en la documentación en español lo tradujimos como [proyecto de Astro](https://docs.astro.build/es/guides/deploy/buddy/#:~:text=construir%20tu%20proyecto), refiriéndonos a lo que sería en inglés "Astro Site". Es para mantener la consistencia en la documentación.

Igualmente no sé que opine @agustinmulet al respecto.

2022-10-06 00:36 UTC, dreyfus92 commented on src/pages/es/guides/deploy/github.md
> +                # node-version: 16 # La version específica de Node que debe utilizarse para compilar tu sitio. La que está por defecto es la 16. (opcional)
En los últimos commits hice el cambio a proyecto.

2022-10-06 00:53 UTC, fredoist approved these changes
LGTM ✅

2022-10-06 01:06 UTC, kevinzunigacuellar commented on src/pages/es/guides/deploy/github.md
> +                # node-version: 16 # La versión específica de Node que debe utilizarse para compilar tu proyecto. Porr defecto es la 16. (opcional)
```suggestion
                # node-version: 16 # La versión específica de Node que debe utilizarse para compilar tu proyecto. Por defecto es la 16. (opcional)
```

2022-10-06 01:12 UTC, merged