Translation of the content (Authoring Content) file to Spanish
withastro/docs pull request #1904
Opened 2022-10-24 20:16 UTC by Franqsanz

#### What kind of changes does this PR include?

- Translated content

#### Description
Added "content" (Authoring Content) file to Spanish.

---

I am participating in the Hacktoberfest. :)

Thank you very much!

2022-10-27 15:09 UTC, kevinzunigacuellar commented
Hello @Franqsanz! 

We appreciate all the work that you have done here. Unfortunately, this page has not been marked as `i18nReady: true` yet. I will move forward and keep this PR as a draft and postpone its review after our docs team approve its translation.

If you would like to contribute to the translation of other pages. Check out our [Translation Status Overview](https://github.com/withastro/docs/issues/438) or join our [discord](https://astro.build/chat).

2022-10-27 15:53 UTC, Franqsanz commented
Great, I'm glad! 🎉

2022-10-28 00:30 UTC, fredoist requested changes
Hola @Franqsanz , gracias por la contribución, te deje algunas sugerencias y comentarios referente al estilo de redacción, si pudieras considerarlos y hacer las correcciones para mantener el mismo estilo con las demás páginas en español. 👍🏼

2022-10-28 00:30 UTC, fredoist commented on src/pages/es/guides/content.md
> +- En archivos Markdown (`.md`), diseñados para facilitar la escritura de contenido de texto enriquecido.
Añadiré esta sugerencia para mantener actualizado este cambio en #1893 y estar a la par con la PR #1941

```suggestion
- En archivos Markdown (`.md` o [extensiones alternativas](/es/guides/markdown-content/)), diseñados para facilitar la escritura de contenido de texto enriquecido.
```

2022-10-28 00:30 UTC, fredoist commented on src/pages/es/guides/content.md
> +description: "Astro es una opción perfecta para su sitio centrado en el contenido: blogs, sitios de marketing, carteras y más. Cree su contenido directamente en su proyecto, o conecte su CMS de elecc
```suggestion
description: "Astro es una opción perfecta para tu proyecto centrado en el contenido: blogs, sitios de marketing, carteras y más. Crea tu contenido directamente en tu proyecto, o conecta tu CMS de elección."
```

2022-10-28 00:30 UTC, fredoist commented on src/pages/es/guides/content.md
> +Astro es una opción perfecta para su sitio centrado en el contenido: blogs, sitios de marketing, carteras y más.
Mantengamos el estilo de redacción usando los pronombres "**tu** proyecto", "Puede**s** escribir una publicación", etc. En este archivo se encuentran de la forma "su proyecto", "puede escribir", etc.

2022-10-28 10:10 UTC, Franqsanz commented
> Hola@Franqsanz, gracias por la contribución, te deje algunas sugerencias y comentarios referentes al estilo de redacción, si pudieras considerarlos y hacer las correcciones para mantener el mismo estilo con las demás páginas en español. 👍🏼

Hola, entiendo ahora lo chequeo y hago los cambios.

2022-10-28 10:58 UTC, Franqsanz commented
Si encuentran algún error no duden en hablarme! 👍

2022-10-31 01:22 UTC, fredoist requested changes
Gracias @Franqsanz , deje algunos comentarios con correcciones, puedes revisarlos.

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +description: "Astro es una opción perfecta para tu proyecto centrado en el contenido: blogs, sitios de marketing, carteras y más. Crea tu contenido directamente en tu proyecto, o conecta tu CMS de el
```suggestion
description: "Astro es una opción perfecta para tu proyecto centrado en el contenido: blogs, sitios de marketing, portafolios y más. Crea tu contenido directamente en tu proyecto, o conecta tu CMS de elección."
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +Astro es una opción perfecta para tu proyecto centrado en el contenido: blogs, sitios de marketing, carteras y más.
```suggestion
Astro es una opción perfecta para tu proyecto centrado en el contenido: blogs, sitios de marketing, portafolios y más.
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +Astro te ayuda a crear y presentar tu contenido. Puede escribir una publicación de blog directamente en Astro usando Markdown/MDX, o buscar tu contenido desde un CMS sin encabezado. Astro le permite
```suggestion
Astro te ayuda a crear y presentar tu contenido. Puedes escribir una publicación de blog directamente en Astro usando Markdown/MDX, o buscar tu contenido desde un headless CMS. Astro te permite crear un sitio en torno a tu contenido: puedes agregar una plantilla a tus páginas, crear un índice de publicaciones y configurar un feed RSS para permitir que los lectores se suscriban.
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +En Astro, puede crear tu contenido de varias maneras:
```suggestion
En Astro, puedes crear tu contenido de varias maneras: 
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +- En archivos MDX (`.mdx`), que le permiten incluir componentes y expresiones dinámicas en tu documento.
```suggestion
- En archivos MDX (`.mdx`), que te permiten incluir componentes y expresiones dinámicas en tu documento.
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +Cree y escriba un nuevo archivo `.md` en tu editor de código o traiga un archivo existente escrito en tu editor Markdown favorito. Algunos editores de Markdown en línea como [StackEdit](https://stack
```suggestion
Crea y escribe un nuevo archivo `.md` en tu editor de código o trae un archivo existente escrito en tu editor Markdown favorito. Algunos editores de Markdown en línea como [StackEdit](https://stackedit.io/) y [Dillinger](https://dillinger.io) incluso te permitirán editar y sincronizar tu trabajo con tu repositorio de Astro almacenado en GitHub.
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +📚 Learn more about [escribir contenido Markdown en Astro](/es/guides/markdown-content/).
```suggestion
📚 Aprende más sobre [escribir contenido Markdown en Astro](/es/guides/markdown-content/).
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +### Autoría MDX
```suggestion
### Autoría MDX

```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +Si agrega la integración MDX a tu proyecto, también puedes escribir una publicación usando archivos `.mdx`, que le permiten incluir expresiones JavaScript y componentes personalizados dentro de tu Ma
```suggestion
Si añades la integración MDX a tu proyecto, también puedes escribir una publicación usando archivos `.mdx`, que te permiten incluir expresiones JavaScript y componentes personalizados dentro de tu Markdown. Esto incluye tanto [componentes de Astro](/es/core-concepts/astro-components/) estáticos y [componentes del framework](/es/core-concepts/framework-components/) interactivos. Agrega elementos de la interfaz de usuario como un banner o un carrusel interactivo directamente en tu texto para convertir tu contenido en páginas web completas.
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +Escriba y edite archivos `.mdx` directamente en tu editor de código, junto con sus archivos de proyecto.
```suggestion
Escribe y edita archivos `.mdx` directamente en tu editor de código, junto con tus archivos del proyecto.
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +### Autoría de CMS sin cabeza
```suggestion
### Autoría de headless CMS
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +Escriba publicaciones de blog en tu sistema de administración de contenido (CMS) existente, como Storyblok, WordPress o Contentful. Algunos CMS, como Storyblok, brindan un [integración Astro](https:/
```suggestion
Escribe publicaciones de blog en tu sistema de administración de contenido (CMS) existente, como Storyblok, WordPress o Contentful. Algunos CMS, como Storyblok, proveen una [integración de Astro](https://www.storyblok.com/mp/announcing-storyblok-astro) oficial. Otros exponen un SDK de JavaScript que las páginas de Astro pueden usar para [obtener tu contenido remoto](/es/guides/data-fetching/#fetching-de-datos-desde-un-headless-cms).
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +Los archivos Markdown y MDX que viven en tu `src/pages` directorio generarán automáticamente páginas en tu proyecto utilizando el [enrutamiento basado en archivos](/es/core-concepts/routing/) de Astr
```suggestion
Los archivos Markdown y MDX que viven en tu directorio `src/pages` generarán automáticamente páginas en tu proyecto utilizando el [enrutamiento basado en archivos](/es/core-concepts/routing/) de Astro, creado en una URL correspondiente a la ruta del archivo de la publicación. 
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +También puede optar por mantener sus archivos Markdown y MDX fuera del directorio `src/pages` y, en tu lugar, [importar tu contenido](/es/guides/markdown-content/#importando-markdown) en páginas `.as
```suggestion
También puedes optar por mantener tus archivos Markdown y MDX fuera del directorio `src/pages` y, en su lugar, [importar tu contenido](/es/guides/markdown-content/#importando-markdown) en páginas `.astro`.
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +## Exhibiendo tu contenido
```suggestion
## Mostrando tu contenido
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +Para crear funciones comunes para organizar y mostrar tu contenido, como un archivo de blog o una página para cada etiqueta de blog, Astro le permite [obtener nombres de archivo y metadatos](/es/refe
```suggestion
Para crear funciones comunes para organizar y mostrar tu contenido, como un archivo de blog o una página para cada etiqueta de blog, Astro te permite [obtener nombres de archivo y metadatos](/es/reference/api-reference/#astroglob) desde tu Markdown y MDX frontmatter y utilizarlos para generar contenido de página y rutas.
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +## Integraciones comunitarias
```suggestion
## Integraciones de la comunidad
```

2022-10-31 01:22 UTC, fredoist commented on src/pages/es/guides/content.md
> +Si está escribiendo tu contenido en un CMS, puede obtener sus publicaciones y usar [enrutamiento dinámico](/es/core-concepts/routing/#rutas-dinámicas) usar un archivo `.astro` para generar una ruta p
```suggestion
Si estás escribiendo tu contenido en un CMS, puedes obtener tus publicaciones y usar el [enrutamiento dinámico](/es/core-concepts/routing/#rutas-dinámicas) para usar un archivo `.astro` para generar una ruta para cada publicación. En el modo estático predeterminado de Astro, estas rutas se generan en el momento de la compilación. Si optas por el [modo SSR](/es/guides/server-side-rendering/), respondes a una petición en tiempo de ejecución y obtienes el contenido a bajo petición.
```

2022-10-31 11:16 UTC, Franqsanz commented
Hola, pido una disculpa por todos los errores. Gracias por la ayuda!

2022-10-31 19:12 UTC, fredoist commented on src/pages/es/guides/content.md
> +Si añades la integración MDX a tu proyecto, también puedes escribir una publicación usando archivos `.mdx`, que te permiten incluir expresiones JavaScript y componentes personalizados dentro de tu Ma
Una última corrección @Franqsanz :)

```suggestion
Si añades la integración MDX a tu proyecto, también puedes escribir una publicación usando archivos `.mdx`, que te permiten incluir expresiones JavaScript y componentes personalizados dentro de tu Markdown. Esto incluye tanto [componentes de Astro](/es/core-concepts/astro-components/) estáticos y [componentes del framework](/es/core-concepts/framework-components/) interactivos. Agrega elementos de la interfaz de usuario como un banner o un carrusel interactivo directamente en tu texto para convertir tu contenido en páginas web completas.
```

2022-10-31 19:57 UTC, fredoist approved these changes
Gracias @Franqsanz 

LGTM ✅

2022-10-31 19:59 UTC, Franqsanz commented
De nada @fredoist, una disculpa nuevamente por tantos errores. 😅

2022-11-01 14:59 UTC, dreyfus92 commented
LGTM!

2022-11-01 15:15 UTC, merged

2022-11-01 15:15 UTC, kevinzunigacuellar commented
gracias @dreyfus92 , @Franqsanz and @fredoist 🚀