i18n(es): Added `cms.md` translation
withastro/docs pull request #1992
Opened 2022-11-05 02:45 UTC by dreyfus92

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Translated `cmd.md` to spanish https://github.com/withastro/docs/pull/1975

2022-11-05 10:55 UTC, delucis reviewed
Woah! That was quick 🤯 

Might be good to include the additions to `nav.ts` and `ui.ts` too:

https://github.com/withastro/docs/blob/8d49a475ca57574baa5bb9e75231a266db409f3d/src/i18n/en/ui.ts#L48-L49

☝️ Translate this heading in `src/i18n/es/ui.ts`

https://github.com/withastro/docs/blob/8d49a475ca57574baa5bb9e75231a266db409f3d/src/i18n/en/nav.ts#L60

☝️ Translate this navigation sidebar label in `src/i18n/es/nav.ts`, something like:

```js
'guides/cms': 'TRANSLATED LABEL',
```

2022-11-05 18:50 UTC, kevinzunigacuellar reviewed
increiblemente rapido 🇪🇸, deje algunos comentarios. Una duda no entendi el termino WYSIWYG quizas debamos explicarlo en parentesis?

2022-11-05 18:50 UTC, kevinzunigacuellar commented on src/pages/es/guides/cms.md
> +**Ready to connect a Headless CMS to your Astro project?** Follow one of our guides to integrate a CMS.
```suggestion
```

2022-11-05 18:50 UTC, kevinzunigacuellar commented on src/pages/es/guides/cms.md
> +**¿Listo para conectar un Headless CMS a su proyecto Astro?** Siga una de nuestras guías para integrar un CMS.
```suggestion
**¿Listo para conectar un Headless CMS a tu proyecto Astro?** Sigue una de nuestras guías para integrar un CMS.
```

2022-11-05 18:50 UTC, kevinzunigacuellar commented on src/pages/es/guides/cms.md
> +Un sistema de gestión de contenido le permite escribir contenido y administrar activos fuera de su proyecto Astro.
```suggestion
Un sistema de gestión de contenido te permite escribir contenido y administrar activos fuera de tu proyecto Astro.
```

2022-11-05 18:50 UTC, kevinzunigacuellar commented on src/pages/es/guides/cms.md
> +Tu proyecto Astro luego puede recuperar su contenido de su CMS y mostrarlo, donde y como quieras en tu sitio.
```suggestion
Tu proyecto Astro luego puede obtener el contenido de tu CMS y mostrarlo, donde y como quieras en tu sitio.
```

2022-11-05 18:50 UTC, kevinzunigacuellar commented on src/pages/es/guides/cms.md
> +Debido a que Astro se ocupa de la _presentación_ de tu contenido, tu vas querer elegir un CMS _headless_, como los de la lista anterior. Esto significa que el CMS le ayuda a escribir su contenido, pe
```suggestion
Debido a que Astro se ocupa de la _presentación_ de tu contenido, procura elegir un CMS _headless_, como los de la lista anterior. Esto significa que el CMS te ayuda a escribir tu contenido, pero no genera un sitio que lo muestre. En su lugar, obtiene los datos de tu contenido y los usa en tu proyecto Astro.
```

2022-11-05 18:50 UTC, kevinzunigacuellar commented on src/pages/es/guides/cms.md
> +Algunos CMSes headless, como Storyblok, proporcionan una [integración](/es/guides/integrations-guide/) de Astro que ayuda a recuperar el contenido específicamente para un sitio Astro. Otros proporcio
```suggestion
Algunos CMSes headless, como Storyblok, proporcionan una [integración](/es/guides/integrations-guide/) de Astro que te ayuda a recuperar el contenido específicamente para un sitio Astro. Otros proporcionan un SDK de JavaScript, una biblioteca que instalas y usas para recuperar tu contenido remoto.
```

2022-11-05 18:50 UTC, kevinzunigacuellar commented on src/pages/es/guides/cms.md
> +¡Si! Astro proporciona formas integradas de [autorizar contenido](/es/guides/content/), incluido el soporte para páginas de Markdown.
```suggestion
¡Si! Astro proporciona formas integradas para [crear contenido](/es/guides/content/), incluyendo el soporte para páginas de Markdown.
```

2022-11-05 19:13 UTC, dreyfus92 commented
> increiblemente rapido 🇪🇸, deje algunos comentarios. Una duda no entendi el termino WYSIWYG quizas debamos explicarlo en parentesis?

WYSIWYG = What You See Is What You Get

2022-11-05 23:05 UTC, agustinmulet requested changes
Pequeños cambios sugeridos. Buen trabajo! 😤

2022-11-05 23:05 UTC, agustinmulet commented on src/pages/es/guides/cms.md
> +Tome en cuenta que muchas de estas páginas son **talones**: ¡Son colecciones de recursos esperando su contribución!
```suggestion
Ten en cuenta que muchas de estas páginas son **talones**: ¡Son colecciones de recursos esperando tu contribución!
```

2022-11-05 23:05 UTC, agustinmulet commented on src/pages/es/guides/cms.md
> +Un CMS puede ser útil para el contenido que sigue una estructura particular, a menudo te brinda una experiencia de panel de control y herramientas de edición WYSIWYG(Lo que ves es lo que obtienes). P
```suggestion
Un CMS puede ser útil para el contenido que sigue una estructura particular, a menudo te brinda una experiencia de panel de control y herramientas de edición WYSIWYG (Lo que ves es lo que obtienes). Puedes usar un CMS para escribir publicaciones de blog usando el editor de texto enriquecido de un CMS en lugar de archivos Markdown. O puedes usar un CMS para mantener listados de productos para una tienda en línea, haciendo que ciertos campos sean obligatorios para evitar listados incompletos.
```

2022-11-05 23:05 UTC, agustinmulet commented on src/pages/es/guides/cms.md
> +¡Si! Astro proporciona formas integradas para [crear contenido](/es/guides/content/), incluyendo el soporte para páginas de Markdown.
```suggestion
¡Sí! Astro proporciona formas integradas para [crear contenido](/es/guides/content/), incluyendo el soporte para páginas de Markdown.
```

2022-11-06 02:18 UTC, merged

2022-11-06 02:18 UTC, kevinzunigacuellar commented
gracias @agustinmulet y @dreyfus92 😇