Translate of `edgio.md`
withastro/docs pull request #2002
Opened 2022-11-05 21:24 UTC by dreyfus92

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Translation of `edgio.md` based on https://github.com/withastro/docs/pull/1939

2022-11-05 23:11 UTC, agustinmulet requested changes
Pequeñas sugerencias, muy buen trabajo! 💪
Es posible cambiar el título del PR para que contenga `i18n(es):` ? Así es más trackeable y entendible qué idioma se está mergeando

2022-11-05 23:11 UTC, agustinmulet commented on src/pages/es/guides/deploy/edgio.md
> +description: Como desplegar tu sitio Astro en la web usando Edgio.
```suggestion
description: Cómo desplegar tu sitio Astro en la web usando Edgio.
```

2022-11-05 23:11 UTC, agustinmulet commented on src/pages/es/guides/deploy/edgio.md
> +Tu puedes desplegar tu proyecto Astro en [Edgio](https://www.edg.io/), una plataforma de CDN y edge para desplegar, proteger y acelerar sitios web y APIs.
```suggestion
Puedes desplegar tu proyecto Astro en [Edgio](https://www.edg.io/), una plataforma de CDN y edge para desplegar, proteger y acelerar sitios web y APIs.
```

2022-11-05 23:11 UTC, agustinmulet commented on src/pages/es/guides/deploy/edgio.md
> +¡Hechale un vistazo a [la guía de Astro en la documentación de Edgio](https://docs.edg.io/guides/astro)!
```suggestion
¡Échale un vistazo a [la guía de Astro en la documentación de Edgio](https://docs.edg.io/guides/astro)!
```

2022-11-05 23:11 UTC, agustinmulet commented on src/pages/es/guides/deploy/edgio.md
> +2. Agrega Edgio a tu sitio Astro
```suggestion
2. Agrega Edgio a tu sitio Astro.
```

2022-11-05 23:11 UTC, agustinmulet commented on src/pages/es/guides/deploy/edgio.md
> +3. (Opcional) Habilita el Server Side Rendering
```suggestion
3. (Opcional) Habilita el Server Side Rendering.
```

2022-11-05 23:11 UTC, agustinmulet commented on src/pages/es/guides/deploy/edgio.md
> +4. Despliega a Edgio
```suggestion
4. Despliega a Edgio.
```

2022-11-06 02:24 UTC, kevinzunigacuellar reviewed
muchas gracias por la PR, deje un par de comentarios

2022-11-06 02:24 UTC, kevinzunigacuellar commented on src/pages/es/guides/deploy/edgio.md
> +Puedes desplegar tu proyecto Astro en [Edgio](https://www.edg.io/), una plataforma de CDN y edge para desplegar, proteger y acelerar sitios web y APIs.
```suggestion
Puedes desplegar tu proyecto de Astro en [Edgio](https://www.edg.io/), una plataforma de CDN y edge para desplegar, proteger y acelerar sitios web y APIs.
```

2022-11-06 02:24 UTC, kevinzunigacuellar commented on src/pages/es/guides/deploy/edgio.md
> +    // edgio.config.js
```suggestion
    ```js title="edgio.config.js" ins={2,5-9}
```

2022-11-06 03:10 UTC, kevinzunigacuellar commented on src/pages/es/guides/deploy/edgio.md
> +    ```js title="edgio.config.js" ins={2,5-9}
```suggestion
    ```js title="edgio.config.js" ins={1,4-8}
```

2022-11-06 03:11 UTC, dreyfus92 commented
Gracias por sus reviews @agustinmulet y @kevinzunigacuellar

2022-11-06 04:03 UTC, agustinmulet approved these changes
LGTM! ✅

2022-11-06 04:11 UTC, merged

2022-11-06 04:12 UTC, kevinzunigacuellar commented
gracias @dreyfus92 y @agustinmulet 💜