docs: Add german translation of Edgio deployment guide
withastro/docs pull request #2340
Opened 2023-01-10 15:05 UTC by rishi-raj-jain

- Translated content

2023-01-11 16:56 UTC, Dezaku commented
Hi,
Laut dem [Style Guide](https://github.com/withastro/docs/blob/main/src/i18n/de/README.md) sollen wir die informelle Ansprache mit kleinem "du" statt "Du" oder "Sie" nutzen. Dazu steht [hier](https://github.com/withastro/docs/pull/2340/commits/e3f77208a8f17faa77ebd4c719b421cb514a7d98) die Zeile 14 in einem Satzbau, welcher mehr wie eine Frage klingt. Stattdessen würde ich es zu `Wie man veröffentlicht` ändern.

2023-01-14 20:25 UTC, campino2k requested changes
This is not needed in translated lages

2023-01-14 20:32 UTC, campino2k requested changes
Sorry für die Kürze, gerade nur mit dem Handy drübergeschaut

2023-01-14 20:32 UTC, campino2k commented on src/pages/de/guides/deploy/edgio.mdx
> +Schauen Sie sich den [Astro-Leitfaden in den Dokumentationen von Edgio an](https://docs.edg.io/guides/astro)!
"in der Dokumentation von Edgio"

2023-01-14 20:32 UTC, campino2k commented on src/pages/de/guides/deploy/edgio.mdx
> +3. (Optional) Aktivieren Sie das Serverseitiges Rendering
"Aktiviere das serverseitige Rendering"

2023-01-14 20:32 UTC, campino2k commented on src/pages/de/guides/deploy/edgio.mdx
> +Sie können Ihr Astro-Projekt auf [Edgio](https://www.edg.io/) veröffentlichen, einer Edge- und CDN-Plattform zum Veröffentlichen, Schützen und Beschleunigen von Websites und APIs.
"Du kannst dein Astro-Projekt..."

2023-01-14 20:32 UTC, campino2k commented on src/pages/de/guides/deploy/edgio.mdx
> +1. Installieren Sie die [the Edgio CLI](https://docs.edg.io/guides/cli) global über die Befehlszeile, falls noch nicht geschehen.
"Installiere die Edgio-CLI

2023-01-14 20:32 UTC, campino2k commented on src/pages/de/guides/deploy/edgio.mdx
> +2. Fügen Sie Edgio Ihrer Astro-Seite hinzu.
"Füge Edgio deiner Astro-Seite hinzu"

2023-01-14 20:32 UTC, campino2k commented on src/pages/de/guides/deploy/edgio.mdx
> +    Nachdem Sie [@astrojs/node with Astro](/de/guides/integrations-guide/node/), konfiguriert haben, geben Sie den Pfad der Serverdatei in der Datei `edgio.config.js` an, wie unten gezeigt:
"Nachdem du .... hast"..., "gib den Pfad der Serverdatei ..."

2023-01-14 20:32 UTC, campino2k commented on src/pages/de/guides/deploy/edgio.mdx
> +4. Veröffentlichen Sie auf Edgio
"Veröffentliche auf Edgio"

2023-01-24 21:26 UTC, delucis commented
Hey @rishi-raj-jain, are you still planning to update this PR?

2023-02-06 20:01 UTC, delucis commented
Going to close this as it hasn’t seen any activity. Please feel to re-open if you want to address the requested changes @rishi-raj-jain. Or if anyone else wants to pick up the translated content here in a new PR, you’re very welcome to!

2023-02-06 20:01 UTC, closed without merging