i18n(fr): Update rss.mdx
withastro/docs pull request #2350
Opened 2023-01-11 10:21 UTC by pioupia

#### What kind of changes does this PR include?

- Translated content

#### Description

- What does this PR change? Give us a brief description.
Updating the page `rss.mdx` in French.

2023-01-11 10:39 UTC, pioupia commented
Needs to translate `markdown-content` page for the compatibility with this page.

2023-01-30 18:28 UTC, AndiKod commented on src/pages/fr/guides/rss.mdx
> +1. [Un résultat de `import.meta.glob(...)`](#1-avec-un-résultat-importmetaglob) **(utilisez cette option uniquement que pour les fichiers `.md` à l'intérieur du répertoire `src/pages/`)**
Hi,
The "que" in the string "uniquement que pour les fichiers" should be removed. 

It looks like a mix of the different ways to say the same thing, thus not a real expression.

2023-01-30 18:30 UTC, AndiKod requested changes
Hi,
Line 72 or the additions...
The "que" in the string "uniquement que pour les fichiers" should be removed.

It looks like a mix of the different ways to say the same thing, thus not a real expression.

2023-02-06 09:10 UTC, AndiKod approved these changes
I can't find anything misspelled or out of place in that commit, seems good enough.

2023-02-06 18:31 UTC, delucis commented
This is ready to merge, right @pioupia?

2023-02-06 18:49 UTC, AndiKod approved these changes
No spelling errors in that commit.

2023-02-06 20:03 UTC, delucis approved these changes
Great! Thanks @pioupia and @AndiKod 🙌

2023-02-06 20:12 UTC, merged