i18n(es): Add translate page /guides/testing/
withastro/docs pull request #2456
Opened 2023-01-24 19:54 UTC by vab1997

#### What kind of changes does this PR include?

- Translated content

#### Description

Added Spanish translation for `testing.mdx`.

2023-01-24 23:03 UTC, dreyfus92 requested changes
Gracias por la PR @vab1997, te dejo algunas sugerencias 🚀

2023-01-24 23:03 UTC, dreyfus92 commented on src/pages/es/guides/testing.mdx
> +Alternativamente, puede instalar Playwright dentro de su proyecto de Astro usando el gestor de paquetes de su elección. Sigue los pasos de la CLI para elegir JavaScript/TypeScript, el nombre de tu ca
```suggestion
Alternativamente, puedes instalar Playwright dentro de tu proyecto de Astro usando el gestor de paquetes de tu elección. Sigue los pasos de la CLI para elegir JavaScript/TypeScript, el nombre de tu carpeta de tests y añadir un workflow opcional de Github Actions.
```

2023-01-25 00:01 UTC, vab1997 commented
Gracias @dreyfus92 por las sugerencias, ya fuero corregidas 👍

2023-01-25 02:04 UTC, dreyfus92 approved these changes
LGTM ✅

2023-01-25 02:22 UTC, merged