i18n(fr): Update core-concepts/routing.mdx
withastro/docs pull request #2490
Opened 2023-01-27 15:47 UTC by thomasbnt

#### What kind of changes does this PR include?

- Translated content

#### Description

About this update https://github.com/withastro/docs/commits/main/src/pages/en/core-concepts/routing.mdx?since=2022-06-26T22:23:34.000Z

2023-01-28 06:36 UTC, pioupia approved these changes

2023-01-28 11:45 UTC, MoustaphaDev commented
Merci @thomasbnt pour cette PR!

Je voulais juste signaler que cette page n'a pas été mise à jour depuis un moment et donc beaucoup de traductions manquantes. Fais moi savoir si tu préfère que je fasse le reste 🙂

2023-01-28 15:45 UTC, thomasbnt commented
WIP

2023-01-28 18:48 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +Astro utilise la standarlisation HTML [`<a>` elements](https://developer.mozilla.org/fr-FR/docs/Web/HTML/Element/a) pour naviguer entre les routes. Il n'y a pas de composant `<Link>` spécifique au fr
Je suggère cette reformulation
```suggestion
Astro utilise des [éléments HTML`<a>`](https://developer.mozilla.org/fr-FR/docs/Web/HTML/Element/a) standards pour naviguer entre les routes. Il n'y a pas de composant `<Link>` spécifique au framework fourni.
```

2023-01-28 18:51 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +Un fichier de page Astro peut spécifier des paramètres de route dynamiques dans son nom de fichier pour générer les pages correspondantes. Par exemple, vous pouvez créer un fichier `authors/[author].
Nit: Je suis pas sûr si ça vaut le coup d'update ça, juste mon ressenti 🙂
```suggestion
Un fichier de page Astro peut spécifier des paramètres de route dynamiques dans son nom de fichier pour générer les pages correspondantes. Par exemple, vous pouvez créer un fichier `authors/[author].astro` qui génère une page de biographie pour chaque auteur de votre blog. `author` devient un _paramètre_ que vous pouvez accéder depuis l'intérieur de la page.
```

2023-01-28 18:55 UTC, thomasbnt commented on src/pages/fr/core-concepts/routing.mdx
> +Un fichier de page Astro peut spécifier des paramètres de route dynamiques dans son nom de fichier pour générer les pages correspondantes. Par exemple, vous pouvez créer un fichier `authors/[author].
Ça me semble plus lisible ton texte.

2023-01-28 18:56 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +<div>Bon chien, {dog}!</div>
**Très pédante suggestion en approche**
```suggestion
<div>Bon chien, {dog} !</div>
```

2023-01-28 18:58 UTC, thomasbnt commented on src/pages/fr/core-concepts/routing.mdx
> +<div>Bon chien, {dog}!</div>
Owwh j'ai fait cette faute ! 😆

2023-01-28 18:58 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +Cela va générer `/fr-v1/info` et `/fr-v2/info`.
```suggestion
Cela va générer `/en-v1/info` et `/fr-v2/info`.
```

2023-01-28 19:02 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +Les paramètres de rest peuvent être utilisés avec **d'autres paramètres nommés**. Par exemple, nous pourrions représenter le visualiseur de fichiers de GitHub avec une route dynamique comme celle-ci
Je suggère ça pour la consistance
```suggestion
Les paramètres rest peuvent être utilisés avec **d'autres paramètres nommés**. Par exemple, nous pourrions représenter le visualiseur de fichiers de GitHub avec une route dynamique comme celle-ci :
```

2023-01-28 19:05 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +In this example, a request for `/withastro/astro/tree/main/docs/public/favicon.svg` would be split into the following named parameters:
Ajout de traduction
```suggestion
Dans cet exemple, une requête pour `/withastro/astro/tree/main/docs/public/favicon.svg` serait divisée en les paramètres nommés suivants :
```

2023-01-28 19:13 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +Ici, nous utilisons un paramètre de repos (`[...slug]`) et la fonctionnalité [`props`](/fr/reference/api-reference/#data-passing-with-props) de `getStaticPaths()` pour générer des pages pour des slug
```suggestion
Ici, nous utilisons un paramètre rest (`[...slug]`) et la fonctionnalité [`props`](/fr/reference/api-reference/#data-passing-with-props) de `getStaticPaths()` pour générer des pages pour des slugs de différentes profondeurs.
```

2023-01-28 19:14 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +- Les routes dynamiques utilisant des paramètres nommés sont prioritaires par rapport aux paramètres de repos.
```suggestion
- Les routes dynamiques utilisant des paramètres nommés sont prioritaires par rapport aux paramètres rest.
```

2023-01-28 19:16 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +Dans l'exemple ci-dessus, voici quelques exemples de la façon dont les règles vont faire correspondre une URL demandée à la route utilisée pour construire le HTML :
```suggestion
Étant donné l'exemple ci-dessus, voici quelques exemples de la façon dont les règles vont faire correspondre une URL demandée à la route utilisée pour construire le HTML :
```

2023-01-28 19:19 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
>  Vous pouvez utiliser la fonction `paginate()` pour générer ces pages pour un tableau de valeurs comme suis :
```suggestion
Vous pouvez utiliser la fonction `paginate()` pour générer ces pages pour un tableau de valeurs comme suit :
```

2023-01-28 19:29 UTC, MoustaphaDev commented on src/pages/fr/core-concepts/routing.mdx
> +  - _hidden-page.astro
Juste pour la consistence
```suggestion
  - _répertoire-caché/
    - page1.md
    - page2.md
  - _page-cachée.astro
```

2023-01-28 20:27 UTC, pioupia requested changes

2023-01-28 20:27 UTC, pioupia commented on src/pages/fr/core-concepts/routing.mdx
> +Un fichier de page Astro peut spécifier des paramètres de route dynamiques dans son nom de fichier pour générer les pages correspondantes. Par exemple, vous pouvez créer un fichier `authors/[author].
J'ai du mal avec "_paramètre_ que vous pouvez accéder". Je ne sais pas si ma version est mieux, mais je la précise au cas où.

```suggestion
Un fichier de page Astro peut spécifier des paramètres de route dynamiques dans son nom de fichier pour générer les pages correspondantes. Par exemple, vous pouvez créer un fichier `authors/[author].astro` qui génère une page de biographie pour chaque auteur de votre blog. `author` devient un _paramètre_ accessible depuis l'intérieur de la page.
```

2023-01-28 20:27 UTC, pioupia commented on src/pages/fr/core-concepts/routing.mdx
> +En mode sortie statique par défaut d'Astro, ces pages sont générées au moment de la construction, et vous devez donc prédéterminer la liste des `author` qui obtiennent un fichier correspondant. En mo
Je suis pas sûr que ça colle parfaitement à la version anglaise, mais ça me parait plus clair.
```suggestion
Dans le mode de sortie statique par défaut d'Astro, ces pages sont générées au moment de la construction, et vous devez donc prédéterminer la liste des `author` qui obtiennent un fichier correspondant. En mode SSR, une page sera générée sur demande pour toute route qui correspond.
```

2023-01-28 20:27 UTC, pioupia commented on src/pages/fr/core-concepts/routing.mdx
> +Si vous avez besoin de plus de flexibilité dans le routage de vos URL, vous pouvez utiliser un [paramètre REST](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parame
C'est un micro-détail, mais la documentation existe en Français si besoin.
```suggestion
Si vous avez besoin de plus de flexibilité dans le routage de vos URL, vous pouvez utiliser un [paramètre REST](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Functions/rest_parameters) (`[...path]`) dans votre nom de fichier `.astro` pour correspondre aux chemins de fichiers de n'importe quelle profondeur :
```

2023-01-28 20:57 UTC, thomasbnt commented on src/pages/fr/core-concepts/routing.mdx
> +Si vous avez besoin de plus de flexibilité dans le routage de vos URL, vous pouvez utiliser un [paramètre REST](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parame
Ouip merci!

2023-01-28 21:01 UTC, thomasbnt commented
Merci à vous deux pour vos review @MoustaphaDev & @pioupia

2023-01-29 00:01 UTC, MoustaphaDev approved these changes
Génial, merci !

2023-01-29 00:01 UTC, merged