i18(fr): Translation of `client-side-scripts.mdx`
withastro/docs pull request #2570
Opened 2023-02-05 01:43 UTC by dreyfus92

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translation of `client-side-scripts.mdx` to french.

2023-02-06 17:39 UTC, pioupia requested changes
Beaucoup de problèmes à résoudre (je me suis arrêté à la ligne 56).
Il vaut mieux dire `balise HTML` que `tag` car la traduction française existe. N'hésites pas à recopier les mots qui sont dans des "guillemets de code (` \` `)".

2023-02-06 17:39 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Vous pouvez ajouter de l'interactivité à vos composants Astro sans [utiliser un framework UI](/fr/core-concepts/framework-components/) comme React, Svelte, Vue, etc. en utilisant le HTML tag `<script
```suggestion
Vous pouvez ajouter de l'interactivité à vos composants Astro sans [utiliser un framework UI](/fr/core-concepts/framework-components/) comme React, Svelte, Vue, etc. en utilisant la balise HTML `<script>`. Cela vous permet d'exécuter votre JavaScript dans le navigateur et ajouter des fonctionnalités à vos composants Astro.
```

2023-02-06 17:39 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +In `.astro` files, you can add client-side JavaScript by adding one (or more) `<script>` tags.
La ligne devrait être retirée....

2023-02-06 17:39 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Dans les fichiers `.astro`, vous pouvez ajouter du JavaScript côté client en ajoutant un (ou plusieurs) tags `<script>`.
```suggestion
Dans les fichiers `.astro`, vous pouvez ajouter du JavaScript côté client en ajoutant une (ou plusieurs) balises `<script>`.
```

2023-02-06 17:39 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Dans cet example, l'ajout du composant `<Hello />` à un page enregistrera un message sur la console du navigateur.
```suggestion
Dans cet example, l'ajout du composant `<Hello />` à un page enregistrera un message dans la console du navigateur.
```

2023-02-06 17:39 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Par défaut, les tags `<script>` sont processés par Astro.
```suggestion
Par défaut, les balises `<script>` sont processées par Astro.
```

2023-02-06 17:39 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +- Quelques importations seront groupées, vous permettant d'importer des fichiers locaux ou des modules Node.
```suggestion
- Toutes les importations seront regroupées, ce qui vous permettra d'importer des fichiers locaux ou des modules Node.
```

2023-02-06 17:39 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +  // Les imports lacales ne sont pas résolues et ne fonctionneront pas.
```suggestion
  // Les importations locales ne sont pas résolues et ne fonctionneront pas.
```

2023-02-06 17:39 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +  // Si dans un composant, répète chaque fois que le composant est utilisé.
```suggestion
  // S'il se trouve dans un composant, il se répète chaque fois que le composant est utilisé.
```

2023-02-06 17:39 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +L'ajout de `type=module` ou d'un attribut autre que `src` à un tag `<script>` désactivera le comportement de regroupement par défaut d'Astro, traitant le tag comme s'il avait une directive `is:line`.
```suggestion
L'ajout de `type="module"` ou de tout autre attribut que `src` à une balise `<script>` désactivera le comportement de regroupement par défaut d'Astro, en traitant la balise comme si elle avait une directive `is:inline`.
```

2023-02-06 18:31 UTC, dreyfus92 commented
Merci pour le review @pioupia 🙏🏻

2023-02-07 02:52 UTC, thomasbnt approved these changes

2023-02-07 12:30 UTC, pioupia requested changes
Encore pas mal de modifications... Je me suis arrêté à la ligne 117.

2023-02-07 12:30 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +📚 Consultez notre [directives reference](/fr/reference/directives-reference/#script--style-directives) pour plus d'information sur les directives disponible pour les balises `<script>`.
```suggestion
📚 Consultez notre page [référence des directives](/fr/reference/directives-reference/#script--style-directives) pour plus d'informations sur les directives disponibles des balises `<script>`.
```

2023-02-07 12:30 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +<!-- chemin absolu vers script à `src/scripts/local.js` -->
```suggestion
<!-- chemin absolu du script à `public/my-script.js` -->
```

2023-02-07 12:30 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +<!-- full URL to a script on a remote server -->
Ligne à supprimer...
```suggestion
```

2023-02-07 12:30 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +### Gérer les évènements `onclick` et autres
```suggestion
### Gérer le `onclick` et d'autres évènements
```

2023-02-07 12:30 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Certains frameworks d'interface utilisent une syntaxe personnalisée pour la gestion d'événements comme `onClick={...}`  (React/Preact) ou `@click="..."` (Vue). Astro suit le HTML standard de plus prè
```suggestion
Certains frameworks d'interface utilisent une syntaxe personnalisée pour la gestion d'événements comme `onClick={...}` (React/Preact) ou `@click="..."` (Vue). Astro suit le HTML standard de plus près et n’utilise pas de syntaxe personnalisée pour les évènements.
```

2023-02-07 12:30 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Si vous avez plusieurs composants `<AlertButton />` sur une page, Astro n'exécutera pas le script plusieurs fois. Les scripts son groupés et inclus seulement une fois par page. L'utilisation de `quer
```suggestion
Si vous avez plusieurs composants `<AlertButton />` sur une page, Astro n'exécutera pas le script plusieurs fois. Les scripts sont groupés et inclus seulement une fois par page. L'utilisation de `querySelectorAll` garantit que ce script attache l'écouteur d'événement à chaque bouton de la classe `alert` trouvé sur la page.
```

2023-02-07 16:52 UTC, pioupia requested changes

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +### Composants Web avec éléments personnalisés
```suggestion
### Composants Web avec des éléments personnalisés
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Vous pouvez créer vos propres éléments HTML avec un comportement personnalisé en utilisant le standard Composants Web. La définition d'un [élément personnalisé](https://developer.mozilla.org/fr/docs/
```suggestion
Vous pouvez créer vos propres éléments HTML avec un comportement personnalisé en utilisant les composants web standards. La définition d'un [élément personnalisé](https://developer.mozilla.org/fr/docs/Web/Web_Components/Using_custom_elements) dans un composant `.astro` vous permet de créer des composants interactifs sans avoir besoin d'une bibliothèque d'interface utilisateur.
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Dans cet exemple, nous définissons un nouvel élément HTML `<astro-heart>` qui suit le nombre de fois que vous cliquez sur le bouton cœur et met à jour le `<span>` avec le dernier décompte.
```suggestion
Dans cet exemple, nous définissons un nouvel élément HTML `<astro-heart>` qui suit le nombre de fois que vous cliquez sur le bouton cœur et met à jour le `<span>` avec le dernier compte.
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +<!-- Enveloppez les éléments dans notre élément personnalisé "astro-heart" -->
```suggestion
<!-- Enveloppez les éléments du composant dans notre élément personnalisé "astro-heart". -->
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +  // Define le comportement pour notre nouveau type d'élément HTML.
```suggestion
  // Définir le comportement de notre nouveau type d'élément HTML.
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +      // Chaque fois que le bouton est cliqué, met à jour le décompte.
```suggestion
      // À chaque fois que le bouton est cliqué, on met à jour le compte.
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +1. Au lieu de chercher dans toute la page en utilisant `document.querySelector()`, vous pouvez utiliser `this.querySelector()`, qui ne recherche que dans l'instance courante de l'élément personnalisé
```suggestion
1. Au lieu de chercher dans toute la page en utilisant `document.querySelector()`, vous pouvez utiliser `this.querySelector()`, qui ne recherche que dans l'instance courante de l'élément personnalisé. Cela facilite le travail en ne travaillant seulement qu'avec les enfants d'une seule instance de composant à la fois.
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Vous pouvez en savoir plus sur les éléments personnalisés dans [guide des composants Web réutilisables de web.dev](https://web.dev/custom-elements-v1/) et [Introduction aux composants personnalisés d
```suggestion
Vous pouvez en savoir plus sur les éléments personnalisés dans le [guide des composants Web réutilisables de web.dev](https://web.dev/custom-elements-v1/) et dans l'[introduction aux composants personnalisés de MDN](https://developer.mozilla.org/fr/docs/Web/Web_Components/Using_custom_elements).
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Une façon de le faire est d'utiliser [attributs `data-*`](https://developer.mozilla.org/fr/docs/Learn/HTML/Howto/Use_data_attributes) pour stocker la valeur des variables dans votre sortie HTML. Les
```suggestion
Une façon de le faire est d'utiliser les [attributs `data-*`](https://developer.mozilla.org/fr/docs/Learn/HTML/Howto/Use_data_attributes) pour stocker la valeur des variables dans votre sortie HTML. Les scripts, y compris les éléments personnalisés, peuvent alors lire ces attributs en utilisant la propriété `dataset` d'un élément une fois que votre HTML se charge dans le navigateur.
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +Dans cet exemple de composant, un prop `message` est stocké dans un attribut `data-message`, de sorte que l'élément personnalisé peut lire `this.dataset.message` et obtenir la valeur du prop dans le
```suggestion
Dans cet exemple de composant, une propriété `message` est stockée dans un attribut `data-message`, de sorte que l'élément personnalisé puisse lire `this.dataset.message` et obtenir la valeur de la propriété dans le navigateur.
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +<!-- Stocker le prop de message comme attribut de données. -->
```suggestion
<!-- Stocker la propriété de message comme attribut de données. -->
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +      // Lisez le message de l’attribut data..
```suggestion
      // Lisez le message de l’attribut data.
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +:::tip[Saviez-vous?]
```suggestion
:::tip[Le saviez-vous?]
```

2023-02-07 16:52 UTC, pioupia commented on src/pages/fr/guides/client-side-scripts.mdx
> +C'est en fait ce que fait Astro dans les coulisses lorsque vous passez des accessoires à un composant écrit en utilisant un framework d'interface utilisateur comme React! Pour les composants avec une
```suggestion
C'est en fait ce que fait Astro dans les coulisses lorsque vous passez des propriétés à un composant écrit en utilisant un framework d'interface utilisateur comme React ! Pour les composants avec une directive `client:*`, Astro crée un élément personnalisé `<astro-island>` avec un attribut `props` qui stocke vos props côté serveur dans la sortie HTML.
```

2023-02-07 16:53 UTC, pioupia commented
J'ai fini complètement la review de cette page !

2023-02-07 17:14 UTC, dreyfus92 commented
merci beaucoup @pioupia,  je suis en train de résoudre toutes les observations.

2023-02-07 18:07 UTC, MoustaphaDev reviewed
Merci pour cette PR @dreyfus92! C'est propre, j'ai juste quelques suggestions de reformulation et corrections de fautes

2023-02-07 18:07 UTC, MoustaphaDev commented on src/pages/fr/guides/client-side-scripts.mdx
> +<h1>Bienvenue, monde!</h1>
Nit: Ajout d'un espace avant les points d'exclamation, y en a pas mal dans le document
```suggestion
<h1>Bienvenue, monde !</h1>
```

2023-02-07 19:10 UTC, MoustaphaDev commented on src/pages/fr/guides/client-side-scripts.mdx
> +Dans les composants Astro, le code dans [le frontmatter](/fr/core-concepts/astro-components/#le-script-du-composant) entre les clôtures “---” s'éxecute sur le serveur et n'est pas disponible dans le
Corrigé la position de l'accent
```suggestion
Dans les composants Astro, le code dans [le frontmatter](/fr/core-concepts/astro-components/#le-script-du-composant) entre les clôtures “---” s'exécute sur le serveur et n'est pas disponible dans le navigateur. Pour envoyer des variables du serveur au client, nous avons besoin d'un moyen de stocker nos variables et de les lire lorsque le JavaScript s'exécute dans le navigateur.
```

2023-02-07 19:20 UTC, dreyfus92 commented
Merci beaucoup pour le review @MoustaphaDev 🚀

2023-02-07 19:29 UTC, MoustaphaDev commented on src/pages/fr/guides/client-side-scripts.mdx
> +**Quand l'utiliser:** Si vos script est dedans `src/`
Suggestion non prise en compte, serait-il possible d'inclure cela @dreyfus92 ?

2023-02-07 19:31 UTC, MoustaphaDev commented on src/pages/fr/guides/client-side-scripts.mdx
> +Pour charger des scripts en dehors du dossier `src/` de votre projet, incluez la directive `is:inline`. Cette approche permet d'éviter le traitement JavaScript, le regroupement et l'optimisations du
```suggestion
Pour charger des scripts en dehors du dossier `src/` de votre projet, incluez la directive `is:inline`. Cette approche permet d'éviter le traitement JavaScript, le regroupement et l'optimisation du JavaScript qui sont fournis par Astro lorsque vous importez des scripts comme décrit ci-dessus.
```

2023-02-07 19:31 UTC, MoustaphaDev commented on src/pages/fr/guides/client-side-scripts.mdx
> +Pour charger des scripts en dehors du dossier `src/` de votre projet, incluez la directive `is:inline`. Cette approche permet d'éviter le traitement JavaScript, le regroupement et l'optimisations du
Typo

2023-02-07 19:39 UTC, MoustaphaDev approved these changes
LGTM, formidable job @dreyfus92 ! J'attends juste que les checks passent

2023-02-07 19:44 UTC, merged