i18n(fr): Translation of `buddy.mdx`
withastro/docs pull request #2640
Opened 2023-02-13 04:38 UTC by dreyfus92

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `buddy.mdx` to french

2023-02-14 21:50 UTC, thomasbnt requested changes

2023-02-14 21:50 UTC, thomasbnt commented on src/pages/fr/guides/deploy/buddy.mdx
> +1. [Creér un compte](https://buddy.works/sign-up).
"Créez un compte"

2023-02-14 21:50 UTC, thomasbnt commented on src/pages/fr/guides/deploy/buddy.mdx
> +Vous pouvez déployer votre projet Astro en utilisant [Buddy](https://buddy.works/), une solution CI/CD qui peut construire votre site et le pousser vers de nombreuses cibles de déploiement différente
`hébergement en nuage.`

Seems not a correct translation, "cloud" is not better like `hébergement sur un cloud` ?

2023-02-15 04:00 UTC, dreyfus92 commented
Merci pour le review @thomasbnt 😄

2023-02-19 14:11 UTC, Yan-Thomas commented
Thanks @thomasbnt and @dreyfus92, great work!

2023-02-19 14:12 UTC, merged