Fix the md hierarchy
withastro/docs pull request #2648
Opened 2023-02-14 02:58 UTC by liruifengv

2023-02-14 13:52 UTC, liruifengv commented
If this pr is approved, I will update the Chinese page also.

2023-02-14 15:34 UTC, Jutanium commented
I'm thinking we should remove the `package.json#` prefix for each of the properties - we don't use this kind of prefix anywhere else in the docs. @sarah11918, thoughts?

2023-02-14 19:25 UTC, sarah11918 commented
Agreed, @Jutanium I would remove those because we don't use them in docs.

And just a quick note, @liruifengv - in future, please make sure to write a description for your PRs. Even for small or obvious PRs, it helps us make sure we know exactly what problem is being fixed so we know what we should be paying attention to, and also to help "categorize" the PR with the proper label! 🙌

2023-02-14 22:37 UTC, Jutanium requested changes

2023-02-14 22:37 UTC, Jutanium commented on src/pages/en/reference/publish-to-npm.mdx
> +#### `package.json#description`
```suggestion
#### `description`
```

2023-02-14 22:37 UTC, Jutanium commented on src/pages/en/reference/publish-to-npm.mdx
> +#### `package.json#type`
```suggestion
#### `type`
```

2023-02-14 22:37 UTC, Jutanium commented on src/pages/en/reference/publish-to-npm.mdx
> +#### `package.json#homepage`
```suggestion
#### `homepage`
```

2023-02-14 22:37 UTC, Jutanium commented on src/pages/en/reference/publish-to-npm.mdx
> +#### `package.json#files`
```suggestion
#### `files`
```

2023-02-14 22:37 UTC, Jutanium commented on src/pages/en/reference/publish-to-npm.mdx
> +#### `package.json#keywords`
```suggestion
#### `keywords`
```

2023-02-15 01:54 UTC, liruifengv commented
@Jutanium @Jutanium Thank your help.

2023-02-15 02:01 UTC, Jutanium approved these changes

2023-02-15 02:26 UTC, merged