i18n(fr): Translation of `images.mdx`
withastro/docs pull request #2675
Opened 2023-02-17 18:08 UTC by Elib27

#### What kind of changes does this PR include?

- Translated content

#### Description

Translated `images.mdx` content to french

2023-02-24 19:54 UTC, thomasbnt approved these changes
LGTM pour ma part ! 🥳🚀

2023-02-24 20:59 UTC, pioupia requested changes
Excellente contribution (traduction de très bonne qualité). Quelques modifications à réaliser, et d'autres à réfléchir !

Beau travail !

2023-02-24 20:59 UTC, pioupia commented on src/pages/fr/guides/images.mdx
> +### Dans les fichiers `.astro`
Petit saut de ligne !
```suggestion

### Dans les fichiers `.astro`
```

2023-02-24 20:59 UTC, pioupia commented on src/pages/fr/guides/images.mdx
> +## Intégration des image Astro
```suggestion
## Intégration des images Astro
```

2023-02-24 20:59 UTC, pioupia commented on src/pages/fr/guides/images.mdx
> +Par défaut, les [`formats`](/fr/guides/integrations-guide/image/#formats) du composant `<Picture />` incluront `avif` et `webp` en plus du format d'origine de l'image s'il n'est pas spécifié .
```suggestion
Par défaut, les [`formats`](/fr/guides/integrations-guide/image/#formats) du composant `<Picture />` incluront `avif` et `webp` en plus du format d'origine de l'image s'il n'est pas spécifié.
```

2023-02-24 20:59 UTC, pioupia commented on src/pages/fr/guides/images.mdx
> +L'image sera traitée comme une image distante, donc une valeur pour `aspectRatio` est également requise pour s'assurer que la hauteur correcte puisse être calculée au moment du Build.
Modification pas super utile, mais une micro-reformulation qui *pourrait* rendre la phrase un _tout petit peu_ plus claire.
```suggestion
L'image sera traitée comme une image distante, donc une valeur pour `aspectRatio` est également requise pour s'assurer que la hauteur puisse être correctement calculée au moment du Build.
```

2023-02-24 20:59 UTC, pioupia commented on src/pages/fr/guides/images.mdx
> +### Définitions des valeurs par défaut
Est-ce que "Réglage" ou "Paramètre" serait plus approprié au lieu de "Définition" ?

```suggestion
### Paramètre des valeurs par défaut
```

ou

```suggestion
### Réglage des valeurs par défaut
```

2023-02-25 21:34 UTC, Elib27 commented
Merci @thomasbnt et @pioupia pour la review 👍

2023-02-25 21:48 UTC, Elib27 commented on src/pages/fr/guides/images.mdx
> +### Définitions des valeurs par défaut
Effectivement, peut-être qu'un "Paramétrage" sonnerait mieux.

2023-02-25 22:40 UTC, MoustaphaDev commented on src/pages/fr/guides/images.mdx
> +### Définitions des valeurs par défaut
Tous les deux passent à mon avis

2023-02-25 22:46 UTC, MoustaphaDev approved these changes
Merci pour cette PR @Elib27, traduction impeccable !
LGMT dès que la dernière discussion est résolue 🥳

2023-02-26 10:11 UTC, MoustaphaDev commented
J'avais pas remarqué que la page était toujours dans `src/pages` pour te faire savoir plus tôt, le contenu de la doc réside dans `src/content` à présent.
J'y ai transféré ta traduction pour t'éviter toutes ces allées et venues.

2023-02-26 10:35 UTC, Elib27 commented
Merci @MoustaphaDev, c'est bon à savoir

2023-02-26 10:39 UTC, merged