Update graphql example
withastro/docs pull request #2799
Opened 2023-03-07 16:28 UTC by sasoria

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content

#### Description

- Closes #2775

This PR updates the graphql example to a working graphql api, in this case [swapi-graphql](https://github.com/graphql/swapi-graphql) and tries to reuse the syntax from the old example (i.e variables and arguments). 

Sadly, I don't have the capacity to translate everything to other languages, so I've kept it in english. I'm using the name `Film.astro` as it relates to the query, but I've seen that `Movies` has been used in som examples above this one. Let me know if there is anything you would like me to change 😊

2023-03-08 09:31 UTC, delucis requested changes
@sasoria Thanks for picking this up! Appreciate it.

In general we prefer to [just update the English pages](https://github.com/withastro/docs/blob/main/CONTRIBUTING.md#making-prs-pull-requests) and let our translators take care of updating their languages as they’ll often catch nuances we miss. Could you revert the changes to non-English pages and then we can focus on getting the English changes spot on?

2023-03-09 18:12 UTC, sasoria commented
Thanks for pointing me in the right direction. I've reverted the changes on the other languages as requested.

2023-03-09 22:18 UTC, Jutanium approved these changes

2023-03-09 23:07 UTC, delucis approved these changes

2023-03-09 23:20 UTC, merged