i18n(es): Translated missing error pages.
withastro/docs pull request #2823
Opened 2023-03-10 02:40 UTC by dreyfus92

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated to spanish missing error pages as follows:
  - `image-missing-alt.mdx`
  - `invalid-image-service.mdx`
  - `missing-image-dimension.mdx`
  - unsupported-image-formate.mdx`

2023-03-11 14:24 UTC, agustinmulet requested changes
Good job! Left a couple of suggestions 🙌

2023-03-11 14:24 UTC, agustinmulet commented on src/content/docs/es/reference/errors/image-missing-alt.mdx
> +> **ImageMissingAlt**: La propiedad alt es requeridad. (E03022)
```suggestion
> **ImageMissingAlt**: La propiedad alt es requerida. (E03022)
```

2023-03-11 14:24 UTC, agustinmulet commented on src/content/docs/es/reference/errors/image-missing-alt.mdx
> +Si la imagen es meramente decorativa (es decir, no contribuye a la comprensión de la página), establezca `alt=""` para que los lectores de pantalla sepan ignorar la imagen.
```suggestion
Si la imagen es meramente decorativa (es decir, no contribuye a la comprensión de la página), establece `alt=""` para que los lectores de pantalla sepan ignorar la imagen.
```

2023-03-11 14:24 UTC, agustinmulet commented on src/content/docs/es/reference/errors/invalid-image-service.mdx
> +> **InvalidImageService**: Hubo un error cargando el servicio configurado de imagen. Porfavor revisa el stack trace para más información. (E03023)
```suggestion
> **InvalidImageService**: Hubo un error cargando el servicio configurado de imagen. Por favor revisa el stack trace para más información. (E03023)
```

2023-03-11 14:24 UTC, agustinmulet commented on src/content/docs/es/reference/errors/invalid-image-service.mdx
> +Si crees que tu servicio está configurado correctamente y este error es incorrecto, porfavor [abre un issue](https://astro.build/issues/).
```suggestion
Si crees que tu servicio está configurado correctamente y este error es incorrecto, por favor [abre un issue](https://astro.build/issues/).
```

2023-03-11 14:24 UTC, agustinmulet commented on src/content/docs/es/reference/errors/missing-image-dimension.mdx
> +Si tu imagen está dentro de tu carpeta `src`, probablemente quieras importarla en su lugar. Consulte [la guía de importaciones para obtener más información](/es/guides/imports/#otros-recursos).
```suggestion
Si tu imagen está dentro de tu carpeta `src`, probablemente quieras importarla en su lugar. Consulta [la guía de importaciones para obtener más información](/es/guides/imports/#otros-recursos).
```

2023-03-11 14:24 UTC, agustinmulet commented on src/content/docs/es/reference/errors/unsupported-image-format.mdx
> +Para formatos no admitidos como SVG y GIF, puede usar una etiqueta `img` directamente:
```suggestion
Para formatos no admitidos como SVG y GIF, puedes usar una etiqueta `img` directamente:
```

2023-03-11 14:56 UTC, dreyfus92 commented
Grande @agustinmulet, gracias por el review 😄

2023-03-12 17:04 UTC, Yan-Thomas commented
Great job @dreyfus92 & @agustinmulet, just a thing: we also need to update the `error-reference.mdx` page here so the new errors are listed on it, could you add this to the PR? Thanks 🙌

2023-03-12 17:08 UTC, dreyfus92 commented
I will handle it in a bit @Yan-Thomas.

2023-03-12 18:34 UTC, Yan-Thomas approved these changes

2023-03-12 18:35 UTC, merged