i18n(es): Update of `astro-components.mdx`, `endpoints.mdx`, `layouts.mdx` & `client-side-scripts.mdx`
withastro/docs pull request #2834
Opened 2023-03-12 02:47 UTC by dreyfus92

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Updated `astro-components.mdx`, `endpoints.mdx`, `layouts.mdx` & `client-side-scripts.mdx` based on this commit -> 60f35d65a6ef99bb13fafbbc312c332213ab5a70

2023-03-12 21:06 UTC, agustinmulet requested changes
Un pequeño acento nada más. Después de eso, LGTM! 🚀

2023-03-12 21:06 UTC, agustinmulet commented on src/content/docs/es/guides/client-side-scripts.mdx
> +  // Importa modulos npm.
```suggestion
  // Importa módulos npm.
```

2023-03-13 06:16 UTC, dreyfus92 commented
Muchas gracias por el review @agustinmulet 😁

2023-03-13 18:28 UTC, Yan-Thomas commented
Great job @dreyfus92 & @agustinmulet! Let's get this merged 🚀

2023-03-13 18:30 UTC, merged