i18n(es-ES): translated `tutorial-build a blog`
withastro/docs pull request #2856
Opened 2023-03-14 23:26 UTC by juanburg98

Description the changes:

I traslated to spanish the section Tutorial,  and change the logo in README.

Checklist:

- [x] Introduction (100%)
- [x] Setup (100%)
- [x]  Pages (100%)
- [x] Components (100%)
- [x] Layouts (100%)
- [x]  Astro API (100%)
- [x]  Islands (100%)
- [x] Fix README logo

2023-03-15 00:35 UTC, juanburg98 commented
@Yan-Thomas  I closed the other PR and opened a new one, fixed some things in the translations and added the logo in the README since it was not displayed.

Before:
![withastro-docs-Astro-documentation](https://user-images.githubusercontent.com/106132925/225173043-8d81f751-f604-41fe-8633-b2ff9405f83a.png)

After:
![juanburg98-docs-Astro-documentation2](https://user-images.githubusercontent.com/106132925/225173055-aab18d6e-05fa-4881-9670-c2c4bf740de3.png)

2023-03-15 17:41 UTC, Yan-Thomas commented
Thanks @juanburg98, might I ask you to remove this README change and make it its own separate PR? I'd like to get this logo fixed before the translation itself is reviewed 🙌

2023-03-15 17:48 UTC, juanburg98 commented
Of course, yes.

2023-03-15 17:51 UTC, Yan-Thomas commented
@juanburg98 sorry for the double ping, just to make you aware I edited my comment above the moment you answered me!

> Just saw TC published a PR fixing the README in 2860, in this case, I need you only to remove this change from the PR

2023-03-15 17:55 UTC, juanburg98 commented
I have already removed it from this PR. 👍

2023-03-15 19:52 UTC, dreyfus92 commented
@juanburg98 Check the CI/ Check links to fix the broken links.

2023-03-15 20:22 UTC, juanburg98 commented
Gracias @dreyfus92 lo agradezco 🤝

2023-03-15 20:31 UTC, dreyfus92 commented
I will try to review this later @Yan-Thomas

2023-03-16 20:20 UTC, dreyfus92 requested changes
Firstly I'd like to thank you for this contribution, this is massive. I left you some suggestions so you can start working on them @juanburg98. Since this is a massive PR I just reviewed `0-introduction` & `1-setup`. I'll try to continue reviewing what's left in the upcoming days 😁

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +Haga clic en la URL en la configuración de su sitio, o escríbala en una ventana del navegador para ver su nuevo sitio web.
```suggestion
Haz clic en la URL en la configuración de tu sitio o escríbela en una ventana del navegador para ver tu nuevo sitio web.
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +Quiere actualizar la página de inicio de su sitio web actual. ¿Qué pasos debe seguir?
```suggestion
Tu quieres actualizar la página de inicio de tu sitio web actual. ¿Qué pasos debes seguir?
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +      Abro un terminal, ejecuto `create astro`, y luego visito mi URL de Netlify.
```suggestion
      Abro una terminal, ejecuto `create astro`, y luego visito mi URL de Netlify.
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +unitTitle: Cree y despliegue su primer sitio Astro
```suggestion
unitTitle: Crea y despliega tu primer sitio Astro
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +  Prepare su entorno de desarrollo y cree y despliegue su primer sitio Astro
```suggestion
  Prepara tu entorno de desarrollo, crea y despliega tu primer sitio Astro
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +Esta unidad le muestra cómo configurar su entorno de desarrollo y desplegar en Netlify. Pase a la [Unidad 2](/es/tutorial/2-pages/) si ya se siente cómodo con su entorno y flujo de trabajo.
```suggestion
Esta unidad te muestra cómo configurar tu entorno de desarrollo y desplegar en Netlify. Pase a la [Unidad 2](/es/tutorial/2-pages/) si ya te sientes cómodo con tu entorno y flujo de trabajo.
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +<summary>Siga estas instrucciones y pase directamente a la Unidad 2.</summary>
```suggestion
<summary>Sigue estas instrucciones y pasa directamente a la Unidad 2.</summary>
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +1. Visite [astro.new](https://astro.new) y haga clic en el botón para abrir la plantilla "Proyecto vacío" en StackBlitz.
```suggestion
1. Visita [astro.new](https://astro.new) y haz clic en el botón para abrir la plantilla "Proyecto vacío" en StackBlitz. 
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +3. En la parte superior izquierda de la ventana del editor StackBlitz, haga clic para hacer un "fork" de la plantilla (guardar en el panel de su propia cuenta).
```suggestion
3. En la parte superior izquierda de la ventana del editor StackBlitz, haz clic para hacer un "fork" de la plantilla (guardar en el panel de tu propia cuenta).
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +4. Espere a que se cargue el proyecto y verá una vista previa en vivo del inicio del "Proyecto vacío".
```suggestion
4. Espera a que se cargue el proyecto y verás una vista previa en vivo del inicio del "Proyecto vacío".
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +**Crear un repositorio GitHub**
```suggestion
**Crea un repositorio GitHub**
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +1. Preciosa en el boton <kbd>Conectar Repositorio</kbd> en la parte superior de la lista de archivos, ingresa una nombre para dicho repositorio y haz click en <kbd>Crear Repo & push</kbd>.
```suggestion
1. Presiona en el botón <kbd>Conectar Repositorio</kbd> en la parte superior de la lista de archivos, ingresa una nombre para dicho repositorio y haz clic en <kbd>Crear Repo & push</kbd>. 
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +**Despliegue su sitio**
```suggestion
**Despliega tu sitio**
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +### ¿Adónde vamos?
```suggestion
### ¿A dónde vamos?
```

2023-03-16 20:20 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +Cada vez que envíes un cambio a GitHub, se enviará una notificación a Netlify. Entonces, Netlify automáticamente reconstruirá y volverá a publicar su sitio en vivo para reflejar esos cambios.
```suggestion
Cada vez que envíes un cambio a GitHub, se enviará una notificación a Netlify. Entonces, Netlify automáticamente reconstruirá y volverá a publicar tu sitio en vivo para reflejar esos cambios.
```

2023-03-16 22:09 UTC, delucis commented
Wanted to pop in to say amazing work @juanburg98! And thank you to @dreyfus92 for helping review this big effort. 💜 

We’ve hopefully just fixed an issue with our build, so next time you update branch @juanburg98, we should get a Netlify preview to test out!

2023-03-21 22:03 UTC, dreyfus92 commented
@juanburg98 No hay necesidad de hacer constantemente merge con main, por que la PR sigue en revisión, cuando se terminen de agregar todas las observaciones podemos hacer el merge a main.

2023-03-22 14:55 UTC, juanburg98 commented
Perfecto @dreyfus92 , gracias!

2023-03-23 18:28 UTC, raul-repos commented on src/content/docs/es/tutorial/0-introduction/index.mdx
> +A lo largo del camino:
Creo que queda mejor como está ahora. En todo caso, si no, sería con tilde.
```suggestion
A lo largo del camino, tú: 
```

2023-03-27 06:45 UTC, dreyfus92 requested changes
@juanburg98 I leave you some suggestions for `2-pages` directory, thank you 🚀

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/3.mdx
> +3. Actualice la vista previa en directo de su página `/about`.
```suggestion
3. Actualiza la vista previa en directo de tu página `/about`.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/3.mdx
> +2. A continuación, añada el siguiente código a su plantilla HTML, debajo del contenido existente:
```suggestion
2. A continuación, añade el siguiente código a tu plantilla HTML, debajo del contenido existente:
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/3.mdx
> +2. Añada las siguientes líneas debajo de los párrafos existentes.
```suggestion
2. Añade las siguientes líneas debajo de los párrafos existentes.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/3.mdx
> +    A continuación, compruebe la vista previa en directo en la pestaña de su navegador para ver lo que se muestra en la página:
```suggestion
    A continuación, comprueba la vista previa en directo en la pestaña de tu navegador para ver lo que se muestra en la página:
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/3.mdx
> +3. Confirma tus cambios en GitHub antes de continuar. Haga esto cada vez que desee guardar su trabajo y actualizar su sitio web en vivo.
```suggestion
3. Confirma tus cambios en GitHub antes de continuar. Haga esto cada vez que deseas guardar tu trabajo y actualizar tu sitio web en vivo.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/3.mdx
> +- [Expresiones dinámicas en Astro](/en/core-concepts/astro-syntax/#jsx-like-expressions)
```suggestion
- [Expresiones dinámicas en Astro](/es/core-concepts/astro-syntax/#jsx-like-expressions)
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +## Estilizar una página individual
```suggestion
## Estilar una página individual
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +    Compruebe las tres páginas en la vista previa de su navegador
```suggestion
    Comprueba las tres páginas en la vista previa de tu navegador
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +        - ¿Su página de inicio?  <Spoiler>negro</Spoiler>
```suggestion
        - ¿Tu página de inicio?  <Spoiler>negro</Spoiler>
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +        - ¿Su página Acerca de? <Spoiler>purpura</Spoiler>
```suggestion
        - ¿Tu página Acerca de? <Spoiler>purpura</Spoiler>
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +    Si no puede determinar los colores visualmente, puede utilizar las herramientas de desarrollo de su navegador para inspeccionar los elementos de título `<h1>` y verificar el color del texto aplic
```suggestion
    Si no puedes determinar los colores visualmente, puedes utilizar las herramientas de desarrollo de su navegador para inspeccionar los elementos de título `<h1>` y verificar el color del texto aplicado.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +2. Añada el nombre de clase `skill` a los elementos `<li>` generados en su página Acerca de, para que podamos aplicarles estilo. Tu código debería tener este aspecto:
```suggestion
2. Añade el nombre de clase `skill` a los elementos `<li>` generados en tu página Acerca de, para que podamos aplicarles estilo. Tu código debería tener este aspecto:
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +3. Añada el siguiente código a la etiqueta de estilo existente:
```suggestion
3. Añade el siguiente código a la etiqueta de estilo existente:
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> + 1. Actualice la etiqueta `<style>` de su página Acerca de para que coincida con la de abajo.
```suggestion
 1. Actualiza la etiqueta `<style>` de tu página Acerca de para que coincida con la de abajo. 
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +- [Comparación entre la sintaxis Astro y JSX](/en/core-concepts/astro-syntax/#differences-between-astro-and-jsx)
```suggestion
- [Comparación entre la sintaxis Astro y JSX](/es/core-concepts/astro-syntax/#differences-between-astro-and-jsx)
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +- [Etiqueta Astro `<style>`.](/en/guides/styling/#styling-in-astro)
```suggestion
- [Etiqueta Astro `<style>`.](/es/guides/styling/#estilando-en-astro)
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +- [Variables CSS en Astro](/en/guides/styling/#css-variables)
```suggestion
- [Variables CSS en Astro](/es/guides/styling/#variables-de-css)
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/5.mdx
> +2. Copie el siguiente código en su nuevo archivo, `global.css`.
```suggestion
2. Copia el siguiente código en tu nuevo archivo, `global.css`.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/5.mdx
> +4. Compruebe la vista previa del navegador de su página Acerca de y ahora debería ver los nuevos estilos aplicados.
```suggestion
4. Comprueba la vista previa del navegador de tu página Acerca de y ahora debería ver los nuevos estilos aplicados.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/5.mdx
> +## Pruébelo usted mismo - Importe su hoja de estilo global
```suggestion
## Pruébalo tu mismo - Importa tu hoja de estilo global
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/5.mdx
> +Añada la línea de código necesaria a cada archivo `.astro` de su proyecto para aplicar sus estilos globales a cada página de su sitio.
```suggestion
Añade la línea de código necesaria a cada archivo `.astro` de tu proyecto para aplicar tus estilos globales a cada página de tu sitio.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/5.mdx
> +Realice cualquier cambio o adición que desee en el contenido de su página Acerca de añadiendo elementos HTML a la plantilla de página, ya sea de forma estática o dinámica. Escriba cualquier JavaScrip
```suggestion
Realiza cualquier cambio o adición que deseas en el contenido de tu página Acerca de añadiendo elementos HTML a la plantilla de la página, ya sea de forma estática o dinámica. Escribe cualquier JavaScript adicional en tu script frontmatter para proporcionarle valores para usar en tu HTML. Cuando estés satisfecho con esta página, confirma tus cambios en GitHub antes de pasar a la siguiente lección.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/5.mdx
> +Su página Acerca de ahora tiene estilo usando *ambos* el archivo importado `global.css` *y* una etiqueta `<style>`.
```suggestion
Tu página Acerca de ahora tiene estilo usando *ambos* el archivo importado `global.css` *y* una etiqueta `<style>`.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/index.mdx
> +- Cree sus primeras páginas Astro con la sintaxis `.astro
```suggestion
- Crea tus primeras páginas Astro con la sintaxis `.astro
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/index.mdx
> +- Estilizar una página individual con `<style>`.
```suggestion
- Estilar una página individual con `<style>`.
```

2023-03-27 06:45 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/index.mdx
> + Por el camino, aprenderás cómo las **dos secciones de un archivo `.astro`** trabajan juntas para crear una página, y cómo usar variables y renderizado condicional en tus páginas.
```suggestion
En el camino, aprenderás cómo las **dos secciones de un archivo `.astro`** trabajan juntas para crear una página, y cómo usar variables y renderizado condicional en tus páginas.
```

2023-03-27 17:10 UTC, Yan-Thomas commented
> @dreyfus92 es lo mismo darle a Resolve Conversation que crear un nuevo commit de cada cambio?

Hey @juanburg98 👋, "Resolve Conversation" only collapses the suggestion box, if you want to commit multiple suggestions as only one commit easily, go to the "Files changed" tab and you will be able to see the suggestions separated by file. There, you can click the "Add suggestion to batch" button that lets you select multiple suggestions and add everything as only one commit.

GitHub docs page with images for better understanding and more info: 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/incorporating-feedback-in-your-pull-request

2023-03-27 17:22 UTC, dreyfus92 commented
@juanburg98 Simplemente lo que hace es como dijo Yan, es colapsar la caja de sugerencia como para llevar un orden de trackeo conforme vayas realizando los cambios localmente. Inclusive hay otra opción que dice `Commit suggestion` o algo así que automáticamente hará el cambio de la sugerencia a la PR.

2023-03-27 18:34 UTC, juanburg98 commented
@Yan-Thomas @dreyfus92 Thanks to both of you 😃🤝

2023-04-05 19:40 UTC, sarah11918 commented
I can't believe how much work has gone into this! Thank you so much @juanburg98 and @dreyfus92 and @Yan-Thomas for helping to keep this on track!  :raised_hands: 

Juan, you might have noticed that there's a failing test here. Not to worry, it often happens on big contributions like this one!  :smile: I just wanted to make sure you knew how to USE those errors to help you make the fixes needed.

You can click into the "files changed" view of this PR, and as you scroll through a file, you can see when a link is causing an error. Sometimes, it's because the link starts with `/en/` when our system is built so that you use `/es/` for any link, even if that page hasn't been translated yet. Other times, it's because you might be using a link with the English header when you've already translated the header, and so that link should now be updated to its translated Spanish version. Scroll through the PR here on GitHub and the errors will show up exactly on the page where they occur, with a message letting you know what needs to be fixed!

Also, and maybe Yan or Paul can help if you need, I noticed that you have some non-tutorial files related to error messages changed in this PR. Those should be removed so that you don't make any changes to those files.

I really look forward to having the tutorial fully translated into its first non-English language! And, it looks like it's going to be Spanish... :partying_face:

2023-04-05 23:02 UTC, juanburg98 commented
Thank you @sarah11918  I will make all necessary changes!

2023-04-06 05:22 UTC, dreyfus92 requested changes
@juanburg98 I leave you more suggestions for `3-components` directory 😁 We're almost there to ship this massive contribution 🚀

2023-04-06 05:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/3-components/4.mdx
> +4. Añade el mismo `<script>` con import a tus otras dos páginas, `about.astro` y `blog.astro` y comprueba que tienes un header responsive e interactivo en cada página.
```suggestion
4. Añade el mismo `<script>` con import a tus otras dos páginas, `about.astro` y `blog.astro` y comprueba que tienes un header responsivo e interactivo en cada página.
```

2023-04-06 05:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/3-components/4.mdx
> +Anteriormente había utilizado JavaScript para construir partes de su sitio:
```suggestion
Anteriormente había utilizado JavaScript para construir partes de tu sitio:
```

2023-04-06 05:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/3-components/4.mdx
> +Todos esos comandos se ejecutan en tiempo de compilación para crear HTML estático para su sitio, y luego el código se "tira".
```suggestion
Todos esos comandos se ejecutan en tiempo de compilación para crear HTML estático para tu sitio, y luego el código se "tira". 
```

2023-04-06 05:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/3-components/index.mdx
> +  Cree componentes Astro para reutilizar el código de los elementos comunes de su sitio web.
```suggestion
  Crea componentes Astro para reutilizar el código de los elementos comunes de tu sitio web.
```

2023-04-07 00:34 UTC, juanburg98 commented
@dreyfus92 All changes have been applied!!

2023-04-07 00:38 UTC, dreyfus92 commented
Thank you @juanburg98 💚 2 directories left.

2023-04-07 11:34 UTC, sarah11918 commented
I AM GETTING EXCITED!!!

2023-04-09 20:57 UTC, juanburg98 commented
@dreyfus92 tengo archivos en en/reference/error que me habias mandado pero en su momento no los aplique, tambien tengo algunos cambios en i18n/es/ui. Es posible que los habilites de nuevo ya que no me deja hacerles nada, aparecen con un cuadrado amarillo , gracias y disculpa las molestias 
![screely-1681073789587](https://user-images.githubusercontent.com/106132925/230796178-43d7ce3f-d955-4008-ac5e-ce81f632dfc9.png)

2023-04-10 00:16 UTC, dreyfus92 commented
@juanburg98 No se cuando hice esas sugerencias, podemos dejarlo para el final ya que hayamos revisado los últimos dos directorios.

2023-04-10 18:19 UTC, dreyfus92 requested changes
Reviewed `4-layouts` here are some suggestions @juanburg98. We're just missing `5-astro-api` & `6-islands`. Thanks again.

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +## Anida tus dos layouts
```suggestion
## Anida tus dos plantillas
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +Ya tienes un `BaseLayout.astro` para definir el layout general de tus páginas.
```suggestion
Ya tienes un `BaseLayout.astro` para definir la plantilla general de tus páginas. 
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +El `MarkdownPostLayout.astro` te proporciona algunas plantillas adicionales para las propiedades comunes de los posts de tu blog, como `title` y `date`, pero los posts de tu blog no tienen el mismo a
```suggestion
El `MarkdownPostLayout.astro` te proporciona algunas plantillas adicionales para las propiedades comunes de los posts de tu blog, como `title` y `date`, pero los posts de tu blog no tienen el mismo aspecto que el resto de páginas de tu sitio. Puedes conseguirlo **anidando plantillas**.
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +2. Compruebe la vista previa de su navegador en `localhost:3000/posts/post-1`. Ahora debería ver el contenido renderizado por:
```suggestion
2. Comprueba la vista previa de tu navegador en `localhost:3000/posts/post-1`. Ahora debería ver el contenido renderizado por:
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +3. Observe que el título de su página se muestra ahora dos veces, una por cada layout.
```suggestion
3. Observa que el título de tu página se muestra ahora dos veces, una por cada plantilla.
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +    - Tu ** layout de página principal**, incluyendo tus estilos, enlaces de navegación y pie de página social.
```suggestion
    - Tu ** plantilla de página principal**, incluyendo tus estilos, enlaces de navegación y pie de página social.
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +    - Tu **blog post layout**, incluyendo propiedades frontmatter como la descripción, fecha, título e imagen.
```suggestion
    - Tu **plantilla de blog post**, incluyendo propiedades frontmatter como la descripción, fecha, título e imagen.
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +5. Compruebe de nuevo la vista previa de su navegador en `localhost:3000/posts/post-1` y verifique que esta línea ya no aparece y que su título sólo se muestra una vez. Realice cualquier otro ajuste
```suggestion
5. Comprueba de nuevo la vista previa de tu navegador en `localhost:3000/posts/post-1` y verifica que esta línea ya no aparece y que su título sólo se muestra una vez. Realice cualquier otro ajuste necesario para asegurarse de que no tiene contenido duplicado.
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +1. Esto le permite anidar un layout dentro de otro y aprovechar las ventajas de trabajar con piezas modulares.
```suggestion
1. Esto le permite anidar una plantilla dentro de otra y aprovechar las ventajas de trabajar con piezas modulares.
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +2. Los layouts múltiples son especialmente útiles para proyectos que contienen páginas Markdown, como...
```suggestion
2. Las plantillas múltiples son especialmente útiles para proyectos que contienen páginas Markdown, como...
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +- [Layouts anidados en Astro](/es/core-concepts/layouts/#nesting-layouts)
```suggestion
- [Layouts anidados en Astro](/es/core-concepts/layouts/#plantillas-anidadas)
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +- [ ] ¡Estoy listo para llevar mi diseño de página al siguiente nivel con layouts!
```suggestion
- [ ] ¡Estoy listo para llevar mi diseño de página al siguiente nivel con plantillas!
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +- Crear componentes de layout reutilizables
```suggestion
- Crear componentes de plantillas reutilizables
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +- Pasa contenido a tus layouts con `<slot />`
```suggestion
- Pasa contenido a tus plantillas con `<slot />`
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +- Varios layouts anidados
```suggestion
- Varias plantillas anidadas
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +En esta unidad, crearás layouts para compartir elementos y estilos comunes en tus páginas y posts de blog.
```suggestion
En esta unidad, crearás plantillas para compartir elementos y estilos comunes en tus páginas y posts de blog.
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +unitTitle: Ahorre tiempo y energía con layouts de página reutilizables
```suggestion
unitTitle: Ahorra tiempo y energía con plantiallas de página reutilizables
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +title: 'Regístrese: Unidad 4 - Layouts'
```suggestion
title: 'Regístrate: Unidad 4 - Plantillas'
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +  Utiliza los layout Astro para compartir elementos y estilos comunes en tus páginas y
```suggestion
  Utiliza los plantillas Astro para compartir elementos y estilos comunes en tus páginas y
```

2023-04-10 18:19 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +Ahora que ya puedes construir con componentes, ¡vamos a crear algunos layouts personalizados!
```suggestion
Ahora que ya puedes construir con componentes, ¡vamos a crear algunas plantillas personalizadas!
```

2023-04-10 18:50 UTC, juanburg98 commented
Ready @dreyfus92  apply all changes. When I pass the tests I have some links to fix

2023-04-12 07:49 UTC, delucis reviewed
Left a few link fixes here. I’m also seeing some changes to the files in `en/reference/errors/` for some reason — we should probably remove those.

**Edit:** Somehow I ended up reviewing old files, sorry 😅
The links look great now but we should still remove the changes to `en/reference/errors/`.

2023-04-12 07:49 UTC, delucis commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +- [Enrutamiento estático en Astro](/es/core-concepts/routing/#static-routes)
```suggestion
- [Enrutamiento estático en Astro](/es/core-concepts/routing/#rutas-estáticas)
```

2023-04-12 07:49 UTC, delucis commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +- [Generación de elementos RSS en Astro](/es/guides/rss/#using-glob-imports)
```suggestion
- [Generación de elementos RSS en Astro](/es/guides/rss/#usando-glob-imports)
```

2023-04-12 07:49 UTC, delucis commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +- [Uso de componentes de UI Framework en Astro](/es/core-concepts/framework-components/#using-framework-components)
```suggestion
- [Uso de componentes de UI Framework en Astro](/es/core-concepts/framework-components/#usando-componente-de-framework)
```

2023-04-12 07:49 UTC, delucis commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +- [Referencia de las directivas del cliente Astro](/es/reference/directives-reference/#client-directives)
```suggestion
- [Referencia de las directivas del cliente Astro](/es/reference/directives-reference/#directivas-del-cliente)
```

2023-04-12 14:29 UTC, juanburg98 commented
@delucis I do not know how to remove the suggestions of changes in `en/reference/error`, if you can do it or suggest me how to do it would be of great help 🙏

2023-04-12 16:02 UTC, delucis commented
> @delucis I do not know how to remove the suggestions of changes in `en/reference/error`, if you can do it or suggest me how to do it would be of great help 🙏

Done! You’ll want to make sure you pull your branch before doing any more work locally to get these updates.

2023-04-18 17:37 UTC, kevinzunigacuellar reviewed
gracias por la PR! No he podido revisar todos los cambios pero para que todo va muy bien! 

Note: This includes sections 0 and 1

2023-04-18 17:37 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/1-setup/2.mdx
> +Mientras el servidor Astro esté funcionando en modo de desarrollo, NO podrás ejecutar comandos en tu ventana de terminal. En su lugar, este panel te dará retroalimentación mientras previsualiza su si
```suggestion
Mientras el servidor Astro esté funcionando en modo de desarrollo, NO podrás ejecutar comandos en esa terminal. En su lugar, este panel te dará retroalimentación mientras previsualiza su sitio.
```

2023-04-18 17:37 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/1-setup/3.mdx
> +1. En tu editor de código, navega en el panel de archivos del Explorador hasta `src/pages/index.astro` y haz clic en él para abrir el contenido del archivo en una pestaña editable.
```suggestion
1. En tu editor de código, navega en el panel de archivos del Explorador hasta `src/pages/index.astro` y abre el contenido del archivo en una pestaña editable.
```

2023-04-18 17:37 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/1-setup/4.mdx
> +Este tutorial utilizará GitHub para almacenar nuestro repositorio y conectarse a un host web. Te invitamos a utilizar el proveedor de git en línea de su elección.
```suggestion
Este tutorial utilizará GitHub para almacenar nuestro repositorio y conectarse a un host web. Te invitamos a utilizar el proveedor de git en línea de tu elección.
```

2023-04-18 17:37 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/1-setup/4.mdx
> +Aunque hay algunas maneras de obtener su código local almacenado en GitHub, este tutorial te guiará a través de un método que no requiere el uso de git en la línea de comandos.
```suggestion
Aunque hay algunas maneras de obtener tu código local almacenado en GitHub, este tutorial te guiará a través de un método que no requiere el uso de git en la línea de comandos. 
```

2023-04-18 17:37 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/1-setup/4.mdx
> +En la última sección, tu hiciste un cambio en el contenido de su página. Esto significa que los archivos de tu proyecto han cambiado y VS Code debería mostrar un número encima del icono del menú "Fue
```suggestion
En la última sección, hiciste un cambio en el contenido de tu página. Esto significa que los archivos de tu proyecto han cambiado y VS Code debería mostrar un número encima del icono del menú "Fuente". Esta pestaña de fuente es a donde irás regularmente para actualizar tus archivos en GitHub.
```

2023-04-18 17:37 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +A medida que escribas código, enviarás periódicamente tus cambios a GitHub. Netlify utilizará los archivos de tu repositorio de GitHub para construir tu sitio web, y luego lo publicará en Internet en
```suggestion
A medida que escribas código, enviarás periódicamente tus cambios a GitHub. Netlify utilizará los archivos de tu repositorio de GitHub para construir tu sitio web, y luego lo publicará en Internet en una dirección única donde cualquiera podrá verlo.
```

2023-05-01 23:52 UTC, Waxer59 reviewed
Incredible PR 🤯🤯, I've been reviewing section 5, there's something I've noticed that you need to check and change when applying the changes:

* There are several instances where you use "usted" instead of "tu", you need to correct this and make sure to use "tu" instead of "usted".
* In the questionnaires, there are terms that have been translated, but within the questionnaire, the term appears untranslated. Please carefully review which terms you have translated and maintain the translation of those terms throughout the entire document. This provides consistency to the translation and avoids confusing the user.
* There are parts, such as links, that you have translated, which could create errors and cause the code or link to not work and "break" the tutorial. Please check if you have translated something that could directly affect the steps of the tutorial to avoid creating errors.

I will send you the review of section 6 soon.

Thank you for the incredible contribution 🎉🎉🎉

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +Anteriormente ha mostrado elementos en una lista desde un array usando `map()`. ¿Cómo sería definir un array con todas tus etiquetas y mostrarlas en una lista en esta página?
```suggestion
Anteriormente has mostrado elementos en una lista desde un array usando `map()`. ¿Cómo sería definir un array con todas tus etiquetas y mostrarlas en una lista en esta página?
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +Afortunadamente, ya conoces una forma de obtener los datos de todos tus archivos Markdown en una sola línea de código y, a continuación, devolver una lista de todas tus etiquetas.
```suggestion
Afortunadamente, ya conoces una forma de obtener los datos de todos tus archivos Markdown en una sola línea de código y luego devolver una lista de todas tus etiquetas.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +## Cree su lista de etiquetas
```suggestion
## Crea tu lista de etiquetas
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +En lugar de crear elementos en una lista desordenada esta vez, crea una `<p>` para cada elemento, dentro de un `<div>`. El patrón debería resultarte familiar.
```suggestion
En lugar de crear elementos en una lista desordenada esta vez, crea un `<p>` para cada elemento, dentro de un `<div>`. El patrón debería resultarte familiar.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +1. Añada el siguiente código a su plantilla de componentes:
```suggestion
1. Añade el siguiente código a tu plantilla de componentes:
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +  En la vista previa de su navegador, compruebe que puede ver sus etiquetas en la lista.
```suggestion
  En la vista previa de tu navegador, comprueba que puedes ver tus etiquetas en la lista.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +2. Para que cada etiqueta enlace con su propia página, añada el siguiente enlace `<a>` al nombre de cada etiqueta:
```suggestion
2. Para que cada etiqueta enlace con su propia página, añade el siguiente enlace `<a>` al nombre de cada etiqueta:
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +2. Defina estas nuevas clases CSS añadiendo la siguiente etiqueta `<style>` a esta página:
```suggestion
2. Define estas nuevas clases CSS añadiendo la siguiente etiqueta `<style>` a esta página:
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +3. Compruebe la vista previa de su navegador en `localhost:3000/tags` para verificar que tiene algunos estilos nuevos y que cada una de las etiquetas de la página tiene un enlace que funciona a su pr
```suggestion
3. Comprueba la vista previa de tu navegador en `localhost:3000/tags` para verificar que tienes algunos estilos nuevos y que cada una de las etiquetas de la página tiene un enlace que funciona a su propia página de etiquetas individual.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +Este es el aspecto que debería tener su nueva página:
```suggestion
Este es el aspecto que debería tener tu nueva página:
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +## Añada esta página a su navegación
```suggestion
## Añade esta página a tu navegación
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +En este momento, puedes navegar a `localhost:3000/tags` y ver esta página. Desde esta página, puede hacer clic en los enlaces a sus páginas de etiquetas individuales.
```suggestion
En este momento, puedes navegar a `localhost:3000/tags` y ver esta página. Desde esta página, puedes hacer clic en los enlaces a sus páginas de etiquetas individuales.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +Pero aún así, debe hacer que estas páginas se puedan descubrir desde otras páginas de su sitio web.
```suggestion
Pero aún así, debes hacer que estas páginas se puedan descubrir desde otras páginas de tu sitio web.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +1. En su componente `Navigation.astro`, incluya un enlace a esta nueva página de índice de etiquetas.
```suggestion
1. En tu componente `Navigation.astro`, incluye un enlace a esta nueva página de índice de etiquetas.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +Para utilizar props (valores pasados) de una entrada de blog `.md` en su diseño, como etiquetas, necesita anteponer al valor una palabra determinada.
```suggestion
Para utilizar props (valores pasados) de una entrada de blog `.md` en tu diseño, como etiquetas, necesitas agregar un prefijo especial al valor.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +Para comprobar tu trabajo, o si simplemente quieres un código completo y correcto para copiar en `MarkdownPostLayout.astro`, aquí tienes el aspecto que debería tener tu componente Astro:
```suggestion
Para comprobar tu trabajo, o si simplemente quieres un código completo y correcto para copiar en `MarkdownPostLayout.astro`, aquí tienes el aspecto que debería tener tu componente de Astro:
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +Haga coincidir cada ruta de archivo con una segunda ruta de archivo que creará una página en la misma ruta.
```suggestion
Coincide cada ruta de archivo con una segunda ruta de archivo que creará una página en la misma ruta.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +  Instale el paquete oficial de Astro para crear un feed al que sus lectores puedan
```suggestion
  Instala el paquete oficial de Astro para crear un feed al que tus lectores puedan
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +  - Instale un paquete Astro para crear un canal RSS para su sitio web
```suggestion
  - Instala un paquete de Astro para crear un canal RSS para su sitio web
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +  - Crear un feed al que puedan suscribirse y leer los lectores de feeds RSS
```suggestion
  - Crea un feed que pueda ser suscrito y leído por lectores de RSS.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +Astro ofrece un paquete personalizado para añadir rápidamente un canal RSS a su sitio web.
```suggestion
Astro ofrece un paquete personalizado para agregar rápidamente un feed RSS a tu sitio web.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +1. Salga del servidor de desarrollo de Astro y ejecute el siguiente comando en el terminal para instalar el paquete RSS de Astro.
```suggestion
1. Sal del servidor de desarrollo de Astro y ejecuta el siguiente comando en el terminal para instalar el paquete RSS de Astro.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +2. Copie el siguiente código en este nuevo documento, sustituyendo la propiedad `site` por la URL única de Netlify de su sitio. Personalice las propiedades `title` y `description`, y si es necesario,
```suggestion
2. Copia el siguiente código en este nuevo documento, sustituyendo la propiedad `site` por la URL única de Netlify de tu sitio. Personaliza las propiedades `title` y `description`, y si es necesario, especifica un idioma diferente en `customData`:
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +3. Este documento `rss.xml` sólo se crea cuando se construye su sitio, por lo que no podrá ver esta página en su navegador durante el desarrollo. Salga del servidor de desarrollo y ejecute los siguie
```suggestion
3. Este documento `rss.xml` sólo se crea cuando se construye tu sitio, por lo que no podrás ver esta página en tu navegador durante el desarrollo. Sal del servidor de desarrollo y ejecuta los siguientes comandos para, en primer lugar, construir tu sitio localmente y, a continuación, ver una vista previa de tu construcción:
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +4. Visite `localhost:3000/rss.xml` y compruebe que puede ver texto (sin formato) en la página con un `item` para cada uno de sus archivos `.md`. Cada elemento debe contener información sobre la entra
```suggestion
4. Visita `localhost:3000/rss.xml` y comprueba que puedes ver texto (sin formato) en la página con un `item` para cada uno de tus archivos `.md`. Cada elemento debe contener información sobre la entrada del blog, como `title`, `url` y `description`.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +- [ ] Puedo instalar un paquete Astro utilizando la línea de comandos.
```suggestion
- [ ] Puedo instalar un paquete de Astro utilizando la línea de comandos.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/4.mdx
> +- [ ] Puedo crear un canal RSS para mi sitio web.
```suggestion
- [ ] Puedo crear un feed RSS para mi sitio web.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/index.mdx
> +En esta unidad, dotarás a tu blog de una página de índice, páginas de etiquetas y un canal RSS.
```suggestion
En esta unidad, mejorarás tu blog con una página de índice, páginas de etiquetas y un feed de RSS.
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/index.mdx
> +- `Astro.glob()` para acceder a los datos de los archivos de su proyecto
```suggestion
- `Astro.glob()` para acceder a los datos de los archivos de tu proyecto
```

2023-05-01 23:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/index.mdx
> +- El paquete Astro RSS para crear un canal RSS
```suggestion
- El paquete Astro RSS para crear un feed RSS.
```

2023-05-01 23:52 UTC, Waxer59 reviewed
Incredible PR 🤯🤯, I've been reviewing section 5, there's something I've noticed that you need to check and change when applying the changes:

* There are several instances where you use "usted" instead of "tu", you need to correct this and make sure to use "tu" instead of "usted".
* In the questionnaires, there are terms that have been translated, but within the questionnaire, the term appears untranslated. Please carefully review which terms you have translated and maintain the translation of those terms throughout the entire document. This provides consistency to the translation and avoids confusing the user.
* There are parts, such as links, that you have translated, which could create errors and cause the code or link to not work and "break" the tutorial. Please check if you have translated something that could directly affect the steps of the tutorial to avoid creating errors.

I will send you the review of section 6 soon.

Thank you for the incredible contribution 🎉🎉🎉

2023-05-02 00:05 UTC, dreyfus92 commented
Thank you por helping reviewing this @Waxer59, @juanburg98 We'll wait until you're done applying the suggestions that @Waxer59 previously mentioned so we can do a quick check and see if we can merge this. Good job everybody.

2023-05-02 19:52 UTC, Waxer59 reviewed
Here are some suggestions for section 6 (and some of section 5) 🥳, and I have a couple of important observations:

* There are several instances where you use "usted" instead of "tu", you need to correct this and make sure to use "tu" instead of "usted".
* In the `<PreCheck/>` blocks, you should use the verb in infinitive form because the user will see something like this:
```
PREPÁRATE PARA...

* Agregar Preact a tu proyecto de Astro. 
* Incluir islas de Astro (componentes .jsx de Preact) en tu página de inicio. 
* Usar directivas client: para hacer que las islas sean interactivas.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +3. Importe y utilice este componente en su página de inicio `index.astro`.
```suggestion
3. Importa y utiliza este componente en tu página de inicio `index.astro`.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +4. Add a second `<Greeting />` component with the `client:load` directive.
Te falta traducir

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +  6. Una vez que la diferencia sea clara, retire el componente de saludo no hidratado.
```suggestion
  6. Una vez que la diferencia esté clara, elimina el componente Greeting sin hidratar
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +Considere un componente Astro con el siguiente código:
```suggestion
Considera un componente Astro con el siguiente código:
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +Para cada uno de los siguientes componentes, identifique lo que se enviará al navegador:
```suggestion
Para cada uno de los siguientes componentes, identifica lo que se enviará al navegador:
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +1. ¿Cuál de los cinco componentes islas se **hidratará**, enviando JavaScript al cliente?
```suggestion
1. ¿Cuáles de los cinco componentes serán islas hidratadas, enviando JavaScript al cliente?
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +      <Spoiler>`<PreactBanner client:load />` and `<SvelteCounter client:visible />` serán islas hidratadas.</Spoiler>
```suggestion
      <Spoiler>`<PreactBanner client:load />` and `<SvelteCounter client:visible />` serán islas hidratadas.</Spoiler>
```
```suggestion
      <Spoiler>`<PreactBanner client:load />`  y `<SvelteCounter client:visible />` serán islas hidratadas.</Spoiler>
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +      <Spoiler>Pruebe a pulsar el botón y vea cuál es el interactivo. Si responde a su entrada, debe haber tenido una directiva `client:`.</Spoiler>
```suggestion
      <Spoiler>Prueba a pulsar el botón y observa cuál es el interactivo. Si responde a tu entrada, debe haber tenido una directiva `client:`.</Spoiler>
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +title: 'De vuelta a tierra firme. Lleva tu blog del día a la noche, ¡sin necesidad de isla!'
```suggestion
title: 'De vuelta a tierra firme. Lleva tu blog del día a la noche, ¡sin necesidad de islas!'
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +Ahora que ya puedes construir islas Astro para elementos interactivos, no olvides que puedes llegar muy lejos con sólo JavaScript y CSS.
```suggestion
Ahora que puedes construir islas de Astro para elementos interactivos, ¡no olvides que puedes llegar bastante lejos con solo JavaScript y CSS básicos!
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +Vamos a crear un icono en el que se pueda hacer clic para que los usuarios puedan togglear entre los modos claro y oscuro utilizando otra etiqueta `<script>` para la interactividad... sin enviar Java
```suggestion
Vamos a crear un icono en el que se pueda hacer clic para que los usuarios puedan togglear entre los modos claro y oscuro utilizando otra etiqueta `<script>` para la interactividad... sin enviar JavaScript al navegador.
```
```suggestion
Vamos a crear un icono en el que se pueda hacer clic para que los usuarios puedan alternar entre los modos claro y oscuro utilizando otra etiqueta `<script>` para la interactividad... sin enviar JavaScript al navegador.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +  - Cree un toggle interactivo con sólo JavaScript y CSS
```suggestion
  - Crear un toggle interactivo con sólo JavaScript y CSS
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +  - Envíe la menor cantidad posible de JavaScript al navegador.
```suggestion
  - Enviar la menor cantidad posible de JavaScript al navegador.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +3. Visita la vista previa de tu navegador en `localhost:3000` para ver el icono ahora en todas tus páginas. Puede intentar hacer clic en él, pero aún no ha escrito un script para hacerlo interactivo.
```suggestion
3. Visita la vista previa de tu navegador en `localhost:3000` para ver el icono ahora en todas tus páginas. Puedes intentar hacer clic en él, pero aún no has escrito un script para hacerlo interactivo.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +1. En `global.css`, define algunos estilos oscuros. Usted puede elegir su propio, o copiar y pegar:
```suggestion
1. En `global.css`, define algunos estilos oscuros. Puedes elegir los tuyos propios o copiar y pegar:
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +Para añadir interactividad a un componente Astro, puede utilizar una etiqueta `<script>`. Este script puede comprobar y establecer el tema actual desde `localStorage` y toggle el tema cuando se hace
```suggestion
Para añadir interactividad a un componente de Astro, puedes utilizar una etiqueta `<script>`. Este script puede comprobar y establecer el tema actual desde  `localStorage` y alternar el tema cuando se hace clic en el icono. 
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +1. Le permiten incluir elementos de UI interactivos en su sitio web.
```suggestion
1. Te permiten incluir elementos de UI interactivos en tu sitio web.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +2. Crearán elementos estáticos en su sitio a menos que incluya un `client:` para enviar su JavaScript al cliente y ejecutarlo en el navegador.
```suggestion
2. Los elementos crearán contenido estático en tu sitio a menos que incluyas un `client:` para enviar tu JavaScript al cliente y ejecutarlo en el navegador.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/3.mdx
> +Continúe con nuestra [guía para migrar este proyecto a colecciones de contenido](/es/guides/content-collections/#migrating-from-file-based-routing)
```suggestion
Continúa con nuestra [guía para migrar este proyecto a colecciones de contenido](/es/guides/content-collections/#migrating-from-file-based-routing)
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/3.mdx
> +[Únase a nosotros en Discord](https://astro.build/chat)
```suggestion
[Únete a nosotros en Discord](https://astro.build/chat)
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +unitTitle: Zarpar hacia las islas Astro
```suggestion
unitTitle: Zarpar hacia las islas de Astro
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +title: 'Check in: Unidad 6 - Astro Islas'
```suggestion
title: 'Check in: Unidad 6 - Islas de Astro'
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +  Utiliza las islas Astro para incorporar componentes frontales a tu sitio Astro.
```suggestion
  Utiliza las islas de Astro para incorporar componentes frontales a tu sitio de Astro.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +En esta unidad, utilizarás **Astro islands** para introducir componentes de frontend framework en tu sitio Astro.
```suggestion
En esta unidad, utilizarás **Astro islands** para introducir componentes de frontend framework en tu sitio de Astro. 
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +Lo harás:
```suggestion
Aprenderás a:
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +- Añade un marco de UI, Preact, a tu proyecto Astro
```suggestion
- Añadeir framework de UI, Preact, a tu proyecto de Astro
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +- Utilice Preact para crear un componente de saludo interactivo
```suggestion
- Utilizar Preact para crear un componente de saludo interactivo
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +- Sepa cuándo _no_ elegir islas para la interactividad
```suggestion
- Saber cuándo _no_ elegir islas para la interactividad
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +- [ ] Estoy lista para añadir interactividad a mi sitio y empezar a vivir la vida isleña.
```suggestion
- [ ] ¡Estoy listo para agregar interactividad a mi sitio y comenzar a vivir esa vida de isla!
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/1.mdx
> +2. Añade la posibilidad de utilizar componentes Preact en tu proyecto Astro con un solo comando:
```suggestion
2. Añade la posibilidad de utilizar componentes Preact en tu proyecto de Astro con un solo comando:
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Etiquetas Astro `<script>`
```suggestion
        Etiquetas `<script>` de Astro
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Etiquetas Astro `<script>`.
```suggestion
        Etiquetas `<script>` de Astro
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Etiquetas Astro `<script>`.
```suggestion
        Etiquetas `<script>` de Astro
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Etiquetas Astro `<script>`.
```suggestion
       Etiquetas `<script>` de Astro
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Etiquetas Astro `<script>`.
```suggestion
        Etiquetas `<script>` de Astro
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Componentes del framework UI
```suggestion
        Componentes de frameworks de UI
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Componentes del framework UI
```suggestion
        Componentes de frameworks de UI
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Componentes del framework UI
```suggestion
        Componentes de frameworks de UI
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Componentes del framework UI
```suggestion
        Componentes de frameworks de UI
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        Componentes del framework UI
```suggestion
        Componentes de frameworks de UI
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        ambos
```suggestion
        Ambas opciones
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        ambos
```suggestion
        Ambas opciones
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        ambos
```suggestion
        Ambas opciones
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        ambos
```suggestion
        Ambas opciones
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +        ambos
```suggestion
        Ambas opciones
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +3. Permiten "probar" un nuevo framework sin necesidad de iniciar un proyecto completamente nuevo con esa pila tecnológica.
```suggestion
3. Te permiten "probar" un nuevo framework sin necesidad de iniciar un proyecto completamente nuevo con esa pila tecnológica.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +4. Permiten reutilizar el código que se ha escrito en otros frameworks y, a menudo, basta con soltarlos directamente en el sitio.
```suggestion
4. Te permiten reutilizar el código que se ha escrito en otros frameworks y, a menudo, basta con soltarlos directamente en el sitio.
```

2023-05-02 19:52 UTC, Waxer59 commented on src/content/docs/es/tutorial/6-islands/2.mdx
> +5. Permiten añadir interactividad sin necesidad de conocer o aprender otros frameworks de JavaScript.
```suggestion
5. Te permiten añadir interactividad sin necesidad de conocer o aprender otros frameworks de JavaScript.
```

2023-05-02 19:52 UTC, Waxer59 reviewed
Here are some suggestions for section 6 (and some of section 5) 🥳, and I have a couple of important observations:

* There are several instances where you use "usted" instead of "tu", you need to correct this and make sure to use "tu" instead of "usted".
* In the `<PreCheck/>` blocks, you should use the verb in infinitive form because the user will see something like this:
```
PREPÁRATE PARA...

* Agregar Preact a tu proyecto de Astro. 
* Incluir islas de Astro (componentes .jsx de Preact) en tu página de inicio. 
* Usar directivas client: para hacer que las islas sean interactivas.
```

2023-05-03 02:42 UTC, dreyfus92 reviewed
@juanburg98 te dejo otras sugerencias de la segunda revisión que le vamos a dar. Estás solo son para la carpeta `0-introduction`

2023-05-03 02:42 UTC, dreyfus92 commented on src/content/docs/es/tutorial/1-setup/1.mdx
> +## Obtenga las herramientas de desarrollo que necesites
```suggestion
## Obtén las herramientas de desarrollo que necesites
```

2023-05-03 11:29 UTC, juanburg98 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +2. Navigate to `localhost:3000/tags` and verify that your site now contains a page at this URL. It will be empty, but it will exist.
Listo 👍

2023-05-03 22:27 UTC, Waxer59 reviewed
Aquí está mi revisión de la sección 1. En breve te enviaré otra para corregir los bloques `<PreCheck>` que tienen errores.

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/2.mdx
> +Mientras el servidor Astro esté funcionando en modo de desarrollo, NO podrás ejecutar comandos en esa terminal. En su lugar, este panel te dará retroalimentación mientras previsualiza su sitio.
```suggestion
Mientras el servidor Astro esté funcionando en modo de desarrollo, NO podrás ejecutar comandos en esa terminal. En su lugar, este panel te dará retroalimentación mientras previsualizas tu sitio.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/3.mdx
> +    Escribe en el editor para cambiar el texto del encabezado de tu página y guarde el cambio.
```suggestion
    Escribe en el editor para cambiar el texto del encabezado de tu página y guarda el cambio.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/3.mdx
> +- [ ] ¡Soy un desarrollador Astro!
```suggestion
- [ ] ¡Soy un desarrollador de Astro!
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/3.mdx
> +¡Enhorabuena! Ya eres desarrollador Astro.
```suggestion
¡Enhorabuena! Ya eres desarrollador de Astro.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/4.mdx
> +  - Pon en línea tu repositorio de proyectos
```suggestion
  - Poner en línea tu repositorio de proyectos
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/3.mdx
> +  - Realiza la primera edición de tu nuevo sitio web
```suggestion
  - Realizar la primera edición de tu nuevo sitio web
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/4.mdx
> +### Vea su proyecto en GitHub
```suggestion
### Ver tu proyecto en GitHub
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/4.mdx
> +5. En la parte superior del panel de menú, habrá un lugar para introducir un **commit message** (descripción de los cambios de su archivo). Escriba `initial commit` y pulse el botón <kbd>Commit</kbd>
```suggestion
5. En la parte superior del panel de menú, habrá un lugar para introducir un **commit message** (descripción de los cambios de su archivo). Escribe `initial commit` y pulsa el botón <kbd>Commit</kbd> para confirmar los cambios.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/4.mdx
> +4. Deberías ver una lista de todos tus repositorios en GitHub. Elige el que creaste para este proyecto. Si no ves tu proyecto, pega directamente su URL de GitHub. Puede que también se te pida que le
```suggestion
4. Deberías ver una lista de todos tus repositorios en GitHub. Elige el que creaste para este proyecto. Si no ves tu proyecto, pega directamente tu URL de GitHub. Puede que también se te pida que le des un nombre local a este repositorio. Puedes seleccionar el nombre que quieras.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/4.mdx
> +1. Haz clic en la pestaña Control de código fuente en su VS Code para ver una lista de los archivos que han cambiado. Si aparece un mensaje indicando que necesita instalar `git`, sigue las instruccio
```suggestion
1. Haz clic en la pestaña Control de código fuente en tu VS Code para ver una lista de los archivos que han cambiado. Si aparece un mensaje indicando que necesita instalar `git`, sigue las instrucciones que se proporcionan y, a continuación, vuelve a cargar VS Code.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +  - Añade tu repositorio GitHub como una nueva aplicación Netlify
```suggestion
  - Añadir tu repositorio GitHub como una nueva aplicación Netlify
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +  - Despliega tu sitio Astro en la web
```suggestion
  - Desplegar tu sitio de Astro en la web
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +2. Clic en <kbd>Añadir nuevo sitio</kbd> > <kbd>Importar un proyecto existente</kbd>.
```suggestion
2. Haz clic en <kbd>Añadir nuevo sitio</kbd> > <kbd>Importar un proyecto existente</kbd>.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +En la página de resumen de tu sitio en Netlify, verá el nombre de su proyecto generado aleatoriamente, y la URL de tu sitio web de la forma `https://project-name-123456.netlify.app`. Puede cambiar el
```suggestion
En la página de resumen de tu sitio en Netlify, verás el nombre de tu proyecto generado aleatoriamente, y la URL de tu sitio web de la forma `https://project-name-123456.netlify.app`. Puede cambiar el nombre de tu proyecto por algo más memorable y esto actualizará automáticamente tu URL.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +Tu quieres actualizar la página de inicio de tu sitio web actual. ¿Qué pasos debes seguir?
```suggestion
Quieres actualizar la página de inicio de tu sitio web actual. ¿Qué pasos debes seguir?
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +Esta unidad te muestra cómo configurar tu entorno de desarrollo y desplegar en Netlify. Pase a la [Unidad 2](/es/tutorial/2-pages/) si ya te sientes cómodo con tu entorno y flujo de trabajo.
```suggestion
Esta unidad te muestra cómo configurar tu entorno de desarrollo y desplegar en Netlify. Pasa a la [Unidad 2](/es/tutorial/2-pages/) si ya te sientes cómodo con tu entorno y flujo de trabajo.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +1. Presiona en el botón <kbd>Conectar Repositorio</kbd> en la parte superior de la lista de archivos, ingresa una nombre para dicho repositorio y haz clic en <kbd>Crear Repo & push</kbd>.
```suggestion
1. Presiona el botón <kbd>Conectar Repositorio</kbd> en la parte superior de la lista de archivos, ingresa un nombre para dicho repositorio y haz clic en <kbd>Create Repo & push</kbd>. 
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/2.mdx
> +6. Cuando el prompt te pregunte si planeas escribir TypeScript, teclea `n`.
```suggestion
6. Cuando el prompt te pregunte si planeas escribir TypeScript, escribe `n`. 
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/2.mdx
> +7. Cuando el prompt te pregunte: "Would you like to initialize a new git repository?", escriba `y`.
```suggestion
7. Cuando el prompt te pregunte: "Would you like to initialize a new git repository?", escribe `y`.
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/3.mdx
> +  Tutorial: Crea tu primer blog Astro —
```suggestion
  Tutorial: Crea tu primer blog en Astro —
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/4.mdx
> +Si ya estás familiarizado con git y tienes tu propio flujo de trabajo, crea un nuevo repositorio de GitHub para tu proyecto utilizando el método que prefieras. Pasa a la página siguiente: ["Despliegu
```suggestion
Si ya estás familiarizado con git y tienes tu propio flujo de trabajo, crea un nuevo repositorio de GitHub para tu proyecto utilizando el método que prefieras. Pasa a la siguiente página: ["Despliegue de su sitio en la Web"](/es/tutorial/1-setup/5/).
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +  Tutorial: Crea tu primer blog Astro —
```suggestion
  Tutorial: Crea tu primer blog en Astro —
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/5.mdx
> +Aquí, conectarás tu repositorio de GitHub a Netlify. Netlify utilizará ese proyecto para construir y desplegar tu sitio en vivo en la web cada vez que confirmes un cambio en tu código.
```suggestion
Aquí, conectarás tu repositorio de GitHub a Netlify. Netlify utilizarás ese proyecto para construir y desplegar tu sitio en vivo en la web cada vez que confirmes un cambio en tu código. 
```

2023-05-03 22:27 UTC, Waxer59 commented on src/content/docs/es/tutorial/1-setup/index.mdx
> +A medida que escribas código, enviarás periódicamente tus cambios a GitHub. Netlify utilizará los archivos de tu repositorio de GitHub para construir tu sitio web, y luego lo publicará en Internet en
```suggestion
A medida que escribas código, enviarás periódicamente tus cambios a GitHub. Netlify utilizará los archivos de tu repositorio de GitHub para construir tu sitio web, y luego lo publicarás en Internet en una dirección única donde cualquiera podrá verlo.
```

2023-05-03 22:50 UTC, Waxer59 reviewed
Aqui tienes la revisión de los bloques `<PreCheck>` 🤠

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/1.mdx
> +  - Crea dos nuevas páginas en su sitio web: Acerca de y Blog
```suggestion
  - Crear dos nuevas páginas en tu sitio web: Acerca de y Blog
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/1.mdx
> +  - Añade enlaces de navegación a tus páginas
```suggestion
  - Añadir enlaces de navegación a tus páginas
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/1.mdx
> +  - Despliega en la web una versión actualizada de tu sitio web
```suggestion
  - Desplegar en la web una versión actualizada de tu sitio web
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/2.mdx
> +  - Crea una nueva carpeta y crea un nuevo post
```suggestion
  - Crear una nueva carpeta y un nuevo post
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/2.mdx
> +  - Enlaza tus posts en la página de tu blog
```suggestion
  - Enlazar tus posts en la página de tu blog
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/3.mdx
> +  - Define el título de tu página en el frontmatter y utilízalo en su HTML
```suggestion
  - Definir el título de tu página en el frontmatter y utilízarlo en tu HTML
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/3.mdx
> +  - Visualización condicional de elementos HTML
```suggestion
  - Mostrar elementos HTML condicionalmente
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/3.mdx
> +  - Añade contenido sobre ti
```suggestion
  - Añadir algo de contenido sobre ti
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/4.mdx
> +  - Elementos de estilo en una sola página
```suggestion
  - Estilizar elementos en una sola página.
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/3-components/1.mdx
> +  - Crea una nueva carpeta para los componentes
```suggestion
  - Crear una nueva carpeta para los componentes
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/3-components/1.mdx
> +  - Crea un componente Astro para mostrar tus enlaces de navegación
```suggestion
  - Crear un componente Astro para mostrar tus enlaces de navegación
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/3-components/1.mdx
> +  - Sustituye el HTML existente por un nuevo componente de navegación reutilizable
```suggestion
  - Sustituir el HTML existente por un nuevo componente de navegación reutilizable
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/3-components/2.mdx
> +  - Crea un componente de pie de página
```suggestion
  - Crear un componente de pie de página
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/3-components/2.mdx
> +  - Crea y pasa props a un componente de medios sociales
```suggestion
  - Crear y pasar props a un componente de redes sociales
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/3-components/3.mdx
> +  - Crea un header para tu sitio que contenga el componente de navegación
```suggestion
  - Crear un header para tu sitio que contenga el componente de navegación
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/3-components/4.mdx
> +  - Escribe un `<script>` para que los visitantes de tu sitio puedan abrir y cerrar el menú de navegación
```suggestion
  - Escribir un `<script>` para que los visitantes de tu sitio puedan abrir y cerrar el menú de navegación
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/3-components/4.mdx
> +  - Mueve tu JavaScript a un archivo `.js`.
```suggestion
  - Mover tu JavaScript a un archivo `.js`.
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/4-layouts/1.mdx
> +  - Refactorización de elementos comunes en un diseño de página
```suggestion
  - Refactorizar elementos comunes en un diseño de página
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/4-layouts/1.mdx
> +  - Utiliza un elemento Astro `<slot />` para colocar el contenido de la página dentro de un diseño
```suggestion
  - Utilizar el elemento `<slot />` de Astro para colocar el contenido de la página dentro de un diseño
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/4-layouts/1.mdx
> +  - Pasar valores específicos de la página como props a su layout
```suggestion
  - Pasar valores específicos de la página como props a tu layout
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/4-layouts/2.mdx
> +  - Cree una nueva plantilla de entrada de blog para tus archivos Markdown
```suggestion
  - Crear una nueva plantilla de entrada de blog para tus archivos Markdown
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/4-layouts/3.mdx
> +  - Anida el layout de los posts de tu blog dentro del layout de tu página principal
```suggestion
  - Anidar el diseño de tus publicaciones de blog dentro del diseño principal de tu página
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +  - Agrega una nueva página utilizando el patrón de enrutamiento `/my-folder/index.astro`
```suggestion
  - Agregar una nueva página utilizando el patrón de enrutamiento `/my-folder/index.astro`
```

2023-05-03 22:50 UTC, Waxer59 commented on src/content/docs/es/tutorial/5-astro-api/3.mdx
> +  - Muestra una lista de todas sus etiquetas únicas, con enlaces a cada página de etiquetas
```suggestion
  - Mostrar una lista de todas sus etiquetas únicas, con enlaces a cada página de etiquetas
```

2023-05-05 00:47 UTC, Waxer59 reviewed
Aqui tienes mi revisión de la sección 3

2023-05-05 13:43 UTC, juanburg98 commented
@Waxer59 todos los cambios fueron realizados, gracias por tu ayuda

2023-05-07 20:45 UTC, kevinzunigacuellar commented
Bueno esta PR la veo muy lista para merge, luego de casi ~ 600 interacciones. Gracias a todos @juanburg98, @Waxer59 , @delucis y @Yan-Thomas

2023-05-07 21:48 UTC, merged

2023-05-08 11:59 UTC, juanburg98 commented
Thanks to everyone who taught me how to do the commits and to all of you for your input and reviews.  ❤

Gracias a todos los que me enseñaron a hacer los commits y a todos por sus aportes y revisiones .  ❤