i18n(zh-cn): Translated astro-syntax.mdx
withastro/docs pull request #2982
Opened 2023-04-04 04:03 UTC by allenli178

2023-04-17 19:29 UTC, Yan-Thomas commented
Thanks @allenli178! FYI, this page is marked as `i18nReady: false`, which means we don't want to have this page translated yet, since it can go through big changes. I'll draft your PR and when this page becomes available for translation I'll open it again. 🙌

2023-07-20 20:41 UTC, imchell requested changes

2023-07-20 20:41 UTC, imchell commented on src/content/docs/zh-cn/guides/content-collections.mdx
> +模式在集合中强制执行一致的front-matter。模式**保证**当你需要引用或查询它时，你的 frontmatter 以可预测的形式存在。如果任何文件违反了它的集合模式，Astro 将提供一个有用的错误让你知道。
There is a missing space between the Chinese and English text.

2023-07-20 20:41 UTC, imchell commented on src/content/docs/zh-cn/core-concepts/astro-syntax.mdx
> +- **变量名必须大**。例如，使用 `Element`，而不是 `element`。否则，Astro 将尝试把变量名渲染为文本 HTML 标签。
变量名必须大 -> 变量名首字母必须大写？

2023-07-24 01:29 UTC, liruifengv commented on src/content/docs/zh-cn/core-concepts/astro-syntax.mdx
> +### 片段及多元素
Some content is outdated. See commit: https://github.com/withastro/docs/commit/6b6f629e2241dce12dd4763124d00eeb223aa1f4

2023-07-28 08:40 UTC, liruifengv commented
@allenli178 你好，我们正在组织社区译者来进行 Astro 中文文档的翻译，你是否愿意继续推动这个 PR 的进行呢？如果你因为其他原因不能推进，我们愿意接手过来。期待你的回复。

2023-07-28 08:45 UTC, allenli178 commented
有时间的，也希望可以为社区做点贡献。



---Original---
From: ***@***.***&gt;
Date: Fri, Jul 28, 2023 16:40 PM
To: ***@***.***&gt;;
Cc: "YuYan ***@***.******@***.***&gt;;
Subject: Re: [withastro/docs] i18n(zh-cn): Translated astro-syntax.mdx (PR#2982)




 
@allenli178 你好，我们正在组织社区译者来进行 Astro 中文文档的翻译，你是否愿意继续推动这个 PR 的进行呢？如果你因为其他原因不能推进，我们愿意接手过来。期待你的回复。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

2023-08-04 08:06 UTC, liruifengv commented
@Yan-Thomas Can you make the CI run the `check link`?

2023-08-04 08:18 UTC, liruifengv requested changes

2023-08-04 08:18 UTC, liruifengv commented on src/content/docs/zh-cn/core-concepts/astro-syntax.mdx
> +<button onClick={handleClick}>Nothing will happen when you click me!</button>
```suggestion
<button onClick={handleClick}>当你点击我的时候什么都不会发生！</button>
```
There may be a need for translation here as well.

2023-08-04 08:18 UTC, liruifengv commented on src/content/docs/zh-cn/core-concepts/astro-syntax.mdx
> +// Template with multiple elements
```suggestion
// 包含多个元素的模板
```

2023-08-04 08:18 UTC, liruifengv commented on src/content/docs/zh-cn/core-concepts/astro-syntax.mdx
> +<p>No need to wrap elements in a single containing element.</p>
```suggestion
<p>无需将元素包装在单个包含元素中。</p>
```

2023-08-04 08:18 UTC, liruifengv commented on src/content/docs/zh-cn/core-concepts/astro-syntax.mdx
> +<p>Astro supports multiple root elements in a template.</p>
```suggestion
<p>Astro 支持模板中的多个根元素。</p>
```

2023-08-04 08:22 UTC, liruifengv commented
@allenli178 内容集合页面，自从创建这个PR之间，有了很多提交，你可以更新一下吗。
你可以查看4月4号以来的所有 commit 历史：
https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/content-collections.mdx?since=2023-04-04T12:20:31.000Z

2023-08-04 08:24 UTC, allenli178 commented
好的 周末有空我会更新一下的

2023-08-04 12:27 UTC, Yan-Thomas commented
> @Yan-Thomas Can you make the CI run the check link?

done!

2023-08-07 01:38 UTC, allenli178 commented
有一些跨文件的链接。   以 ![image](https://github.com/withastro/docs/assets/53218750/a5cec036-9484-42c6-92e0-fc518d0770bc)为例。我要怎么写这样的链接。我试了  
![image](https://github.com/withastro/docs/assets/53218750/fe80ea20-980c-46ce-8603-20ce473a2cdc)
但是不起作用，只跳转到了相应的页面，但没有跳转到标题。
@liruifengv

2023-08-07 02:14 UTC, liruifengv commented on src/content/docs/zh-cn/guides/content-collections.mdx
> +Astro 提供了两个函数来查询一个集合并返回一个(或多个)内容条目: [`getCollection()`](/zh-cn/reference/api-reference/#`getCollection()`)和 [`getEntry()`](/zh-cn/reference/api-reference/#`getEntry()`)。
```suggestion
Astro 提供了两个函数来查询一个集合并返回一个(或多个)内容条目: [`getCollection()`](/zh-cn/reference/api-reference/#getcollection)和 [`getEntry()`](/zh-cn/reference/api-reference/#getentry)。
```
应该是这样，可以在原页面点击右侧目录看一下

2023-08-07 04:20 UTC, allenli178 commented
![image](https://github.com/withastro/docs/assets/53218750/b4b207b6-7fd8-4713-aca1-dc50faf61758)
There is a single link but no title in en/guides/content-collections.mdx docs

2023-08-07 05:27 UTC, liruifengv commented on src/content/docs/zh-cn/guides/content-collections.mdx
> +    例如，要迁移[教程中的博客文章](/en/tutorial/2-pages/2/) ，请将 `src/pages/post/` 的内容移动到 `src/content/posts/`。
```suggestion
    例如，要迁移[教程中的博客文章](/zh-cn/tutorial/2-pages/2/) ，请将 `src/pages/post/` 的内容移动到 `src/content/posts/`。
```

2023-08-07 05:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/content-collections.mdx
> +5. [从集合中生成路由](#从集合中生成路由)。在集合中，Markdown 和 MDX 文件不再使用 Astro 的[基于文件的路由](/zh-cn/guides/markdown-content/#基于文件的路由)自动成为页面，因此必须自己生成页面。
```suggestion
5. [从集合中生成路由](#从内容生成路由)。在集合中，Markdown 和 MDX 文件不再使用 Astro 的[基于文件的路由](/zh-cn/guides/markdown-content/#基于文件的路由)自动成为页面，因此必须自己生成页面。
```
Should be `#从内容生成路由`

2023-08-07 05:42 UTC, allenli178 commented on src/content/docs/zh-cn/guides/content-collections.mdx
> +    例如，要迁移[教程中的博客文章](/en/tutorial/2-pages/2/) ，请将 `src/pages/post/` 的内容移动到 `src/content/posts/`。
tutorial还没有中文翻译

2023-08-07 05:46 UTC, allenli178 commented on src/content/docs/zh-cn/guides/content-collections.mdx
> +5. [从集合中生成路由](#从集合中生成路由)。在集合中，Markdown 和 MDX 文件不再使用 Astro 的[基于文件的路由](/zh-cn/guides/markdown-content/#基于文件的路由)自动成为页面，因此必须自己生成页面。
已修改

2023-08-07 09:59 UTC, liruifengv commented on src/content/docs/zh-cn/guides/content-collections.mdx
> +    例如，要迁移[教程中的博客文章](/en/tutorial/2-pages/2/) ，请将 `src/pages/post/` 的内容移动到 `src/content/posts/`。
会 fallback 到英文

2023-08-07 10:05 UTC, allenli178 commented on src/content/docs/zh-cn/guides/content-collections.mdx
> +    例如，要迁移[教程中的博客文章](/en/tutorial/2-pages/2/) ，请将 `src/pages/post/` 的内容移动到 `src/content/posts/`。
已修改

2023-08-07 10:59 UTC, liruifengv approved these changes

2023-08-07 11:41 UTC, liruifengv commented
内容大体上可以了。但是其他页面应该有链接会挂掉，不知道为啥 check link 的 CI 没运行。

2023-08-07 19:34 UTC, Yan-Thomas commented
Runned the CI, there's well, lots of broken links! Could you fix them? After doing so I believe we're good to go!

2023-08-08 00:49 UTC, liruifengv commented on src/content/docs/zh-cn/guides/content-collections.mdx
> +有关将内容呈现为 HTML 的信息，请参见下面的[将内容渲染成 HTML](#将内容渲染成-hTML)。
```suggestion
有关将内容呈现为 HTML 的信息，请参见下面的[将内容渲染成 HTML](#将内容渲染成-html)。
```

2023-08-08 02:06 UTC, liruifengv commented
@allenli178 一有新的 commit 提交，CI 就重新运行了。你可以在本地全局搜索一下其他页面，有引用到这两个页面的链接的，锚点部分要改成对应中文

2023-08-08 02:09 UTC, allenli178 commented
ok, 我一会儿有空的时候弄一下。

2023-08-09 01:40 UTC, allenli178 commented
@liruifengv  @Yan-Thomas  
Please run  the CI to check links.

2023-08-09 12:54 UTC, liruifengv approved these changes
LGTM

2023-08-09 18:53 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-08-09 18:53 UTC, merged