i18n(es): Translated `contribute.mdx`
withastro/docs pull request #2990
Opened 2023-04-04 17:24 UTC by dreyfus92

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `contribute.mdx` to spanish 🚀

2023-04-04 19:06 UTC, kevinzunigacuellar reviewed
Algunos comentarios, gracias @dreyfus92 💜

2023-04-04 19:06 UTC, kevinzunigacuellar commented on src/content/docs/es/contribute.mdx
> +Aceptamos contribuciones de cualquier tamaño y contribuyentes de cualquier nivel de habilidad. Como un proyecto de código abierto, creemos en devolver a nuestros contribuyentes. Estamos encantados de
```suggestion
Aceptamos contribuciones de cualquier tamaño y contribuyentes de todos los niveles de habilidad. Como un proyecto de código abierto, creemos en devolver a nuestros contribuyentes. Estamos encantados de ayudar con orientación sobre PRs, escritura técnica y convertir cualquier en realidad.
```

2023-04-04 19:06 UTC, kevinzunigacuellar commented on src/content/docs/es/contribute.mdx
> +Cada PR, especialmente los PR de traducción, ¡necesita evaluadores! Revisar PR y dejar comentarios, sugerencias o un aprobador "LGTM!" ("¡Me parece bien!") Es una gran manera de comenzar en Team Docs
```suggestion
Cada PR, especialmente las PR de traducción, ¡necesita evaluadores! Revisar la PR y dejar comentarios, sugerencias o un aprobador "LGTM!" ("¡Me parece bien!") Es una gran manera de comenzar en Team Docs y aprender más sobre Astro.
```

2023-04-04 19:06 UTC, kevinzunigacuellar commented on src/content/docs/es/contribute.mdx
> +- [Guía de Escuadrón de Apoyo](https://github.com/withastro/docs/blob/main/SUPPORTSQUAD.md) - Como ayudar a Team Docs como parte de su rol de soporte.
```suggestion
- [Guía de Escuadrón de Apoyo](https://github.com/withastro/docs/blob/main/SUPPORTSQUAD.md) - Como ayudar a Team Docs como parte de soporte técnico.
```

2023-04-05 03:46 UTC, dreyfus92 commented
Muchas gracias por el review @kevinzunigacuellar 😁

2023-04-05 19:18 UTC, kevinzunigacuellar reviewed
Segunda re-leida, gracias por los fixes @dreyfus92

2023-04-05 19:18 UTC, kevinzunigacuellar commented on src/content/docs/es/contribute.mdx
> +Aceptamos contribuciones de cualquier tamaño y contribuyentes de todos los niveles de habilidad. Como un proyecto de código abierto, creemos en devolver a nuestros contribuyentes. Estamos encantados
```suggestion
Aceptamos contribuciones de cualquier tamaño y contribuyentes de todos los niveles de habilidad. Como un proyecto de código abierto, creemos en devolver a nuestros contribuyentes. Estamos encantados de ayudar con orientación sobre PRs, escritura técnica y convertir cualquier idea en realidad.
```

2023-04-05 19:18 UTC, kevinzunigacuellar commented on src/content/docs/es/contribute.mdx
> +Hay muchas formas de contribuir al sitio web de la documentación de Astro!
```suggestion
Hay muchas formas de contribuir a la documentación de Astro!
```

2023-04-05 19:18 UTC, kevinzunigacuellar commented on src/content/docs/es/contribute.mdx
> +Cada PR, especialmente las PR de traducción, ¡necesita evaluadores! Revisar la PR y dejar comentarios, sugerencias o un aprobador "LGTM!" ("¡Me parece bien!") Es una gran manera de comenzar en Team D
```suggestion
Cada PR, especialmente las PRs de traducción, ¡necesita evaluadores! Revisar la PR y dejar comentarios, sugerencias o aprobarla con un "LGTM!" ("¡Me parece bien!") Es una gran manera de comenzar en Team Docs y aprender más sobre Astro.
```

2023-04-05 19:18 UTC, kevinzunigacuellar commented on src/content/docs/es/contribute.mdx
> +Estos documentos son traídos por toda esta gente útil. [¡Únete a nosotros en GitHub!](https://github.com/withastro/docs)
```suggestion
Estos documentos son traídos por nuestra comunidad. [¡Únete a nosotros en GitHub!](https://github.com/withastro/docs)
```

2023-04-06 16:40 UTC, Yan-Thomas requested changes
Hey @dreyfus92, just found out now that we're missing the `ui.ts` label for the "Contributor Guides" item in the sidebar that is were you go to this page, could you add this to the PR? After this LGTM & good to be merged!

2023-04-06 17:01 UTC, dreyfus92 commented
> Hey @dreyfus92, just found out now that we're missing the `ui.ts` label for the "Contributor Guides" item in the sidebar that is were you go to this page, could you add this to the PR? After this LGTM & good to be merged!

do you mean the  `rightSidebar`?

2023-04-06 17:19 UTC, Yan-Thomas commented
> do you mean the rightSidebar?

Yes, here's the label: https://github.com/withastro/docs/blob/main/src/i18n/en/ui.ts#L26

2023-04-06 17:25 UTC, dreyfus92 commented
Done @Yan-Thomas 😄

2023-04-06 18:24 UTC, Yan-Thomas commented
Thanks @dreyfus92, LGTM!

2023-04-06 20:34 UTC, merged

2023-04-07 14:35 UTC, kevinzunigacuellar commented
Thanks a lot @Yan-Thomas and @dreyfus92 🚀