i18n(zh-cn): Translate from-nextjs.mdx
withastro/docs pull request #3011
Opened 2023-04-07 09:22 UTC by qlly0630

#### What kind of changes does this PR include?
- New or updated content
#### Description
- update src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx

2023-04-07 11:51 UTC, Yan-Thomas commented
Thanks for the PR @qlly0630, I'm going to share your PR with other Chinese translators in our Discord, and would love to have you there so you can share any contributions you make as well! https://astro.build/chat

2023-04-08 01:31 UTC, liruifengv requested changes

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +在Next.js中，你的posts要么在`/pages`，要么在`/app/routeName/page.jsx`。
```suggestion
在Next.js中，你的文章要么在`/pages`，要么在`/app/routeName/page.jsx`。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +在Astro中，**你所有的页面内容必须在`src/`**中，在`src/pages`或`src/content`其中。
Incorrect Markdown formatting here.

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +现有的Next JSX (.js)页面将需要从JSX文件转换为.astro页面。你不能在Astro中使用现有的JSX页面文件。
Missing link!

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +这些.astro页面必须位于src/pages/内，并将根据其文件路径自动生成页面路由。
Missing link!

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +Astro内置了对Markdown的支持和对MDX文件的可选整合。你可以复用任何现有的[Markdown和MDX文件](/zh-cn/guides/markdown-content/)，但它们可能需要对它们的frontmatter进行一些调整，比如添加[Astro的特殊`layout`前言属性](/zh-cn/corecepts/layouts/#markdownmdx-layouts)。你将不
```suggestion
Astro内置了对Markdown的支持和对MDX文件的可选整合。你可以复用任何现有的[Markdown和MDX文件](/zh-cn/guides/markdown-content/)，但它们可能需要对它们的frontmatter进行一些调整，比如添加[Astro的特殊`layout` frontmatter 属性](/zh-cn/core-concepts/layouts/#markdownmdx-布局)。你将不再需要为每个Markdown生成的路由手动创建页面。这些文件可以放在`src/pages/`中，利用文件即路由的优势自动生成。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +### Links
```suggestion
### 链接
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +Astro没有为links使用任何特殊的组件，但我们欢迎你建立你自己的`<Link>`组件。然后你可以像使用其他组件一样导入和使用这个`<Link>`。
```suggestion
Astro没有为链接使用任何特殊的组件，但我们欢迎你建立你自己的`<Link>`组件。然后你可以像使用其他组件一样导入和使用这个`<Link>`。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +### Imports
```suggestion
### 导入
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +更新任何[文件导入](/zh-cn/guides/imports/)以准确引用相对文件路径。这可以通过[import aliases](/zh-cn/guides/typescript/#import-aliases)来完成，或者通过写出相对路径的全称。
```suggestion
更新任何[文件导入](/zh-cn/guides/imports/)以准确引用相对文件路径。这可以通过[import aliases](/zh-cn/guides/typescript/#导入别名)来完成，或者通过写出相对路径的全称。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +可以使用[命名插槽](/zh-cn/corecepts/astro-components/#named-slots)将有多个子组件的React组件迁移到Astro组件。
```suggestion
可以使用[命名插槽](/zh-cn/core-concepts/astro-components/#命名插槽)将有多个子组件的React组件迁移到Astro组件。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +参考更多关于[Astro中具体的`<slot />`用法](/zh-cn/core-concepts/astro-components/#slots)。
```suggestion
参考更多关于[Astro中具体的`<slot />`用法](/zh-cn/core-concepts/astro-components/#插槽)。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +### Children Props
```suggestion
### 转换 Next 的 Children Props 到 Astro
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +### Fetching
```suggestion
### 转换 Next 的数据获取到 Astro
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +### Styling
```suggestion
### 转换 Next 的样式到 Astro
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +### Image
```suggestion
### 转换 Next 的 图像插件到 Astro
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +查看更多关于 [Styling in Astro](/zh-cn/guides/styling/)的信息。
```suggestion
查看更多关于[在 Astro 中设计样式](/zh-cn/guides/styling/)的信息。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +如果有必要，将任何内联样式对象（`style={{ fontWeight: "bold" }}`）转换成内联HTML样式属性（`style="font-weight:bold;"`）。或者，使用[Astro `<style>`标签](/zh-cn/guides/styling/#styling-in-astro)实现scoped CSS styles。
```suggestion
如果有必要，将任何内联样式对象（`style={{ fontWeight: "bold" }}`）转换成内联HTML样式属性（`style="font-weight:bold;"`）。或者，使用[Astro `<style>`标签](/zh-cn/guides/styling/#在-astro-进行设计)实现scoped CSS styles。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +用[Astro自己的图片集成组件](/zh-cn/guides/images/#astros-image-integration)，或用标准的HTML`<img>`来转换任何Next`<Image />`组件。请看[组件属性的完整列表](/zh-cn/guides/integrations-guide/image/#usage)，可用于Astro的`<Image />`和`<Picture />
```suggestion
用[Astro自己的图片集成组件](/zh-cn/guides/images/#astro-的图片集成)，或用标准的HTML`<img>`来转换任何Next`<Image />`组件。请看[组件属性的完整列表](/zh-cn/guides/integrations-guide/image/#usage)，可用于Astro的`<Image />`和`<Picture />`组件，注意有几个属性和Next不同。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +1. 定义return() JSX。
```suggestion
1. 定义要返回的 JSX。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +使用Next函数的返回值。将任何Next或React语法转换成Astro，包括改变任何[HTML全局属性]的大小写(https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes)。
Incorrect Markdown formatting!

MDN links maybe can use `zh-CN`

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +- `className` 变成 `class`.
```suggestion
- `className` 变成 `class`。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +- `<Link>` 变成 `<a>`.
```suggestion
- `<Link>` 变成 `<a>`。
```

2023-04-08 01:31 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +- Video: [NextJS to Astro: more control = faster sites](https://www.youtube.com/watch?v=PSzCtdM20Fc).
There also need to be translated.

2023-04-08 01:41 UTC, liruifengv commented
感谢你的贡献 @qlly0630 为了方便我直接说中文，我标记了一些错误出来：
- 检查所有中文的链接，#号之后的fragment
- 一些 core-concepts -> corecepts 的链接错误
- Markdown 格式渲染错误
- MDN 等外部链接，如果有对应中文站点，可以指向中文站点，例如 https://developer.mozilla.org/zh-CN/
- 更通顺的中文翻译
- 中文和英文单词之间可以有空格，如果你愿意处理的话

2023-04-17 19:23 UTC, Yan-Thomas commented
Hey @qlly0630, pinging for freshness! Could you commit liruifengv's suggestions to your PR? After this I think we're good to merge it!

2023-05-04 00:22 UTC, Yan-Thomas commented
This PR got stale, I'll be drafting it for now till you have the time to look through the suggested changes so we can merge it, thanks!

2023-05-23 09:12 UTC, qlly0630 commented
@liruifengv I've finished fixing all the issues in the code review, help with the code review again.

2023-05-23 09:29 UTC, liruifengv commented
> @liruifengv I've finished fixing all the issues in the code review, help with the code review again.↳

Please resolve the conversations.

2023-05-23 09:36 UTC, qlly0630 commented
> > @liruifengv I've finished fixing all the issues in the code review, help with the code review again.↳
> 
> Please resolve the conversations.

Done.

2023-05-23 09:46 UTC, liruifengv approved these changes
LGTM! Thanks for your continued follow-up @qlly0630

2023-05-23 12:09 UTC, qlly0630 commented
> One thing to note, a stable version of the app route layout for next.js has been released. We should update it in the original English version at a later date.

ok

2023-05-23 22:32 UTC, Yan-Thomas commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +查看更多关于[用`Astro.glob()`导入本地文件](/zh-cn/guides/imports/#astroglob)，[使用 Collections API 查询](/zh-cn/guides/content-collections/#querying-collections)或[获取远程数据](/zh-cn/guides/Data-fetching/)。
Fix broken link
```suggestion
查看更多关于[用`Astro.glob()`导入本地文件](/zh-cn/guides/imports/#astroglob)，[使用 Collections API 查询](/zh-cn/guides/content-collections/#querying-collections)或[获取远程数据](/zh-cn/guides/data-fetching/)。
```

2023-05-23 22:42 UTC, Yan-Thomas approved these changes
LGTM! Nice work peeps 💜

2023-05-23 22:42 UTC, merged