Updates Kinsta Deployment with SSR deployment
withastro/docs pull request #3030
Opened 2023-04-12 14:00 UTC by palmiak

#### What kind of changes does this PR include?

- New or updated content

#### Description

- It adds a tutorial on how to deploy SSR Astro to Kinsta
- Also, it changes the structure of the Deploy to Kinsta page

2023-04-12 14:16 UTC, ElianCodes approved these changes
Looks good to me!

2023-04-12 14:42 UTC, ElianCodes commented
Page of interest: https://deploy-preview-3030--astro-docs-2.netlify.app/en/guides/deploy/kinsta/

*just putting that up here in case anyone wants to read along*

2023-04-14 14:53 UTC, ElianCodes approved these changes
Looks very good! Approved by Talking and Doc'ing team!

Just a few comments

2023-04-15 20:10 UTC, Jutanium requested changes
Left some comments. Great work!

2023-04-15 20:13 UTC, ElianCodes commented
Dan forgot to apply his changes; now that he did, when changes addressed, everything else looks fine!

2023-04-15 20:59 UTC, palmiak commented on src/content/docs/en/guides/deploy/kinsta.mdx
> +- Include a `name` field in your `package.json`. (This can be anything, and will not affect your deployment.)
In theory, `name` is always required in the package.json file.package.json (https://docs.npmjs.com/creating-a-package-json-file#required-name-and-version-fields), also some buildpack environments (like the one that Kinsta uses) will throw an error when `name` isn`t there,

2023-04-16 07:34 UTC, ElianCodes commented on src/content/docs/en/guides/deploy/kinsta.mdx
> +- Include a `name` field in your `package.json`. (This can be anything, and will not affect your deployment.)
Little nitpick here, `name` is required, but only in the case you're actually wanting to publish the package on NPM

2023-04-16 08:36 UTC, palmiak commented on src/content/docs/en/guides/deploy/kinsta.mdx
> +- Include a `name` field in your `package.json`. (This can be anything, and will not affect your deployment.)
True, but an automated environment that is building from package.json file doesn't know that.

In general some buildpacks will throw an error that 'name' is missing. Kinsta requires it, I see that fly.io too (https://community.fly.io/t/fly-launch-couldnt-parse-package-json-error/6308) and probably Heroku too.

2023-04-20 07:46 UTC, Jutanium approved these changes

2023-04-20 07:47 UTC, merged