i18n(zh-cn): Translated get-static-paths-required.mdx
withastro/docs pull request #3038
Opened 2023-04-13 05:43 UTC by magnum-zx

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description
translated get-static-paths-required.mdx

2023-04-13 06:01 UTC, liruifengv commented on src/content/docs/zh-cn/reference/errors/get-static-paths-required.mdx
> +# Translators, please remove this note and the <DontEditWarning/> component.
There was not need for translations.

2023-04-13 06:07 UTC, liruifengv requested changes

2023-04-13 06:07 UTC, liruifengv commented on src/content/docs/zh-cn/reference/errors/get-static-paths-required.mdx
> +<DontEditWarning />
`<DontEditWarning />` not need.

2023-04-13 06:07 UTC, liruifengv commented on src/content/docs/zh-cn/reference/errors/get-static-paths-required.mdx
> +在[静态模式](/zh-cn/core-concepts/routing/#static-ssg-mode)下，所有路由都必须在构建时确定。因此，动态路由必须`export`一个 `getStaticPaths` 函数，来返回将要生成的不同路径。
There has a broken link. `routing.mdx` is outdated

2023-04-13 06:07 UTC, liruifengv commented on src/content/docs/zh-cn/reference/errors/get-static-paths-required.mdx
> +-  [Dynamic Routes](/zh-cn/core-concepts/routing/#dynamic-routes)
There is also a need to translate. Broken link too.
```suggestion
-  [动态路由](/zh-cn/core-concepts/routing/#动态路由)
```

2023-04-13 06:07 UTC, liruifengv commented on src/content/docs/zh-cn/reference/errors/get-static-paths-required.mdx
> +-  [Server-side Rendering](/zh-cn/guides/server-side-rendering/)
```suggestion
-  [服务端渲染](/zh-cn/guides/server-side-rendering/)
```

2023-04-13 06:08 UTC, liruifengv commented
Thanks for your first PR to Astro docs. @magnum-zx 
I pointed out some need to fix.

2023-04-13 06:21 UTC, magnum-zx commented
@liruifengv This is my first PR to Astro docs, thanks for your review!
do I need to resubmit the PR after fix?

2023-04-13 06:32 UTC, liruifengv commented
> @liruifengv This is my first PR to Astro docs, thanks for your review! do I need to resubmit the PR after fix?↳

You can continue to commit to this PR.

2023-04-13 07:33 UTC, liruifengv commented
To make review easier, we recommend creating multiple PRs if there are no broken links between pages each other.

`environment-variables.mdx` seems to have some other outdated content. I suggested you create a new PR to update it.

2023-04-13 11:32 UTC, liruifengv commented on src/content/docs/zh-cn/reference/errors/get-static-paths-required.mdx
> +在[静态模式](/en/core-concepts/routing/#static-ssg-mode)下，所有路由都必须在构建时确定。因此，动态路由必须`export`一个 `getStaticPaths` 函数，来返回将要生成的不同路径。
The link should be `zh-cn`. I don't know why check-link ci not working.

Maybe you need to update the `routing` page.

2023-04-18 01:19 UTC, magnum-zx commented
That is OK@Yan-Thomas,I was doing other work before, and I will continue Update of the Routing page today.

2023-04-18 11:15 UTC, Yan-Thomas commented
That was fast, thanks @magnum-zx! Could I please ask for another review @liruifengv? Thanks in advance 🙌

2023-04-18 12:36 UTC, liruifengv commented
> 

I'm coming.

2023-04-18 13:01 UTC, liruifengv commented on src/content/docs/zh-cn/core-concepts/routing.mdx
> +如果你的URL路由需要更加灵活，你可以在 `.astro` 文件名中使用一个剩余参数（`[...path]`），去匹配任何深度的文件路径。
There is a missing link here.

2023-04-18 13:06 UTC, liruifengv commented on src/content/docs/zh-cn/core-concepts/routing.mdx
>  ```astro
This code snippet is missing highlighting.

2023-04-18 13:08 UTC, liruifengv commented on src/content/docs/zh-cn/core-concepts/routing.mdx
>  例如，如果你想通过一些标签来分组你的分页的 Markdown 帖子，你可以通过创建一个 `/src/pages/[tag]/[page].astro` 的页面来使用嵌套分页，该页面将匹配以下链接。
```suggestion

例如，如果你想通过一些标签来分组你的分页的 Markdown 帖子，你可以通过创建一个 `/src/pages/[tag]/[page].astro` 的页面来使用嵌套分页，该页面将匹配以下链接。
```

2023-04-18 13:10 UTC, liruifengv commented on src/content/docs/zh-cn/core-concepts/routing.mdx
> +Astro 使用标准 HTML [`<a>` 元素](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) 在路由之间导航。 没有提供特定框架的 `<Link>` 组件。
```suggestion
Astro 使用标准 HTML [`<a>` 元素](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/a) 在路由之间导航。 没有提供特定框架的 `<Link>` 组件。
```

2023-04-18 14:20 UTC, liruifengv approved these changes
LGTM!

2023-04-18 22:18 UTC, merged