I18n(ko): Translate 'manual.mdx' and 'editor-setup.mdx'
withastro/docs pull request #3055
Opened 2023-04-16 07:03 UTC by sujang958

#### What kind of changes does this PR include?

- Translated content

#### Description

- Translated `manual.mdx`
- Translated `editor-setup.mdx`

2023-04-16 09:54 UTC, filename24 requested changes

2023-04-16 09:54 UTC, filename24 commented on src/content/docs/ko/editor-setup.mdx
> +## 브라우저 안 에디터
```suggestion
## 웹 에디터
```

이게 더 직관적이고 읽을떼 편한거같습니다.

2023-04-16 09:54 UTC, filename24 commented on src/content/docs/ko/guides/upgrade-to/v2.mdx
> + astro.config.mjs`에서 `site`에 설정된 URL에 후행 슬래시를 추가합니다.
여기 코드블럭 오류가 있네요.

2023-04-16 09:54 UTC, sujang958 commented on src/content/docs/ko/editor-setup.mdx
> +## 브라우저 안 에디터
그런 것 같네요, 수정하겠습니다!

2023-04-16 09:55 UTC, sujang958 commented on src/content/docs/ko/guides/upgrade-to/v2.mdx
> + astro.config.mjs`에서 `site`에 설정된 URL에 후행 슬래시를 추가합니다.
수정하겠습니다!

2023-04-16 09:56 UTC, filename24 approved these changes

2023-04-16 12:11 UTC, imjlk commented on src/content/docs/ko/guides/upgrade-to/v2.mdx
> +문제가 생기면 [공식 Vite 마이그레이션 가이드](https://vitejs.dev/guide/migration.html)을 참조하세요
```suggestion
문제가 생기면 [공식 Vite 마이그레이션 가이드](https://vitejs.dev/guide/migration.html)를 참조하세요
```

2023-04-16 12:11 UTC, imjlk commented on src/content/docs/ko/guides/upgrade-to/v2.mdx
> +마크다운 파일을 가져오기 위해 [`Astro.glob()`](/ko/guides/imports/#astroglob) 을 사용하거나 [Content Collections](/ko/guides/content-collections/) 기능으로 바꾸세요.
```suggestion
마크다운 파일을 가져오기 위해 [`Astro.glob()`](/ko/guides/imports/#astroglob)을 사용하거나 [Content Collections](/ko/guides/content-collections/) 기능으로 바꾸세요.
```

2023-04-16 12:11 UTC, imjlk commented on src/content/docs/ko/install/manual.mdx
> +Astro 프로젝트를 자동으로 생성하는 'create astro' CLI 도구를 사용하지 않으려면 아래 가이드에 따라 프로젝트를 직접 설정할 수 있습니다.
```suggestion
Astro 프로젝트를 자동으로 생성하는 `create astro` CLI 도구를 사용하지 않으려면 아래 가이드에 따라 프로젝트를 직접 설정할 수 있습니다.
```

2023-04-16 13:49 UTC, sujang958 commented
자세한 리뷰 감사합니다!

2023-04-16 15:10 UTC, imjlk requested changes
띄어쓰기 부분 몇 군데만 더 추가했습니다!

2023-04-17 10:45 UTC, imjlk approved these changes

2023-04-17 18:29 UTC, Yan-Thomas commented on src/content/docs/ko/guides/upgrade-to/v2.mdx
> +만약 v1.x에서 이 기능을 사용 중이라면 컴포넌트와 JSX 표현식을 마크다운 구문과 결합할 수 있는 [MDX 통합](/ko/guides/통합-가이드/mdx/)을 사용하는 것이 좋습니다.
```suggestion
만약 v1.x에서 이 기능을 사용 중이라면 컴포넌트와 JSX 표현식을 마크다운 구문과 결합할 수 있는 [MDX 통합](/ko/guides/integrations-guide/mdx/)을 사용하는 것이 좋습니다.
```

2023-04-17 18:30 UTC, Yan-Thomas commented on src/content/docs/ko/install/manual.mdx
> +이 가이드를 완전히 따랐다면 [2단계: Astro 시작하기](/ko/install/auto/#2-start-astro-)로 바로 이동하여 Astro를 처음 실행하는 방법을 계속 학습할 수 있습니다.
```suggestion
이 가이드를 완전히 따랐다면 [2단계: Astro 시작하기](/ko/install/auto/#2-astro-시작하기-)로 바로 이동하여 Astro를 처음 실행하는 방법을 계속 학습할 수 있습니다.
```

2023-04-17 18:32 UTC, Yan-Thomas approved these changes
LGTM! Thanks @sujang958 for the PR, also thanks @filename24 and @imjlk for the careful review. I went ahead and fixed the couple broken links in the page, so then we're good to merge! 🥳

2023-04-17 18:39 UTC, merged