i18n(es): Translated `from-sveltekit.mdx`
withastro/docs pull request #3116
Opened 2023-04-29 16:15 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `from-sveltekit.mdx` to spanish

2023-04-30 01:43 UTC, dreyfus92 requested changes
Gracias por la PR @Waxer59 , te dejo una sugerencia.

2023-04-30 01:43 UTC, dreyfus92 commented on src/content/docs/es/guides/migrate-to-astro/from-sveltekit.mdx
> +- ¡Añade el tuyo propio!
```suggestion
- ¡Añade el tuyo!
```

2023-04-30 02:14 UTC, Waxer59 commented
Gracias por la revisión @dreyfus92

2023-05-01 19:13 UTC, Yan-Thomas approved these changes
LGTM! Thanks @Waxer59 & @dreyfus92 🙌

2023-05-01 19:13 UTC, merged