i18n(es): Translated `from-nextjs.mdx` *(in progress)*
withastro/docs pull request #3124
Opened 2023-04-30 04:00 UTC by Waxer59

> Warning: this PR is in process and not yet finished, that's why it is marked as draft, any revision please do it when it is marked as ready for review.

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `from-nextjs.mdx` to spanish

2023-05-04 06:06 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo algunas sugerencias 😄

2023-05-04 06:06 UTC, dreyfus92 commented on src/content/docs/es/guides/migrate-to-astro/from-nextjs.mdx
> +Como Astro produce HTML sin procesar, es posible escribir tests end-to-end utilizando la salida del paso de compilación. Cualquier test end-to-end escrito anteriormente  podría funcionar sin problema
```suggestion
Como Astro produce HTML sin procesar, es posible escribir tests end-to-end utilizando la salida del paso de compilación. Cualquier test end-to-end escrito anteriormente podría funcionar sin problemas si has podido coincidir con el marcado de tu sitio de Next. Bibliotecas de testing como Jest y React Testing Library pueden ser importadas y utilizadas en Astro para poner a prueba tus componentes de React.
```

2023-05-04 06:06 UTC, dreyfus92 commented on src/content/docs/es/guides/migrate-to-astro/from-nextjs.mdx
> +Alternativamente, puedes usar [colecciones de contenido](/es/guides/content-collections/) en Astro para almacenar y administrar tu contenido. Cuando forman parte de una colección, los archivos Markdo
```suggestion
Alternativamente, puedes usar [colecciones de contenido](/es/guides/content-collections/) en Astro para almacenar y administrar tu contenido. Cuando forman parte de una colección, los archivos Markdown y MDX vivirán en carpetas dentro de `src/content/`. Deberás recuperar el contenido tú mismo y [generar esas páginas dinámicamente](/es/guides/content-collections/#generating-routes-from-content).
```

2023-05-04 06:06 UTC, dreyfus92 commented on src/content/docs/es/guides/migrate-to-astro/from-nextjs.mdx
> +Cada página de Astro requiere explícitamente que se incluyan las etiquetas `<html>`, `<head>`, y `<body>`, por lo que es comñun reutilizar un archivo de diseño en varias páginas. Astro utiliza [`<slo
```suggestion
Cada página de Astro requiere explícitamente que se incluyan las etiquetas `<html>`, `<head>`, y `<body>`, por lo que es común reutilizar un archivo de diseño en varias páginas. Astro utiliza [`<slot />`](/es/core-concepts/astro-components/#slots) para el contenido de la página, sin necesidad de importar ninguna declaración. Observa la estructura estándar de templating de HTML y el acceso directo al elemento `<head>`:  
```

2023-05-05 00:42 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-05-08 16:59 UTC, Yan-Thomas approved these changes
LGTM! Thanks @Waxer59 & @dreyfus92 🙌

2023-05-08 16:59 UTC, merged