i18n(es): Translated `mdx.mdx`
withastro/docs pull request #3131
Opened 2023-05-01 04:35 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `mdx.mdx` to spanish

2023-05-01 05:12 UTC, Waxer59 commented
I have fixed a file that had broken links pointing to this page.

2023-05-12 01:17 UTC, dreyfus92 requested changes
Te dejo una sugerencia @Waxer59, buen trabajo 😁

2023-05-12 01:17 UTC, dreyfus92 commented on src/content/docs/es/core-concepts/astro-pages.mdx
> +Astro trata archivos Markdown (`.md`) dentro de `src/pages/` como páginas en tu proyecto. Si tienes la [integración de MDX instalada](/es/guides/integrations-guide/mdx/#instalación), también procesa
```suggestion
Astro trata los archivos Markdown (`.md`) dentro de `src/pages/` como páginas en tu proyecto. Si tienes la [integración de MDX instalada](/es/guides/integrations-guide/mdx/#instalación), también procesa los archivos MDX (`.mdx`) de la misma manera. Estos se usan comúnmente para páginas con mucho texto, como artículos de blog y documentación.
```

2023-05-12 01:35 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-05-12 20:21 UTC, Yan-Thomas approved these changes
LGTM! Nice job peeps, 💜

2023-05-12 20:21 UTC, merged