i18n(zh-cn): Translated `tailwind.mdx`
withastro/docs pull request #3140
Opened 2023-05-02 08:19 UTC by vuecat

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

Translated `tailwind.mdx`.

2023-05-17 07:11 UTC, liruifengv requested changes
@vuecat Thanks! Long wait. I translated some untranslated changes. Other LGTM!

2023-05-17 07:11 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/tailwind.mdx
> +    // Example: Provide a custom path to a Tailwind config file
```suggestion
    // 示例：为 Tailwind 配置文件提供一个自定义路径
```

2023-05-17 07:11 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/tailwind.mdx
> +    // Example: Disable injecting a basic `base.css` import on every page.
```suggestion
    // 示例：在每个页面上禁用注入基本的`base.css`导入。
```

2023-05-17 07:11 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/tailwind.mdx
> +    // Useful if you need to define and/or import your own custom `base.css`.
```suggestion
    // 如果你需要定义或导入你自己的 "base.css"，这很有用。
```

2023-05-19 19:37 UTC, Yan-Thomas approved these changes
Looks great, thanks @vuecat & @liruifengv 🙌

2023-05-19 19:37 UTC, merged