i18n(ko): Translated `project-structure.mdx`
withastro/docs pull request #3197
Opened 2023-05-07 08:52 UTC by minjongbaek

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- Translated `project-structure.mdx` to korean

2023-05-07 13:29 UTC, WooDaeHyun reviewed
너무 고생 많으셨어요~ 이렇게 번역하는게 쉬운일이 아닌데 너무 멋있습니다.👍

번역된 부분을 읽으면서 들었던 생각인데 원문에 'files'로 된 부분들이 대부분 그냥 '파일'로 번역이 되어있는 것 같았습니다. 엄밀하게 하자면 파일들로 번역하는게 맞다고 생각하지만 또 무언가 어색한 감이 없지 않아 있는 것 같더라구요! 그래서 제안드리자면 그냥 files로 나둬도 괜찮지 않을까 생각이 들기도 했습니다! 제 개인적인 생각이니 참고 정도만 해주시면 될 것 같아요~ 👍

2023-05-07 13:29 UTC, WooDaeHyun commented on src/content/docs/ko/core-concepts/project-structure.mdx
> +- `src/*` - 프로젝트 소스 코드 (컴포넌트, 페이지, 스타일 등)
✨ 프로젝트 소스 코드 (컴포넌트, 페이지, 스타일 등)

 를 원문 그대로 번역해서

📝 당신의 프로젝트 소스 코드 (컴포넌트, 페이지, 스타일 등)

 로 번역 해주는게 명시적으로 더 좋지 않을까요?

2023-05-07 13:29 UTC, WooDaeHyun commented on src/content/docs/ko/core-concepts/project-structure.mdx
> +- `public/*` - 소스 코드가 아니거나 처리할 필요가 없는 에셋 파일들 (폰트, 아이콘 등)
✨ 소스 코드가 아니거나 처리할 필요가 없는 에셋 파일들 (폰트, 아이콘 등) 

를

📝 소스 코드가 아니거나 처리되지 않은 에셋 파일들 (폰트, 아이콘 등)

로 번역 해주는게 더 올바른 의미인 것 같아요!

2023-05-07 13:29 UTC, WooDaeHyun commented on src/content/docs/ko/core-concepts/project-structure.mdx
> +이는 Astro 프로젝트에서 흔히 볼 수 있는 관례이지만 꼭 필요한 것은 아닙니다. 원하는 대로 컴포넌트를 구성하세요!
✨ 이는 Astro 프로젝트에서 흔히 볼 수 있는 관례이지만 꼭 필요한 것은 아닙니다. 원하는 대로 컴포넌트를 구성하세요!

이 부분은 독자를 생각해서 꼭 번역해주지 않아도 좋을 것 같아요!

📝 이것은 Astro 프로젝트에서 흔히 사용되는 컨벤션이지만, 꼭 지켜야 하는 것은 아닙니다. 원하는 대로 컴포넌트를 구성하세요!

라고 번역하면 조금 더 와 닿지 않을까 싶어요!

2023-05-07 13:29 UTC, WooDaeHyun commented on src/content/docs/ko/core-concepts/project-structure.mdx
> +[Pages](/ko/core-concepts/astro-pages/)는 사이트에 새로운 페이지를 만드는 데 사용되는 특별한 종류의 컴포넌트입니다. 페이지는 Astro 컴포넌트 또는 사이트 콘텐츠를 나타내는 마크다운 파일이 될 수 있습니다.
✨ 페이지는 Astro 컴포넌트 또는 사이트 콘텐츠를 나타내는 마크다운 파일이 될 수 있습니다. 

이 부분은 읽을 때 독자 입장에서 이해하기 힘들 수도 있을 것 같아요!

📝 컴포넌트, 사이트 컨텐츠를 나타내는 마크다운 등이 페이지가 될 수 있습니다.

로 문장 구성을 조금 변경해주면 조금 더 읽기 편할 것 같아요~

2023-05-07 13:29 UTC, WooDaeHyun commented on src/content/docs/ko/core-concepts/project-structure.mdx
> +CSS 또는 Sass 파일을 `src/styles` 디렉터리에 저장하는 것이 일반적인 관례이지만 반드시 그럴 필요는 없습니다. 스타일이 `src/` 디렉터리의 어딘가에 있고 올바르게 가져온 것이라면 Astro는 스타일을 처리하고 최적화합니다.
✨ CSS 또는 Sass 파일을 `src/styles` 디렉터리에 저장하는 것이 일반적인 관례이지만 반드시 그럴 필요는 없습니다. 스타일이 `src/` 디렉터리의 어딘가에 있고 올바르게 가져온 것이라면 Astro는 스타일을 처리하고 최적화합니다. 

이 부분도 독자를 위해서 전부 번역해줄 필요는 없어보입니다.

📝 CSS 또는 Sass 파일을 `src/styles` 디렉터리에 저장하는 것이 흔히 사용되는 컨벤션이지만 반드시 그럴 필요는 없습니다. 스타일이 `src/` 디렉터리의 어딘가에 있고 올바르게 임포트 했다면 Astro는 스타일을 처리하고 최적화합니다.
 
로 번역해 주어도 전혀 이해하기 어렵지 않을 것 같습니다!

2023-05-07 13:38 UTC, WooDaeHyun commented on src/content/docs/ko/core-concepts/project-structure.mdx
> +- `src/*` - 프로젝트 소스 코드 (컴포넌트, 페이지, 스타일 등)
```suggestion
- `src/*` - 당신의 프로젝트 소스 코드 (컴포넌트, 페이지, 스타일 등)
```

2023-05-09 02:18 UTC, WooDaeHyun requested changes
너무 고생 많으셨어요~일부 추가 수정하면 좋을 것 같은 부분 다시 올려봅니다~

2023-05-09 02:26 UTC, minjongbaek commented on src/content/docs/ko/core-concepts/project-structure.mdx
> +CSS 또는 Sass 파일을 `src/styles` 디렉터리에 저장하는 것이 일반적인 관례이지만 반드시 그럴 필요는 없습니다. 스타일이 `src/` 디렉터리의 어딘가에 있고 올바르게 가져온 것이라면 Astro는 스타일을 처리하고 최적화합니다.
좋은 의견 감사합니다!
다만, import를 임포트로 번역하는게 괜찮은지 모르겠습니다. '임포트'로 번역된 다른 문서를 접하지 못해서 그럴 수도 있겠네요.

[MDN - import](https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Statements/import) 에서는 import를 '가져온, 가져오기' 등으로 번역하는 것 같습니다.

2023-05-09 02:36 UTC, WooDaeHyun commented on src/content/docs/ko/core-concepts/project-structure.mdx
> +CSS 또는 Sass 파일을 `src/styles` 디렉터리에 저장하는 것이 일반적인 관례이지만 반드시 그럴 필요는 없습니다. 스타일이 `src/` 디렉터리의 어딘가에 있고 올바르게 가져온 것이라면 Astro는 스타일을 처리하고 최적화합니다.
네 이해했습니다. 제가 그 부분까지 알지 못했는데 말씀해주셔서 감사합니다! ☺️ 저도 많이 배웠습니다. 
```suggestion
CSS 또는 Sass 파일을 `src/styles` 디렉터리에 저장하는 것이 흔히 사용되는 컨벤션이지만 반드시 그럴 필요는 없습니다. 스타일이 `src/` 디렉터리의 어딘가에 있고 올바르게 가져온 것이라면 Astro는 스타일을 처리하고 최적화합니다.
```
 import 부분은 처음 번역해 주신 것 그대로 반영해서 다시 수정해 보았습니다. 참고 부탁드려요! 🤗

2023-05-09 02:39 UTC, WooDaeHyun reviewed
i think this page was translated perfectly thanks to minjongbaek! 👍

2023-05-09 08:07 UTC, merged

2023-05-09 08:08 UTC, delucis commented
Thank for the translation @minjongbaek and for reviewing @WooDaeHyun! 💜