i18n(es): Translated `middleware-no-data-or-next-called.mdx`
withastro/docs pull request #3209
Opened 2023-05-08 21:38 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `middleware-no-data-or-next-called.mdx` to spanish

2023-05-09 03:58 UTC, dreyfus92 requested changes
Buen trabajo, te dejo una sugerencia @Waxer59 😁

2023-05-09 03:58 UTC, dreyfus92 commented on src/content/docs/es/reference/errors/middleware-no-data-or-next-called.mdx
> +	// doesn't return anything or call `next`
```suggestion
	// no regresa nada o llama `next
```

2023-05-09 18:31 UTC, Waxer59 commented
Gracias por la revision 🤠

2023-05-11 17:06 UTC, Yan-Thomas approved these changes
LGTM! Thanks for the awesome work @Waxer59 & @dreyfus92 💜

2023-05-11 17:06 UTC, merged