i18n(es): Translated `lit.mdx`
withastro/docs pull request #3275
Opened 2023-05-18 09:14 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `lit.mdx` to spanish

2023-05-18 14:40 UTC, dreyfus92 requested changes
Te dejo unos comentarios @Waxer59, muchas gracias por la PR 😄

2023-05-18 14:40 UTC, dreyfus92 commented on src/content/docs/es/guides/integrations-guide/lit.mdx
> +Hydration is also handled automatically. You can use the same hydration directives such as `client:load`, `client:idle` and `client:visible` as you can with other libraries that Astro supports.
Faltó traducir.

2023-05-18 14:40 UTC, dreyfus92 commented on src/content/docs/es/guides/integrations-guide/lit.mdx
> +The above will only load the element's JavaScript when the user has scrolled it into view. Since it is server rendered they will not see any jank; it will load and hydrate transparently.
Faltó traducir.

2023-05-20 20:44 UTC, kevinzunigacuellar reviewed
gracias por la PR, te dejo algunos comentarios!

2023-05-20 20:44 UTC, kevinzunigacuellar commented on src/content/docs/es/guides/integrations-guide/lit.mdx
> +Esta **[integración de Astro][astro-integration]** permite renderización en el servidor y hidratación en el cliente para tus elementos personalizados de [Lit](https://lit.dev/).
```suggestion
Esta **[integración de Astro][astro-integration]** permite renderización en el servidor e hidratación en el cliente para tus elementos personalizados de [Lit](https://lit.dev/).
```

2023-05-20 20:44 UTC, kevinzunigacuellar commented on src/content/docs/es/guides/integrations-guide/lit.mdx
> +Astro incluye una herramienta CLI para agregar integraciones de primera parte: `astro add`. Este comando hará:
```suggestion
Astro incluye una herramienta CLI para agregar integraciones: `astro add`. Este comando hará:
```

2023-05-20 20:44 UTC, kevinzunigacuellar commented on src/content/docs/es/guides/integrations-guide/lit.mdx
> +1.  (Opcionalmente) Instalar todas las dependencias necesarias y dependencias entre pares
```suggestion
1.  (Opcionalmente) Instalar todas las dependencias necesarias y dependencias pares asociadas
```

2023-05-20 20:44 UTC, kevinzunigacuellar commented on src/content/docs/es/guides/integrations-guide/lit.mdx
> +La mayoría de los gestores de paquetes también instalarán las dependencias de pares asociadas. Sin embargo, si ves una advertencia de "No se puede encontrar el paquete 'lit'" (o similar)cuando inicia
```suggestion
La mayoría de los gestores de paquetes también instalarán las dependencias de pares asociadas. Sin embargo, si ves una advertencia de "No se puede encontrar el paquete 'lit'" (o similar) cuando inicias Astro, necesitarás instalar `lit` y `@webcomponents/template-shadowroot` de la siguiente manera:
```

2023-05-20 20:52 UTC, Waxer59 commented
Gracias por la revisión 🚀

2023-05-21 17:05 UTC, merged

2023-05-21 17:06 UTC, kevinzunigacuellar commented
Thanks @Waxer59, @dreyfus92 and @Yan-Thomas