i18n(es): Translated `image.mdx (in progress)`
withastro/docs pull request #3276
Opened 2023-05-18 09:19 UTC by Waxer59

>IMPORTANT! this Pr is in translation process, once translated it will be ready for review.

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `image.mdx` to spanish

2023-05-20 04:58 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo algunas sugerencias 😄

2023-05-20 04:58 UTC, dreyfus92 commented on src/content/docs/es/guides/integrations-guide/image.mdx
> +El color de fondo a utilizar para reemplazar el canal alfa con el método `flatten` de `sharp`.En caso de que el formato de salida no admita transparencia (p. ej. `jpeg`), se recomienda incluir un col
```suggestion
El color de fondo a utilizar para reemplazar el canal alfa con el método `flatten` de `sharp`. En caso de que el formato de salida no admita transparencia (p. ej. `jpeg`), se recomienda incluir un color de fondo; de lo contrario, se utilizará el negro como reemplazo predeterminado para los píxeles transparentes.
```

2023-05-20 04:58 UTC, dreyfus92 commented on src/content/docs/es/guides/integrations-guide/image.mdx
> +Esta es la función auxiliar utilizada por el componente  `<Image />` para construir los atributos `<img />` para la imagen transformada. Esta función auxiliar se puede utilizar directamente para caso
```suggestion
Esta es la función auxiliar utilizada por el componente `<Image />` para construir los atributos `<img />` para la imagen transformada. Esta función auxiliar se puede utilizar directamente para casos de uso más complejos que no son compatibles actualmente con el componente `<Image />`.
```

2023-05-20 04:58 UTC, dreyfus92 commented on src/content/docs/es/guides/integrations-guide/image.mdx
> +ByDe forma predeterminada, las imágenes transformadas se almacenarán en caché en `./node_modules/.astro/image`. Esto se puede configurar en las opciones de configuración de la integración.
```suggestion
De forma predeterminada, las imágenes transformadas se almacenarán en caché en `./node_modules/.astro/image`. Esto se puede configurar en las opciones de configuración de la integración.
```

2023-05-20 04:58 UTC, dreyfus92 commented on src/content/docs/es/guides/integrations-guide/image.mdx
> +Para imágenes remotas, se requiere un `aspectRatio` para asegurar que se pueda calcular la `altura`  correcta en el momento de la construcción.
```suggestion
Para imágenes remotas, se requiere un `aspectRatio` para asegurar que se pueda calcular la `altura` correcta en el momento de la construcción.
```

2023-05-20 18:46 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-05-21 18:27 UTC, merged

2023-05-21 18:27 UTC, kevinzunigacuellar commented
gracias por todo @Waxer59 y @dreyfus92