i18n(es): Translate `sitemap.mdx`
withastro/docs pull request #3295
Opened 2023-05-18 20:00 UTC by Waxer59

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translate `sitemap.mdx` to spanish

2023-05-20 05:27 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo unas sugerencias 😄

2023-05-20 05:27 UTC, dreyfus92 commented on src/content/docs/es/guides/integrations-guide/sitemap.mdx
> +APor defecto, todas las páginas se incluyen en tu sitemap. Al agregar una función `filter` personalizada, puedes filtrar las páginas incluidas según su URL.
```suggestion
Por defecto, todas las páginas se incluyen en tu sitemap. Al agregar una función `filter` personalizada, puedes filtrar las páginas incluidas según su URL.
```

2023-05-20 05:27 UTC, dreyfus92 commented on src/content/docs/es/guides/integrations-guide/sitemap.mdx
> +La propiedad  `links`  contiene una lista de `LinkItem` que representa las páginas alternativas, incluida la página principal.
```suggestion
La propiedad `links` contiene una lista de `LinkItem` que representa las páginas alternativas, incluida la página principal.
```

2023-05-20 18:44 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-05-20 18:45 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-05-21 20:34 UTC, merged

2023-05-21 20:34 UTC, kevinzunigacuellar commented
gracias @Waxer59 y @dreyfus92