i18n(es): Translated `storyblok.mdx`
withastro/docs pull request #3303
Opened 2023-05-20 20:51 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `storyblok.mdx` to spanish

2023-05-21 07:55 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo unas sugerencias 😁

2023-05-21 07:55 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/storyblok.mdx
> +Para renderizar tu contenido, pasa la propiedad `content` del Story al componente `StoryblokComponent` como una prop `blok`.  Este componente renderizará los Bloks que están definidos dentro de la pr
```suggestion
Para renderizar tu contenido, pasa la propiedad `content` del Story al componente `StoryblokComponent` como una prop `blok`. Este componente renderizará los Bloks que están definidos dentro de la propiedad `content` property. En este caso, renderizará el componente `BlogPost`.
```

2023-05-21 07:55 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/storyblok.mdx
> +Para generar páginas para todas tus publicaciones de blog, crea una página  `.astro`  que creará rutas dinámicas. Este enfoque varía dependiendo de si estás utilizando la **generación de sitios estát
```suggestion
Para generar páginas para todas tus publicaciones de blog, crea una página `.astro` que creará rutas dinámicas. Este enfoque varía dependiendo de si estás utilizando la **generación de sitios estáticos** (la opción predeterminada) o **el renderizado en el lado del servidor**.
```

2023-05-21 07:55 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/storyblok.mdx
> +Crea un nuevo directorio  `src/pages/blog/` y agrega un nuevo archivo llamado `[...slug].astro` con el siguiente código:
```suggestion
Crea un nuevo directorio `src/pages/blog/` y agrega un nuevo archivo llamado `[...slug].astro` con el siguiente código:
```

2023-05-21 07:55 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/storyblok.mdx
> +3. Proporciona un nombre para tu webhook y la rama en la que deseas activar la compilación. Haz clic en **Add**  y copia la URL generada.
```suggestion
3. Proporciona un nombre para tu webhook y la rama en la que deseas activar la compilación. Haz clic en **Add** y copia la URL generada.
```

2023-05-21 10:11 UTC, Waxer59 commented
Gracias por la revisión 🚀

2023-05-23 22:57 UTC, Yan-Thomas approved these changes
LGTM! Nice work @Waxer59 & @dreyfus92 💜

2023-05-23 22:57 UTC, merged