i18n(es): Update `rss.mdx`
withastro/docs pull request #3338
Opened 2023-05-25 14:10 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Update translation `rss.mdx`

2023-05-25 16:10 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo una sugerencia 😁

2023-05-25 16:12 UTC, dreyfus92 commented on src/content/docs/es/guides/rss.mdx
> +Estiliza tu RSS feed para proveer una experiencia de usuario más placentera a la hora de ver el archivo en el navegador.
```suggestion
Puedes estilar tu RSS feed para proveer una experiencia de usuario más placentera a la hora de ver el archivo en el navegador.
```
Estilar es válido para referirse a estilo.

2023-05-25 16:18 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-06-01 21:36 UTC, Yan-Thomas approved these changes
LGTM! Nice work folks 🥳

2023-06-01 21:36 UTC, merged