i18n(es): update configuration-reference.mdx
withastro/docs pull request #3385
Opened 2023-05-30 20:35 UTC by Mardroide

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translation for the configuration-reference.mdx file, new content added and fixed some typos.
- Did you change something visual? A before/after screenshot can be helpful.
Just re-factor some line breaks to let the file be more visual.

2023-05-30 21:43 UTC, Waxer59 reviewed
¡Hola!, gracias por la PR 🚀, te dejo un par de sugerencias

2023-05-30 21:43 UTC, Waxer59 commented on src/content/docs/es/reference/configuration-reference.mdx
> +A continuación, añade `export const prerender = false` a cualquier página o punto final que desees excluir del pre-renderizado.
```suggestion
Luego añade `export const prerender = false` a cualquier página o endpoint que desees excluir del pre-renderizado.
```

2023-05-30 21:43 UTC, Waxer59 commented on src/content/docs/es/reference/configuration-reference.mdx
> +Establece el directorio para almacenar en caché los artefactos de construcción. Los archivos de este directorio se utilizarán en compilaciones posteriores para acelerar el tiempo de compilación.
```suggestion
Establece el directorio para almacenar en caché los artefactos de compilación. Los archivos de este directorio se utilizarán en compilaciones posteriores para acelerar el tiempo de compilación.
```

2023-05-30 21:43 UTC, Waxer59 commented on src/content/docs/es/reference/configuration-reference.mdx
> +Esta es una opción para minificar tu salida HTML y reducir el tamaño de tus archivos HTML. Cuando está activada, Astro elimina todos los espacios en blanco de tu HTML, incluidos los saltos de línea,
```suggestion
Esta es una opción para minificar tu salida HTML y reducir el tamaño de tus archivos HTML. Cuando está activada, Astro elimina todos los espacios en blanco de tu HTML, incluyendo los saltos de línea, en los componentes `.astro`. Esto ocurre tanto en el modo de desarrollo como en la compilación final.
```

2023-05-30 21:43 UTC, Waxer59 commented on src/content/docs/es/reference/configuration-reference.mdx
> +Utilizar `'class'` es útil cuando quieres asegurar que los selectores de elementos dentro de un componente de Astro anulan los valores predeterminados de estilo global (p. ej, de una hoja de estilos
```suggestion
Utilizar `'class'` es útil cuando quieres asegurar que los selectores de elementos dentro de un componente de Astro anulan los valores predeterminados de estilo global (p. ej. de una hoja de estilos global).
```

2023-05-30 21:43 UTC, Waxer59 commented on src/content/docs/es/reference/configuration-reference.mdx
> +- 'hybrid' - Construye un sitio estático con unas pocas páginas renderizadas en el lado del servidor.
```suggestion
- 'hybrid' - Construye un sitio estático con algunas páginas renderizadas en el lado del servidor.
```

2023-05-30 21:43 UTC, Waxer59 commented on src/content/docs/es/reference/configuration-reference.mdx
> + - `'auto'` - sólo las hojas de estilo de tamaño inferior a `ViteConfig.build.assetsInlineLimit` (default: 4kb) se alinean. De lo contrario, los estilos se envían en hojas de estilo externas.
```suggestion
 - `'auto'` - sólo las hojas de estilo más pequeñas que `ViteConfig.build.assetsInlineLimit` (por defecto: 4kb) se incrustan. De lo contrario, los estilos se envían en hojas de estilo externas.
```

2023-05-30 21:43 UTC, Waxer59 commented on src/content/docs/es/reference/configuration-reference.mdx
> + - `'always'` - todos los estilos se colocan dentro de las etiquetas `<style>`.
```suggestion
 - `'always'` - todos los estilos se incrustan en etiquetas `<style>`.
```

2023-05-30 21:43 UTC, Waxer59 commented on src/content/docs/es/reference/configuration-reference.mdx
> +Para activar esta función, establece `experimental.middleware` en `true` en tu configuración Astro:
```suggestion
Para activar esta función, establece `experimental.middleware` en `true` en tu configuración de Astro:
```

2023-05-30 21:43 UTC, Waxer59 commented on src/content/docs/es/reference/configuration-reference.mdx
> +Habilitar soporte experimental para SSR híbrido con pre-renderizado habilitado por defecto.
```suggestion
Habilita el soporte experimental para SSR híbrido con pre-renderizado habilitado por defecto.
```

2023-05-30 23:03 UTC, Waxer59 approved these changes
LGTM ✔️

2023-05-31 05:19 UTC, dreyfus92 requested changes
Gracias por la PR @Mardroide, excelente trabajo. Te dejo una sugerencia 😄

2023-05-31 05:19 UTC, dreyfus92 commented on src/content/docs/es/reference/configuration-reference.mdx
> +Controla si los estilos se envían al navegador en un archivo de css independiente o dentro de la etiqueta `<style>`. Elije entre las siguientes opciones:
```suggestion
Controla si los estilos se envían al navegador en un archivo de css independiente o dentro de la etiqueta `<style>`. Elige entre las siguientes opciones:
```

2023-06-01 18:33 UTC, Yan-Thomas commented on src/content/docs/es/reference/configuration-reference.mdx
> +Permite que las integraciones utilicen la [API experimental `addClientDirective`](/en/reference/integrations-reference/#addclientdirective-option) en el hook `astro:config:setup` para añadir directiv
```suggestion
Permite que las integraciones utilicen la [API experimental `addClientDirective`](/es/reference/integrations-reference/#addclientdirective-option) en el hook `astro:config:setup` para añadir directivas de cliente personalizadas en los archivos de Astro.
```

2023-06-01 18:42 UTC, Yan-Thomas commented
Hey @Mardroide, thanks for the PR! Heads up we can't merge this PR till we have the Integrations Reference page updated, would you (or anyone else here) be interested in making a PR updating it?

2023-06-01 18:52 UTC, Mardroide commented
> Hey @Mardroide, thanks for the PR! Heads up we can't merge this PR till we have the Integrations Reference page updated, would you (or anyone else here) be interested in making a PR updating it?

Hey, I'll do It by my self, thanks for asking. The issue with the link is that the feature is experimental and at spanish docs the reference doesn't exist.

2023-06-01 21:51 UTC, Waxer59 commented on src/content/docs/es/reference/directives-reference.mdx
> +Desde Astro 2.5.0, las integraciones también pueden añadir directivas de cliente personalizadas a través de la [API experimental `addClientDirective`](/es/reference/integrations-reference/#opción-add
```suggestion
Desde Astro 2.5.0, las integraciones también pueden añadir directivas de cliente personalizadas a través de la [API experimental `addClientDirective`](/es/reference/integrations-reference/#opción-addclientdirective). Puedes utilizar directivas personalizadas `client:*` para cambiar cómo y cuándo deben hidratarse los componentes.
```

2023-06-01 21:51 UTC, Waxer59 commented on src/content/docs/es/reference/integrations-reference.mdx
> +Añade una [directiva de cliente personalizada](/es/reference/directives-reference/#directivas-de-cliente-personalizadas) para utilizarla en los archivos Astro. Como se trata de una función experiment
```suggestion
Añade una [directiva de cliente personalizada](/es/reference/directives-reference/#directivas-de-cliente-personalizadas) para utilizarla en los archivos Astro. Como se trata de una característica experimental, también tienes que activar la opción de configuración [`experimental.customClientDirectives`](/en/reference/configuration-reference/#experimentalcustomclientdirectives) para utilizar esta API.
```

2023-06-01 21:51 UTC, Waxer59 commented on src/content/docs/es/reference/integrations-reference.mdx
> +Ten en cuenta que los puntos de entrada de la directiva sólo se empaquetan a través de esbuild y deben ser pequeños para que no ralenticen la hidratación de los componentes.
```suggestion
Ten en cuenta que los puntos de entrada de las directivas solo se incluyen en el paquete a través de esbuild y se deben mantener pequeños para no ralentizar la hidratación del componente.
```

2023-06-02 20:37 UTC, Yan-Thomas commented on src/content/docs/es/reference/integrations-reference.mdx
> +Añade una [directiva de cliente personalizada](/es/reference/directives-reference/#directivas-de-cliente-personalizadas) para utilizarla en los archivos Astro. Como se trata de una característica exp
```suggestion
Añade una [directiva de cliente personalizada](/es/reference/directives-reference/#directivas-de-cliente-personalizadas) para utilizarla en los archivos Astro. Como se trata de una característica experimental, también tienes que activar la opción de configuración [`experimental.customClientDirectives`](/es/reference/configuration-reference/#experimentalcustomclientdirectives) para utilizar esta API.
```

2023-06-02 20:45 UTC, Yan-Thomas approved these changes
LGTM! Thanks @Mardroide and everyone helping with reviews, let get this merged 🚀

2023-06-02 20:45 UTC, merged