i18n(ko): Translate `framework-components.mdx`
withastro/docs pull request #3388
Opened 2023-05-31 09:05 UTC by minjongbaek

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- Translated content

#### Description

- Translate `framework-components.mdx` to korean

2023-06-07 23:44 UTC, filename24 requested changes

2023-06-07 23:44 UTC, filename24 commented on src/content/docs/ko/core-concepts/astro-components.mdx
> +Astro 컴포넌트에 클라이언트 측 상호 작용이 필요한 경우에는 [standard HTML `<script>` tags](/ko/guides/client-side-scripts/)나 [UI 프레임워크 컴포넌트](/ko/core-concepts/framework-components/#인터랙티브-컴포넌트)를 추가할 수 있습니다. 자세한 내용은 링크에서 확인해
해당 내용을 굳이 번역해야하나 라는 의문이 듭니다.

2023-06-07 23:44 UTC, filename24 commented on src/content/docs/ko/core-concepts/framework-components.mdx
> +description: React, Svelte와 같은 다양한 프레임워크를 사용하는 방법에 대해 배웁니다.
번역기 쓴거같은 느낌이나서 수정이 필요해보여요

2023-06-08 13:18 UTC, minjongbaek commented on src/content/docs/ko/core-concepts/framework-components.mdx
> +description: React, Svelte와 같은 다양한 프레임워크를 사용하는 방법에 대해 배웁니다.
@filename24 이전 번역들을 참고하여 작성했습니다.

원문은 `Learn how to use React, Svelte, etc.` 인데 원문을 그대로 번역하는게 조금 더 자연스러울까요?

2023-06-08 13:20 UTC, minjongbaek commented on src/content/docs/ko/core-concepts/astro-components.mdx
> +Astro 컴포넌트에 클라이언트 측 상호 작용이 필요한 경우에는 [standard HTML `<script>` tags](/ko/guides/client-side-scripts/)나 [UI 프레임워크 컴포넌트](/ko/core-concepts/framework-components/#인터랙티브-컴포넌트)를 추가할 수 있습니다. 자세한 내용은 링크에서 확인해
번역을 하지 않아도 된다고 생각하시는 이유는 번역을 하지 않아도 해당 용어를 읽는데 무리가 없어서일까요? 아니면, 번역으로 인해 원문의 내용을 이해하는 것이 방해가 되서인가요?

번역 경험이 많지 않아 정말 궁금해서 질문 드려요.

2023-06-09 14:56 UTC, imjlk requested changes

2023-06-09 14:56 UTC, imjlk commented on src/i18n/ko/nav.ts
> +	'core-concepts/framework-components': 'UI 프레임워크',
```suggestion
	'core-concepts/framework-components': '프레임워크 컴포넌트',
```

일관된 용어(`프레임워크 컴포넌트`)로 내비게이션에 반영하는게 좋을 것 같습니다

2023-06-09 14:56 UTC, imjlk commented on src/content/docs/ko/core-concepts/framework-components.mdx
> +Astro 컴포넌트는 하이드레이션되는 프레임워크 컴포넌트를 포함하더라도 항상 정적 HTML로 렌더링 됩니다. 즉, Astro 컴포넌트에서 프레임워크 컴포넌트에 React의 'render props'를 전달하면, Astro 컴포넌트는 이 패턴이 요구하는 클라이언트 런타임 동작을 제공하지 못하기 때문에 작동하지 않습니다. 대신 명명된 슬롯을 사용합니다.
https://github.com/withastro/docs/pull/3388/files#diff-82821b2a3609cfa86c271080ea57d4c6f0ae96dea8547d23353bb55a2cc8d215R132

`이름을 가진 슬롯`과 `명명된 슬롯` 둘 중 하나로 통일하는게 좋을 것 같습니다.

2023-06-09 14:56 UTC, imjlk commented on src/content/docs/ko/core-concepts/framework-components.mdx
> +기본적으로 프레임워크 컴포넌트는 정적 HTML로 렌더링 됩니다. 이는 비대화형 컴포넌트를 템플릿화하는데 유용하며, 필요하지 않은 자바스크립트를 클라이언트에 전송하는 것을 방지합니다.
```
... only render on the server ... 
```

서버에서 렌더링 된다는 내용을 빼신 이유가 있을까요?

2023-06-09 14:56 UTC, imjlk commented on src/content/docs/ko/core-concepts/framework-components.mdx
> +## 인터랙티브 컴포넌트
```suggestion
## 인터랙티브 컴포넌트 하이드레이션하기
```

완전히 누락하기보다, 다른 헤딩 요소 처럼 ~하기로 반영하면 어떨까요

2023-06-09 15:14 UTC, imjlk commented on src/content/docs/ko/core-concepts/astro-components.mdx
> +Astro 컴포넌트에 클라이언트 측 상호 작용이 필요한 경우에는 [standard HTML `<script>` tags](/ko/guides/client-side-scripts/)나 [UI 프레임워크 컴포넌트](/ko/core-concepts/framework-components/#인터랙티브-컴포넌트)를 추가할 수 있습니다. 자세한 내용은 링크에서 확인해
https://github.com/withastro/docs/tree/main/src/i18n/ko#번역-팁 README 내용 중에 `아직 번역되지 않은 내부링크 문서가 있을 경우`를 제가 적었었는데요, 내부 링크의 경우 번역된 문서의 제목으로 반영되는게 적절하다고 생각해서 간단하게 번역 완료 후의 할 일에 대한 내용을 남겼었습니다. 일부 문서 내용 중에는 문서의 제목이 그대로 반영되면 어색한 경우가 있지만 이 문서에서는 적절한 것 같습니다.

2023-06-10 03:09 UTC, minjongbaek commented on src/content/docs/ko/core-concepts/framework-components.mdx
> +기본적으로 프레임워크 컴포넌트는 정적 HTML로 렌더링 됩니다. 이는 비대화형 컴포넌트를 템플릿화하는데 유용하며, 필요하지 않은 자바스크립트를 클라이언트에 전송하는 것을 방지합니다.
제 실수로 내용이 빠졌어요.
[411bb8d](https://github.com/withastro/docs/pull/3388/commits/411bb8d91d2374ee12a3bf9c0d5dd983793edd57) 커밋을 통해 내용을 추가해두었어요.

2023-06-10 23:18 UTC, filename24 commented on src/content/docs/ko/core-concepts/framework-components.mdx
> +description: React, Svelte와 같은 다양한 프레임워크를 사용하는 방법에 대해 배웁니다.
네 원본 그대로 번역하는게 좋을거 같습니다.

2023-06-11 02:10 UTC, minjongbaek commented on src/content/docs/ko/core-concepts/astro-components.mdx
> +Astro 컴포넌트에 클라이언트 측 상호 작용이 필요한 경우에는 [standard HTML `<script>` tags](/ko/guides/client-side-scripts/)나 [UI 프레임워크 컴포넌트](/ko/core-concepts/framework-components/#인터랙티브-컴포넌트)를 추가할 수 있습니다. 자세한 내용은 링크에서 확인해
앗 그렇군요.
그렇다면 `프레임워크 컴포넌트`로 번역된 다른 페이지들도 일관성 있게 `framework component`로 변경해주는 것이 바람직할까요?

2023-06-11 02:11 UTC, minjongbaek commented on src/content/docs/ko/core-concepts/astro-components.mdx
> +Astro 컴포넌트에 클라이언트 측 상호 작용이 필요한 경우에는 [standard HTML `<script>` tags](/ko/guides/client-side-scripts/)나 [UI 프레임워크 컴포넌트](/ko/core-concepts/framework-components/#인터랙티브-컴포넌트)를 추가할 수 있습니다. 자세한 내용은 링크에서 확인해
앗 그렇군요.
그렇다면 `프레임워크 컴포넌트`로 번역된 다른 페이지들도 일관성 있게 `framework components`로 변경해주는 것이 바람직할까요?

2023-06-11 07:59 UTC, minjongbaek commented on src/content/docs/ko/core-concepts/framework-components.mdx
> +description: React, Svelte와 같은 다양한 프레임워크를 사용하는 방법에 대해 배웁니다.
수정했습니다! [94a33cb](https://github.com/withastro/docs/pull/3388/commits/94a33cbbc7ab8f1e5c56aae41c023884ca855c30)

2023-06-11 09:44 UTC, imjlk approved these changes

2023-06-11 09:52 UTC, imjlk commented on src/content/docs/ko/core-concepts/astro-components.mdx
> +Astro 컴포넌트에 클라이언트 측 상호 작용이 필요한 경우에는 [standard HTML `<script>` tags](/ko/guides/client-side-scripts/)나 [UI 프레임워크 컴포넌트](/ko/core-concepts/framework-components/#인터랙티브-컴포넌트)를 추가할 수 있습니다. 자세한 내용은 링크에서 확인해
제 생각에는 지금 그대로 `UI 프레임워크 컴포넌트`로 반영되는게 좋은 것 같아요

저도 번역 기여 경험이 별로 없어서 혼동되는 부분이 많은데, 자유롭게 디스코드 채널이나 README파일 업데이트 해주시면서 의견 공유해주시면 좋을 것 같습니다!

2023-06-11 19:34 UTC, Yan-Thomas approved these changes
LGTM! Thanks for the great work @minjongbaek and @filename24 & @imjlk for the careful reviews 💜

2023-06-11 19:34 UTC, merged