i18n(zh): translate upgrade-to/v2.mdx
withastro/docs pull request #3460
Opened 2023-06-09 02:43 UTC by 4pmtong

#### What kind of changes does this PR include?

- Translated content

#### Description

Translate upgrade-to/v2.mdx to chinese

2023-06-24 15:47 UTC, luoingly requested changes
Thank you for your contributions to this project! 💜

Although I think there are several details that need to be modified in your translation, overall I think it is fine, except for the issues I have pointed out (suggested changes):

You should change all the `/en/` in the internal hyperlinks of the document to `/zh-cn/`, and you don't need to worry about whether the target page has been translated.

Additionally, if you could add spaces between Chinese and English, while removing unnecessary spaces between Chinese text (without affecting Markdown rendering), I think it would be better! 🚀

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +您可以通过 [新的 `build.assets` 配置项](/en/reference/configuration-reference/#buildassets) 来控制这个位置。
```suggestion
您可以通过 [新的 `build.assets` 配置项](/zh-cn/reference/configuration-reference/#buildassets) 来控制这个位置。
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +需要将旧项目升级到 v1 吗？请参阅我们的 [旧版本迁移指南](/en/guides/upgrade-to/v1/).
```suggestion
需要将旧项目升级到 v1 吗？请参阅我们的 [旧版本迁移指南](/zh-cn/guides/upgrade-to/v1/).
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +2. 查看您的 [部署环境](/en/guides/deploy/) 的文档，以确认它们是否支持 Node 16。
```suggestion
2. 查看您的 [部署环境](/zh-cn/guides/deploy/) 的文档，以确认它们是否支持 Node 16。
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +Astro v2.0 现在包含了用于将Markdown和MDX文件整理到 [内容集合](/en/guides/content-collections/) 中的Collections API。此API将`src/content/`设定为一个特殊的文件夹。
```suggestion
Astro v2.0 现在包含了用于将Markdown和MDX文件整理到 [内容集合](/zh-cn/guides/content-collections/) 中的Collections API。此API将`src/content/`设定为一个特殊的文件夹。
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +重命名现有的`src/content/`文件夹以避免冲突。 如果该文件夹存在，现在只能用于 [内容集合](/en/guides/content-collections/).
```suggestion
重命名现有的`src/content/`文件夹以避免冲突。 如果该文件夹存在，现在只能用于 [内容集合](/zh-cn/guides/content-collections/).
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +- **[`mdx.extendMarkdownConfig`](/en/guides/integrations-guide/mdx/#extendmarkdownconfig)** 继承全部或不继承你的 Markdown 配置
```suggestion
- **[`mdx.extendMarkdownConfig`](/zh-cn/guides/integrations-guide/mdx/#extendmarkdownconfig)** 继承全部或不继承你的 Markdown 配置
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +Astro v2.0 现在允许您在 MDX 集成配置中分别设置 [每一个可用的 Markdown 配置选项](/en/reference/configuration-reference/#markdown-options)（除了 `drafts`）。
```suggestion
Astro v2.0 现在允许您在 MDX 集成配置中分别设置 [每一个可用的 Markdown 配置选项](/zh-cn/reference/configuration-reference/#markdown-options)（除了 `drafts`）。
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +如果你正在使用 [`@astrojs/svelte` 集成](/en/guides/integrations-guide/svelte/)，Astro v2.0 需要在你的项目中有一个 `svelte.config.js` 文件。这是为了提供 IDE 的自动补全功能。
```suggestion
如果你正在使用 [`@astrojs/svelte` 集成](/zh-cn/guides/integrations-guide/svelte/)，Astro v2.0 需要在你的项目中有一个 `svelte.config.js` 文件。这是为了提供 IDE 的自动补全功能。
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +如果你在 v1.x 版本中使用了这个特性，我们推荐 [使用 MDX 集成](/en/guides/integrations-guide/mdx/)，它允许你将组件和 JSX 表达式与 Markdown 语法结合起来。
```suggestion
如果你在 v1.x 版本中使用了这个特性，我们推荐 [使用 MDX 集成](/zh-cn/guides/integrations-guide/mdx/)，它允许你将组件和 JSX 表达式与 Markdown 语法结合起来。
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +使用 [`Astro.glob()`](/en/guides/imports/#astroglob) 方法获取 Markdown 文件，或者转换为 [内容集合](/en/guides/content-collections/) 功能。
```suggestion
使用 [`Astro.glob()`](/zh-cn/guides/imports/#astroglob) 方法获取 Markdown 文件，或者转换为 [内容集合](/zh-cn/guides/content-collections/) 功能。
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +- [内容集合](/en/guides/content-collections/)，用于以类型安全的方式管理你的 Markdown 和 MDX 文件。
```suggestion
- [内容集合](/zh-cn/guides/content-collections/)，用于以类型安全的方式管理你的 Markdown 和 MDX 文件。
```

2023-06-24 15:47 UTC, luoingly commented on src/content/docs/zh-cn/guides/upgrade-to/v2.mdx
> +- 在使用 SSR 时，将个别页面[预渲染为静态 HTML](/en/guides/server-side-rendering/#configuring-individual-routes)，以提高速度和缓存能力。详见 配置个别路由。
```suggestion
- 在使用 SSR 时，将个别页面[预渲染为静态 HTML](/zh-cn/guides/server-side-rendering/#configuring-individual-routes)，以提高速度和缓存能力。详见 配置个别路由。
```

2023-07-10 20:34 UTC, Yan-Thomas commented
Thanks for this @4pmtong! Could you take a look at luoingly's suggestions and apply them if they make sense? I'd love to get this merged 🙌

2023-07-24 16:32 UTC, Yan-Thomas commented
I see this PR got stale, no worries! I'll be merging it in its current state with the suggestions applied. If you have any more suggestions for improvements, feel free to make another PR and I'll take a look into it! 🙌

2023-07-24 16:51 UTC, Yan-Thomas approved these changes
LGTM! Thanks @4pmtong and @luoingly for the careful review! 🙌

2023-07-24 16:53 UTC, merged

2023-07-25 02:36 UTC, 4pmtong commented
My apologies for the delay in responding as I was without internet access these past few days. I've just seen your message. Thanks @Yan-Thomas and @luoingly  for your review and suggestions!