i18n(es): Translated `strapi.mdx`
withastro/docs pull request #3468
Opened 2023-06-10 14:55 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `strapi.mdx`

2023-06-10 16:29 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo un par de sugerencias 😁

2023-06-10 16:29 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/strapi.mdx
> +  La llamada a la API solicita datos desde `http://localhost:1337/api/articles` y devuelve `articles`: un array de objetos JSON que representa tus datos:
```suggestion
  La llamada a la API solicita datos desde `http://localhost:1337/api/articles` y devuelve `articles`: un arreglo de objetos JSON que representa tus datos:
```

2023-06-10 16:29 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/strapi.mdx
> +3. Utilizando los datos del array `articles` devuelto por la API, muestra tus publicaciones de blog de Strapi en una lista. Estas publicaciones estarán vinculadas a sus propias páginas individuales,
```suggestion
3. Utilizando los datos del arreglo `articles` devuelto por la API, muestra tus publicaciones de blog de Strapi en una lista. Estas publicaciones estarán vinculadas a sus propias páginas individuales, las cuales crearás en el siguiente paso.
```

2023-06-10 16:29 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/strapi.mdx
> +## Official Resources
```suggestion
## Recursos oficiales
```

2023-06-12 17:36 UTC, Yan-Thomas approved these changes
LGTM! Thanks for the great work 🚀

2023-06-12 17:36 UTC, merged