Create 1.mdx
withastro/docs pull request #3512
Opened 2023-06-16 13:45 UTC by webdevKmer

#### What kind of changes does this PR include?

- Translated content

#### Description

- Closes # 
- What does this PR change? Give us a brief description.
A translation of the page from English to French.

2023-07-10 20:55 UTC, thomasbnt reviewed
Hello superbe merci ! 
Il manque pas mal d'accents sur le fichier, et revoir la ponctuation sur certaines phrases!

2023-07-10 20:55 UTC, thomasbnt commented on src/content/docs/fr/tutorial/0-introduction/1.mdx
> +Si vous avez des connaissances en **HTML**, **Markdown**, **CSS**, et si vous avez un peu de connaissances en **JavaScript**, alors vous etes prets a debuter! Vous pourrez etre en mesure de terminer
Hello! Il manque quelques accents comme pour "etes" "prets" "a" "debuter"

2023-07-10 20:55 UTC, thomasbnt commented on src/content/docs/fr/tutorial/0-introduction/1.mdx
> +A la fin de chaque page, vous trouverez une liste de cases a cocher, de taches que vous etes deja en mesure de faire. Cocher les cases correspondantes pour visualiser votre progres sur le trackeur du
Même issue d'orthographe "taches", "deja" "progres" et le point à la fin

2023-07-10 21:26 UTC, dreyfus92 requested changes
Salut! bon travail, je vous laisse quelques suggestions 😁

2023-07-10 21:26 UTC, dreyfus92 commented on src/content/docs/fr/tutorial/0-introduction/1.mdx
> +<summary>Ou juis-je laisser un feedback a propos de ce tutoriel?</summary>
```suggestion
<summary>Où puis-je laisser un feedback à propos de ce tutoriel ?</summary>
```

2023-07-10 21:26 UTC, dreyfus92 commented on src/content/docs/fr/tutorial/0-introduction/1.mdx
> +- [ ] Je suis pret a construire cala.!
```suggestion
- [ ] Je suis prêt à construire cela !
```

2023-07-10 21:26 UTC, dreyfus92 commented on src/content/docs/fr/tutorial/0-introduction/1.mdx
> +Entrer dans le canal de support forum et posez vos questions, dites `bonjour` et chattez sur le canal `#general` ou `#off-topic`.
```suggestion
Rejoignez dans le canal de support forum et posez vos questions, dites `bonjour` et chattez sur le canal `#general` ou `#off-topic`.
```

2023-07-17 11:28 UTC, webdevKmer commented on src/content/docs/fr/tutorial/0-introduction/1.mdx
> +Si vous avez des connaissances en **HTML**, **Markdown**, **CSS**, et si vous avez un peu de connaissances en **JavaScript**, alors vous etes prets a debuter! Vous pourrez etre en mesure de terminer
souci de clavier... Je corrige cela des que possible

2023-07-17 11:28 UTC, webdevKmer commented on src/content/docs/fr/tutorial/0-introduction/1.mdx
> +A la fin de chaque page, vous trouverez une liste de cases a cocher, de taches que vous etes deja en mesure de faire. Cocher les cases correspondantes pour visualiser votre progres sur le trackeur du
bien recu

2023-07-19 15:37 UTC, Yan-Thomas commented
Thanks @webdevKmer, I guess this looks good to go, I see @thomasbnt pointed out a few accentuation issues, were these addressed yet? If yes, I'l proceed with the merge.

2023-08-07 13:34 UTC, thomasbnt commented
Bonjour @webdevKmer, des nouvelles concernant ce PR? 🙌

2023-08-07 14:01 UTC, pioupia requested changes
Accent and French mistakes to correct.

2023-08-07 16:21 UTC, delucis commented on src/content/docs/fr/tutorial/0-introduction/1.mdx
> +Si vous [créez un nouveau projet Astro vide](/en/install/auto/) et êtes à l'aise avec votre setup, libre à vous de continuer directement au [Module 2](/en/tutorial/2-pages/) où vous commencerez à cré
Mistake in the link here:
```suggestion
Si vous [créez un nouveau projet Astro vide](/fr/install/auto/) et êtes à l'aise avec votre setup, libre à vous de continuer directement au [Module 2](/fr/tutorial/2-pages/) où vous commencerez à créer de nouvelles pages dans votre projet.
```

2023-08-07 16:46 UTC, merged