i18n(ar): Translate contribute page
withastro/docs pull request #3522
Opened 2023-06-17 19:32 UTC by ymhaah

In general, I am not sure of some of the words, so I collected the words that I am not sure of their accuracy:

- I was hesitant to translate the word documents to "وثائق" or "مستندات" And I decided to imitate React and go with "وثائق" and also with the "repository" l go with "مستودع"
- Literal translation of "pull request" Doesn't have a meaning so I went with "طلب الدمج"
- 'Governance doc' --> 'إدارة الوثائق' Source: https://www.almaany.com/ar/dict/ar-en/governance/
- Code of Conduct enforcement --> "قواعد السلوك العامة"  Source: https://blog.volkovlaw.com/2015/04/code-of-conduct-enforcement/ 
- compiler --> "مترجم" Source:  https://www.almaany.com/ar/dict/ar-en/compiler/

2023-07-02 15:36 UTC, wusaby-rush commented
what about this:

- first paragraph: 

نحن نرحب بالمساهمات من أي حجم والمساهمين من أي مستوى مهارة. و كمشروع مفتوح المصدر ، نحن نؤمن برد الجميل لمساهمينا. و يسعدنا تقديم المساعدة في التوجيهات بشأن طلبات الدمج PRs ,الكتابة الفنية, وتحويل أي فكرة ميزة إلى حقيقة.

نحن نرحب بالمساهمات من أي حجم والمساهمين بأي مهارة. و كمشروع مفتوح المصدر ، نحن نؤمن برد الجميل لمساهمينا. و يسعدنا تقديم  التوجيهات بشأن طلبات الدمج PRs ,الكتابة التقنية, وتحويل أي فكرة لميزة إلى حقيقة.

- I prefer `مخزن الكود الأساسي` not `مركز الكود الأساسي`
- in contribution guides

بالإضافة إلى المساهمة بالكود الخاص بك أو المحتوى, يمكنك ايضا تقديم مساهمة كبيرا لنا عن طريق تقديم مراجعة علي طلبات الدمج

بالإضافة إلى المساهمة بالكود أو المحتوى، يمكنك ايضا تقديم مساهمة فعّالة بمراجعة طلبات الدمج

other things LGTM

2023-07-10 20:29 UTC, Yan-Thomas commented
Thanks for the contribution @ymhaah, I see @wusaby-rush added a few suggestions for you, could you take a look and address them?

2023-07-16 16:01 UTC, pewpewded commented
السلام عليكم، الأسماء الأعجمية المعربة همزتها قطع.
 Astro = أسترو

2023-07-16 16:14 UTC, pewpewded commented
Also, regarding words such as "repository", "commit", etc., I don't think we should overthink their translations. In fact, we should just leave them as they are most of the time.

The whole idea behind a translation is to make it easier for speakers of that language. This is done by linking a word they know with a word they don't. However, this is not the case with GitHub, as the platform does not have an Arabic version or Arabic docs at all. We are all already exposed to these words, so trying to bridge a word that most people know with a word that most people don't, only for them to reuse it in its original form, is a waste of time for everyone 😅

2023-07-16 16:16 UTC, pewpewded commented
- مصطلع طلبات الدمج ممتاز ومفهوم، وما يخليك تقعد ربع ساعة تحاول تستوعب إيش معناه 👍🏻
- وثائق أيضًا أكثر مصطلح مناسب ورائج في الترجمات برضو
- إدارة الوثائق، "مستودع" يمشون الحال
- مترجم، قواعد السلوك العامة لا يوجد خيار أفضل منهم

2023-07-16 16:19 UTC, pewpewded commented
anyhow I noticed it's been a week, would you like me to fork and continue working on it?

2023-07-16 16:22 UTC, pewpewded requested changes
الأسماء الأعجمية المعربة همزتها قطع:

Astro = أسترو

2023-08-14 16:35 UTC, Yan-Thomas commented
I see this PR got stale, I am closing it so someone else will have the chance to work on it! Thanks for your contribution, we'd love to see you again when you have the time to contribute 🚀

2023-08-14 16:35 UTC, closed without merging