Add link to endpoint context in middleware documentation
withastro/docs pull request #3571
Opened 2023-06-23 20:32 UTC by sasoria

#### What kind of changes does this PR include?

- New or updated content

#### Description

- Closes #3523
- This Pull request makes it easier to find the context API in the Middleware documentation. This is useful for finding a simple way to redirect, among other things.

2023-06-23 20:43 UTC, dreyfus92 requested changes
I left you a suggestion, thanks for the PR @sasoria 😁

2023-06-23 20:44 UTC, dreyfus92 commented on src/content/docs/en/guides/middleware.mdx
> +This is the same [`context`](en/reference/api-reference/#endpoint-context) object that is passed to API routes.
```suggestion
This is the same [`context`](/en/reference/api-reference/#endpoint-context) object that is passed to API routes.
```

2023-06-23 20:48 UTC, sasoria commented on src/content/docs/en/guides/middleware.mdx
> +This is the same [`context`](en/reference/api-reference/#endpoint-context) object that is passed to API routes.
Thanks!

2023-06-23 21:33 UTC, dreyfus92 approved these changes
LGTM ✅

2023-06-26 20:31 UTC, ElianCodes requested changes
Just a small nit

2023-06-26 20:43 UTC, ElianCodes approved these changes

2023-06-26 20:53 UTC, ElianCodes commented
Thanks @sasoria ! Looks good now that `main` has been merged back into your PR!

Shipping it! ⛴️🚀

2023-06-26 20:54 UTC, merged