Fix titles link
withastro/docs pull request #3572
Opened 2023-06-23 21:24 UTC by Waxer59

#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

- What does this PR change? Give us a brief description.
Fixed the icon linking the page title to the URL.

2023-06-23 21:59 UTC, dreyfus92 approved these changes
LGTM ✅

2023-06-26 17:02 UTC, Yan-Thomas commented
I can see removing this CSS rule causes the viewport to work less in smaller viewports (I don't think it's a big problem considering most people aren't going to see the site in a 230px wide screen), but here's what's happening:

| Before | After|
|--------|--------|
|![image](https://github.com/withastro/docs/assets/61414485/45ba8015-b2a4-4975-8ed4-43f0333dc6cb)| ![image](https://github.com/withastro/docs/assets/61414485/decbb7d7-61cc-4f29-bf9e-5476fb260524) |

2023-06-27 05:28 UTC, Waxer59 commented
I have already added a mediaquery that solves this problem.

2023-06-27 10:46 UTC, Yan-Thomas approved these changes
Thanks, perfect!

2023-06-28 16:27 UTC, sarah11918 approved these changes
I am happy with the discussion I've seen here! This seems to have been a well-thought-out improvement, and I'm happy to approve subject to Yan or Chris being satisfied!  :purple_heart:

2023-06-30 10:53 UTC, delucis requested changes
In general we always use `min-width` media queries instead of `max-width`. Can we change this to keep `overflow-x: hidden` the default style and then disable it at `min-width: 50em` instead, please?

2023-06-30 11:01 UTC, Waxer59 commented
Changes made!

2023-06-30 11:05 UTC, Waxer59 commented on src/components/PageContent/PageContent.astro
> +
```suggestion
```

2023-06-30 12:38 UTC, delucis approved these changes
Thanks @Waxer59! Made a tweak to avoid using `!important` which is generally best avoid if it’s at all possible. Here we just needed to move the media query `.content` style below the `.content` without a media query. I took the opportunity to group up the different media queries too.

2023-06-30 12:55 UTC, Yan-Thomas approved these changes
LGTM!

2023-06-30 12:55 UTC, merged