i18n(es): Translated `reading-time.mdx`
withastro/docs pull request #3590
Opened 2023-06-27 08:34 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `reading-time.mdx`

2023-06-29 01:25 UTC, dreyfus92 requested changes
Te dejo una sugerencia @Waxer59, buen trabajo 😁

2023-06-29 01:25 UTC, dreyfus92 commented on src/content/docs/es/recipes/reading-time.mdx
> +      // readingTime.text  nos dará el tiempo de lectura en minutos como un string amigable,
```suggestion
      // readingTime.text nos dará el tiempo de lectura en minutos como un string legible,
```

2023-06-29 04:28 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-06-30 12:28 UTC, Yan-Thomas commented on src/content/docs/es/recipes/reading-time.mdx
> +## Recipe
Missing translation here!

2023-06-30 12:29 UTC, Waxer59 commented on src/content/docs/es/recipes/reading-time.mdx
> +## Recipe
```suggestion
## Receta
```

2023-06-30 18:17 UTC, Yan-Thomas approved these changes
LGTM!

2023-06-30 18:17 UTC, merged