i18n(es): Translated `captcha.mdx`
withastro/docs pull request #3592
Opened 2023-06-27 09:27 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `captcha.mdx`

2023-06-29 01:53 UTC, dreyfus92 requested changes
Te dejo unas sugerencias @Waxer59, buen trabajo 😁

2023-06-29 01:53 UTC, dreyfus92 commented on src/content/docs/es/recipes/captcha.mdx
> +description: Learn how to create an API route and fetch it from the client.
```suggestion
description: Aprende como crear una ruta de API y consultarla desde el cliente.
```

2023-06-29 01:53 UTC, dreyfus92 commented on src/content/docs/es/recipes/captcha.mdx
> +                // Captcha verification was a success
```suggestion
                // Verificación del Captcha fue un éxito
```

2023-06-29 01:53 UTC, dreyfus92 commented on src/content/docs/es/recipes/captcha.mdx
> +                // Captcha verification failed
```suggestion
                // Falló la verificación del Captcha
```

2023-06-29 04:29 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-06-30 12:11 UTC, Yan-Thomas approved these changes
LGTM!

2023-06-30 12:11 UTC, merged