i18n(zh-cn): translate tutorial
withastro/docs pull request #3597
Opened 2023-06-27 15:30 UTC by luoingly

#### What kind of changes does this PR include?

- Translated content

#### Description

- Chinese translation of the tutorial introduction
- The continuation of another PR: https://github.com/withastro/docs/pull/2704

考虑到原译者目前可能没有时间和精力去继续这项翻译工作，我直接接手了翻译进度并且完成了剩余部分的翻译。为了不打扰原译者，我选择来直接另开一个 PR。当然如果任何人对此有其他想法，可以直接提出来。

Considering that the original translator @KurumiFrost may currently lack the time and energy to continue with this translation work, I have taken over the translation progress directly and completed the remaining part of the translation. In order to not disturb the original translator, I have chosen to open a new PR directly. Of course, if anyone has other ideas about this, they can directly propose them.

我刚刚完成基本的翻译就来开这个 PR 了，尽管我也认为它需要进一步修改，所以刚开始一段时间我可能会把这个 PR 设置为草稿（Draft）。这么早开 PR 的一个原因，就是为了让更多的译者能来审阅并提出修改意见。当我觉得这个翻译已经很完善的时候，我大概就会删除这个草案标记。

I just completed the basic translation and came to open this PR, although I also believe that it needs further modifications, so I might set this PR as a draft for a while at the beginning. One reason for opening the PR this early is to allow more translators to review it and provide suggestions for modifications. When I feel that the translation is already quite refined, I will probably remove the draft mark.

**对于其他译者和贡献者：** 如果你有任何修改意见，可以直接在这个 PR 中提出，也可以修改并提交后去[我的仓库](https://github.com/luoingly/astro-docs/tree/patch-4)开一个 PR。

**For other translators and contributors:** If you have any suggestions for modifications, you can directly propose them in this PR or make modifications and submit a PR in [my repository](https://github.com/luoingly/astro-docs/tree/patch-4).

2023-07-25 02:28 UTC, liruifengv commented
Very large workload. I will help review this pr.

2023-07-25 13:51 UTC, liruifengv requested changes

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/1-setup/5.mdx
> +- <p>[在 Netlify 上进行部署的详细指南](https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on- netlify/) <Badge>外部链接</Badge></p>
```suggestion
- <p>[在 Netlify 上进行部署的详细指南](https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/) <Badge>外部链接</Badge></p>
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/index.mdx
> +- 使用 .astro 语法创建你的第一个 Astro 页面
```suggestion
- 使用 `.astro` 语法创建你的第一个 Astro 页面
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/index.mdx
> +- 应用跨页面应用全局样式
```suggestion
- 跨页面应用全局样式
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/1.mdx
> +2. 在同一文件夹中，创建一个名为`about.astro'的新文件。
```suggestion
2. 在同一文件夹中，创建一个名为`about.astro`的新文件。
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/2.mdx
> +## 创建你的第一个 .md 文件
```suggestion
## 创建你的第一个 `.md` 文件
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/2.mdx
> +    author: 'Astro 学者'
```suggestion
    author: 'Astro 学习者'
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/2.mdx
> +        url: 'https://astro.build/assets/blog/astro-1-release-update/cover.jpeg'
```suggestion
        url: 'https://docs.astro.build/assets/full-logo-light.png'
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/2.mdx
> +        alt: 'The Astro logo with the word One.'
```suggestion
        alt: 'The full Astro logo.'
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/2.mdx
> +        url: "https://astro.build/assets/blog/astro-showcase/astro-showcase-screenshot.jpg"
```suggestion
        url: "https://docs.astro.build/assets/arc.webp"
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/2.mdx
> +    ```md title="src/pages/posts/post-3.md"
The code snippet for `post-2` is missing here.

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/2.mdx
> +- [什么是浏览器开发者工具？- MDN](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_are_browser_developer_tools) <Badge>外部链接</Badge>
```suggestion
- [什么是浏览器开发者工具？- MDN](https://developer.mozilla.org/zh-CN/docs/Learn/Common_questions/What_are_browser_developer_tools) <Badge>外部链接</Badge>
```
MDN link can use zh-CN

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/3.mdx
> +3. 刷新你的 “关于” 页面的实时预览。
```suggestion
3. 刷新你的 `/about` 页面的实时预览。
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/4.mdx
> +Astro 的 `<style>` 标签还可以使用 `define:vars={{ {...} }}` 指令引用 `frontmatter` 中的任何变量。你可以**在代码栏中定义变量，然后在样式标签中将其用作CSS变量使用**。
```suggestion
Astro 的 `<style>` 标签还可以使用 `define:vars={ {...} }` 指令引用 `frontmatter` 中的任何变量。你可以**在代码围栏中定义变量，然后在样式标签中将其用作CSS变量使用**。
```

2023-07-25 13:51 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/2-pages/4.mdx
> +3. 在浏览器预览中查看 “关于” 页面。您应该看到技能现在是海军蓝色`navy`，由传递给 define:vars 指令的 skillColor 变量设置。
```suggestion
3. 在浏览器预览中查看 “关于” 页面。您应该看到技能现在是海军蓝色`navy`，由传递给 `define:vars` 指令的 `skillColor` 变量设置。
```

2023-07-25 13:53 UTC, liruifengv commented
I reviewed the first three units, I spotted a few small details.
Tomorrow I will continue.

2023-07-28 02:15 UTC, liruifengv reviewed
A little bit of advice. I've reviewed it in its entirety and it's a great tutorial in Chinese.

2023-07-28 02:15 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/5-astro-api/4.mdx
> +这个官方包会生成一个非 HTML 文档，其中包含有关你的所有博客文章的信息，可以被 Feedly、The Old Reader 等**订阅源阅读器（Feed Reader）**读取。每次重新构建你的网站时，该文档都会更新。
```suggestion
这个官方包会生成一个非 HTML 文档，其中包含有关你的所有博客文章的信息，可以被 Feedly、The Old Reader 等 **订阅源阅读器（Feed Reader）** 读取。每次重新构建你的网站时，该文档都会更新。
```
There is a rendering error here

2023-07-28 02:15 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/6-islands/1.mdx
> +      <Spoiler>`<PreactBanner client:load />` and `<SvelteCounter client:visible />` will be hydrated islands.</Spoiler>
Translation is missing here.

2023-08-04 01:13 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/5-astro-api/4.mdx
> +这个官方包会生成一个非 HTML 文档，其中包含有关你的所有博客文章的信息，可以被 Feedly、The Old Reader 等**订阅源阅读器（Feed Reader）**读取。每次重新构建你的网站时，该文档都会更新。
这里似乎还有问题没解决

2023-08-04 01:13 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/6-islands/1.mdx
> +      <Spoiler>`<PreactBanner client:load />` and `<SvelteCounter client:visible />` will be hydrated islands.</Spoiler>
这里也翻译一下吧

2023-08-07 02:22 UTC, liruifengv approved these changes
LGTM. Amazing work!

2023-08-07 18:27 UTC, Yan-Thomas approved these changes
LGTM! Thanks folks for this fantastic work, let's get this tutorial on the site! 🥳 🎉

2023-08-07 18:27 UTC, merged