i18n(es): Translated `bun.mdx`
withastro/docs pull request #3599
Opened 2023-06-27 18:25 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `bun.mdx`

2023-06-29 02:02 UTC, dreyfus92 requested changes
Te dejo algunas sugerencias @Waxer59, buen trabajo 😁

2023-06-29 02:02 UTC, dreyfus92 commented on src/content/docs/es/recipes/bun.mdx
> +Algunas integraciones pueden no funcionar como se espera. Si encuentras algún problema, por favor [abre un problema en GitHub](https://github.com/withastro/astro/issues/new/choose).
```suggestion
Algunas integraciones pueden no funcionar como se espera. Si encuentras algún problema, por favor [abre un issue en GitHub](https://github.com/withastro/astro/issues/new/choose).
```

2023-06-29 04:29 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-06-30 12:02 UTC, Yan-Thomas approved these changes
LGTM! Great work 🚀

2023-06-30 12:02 UTC, merged