i18n(es): Translated `leystone.mdx`
withastro/docs pull request #3602
Opened 2023-06-27 18:44 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `leystone.mdx`

2023-06-29 02:05 UTC, dreyfus92 requested changes
Te dejo unas sugerencias @Waxer59, buen trabajo ✅

2023-06-29 02:05 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/keystonejs.mdx
> +description: Add content to your Astro project using KeystoneJS as a CMS
Falta traducir

2023-06-29 02:05 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/keystonejs.mdx
> +[KeystoneJS](https://keystonejs.com/) is an open source, headless content-management system that allows you to describe the structure of your schema.
Falta traducir

2023-06-29 04:34 UTC, Waxer59 commented on src/content/docs/es/guides/cms/keystonejs.mdx
> +[KeystoneJS](https://keystonejs.com/) is an open source, headless content-management system that allows you to describe the structure of your schema.
```suggestion
[KeystoneJS](https://keystonejs.com/) es un sistema de gestión de contenido headless de código abierto que te permite describir la estructura de tu esquema.
```

2023-06-29 04:34 UTC, Waxer59 commented on src/content/docs/es/guides/cms/keystonejs.mdx
> +description: Add content to your Astro project using KeystoneJS as a CMS
```suggestion
description: Agrega contenido a tu proyecto Astro utilizando KeystoneJS como un CMS
```

2023-06-29 04:35 UTC, Waxer59 commented
Ya traduje lo que faltaba, gracias por la revisión 🤠

2023-06-30 11:52 UTC, Yan-Thomas approved these changes
LGTM!

2023-06-30 11:52 UTC, merged