i18n(es): Translated `google-firebase.mdx` WIP
withastro/docs pull request #3620
Opened 2023-06-28 09:59 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translated `google-firebase.mdx`

2023-06-28 15:21 UTC, Waxer59 commented on src/content/docs/es/guides/backend/google-firebase.mdx
> +- Un proyecto de Astro [inicializado con Firebase](#initializing-firebase-in-astro).
```suggestion
- Un proyecto de Astro [inicializado con Firebase](#inicializando-firebase-en-astro).
```

2023-06-29 20:46 UTC, dreyfus92 requested changes
Te dejo algunas sugerencias @Waxer59, buen trabajo 😁

2023-06-29 20:46 UTC, dreyfus92 commented on src/content/docs/es/guides/backend/google-firebase.mdx
> +Consulta nuestra guía independiente para [implementar en Firebase Hosting](/es/guides/deploy/google-firebase/).
```suggestion
Consulta nuestra guía independiente para [desplegar en Firebase Hosting](/es/guides/deploy/google-firebase/).
```

2023-06-29 20:46 UTC, dreyfus92 commented on src/content/docs/es/guides/backend/google-firebase.mdx
> +- Un [royecto de Firebase con una aplicación web configurad](https://firebase.google.com/docs/web/setup).
```suggestion
- Un [proyecto de Firebase con una aplicación web configurada](https://firebase.google.com/docs/web/setup).
```

2023-06-29 20:46 UTC, dreyfus92 commented on src/content/docs/es/guides/backend/google-firebase.mdx
> +- Un proyecto de Astro con [renderizado del lado del servidor (SSR)](/es/guides/server-side-rendering/#habilitando-ssr-en-tu-proyecto) enabled.
```suggestion
- Un proyecto de Astro con [renderizado del lado del servidor (SSR)](/es/guides/server-side-rendering/#habilitando-ssr-en-tu-proyecto) habilitado.
```

2023-06-29 20:46 UTC, dreyfus92 commented on src/content/docs/es/guides/backend/google-firebase.mdx
> +`register.ts` contains the code to register a user using Firebase:
Te falta traducir.

2023-06-29 20:46 UTC, dreyfus92 commented on src/content/docs/es/guides/backend/google-firebase.mdx
> +    <label for="email" for="email">Email</label>
```suggestion
    <label for="email" for="email">Correo electrónico</label>
```

2023-06-29 20:46 UTC, dreyfus92 commented on src/content/docs/es/guides/backend/google-firebase.mdx
> +    <label for="email" for="email">Email</label>
```suggestion
    <label for="email" for="email">Correo electrónico</label>
```

2023-06-29 20:46 UTC, dreyfus92 commented on src/content/docs/es/guides/backend/google-firebase.mdx
> +- Un proyecto Astro inicializado con Firebase según se describe en la sección [Inicializando Firebase en Astro](#inicializando-firebase-en-astro) section.
```suggestion
- Un proyecto Astro inicializado con Firebase según se describe en la sección [Inicializando Firebase en Astro](#inicializando-firebase-en-astro).
```

2023-06-29 22:58 UTC, Waxer59 commented on src/content/docs/es/guides/backend/google-firebase.mdx
> +`register.ts` contains the code to register a user using Firebase:
```suggestion
`register.ts` contiene el código para registrar un usuario utilizando Firebase:
```

2023-06-29 22:59 UTC, Waxer59 commented
Listo!, gracias por la revisión 🤠

2023-06-30 11:19 UTC, Yan-Thomas approved these changes
Amazing work, LGTM!

2023-06-30 11:19 UTC, merged