i18n(es): Updated `prefetch.mdx` & `configuration-reference.mdx`
withastro/docs pull request #3699
Opened 2023-07-11 18:03 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Updated `prefetch.mdx`

`prefetch.mdx`
* [`f6563bb`](https://github.com/withastro/docs/commit/f6563bbd815168345e402fd56204013797c262e8)

`configuration-reference.mdx`
* [`e724d5e`](https://github.com/withastro/docs/commit/e724d5ed5821e888f56d64113bebe330dd6c28a8)

2023-07-11 19:05 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo una sugerencia 😄

2023-07-11 19:05 UTC, dreyfus92 commented on src/content/docs/es/reference/configuration-reference.mdx
> +Cuando está habilitado, el código del middleware no se incluye y se importa en todas las páginas durante la compilación. Para ejecutar e importar manualmente el código del middleware, establece `buil
```suggestion
Cuando está habilitado, el código del middleware no es empaquetado ni se importa en todas las páginas durante la compilación. Para ejecutar e importar manualmente el código del middleware, establece `build.excludeMiddleware: true`:
```

2023-07-11 20:18 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-07-12 12:03 UTC, Yan-Thomas approved these changes
Thanks peeps, I noticed a small issue in the Configuration Reference I'll fix upstream and let you know to update later!

2023-07-12 12:03 UTC, merged