i18n(es): `api-reference.mdx` update
withastro/docs pull request #3762
Opened 2023-07-19 14:11 UTC by Mardroide

#### What kind of changes does this PR include?
- Updated content

#### Reference
- [840b0e6](https://github.com/withastro/docs/commit/840b0e60b45d6261a5ebaa99ae536ae8c0bd063e)

2023-07-20 01:22 UTC, dreyfus92 requested changes
Buen trabajo @Mardroide, te dejo una sugerencia 😁

2023-07-20 01:22 UTC, dreyfus92 commented on src/content/docs/es/reference/api-reference.mdx
> +    body: locals.title // "Default Title"
```suggestion
    body: locals.title // "Título por defecto"
```

2023-07-20 01:24 UTC, dreyfus92 commented
Por cierto me quedó la duda de que andas arrastrando unos updates en esta PR también presentes en esta PRhttps://github.com/withastro/docs/pull/3763, no se si los cambios también son parte de esta PR.

2023-07-20 12:10 UTC, Mardroide commented
Hice varias ramas para las 4 pull request pero se  juntaron los commits. No se porqué. Por cierto @dreyfus92, en cuanto a la sugerencia, si subes un poco pone `locals.title = "Default Title";` por eso había dejado el comentario en inglés pensado que se refiere a esa parte.

2023-07-20 14:52 UTC, dreyfus92 commented
> Hice varias ramas para las 4 pull request pero se juntaron los commits. No se porqué. Por cierto @dreyfus92, en cuanto a la sugerencia, si subes un poco pone `locals.title = "Default Title";` por eso había dejado el comentario en inglés pensado que se refiere a esa parte.

Entonces déjalo en inglés, por otro lado los commits los puedes quitar/remover con diferentes [estrategias](https://stackoverflow.com/questions/34519665/how-can-i-move-head-back-to-a-previous-location-detached-head-undo-commits/34519716#34519716) una de ellas es usar git revert.

2023-07-20 15:27 UTC, Mardroide commented
> Entonces déjalo en inglés, por otro lado los commits los puedes quitar/remover con diferentes [estrategias](https://stackoverflow.com/questions/34519665/how-can-i-move-head-back-to-a-previous-location-detached-head-undo-commits/34519716#34519716) una de ellas es usar git revert.

Ya lo dejamos tal cual está. Ya me aceptaron alguna PR. Solo falta que hagan merge.

2023-07-21 00:44 UTC, Waxer59 reviewed
Yo traduciria ambos strings ya que no afecta al correcto funcionamiento de la página

2023-07-21 00:44 UTC, Waxer59 commented on src/content/docs/es/reference/api-reference.mdx
> +    locals.title = "Default Title";
```suggestion
    locals.title = "Título por defecto";
```

2023-07-21 00:44 UTC, Waxer59 commented on src/content/docs/es/reference/api-reference.mdx
> +    body: locals.title // "Default Title"
```suggestion
    body: locals.title // "Título por defecto"
```

2023-07-21 00:45 UTC, Waxer59 commented on src/content/docs/es/reference/api-reference.mdx
> +    if (!locals.title) {
```suggestion
  if (!locals.title) {
```

2023-07-21 00:50 UTC, Waxer59 approved these changes
LGTM ✔

2023-07-21 01:04 UTC, Yan-Thomas approved these changes
LGTM! Great work everyone!

2023-07-21 01:04 UTC, merged