[WIP] i18n(fr): Add French tutorial
withastro/docs pull request #3809
Opened 2023-07-24 17:12 UTC by Yan-Thomas

#### What kind of changes does this PR include?

- Translated content

#### Description

Tutorial translation to French.

2023-07-29 06:35 UTC, sdp971 requested changes
Hi, Good job ✌️. I made suggestions and rephrased few sentences. Hope it will help.

2023-07-29 06:35 UTC, sdp971 commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Sur votre chemin, vous:
I suggest : 

Au cours de ce tutoriel, vous serez amené(e) à :

- Mettre en place un environnement de développement
- Créer des pages et des articles de blog pour votre site web
- Utiliser des composants Astro pour construire votre site
- Interroger et manipuler des fichiers en local
- Ajouter de l'interactivité à votre site
- Mettre en ligne votre site sur Internet

2023-07-29 06:35 UTC, sdp971 commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Voulez vous avoir un percu de ce que vous allez realiser? Vous pouvez voir le projet fini sur [GitHub](https://github.com/withastro/blog-tutorial-demo) ou [StackBlitz](https://stackblitz.com/github/w
I suggest for line 26 => Souhaitez-vous avoir un aperçu de ce que vous allez réaliser ? Vous pouvez visualiser le projet finalisé à l'adresse suivante : [GitHub](https://github.com/withastro/blog-tutorial-demo) ou [StackBlitz](https://stackblitz.com/github/withastro/blog-tutorial-demo/tree/complete?file=src%2Fpages%2Findex.astro).

2023-07-29 06:35 UTC, sdp971 commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Si vous preferez commencer a explorer Astro avec une version pre-construite, vous pouvez visiter https://astro.new et selectionner un gabarit de demmarrage, l'ouvrir et l'editer dans l'editeur en lig
I suggest for line 29 => Si vous souhaitez plutôt commencer à explorer Astro avec un site Astro pré-construit, vous pouvez visiter https://astro.new et choisir un modèle, l'ouvrir et le modifier dans un éditeur en ligne.

2023-07-29 06:35 UTC, sdp971 commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +- [ ] Ca a l'air bon! Je suis pret a commencer!
I suggest for line 37 => Parfait, je suis prêt(e) à commencer !

2023-08-04 15:18 UTC, thomasbnt approved these changes

2023-08-04 15:18 UTC, thomasbnt commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +<Lede> Dans de tutoriel, vous apprendrez les fonctionnalites cles d'Astro en realisant un blog totalement fonctionnel, de zero jusqu'au deploiement en ligne! 🚀 </Lede>
> Dans ce tutoriel, vous apprendrez les fonctionnalités clés d'Astro en réalisant un blog totalement fonctionnel à partir de zéro jusqu'à son déploiement en ligne.

This one is cool! ☕

2023-08-04 15:19 UTC, thomasbnt commented
Arrrg I approved, but this is a mistake, only comment and to be notified of any changes. 😶

2023-08-17 18:25 UTC, Yan-Thomas commented
Thanks for the reviews @sdp971 & @thomasbnt, this is a "collection" PR that merges other folks translations, I particularly don't spreak French so I can't really discuss or know if what you proposed is appropriate, could you make a separate PR making these specific changes to this branch and then I can merge them here?

2023-08-17 18:52 UTC, sdp971 commented
> Thanks for the reviews @sdp971 & @thomasbnt, this is a "collection" PR that merges other folks translations, I particularly don't spreak French so I can't really discuss or know if what you proposed is appropriate, could you make a separate PR making these specific changes to this branch and then I can merge them here?

Hi @Yan-Thomas, ok I'll make the PR tonight. I might need some guidance during the process.

2023-08-17 18:54 UTC, thomasbnt commented
> Hi @Yan-Thomas, ok I'll make the PR tonight. I might need some guidance during the process.

Hello! Thanks @sdp971 !

2023-08-17 20:40 UTC, sdp971 commented
> > Hi @Yan-Thomas, ok I'll make the PR tonight. I might need some guidance during the process.
> 
> Hello! Thanks @sdp971 !

You're welcome 🙂

2023-08-17 20:42 UTC, sdp971 commented
> Thanks for the reviews @sdp971 & @thomasbnt, this is a "collection" PR that merges other folks translations, I particularly don't spreak French so I can't really discuss or know if what you proposed is appropriate, could you make a separate PR making these specific changes to this branch and then I can merge them here?

@Yan-Thomas it's done  [here](https://github.com/withastro/docs/pull/4252). Hope it's fine.

2023-09-02 07:46 UTC, McFlyPartages commented
What is the status of this PR ?

2023-09-05 17:33 UTC, Yan-Thomas commented
> What is the status of this PR ?

This PR is just to allow people to see a deploy preview of the translation as it is translated in other, individual, PRs tackling certain pages of it. Some people have been translating the pages with time, so it is being actively maintained.

2023-09-14 19:25 UTC, Ranily57 commented
I sure did mistake haha, thank's for the help on the translation !

2023-10-05 18:02 UTC, thomasbnt commented
Hello! Seems an old MR since https://github.com/withastro/docs/pull/4688 was created for tutorial part.

2023-11-09 11:39 UTC, sarah11918 commented
Yes, it appears that the other PR is the complete one! We will review it for merging this week! :rocket:

2023-11-09 14:46 UTC, sarah11918 commented
Just closing this PR in favour of the full French tutorial being merged in the other PR! :partying_face:

2023-11-09 14:46 UTC, closed without merging