i18n(ar): Translate Astro-Components page.
withastro/docs pull request #3830
Opened 2023-07-26 10:30 UTC by Somespi

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.

translating `core-concepts/astro-components` page to Arabic, although I'm not sure of some words, so I used some docs as a reference.

2023-07-26 11:12 UTC, yhyadev commented
You forgot to change the navbar, It is still saying "Components" instead of "المكونات".

2023-07-26 11:17 UTC, Somespi commented
> You forgot to change the navbar, It is still saying "Components" instead of "المكونات".

sure its, thanks for notifying me, I fixed it.

2023-07-28 01:56 UTC, g9wz requested changes
left "some" comments 😅

great work otherwise

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +و مع ذلك، يدعم [ بناء قالب المكوّن لأسترو](/ar/core-concepts/astro-syntax/) كذلك **تعابير جافاسكربت**، وسوم [`<style>`](/ar/guides/styling/#styling-in-astro) و [`<script>`](/guides/client-side-script
- "ومع ذلك، يدعم هيكل قالب المكوّن في أسترو تعابير جافاسكربت .." بدلًا من المكتوب.
- حذف المسافات بعد واو العطف
- "استخدامها" همزة وصل

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +المكوّنات مصممة لتكون قابلة لإعادة الاستخدام وقابلة للتركيب. يمكنك استخدام المكوّنات داخل مكوّنات أخرى لبناء واجهات مستخدم متقدمة بشكل أكبر وأكثر تطوراً. على سبيل المثال، يمكن استخدام مكوّن "زر" (But
```suggestion
المكوّنات مصممة لتكون قابلة **لإعادة الاستخدام** و**التركيب**. يمكنك استخدام مكوّنات داخل مكوّنات أخرى لبناء واجهات مستخدم متقدمة بشكل أكبر وأكثر تطورًا. على سبيل المثال، يمكن استخدام مكوّن "زر" (Button) لإنشاء مكوّن "مجموعة أزرار" (ButtonGroup):
```

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +يمكن لمكوّن أسترو أن يعرّف و يستقبل الخاصيّات "props". هذه الخاصيّات "props" تصبح متاحة بعدها لقالب المكوّن لتصيير HTML. الخاصيّات "props" متاحة في `Astro.props` .بشكل عام في البرنامج النصّي  للـfron
```suggestion
يمكن لمكوّن أسترو تعريف الخاصيات وقبولها "props". هذه الخاصيّات تصبح متاحة لقالب المكوّن لتصيير HTML. الخاصيّات متاحة على `Astro.props` بشكل عام في  الـfrontmatter الخاص بك.
```

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +هنا مثال لمكوّن يستقبل خاصيّة `greeting` و خاصيّة `name`. لاحظ أن الخاصيّات "props" التي سيتم استقبالها مفككة من object `Astro.props` العام.
```suggestion
هنا مثال لمكوّن يستقبل خاصيّة `greeting` وخاصيّة `name`. لاحظ أن الخاصيّات التي سيتم استقبالها مفككة من object `Astro.props` العام.
```

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +هذا المكوّن، عندما يُستورد و يُصيّر في مكوّنات أسترو اخرى، مخططات أو صفحات، يمكن أن يتم تمرير هذه الخاصيّات "props" كسمات "attributes":
```suggestion
عند استيراد هذا المكوّن وتصييره في مكونات أو تخطيطات أو صفحات أسترو أخرى، يمكن تمرير هذه الخاصيّات "props" كسمات "attributes":

```

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +بالإمكان ايضًا تعريف الخاصيّات "props" الخاصة بك مع TypeScript باستخدام واجهة `Props`. سيقوم أسترو تلقائيًا باكتشاف واجهة `Props` في معلوماتك الأوّليّة "frontmatter"  و يعطي تحذيرات أو أخطاء. يمكن أي
```suggestion
بالإمكان أيضًا تعريف الخاصيّات الخاصة بك مع TypeScript باستخدام واجهة `Props`. سيقوم أسترو تلقائيًا باكتشاف واجهة `Props` في الـ "frontmatter" الخاص بك وإعطاء تحذيرات أو أخطاء إن وجد. يمكن أيضًا إعطاء هذه الخاصيات قيمًا افتراضية عند استخراجها من `Astro.props`.
```

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +يمكن إعطاء خاصيّات "props" المكوّنات قيم إفتراضية عندما لا يتم توفير أي منها.
```suggestion
يمكن إعطاء خاصيّات المكوّنات قيمًا افتراضية عندما لا يتم توفير أي منها.
```

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +`<slot />` هو عنصر نائب لمحتوى HTML الخارجي، مما يسمح لك بحقن (أو "ادخال") عناصر داخلية من ملفّات اخرى الى قالب مكوّنك.
```suggestion
`<slot />` هو عنصر نائب لمحتوى HTML الخارجي، مما يسمح لك بحقن (أو "ادخال") عناصر من ملفّات أخرى الى قالب مكوّنك.
```

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +بشكل افتراضي، سيتم تصيير كل العناصر الداخلية الممرّرة لمكوّن في `<slot />` الخاص بها.
- using "الداخلية" does not make sense, use "التابعة if you must.
- الخاص به (مكوّن)، وليس بها.

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +هذ النمط هو أساس [مكوّنات تخطيط أسترو](/ar/core-concepts/layouts/): صفحة كامل من محتوى HTML يمكن أن "تُلف" بواسطة وسوم `<SomeLayoutComponent></SomeLayoutComponent>` و يتم ارسالها الى المكوّن ليتهم تص
component is not plural, use "مكوّن تخطيط أسترو"

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +يمكن كذلك لمكوّن أسترو أن يحتوي على مداخل مسماة "named slots". يسمح لك هذا بتمرير عناصر HTML فقط مع اسم المدخل المقابل الى موقع المدخل
full stop

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +يمكن تسمية الفتحات "slots" باستخدام سمة "attribute" `name`:
you either use فتحات or مداخل to reduce confusion

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +لإدخال محتوى HTML الى مدخل معين، يمكنك إستخدام سمة "attribute" `slot` على أي عنصر داخلي لتحديد اسم المدخل. سيتم إدخال بقية العناصر الداخلية الى المدخل الإفتراضي (غير مسمى) `<slot />`.
- "لحقن" بدل "لإدخال"
- ماله داعي كتابة ترجمة كلمة ما كل ما يتم استخدامها، مرة وحدة تكفي
- عنصر تابع أدق من عنصر داخلي

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +إستخدم سمة "attribute" `slot="my-slot"` على العنصر الداخلي الذي تريد تمريره الى عنصر نائب مطابق لـ `<slot name="my-slot" />` في مكوّنك.
- فعل الأمر ما تكتب همزته قطع، استخدم
- احذف التراجم الإنجليزية الغير ضرورية

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +يمكن ايضًا أن تمرر المدخلات المسماة الى [مكوّنات أطر واجهة المستخدم](/ar/core-concepts/framework-components/)!
أيضًا، إلى

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +بإمكان المداخل ايضًا ان تصّير **محتوى احتياطي**. عندما لا يكون هنالك عنصر داخلي مطابق مُرّرَ الى المدخل، عنصر `<slot />` سيُصيّر عنصر داخلي نائب خاص به.
"عند عدم وجود عناصر تابعة مُمررة إلى "الفتحة أو المدخل - اختر وحدة"، عنصر .."

2023-07-28 01:56 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +## مكوّنات HTML
proofread the whole section
- inconsistent punctuation
- waslas
- src/pages/

2023-07-28 21:12 UTC, Somespi commented
I've addressed all the suggestions, and upon review, I noticed that I had overlooked several mistakes. Thank you for correcting me 😅

2023-07-28 21:16 UTC, g9wz commented
> @g9wz I've addressed all the suggestions, and upon review, I noticed that I had overlooked several mistakes. Thank you for correcting me 😅

I know what it is like to deal with rtl in markdown, don't worry about it 😁

2023-07-28 21:45 UTC, g9wz requested changes
minor last touches ✍🏻

2023-07-28 21:45 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +أهم شيء يجب معرفته عن مكوّنات أسترو هو أنها **لا تُصيّر على جانب العميل**. يحوَّل المكون إلى HTML إما في وقت البناء أو حسب الطلب باستخدام [ (SSR) العرض على الخادم](/ar/guides/server-side-rendering/)
inconsistent use of quotation marks around frontmatter

2023-07-28 21:45 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +سياج الكود "code fence" مصمّم لضمان أنّ جافاسكربت الذي ستكتبه سيكون "محاط بسياج". لن يعرض في تطبيقك على جانب العميل، ولن يقع بين يدي مستخدميك. يمكنك هنا كتابة الكود بأمان، حتى إذا كانت تكلفة التنفيذ
محاطًا بسياج.

overlooked by me in the initial review 😅

2023-07-28 21:45 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +بعكس _الخاصيات _، التي هي سمات "attributes" يتم تمريرها إلى مكوّن أسترو والمتاحة للإستخدام في المكوّن الخاص بك باستخدام `Astro.props`، _المداخل "slots"_ تُصيّر عناصر HTML الداخليّة حيث كتبت.
extra space between one of the underscores and the word inside causes it not to be Italicized

2023-07-28 21:45 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +بإمكان المداخل ايضًا ان تصّير **محتوى احتياطي**. عندما لا يكون هنالك عنصر تابع مطابق مُرّرَ إلى المدخل، عنصر `<slot />` سيُصيّر عنصر تابع نائب خاص به.
```suggestion
بإمكان المداخل أيضًا تصيّير **محتوى احتياطي**. عندما لا يكون هنالك عنصر تابع مطابق مُرّرَ إلى المدخل، عنصر `<slot />` سيُصيّر عنصر تابع نائب خاص به.
```

2023-07-28 21:45 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +يدعم أسترو استيراد واستخدام ملفات `.html` كمكوّنات أو وضع هذه الملفات في الدليل الفرعي `src/pages` كصفحات. قد ترغب باستخدام مكوّنات HTML اذا كنت تعيد استخدام الكود من موقع ويب مبني بدون استخدام أي اط
- missing slash after pages to indicate that it is a folder
- إذا، إطار، جميعها همزات وصل

2023-07-28 21:45 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +يجب ات تحتوي مكوّنات HTML على HTML صالح فقط، وبالتالي، تفتقر إلى ميزات أسترو الأساسية:
```suggestion
يجب أن تحتوي مكوّنات HTML على HTML صالح فقط، وبالتالي تفتقر إلى ميزات مكوّن أسترو الأساسية:
```

2023-07-28 21:45 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +- أي وسوم `<script>` تُركت غير مجمّعة, سيتم التعامل معها كما لو انها تحتوي على `is:inline`.
```suggestion
- أي وسوم `<script>` تُركت غير مجمّعة، سيتم التعامل معها كما لو انها تحتوي على `is:inline`.
```

2023-07-28 21:45 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +[عنصر `<slot />`](/en/core-concepts/astro-components/#slots) الموجود داخل مكوّن HTML سيعمل كما يعمل في مكوّن أسترو. لإستخدام عنصر ["HTML Web Component Slot"](https://developer.mozilla.org/en-US/docs/
missing a full stop

2023-07-28 23:19 UTC, g9wz requested changes
kindly fix the following

2023-07-28 23:19 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +بعكس _الخاصيات _، التي هي سمات "attributes" يتم تمريرها إلى مكوّن أسترو والمتاحة للإستخدام في المكوّن الخاص بك باستخدام `Astro.props`، _المداخل "slots"_ تُصيّر عناصر HTML الداخليّة حيث كتبت.
<img width="851" alt="Screenshot 2023-07-29 at 2 08 51 AM" src="https://github.com/withastro/docs/assets/118110192/68924f23-9adf-42f7-9213-f52144c1954b">

this has not been resolved

2023-07-28 23:19 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +**مكوّنات أسترو** هي اللبنات الأساسية لأي مشروع أسترو. إنها مكوّنات قوالب HTML فقط بلا وقت تشغيل من جانب العميل. يمكنك التعرف على مكوّن ويب أسترو عن طريق إمتداد الملف: `.astro`
kindly remove any instance of "ويب أسترو", mentioning web is not needed nor used originally

2023-07-28 23:19 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +[عنصر `<slot />`](/en/core-concepts/astro-components/#slots) الموجود داخل مكوّن HTML سيعمل كما يعمل في مكوّن أسترو. لإستخدام عنصر ["HTML Web Component Slot"](https://developer.mozilla.org/en-US/docs/
change the first link to navigate locally, it's currently routing to the en page

change "/en/" with "/ar/" && "#slots" with "#المداخل"

2023-07-28 23:19 UTC, g9wz commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +- استيراد مكوّنات أطر عمل أخرى، مثل رياكت
add "(React)" at the end of the sentance

2023-07-29 00:02 UTC, g9wz commented
sync your fork after that, I want to compare & pr an updated nav.ts file

2023-07-29 04:34 UTC, g9wz approved these changes
@Yan-Thomas LGTM 👍🏻

2023-07-29 04:53 UTC, g9wz approved these changes

2023-07-29 12:50 UTC, Yan-Thomas commented on src/content/docs/ar/core-concepts/astro-components.mdx
> +ومع ذلك، يدعم [ بناء قالب المكوّن لأسترو](/ar/core-concepts/astro-syntax/) كذلك **تعابير جافاسكربت**، وسوم [`<style>`](/ar/guides/styling/#styling-in-astro) و[`<script>`](/guides/client-side-scripts/
```suggestion
ومع ذلك، يدعم [ بناء قالب المكوّن لأسترو](/ar/core-concepts/astro-syntax/) كذلك **تعابير جافاسكربت**، وسوم [`<style>`](/ar/guides/styling/#styling-in-astro) و[`<script>`](/ar/guides/client-side-scripts/#using-script-in-astro) لأسترو والمكوّنات المستوردة و[توجيهات أسترو الخاصة](/ar/reference/directives-reference/). البيانات والقيم المعرّفة في البرنامج النصي للمكوّن يمكن إستخدامها في قالب المكوّن لإنتاج HTML مُنشأ ديناميكيًا.
```

2023-07-29 13:00 UTC, Yan-Thomas approved these changes
LGTM! Thanks @Somespi 🙌

2023-07-29 13:00 UTC, merged