i18n(zh-cn): Translate reference/api-reference.mdx
withastro/docs pull request #3864
Opened 2023-07-27 07:43 UTC by Chaochao2020

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

-Translate reference/api-reference.mdx content to Chinese.

2023-07-27 11:23 UTC, liruifengv requested changes

2023-07-27 11:23 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +`Astro` global 在 .astro 文件的所有上下文中都可用。它具有以下功能：
```suggestion
`Astro` global 在 `.astro` 文件的所有上下文中都可用。它具有以下功能：
```

2023-07-27 11:23 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +| `value`          | `string` \| undefined                      | cookie 的原始字符串值          |
注意这里上下两个表格的渲染格式问题。需要调整一下

2023-07-27 11:23 UTC, liruifengv commented
`Astro.redirect()`有变动，查看 commit https://github.com/withastro/docs/pull/3395/files

2023-07-27 11:24 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +context.locals "是一个对象，用于在请求的生命周期内存储和访问任意信息。
```suggestion
`context.locals`是一个对象，用于在请求的生命周期内存储和访问任意信息。
```

2023-07-27 11:33 UTC, liruifengv requested changes

2023-07-27 11:33 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +**Type:** `'content' | 'data'`
```suggestion
**类型：** `'content' | 'data'`  
```
这里也需要翻译，其他同理。

2023-07-27 11:33 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +[参阅 `内容集合`指南](/en/guides/content-collections/#defining-collection-references) for example usage.
```suggestion
有关示例请[参考 `内容集合`指南](/zh-cn/guides/content-collections/#defining-collection-references)
```
其他类似的地方都统一按这个来翻译吧

2023-07-27 11:33 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +**Available for:** `type: 'content'` and `type: 'data'` collections
这里也需要翻译哈

2023-07-27 11:33 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +**示例类型:** `'blog' | 'authors' | ...`
```suggestion
**示例类型：** `'blog' | 'authors' | ...`
```

2023-07-27 11:33 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
>  **示例类型** `'entry-1' | 'entry-2' | ...`
```suggestion
**示例类型：** `'entry-1' | 'entry-2' | ...`
```

2023-07-27 11:56 UTC, liruifengv commented
https://github.com/withastro/docs/pull/3233 还有这个 commit

2023-07-31 03:07 UTC, liruifengv requested changes

2023-07-31 03:07 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +**Type:** `(collection: string) => ZodEffects<ZodString, { collection, id: string } | { collection, slug: string }>`
```suggestion
**类型：** `(collection: string) => ZodEffects<ZodString, { collection, id: string } | { collection, slug: string }>`
```

2023-07-31 03:07 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +有关`内容集合`的示例, 请参考 [querying collection entries](/zh-cn/guides/content-collections/#querying-collections).
这里翻译一下

2023-07-31 03:07 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +**Types:**
```suggestion
**类型：**
```

2023-07-31 03:07 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +**Types:**
```suggestion
**类型：**
```

2023-07-31 03:07 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +**适用于:** 仅 `type: 'content'` 集合
```suggestion
**适用于：** 仅 `type: 'content'` 集合
```

2023-07-31 03:09 UTC, liruifengv commented
Miss:
- https://github.com/withastro/docs/commit/c79342060d9a1094ca33dadd609ce72bac4709a7

2023-07-31 03:14 UTC, liruifengv requested changes

2023-07-31 03:14 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +**默认:** `'content'`
```suggestion
**默认：** `'content'`
```

2023-07-31 03:14 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +**类型:** `'content' | 'data'`
```suggestion
**类型：** `'content' | 'data'`  
```

2023-07-31 18:33 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-07-31 18:33 UTC, merged