i18n(zh-cn): update guides/styling.mdx
withastro/docs pull request #3886
Opened 2023-07-27 15:48 UTC by dorasans

#### What kind of changes does this PR include?
- Do some minor content fixes,translate the part of  `Production`.

#### Description

- update the translation

2023-07-27 16:08 UTC, dorasans commented
@liruifengv pls review

2023-07-28 01:04 UTC, liruifengv commented
PR 描述分类改一下

2023-07-28 01:14 UTC, liruifengv requested changes
A little change. Other LGTM! Thanks @dorasans

2023-07-28 01:14 UTC, liruifengv commented on src/content/docs/zh-cn/guides/styling.mdx
> +### 捆绑包控制
```suggestion
### 打包控制
```

2023-07-28 01:14 UTC, liruifengv commented on src/content/docs/zh-cn/guides/styling.mdx
> +完整的细节见[Vite的文档](https://vitejs.dev/guide/assets.html#importing-asset-as-string)。
```suggestion
完整的细节见[Vite的文档](https://cn.vitejs.dev/guide/assets.html#importing-asset-as-string)。
```
Vite 的文档可以指向中文

2023-07-28 01:14 UTC, liruifengv commented on src/content/docs/zh-cn/guides/styling.mdx
> +Astro 内置了 PostCSS，作为 [Vite](https://vitejs.dev/guide/features.html#postcss) 的一部分。要为你的项目配置 PostCSS，在项目根部创建 `postcss.config.js` 文件。然后你就可以在安装插件后使用 `require()` 导入插件（例如 `npm install autoprefixer`）。
```suggestion
Astro 内置了 PostCSS，作为 [Vite](https://cn.vitejs.dev/guide/features.html#postcss) 的一部分。要为你的项目配置 PostCSS，在项目根部创建 `postcss.config.js` 文件。然后你就可以在安装插件后使用 `require()` 导入插件（例如 `npm install autoprefixer`）。
```

2023-07-29 13:23 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-07-29 13:23 UTC, merged