i18n(zh-cn): translate from-vuepress.mdx
withastro/docs pull request #3890
Opened 2023-07-27 18:10 UTC by woshierha

#### What kind of changes does this PR include?

- Translated content

#### Description

- translate from-vuepress.mdx

2023-07-28 02:57 UTC, liruifengv commented
Thank you for your contribution. the description of the PR needs to be modified a bit, select the category you are modifying this time, and the description of what you are modifying.

For example:

### What kind of changes does this PR include?
Translated content
### Description
translate from-vuepress.mdx

2023-07-28 03:34 UTC, liruifengv requested changes

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +- VuePress 和 Astro 都是现代的 Javascript 静态网站生成器,具有类似的项目文件结构。它们都使用 [特殊的`src/pages/`文件夹来进行基于文件的路由](/en/core-concepts/astro-pages/)。因此，在创建和管理站点页面时，你应该会感到非常熟悉。
```suggestion
- VuePress 和 Astro 都是现代的 JavaScript 静态网站生成器，具有类似的项目文件结构。它们都使用 [特殊的`src/pages/`文件夹来进行基于文件的路由](/zh-cn/core-concepts/astro-pages/)。因此，在创建和管理站点页面时，你应该会感到非常熟悉。
```
The link should be pointed to zh-cn.

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +- Astro 和 VuePress 都是为 [以内容为中心的网站](/en/concepts/why-astro/#content-focused) 设计的，它们都拥有出色的内置 Markdown 文件支持。因此，在使用 Markdown 编写内容时，你会感到非常熟悉，并且你可以保留现有的内容。
```suggestion
- Astro 和 VuePress 都是为 [以内容为中心的网站](/zh-cn/concepts/why-astro/#以内容为中心) 设计的，它们都拥有出色的内置 Markdown 文件支持。因此，在使用 Markdown 编写内容时，你会感到非常熟悉，并且你可以保留现有的内容。
```

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +- Astro 提供了 [官方集成的 Vue 组件使用方式](/en/guides/integrations-guide/vue/) 并且支持 [安装NPM包](/en/guides/imports/#npm-packages)，其中包括一些适用于 Vue 的包。你可以编写 Vue UI 组件，并且可能可以保留你现有的部分或全部 Vue 组件和依赖项。
```suggestion
- Astro 提供了 [官方集成的 Vue 组件使用方式](/zh-cn/guides/integrations-guide/vue/) 并且支持 [安装NPM包](/zh-cn/guides/imports/#npm-包)，其中包括一些适用于 Vue 的包。你可以编写 Vue UI 组件，并且可能可以保留你现有的部分或全部 Vue 组件和依赖项。
```

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +- [MPA 和 SPA](/en/concepts/mpa-vs-spa/): VuePress 是基于 Vue 的单页面应用(SPA)。而 Astro 站点是使用 [`.astro`组件](/en/core-concepts/astro-components/)构建的多页面应用(MPA)，同时也支持 [React, Preact, Vue.js, Svelte, SolidJS, Alpin
```suggestion
- [MPA 和 SPA](/en/concepts/mpa-vs-spa/): VuePress 是基于 Vue 的单页面应用（SPA）。而 Astro 站点是使用 [`.astro`组件](/zh-cn/core-concepts/astro-components/)构建的多页面应用（MPA），同时也支持 [React, Preact, Vue.js, Svelte, SolidJS, AlpineJS, Lit](/zh-cn/core-concepts/framework-components/) 和原生 HTML 模板。
```

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +- [模板布局](/en/core-concepts/layouts/): VuePress 站点使用 Markdown (`.md`) 文件作为页面内容，同时使用HTML (`.html`) 模板作为布局。而 Astro 则是基于组件的，使用了 Astro 组件来构建页面的HTML模板、布局以及单个的UI元素。Astro 也可以通过[`.md` and `.mdx` 文件](/en/guide
```suggestion
- [模板布局](/zh-cn/core-concepts/layouts/): VuePress 站点使用 Markdown (`.md`) 文件作为页面内容，同时使用 HTML (`.html`) 模板作为布局。而 Astro 则是基于组件的，使用了 Astro 组件来构建页面的HTML模板、布局以及单个的 UI 元素。Astro 也可以通过[`.md` and `.mdx` 文件](/zh-cn/guides/markdown-content/) 来创建页面，通过 Astro 布局组件将 Markdown 内容封装在页面模板中。
```

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +- VuePress 是为内容丰富的 Markdown 优先网站设计的，并且它还具有一些内置的、专为文档设计的网站功能，而这些功能需要你自己在 Astro 中构建。同时，Astro 也提供了一些专为文档编写的功能，通过 [官方文档主题](https://github.com/withastro/astro/tree/latest/examples/docs?on=github) 就能够实现。本网
[官方文档主题](https://github.com/withastro/astro/tree/latest/examples/docs?on=github) Link had be removed. Maybe we should update the content here. @Yan-Thomas

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +要将 VuePress 文档网站转换为 Astro ，可以通过我们的官方 [Starlight 文档主题起始模板](https://starlight.astro.build)开始创建，或者在我们的 [主题展示页面](https://astro.build/themes?search=&categories%5B%5D=docs) 中探索更多社区文档主题。
```suggestion
要将 VuePress 文档网站转换为 Astro ，可以通过我们的官方 [Starlight 文档主题起始模板](https://starlight.astro.build/zh/)开始创建，或者在我们的 [主题展示页面](https://astro.build/themes?search=&categories%5B%5D=docs) 中探索更多社区文档主题。
```

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +你可以在 `create astro` 命令中使用 `--template` 参数，并选择其中一个官方起始模板来开始一个新的 Astro 项目。另外，你也可以 [从 GitHub 上的任意现有 Astro 存储库开始一个新项目](/en/install/auto/#starter-templates)。
```suggestion
你可以在 `create astro` 命令中使用 `--template` 参数，并选择其中一个官方起始模板来开始一个新的 Astro 项目。另外，你也可以 [从 GitHub 上的任意现有 Astro 存储库开始一个新项目](/zh-cn/install/auto/#入门模板)。
```

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +带着你现有的 Markdown 内容来 [创建 Markdown 页面](/en/guides/markdown-content/)。 你仍然可以利用 [基于文件的路由](/en/core-concepts/routing/)，只需将这些文档从 VuePress 的 `docs` 文件目录下 移动到 Astro 的 `src/pages/` 目录下，并且保证创建了与现有的 VuePress 项目
```suggestion
带着你现有的 Markdown 内容来 [创建 Markdown 页面](/zh-cn/guides/markdown-content/)。 你仍然可以利用 [基于文件的路由](/zh-cn/core-concepts/routing/)，只需将这些文档从 VuePress 的 `docs` 文件目录下 移动到 Astro 的 `src/pages/` 目录下，并且保证创建了与现有的 VuePress 项目对应的文件夹，就能够保留现有的URLs. 
```

2023-07-28 03:34 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +VuePress 或你安装的其他任意主题可能已经为你处理了大部分站点的布局和元数据。你可能希望阅读关于 [在 Astro 中将 Markdown 页面包装为布局](/en/core-concepts/layouts/#markdownmdx-layouts) 以了解如何在 Astro 中自行管理模板，包括页面的 `<head>` 部分。
```suggestion
VuePress 或你安装的其他任意主题可能已经为你处理了大部分站点的布局和元数据。你可能希望阅读关于 [在 Astro 中将 Markdown 页面封装为布局](/zh-cn/core-concepts/layouts/#markdownmdx-布局) 以了解如何在 Astro 中自行管理模板，包括页面的 `<head>` 部分。
```

2023-07-29 12:53 UTC, Yan-Thomas commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +- VuePress 是为内容丰富的 Markdown 优先网站设计的，并且它还具有一些内置的、专为文档设计的网站功能，而这些功能需要你自己在 Astro 中构建。同时，Astro 也提供了一些专为文档编写的功能，通过 [官方文档主题](https://github.com/withastro/astro/tree/latest/examples/docs?on=github) 就能够实现。本网
Thanks for pointing out!

2023-07-31 00:42 UTC, liruifengv approved these changes
LGTM

2023-08-02 11:24 UTC, Yan-Thomas commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-vuepress.mdx
> +- [MPA 和 SPA](/en/concepts/mpa-vs-spa/): VuePress 是基于 Vue 的单页面应用（SPA）。而 Astro 站点是使用 [`.astro`组件](/zh-cn/core-concepts/astro-components/)构建的多页面应用（MPA），同时也支持 [React, Preact, Vue.js, Svelte, SolidJS, Al
```suggestion
- [MPA 和 SPA](/zh-cn/concepts/mpa-vs-spa/): VuePress 是基于 Vue 的单页面应用（SPA）。而 Astro 站点是使用 [`.astro`组件](/zh-cn/core-concepts/astro-components/)构建的多页面应用（MPA），同时也支持 [React, Preact, Vue.js, Svelte, SolidJS, AlpineJS, Lit](/zh-cn/core-concepts/framework-components/) 和原生 HTML 模板。
```

2023-08-02 11:34 UTC, Yan-Thomas approved these changes
LGTM! Great work :purple_heart:

2023-08-02 11:34 UTC, merged