i18n(zh-cn): add guides/migrate-to-astro/from-sveltekit.mdx
withastro/docs pull request #3902
Opened 2023-07-28 03:25 UTC by zhuchentong

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- add guides/migrate-to-astro/from-sveltekit.mdx

2023-07-28 03:35 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +- Astro 有[一个使用Svelte组件的官方集成](/zh-cn/guides/integrations-guide/svelte/)，并支持[安装NPM包](/zh-cn/guides/imports/#npm-packages)，包括一些用于 Svelte 的包。您将能够编写 Svelte UI 组件，并且可能做到保留部分或全部现有的组件和依赖项。
```suggestion
- Astro 有[一个使用Svelte组件的官方集成](/zh-cn/guides/integrations-guide/svelte/)，并支持[安装NPM包](/zh-cn/guides/imports/#npm-包)，包括一些用于 Svelte 的包。您将能够编写 Svelte UI 组件，并且可能做到保留部分或全部现有的组件和依赖项。
```

2023-07-28 03:36 UTC, liruifengv requested changes

2023-07-28 03:36 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +您可以将 `--template` 参数传递给 `create astro` 命令，以便使用其中一个模板开始一个新的 Astro 项目。或者，您可以[从 GitHub 上的任何现有的 Astro 的存储库中开始一个新项目](/zh-cn/install/auto/#starter-templates)。
```suggestion
您可以将 `--template` 参数传递给 `create astro` 命令，以便使用其中一个模板开始一个新的 Astro 项目。或者，您可以[从 GitHub 上的任何现有的 Astro 的存储库中开始一个新项目](/zh-cn/install/auto/#入门模板)。
```

2023-07-28 06:02 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +Next.js 和 Astro 有一些相似之处，可以帮助你迁移你的项目：
Next?

2023-07-28 06:08 UTC, liruifengv requested changes
The word "您" needs to be changed to "你" throughout the text.

2023-07-28 06:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +- SvelteKit 和 Astro 都存在一个 [`src/` 文件目录在您的项目文件](/zh-cn/core-concepts/project-structure/#src) 以及一个 [基于文件路由的特定文件目录](/zh-cn/core-concepts/astro-pages/)。对于您创建和管理页面应该会感觉很熟悉。
```suggestion
- SvelteKit 和 Astro 都存在一个 [`src/` 文件目录在你的项目文件](/zh-cn/core-concepts/project-structure/#src) 以及一个 [基于文件路由的特定文件目录](/zh-cn/core-concepts/astro-pages/)。对于你创建和管理页面应该会感觉很熟悉。
```
"您" -> "你"

2023-07-28 06:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +- [MPA vs alternatives](/zh-cn/concepts/mpa-vs-spa/)：Astro 网站是多页面应用程序，而 SvelteKit 默认为支持服务器端渲染的 SPA（单页面应用程序），但也可以创建 MPA、传统 SPA，或者您可以在应用程序中混合使用这些技术。
```suggestion
- [MPA vs 其它方案](/zh-cn/concepts/mpa-vs-spa/)：Astro 网站是多页面应用程序，而 SvelteKit 默认为支持服务器端渲染的 SPA（单页面应用程序），但也可以创建 MPA、传统 SPA，或者您可以在应用程序中混合使用这些技术。
```

2023-07-28 06:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +- [Markdown 准备](/zh-cn/guides/markdown-content/)：Astro 包含内置的 Markdown 支持，并且包含用于每个文件的页面模板的一个 [特殊的前置 YAML `layout` 属性](/zh-cn/core-concepts/layouts/#markdownmdx-布局)。如果您正在将 SvelteKit 的基于 Markdown 的博客转换为
```suggestion
- [Markdown 支持就绪](/zh-cn/guides/markdown-content/)：Astro 包含内置的 Markdown 支持，并且包含用于每个文件的页面模板的一个 [特殊的前置 YAML `layout` 属性](/zh-cn/core-concepts/layouts/#markdownmdx-布局)。如果您正在将 SvelteKit 的基于 Markdown 的博客转换为 Astro，您将不需要安装单独的 Markdown 集成，并且您不需要通过配置文件设置布局。您可以将现有的 Markdown 文件带入，但是您可能需要重新整理下这些文件，因为 Astro 的基于文件的路由不需要为每个页面路由创建一个文件夹。
```

2023-07-28 06:32 UTC, zhuchentong commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +- SvelteKit 和 Astro 都存在一个 [`src/` 文件目录在您的项目文件](/zh-cn/core-concepts/project-structure/#src) 以及一个 [基于文件路由的特定文件目录](/zh-cn/core-concepts/astro-pages/)。对于您创建和管理页面应该会感觉很熟悉。
Okay, I'll fix that

2023-08-01 03:00 UTC, liruifengv requested changes
A little change.

2023-08-01 03:00 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +- Astro 有[一个使用Svelte组件的官方集成](/zh-cn/guides/integrations-guide/svelte/)，并支持[安装NPM包](/zh-cn/guides/imports/#npm-包)，包括一些用于 Svelte 的包。你将能够编写 Svelte UI 组件，并且可能做到保留部分或全部现有的组件和依赖项。
```suggestion
- Astro 有[一个使用 Svelte 组件的官方集成](/zh-cn/guides/integrations-guide/svelte/)，并支持[安装NPM包](/zh-cn/guides/imports/#npm-包)，包括一些用于 Svelte 的包。你将能够编写 Svelte UI 组件，并且可能做到保留部分或全部现有的组件和依赖项。
```

2023-08-01 03:00 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +- Astro 和 SvelteKit 都允许你使用 [无头 CMS、API 或 Markdown 文件进行数据获取](/zh-cn/guides/data-fetching/)。你可以继续使用你喜欢的 [创作内容](/zh-cn/guides/content/) 系统，并且能够保留你现有的内容。
```suggestion
- Astro 和 SvelteKit 都允许你使用 [无头（headless） CMS、API 或 Markdown 文件进行数据获取](/zh-cn/guides/data-fetching/)。你可以继续使用你喜欢的 [创作内容](/zh-cn/guides/content/) 系统，并且能够保留你现有的内容。
```

2023-08-01 03:00 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-sveltekit.mdx
> +[SvelteKit](https://kit.svelte.dev) 是一个基于 Svelte 构建Web应用程序的框架。
```suggestion
[SvelteKit](https://kit.svelte.dev) 是一个基于 Svelte 构建 Web 应用程序的框架。
```

2023-08-01 09:36 UTC, liruifengv approved these changes
LGTM. Thanks @zhuchentong

2023-08-01 14:10 UTC, Yan-Thomas approved these changes
LGTM! Thanks for this! 💜

2023-08-01 14:10 UTC, merged