i18n(zh-cn): translate some migrate docs
withastro/docs pull request #3908
Opened 2023-07-28 05:09 UTC by Bluex-xx

#### What kind of changes does this PR include?
- Translated [from-docusaurus.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/migrate-to-astro/from-docusaurus.mdx)
- Translated [from-eleventy.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/migrate-to-astro/from-eleventy.mdx)
- Translated [from-gatsby.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/migrate-to-astro/from-gatsby.mdx)
- Translated [from-gitbook.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/migrate-to-astro/from-gitbook.mdx)
- Translated [from-gridsome.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/migrate-to-astro/from-gridsome.mdx)
#### Description

- Closes # 
- What does this PR change? Give us a brief description.
- Did you change something visual? A before/after screenshot can be helpful.

2023-07-28 15:25 UTC, CaptainOfPhB commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +查看[Gatsby's Blog启动模板转换步骤示例](#引导示例-gatsby-layout-to-astro)
Broken link

2023-07-28 15:28 UTC, CaptainOfPhB reviewed
Please fix broken links to pass the ci check

2023-07-28 15:28 UTC, CaptainOfPhB commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +2. 将任何[ Gatsby 或 JSX 语法转换为 Astro 语法](#参考-转化为-astro-语法)或HTML网络标准。例如 `<Link to="">`， `{children}`和 `className`。
Broken link

2023-07-28 15:28 UTC, CaptainOfPhB commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +您现有的 Gatsby JSX（`.js`）页面需要被[从 JSX 文件转换为 `.astro` 页面](#提示将jsx文件转换为astro文件)。您不能在 Astro 中使用现有的 JSX 页面文件。
Broken link

2023-07-28 15:28 UTC, CaptainOfPhB commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +- `gatsby-browser.js`：考虑将这里使用的任何东西直接添加到您的[主布局](#迁移布局文件)的 `<head>` 标签中。
Broken link

2023-07-28 15:28 UTC, CaptainOfPhB commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +2. 创建 `Layout.astro` 并添加此 `return` 值，[转换为 Astro 语法](#参考转换为-astro-语法)。
Broken link

2023-07-31 06:22 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gridsome.mdx
> +- Gridsome 和 Astro 都是现代 Javascript 静态网站生成器，具有相似的[项目文件结构](/zh-cn/core-concepts/project-structure#directories-and-files)。
```suggestion
- Gridsome 和 Astro 都是现代 Javascript 静态网站生成器，具有相似的[项目文件结构](/zh-cn/core-concepts/project-structure#目录和文件)。 
```

2023-08-01 00:56 UTC, liruifengv requested changes

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-docusaurus.mdx
> +- Docusaurus 设计用于构建文档网站，并且有一些内置的，特定于文档的网站功能，你需要在 Astro 中自己构建。相反，Astro 通过一个[官方的文档主题](https://github.com/withastro/astro/tree/latest/examples/docs)提供其中一些功能。这个网站就是使用该模板构建的！你还可以在我们的主题展示中找到更多具有内置功能的[社区文档主
```suggestion
- Docusaurus 设计用于构建文档网站，并且有一些内置的，特定于文档的网站功能，你需要在 Astro 中自己构建。相反，Astro 通过一个[官方的文档主题](https://starlight.astro.build)提供其中一些功能。这个网站就是该模板的灵感来源！你还可以在我们的主题展示中找到更多具有内置功能的[社区文档主题](https://astro.build/themes?search=&categories%5B%5D=docs)。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-docusaurus.mdx
> +- Docusaurus 站点使用MDX页面进行内容。Astro 的文档主题默认使用 Markdown(`.md`) 文件，并不需要你使用MDX。你可以选择[安装 Astro 的 MDX 集成](/zh-cn/guides/integrations-guide/mdx/)并使用`.mdx`文件作为标准Markdown文件。
```suggestion
- Docusaurus 站点使用 MDX 页面进行内容。Astro 的文档主题默认使用 Markdown(`.md`) 文件，并不需要你使用 MDX。你可以选择[安装 Astro 的 MDX 集成](/zh-cn/guides/integrations-guide/mdx/)并使用`.mdx`文件作为标准 Markdown 文件。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-docusaurus.mdx
> +要把一个 Docusaurus 文档站点转换为 Astro，首先使用我们的官方[Starlight 文档主题启动模板](https://starlight.astro.build)，或者在我们的[主题展示](https://astro.build/themes?search=&categories%5B%5D=docs)中探索更多社区文档主题。
```suggestion
要把一个 Docusaurus 文档站点转换为 Astro，首先使用我们的官方 [Starlight 文档主题启动模板](https://starlight.astro.build)，或者在我们的[主题展示](https://astro.build/themes?search=&categories%5B%5D=docs)中探索更多社区文档主题。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-docusaurus.mdx
> +你可以向`create astro`命令传递一个`--template`参数，以一个我们的官方启动器开始一个新的Astro项目。或者，你可以[从 GitHub 上任何现有的 Astro 存储库开始一个新项目](/zh-cn/install/auto/#入门模板)。
```suggestion
你可以向`create astro`命令传递一个`--template`参数，以一个我们的官方启动器开始一个新的 Astro 项目。或者，你可以[从 GitHub 上任何现有的 Astro 存储库开始一个新项目](/zh-cn/install/auto/#入门模板)。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-docusaurus.mdx
> +添加我们的 MDX 集成并带来你现有的内容文件，创建[MDX页面](/zh-cn/guides/markdown-content/)。你仍然可以通过将这些文件直接复制到 Astro 中的`src/pages/`来利用[基于文件的路由](/zh-cn/core-concepts/routing/)，这是你现在使用的同一个文件夹。创建与你现有的 Docusaurus 项目对应的名称的文件夹，你应该能
```suggestion
添加我们的 MDX 集成并带来你现有的内容文件，创建 [MDX页面](/zh-cn/guides/markdown-content/)。你仍然可以通过将这些文件直接复制到 Astro 中的`src/pages/`来利用[基于文件的路由](/zh-cn/core-concepts/routing/)，这是你现在使用的同一个文件夹。创建与你现有的 Docusaurus 项目对应的名称的文件夹，你应该能保留你现有的 URL。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-docusaurus.mdx
> +Docusaurus 可能处理了你的许多网站布局和元数据。你可能希望阅读有关[构建 Astro 布局作为Markdown和MDX的页面包装器](/zh-cn/core-concepts/layouts/#markdownmdx-布局)，看看如何在Astro中自己管理模板，包括你的页面`<head>`。
```suggestion
Docusaurus 可能处理了你的许多网站布局和元数据。你可能希望阅读有关[构建 Astro 布局作为 Markdown 和 MDX 的页面包装器](/zh-cn/core-concepts/layouts/#markdownmdx-布局)，看看如何在 Astro 中自己管理模板，包括你的页面`<head>`。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-eleventy.mdx
> +- Astro 和 Eleventy 都允许你使用[无头（headless）CMS，API或Markdown文件获取数据](/zh-cn/guides/data-fetching/)。你可以继续使用你喜欢的[内容创作](/zh-cn/guides/content/)系统，并能保留你现有的内容。
```suggestion
- Astro 和 Eleventy 都允许你使用[无头（headless）CMS，API 或 Markdown 文件获取数据](/zh-cn/guides/data-fetching/)。你可以继续使用你喜欢的[内容创作](/zh-cn/guides/content/)系统，并能保留你现有的内容。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-eleventy.mdx
> +- Eleventy 支持多种模板语言。Astro 支持[包含来自几个流行的JS框架（例如React，Svelte，Vue，Solid）的组件](/zh-cn/core-concepts/framework-components/)，但大部分页面模板都使用[Astro布局，页面和组件](/zh-cn/core-concepts/astro-components/)。
```suggestion
- Eleventy 支持多种模板语言。Astro 支持[包含来自几个流行的JS框架（例如 React，Svelte，Vue，Solid）的组件](/zh-cn/core-concepts/framework-components/)，但大部分页面模板都使用 [Astro布局，页面和组件](/zh-cn/core-concepts/astro-components/)。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-eleventy.mdx
> +- 在Eleventy中，必须手动配置CSS，JavaScript和其他资产的捆绑。[Astro为你提供开箱即用的处理方式](/zh-cn/concepts/why-astro/#易于使用)。
```suggestion
- 在Eleventy中，必须手动配置 CSS，JavaScript 和其他资产的打包。[Astro 为你提供开箱即用的处理方式](/zh-cn/concepts/why-astro/#易于使用)。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-eleventy.mdx
> +你可以向`create astro`命令传递一个`--template`参数，以使用我们的官方启动器开始一个新的Astro项目。或者，你可以[从GitHub上的任何现有Astro库开始一个新项目](/zh-cn/install/auto/#入门模板)
```suggestion
你可以向`create astro`命令传递一个`--template`参数，以使用我们的官方启动器开始一个新的 Astro 项目。或者，你可以[从 GitHub 上的任何现有 Astro 库开始一个新项目](/zh-cn/install/auto/#入门模板)
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-eleventy.mdx
> +将你现有的 Markdown（或MDX，通过我们可选的集成）文件作为内容，[创建Markdown或MDX页面](/zh-cn/guides/markdown-content/)。
```suggestion
将你现有的 Markdown（或MDX，通过我们可选的集成）文件作为内容，[创建 Markdown 或 MDX 页面](/zh-cn/guides/markdown-content/)。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-eleventy.mdx
> +你的Eleventy项目允许你使用各种模板语言来构建你的网站。在Astro项目中，你的页面模板大部分将使用Astro组件，这些组件可以作为UI元素，布局甚至完整的页面。你可能想要探索[Astro的组件语法](/zh-cn/core-concepts/astro-components/)，看看如何使用组件在Astro中进行模板化。
```suggestion
你的 Eleventy 项目允许你使用各种模板语言来构建你的网站。在 Astro 项目中，你的页面模板大部分将使用Astro 组件，这些组件可以作为 UI 元素，布局甚至完整的页面。你可能想要探索[Astro 的组件语法](/zh-cn/core-concepts/astro-components/)，看看如何使用组件在 Astro 中进行模板化。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-eleventy.mdx
> +要转换其他类型的网站，例如作品集或文档站点，请在[astro.new](https://astro.new)上查看更多官方启动器模板。你会找到每个项目的GitHub仓库的链接，以及一键链接到 StackBlitz，CodeSandbox 和 Gitpod 在线开发环境中的有效项目。
```suggestion
要转换其他类型的网站，例如作品集或文档站点，请在 [astro.new](https://astro.new) 上查看更多官方启动器模板。你会找到每个项目的 GitHub 仓库的链接，以及一键链接到 StackBlitz，CodeSandbox 和 Gitpod 在线开发环境中的有效项目。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +- [本地文件数据](/zh-cn/guides/imports/)：Gatsby 使用 GraphQL 从你的项目文件中检索数据。Astro 使用 ESM imports 和顶层等待函数（例如 [`Astro.glob()`](/zh-cn/guides/imports/#astroglob), [`getCollection()`](/zh-cn/guides/content-collect
```suggestion
- [本地文件数据](/zh-cn/guides/imports/)：Gatsby 使用 GraphQL 从你的项目文件中检索数据。Astro 使用 ESM imports 和顶层 await 函数（例如 [`Astro.glob()`](/zh-cn/guides/imports/#astroglob), [`getCollection()`](/zh-cn/guides/content-collections/#querying-collections)）从你的项目文件中导入数据。你可以手动向你的 Astro 项目添加 GraphQL，但默认情况下不包含它。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +6. 删除任何 GraphQ L查询。改为使用 import 和[`Astro.glob()`](/zh-cn/reference/api-reference/#astroglob)语句来查询你的本地文件。
```suggestion
6. 删除任何 GraphQL 查询。改为使用 import 和[`Astro.glob()`](/zh-cn/reference/api-reference/#astroglob)语句来查询你的本地文件。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +4. 使用[`Astro.props`](/zh-cn/reference/api-reference/#astroprops)来访问之前传递给你的Gatsby函数的任何其他 props。
```suggestion
4. 使用[`Astro.props`](/zh-cn/reference/api-reference/#astroprops)来访问之前传递给你的 Gatsby 函数的任何其他 props。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +2. 将任何[ Gatsby 或 JSX 语法转换为 Astro 语法](#参考转换为-astro-语法)或HTML网络标准。例如 `<Link to="">`， `{children}`和 `className`。
```suggestion
2. 将任何[ Gatsby 或 JSX 语法转换为 Astro 语法](#参考转换为-astro-语法)或 HTML web 标准。例如 `<Link to="">`， `{children}`和 `className`。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +查看[Gatsby's Blog启动模板转换步骤示例](#引导示例gatsby-布局转换为-astro)
```suggestion
查看 [Gatsby's Blog 启动模板转换步骤示例](#引导示例gatsby-布局转换为-astro)
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +Astro 对 Markdown 有内建支持，并对 MDX 文件有可选集成。你现有的 [Markdown 和 MDX 文件](/zh-cn/guides/markdown-content/) 可以重用，但可能需要对它们的 frontmatter 进行一些调整，如添加 [Astro 的特殊 `layout` frontmatter 属性](/zh-cn/core-concepts/layouts/
```suggestion
Astro 对 Markdown 有内置支持，并对 MDX 文件有可选集成。你现有的 [Markdown 和 MDX 文件](/zh-cn/guides/markdown-content/) 可以重用，但可能需要对它们的 frontmatter 进行一些调整，如添加 [Astro 的特殊 `layout` frontmatter 属性](/zh-cn/core-concepts/layouts/#markdownmdx-布局)。它们也可以被放置在 `src/pages/` 中以利用自动的基于文件的路由。
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +   条件性地根据页面路由和标题在 Astro 中渲染一个头部：
```suggestion
   根据 Astro 中页面路由和标题条件性地渲染 header：
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gatsby.mdx
> +6. 为了测试条件头部，使用相同的模式创建第二个页面 `about.astro`：
```suggestion
6. 为了测试条件 header，使用相同的模式创建第二个页面 `about.astro`：
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gitbook.mdx
> +title: 从 GitBook 迁移到
```suggestion
title: 从 GitBook 迁移到 Astro
```

2023-08-01 00:56 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-gridsome.mdx
> +将你现有的 Markdown 文件（或MDX文件，如果你选择了我们的可选集成）作为内容[创建Markdown或MDX页面](/zh-cn/guides/markdown-content/)。
```suggestion
将你现有的 Markdown 文件（或 MDX 文件，如果你选择了我们的可选集成）作为内容[创建 Markdown 或 MDX 页面](/zh-cn/guides/markdown-content/)。
```

2023-08-02 01:33 UTC, liruifengv approved these changes
LGTM

2023-08-02 11:05 UTC, Yan-Thomas approved these changes
LGTM! Amazing work 🚀

2023-08-02 11:05 UTC, merged