i18n(zh-cn): update images.mdx
withastro/docs pull request #3913
Opened 2023-07-28 09:02 UTC by mingXta

#### What kind of changes does this PR include?
Translated content

#### Description
update images.mdx

2023-07-28 13:01 UTC, mingXta commented
@liruifengv

2023-07-31 01:13 UTC, 100gle requested changes
有一些小地方可能需要修改和调整

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +**下面的一些建议可能与实验性标志不兼容。如果你正在使用 `astro:assets` 请参考资源页面.**
```suggestion
**下面的一些建议可能与实验性标志不兼容。如果你正在使用 `astro:assets` 请参考资源页面。**
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +src 属性是必需的，其格式取决于图像的存储位置以及您是否启用了对资产的实验性支持：
```suggestion
src 属性是必需的，其格式取决于图像的存储位置以及你是否启用了对资源的实验性支持：
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +如果你无法将图片保留在 `public/` 中，我们建议启用 [资产的实验性支持](/zh-cn/guides/assets/), 或使用 `.mdx` 文件格式，该格式允许你将导入的组件与类似 Markdown 的语法结合起来。使用 [MDX integration](/zh-cn/guides/integrations-guide/mdx/) 向 Astro 添加对 MDX 的支持。
```suggestion
如果你无法将图片保留在 `public/` 中，我们建议启用 [资源的实验性支持](/zh-cn/guides/assets/), 或使用 `.mdx` 文件格式，该格式允许你将导入的组件与类似 Markdown 的语法结合起来。使用 [MDX 集成](/zh-cn/guides/integrations-guide/mdx/) 向 Astro 添加对 MDX 的支持。
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +存储在 `src/`中的图像可以由组件（`.astro`，`.mdx`和其他UI框架）使用，但不能在Markdown文档中使用。
```suggestion
存储在 `src/`中的图像可以由组件（`.astro`，`.mdx`和其他 UI 框架）使用，但不能在 Markdown 文档中使用。
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +如果您必须使用 Markdown 文档，我们建议您将图像保存在 ['public/']（#public） 中或 [远程](#using-images-from-a-cms-or-cdn)存储他们。
```suggestion
如果您必须使用 Markdown 文档，我们建议你将图像保存在 ['public/']（#public） 中或 [远程](#使用cms-或-cdn-上的图片) 存储他们。
```

注意锚点要和你翻译的中文标题相对应上，如要必要，可以在安装了 Astro 依赖之后通过 `pnpm run dev` 运行查看

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +Astro v3将不在主动支持 [`@astrojs/image`](https://github.com/withastro/astro/tree/main/packages/integrations/image)集成
```suggestion
Astro v3 将不再主动支持 [`@astrojs/image`](https://github.com/withastro/astro/tree/main/packages/integrations/image) 集成
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +我们建议您尽早删除它，并使用将内置在 `astro@3.0` 中的实验性 `astro:assets` 模块。
```suggestion
我们建议你尽早删除它，并使用将内置在 `astro@3.0` 中的实验性 `astro:assets` 模块。
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +请按照 [资源（实验性） 使用指南](/zh-cn/guides/assets/) 开始使用新的图片解决方案！
```suggestion
请按照 [资源（实验性）使用指南](/zh-cn/guides/assets/) 开始使用新的图片解决方案！
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +Image CDN 可与 Astro 配合使用。使用图片的完整网址作为 `<img>` 标签或 Markdown 中的“src”属性。
```suggestion
Image CDN 可与 Astro 配合使用，可将图片的完整网址作为 `<img>` 标签中的 `src` 属性或 Markdown 标记
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +并非所有用户都能以相同的方式查看图片，因此在使用图片时可访问性是一个特别重要的问题。使用 alt 属性为图片提供 [描述性替代文本](https://www.w3.org/WAI/tutorials/images/)。
```suggestion
并非所有用户都能以相同的方式查看图片，因此在使用图片时可访问性是一个特别重要的问题。使用 `alt` 属性为图片提供 [描述性替代文本](https://www.w3.org/WAI/tutorials/images/)。
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +此属性对于映像集成的`<Image />`和`<图片/>`组件是必需的，如果未提供替代文本，这些组件将引发错误。
```suggestion
此属性对于映像集成的 `<Image />` 和 `<Picture/>` 组件是必需的，如果未提供替代文本，这些组件将引发错误。
```

2023-07-31 01:13 UTC, 100gle commented on src/content/docs/zh-cn/guides/images.mdx
> +如果图像只是装饰性的（即无助于理解页面）请设置`alt=""`，以便屏幕阅读器知道忽略图像。
```suggestion
如果图像只是装饰性的（即无助于理解页面）请设置 `alt=""`，以便屏幕阅读器知道忽略该图像。
```

2023-07-31 01:41 UTC, mingXta commented
> 有一些小地方可能需要修改和调整

感谢

2023-07-31 02:02 UTC, 100gle commented
LGTM!

2023-07-31 03:00 UTC, 100gle approved these changes

2023-07-31 14:00 UTC, Yan-Thomas commented on src/content/docs/zh-cn/guides/images.mdx
> +如果您必须使用 Markdown 文档，我们建议你将图像保存在 ['public/']（#public） 中或 [远程](#使用cms-或-cdn-上的图片) 存储他们。
```suggestion
如果您必须使用 Markdown 文档，我们建议你将图像保存在 ['public/']（#public） 中或 [远程](#cmsやcdn上の画像利用) 存储他们。
```

2023-07-31 14:08 UTC, Yan-Thomas commented on src/content/docs/zh-cn/guides/images.mdx
> +如果您必须使用 Markdown 文档，我们建议你将图像保存在 ['public/']（#public） 中或 [远程](#cmsやcdn上の画像利用) 存储他们。
```suggestion
如果您必须使用 Markdown 文档，我们建议你将图像保存在 ['public/']（#public） 中或 [远程](#使用-cms-或-cdn-上的图片) 存储他们。
```

2023-07-31 14:18 UTC, Yan-Thomas approved these changes
LGTM! Thanks for the great work here, peeps! 🚀

2023-07-31 14:19 UTC, merged