i18n(zh-cn): update `guides/troubleshooting.mdx`
withastro/docs pull request #3926
Opened 2023-07-28 17:12 UTC by dorasans

#### What kind of changes does this PR include?

- update the translation

#### Description
- update `guides/troubleshooting.mdx`

2023-07-28 17:15 UTC, dorasans commented
@liruifengv pls review

2023-07-30 02:38 UTC, 100gle requested changes

2023-07-30 02:38 UTC, 100gle commented on src/content/docs/zh-cn/guides/troubleshooting.mdx
> +### 在单一代码库中为 Astro 添加依赖。
```suggestion
### 在单一代码库中为 Astro 添加依赖
```
标题里面可以不用加句号

2023-07-30 02:38 UTC, 100gle commented on src/content/docs/zh-cn/guides/troubleshooting.mdx
> +你可以使用 [astro.new](https://astro.new) 来一键创建一个新的Astro项目。对于最小化复现，我们强烈建议从在 [StackBlitz](https://stackblitz.com) 上运行的最小（空白）示例开始，尽量少添加额外的代码。
```suggestion
你可以使用 [astro.new](https://astro.new) 来一键创建一个新的 Astro 项目。对于最小化复现，我们强烈建议在 [StackBlitz](https://stackblitz.com) 上运行的最小（空白）示例开始，尽量少添加额外的代码。
```

2023-07-30 02:38 UTC, 100gle commented on src/content/docs/zh-cn/guides/troubleshooting.mdx
> +请注意，并非所有问题都可以在StackBlitz中复现。例如，你的问题可能依赖于特定的环境或包管理器，或者可能涉及到 HTML 流式传输，而这在 StackBlitz 中是不支持的。在这种情况下，请使用命令行工具（CLI）创建一个新的最小化的（空白的）Astro项目来复现问题，并将其上传到 GitHub 代码库中。提供一个指向你最小化复现的 GitHub 代码库的链接，而不是分享一个 Stack
```suggestion
请注意，并非所有问题都可以在 StackBlitz 中复现。例如，你的问题可能依赖于特定的环境或包管理器，或者可能涉及到 HTML 流式传输，而这在 StackBlitz 中是不支持的。在这种情况下，请使用命令行工具（CLI）创建一个新的最小化的（空白的）Astro 项目来复现问题，并将其上传到 GitHub 代码库中。提供一个指向你最小化复现的 GitHub 代码库的链接，而不是分享一个 StackBlitz 的 URL。
```

2023-07-30 02:38 UTC, 100gle commented on src/content/docs/zh-cn/guides/troubleshooting.mdx
> +前往 GitHub上 相应的 Astro 代码库去创建一个新的问题。大多数代码库都有一个问题模板，会询问问题或要求提供信息以便提交报告。遵循这些模板很重要，因为如果你没有提供我们需要的信息，我们就不得不向你询问... 这样会导致你的问题得不到及时处理！
```suggestion
前往 GitHub上 相应的 Astro 代码库去创建一个新的问题。大多数代码库都有一个问题模板，会询问问题或要求提供信息以便提交报告。遵循这些模板很重要，因为如果你没有提供我们需要的信息，我们就不得不向你询问……这样会导致你的问题得不到及时处理！
```

2023-07-30 03:03 UTC, 100gle commented
LGTM

2023-07-30 18:08 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-07-30 18:08 UTC, merged