i18n(zh-cn): translate `guides/cms/hygraph.mdx`
withastro/docs pull request #3938
Opened 2023-07-29 06:01 UTC by miroim

#### What kind of changes does this PR include?

- Translated content

#### Description

translate `\guides\cms\hygraph.mdx`

2023-07-29 06:02 UTC, miroim commented
cc: @liruifengv

2023-07-31 00:48 UTC, 100gle requested changes

2023-07-31 00:48 UTC, 100gle commented on src/content/docs/zh-cn/guides/cms/hygraph.mdx
> +title: Hygraph & Astro
```suggestion
title: Hygraph 与 Astro
```

2023-07-31 00:48 UTC, 100gle commented on src/content/docs/zh-cn/guides/cms/hygraph.mdx
> +[Hygraph](https://hygraph.com/) 是一个无头 CMS（Content Management System，内容管理系统）。它提供了一个用于 Astro 获取内容的 GraphQL 端点。
```suggestion
[Hygraph](https://hygraph.com/) 是一个无头的 CMS（Content Management System，内容管理系统）。它提供了一个用于 Astro 获取内容的 GraphQL 端点。
```

2023-07-31 02:34 UTC, 100gle commented
LGTM!

2023-07-31 03:00 UTC, 100gle approved these changes

2023-07-31 13:27 UTC, Yan-Thomas approved these changes
LGTM! Thanks @miroim 💜

2023-07-31 13:27 UTC, merged