i18n(zh-cn): translate `guides/cms/keystonejs.mdx`
withastro/docs pull request #3939
Opened 2023-07-29 06:58 UTC by miroim

#### What kind of changes does this PR include?

- Translated content

#### Description

translate `\guides\cms\keystonejs.mdx`

2023-07-29 06:58 UTC, miroim commented
cc: @liruifengv

2023-07-31 00:46 UTC, 100gle requested changes

2023-07-31 00:46 UTC, 100gle commented on src/content/docs/zh-cn/guides/cms/keystonejs.mdx
> +title: KeystoneJS & Astro
```suggestion
title: KeystoneJS 与 Astro
```

2023-07-31 00:46 UTC, 100gle commented on src/content/docs/zh-cn/guides/cms/keystonejs.mdx
> +[KeystoneJS](https://keystonejs.com/) 是一个开源无头 CMS（Content Management System，内容管理系统）。只需描述你的数据结构，即可使用 KeystoneJS 的 GraphQL API 和数据管理界面。
```suggestion
[KeystoneJS](https://keystonejs.com/) 是一个开源无头的 CMS（Content Management System，内容管理系统）。只需描述你的数据结构，即可使用 KeystoneJS 的 GraphQL API 和数据管理界面。
```

2023-07-31 02:38 UTC, 100gle commented
LGTM

2023-07-31 03:01 UTC, 100gle approved these changes

2023-07-31 12:47 UTC, Yan-Thomas approved these changes
LGTM! Thanks @miroim 🙌

2023-07-31 12:47 UTC, merged