i18n(zh-cn): translate `guides/cms/payload.mdx`
withastro/docs pull request #3940
Opened 2023-07-29 08:04 UTC by miroim

#### What kind of changes does this PR include?

- Translated content

#### Description

translate `\guides\cms\payload.mdx`

2023-07-29 08:05 UTC, miroim commented
cc: @liruifengv

2023-07-29 08:05 UTC, miroim commented
cc: @liruifengv

2023-07-31 06:29 UTC, liruifengv requested changes

2023-07-31 06:29 UTC, liruifengv commented on src/content/docs/zh-cn/guides/cms/payload.mdx
> +[PayloadCMS](https://payloadcms.com/) 是一个开源无头的 CMS（Content Management System，内容管理系统），可以用来为你的 Astro 项目提供内容。
```suggestion
[PayloadCMS](https://payloadcms.com/) 是一个开源的 headless CMS（Content Management System，内容管理系统），可以用来为你的 Astro 项目提供内容。
```

2023-07-31 06:29 UTC, liruifengv commented on src/content/docs/zh-cn/guides/cms/payload.mdx
> +创建一个页面 `src/pages/post/[slug].astro` 为每一篇文章[动态生成一个页面](/zh-cn/core-concepts/routing/#dynamic-routes)。
```suggestion
创建一个页面 `src/pages/post/[slug].astro` 为每一篇文章[动态生成一个页面](/zh-cn/core-concepts/routing/#动态路由)。
```

2023-08-01 08:04 UTC, liruifengv approved these changes
LGTM

2023-08-01 12:29 UTC, merged