i18n(zh-cn): translate from-nuxtjs.mdx
withastro/docs pull request #3962
Opened 2023-07-31 00:56 UTC by woshierha

#### What kind of changes does this PR include?

- Translated content

#### Description
- translate from-nuxtjs.mdx

2023-07-31 04:36 UTC, 100gle commented
@woshierha 翻译里面有一些 `zh-cn` 链接的锚点引用需要你一并修改成中文版本，具体的中文版本锚点名称你可以直接参考 [astro 官方文档](https://docs.astro.build/zh-cn/getting-started/)，或者是在本地运行最新的文档之后再复制并修改

2023-07-31 05:55 UTC, woshierha commented
> @woshierha 翻译里面有一些 `zh-cn` 链接的锚点引用需要你一并修改成中文版本，具体的中文版本锚点名称你可以直接参考 [astro 官方文档](https://docs.astro.build/zh-cn/getting-started/)，或者是在本地运行最新的文档之后再复制并修改
我是把之前链接里的EN都改成zh-cn了，但是有些可能目前还没有翻译完的版本的所以连接上还是显示EN，所以这个链接格式是可能会变吗？

2023-07-31 06:04 UTC, woshierha commented
> @woshierha 翻译里面有一些 `zh-cn` 链接的锚点引用需要你一并修改成中文版本，具体的中文版本锚点名称你可以直接参考 [astro 官方文档](https://docs.astro.build/zh-cn/getting-started/)，或者是在本地运行最新的文档之后再复制并修改

http://localhost:3000/zh-cn/guides/integrations-guide/vue/ 比如这个我已经改成zh-cn了但是由于目前更新的版本还没有这个文件所以他会连接到英文版的 源文件都已经替换成zh-cn了

2023-07-31 06:09 UTC, 100gle commented
> > @woshierha 翻译里面有一些 `zh-cn` 链接的锚点引用需要你一并修改成中文版本，具体的中文版本锚点名称你可以直接参考 [astro 官方文档](https://docs.astro.build/zh-cn/getting-started/)，或者是在本地运行最新的文档之后再复制并修改
> 
> http://localhost:3000/zh-cn/guides/integrations-guide/vue/ 比如这个我已经改成zh-cn了但是由于目前更新的版本还没有这个文件所以他会连接到英文版的 源文件都已经替换成zh-cn了

我其实指的是 `#` 锚点后面的部分，有些已经存在对应中文标题的就需要替换的

<img width="908" alt="SCR-20230731-moug" src="https://github.com/withastro/docs/assets/36526527/bfb36457-265b-48d1-8767-4e54d94c3a7b">

2023-07-31 06:21 UTC, woshierha commented
> > > @woshierha 翻译里面有一些 `zh-cn` 链接的锚点引用需要你一并修改成中文版本，具体的中文版本锚点名称你可以直接参考 [astro 官方文档](https://docs.astro.build/zh-cn/getting-started/)，或者是在本地运行最新的文档之后再复制并修改
> > 
> > 
> > http://localhost:3000/zh-cn/guides/integrations-guide/vue/ 比如这个我已经改成zh-cn了但是由于目前更新的版本还没有这个文件所以他会连接到英文版的 源文件都已经替换成zh-cn了
> 
> 我其实指的是 `#` 锚点后面的部分，有些已经存在对应中文标题的就需要替换的
> 
> <img alt="SCR-20230731-moug" width="908" src="https://user-images.githubusercontent.com/36526527/257130116-bfb36457-265b-48d1-8767-4e54d94c3a7b.png">

哦哦好滴 我更新下 谢谢啦

2023-07-31 08:08 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +2. 将任意的 [Nuxt 或 Vue 语法更改为 Astro](#reference-convert-nuxtjs-syntax-to-astro) 或转换为 HTML Web 标准。包括`<NextLink>`，`:class`，`{{variable}}`和 `v-if`等。
翻译内容里有多处是直接使用 `#` 来对同一篇内容里的不同小节进行引用，比如这里的 `#reference-convert-nuxtjs-syntax-to-astro`，这需要你同样改成对应小节的中文标题方便读者跳转；不过你可能需要注意一下标题最终的锚点内容是什么，建议在本地运行 astro docs 之后再查看并复制修改

2023-07-31 23:09 UTC, woshierha commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +2. 将任意的 [Nuxt 或 Vue 语法更改为 Astro](#reference-convert-nuxtjs-syntax-to-astro) 或转换为 HTML Web 标准。包括`<NextLink>`，`:class`，`{{variable}}`和 `v-if`等。
好滴 修改了

2023-08-01 00:58 UTC, 100gle requested changes
内容方面大部分都没什么问题了，就是有些小地方可能还要调整一下，最主要的是源码中的注释部分，需要一同翻译成中文。因为有好几个地方我就不一一列出来了，调整完之后基本上就没问题了~

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +- [页面路由](/zh-cn/core-concepts/astro-pages/#基于文件的路由)： Nuxt 使用 `vue-router` 进行 SPA 路由, 并且使用 `vue-meta` 来管理 `<head>`。在 Astro 中，你将创建单独的 HTML 页面路由，并直接控制页面的 `<head>`，或者在布局组件中控制。
```suggestion
- [页面路由](/zh-cn/core-concepts/astro-pages/#基于文件的路由)： Nuxt 使用 `vue-router` 进行 SPA 路由，并且使用 `vue-meta` 来管理 `<head>`。在 Astro 中，你将创建单独的 HTML 页面路由，并直接控制页面的 `<head>`，或者在布局组件中控制。
```

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +使用你的包管理器的 `create astro` 来启动Astro的CLI向导，或者从 [Astro 主题展示](https://astro.build/themes) 中选择一个社区主题。
```suggestion
使用你的包管理器的 `create astro` 来启动 Astro 的 CLI 向导，或者从 [Astro 主题展示](https://astro.build/themes) 中选择一个社区主题。
```

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +访问 https://astro.new 以获取官方启动模板的完整列表，以及能在 StackBlitz、CodeSandbox或 Gitpod 中打开新项目的链接。
```suggestion
访问 https://astro.new 以获取官方启动模板的完整列表，以及能在 StackBlitz、CodeSandbox 或 Gitpod 中打开新项目的链接。
```

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +    <!-- Wrap the slot element with your existing layout templating -->
通常源码部分的内容不需要翻译，但是如果碰到有注释的情况下需要**对注释进行翻译**

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +<!-- Also support component props -->
同注释翻译

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +<!-- Also support component props -->
同注释翻译

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +<!-- Or -->
同注释翻译

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +          // Axios is required here unless you're using Node 18
同注释翻译

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +<!-- Your template here -->
同注释翻译

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +<!-- Your template here -->
同注释翻译

2023-08-01 00:58 UTC, 100gle commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +将任何 [Nuxt `<nuxt-img/>` 或 `<nuxt-picture/>` 组件](https://image.nuxtjs.org/components/nuxt-img) 转换为 [Astro 的图像集成组件](/zh-cn/guides/images/#astro-的图片集成)，或者转换为标准的HTML `<img>` 标签。
```suggestion
将任何 [Nuxt `<nuxt-img/>` 或 `<nuxt-picture/>` 组件](https://image.nuxtjs.org/components/nuxt-img) 转换为 [Astro 的图像集成组件](/zh-cn/guides/images/#astro-的图片集成)，或者转换为标准的 HTML `<img>` 标签。
```

2023-08-01 23:14 UTC, woshierha commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +<!-- Your template here -->
好的好的，更新了

2023-08-02 00:48 UTC, 100gle approved these changes
Thanks for the great work!

2023-08-02 13:34 UTC, 100gle commented
@Yan-Thomas the CI seems to be failed because the broken fragment link. I will update the server-side rendering guide tomorrow then fix it.

2023-08-03 00:44 UTC, liruifengv commented
> 

https://github.com/withastro/docs/pull/4024

2023-08-03 11:35 UTC, Yan-Thomas commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nuxtjs.mdx
> +- Astro 项目可以是 SSG（静态网站生成）或 [支持页面级预渲染的SSR（服务端渲染）](/zh-cn/guides/server-side-rendering/#configuring-individual-routes)。
```suggestion
- Astro 项目可以是 SSG（静态网站生成）或 [支持页面级预渲染的SSR（服务端渲染）](/zh-cn/guides/server-side-rendering/#配置单个路由)。
```

2023-08-03 11:51 UTC, Yan-Thomas approved these changes
LGTM! Thanks everyone 💜

2023-08-03 11:52 UTC, merged