i18n(zh-cn): Update `markdown-content.mdx` `rss.mdx` `server-side-rendering.mdx`
withastro/docs pull request #4024
Opened 2023-08-02 14:33 UTC by zhengbangbo

#### What kind of changes does this PR include?

- Translated content

#### Description

Updated three files on the `guides` directory
- markdown-content.mdx
- rss.mdx
- server-side-rendering.mdx

2023-08-02 14:35 UTC, zhengbangbo commented
@liruifengv pls review

2023-08-03 00:52 UTC, liruifengv requested changes

2023-08-03 00:52 UTC, liruifengv commented on src/content/docs/zh-cn/guides/markdown-content.mdx
> +Astro 将 `id` 属性注入到 Markdown 和 MDX 文件中的所有标题元素（`<h1>` 到 `<h6>`），并提供 `getHeadings()` 实用程序，用于在 [Markdown 导出的属性](#exported-properties) 中检索这些 ID。
```suggestion
Astro 将 `id` 属性注入到 Markdown 和 MDX 文件中的所有标题元素（`<h1>` 到 `<h6>`），并提供 `getHeadings()` 实用程序，用于在 [Markdown 导出的属性](#导出的属性) 中检索这些 ID。
```
There has a broken link.

2023-08-03 00:52 UTC, liruifengv commented on src/content/docs/zh-cn/guides/markdown-content.mdx
> +如果您使用的是 [内容集合](/zh-cn/guides/content-collections/)，请参阅[“使用 Remark 修改 Frontmatter”](/zh-cn/guides/content-collections/#modifying-frontmatter-with-remark)。
```suggestion
如果你使用的是 [内容集合](/zh-cn/guides/content-collections/)，请参阅[“使用 Remark 修改 Frontmatter”](/zh-cn/guides/content-collections/#modifying-frontmatter-with-remark)。
```

2023-08-03 01:08 UTC, liruifengv requested changes
The `from-nextjs.mdx` page has a broken link due to this change. Can you update the `from-nextjs.mdx` page?

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/server-side-rendering.mdx
> +在此过程中，浏览器以增量方式使用 HTML：解析、呈现到 DOM 中和绘制。无论您是否有意流式传输 HTML，都会发生这种情况。网络状况可能会导致大型文档下载缓慢，等待数据获取可能会阻止页面呈现。
```suggestion
在此过程中，浏览器以增量方式使用 HTML：解析、呈现到 DOM 中和绘制。无论你是否有意流式传输 HTML，都会发生这种情况。网络状况可能会导致大型文档下载缓慢，等待数据获取可能会阻止页面呈现。
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/server-side-rendering.mdx
> +将 `await` 调用移动到较小的组件中，您可以利用 Astro 的流式传输。使用以下组件执行数据获取，Astro 可以先渲染一些 HTML，例如标题，然后在数据准备就绪时呈现段落。
```suggestion
将 `await` 调用移动到较小的组件中，你可以利用 Astro 的流式传输。使用以下组件执行数据获取，Astro 可以先渲染一些 HTML，例如标题，然后在数据准备就绪时呈现段落。
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/server-side-rendering.mdx
> +您还可以直接在模板中包含 promises。它不会阻止整个组件，而是并行解析 promise，并且只阻止它后面的标记。
```suggestion
你还可以直接在模板中包含 promises。它不会阻止整个组件，而是并行解析 promise，并且只阻止它后面的标记。
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/server-side-rendering.mdx
> +默认情况下，Astro 将所有页面构建到一个名为 `entry.mjs` 的单个文件中。您可以在构建选项中配置 [`split`](/zh-cn/reference/configuration-reference/#buildsplit)，改为为每个页面发出一个文件：
```suggestion
默认情况下，Astro 将所有页面构建到一个名为 `entry.mjs` 的单个文件中。你可以在构建选项中配置 [`split`](/zh-cn/reference/configuration-reference/#buildsplit)，改为为每个页面发出一个文件：
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/markdown-content.mdx
> +你可以在 Astro 中的特殊的 `src/content/` 文件夹中管理您的 Markdown 和 MDX 文件。[内容集合](/zh-cn/guides/content-collections/) 可帮助你组织内容、验证你的 frontmatter，并在处理你的内容时提供自动 TypeScript 类型安全。
```suggestion
你可以在 Astro 中的特殊的 `src/content/` 文件夹中管理你的 Markdown 和 MDX 文件。[内容集合](/zh-cn/guides/content-collections/) 可帮助你组织内容、验证你的 frontmatter，并在处理你的内容时提供自动 TypeScript 类型安全。
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/markdown-content.mdx
>  要访问 Markdown 内容，请将 `<Content/>` 组件传递给 Astro 页面的 `props`。 然后，您可以从 `Astro.props` 中检索该组件并在页面模板中渲染它。
```suggestion
要访问 Markdown 内容，请将 `<Content/>` 组件传递给 Astro 页面的 `props`。 然后，你可以从 `Astro.props` 中检索该组件并在页面模板中渲染它。
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/markdown-content.mdx
> +你可以通过添加注入 `id` 属性的 rehype 插件（例如 `rehype-slug`）来自定义这些标题ID。您的自定义 ID（而不是 Astro 的默认值）将反映在 HTML 输出和 `getHeadings()` 返回的项目中。
```suggestion
你可以通过添加注入 `id` 属性的 rehype 插件（例如 `rehype-slug`）来自定义这些标题ID。你的自定义 ID（而不是 Astro 的默认值）将反映在 HTML 输出和 `getHeadings()` 返回的项目中。
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/markdown-content.mdx
> +默认情况下，Astro 会在您的 rehype 插件运行后注入 `id` 属性。如果你的自定义 rehype 插件之一需要访问 Astro 注入的 ID，你可以直接导入和使用 Astro 的 `rehypeHeadingIds` 插件。确保在任何依赖它的插件之前添加 `rehypeHeadingIds`：
```suggestion
默认情况下，Astro 会在你的 rehype 插件运行后注入 `id` 属性。如果你的自定义 rehype 插件之一需要访问 Astro 注入的 ID，你可以直接导入和使用 Astro 的 `rehypeHeadingIds` 插件。确保在任何依赖它的插件之前添加 `rehypeHeadingIds`：
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/markdown-content.mdx
> +**Astro 不包含对远程 Markdown 的内置支持！** 要获取远程 Markdown 并将其呈现为 HTML，您需要从 npm 安装并配置自己的 Markdown 解析器。 这将**不会**从您配置的 Astro 的内置 Markdown 和 MDX 设置中继承。 在将其添加到您的项目之前，请确保您了解这些限制。
```suggestion
**Astro 不包含对远程 Markdown 的内置支持！** 要获取远程 Markdown 并将其呈现为 HTML，你需要从 npm 安装并配置自己的 Markdown 解析器。 这将**不会**从你配置的 Astro 的内置 Markdown 和 MDX 设置中继承。 在将其添加到你的项目之前，请确保你了解这些限制。
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/server-side-rendering.mdx
> +- **频繁更改的内容**：启用 SSR 可让您生成单个页面，而无需静态重建站点。当页面内容频繁更新时，这很有用。
```suggestion
- **频繁更改的内容**：启用 SSR 可让你生成单个页面，而无需静态重建站点。当页面内容频繁更新时，这很有用。
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/server-side-rendering.mdx
> +然后，您可以在任何页面或路由中使用 export 语句选择退出默认渲染行为：
```suggestion
然后，你可以在任何页面或路由中使用 export 语句选择退出默认渲染行为：
```

2023-08-03 01:08 UTC, liruifengv commented on src/content/docs/zh-cn/guides/server-side-rendering.mdx
> +`server` 和 `hybrid` 模式都允许服务器渲染的页面和端点，并将根据其默认模式渲染。但是，这两种模式都允许您将单个页面标记为 opt-out 此默认行为。
```suggestion
`server` 和 `hybrid` 模式都允许服务器渲染的页面和端点，并将根据其默认模式渲染。但是，这两种模式都允许你将单个页面标记为 opt-out 此默认行为。
```

2023-08-03 01:11 UTC, liruifengv reviewed
Some commit for en was missed. You can find them in https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/server-side-rendering.mdx?since=2023-04-04T13:31:19.000Z

Such as:
- https://github.com/withastro/docs/pull/3395/files
- https://github.com/withastro/docs/commit/961716b926d7f477049fc5d858a054c53a45556e

2023-08-03 08:45 UTC, zhengbangbo commented
Many linked documents in the `from-nextjs.mdx` file are not translated into Chinese

Such as:

- [.astro 文件的语法类似于 JSX (EN)](https://docs.astro.build/zh-cn/core-concepts/astro-syntax/#differences-between-astro-and-jsx)
- [条件渲染内容 (EN)](https://docs.astro.build/zh-cn/core-concepts/astro-syntax/#dynamic-html)
- [内容集合 (EN)](https://docs.astro.build/zh-cn/guides/content-collections/)
- [动态生成这些页面 (EN)](https://docs.astro.build/zh-cn/guides/content-collections/#generating-routes-from-content)
- [使用 Collections API 查询 (EN)](https://docs.astro.build/zh-cn/guides/content-collections/#querying-collections)
- [组件属性的完整列表 (EN)](https://docs.astro.build/zh-cn/guides/integrations-guide/image/#usage)

2023-08-03 09:54 UTC, liruifengv approved these changes
A little change. LGTM

2023-08-03 09:54 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-nextjs.mdx
> +访问 `astro:assets` 目前可以在实验标志下使用，并且是开始新 Astro 项目的推荐方式。如果你要迁移到 Astro v3.0 之前，我们建议你 [启用实验标志以使用 assets](/zh-cn/guides/assets/) 作为图像解决方案。
```suggestion
访问 `astro:assets` 目前可以在实验标志下使用，并且是开始新 Astro 项目的推荐方式。如果你要迁移到 Astro pre-v3.0，我们建议你 [启用实验标志以使用 assets](/zh-cn/guides/assets/) 作为图像解决方案。
```

2023-08-03 11:16 UTC, Yan-Thomas approved these changes
LGTM! Great work everyone 🚀

2023-08-03 11:16 UTC, merged