i18n(zh-cn): Translate `reference/errors/unknown-clierror.mdx`
withastro/docs pull request #4070
Opened 2023-08-05 01:40 UTC by 100gle

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

Translate `reference/errors/unknown-clierror.mdx` content to Chinese.

2023-08-07 01:10 UTC, liruifengv requested changes

2023-08-07 01:10 UTC, liruifengv commented on src/content/docs/zh-cn/reference/errors/unknown-clierror.mdx
> +## 哪里发送了错误?
```suggestion
## 哪里发生了错误?
```

2023-08-07 01:10 UTC, liruifengv commented on src/content/docs/zh-cn/reference/errors/unknown-clierror.mdx
> +如果你能稳定地重现这个错误，我们会很感激你能为此[提交一个问题](https://astro.build/issues/)。
```suggestion
如果你能稳定地重现这个错误，我们会很感激你能为此[创建一个 issue](https://astro.build/issues/)。
```

2023-08-08 00:44 UTC, liruifengv approved these changes
LGTM

2023-08-08 17:08 UTC, Yan-Thomas approved these changes
LGTM!

2023-08-08 17:08 UTC, merged