i18n(es): Translate `from-create-react-app.mdx`
withastro/docs pull request #4073
Opened 2023-08-05 01:55 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translate `from-create-react-app.mdx`

2023-08-05 17:05 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo unas pequeñas sugerencias.

2023-08-05 17:05 UTC, dreyfus92 commented on src/content/docs/es/guides/migrate-to-astro/from-create-react-app.mdx
> +### Agrega los archivos de tu app existente
```suggestion
### Agrega los archivos de tu aplicación existente
```

2023-08-05 19:29 UTC, Waxer59 commented
Listo!, gracias por la revisión 🤠

2023-08-05 20:34 UTC, dreyfus92 approved these changes
LGTM ✅

2023-08-06 13:33 UTC, Yan-Thomas approved these changes
LGTM peeps, thanks for the great work 💜

2023-08-06 13:33 UTC, merged