i18n(zh-cn): update guides/integrations-guide/mdx.mdx
withastro/docs pull request #4074
Opened 2023-08-05 08:35 UTC by melon95

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content
- Translated content
- Changes to the docs site code
- Something else!

#### Description

- Closes # 
- What does this PR change? Give us a brief description.
- Did you change something visual? A before/after screenshot can be helpful.

2023-08-05 08:37 UTC, melon95 commented
@liruifengv

2023-08-07 01:43 UTC, liruifengv requested changes

2023-08-07 01:43 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
> +这是一个可选的配置设置，用于优化 MDX 输出，以便通过内部 rehype 插件加快构建和渲染速度。如果您的 MDX 文件较多，并注意到构建速度较慢，这可能会很有用。不过，该选项可能会生成一些未转义的 HTML，因此请确保您网站的交互式部分在启用该选项后仍能正常工作。
```suggestion
这是一个可选的配置设置，用于优化 MDX 输出，以便通过内部 rehype 插件加快构建和渲染速度。如果你的 MDX 文件较多，并注意到构建速度较慢，这可能会很有用。不过，该选项可能会生成一些未转义的 HTML，因此请确保你的网站的交互式部分在启用该选项后仍能正常工作。
```

2023-08-07 01:43 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
> +请注意，如果你的 MDX 文件[使用 `export const components = {...}` 配置自定义组件](/zh-cn/guides/markdown-content/#assigning-custom-components-to-html-elements)，则您无需手动配置此选项。优化器将自动检测它们。
```suggestion
请注意，如果你的 MDX 文件[使用 `export const components = {...}` 配置自定义组件](/zh-cn/guides/markdown-content/#assigning-custom-components-to-html-elements)，则无需手动配置此选项。优化器将自动检测它们。
```

2023-08-07 01:43 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
> +        // Prevent the optimizer from handling `h1` elements
这里注释需要翻译

2023-08-07 01:43 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
> +*   **类型:** `string[]`
```suggestion
*   **类型：** `string[]`
```

2023-08-07 01:45 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/mdx.mdx
> +`optimize` 的一个可选属性，用于防止 MDX 优化器处理[通过组件属性传递给导入的 MDX 内容的任何自定义组件](/zh-cn/guides/markdown-content/#custom-components-with-imported-mdx)。
```suggestion
`optimize` 的一个可选属性，用于防止 MDX 优化器处理[通过组件属性传递给导入的 MDX 内容的任何自定义组件](/zh-cn/guides/markdown-content/#使用导入的-mdx-的自定义组件)。
```

2023-08-07 02:24 UTC, liruifengv approved these changes
LGTM

2023-08-07 17:35 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 💜

2023-08-07 17:35 UTC, merged