i18n(zh-cn): translate `guides/integrations-guide/alpinejs.mdx`
withastro/docs pull request #4116
Opened 2023-08-08 00:34 UTC by hellolin-oi

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
  translate `guides/integrations-guide/alpinejs.mdx`

2023-08-08 02:04 UTC, 100gle reviewed
需要修改一下最后部分链接所对应的中文版本锚点

2023-08-08 02:04 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/alpinejs.mdx
> +[astro-ui-frameworks]: /zh-cn/core-concepts/framework-components/#using-framework-components
```suggestion
[astro-ui-frameworks]: /zh-cn/core-concepts/framework-components/#使用框架组件
```

2023-08-09 00:59 UTC, liruifengv requested changes

2023-08-09 00:59 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/alpinejs.mdx
> +import Video from '~/components/Video.astro';
```suggestion
```

2023-08-09 00:59 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/alpinejs.mdx
> +import DontEditWarning from '~/components/DontEditWarning.astro';
```suggestion
```

2023-08-09 07:05 UTC, liruifengv approved these changes
LGTM

2023-08-09 10:56 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-08-09 10:56 UTC, merged