i18n(zh-cn): Translate markdoc.mdx
withastro/docs pull request #4127
Opened 2023-08-08 07:51 UTC by liruifengv

#### What kind of changes does this PR include?

- Translated content

#### Description

- Translate markdoc.mdx

2023-08-09 01:35 UTC, 100gle requested changes

2023-08-09 01:35 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +description: Learn how to use the @astrojs/markdoc integration in your Astro project.
这里还没翻

2023-08-09 01:35 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +
这部分的锚点没翻，可能需要跟 #2982 里面的对上

2023-08-09 01:35 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +这个例子渲染了一个 `Aside` 组件，并允许传递一个 `type` 属性作为字符串：
```suggestion
这个例子渲染了一个 `Aside` 组件，并允许传递一个 `type` 字符串属性：
```

2023-08-09 01:35 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +`@astrojs/markdoc` 会自动为你的标题添加锚点链接，并且通过 [内容集合 API 生成一个 `headings` 列表](/zh-cn/guides/content-collections/#rendering-content-to-html)。为了进一步自定义标题的渲染方式，你可以将 Astro 组件 [作为 Markdoc 节点][markdoc-nodes] 应用。
这里的锚点一样要和 #2982 对齐

2023-08-09 01:35 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +*   `id: string` 从标题的文本内容生成的 `id`。这对应于 [内容 `render()` 函数生成的 `slug`](/zh-cn/guides/content-collections/#rendering-content-to-html)。
同上

2023-08-09 01:35 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +      // 注意：Shiki内置了无数的langs，包括 `.astro`！
```suggestion
      // 注意：Shiki内置了许多的 langs，包括 `.astro`！
```

2023-08-09 01:35 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +你可能想要将标准的 Markdown 元素，例如段落和加粗文本，渲染为 Astro 组件。为此，你可以配置一个 [Markdoc 节点][markdoc-nodes]。如果给定的节点接收到属性，它们将作为组件 props 可用。
```suggestion
你可能想要将标准的 Markdown 元素，例如段落和加粗文本，渲染为 Astro 组件。为此，你可以配置一个 [Markdoc 节点][markdoc-nodes]。如果给定的节点接收到属性，它们可将作为组件 props 来使用。
```

2023-08-09 01:35 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +标签和节点仅限于 `.astro` 文件。要在 Markdoc 中嵌入客户端 UI 组件，请 [使用一个包装器 `.astro` 组件来渲染框架组件](https://github.com/withastro/astro/tree/main/packages/integrations/markdoc/en/core-concepts/framework-components/#nesting-f
这里我觉得可以改成中文版的链接和锚点

2023-08-09 01:35 UTC, 100gle commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +## Contributing
```suggestion
## 贡献
```

2023-08-09 02:07 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +标签和节点仅限于 `.astro` 文件。要在 Markdoc 中嵌入客户端 UI 组件，请 [使用一个包装器 `.astro` 组件来渲染框架组件](https://github.com/withastro/astro/tree/main/packages/integrations/markdoc/en/core-concepts/framework-components/#nesting-f
这是个错误的链接，我在 https://github.com/withastro/docs/pull/4143 修复了

2023-08-09 02:09 UTC, liruifengv commented
This PR also needs to merge after https://github.com/withastro/docs/pull/2982 is merged because of the broken link.

2023-08-10 00:52 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/markdoc.mdx
> +标签和节点仅限于 `.astro` 文件。要在 Markdoc 中嵌入客户端 UI 组件，请 [使用一个包装器 `.astro` 组件来渲染框架组件](https://docs.astro.build/zh-cn/core-concepts/framework-components/#嵌套框架组件) 和你想要的 `client:` 指令。
```suggestion
标签和节点仅限于 `.astro` 文件。要在 Markdoc 中嵌入客户端 UI 组件，请 [使用一个包装器 `.astro` 组件来渲染框架组件](/zh-cn/core-concepts/framework-components/#嵌套框架组件) 和你想要的 `client:` 指令。
```

2023-08-10 01:13 UTC, 100gle approved these changes
LGTM!

2023-08-10 10:32 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-08-10 10:32 UTC, merged