i18n(zh-cn): translate guides/integrations-guide/preact.mdx
withastro/docs pull request #4156
Opened 2023-08-09 21:24 UTC by lu-sd

#### What kind of changes does this PR include?
- Translated content

#### Description

 - Translateguides/integrations-guide/preact.mdx to Chinese.

2023-08-09 21:25 UTC, lu-sd commented
@liruifengv

2023-08-10 06:33 UTC, liruifengv requested changes

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +[astro-integration]: /en/guides/integrations-guide/
```suggestion
[astro-integration]: /zh-cn/guides/integrations-guide/
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +[astro-ui-frameworks]: /en/core-concepts/framework-components/#using-framework-components
```suggestion
[astro-ui-frameworks]: /zh-cn/core-concepts/framework-components/#使用框架组件
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +你也可以查阅Astro集成文档 [Astro Integration Documentation][astro-integration] 获得更多集成信息。
```suggestion
你也可以查阅 [Astro 集成文档][astro-integration] 获得更多集成信息。
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +如果遇到任何问题，[请随时在GitHub留言](https://github.com/withastro/astro/issues) 并尝试以下的手动安装步骤。
```suggestion
如果遇到任何问题，[请随时在 GitHub 留言](https://github.com/withastro/astro/issues) 并尝试以下的手动安装步骤。
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +要在 Astro 中使用你的第一个 Preact 组件，请前往我们的 [UI framework documentation][astro-ui-frameworks]. 你将会发现：
```suggestion
要在 Astro 中使用你的第一个 Preact 组件，请前往我们的 [UI 框架文档][astro-ui-frameworks]。你将会了解到：
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +*   💧 客户端水合选项以及，
```suggestion
*   💧 客户端水合选项
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +*   📦 框架组件是如何加载的，
```suggestion
*   📦 如何加载框架组件
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +还可以查阅我们的 [Astro Integration Documentation][astro-integration] 以获取更多关于集成的信息。
```suggestion
还可以查阅我们的 [Astro 集成文档][astro-integration] 以获取更多关于集成的信息。
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +当启用了 `compat` 选项后，Preact 集成将会在你的项目中渲染 React 组件和 Preact 组件，同时还允许你在 Preact 组件中导入 React 组件。在 Preact 网站的“从 React 切换到 Preact”页面中可以阅读更多信息 [“Switching to Preact (from React)”](https://preactjs.com/guide/v10
```suggestion
当启用了 `compat` 选项后，Preact 集成将会在你的项目中渲染 React 组件和 Preact 组件，同时还允许你在 Preact 组件中导入 React 组件。在 Preact 网站的[“从 React 切换到 Preact”](https://preactjs.com/guide/v10/switching-to-preact)页面中可以阅读更多信息。
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +目前，`compat` 选项只适用于 React 库,将代码以 ESM 的形式导出。如果在构建时出现错误，请尝试将该库添加到你的`vite.ssr.noExternal: ['the-react-library']` 的 `astro.config.mjs` 文件中.
```suggestion
目前，`compat` 选项只适用于 React 库，将代码以 ESM 的形式导出。如果在构建时出现错误，请尝试将该库添加到你的`vite.ssr.noExternal: ['the-react-library']` 的 `astro.config.mjs` 文件中。
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +*   在 [Astro Preact example](https://github.com/withastro/astro/tree/latest/examples/framework-preact) 中展示了如何在 Astro 项目中使用交互式的 Preact 组件。
```suggestion
*   在 [Astro Preact 示例](https://github.com/withastro/astro/tree/latest/examples/framework-preact) 中展示了如何在 Astro 项目中使用交互式的 Preact 组件。
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +*   在 [Astro Nanostores example](https://github.com/withastro/astro/tree/latest/examples/with-nanostores) 中展示了如何在 Astro 项目中在不同组件之间共享状态，甚至可以跨不同框架共享状态。
```suggestion
*   在 [Astro Nanostores 示例](https://github.com/withastro/astro/tree/latest/examples/with-nanostores) 中展示了如何在 Astro 项目中在不同组件之间共享状态，甚至可以跨不同框架共享状态。
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +## 问题排查
```suggestion
## 故障排查
```

2023-08-10 06:33 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +这个包由 Astro 的核心团队维护。欢迎你提交问题或（PR）！
```suggestion
这个包由 Astro 的核心团队维护。欢迎你提交 isse 或 PR!
```

2023-08-10 12:35 UTC, liruifengv commented
Thanks for the PR, here are some suggested changes to merge once the changes are complete.

2023-08-10 23:40 UTC, lu-sd commented
Thanks for the review!

2023-08-10 23:44 UTC, Yan-Thomas commented
Thanks @lu-sd! I can see there are a few suggestions in "Files changed" that still show up as not addressed, could you take a look at these in case you missed applying them?

2023-08-11 01:19 UTC, lu-sd commented
oops.  Updated. Thanks!

2023-08-11 01:34 UTC, liruifengv approved these changes
LGTM! So cool! We've done it!!!

2023-08-11 08:39 UTC, Yan-Thomas approved these changes
LGTM! Thanks for the hard work everyone! :rocket:

2023-08-11 08:39 UTC, merged