i18n(es): Fix typo in `server-side-rendering.mdx`
withastro/docs pull request #4230
Opened 2023-08-16 01:34 UTC by Waxer59

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Fix typo in `server-side-rendering.mdx`

2023-08-16 14:01 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59 😁 te dejo algunas sugerencias.

2023-08-16 14:01 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/2.mdx
> +- [Diseños de Markdown en Astro](/es/guides/markdown-content/#layout-en-el-frontmatter)
```suggestion
- [Plantillas de Markdown en Astro](/es/guides/markdown-content/#layout-en-el-frontmatter)
```

2023-08-16 14:01 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/2.mdx
> +- [Props de diseño para Markdown.](/es/core-concepts/layouts/#props-de-plantillas-markdown)
```suggestion
- [Props de plantilla para Markdown](/es/core-concepts/layouts/#props-de-plantillas-markdown)
```

2023-08-17 03:45 UTC, Waxer59 commented
Listo 🤠, gracias por la revision!

2023-08-18 14:13 UTC, dreyfus92 approved these changes
LGTM ✅

2023-08-18 14:46 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-08-18 14:46 UTC, merged