i18n(ru): Add new guides/typescript translation
withastro/docs pull request #4240
Opened 2023-08-16 16:30 UTC by sobresaliente

#### What kind of changes does this PR include?
- Translated content(https://docs.astro.build/en/guides/typescript/)

#### Description
- Translate guides/typescript page to Russian

2023-08-17 08:21 UTC, RolginRoman requested changes

2023-08-17 08:21 UTC, RolginRoman commented on src/content/docs/ru/guides/typescript.mdx
> +Astro имеет хелперы для работы с типами, которые возвращаются из  [`getStaticPaths()`](/ru/reference/api-reference/#getstaticpaths) функции, которая используется для динамически путей.
typo
```suggestion
Astro имеет хелперы для работы с типами, которые возвращаются из  [`getStaticPaths()`](/ru/reference/api-reference/#getstaticpaths) функции, которая используется для динамических путей.
```

2023-08-17 08:21 UTC, RolginRoman commented on src/content/docs/ru/guides/typescript.mdx
> +Используя Typescript, вы можете предотвратить ошибки во время выполнения описывая объекты и компоненты в коде. К примеру, если вы используете  Typescript для [типизации параметров(пропсов) компонента
```suggestion
Используя Typescript, вы можете предотвратить ошибки во время выполнения, описывая объекты и компоненты в коде. К примеру, если вы используете  Typescript для [типизации параметров(пропсов) компонента](#параметры-компонентов), то редактор выведет ошибку, если вы попытаетесь передать параметр, который компонент не принимает.
```

2023-08-17 08:21 UTC, RolginRoman commented on src/content/docs/ru/guides/typescript.mdx
> +Используя Typescript, вы можете предотвратить ошибки во время выполнения описывая объекты и компоненты в коде. К примеру, если вы используете  Typescript для [типизации параметров(пропсов) компонента
imho we're losing a bit of the meaning here
en: `...by defining the shapes of objects...`
ru suggestion: ", описывая типы объектов и компонентов"

2023-08-17 08:21 UTC, RolginRoman commented on src/content/docs/ru/guides/typescript.mdx
> +### Полиморфичные типы
not sure about ru alternative here. might it be a "Полиморфные"? 

[wiki Polymorphism (computer science)](https://ru.wikipedia.org/wiki/%D0%9F%D0%BE%D0%BB%D0%B8%D0%BC%D0%BE%D1%80%D1%84%D0%B8%D0%B7%D0%BC_(%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%82%D0%B8%D0%BA%D0%B0)) sticks to `Полиморфные` too

```suggestion
### Полиморфные типы
```

2023-08-17 17:03 UTC, sobresaliente commented on src/content/docs/ru/guides/typescript.mdx
> +### Полиморфичные типы
Yeah! I agree with you

2023-08-17 17:04 UTC, sobresaliente commented on src/content/docs/ru/guides/typescript.mdx
> +Используя Typescript, вы можете предотвратить ошибки во время выполнения описывая объекты и компоненты в коде. К примеру, если вы используете  Typescript для [типизации параметров(пропсов) компонента
fixed

2023-08-17 17:04 UTC, sobresaliente commented on src/content/docs/ru/guides/typescript.mdx
> +Astro имеет хелперы для работы с типами, которые возвращаются из  [`getStaticPaths()`](/ru/reference/api-reference/#getstaticpaths) функции, которая используется для динамически путей.
fixed

2023-08-17 18:58 UTC, RolginRoman approved these changes
LGTM 👍🏻

2023-08-17 20:10 UTC, Yan-Thomas commented
Thanks @sobresaliente! I can see there's a broken link in `markdown-content.mdx`, would you be up to updating this page here as well and fix the broken link? 🙌

2023-08-22 16:42 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps, and welcome @sobresaliente! 🥳

2023-08-22 16:44 UTC, merged