i18n(fr) : add new "index.mdx" and "1.mdx" for french tutorial
withastro/docs pull request #4252
Opened 2023-08-17 20:33 UTC by sdp971

#### What kind of changes does this PR include?

- Minor content fixes (broken links, typos, etc.)
- New or updated content
- Translated content

#### Description

- Closes # 
- What does this PR change? Give us a brief description.
- Did you change something visual? A before/after screenshot can be helpful.

2023-08-31 19:50 UTC, pioupia requested changes
LGTM, just in French, we have spaces before the exclamation marks

2023-08-31 19:50 UTC, pioupia commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +- [ ] Parfait, Je suis prêt(e) à commencer!
```suggestion
- [ ] Parfait, je suis prêt(e) à commencer !
```

2023-08-31 19:50 UTC, pioupia commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Souhaitez-vous avoir un aperçu de ce que vous allez réaliser? Vous pouvez visualiser le projet finalisé à l'adresse suivante : [GitHub](https://github.com/withastro/blog-tutorial-demo) ou [StackBlitz
```suggestion
Souhaitez-vous avoir un aperçu de ce que vous allez réaliser ? Vous pouvez visualiser le projet finalisé à l'adresse suivante : [GitHub](https://github.com/withastro/blog-tutorial-demo) ou [StackBlitz](https://stackblitz.com/github/withastro/blog-tutorial-demo/tree/complete?file=src%2Fpages%2Findex.astro).
```

2023-08-31 19:50 UTC, pioupia commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +<Lede> Dans ce tutoriel, vous apprendrez les fonctionnalités clés d'Astro en réalisant un blog totalement fonctionnel à partir de zéro jusqu'à son déploiement en ligne! 🚀 </Lede>
```suggestion
<Lede> Dans ce tutoriel, vous apprendrez les fonctionnalités clés d'Astro en réalisant un blog totalement fonctionnel à partir de zéro jusqu'à son déploiement en ligne ! 🚀 </Lede>
```

2023-08-31 19:50 UTC, pioupia commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +unitTitle: 'Bonjour, tout le monde!'
```suggestion
unitTitle: 'Bonjour, tout le monde !'
```

2023-09-02 07:55 UTC, McFlyPartages reviewed
Rien de transcendant, juste des changements qui peuvent être très subjectifs.

2023-09-02 07:55 UTC, McFlyPartages commented on src/content/docs/fr/tutorial/0-introduction/1.mdx
> +Utiliser le tracker est optionnel, mais il permet de vous rappeler les étapes déjà réalisée lorsque vous parcourez le tutoriel en plusieurs visites. Vous pouvez aussi laisser certaines cases à cocher
```suggestion
Utiliser le tracker est optionnel, mais il permet de vous rappeler les étapes déjà réalisées lorsque vous parcourez le tutoriel en plusieurs visites. Vous pouvez aussi laisser certaines cases à cocher vierges pour vous rappeler des modules que vous voulez relire plus tard.
```

2023-09-02 07:55 UTC, McFlyPartages commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Souhaitez-vous avoir un aperçu de ce que vous allez réaliser? Vous pouvez visualiser le projet finalisé à l'adresse suivante : [GitHub](https://github.com/withastro/blog-tutorial-demo) ou [StackBlitz
```suggestion
Vous souhaitez avoir un aperçu de ce que vous allez réaliser? Vous pouvez visualiser le projet finalisé à l'adresse suivante : [GitHub](https://github.com/withastro/blog-tutorial-demo) ou [StackBlitz](https://stackblitz.com/github/withastro/blog-tutorial-demo/tree/complete?file=src%2Fpages%2Findex.astro).
```

2023-09-02 07:55 UTC, McFlyPartages commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Souhaitez-vous avoir un aperçu de ce que vous allez réaliser? Vous pouvez visualiser le projet finalisé à l'adresse suivante : [GitHub](https://github.com/withastro/blog-tutorial-demo) ou [StackBlitz
Très subjectif comme préférence.

2023-09-02 07:55 UTC, McFlyPartages commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Si vous souhaitez plutôt commencer à explorer Astro avec un site Astro pré-construit, vous pouvez visiter https://astro.new et choisir un modèle, l'ouvrir et le modifier dans un éditeur en ligne.
```suggestion
Si vous souhaitez, plutôt commencer avec un site Astro pré-construit, vous pouvez visiter https://astro.new, choisir un modèle, l'ouvrir et le modifier dans un éditeur en ligne.
```

2023-09-02 10:15 UTC, sdp971 commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Souhaitez-vous avoir un aperçu de ce que vous allez réaliser? Vous pouvez visualiser le projet finalisé à l'adresse suivante : [GitHub](https://github.com/withastro/blog-tutorial-demo) ou [StackBlitz
@McFlyPartages je préfère ta suggestion 🙂

2023-09-02 10:17 UTC, sdp971 commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Si vous souhaitez plutôt commencer à explorer Astro avec un site Astro pré-construit, vous pouvez visiter https://astro.new et choisir un modèle, l'ouvrir et le modifier dans un éditeur en ligne.
@McFlyPartages  Je suggère un mix des deux ? : " Si vous souhaitez plutôt commencer avec un site Astro pré-construit, vous pouvez visiter https://astro.new, choisir un modèle, l'ouvrir et le modifier dans un éditeur en ligne." 
Qu'en penses-tu ?

2023-09-02 11:44 UTC, McFlyPartages commented on src/content/docs/fr/tutorial/0-introduction/index.mdx
> +Si vous souhaitez plutôt commencer à explorer Astro avec un site Astro pré-construit, vous pouvez visiter https://astro.new et choisir un modèle, l'ouvrir et le modifier dans un éditeur en ligne.
> @McFlyPartages Je suggère un mix des deux ? : " Si vous souhaitez plutôt commencer avec un site Astro pré-construit, vous pouvez visiter https://astro.new, choisir un modèle, l'ouvrir et le modifier dans un éditeur en ligne." Qu'en penses-tu ?

Excellent

2023-09-04 20:26 UTC, pioupia approved these changes
LGTM!

2023-09-13 17:18 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 👋

2023-09-13 17:18 UTC, merged