Add basic custom Translation Tracker syntax
withastro/docs pull request #4267
Opened 2023-08-18 20:11 UTC by Yan-Thomas

#### What kind of changes does this PR include?

- Changes to the docs site code

#### Description

This PR adds a rudimentary version of the custom tracker syntax to help with the 3.0 PRs changing lots of translations to fix links (LOOKING AT YOU 3.0 IMAGE GUIDE).

This allows you to add a `@tracker-major:(list of file paths separated by ;)` to a final squashed commit description (the one you have to confirm before you merge) that makes all changes be considered minor except the ones you have explicitly marked as major.

🚨 **THE FILE PATH HAS TO INCLUDE EVERYTHING (SEE BELOW)** 🚨 

Example:

**PR updates the pages (br/1.mdx, br/2.mdx), but also updates the link to another page that isn't fully updated yet (br/3.mdx).**
Using: `@tracker-major:./src/content/docs/br/1.mdx;./src/content/docs/br/2.mdx`, `br/3.mdx` continues to be marked as outdated.

More info in the code comment!

**How to test it?**
1. Pull the branch
2. Run `pnpm translation-status` (or with your preferred package manager) 
3. Open the `dist/translation-status/index.html` file. (this is the current status in the branch!)
4. Now, make a new commit changing any pages you want, and add the custom syntax to the commit description.
5. Do steps 2 & 3 again.
6. See the changes done in the tracker. Might be helpful to have `i18n.docs.astro.build` side by side, but will be inconsistent the moment the branch isn't 100% updated in relation to main.

2023-08-18 22:35 UTC, dreyfus92 requested changes
Awesome job @Yan-Thomas. I left you a couple of minor suggestions to improve a bit code readibility. Let me know what you think 😁

2023-08-18 22:35 UTC, dreyfus92 commented on scripts/lib/translation-status/builder.ts
> +			return filePaths.indexOf(filePath) > -1;
```suggestion
			return filePaths.includes(filePath);
```

2023-08-18 22:35 UTC, dreyfus92 commented on scripts/lib/translation-status/builder.ts
> +		const trackerDirective = entry.body.match(TRACKER_DIRECTIVE);
```suggestion
		const trackerDirectiveMatch = entry.body.match(TRACKER_DIRECTIVE);
```

2023-08-18 22:35 UTC, dreyfus92 commented on scripts/lib/translation-status/builder.ts
> +			const filePaths = trackerDirective[0].replace('@tracker-major:', '').split(';');
```suggestion
			const filePaths = trackerDirectiveMatch[0].replace('@tracker-major:', '').split(';');
```

2023-08-18 23:01 UTC, dreyfus92 commented on scripts/lib/translation-status/builder.ts
> +		if (trackerDirective) {
```suggestion
		if (trackerDirectiveMatch) {
```

2023-08-18 23:02 UTC, dreyfus92 commented on scripts/lib/translation-status/builder.ts
> +		if (trackerDirective) {
This might fix the error logged by the CI / Check

2023-08-19 14:34 UTC, TheOtterlord approved these changes
Tested locally :partying_face:

2023-08-19 19:54 UTC, Yan-Thomas commented
Thanks peeps! Let's get this merged 🚀

2023-08-19 20:06 UTC, merged