i18n(es): Update `ui.ts`
withastro/docs pull request #4273
Opened 2023-08-19 02:07 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Changes to the docs site code

#### Description

- What does this PR change? Give us a brief description.
Update `ui.ts`

2023-08-19 20:17 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo una pequeña sugerencia 😁

2023-08-19 20:17 UTC, dreyfus92 commented on src/i18n/es/ui.ts
> +		'¿Quieres contribuir a esta guía? ¿Tienes una publicación en un blog, un video u otro recurso para compartir sobre la migración desde esta tecnología a Astro?',
```suggestion
		'¿Quieres contribuir a esta guía? ¿Tienes alguna publicación en un blog, un video u otro recurso para compartir sobre la migración desde esta tecnología a Astro?',
```

2023-08-20 00:16 UTC, Waxer59 commented
Gracias por la revisión!

2023-08-20 12:09 UTC, Yan-Thomas approved these changes
LGTM! Thanks folks 💜

2023-08-20 12:09 UTC, merged