i18n(fr): Translation of tutorial setup 1: `1.mdx`
withastro/docs pull request #4277
Opened 2023-08-19 21:27 UTC by Elib27

#### What kind of changes does this PR include?
- Translated content

#### Description

Translated tutorial setup: `1.mdx` content to french

2023-08-23 15:52 UTC, dreyfus92 approved these changes
LGTM ✅

2023-08-23 16:04 UTC, pioupia requested changes
It's all good, except for a phrase that gave me problems to understand.

2023-08-23 16:04 UTC, pioupia commented on src/content/docs/fr/tutorial/1-setup/1.mdx
> +Vous pouvez accéder à la ligne de commande via un programme terminal local pour votre système d'exploitation. Les applications courantes sont **Terminal** (MacOS/Linux), **Invite de commandes** (Wind
I'm not agree with the English version. So even you wrote the good translation, I think we should say `de` instead of `pour` because this is not really clear. I don't understand the sentence.
But this suggestion is a suggestion, so if you found / find that it was clear / made sense, leave it. I don't find my sentence makes more sense, it just sounds better!
```suggestion
Vous pouvez accéder à la ligne de commande via un programme terminal local de votre système d'exploitation. Les applications courantes sont **Terminal** (MacOS/Linux), **Invite de commandes** (Windows) et **Termux** (Android). L'une de ces options sera probablement déjà sur votre machine.
```

2023-08-23 16:04 UTC, pioupia commented on src/content/docs/fr/tutorial/1-setup/1.mdx
> +Vous pouvez accéder à la ligne de commande via un programme terminal local pour votre système d'exploitation. Les applications courantes sont **Terminal** (MacOS/Linux), **Invite de commandes** (Wind
Or maybe with `en fonction de` should be better?

```suggestion
Vous pouvez accéder à la ligne de commande via un programme terminal local en fonction de votre système d'exploitation. Les applications courantes sont **Terminal** (MacOS/Linux), **Invite de commandes** (Windows) et **Termux** (Android). L'une de ces options sera probablement déjà sur votre machine.
```

2023-08-23 16:59 UTC, Elib27 commented on src/content/docs/fr/tutorial/1-setup/1.mdx
> +## Obtenez les outils de développement dont vous avez besoin
Yes, I think it's better

2023-08-23 17:07 UTC, Elib27 commented on src/content/docs/fr/tutorial/1-setup/1.mdx
> +Vous pouvez accéder à la ligne de commande via un programme terminal local pour votre système d'exploitation. Les applications courantes sont **Terminal** (MacOS/Linux), **Invite de commandes** (Wind
I struggled a bit with the translation of this sentence, I was not convinced of the result.
It's maybe better to say `adapté à` ?

2023-08-23 17:26 UTC, pioupia commented on src/content/docs/fr/tutorial/1-setup/1.mdx
> +Vous pouvez accéder à la ligne de commande via un programme terminal local pour votre système d'exploitation. Les applications courantes sont **Terminal** (MacOS/Linux), **Invite de commandes** (Wind
> I struggled a bit with the translation of this sentence, I was not convinced of the result. It's maybe better to say `adapté à` ?

Yeah, that sounds better! This is a very good idea for me

2023-08-24 13:49 UTC, pioupia approved these changes
LGTM

2023-08-24 19:23 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🖖

2023-08-24 19:24 UTC, merged