i18n(zh-cn): uppercase http methods & some update.
withastro/docs pull request #4353
Opened 2023-08-24 13:25 UTC by liruifengv

#### What kind of changes does this PR include?

- New or updated content

#### Description

- uppercase http methods & some update.

2023-08-26 16:22 UTC, Genteure requested changes
Sorry for nitpicking word choices not made in this PR. 😂

2023-08-26 16:22 UTC, Genteure commented on src/content/docs/zh-cn/concepts/why-astro.mdx
> +**Astro 是集多功能于一体的 Web 框架，提供了构建网站所需的一切** Astro 包括组件语法、基于文件的路由、静态资源处理、构建处理、捆绑、优化、数据获取等。你可以在不超过 Astro 核心功能集 的情况下构建出色的网站。
```suggestion
**Astro 是集多功能于一体的 Web 框架，提供了构建网站所需的一切** Astro 包括组件语法、基于文件的路由、静态资源处理、构建处理、捆绑、优化、数据获取等。你只使用 Astro 核心功能集就可构建出色的网站。
```

Original English text: `You can build great websites without ever reaching outside of Astro's core feature set.`

Once again while I agree "你可以在不超过 Astro 核心功能集 的情况下构建出色的网站。" is an accurate translation, it's a little too literal, making it hard to understand (to me at least). "Reaching outside" seems hard to translate in this context, so I'm suggesting flipping the sentence from negative to affirmative.

Literal translation back to English: `You can build great websites using only Astro's core feature set.`

2023-08-26 16:22 UTC, Genteure commented on src/content/docs/zh-cn/concepts/why-astro.mdx
> +如果你需要更多的控制，你可以通过 [React](https://www.npmjs.com/package/@astrojs/react), [Svelte](https://www.npmjs.com/package/@astrojs/svelte), [Vue](https://www.npmjs.com/package/@astrojs/vue), [Tailwind CSS](http
```suggestion
如果你需要更多的控制，你可以通过 [React](https://www.npmjs.com/package/@astrojs/react), [Svelte](https://www.npmjs.com/package/@astrojs/svelte), [Vue](https://www.npmjs.com/package/@astrojs/vue), [Tailwind CSS](https://www.npmjs.com/package/@astrojs/tailwind), [MDX](https://www.npmjs.com/package/@astrojs/mdx) 等[100多个集成](https://astro.build/integrations/)。 扩展 Astro 只需要一个命令 [即可连接你喜欢的 CMS](/zh-cn/guides/cms/) 或 [部署到你喜欢的托管平台](/zh-cn/guides/deploy/)
```

Original: `deploy to your favorite host`

While "host" can be translated as "服务器" (literal: server), it seems to me "托管" or "托管平台" is more appropriate.

"服务器" usually means a physical or virtual server that you can SSH into, like AWS Lightsail, EC2, or GCP Compute Engine.
Services that hosts static web resources or provides a serverless runtime certainly does not count as a "server" (it's literally "serverless").

Both AWS and GCP translate "hosting" as "托管".
https://aws.amazon.com/cn/what-is/web-hosting/
https://cloud.google.com/solutions/web-hosting?hl=zh-cn

2023-08-26 16:55 UTC, Genteure requested changes
These suggestions also apply to other pages containing the same "multiple JSX frameworks" paragraph.

2023-08-26 16:55 UTC, Genteure commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +### 组合对个 JSX 框架
```suggestion
### 组合多个 JSX 框架
```

Typo.

2023-08-26 16:55 UTC, Genteure commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +当你在同一个项目中使用多个 JSX 框架（React、Preact、Solid）时，Astro 需要确定每个组件应该使用哪个 JSX 框架特定的转换。如果你只向你的项目中添加了一个 JSX 框架集成，那么就不需要额外的配置。
Original: `Astro needs to determine which JSX framework-specific transformations should be used for each of your components.`

No suggestion on top of my head yet, but the current translation seems too verbose and literal to me.

2023-08-26 16:55 UTC, Genteure commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +使用 `include`（必填）和 `exclude`（可选）配置选项来指定哪些文件属于哪个框架。为你使用的每个框架提供一个文件数组或者文件夹。通配符可用于包含多个文件路径。
```suggestion
使用 `include`（必填）和 `exclude`（可选）配置选项来指定哪些文件属于哪个框架。为你使用的每个框架提供一个文件或/和文件夹数组。通配符可用于包含多个文件路径。
```

Original: ```Provide an array of files and/or folders to `include` for each framework you are using.```

2023-08-26 16:55 UTC, Genteure commented on src/content/docs/zh-cn/guides/integrations-guide/preact.mdx
> +我们建议将常见的框架组件放在同一个文件夹中（例如 `/components/react/` 和 `/components/solid/`），以便更容易地指定你的包含内容，但这不是必需的：
```suggestion
我们建议将每个框架的组件放在同一个文件夹中（例如 `/components/react/` 和 `/components/solid/`），以便更容易地指定你的包含内容，但这不是必需的：
```

Original: `We recommend placing common framework components in the same folder...`

My understanding of `common` in this context is `shared by, coming from, or done by more than one`. Currently it's translated as `occurring, found, or done often; prevalent`.

2023-08-26 18:27 UTC, Genteure requested changes

2023-08-26 18:27 UTC, Genteure commented on src/content/docs/zh-cn/guides/upgrade-to/v3.mdx
> +Astro v3.0 不再默认情况下将 `import.meta.env.BASE_URL` 与尾随斜杠附加在一起，也不会在设置 `trailingSlash: "ignore"` 时附加一个尾随斜杠。（`base` 与 `trailingSlash: "always"` 或 `trailingSlash: "never"` 结合使用的现有行为保持不变。）
Could use some rewording. Waiting for confirmation of whether or not my understanding of the original English docs is correct before suggesting changes.

2023-08-28 00:17 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/react.mdx
> +### 组合对个 JSX 框架
```suggestion
### 组合多个 JSX 框架
```

2023-08-28 00:17 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/react.mdx
> +使用 `include`（必填）和 `exclude`（可选）配置选项来指定哪些文件属于哪个框架。为你使用的每个框架提供一个文件数组或者文件夹。通配符可用于包含多个文件路径。
```suggestion
使用 `include`（必填）和 `exclude`（可选）配置选项来指定哪些文件属于哪个框架。为你使用的每个框架提供一个文件或/和文件夹数组。通配符可用于包含多个文件路径。
```

2023-08-28 00:18 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/solid-js.mdx
> +### 组合对个 JSX 框架
```suggestion
### 组合多个 JSX 框架
```

2023-08-28 00:18 UTC, liruifengv commented on src/content/docs/zh-cn/guides/integrations-guide/solid-js.mdx
> +使用 `include`（必填）和 `exclude`（可选）配置选项来指定哪些文件属于哪个框架。为你使用的每个框架提供一个文件数组或者文件夹。通配符可用于包含多个文件路径。
```suggestion
使用 `include`（必填）和 `exclude`（可选）配置选项来指定哪些文件属于哪个框架。为你使用的每个框架提供一个文件或/和文件夹数组。通配符可用于包含多个文件路径。
```

2023-08-28 00:51 UTC, liruifengv commented
@Genteure Thank you for the detailed review. I fixed them and added some updates from upstream https://github.com/withastro/docs/pull/4166

2023-08-28 06:04 UTC, Genteure requested changes
Review progress: 41/48 files.

2023-08-28 06:04 UTC, Genteure commented on src/content/docs/zh-cn/reference/directives-reference.mdx
> +`class:list={...}` 接收 class 数组，并将其转换为 class 字符串。这是受流行的 @lukeed [clsx](https://github.com/lukeed/clsx)辅助库的启发。
```suggestion
`class:list={...}` 接收 class 数组，并将其转换为 class 字符串。这是受流行的 @lukeed [clsx](https://github.com/lukeed/clsx) 辅助库的启发。
```

2023-08-28 07:13 UTC, liruifengv commented
> Review progress: 41/48 files.

Thanks for your hard work

2023-08-28 15:35 UTC, Genteure requested changes
All 48 files reviewed.

2023-08-28 15:35 UTC, Genteure commented on src/content/docs/zh-cn/guides/upgrade-to/v3.mdx
> +你可以安全的删除任何使用 `has()` 来检查 `Astro.cookies` 的值是否为 `undefined` 的代码：
```suggestion
这个修改不会影响任何在调用 `Astro.cookies.get(key)` 之前用 `Astro.cookies.has(key)` 检查 cookie 是否存在的代码，但现在不再需要检查。

你可以安全的删除任何使用 `has()` 来检查 cookie 是否存在的代码：
```

The suggested change deviate a lot from the original English text. Waiting for feedback on the wording of the original text on Discord.

2023-08-28 15:35 UTC, Genteure commented on src/content/docs/zh-cn/guides/upgrade-to/v3.mdx
> +Astro v3.0 删除了这两个入口文件，而是使用现有的 `astro/runtime/*` 入口文件。此外，还添加了一个新的 `astro/compiler-runtime` 导出，用于编译器特定的运行时代码。
```suggestion
Astro v3.0 删除了这两个入口文件，而是使用现有的 `astro/runtime/*` 入口文件。此外，还为编译器的运行时代码导出了一个新的 `astro/compiler-runtime`。
```

Preferring natural phrasing over accurate/literal translations.

2023-08-28 15:35 UTC, Genteure commented on src/content/docs/zh-cn/guides/view-transitions.mdx
> +-  对于尚未支持视图过渡动画 API 的浏览器，可以 [控制回退行为](#回退控制)。
```suggestion
- 可完全 [自定义过渡动画](#自定义动画) 的能力，可以构建自己的动画效果；
- 用于 [阻止非页面链接的客户端导航](#阻止客户端导航) 的选项。
- 对于尚未支持视图过渡动画 API 的浏览器，可以 [控制回退行为](#回退控制)。
```

Formatting.

2023-08-28 15:35 UTC, Genteure commented on src/content/docs/zh-cn/guides/view-transitions.mdx
>  - `transition:persist`: 允许你覆盖 Astro 的默认行为。不同于在导航到另一个页面时用将替换旧元素为新元素的方式，该行为则是在导航到另一个页面时 [保留组件和 HTML 元素的状态](#维持状态)。
```suggestion
- `transition:name`：允许你覆盖 Astro 的默认元素匹配方式，为一对 DOM 元素 [指定过渡动画名称](#命名过渡动画)。
- `transition:animate`：在用新元素替换旧元素时，允许你通过指定动画类型来覆盖 Astro 的默认动画效果。可以使用 Astro 的 [内置动画指令](#内置的动画指令) 或 [创建自定义动画](#自定义动画)。
- `transition:persist`: 允许你覆盖 Astro 的默认行为。不同于在导航到另一个页面时用将替换旧元素为新元素的方式，该行为则是在导航到另一个页面时 [保留组件和 HTML 元素的状态](#维持状态)。
```

Formatting.

2023-08-28 15:35 UTC, Genteure commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +`import.meta.env.BASE_URL` 的值会遵从你的 `trailingSlash` 配置，如果你明确地包含一个尾部斜杠，或者设置了 `trailingSlash: "always"`，它将包含一个尾部斜杠。如果设置了 `trailingSlash: "never"`，`BASE_URL` 将不包含尾部斜杠，即使 `base` 中包含。
```suggestion
`import.meta.env.BASE_URL` 的值会遵从你的 `trailingSlash` 配置。如果你的 `base` 以斜杠结尾，或者设置了 `trailingSlash: "always"`，它将以斜杠结尾。如果设置了 `trailingSlash: "never"`，即使 `base` 是以斜杠结尾的 `BASE_URL` 也不会以斜杠结尾。
```

Preferring natural phrasing over accurate/literal translations.

2023-08-28 15:35 UTC, Genteure commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +  - `'attribute'` 	- 使用 `data-` 属性，不会增加特异性。
```suggestion
  - `'attribute'` - 使用 `data-` 属性，不会增加特异性。
```

Formatting.

2023-08-28 15:35 UTC, Genteure commented on src/content/docs/zh-cn/reference/integrations-reference.mdx
> +所有消息都前面带有一个具有相同集成值的标签。
```suggestion
所有消息都前面带有一个具有集成名字的标签。
```

Original:

```markdown
All the messages are prepended with a label that has the same value of the integration.
```

2023-08-28 15:35 UTC, Genteure commented on src/content/docs/zh-cn/reference/integrations-reference.mdx
> +上面的示例将默认生成带有 `[astro-format]` 的日志，并在指定时生成带有 `[astro-format/build]` 的日志：
```suggestion
上面的示例将默认生成带有 `[astro-format]` 的日志，并在指定名字时生成带有 `[astro-format/build]` 的日志：
```

2023-08-29 00:40 UTC, liruifengv commented on src/content/docs/zh-cn/guides/upgrade-to/v3.mdx
> +如果你的 `base` 没有尾随斜杠，请添加一个，如果你希望保留以前的默认行为（或 `trailingSlash: "ignore"`）。
Cool!

2023-08-29 01:39 UTC, liruifengv commented
Updated endpoints.mdx & v3.mdx @Genteure

2023-08-29 02:56 UTC, 100gle approved these changes
LGTM, This is a hard but great work!

2023-08-29 02:56 UTC, 100gle commented on src/content/docs/zh-cn/guides/view-transitions.mdx
> +- `initial`: Opt out of Astro's opinionated crossfade animation and use the browser's default styling.
```suggestion
```

这里忘记删除英语原文了

2023-08-29 13:06 UTC, Genteure approved these changes
LGTM 👍

2023-08-30 01:30 UTC, liruifengv commented
@Genteure @100gle Added some updates from upstream, this may be the last change. (hopefully)

2023-08-30 01:48 UTC, 100gle approved these changes
adapter-reference 的一个部分需要调整一下语序

2023-08-30 01:48 UTC, 100gle commented on src/content/docs/zh-cn/reference/adapter-reference.mdx
> +当设置 `functionPerRoute: false` 时，只有一个单一的处理程序（handler）负责渲染所有路由。当此处理程序（handler）首次触发时，你将受到冷启动的影响。然后，所有其他路由都应该没有延迟。但是，你将失去 `functionPerRoute: true` 提供的代码拆分（code splitting）的好处。
```suggestion
当设置 `functionPerRoute: false` 时，只有一个单一的处理程序（handler）负责渲染所有路由。当此处理程序（handler）首次触发时，你将受到冷启动的影响。然后，所有其他路由都应该没有延迟。但是，你将无法享受由 `functionPerRoute: true` 提供的代码拆分（code splitting）所带来的好处。
```

2023-08-30 08:14 UTC, Genteure approved these changes
LGTM

2023-08-30 10:17 UTC, Yan-Thomas approved these changes
Amazing work everyone, thanks!

2023-08-30 10:17 UTC, merged