i18n(es): Update `view-transitions.mdx v3`
withastro/docs pull request #4370
Opened 2023-08-25 18:54 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Update `view-transitions.mdx V3` [`PR`](https://github.com/withastro/docs/pull/4320/files#diff-98423fea56caf403fbdc68882f98104aeee89ca2fdfab857e9f2d73c74c2c90a)

2023-08-25 21:22 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59 😁, pero sería bueno que incluyas los cambios al archivo `src/content/docs/en/guides/upgrade-to/v3.mdx` que viene en esa misma PR que ligaste.

2023-08-25 21:22 UTC, dreyfus92 commented on src/content/docs/es/guides/view-transitions.mdx
> +Por defecto, cada página utilizará la navegación normal del navegador, ocupando toda la página. Debes elegir activamente las view transitions a y puedes utilizarlas ya sea en base a cada página indiv
```suggestion
Por defecto, cada página utilizará la navegación normal del navegador, ocupando toda la página. Debes optar por ver las view transitions y puedes usarlas por página o en todo el sitio.
```

2023-08-25 21:22 UTC, dreyfus92 commented on src/content/docs/es/guides/view-transitions.mdx
> +- `none`: Desactiva las animaciones predeterminadas del navegador. Úsalo en el elemento `<html>` de una página para desactivar el fundido predeterminado para cada elemento en la página.
Siento que aquí si cambiamos el anglicismo, va a causar un poco de confusión. Cuando lo estaba leyendo no sabía que era fundido. 

```suggestion
- `none`: Desactiva las animaciones predeterminadas del navegador. Úsalo en el elemento `<html>` de una página para desactivar el fade predeterminado para cada elemento en la página.
```

2023-08-25 21:22 UTC, dreyfus92 commented on src/content/docs/es/guides/view-transitions.mdx
> +Una vez hayas habilitado el enrutamiento del lado del cliente en una página al agregar el componente `<ViewTransitions />`, todos los enlaces tipo anchor en la página que lleven a otra página en tu s
```suggestion
Una vez hayas habilitado el enrutamiento del lado del cliente en una página al agregar el componente `<ViewTransitions />`, todos los enlaces tipo anchor en la página que lleven a otra página en tu sitio se navegarán mediante enrutamiento del lado del cliente. Hay casos en los que puede que no desees navegar mediante este método. Un ejemplo es cuando el enlace lleva a cualquier recurso que no sea una página, como un archivo PDF dentro de tu carpeta `public/` o una ruta de API que produce una imagen.
```

2023-08-25 21:22 UTC, dreyfus92 commented on src/content/docs/es/guides/view-transitions.mdx
> +- Se desencadena el evento `astro:after-swap` en el `document`. Esto marca el final del proceso de __intercambio__.
```suggestion
    - El contenido de `<head>` se intercambia, manteniendo algunos elementos:
        - Los nodos DOM de las hojas de estilo se mantienen si existen en la nueva página, para evitar el parpadeo de contenido no estilizado (FOUC).
        - Los scripts se mantienen si existen en la nueva página.
        - Cualquier otro elemento de `<head>` con `transition:persist` se mantiene si hay un elemento correspondiente en la nueva página.

    - `<body>` se reemplaza completamente con el cuerpo de la nueva página.

    - Los elementos marcados con `transition:persist` se trasladan al nuevo DOM si existen en la nueva página.

    - La posición de desplazamiento se restaura si es necesario.

    - Se desencadena el evento `astro:after-swap` en el `document`. Esto marca el final del proceso de __intercambio__.
```

2023-08-26 08:55 UTC, Waxer59 commented
Listo!, gracias por la review 🤠!

2023-08-26 09:09 UTC, Waxer59 commented
> Buen trabajo @Waxer59 😁, pero sería bueno que incluyas los cambios al archivo `src/content/docs/en/guides/upgrade-to/v3.mdx` que viene en esa misma PR que ligaste.

Para incluir el archivo `v3.mdx` habria que traducirlo entero, no? creo que seria mejor abrir otra PR con la traduccion de este archivo

2023-08-26 15:36 UTC, dreyfus92 approved these changes
LGTM ✅

2023-08-30 00:53 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-08-30 00:53 UTC, merged