i18n(es): Translate `v3.mdx` `V3`
withastro/docs pull request #4375
Opened 2023-08-26 11:37 UTC by Waxer59

#### What kind of changes does this PR include?

> **Still need to fix the links that are in English, but these links will remain until the rest of the pages are upgraded to V3.**

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translate `v3.mdx` `V3`

2023-08-26 16:25 UTC, dreyfus92 requested changes
Te dejo una sugerencias @Waxer59, buen trabajo 😁

2023-08-26 16:25 UTC, dreyfus92 commented on src/content/docs/es/guides/upgrade-to/v3.mdx
> +En Astro v2.x, el valor de retorno de [`getStaticPaths()`](/en/reference/api-reference/#getstaticpaths) se aplanaba automáticamente para permitirte devolver un array de arrays sin errores.
```suggestion
En Astro v2.x, el valor de retorno de [`getStaticPaths()`](/en/reference/api-reference/#getstaticpaths) se aplanaba automáticamente para permitirte devolver un arreglo de arreglos sin errores.
```

2023-08-26 16:25 UTC, dreyfus92 commented on src/content/docs/es/guides/upgrade-to/v3.mdx
> +Si estás devolviendo un array de arrays en lugar de un array de _objetos_ (como se espera), ahora debes usar `.flatMap` y `.flat` para asegurarte de que estás devolviendo un array plano.
```suggestion
Si estás devolviendo un arreglo de arreglos en lugar de un arreglo de _objetos_ (como se espera), ahora debes usar `.flatMap` y `.flat` para asegurarte de que estás devolviendo un array plano.
```

2023-08-26 16:25 UTC, dreyfus92 commented on src/content/docs/es/guides/upgrade-to/v3.mdx
> +Se proporcionará un [mensaje de error indicando que el valor de retorno de `getStaticPath()` debe ser un array de objetos](/en/reference/errors/invalid-get-static-paths-entry/#what-went-wrong) si nec
```suggestion
Se proporcionará un [mensaje de error indicando que el valor de retorno de `getStaticPath()` debe ser un arreglo de objetos](/en/reference/errors/invalid-get-static-paths-entry/#what-went-wrong) si necesitas actualizar tu código.
```

2023-08-26 16:25 UTC, dreyfus92 commented on src/content/docs/es/guides/upgrade-to/v3.mdx
> +Si estás utilizando múltiples frameworks JSX en el mismo proyecto, establece `include` (y opcionalmente `exclude`) en un array de archivos y/o carpetas. Puedes utilizar comodines para incluir múltipl
```suggestion
Si estás utilizando múltiples frameworks JSX en el mismo proyecto, establece `include` (y opcionalmente `exclude`) en un arreglo de archivos y/o carpetas. Puedes utilizar comodines para incluir múltiples rutas de archivo.
```

2023-08-26 16:41 UTC, Waxer59 commented
Listo!, gracias por la review 🤠

2023-08-29 15:29 UTC, Waxer59 commented
Commits applied:
* [`458b36`](https://github.com/withastro/docs/pull/4166/commits/458b3624deab0dbff5da7413791c743c01354446#diff-98423fea56caf403fbdc68882f98104aeee89ca2fdfab857e9f2d73c74c2c90a)
* [`316b0e`](https://github.com/withastro/docs/pull/4166/commits/316b0e772799d13cb93f37011ca5b5dc3cc840f1)

2023-08-29 19:10 UTC, Yan-Thomas commented
Thanks @Waxer59! Just a heads up we added a few more commits to this page, hopefully, there won't be more 🙌

2023-08-29 19:21 UTC, Waxer59 commented
Commits:
* [`4bb543`](https://github.com/withastro/docs/pull/4166/commits/4bb5430a1d5f2abf1af2052e9b9f2baf3cd3811a)
* [`0895ea`](https://github.com/withastro/docs/pull/4166/commits/0895eaf87321e84e8da9094cf69e7e592e4b58cc)
* [`333cdd`](https://github.com/withastro/docs/pull/4166/commits/333cdd5ee86c6aa44d93c997abd32f88276b8471)
* [`7b89c4`](https://github.com/withastro/docs/pull/4166/commits/7b89c400e5be15a0d5378be6c71645965b2a8f1c)

2023-08-29 19:21 UTC, Waxer59 commented
> Thanks @Waxer59! Just a heads up we added a few more commits to this page, hopefully, there won't be more 🙌

Changes applied! 🤠

2023-08-30 04:51 UTC, dreyfus92 approved these changes
LGTM ✅

2023-08-30 05:29 UTC, kevinzunigacuellar approved these changes
LGTM! 🥳

2023-08-30 10:11 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-08-30 10:12 UTC, merged