i18n(es): Update `guides/` `V3`
withastro/docs pull request #4383
Opened 2023-08-26 16:42 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- Closes # 
- What does this PR change? Give us a brief description.
Update `guides/` `V3` [PR](https://github.com/withastro/docs/pull/4166/files#diff-f3d2bb9ef8c11d189abbf550bf423e5698c35a1af013173d764613cdbb15aaa9)

2023-08-26 17:20 UTC, dreyfus92 requested changes
Te dejo algunas sugerencias @Waxer59, buen trabajo 😁

2023-08-26 17:20 UTC, dreyfus92 commented on src/content/docs/es/guides/rss.mdx
> +    description: 'Guía de las estrellas para un humilde astronauta',
```suggestion
    description: 'Guía de un humilde astronauta a las estrellas',
```

2023-08-26 17:20 UTC, dreyfus92 commented on src/content/docs/es/guides/rss.mdx
> +    description: 'Guía de las estrellas para un humilde astronauta',
```suggestion
    description: 'Guía de un humilde astronauta a las estrellas',
```

2023-08-26 17:20 UTC, dreyfus92 commented on src/content/docs/es/guides/rss.mdx
> +    description: 'Guía de las estrellas para un humilde astronauta',
```suggestion
    description: 'Guía de un humilde astronauta a las estrellas',
```

2023-08-26 17:20 UTC, dreyfus92 commented on src/content/docs/es/guides/rss.mdx
> +    description: 'Guía de las estrellas para un humilde astronauta',
```suggestion
    description: 'Guía de un humilde astronauta a las estrellas',
```

2023-08-26 17:24 UTC, Waxer59 commented
Listo!, gracias por la review 🤠

2023-08-29 19:12 UTC, Waxer59 commented
Commit: 
* [`355b66`](https://github.com/withastro/docs/pull/4166/commits/355b667be370620c87c204a2608a61bc55bd384e)

2023-08-30 01:14 UTC, Yan-Thomas approved these changes
LGTM!

2023-08-30 01:14 UTC, merged