i18n(es): Update `images` `V3`
withastro/docs pull request #4408
Opened 2023-08-28 19:55 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Update `images` `V3` [`PR`](https://github.com/withastro/docs/pull/3739/files#diff-9ea5d63bc29a5a013378b352f2b77fffd61f773692ff6c329a3cc9292552ac23)

2023-08-28 20:07 UTC, Waxer59 commented on src/content/docs/es/guides/images.mdx
> +En su lugar, puedes [generar imágenes o componentes personalizados usando `getImage()`](#generando-imágenes-con-getImage) que utilicen los atributos HTML de imagen `srcset` y `sizes` o la etiqueta `<
```suggestion
En su lugar, puedes [generar imágenes o componentes personalizados usando `getImage()`](#generando-imágenes-con-getImage) que utilicen los atributos HTML de imagen `srcset` y `sizes` o la etiqueta `<picture>` [para la dirección de arte o para crear imágenes responsivas](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#art_direction).
```

2023-08-29 01:46 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo una sugerencia 😁

2023-08-29 01:46 UTC, dreyfus92 commented on src/content/docs/es/guides/images.mdx
> +You can declare an associated image for a content collections entry, such as a blog post's cover image, in your frontmatter using its path relative to the current folder:
Falta traducir.

2023-08-29 10:22 UTC, Waxer59 commented on src/content/docs/es/guides/images.mdx
> +You can declare an associated image for a content collections entry, such as a blog post's cover image, in your frontmatter using its path relative to the current folder:
```suggestion
Puedes declarar una imagen asociada para una entrada de colecciones de contenido, como la imagen de portada de una entrada de blog, en tu metadatos utilizando su ruta relativa a la carpeta actual:
```

2023-08-29 10:23 UTC, Waxer59 commented
Listo!, gracias por la revisión 🤠

2023-08-29 16:01 UTC, sarah11918 commented
Looking great @Waxer59 & @dreyfus92 ! Please see the last minute change I made to the images page, 4. Removing Sharp in the main PR, and then I think we're calling the Image PR done!  :partying_face:

2023-08-29 16:24 UTC, dreyfus92 commented on src/content/docs/es/guides/images.mdx
> +    [Sharp](https://github.com/lovell/sharp) es ahora el servicio de imágenes por defecto utilizado para `astro:assets`. Ya no necesitas instalar la dependencia localmente en tu proyecto.
Cambia esto con esto a0bc8c528a725775caa452368185f12e3e90a825

2023-08-30 01:05 UTC, Yan-Thomas commented
> Did I miss any other commit?

I believe not! Thanks @Waxer59 🙌

2023-08-30 04:51 UTC, dreyfus92 approved these changes
LGTM ✅

2023-08-30 05:32 UTC, kevinzunigacuellar approved these changes
LGTM!

2023-08-30 10:16 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-08-30 10:16 UTC, merged