i18n(es): Update `reference/` `V3`
withastro/docs pull request #4409
Opened 2023-08-28 21:49 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- Closes # 
- What does this PR change? Give us a brief description.
Update `reference/` `V3` [`PR`](https://github.com/withastro/docs/pull/4166/files#diff-db473265321c7d52cab488e5f6e46ed80df851e219da93e3b6aa30e0d704d5af)

2023-08-29 18:52 UTC, dreyfus92 requested changes
Te dejo una pequeña sugerencia, buen trabajo @Waxer59 😁

2023-08-29 18:52 UTC, dreyfus92 commented on src/content/docs/es/reference/cli-reference.mdx
> +// Stop the server if needed
Falta traducir

2023-08-29 18:53 UTC, Waxer59 commented on src/content/docs/es/reference/cli-reference.mdx
> +// Stop the server if needed
```suggestion
// Detén el servidor si es necesario
```

2023-08-29 18:53 UTC, Waxer59 commented
Listo!, gracias por la revisión vaque

2023-08-29 19:06 UTC, Waxer59 commented
Commit applied: 
* [`c4d249`](https://github.com/withastro/docs/pull/4166/commits/c4d24997452599b85138582b2b3fa761753e76d8)

2023-08-29 19:16 UTC, Waxer59 commented
Commit (it has not been necessary to update the page):

* [`8190f7`](https://github.com/withastro/docs/pull/4166/commits/8190f7e1c737de336a0aad046b06164c733395e0)

2023-08-29 20:21 UTC, Waxer59 commented on src/content/docs/es/reference/adapter-reference.mdx
> +Establecer `functionPerRoute:true` en un entorno serverless crea un archivo JavaScript (controlador) para cada ruta. El nombre de un controlador puede variar según la plataforma de alojamiento que es
```suggestion
Establecer `functionPerRoute: true` en un entorno serverless crea un archivo JavaScript (controlador) para cada ruta. El nombre de un controlador puede variar según la plataforma de alojamiento que estés utilizando: lambda, función, página, etc.
```

2023-08-29 20:21 UTC, Waxer59 commented on src/content/docs/es/reference/adapter-reference.mdx
> +Con `functionPerRoute: false`, solo hay un controlador único encargado de renderizar todas tus rutas. Cuando se activa este controlador por primera vez, estarás sujeto a un arranque en frío. Después
```suggestion
Con `functionPerRoute: false`, solo hay un controlador único encargado de renderizar todas tus rutas. Cuando se activa este controlador por primera vez, estarás sujeto a un arranque en frío. Después de eso, todas las demás rutas deberían funcionar sin retraso. Sin embargo, perderás el beneficio de la división de código que proporciona `functionPerRoute: true`.
```

2023-08-29 20:22 UTC, Waxer59 commented
Commit:
* [`9a8f0a`](https://github.com/withastro/docs/pull/4166/commits/9a8f0a3880bd75b89b4c1ff44e9c20c246e8b687)

2023-08-30 01:08 UTC, Yan-Thomas approved these changes
LGTM! Thanks @Waxer59 🙌

2023-08-30 01:09 UTC, merged