i18n(fr-FR): Update `why-astro.mdx` v3 translation
withastro/docs pull request #4517
Opened 2023-09-02 12:41 UTC by McFlyPartages

#### What kind of changes does this PR include?
- Minor content fixes
- Updated content 

#### Description

Just update content of why-astro.mdx` with v3 of english doc

2023-09-02 12:43 UTC, McFlyPartages commented
This is my first PR.

I'm not a GitHub king so don't hesitate to tell me what's wrong or what can be improved.

Thanks

2023-09-03 06:43 UTC, McFlyPartages commented
Hy,

Sorry but i add `contribute.mdx`on the original push.

Sorry

2023-09-03 07:55 UTC, pioupia requested changes
A few minor problems, but it's a very good start!

2023-09-03 07:55 UTC, pioupia commented on src/content/docs/fr/concepts/why-astro.mdx
> +C'est l'une des différences les plus importantes à comprendre concernant Astro. a focalisation unique d'Astro sur le contenu lui permet de faire des compromis et d'offrir des performances inégalées q
```suggestion
C'est l'une des différences les plus importantes à comprendre concernant Astro. L'unique focalisation mise par Astro sur le contenu lui permet de faire des compromis et d'offrir des performances inégalées qui n'auraient pas de sens pour des frameworks web plus orientés applications.
```

2023-09-03 07:55 UTC, pioupia commented on src/content/docs/fr/concepts/why-astro.mdx
> +Si votre projet se situe dans le champ des "applications", Astro n'est peut-être pas le bon choix... **et ce n'est pas grave !** Consultez [Next.js](https://nextjs.org/) pour une alternative à Astro
```suggestion
Si votre projet se situe dans le deuxième camp des "applications", Astro n'est peut-être pas le bon choix... **et ce n'est pas grave !** Consultez [Next.js](https://nextjs.org/) pour une alternative à Astro plus axée sur les applications.
```

2023-09-03 07:55 UTC, pioupia commented on src/content/docs/fr/concepts/why-astro.mdx
> +**Astro privilégie autant que possible le rendu côté serveur par rapport au rendu côté client**. Il s'agit de la même approche que les frameworks traditionnels côté serveur -- PHP, WordPress, Laravel
We unlock the `rendu côté serveur`, no?
```suggestion
**Astro privilégie autant que possible le rendu côté serveur par rapport au rendu côté client**. Il s'agit de la même approche que les frameworks traditionnels côté serveur -- PHP, WordPress, Laravel, Ruby on Rails, etc. -- utilisent depuis des décennies. Mais vous n'avez pas besoin d'apprendre un deuxième langage côté serveur pour le débloquer. Avec Astro, tout se résume toujours à HTML, CSS et JavaScript (ou TypeScript, si vous préférez).
```

2023-09-03 07:55 UTC, pioupia commented on src/content/docs/fr/concepts/why-astro.mdx
> +Dans de nombreux frameworks web, il est facile de créer un site web qui semble parfait pendant le développement, mais qui se charge douloureusement lentement une fois déployé. JavaScript est souvent
```suggestion
Dans de nombreux frameworks web, il est facile de créer un site web qui semble parfait pendant le développement, mais dont le chargement est terriblement lent une fois déployé. JavaScript est souvent le coupable, car les téléphones des utilisateurs et les appareils moins puissants atteignent rarement la vitesse de l'ordinateur portable d'un développeur.
```

2023-09-03 07:55 UTC, pioupia commented on src/content/docs/fr/concepts/why-astro.mdx
> +Si vous avez besoin de plus de contrôle, vous pouvez étendre Astro avec plus de [100+ intégrations](https://astro.build/integrations/) comme [React](https://www.npmjs.com/package/@astrojs/react), [Sv
```suggestion
Si vous avez besoin de plus de contrôle, vous pouvez étendre Astro avec plus de [100+ intégrations](https://astro.build/integrations/) comme [React](https://www.npmjs.com/package/@astrojs/react), [Svelte](https://www.npmjs.com/package/@astrojs/svelte), [Vue](https://www.npmjs.com/package/@astrojs/vue), [Tailwind CSS](https://www.npmjs.com/package/@astrojs/tailwind), [MDX](https://www.npmjs.com/package/@astrojs/mdx), et plus encore. [Connectez votre CMS préféré](/fr/guides/cms/) ou [déployez sur votre hôte préféré](/fr/guides/deploy/) avec une seule commande.
```

2023-09-03 10:53 UTC, McFlyPartages commented
@pioupia thank you for your suggestions, I've just validated them (normally).

2023-09-03 11:42 UTC, McFlyPartages commented
I've corrected a few syntax URLs in the contribte file

2023-09-03 13:38 UTC, pioupia approved these changes
LGTM

2023-09-04 16:46 UTC, Yan-Thomas approved these changes
LGTM! Great work peeps 🙌

2023-09-04 16:47 UTC, merged