i18n(it): translate `core-concepts`, part 2
withastro/docs pull request #4530
Opened 2023-09-03 19:53 UTC by itsmatteomanf

#### What kind of changes does this PR include?

- Translated content

#### Description

Translates [framework-components.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/core-concepts/framework-components.mdx).

2023-09-19 13:11 UTC, csarnataro requested changes

2023-09-19 13:11 UTC, csarnataro commented on src/content/docs/it/core-concepts/framework-components.mdx
> +## Componenti della struttura inseriti l´uno nell'altro
**nitpick**: I would not use the prime symbol `´` for the apostrophe, since we're using the basic straight apostrophe `'` everywhere else.

2023-09-19 15:26 UTC, itsmatteomanf commented on src/content/docs/it/core-concepts/framework-components.mdx
> +title: Componenti del framework
That is a nice catch, you are right... let me think how to best put it.

2023-09-19 20:42 UTC, itsmatteomanf reviewed
Done everything. Still missing the only comment I replied to with a review.

2023-09-20 07:15 UTC, csarnataro commented on src/content/docs/it/core-concepts/framework-components.mdx
> +Ricorda: gli stessi file dei componenti del framework (ad esempio `.jsx`, `.svelte`) non possono mescolare più framework.
If you're referring to "ricordare", what I meant is that in technical translations it's quite more common to use "Attenzione" or "Nota", much more than "Ricorda" which seems more a colloquial term to me. 😄

2023-09-25 17:32 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps, I see you still were debating about a small wording but I am happy to get this one merged after so long, feel free to make another PR fixing the wording if necessary!

2023-09-25 17:32 UTC, merged