i18n(fr): Update the French glossary
withastro/docs pull request #4562
Opened 2023-09-05 20:53 UTC by pioupia

#### What kind of changes does this PR include?

- New or updated content

#### Description

- What does this PR change? Give us a brief description.
Updated the French glossary to add two words. I didn't know how to translate `Recipies` when I translated this file: https://github.com/withastro/docs/pull/4561. But I think `Méthodes` is a good translation.
And I've added the `Middleware` under the `Backend` and `Frontend` line in the tab.

2023-09-05 22:10 UTC, dreyfus92 commented on src/i18n/fr/README.md
> +| Recipies                     | Méthodes                                  |
```suggestion
| Recipes                      | Recettes                                  |
```

2023-09-05 22:15 UTC, dreyfus92 requested changes
Salut @pioupia, Je vous laisse une petite suggestion. Étant donné que les "recettes" font référence à la construction de quelque chose de manière figurative, par exemple (cuisiner  -> construire), je pense que nous devrions nous en tenir à la même idée. Qu’est-ce que tu en penses ?

2023-09-06 08:31 UTC, pioupia commented
> Salut @pioupia, Je vous laisse une petite suggestion. Étant donné que les "recettes" font référence à la construction de quelque chose de manière figurative, par exemple (cuisiner -> construire), je pense que nous devrions nous en tenir à la même idée. Qu’est-ce que tu en penses ?

Justement, la traduction initiale était `recette`. Le souci c'est que `recette` me semble beaucoup trop lié à la cuisine.
Je cite la définition du Larousse ([recette](https://www.larousse.fr/dictionnaires/francais/recette/66973)) :
`Description détaillée de la façon de préparer un mets.` -> Donc on a bien un rapport culinaire.
Je saute les autres définitions qui n'ont qu'un rapport financier.

Un synonyme semble adapté au propos :
- [procédé](https://www.larousse.fr/dictionnaires/francais/proc%C3%A9d%C3%A9/64051): `Manière de s'y prendre, méthode pratique pour faire quelque chose`

J'ai préférer choisir le mot [méthode (def.)](https://www.larousse.fr/dictionnaires/francais/m%C3%A9thode/50965), qui suit bien avec méthodologie, faire quelque chose méthodiquement. Sa définition est : `Manière de mener, selon une démarche raisonnée, une action, un travail, une activité ; technique`.

Pour moi, cela tient parfaitement au propos, et beaucoup mieux que [`recette`](https://www.larousse.fr/dictionnaires/francais/recette/66973), et discutablement mieux que [`procédé`](https://www.larousse.fr/dictionnaires/francais/proc%C3%A9d%C3%A9/64051). Qu'en penses-tu ?

2023-09-06 11:10 UTC, ElianCodes approved these changes
Hey @pioupia! Thanks for your translation!
I see you had a discussion with @dreyfus92, but eventually settled on using `Méthodes`.

Is this PR in it's final form / can it be merged?

2023-09-06 11:34 UTC, pioupia commented
> Hey @pioupia! Thanks for your translation! I see you had a discussion with @dreyfus92, but eventually settled on using `Méthodes`.
> 
> Is this PR in it's final form / can it be merged?

Thanks! I don't know @dreyfus92's opinion, but if you agree with the current translation, that's good for me.

2023-09-06 14:32 UTC, dreyfus92 approved these changes
Merci pour l’explication @pioupia, LGTM ✅

2023-09-06 17:31 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps

2023-09-06 17:31 UTC, merged