i18n(it): tutorial - unit 1 setup - part 1
withastro/docs pull request #4573
Opened 2023-09-06 16:27 UTC by csarnataro

#### What kind of changes does this PR include?

- Translated content

#### Description

- Added translation of Tutorial - Unit 1 Setup - First 2 files

2023-09-06 21:55 UTC, itsmatteomanf requested changes
Credo di aver trovato tutto, ma gli darò un'occhiata di giorno...

2023-09-06 21:55 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/1.mdx
> +Potrai accedere alla linea di comando usando un programma cosiddetto "Terminale" per il tuo sistema operativo. I terminali più diffusi sono **Terminale** (MacOS/Linux), **Prompt dei comandi** (Window
Non sono sicuro la scriverei in questo modo, personalmente. Probabilmente eviterei il "cosiddetto".

```suggestion
Potrai accedere alla linea di comando usando un programma terminale locale per il tuo sistema operativo. I terminali più diffusi sono **Terminale** (MacOS/Linux), **Prompt dei comandi** (Windows) o **Termux** (Android). Probabilmente uno di questi è già presente sulla tua macchina.
```

2023-09-06 21:55 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/1.mdx
> +Per eseguire Astro sul tuo computer devi avere installato [**Node.js**](https://nodejs.org/en/), versione `v16.12.0` o successive.
```suggestion
Per eseguire Astro sul tuo computer devi avere installato [**Node.js**](https://nodejs.org/it/), versione `v18.14.1` o successive.
```

2023-09-06 21:55 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/1.mdx
> +v16.14.0
```suggestion
v18.14.1
```

2023-09-06 21:55 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/1.mdx
> +Se il comando restituisce la versione `v16.12.0` o superiore, tutto a posto, puoi continuare.
```suggestion
Se il comando restituisce la versione `v18.14.1` o superiore, tutto a posto, puoi continuare.
```

2023-09-06 21:55 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/1.mdx
> +Se invece il comando restituisce un errore simile a `Command not found` o `Comando non trovato`, oppure una versione inferiore a `v16.12.0`, allora dovrai [installare una versione di Node.js compatib
A parte la versione, non so se tenere anche l'inglese o meno. @delucis, cosa ne dici?

```suggestion
Se invece il comando restituisce un errore simile a `Command 'node' not found` o `Comando 'node' non trovato`, oppure una versione inferiore a `v18.14.1`, allora dovrai [installare una versione di Node.js compatibile](https://docs.npmjs.com/downloading-and-installing-node-js-and-npm)
```

2023-09-06 21:55 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/1.mdx
> +- [ ] Ho accesso alla linea di comando in un terminale
Puntiglioso... ma l'ho notato ahah

```suggestion
- [ ] Ho accesso alla linea di comando in un terminale.
```

2023-09-06 21:55 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/index.mdx
> +i18nReady: true
Questo mi pare non debba esserci nelle singole traduzioni.

```suggestion
```

2023-09-06 21:55 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/index.mdx
> +:::tip[stackblitz]
Metterei il verbo, come la versione inglese.

```suggestion
:::tip[usare stackblitz]
```

2023-09-06 21:55 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/index.mdx
> +## Cosa andremo a realizzare
```suggestion
## Cosa andremo a realizzare?
```

2023-09-25 16:39 UTC, Yan-Thomas commented
This looks great @csarnataro, could you please update `index.md` so the (small) latest changes are incorporated here? See: https://github.com/withastro/docs/commits/main/src/content/docs/en/tutorial/1-setup/index.mdx

2023-09-26 16:27 UTC, Yan-Thomas approved these changes
LGTM! Thanks for the great work 💜

2023-09-26 16:27 UTC, merged