i18n(es): Update `styling.mdx` & `tina-cms.mdx`
withastro/docs pull request #4574
Opened 2023-09-06 17:35 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Update `styling.mdx` & `tina-cms.mdx`

`styling.mdx` [`58bc79a`](https://github.com/withastro/docs/commit/58bc79a6a39f5c25902a642f6e9579e8a43d8b91)

`tina-cms.mdx` [`a250850`](https://github.com/withastro/docs/commit/a2508507e6e87195eee6dfdadb887292fe40bfde)

2023-09-06 17:56 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59 😁, te dejo una pequeña sugerencia.

2023-09-06 17:56 UTC, dreyfus92 commented on src/content/docs/es/guides/styling.mdx
> +Puedes aplicar estilos globales a tu contenido de Markdown agregando [hojas de estilo importadas](#estilos-externos) al diseño que envuelve el contenido de tu página. También es posible estilizar tu
```suggestion
Puedes aplicar estilos globales a tu contenido de Markdown agregando [hojas de estilo importadas](#estilos-externos) a la plantilla que envuelve el contenido de tu página. También es posible estilizar tu Markdown con etiquetas [`<style is:global>`](#estilos-globales) en el componente de diseño. Ten en cuenta que cualquier estilo agregado está sujeto al [orden de cascada de Astro](#orden-de-cascada), por lo que debes revisar cuidadosamente tu página renderizada para asegurarte de que los estilos se apliquen como se pretende.
```

2023-09-06 17:57 UTC, Waxer59 commented
Listo!, gracias por la revisión 🤠

2023-09-11 18:07 UTC, Yan-Thomas approved these changes
LGTM! Great work peeps! 💜

2023-09-11 18:08 UTC, merged