i18n(es): Update `getting-started.md`
withastro/docs pull request #461
Opened 2022-05-06 12:53 UTC by agustinmulet

- [ ] Updated `getting-started` page
- [ ] Reviewed

2022-05-06 13:56 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +Quisimos hacer que probar Astro sea lo más simple posible, tanto en tu navegador como en tu máquina!
Solo una idea: `Empieza con Astro de manera sencilla en su navegador o máquina local`

2022-05-06 13:59 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +O bien puedes **correr nuestro proyecto base instantáneamente** con tan sólo el click de un botón:
correr -> ejecutar
base -> básico

2022-05-06 14:01 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +⚙️ Nuestra [Guía de instalación](/es/install/auto) tiene instrucciones paso a paso para instalar Astro utilizando tu administrador de paquetes favorito.
tu administrador de paquetes -> su gestor de paquetes

2022-05-06 14:02 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +Pon en marcha un nuevo proyecto local de manera instantánea con nuestro asistente de CLI `create-astro`!
asistente de CLI -> asistente de instalación (CLI)

2022-05-06 14:06 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +🏗️ Agrega nuevas [páginas de Astro (.astro)](/es/core-concepts/astro-pages) y/o [páginas de Markdown (.md)](/es/guides/markdown-content) a tu sitio.
a tu sitio web.

2022-05-06 14:07 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +🏗️ Agrega [CSS y estilos](/es/guides/styling) a tu sitio.
sitio web. 
Tambien podria ser proyecto

2022-05-06 14:08 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +🧰 Comienza tu próximo proyecto con un [tema pre-armado](https://astro.build/themes).
pre-armado a predeterminado

2022-05-06 14:10 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +🧰 Inspírate visitando nuestra [exhibición de sitios](https://astro.build/showcase).
lo mismo: sitios por sitios web o proyectos. El que elijas pienso que seria lo mas recomendado usarlos para todos los casos

2022-05-06 14:11 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +*... chequea nuestra [guía de integraciones](/es/guides/integrations-guide)*
Lea nuestra guia de integraciones

2022-05-06 14:13 UTC, kevinzunigacuellar requested changes
Me gusto muchisimo la traducion 😊, muchas gracias por el apoyo

2022-05-06 15:10 UTC, agustinmulet commented on src/pages/es/getting-started.md
> +🏗️ Agrega [CSS y estilos](/es/guides/styling) a tu sitio.
Me gusta proyecto! Creo que si en un futuro pueden construirse cosas distintas a web con Astro ya estaríamos cubiertos 🙌

2022-05-06 15:12 UTC, agustinmulet commented on src/pages/es/getting-started.md
> +🧰 Comienza tu próximo proyecto con un [tema pre-armado](https://astro.build/themes).
En inglés dice `prebuilt`, no crees que este caso sería más correcto pre-armado?

2022-05-06 15:52 UTC, kevinzunigacuellar commented on src/pages/es/getting-started.md
> +🧰 Comienza tu próximo proyecto con un [tema pre-armado](https://astro.build/themes).
si la verdad que suena raro, se me ocurrio plantillas prediseñadas que te parece?

2022-05-06 22:28 UTC, agustinmulet commented on src/pages/es/getting-started.md
> +🧰 Comienza tu próximo proyecto con un [tema pre-armado](https://astro.build/themes).
Me gusta! Ya lo cambio

2022-05-07 21:17 UTC, readonlychild commented
LGTM!

2022-05-07 21:17 UTC, merged