i18n(es): Translate `bun.mdx`
withastro/docs pull request #4637
Opened 2023-09-11 03:56 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translate `bun.mdx`

2023-09-11 21:58 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo una sugerencia 😁

2023-09-11 21:58 UTC, dreyfus92 commented on src/content/docs/es/recipes/bun.mdx
> +¿Usando Bun con Astro? ¡Agrega tu entrada de blog o video a esta página!
```suggestion
¿Estás usando Bun con Astro? ¡Agrega tu entrada de blog o video a esta página!
```

2023-09-12 07:02 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-09-13 16:37 UTC, dreyfus92 approved these changes
LGTM ✅

2023-09-13 16:50 UTC, Yan-Thomas approved these changes
LGTM! Great work peeps 🚀

2023-09-13 16:50 UTC, merged