i18n(zh-cn): update `guides/migrate-to-astro/from-jekyll.mdx`
withastro/docs pull request #4643
Opened 2023-09-11 07:24 UTC by 100gle

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

update `guides/migrate-to-astro/from-jekyll.mdx` since #4572

2023-09-12 00:54 UTC, liruifengv requested changes

2023-09-12 00:54 UTC, liruifengv commented on src/content/docs/zh-cn/guides/migrate-to-astro/from-jekyll.mdx
> +- 博客文章：[回到未来：我们技术博客从 Jekyll 过渡到 Astro](https://alasco.tech/2023/09/06/migrating-to-astro/).
```suggestion
- 博客文章：[回到未来：我们的技术博客从 Jekyll 过渡到 Astro](https://alasco.tech/2023/09/06/migrating-to-astro/)。
```

2023-09-12 12:23 UTC, liruifengv approved these changes
LGTM

2023-09-13 10:54 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps! 💜

2023-09-13 10:54 UTC, merged