i18n(es): Translate add-yaml-support.mdx
withastro/docs pull request #4670
Opened 2023-09-12 19:43 UTC by nabu1615

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Translate add-yaml-support.mdx

2023-09-12 20:06 UTC, dreyfus92 requested changes
Buen trabajo @nabu1615, te dejo una pequeña sugerencia.

2023-09-12 20:06 UTC, dreyfus92 commented on src/content/docs/es/recipes/add-yaml-support.mdx
> +i18nReady: false
```suggestion
i18nReady: true
```

2023-09-12 20:21 UTC, Waxer59 reviewed
Buena PR 🤠, te dejo una sugerencia

2023-09-12 20:21 UTC, Waxer59 commented on src/content/docs/es/recipes/add-yaml-support.mdx
> +      const value: any; // Añade la definición de tipo acá, si es necesario
```suggestion
      const value: any; // Agrega las definiciones de tipos aquí si así lo deseas.
```

2023-09-12 23:00 UTC, nabu1615 commented on src/content/docs/es/recipes/add-yaml-support.mdx
> +i18nReady: false
Done.

2023-09-12 23:01 UTC, nabu1615 commented on src/content/docs/es/recipes/add-yaml-support.mdx
> +      const value: any; // Añade la definición de tipo acá, si es necesario
Thanks, it looks clearer now.

2023-09-13 00:08 UTC, Waxer59 approved these changes
LGTM ✅

2023-09-13 01:06 UTC, dreyfus92 approved these changes
LGTM ✅

2023-09-13 10:44 UTC, Yan-Thomas approved these changes
LGTM! Welcome to Team Docs, @nabu1615!

2023-09-13 10:44 UTC, merged