i18n(zh-cn): update `guides/integrations-guide/vercel.mdx`
withastro/docs pull request #4706
Opened 2023-09-15 01:16 UTC by 100gle

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

update `guides/integrations-guide/vercel.mdx` since #4690

2023-09-15 11:37 UTC, Genteure requested changes

2023-09-15 11:37 UTC, Genteure commented on src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx
> +Allows you to configure which image service to use in development when [imageService](#imageservice) is enabled. This can be useful if you cannot install Sharp's dependencies on your development mach
```suggestion
```

Remove source text.

2023-09-16 00:58 UTC, 100gle commented
There are some updates from upstream #4713, please review again. @Genteure

2023-09-16 02:11 UTC, Genteure approved these changes
LGTM 👍

2023-09-16 02:11 UTC, Genteure commented on src/content/docs/zh-cn/guides/integrations-guide/vercel.mdx
> +启用后，在生产中会自动配置并使用由 Vercel Image Optimization API 提供支持的[图像服务](/zh-cn/reference/image-service-reference/) 。在开发中，将使用由[`devImageService`](#devimageservice) 指定的图像服务。
```suggestion
启用后，在生产中会自动配置并使用由 Vercel Image Optimization API 提供支持的[图像服务](/zh-cn/reference/image-service-reference/) 。在开发中，将使用由 [`devImageService`](#devimageservice) 指定的图像服务。
```

nit: formatting

2023-09-16 15:00 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🙌

2023-09-16 15:00 UTC, merged