i18n(es): Update `tutorial`
withastro/docs pull request #4707
Opened 2023-09-15 01:44 UTC by Waxer59

#### What kind of changes does this PR include?

- New or updated content
- Translated content

#### Description

- What does this PR change? Give us a brief description.
Update `tutorial` [`0b2ebea`](https://github.com/withastro/docs/commit/0b2ebea9fa080c30bd1b0308326fbc025b4e9073#diff-d4b2821dbf3833fa9a439e77e9af6b66f6286435054cee44ffdd2b027430e9ab)

2023-09-15 15:00 UTC, Waxer59 commented
add commit [`f607140`](https://github.com/withastro/docs/commit/f607140fb45e30a3adb212b85100d7bcb419a345)

2023-09-15 17:22 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo algunas sugerencias 😁

2023-09-15 17:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/2.mdx
> +La información en la parte superior del archivo, dentro de las vallas de código, se llama frontmatter. Estos datos -incluyendo etiquetas y una imagen de la publicación- son información *sobre* tu pub
```suggestion
La información en la parte superior del archivo, dentro de las vallas de código, se llama frontmatter. Estos datos -incluyendo etiquetas y una imagen de la publicación - son información *sobre* tu publicación que Astro puede usar. No aparece en la página automáticamente, pero accederás a ella más adelante en el tutorial para mejorar tu sitio. 
```

2023-09-15 17:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +## ¿Adónde vas?
```suggestion
## ¿A dónde vas?
```

2023-09-15 17:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/2-pages/index.mdx
> +## ¿Adónde vas?
```suggestion
## ¿A dónde vas?
```

2023-09-15 17:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/3-components/index.mdx
> +## ¿Adónde vas?
```suggestion
## ¿A dónde vas?
```

2023-09-15 17:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/4-layouts/index.mdx
> +## ¿Adónde vas?
```suggestion
## ¿A dónde vas?
```

2023-09-15 17:22 UTC, dreyfus92 commented on src/content/docs/es/tutorial/5-astro-api/index.mdx
> +## ¿Adónde vas?
```suggestion
## ¿A dónde vas?
```

2023-09-15 17:24 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-09-15 17:26 UTC, dreyfus92 approved these changes
LGTM ✅

2023-09-15 21:23 UTC, DavidEGiraldo approved these changes
LGTM 👍

2023-09-16 14:50 UTC, Yan-Thomas approved these changes
LGTM! Thank you everyone 🙌

2023-09-16 14:50 UTC, merged