add ru translation for Wordpress CMS guide
withastro/docs pull request #4711
Opened 2023-09-15 11:42 UTC by sbadulin

#### What kind of changes does this PR include?

- Translated content

#### Description

- Adding russian translation for [Wordpress CMS guide](https://docs.astro.build/ru/guides/cms/wordpress/)

2023-09-16 12:32 UTC, pvvrzv requested changes

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +Через этот API вам доступно большое количество данных, поэтому, вероятно, вы захотите получить только определенные поля. Вы можете ограничить ответ, добавив параметр [`_fields`](https://developer.wor
```suggestion
Через этот API вам доступно большое количество данных, поэтому, возможно, вы захотите получить только определенные поля. Вы можете выбрать их, добавив параметр [`_fields`](https://developer.wordpress.org/rest-api/using-the-rest-api/global-parameters/#_fields) к API URL, например: `[YOUR-SITE]/wp/v2/posts?_fields=author,id,excerpt,title,link`
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +В этом примере получение данных осуществляется через общедоступный WordPress API [https://norian.studio/dinosaurs/](https://norian.studio/dinosaurs/). Этот сайт WordPress сохраняет информацию о каждо
```suggestion
В этом примере получение данных осуществляется через публичный WordPress API сайта [https://norian.studio/dinosaurs/](https://norian.studio/dinosaurs/). Данный сайт хранит информацию о каждом отдельном динозавре по маршруту `dinos`, точно так же, как блог хранит отдельные записи по маршруту `posts`.
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +Этот пример показывает, как воспроизвести структуру этого сайта в Astro: индексную страницу, которая перечисляет динозавров со ссылками на динамически создаваемые отдельные страницы динозавров.
```suggestion
Этот пример показывает, как воспроизвести структуру этого сайта в Astro: главную страницу, на которой перечислены динозавры со ссылками на динамически создаваемые отдельные страницы динозавров.
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +В этом примере показывается получение данных с сайта WordPress, типы записей которого уже настроены и доступны для REST API.
```suggestion
Этот пример демонстрирует получение данных с сайта WordPress, типы записей которого уже настроены и доступны для REST API.
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +Страница `src/pages/index.astro` перечисляет каждого динозавра с описанием и ссылкой на его собственную страницу.
```suggestion
На странице `src/pages/index.astro` перечислены динозавры с описанием и ссылками на их собственные страницы.
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +Получение данных через API возвращает объект, внутри которого есть свойства:
```suggestion
Запрос к API возвращает объект, имеющий следующие поля:
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +- `slug` - Содержит slug поста. (Это позволит создать ссылку на динамически создаваемые отдельные страницы динозавров.)
```suggestion
- `slug` - Содержит [slug](https://docs.astro.build/ru/reference/api-reference/#slug) поста. (Это позволит создать ссылку на динамически создаваемые отдельные страницы динозавров.)
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +Возвращается свойство `_embedded['wp:featuredmedia']['0'].media_details.sizes.medium.source_url`, которое можно использовать для отображения изображения на каждой странице динозавра. (Замените `mediu
```suggestion
Возвращаемое свойство `_embedded['wp:featuredmedia']['0'].media_details.sizes.medium.source_url`, может быть использовано для отображения изображения на каждой странице динозавра. (Замените `medium` на необходимый вам размер изображения.)
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +## Сайты в продакшене
```suggestion
## Примеры сайтов
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +Следующие сайты используют Astro + WordPress в продакшене:
```suggestion
Следующие сайты используют Astro + WordPress:
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +- [Dinos!](https://wc-dinos.netlify.app/) от Аниндо Неел Дутты — [исходный код на GitHub](https://github.com/leen-neel/astro-wordpress)
```suggestion
- [Dinos!](https://wc-dinos.netlify.app/) от Аниндо Неел Дутты (Anindo Neel Dutta) — [исходный код на GitHub](https://github.com/leen-neel/astro-wordpress)
```

2023-09-16 12:32 UTC, pvvrzv commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +- [Soft Hard System](https://softhardsystem.com/) от Рафида Мухюмина Вафи — [исходный код на GitHub](https://github.com/RafidMuhymin/softhardsystem)
```suggestion
- [Soft Hard System](https://softhardsystem.com/) от Рафида Мухюмина Вафи (Rafid Muhymin Wafi) — [исходный код на GitHub](https://github.com/RafidMuhymin/softhardsystem)
```

2023-09-18 09:34 UTC, pvvrzv approved these changes

2023-09-18 17:57 UTC, Yan-Thomas commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +- `slug` - Содержит [slug](https://docs.astro.build/ru/reference/api-reference/#slug) поста. (Это позволит создать ссылку на динамически создаваемые отдельные страницы динозавров.)
Removing this link that doesn't exist in the original version
```suggestion
- `slug` - Содержит slug поста. (Это позволит создать ссылку на динамически создаваемые отдельные страницы динозавров.)
```

2023-09-18 17:59 UTC, Yan-Thomas commented on src/content/docs/ru/guides/cms/wordpress.mdx
> +Страница `src/pages/dinos/[slug].astro` [динамически создает страницу](/ru/core-concepts/routing/#dynamic-routes) для каждого динозавра.
```suggestion
Страница `src/pages/dinos/[slug].astro` [динамически создает страницу](/ru/core-concepts/routing/#динамические-маршруты) для каждого динозавра.
```

2023-09-18 18:07 UTC, Yan-Thomas approved these changes
LGTM! Great work peeps, and welcome to Team Docs @sbadulin 🙌 

I have fixed a few broken links for you, hope you don't mind!

2023-09-18 18:07 UTC, merged