i18n(fr): Update `getting-started` translation and glossary
withastro/docs pull request #4860
Opened 2023-09-28 21:25 UTC by alextison

#### What kind of changes does this PR include?

- Updated content
- Translated content

#### Description

- Update `getting-started` file to integrate the v3 banner
- Add a new word to glossary
- Replace a MD title by an HTML title to be iso with the rest of the docs

J'ai décidé d'intégrer `upgrade` au glossaire afin d'être sûr de sa tournure dans la documentation, afin qu'on utilise bien sa signification `mise à niveau` et non `améliorer`, n'hésitez pas à me faire part de vos retours :)

2023-09-29 07:14 UTC, McFlyPartages commented
Salut er merci pour le travail.
Je regarde mieux plus tard, mais il manque un import au début et aussi le ready:true dans le front matter.

;)

2023-09-29 09:56 UTC, alextison commented
J'ai ajouté l'import et la section correspondante ainsi que la propriété ready au sein du premier commit, en attente de tes retours :)

2023-09-29 10:52 UTC, thomasbnt requested changes

2023-09-29 10:52 UTC, thomasbnt commented on src/content/docs/fr/getting-started.mdx
> +Ces traductions de docs vous sont proposées par touces ces extraordinaires personnes. [Help us with translations!](https://github.com/withastro/docs/blob/main/contributor-guides/translating-astro-doc
Hello! 

Manque la traduction du lien `[Help us with translations!]`

2023-09-29 15:08 UTC, alextison commented on src/content/docs/fr/getting-started.mdx
> +Ces traductions de docs vous sont proposées par touces ces extraordinaires personnes. [Help us with translations!](https://github.com/withastro/docs/blob/main/contributor-guides/translating-astro-doc
Hello,
Petit oubli de ma part, c'est fix :)

2023-09-29 16:35 UTC, thomasbnt approved these changes
LGTM!

2023-09-29 20:55 UTC, McFlyPartages commented
LGTM

2023-10-01 12:41 UTC, Yan-Thomas approved these changes
LGTM! Thanks for this @alextison, welcome to Team Docs! 💜

2023-10-01 12:42 UTC, merged