i18n(fr) Update translated  routing file
withastro/docs pull request #4884
Opened 2023-09-30 12:48 UTC by McFlyPartages

#### What kind of changes does this PR include?

- Updated Translated content

2023-09-30 16:16 UTC, dreyfus92 requested changes
Super boulot @McFlyPartages, je vous laisse un petit suggestion 😁

2023-09-30 16:16 UTC, dreyfus92 commented on src/content/docs/fr/core-concepts/routing.mdx
> +src/pages/posts/1.md         -> mysite.com/posts/1
Je pense qu'on peut laisser la traduction comme `monsite`, qu'en pensez-vous?

2023-10-08 08:36 UTC, McFlyPartages commented
Une petite relecture pour valider  ?

2023-10-10 07:54 UTC, McFlyPartages commented
LGTM

2023-10-10 08:03 UTC, thomasbnt requested changes

2023-10-10 08:03 UTC, thomasbnt commented on src/content/docs/fr/core-concepts/routing.mdx
> +Astro utilise des éléments HTML [`<a>` (EN)](https://developer.mozilla.org/fr-FR/docs/Web/HTML/Element/a) standards pour naviguer entre les routes. Il n'y a pas de composant `<Link>` spécifique au fr
`Le document est disponible en français et l'URL est bonne. Retirer la mention `(EN)` sur le lien.

2023-10-10 09:58 UTC, McFlyPartages commented on src/content/docs/fr/core-concepts/routing.mdx
> +Astro utilise des éléments HTML [`<a>` (EN)](https://developer.mozilla.org/fr-FR/docs/Web/HTML/Element/a) standards pour naviguer entre les routes. Il n'y a pas de composant `<Link>` spécifique au fr
C'est fait merci

2023-10-10 16:27 UTC, thomasbnt approved these changes
LGTM!

2023-10-10 16:53 UTC, Yan-Thomas commented
Looks like the redirects section is missing? Could you take a look at this? https://docs.astro.build/en/core-concepts/routing/#redirects

2023-10-13 07:38 UTC, McFlyPartages commented
> Looks like the redirects section is missing? Could you take a look at this? https://docs.astro.build/en/core-concepts/routing/#redirects
Ohh sorry, it's now OK. Thanks for remark

2023-10-13 07:49 UTC, McFlyPartages commented
LGTM

2023-10-21 13:10 UTC, Yan-Thomas commented on src/content/docs/fr/core-concepts/routing.mdx
>  ## Pagination Imbriquée
```suggestion
### Pagination Imbriquée
```

2023-10-21 13:18 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-10-21 13:18 UTC, merged