i18n(fr) Update translated client-side-scripts.mdx
withastro/docs pull request #4889
Opened 2023-09-30 15:39 UTC by McFlyPartages

#### What kind of changes does this PR include?
- Updated Translated content

2023-10-08 08:50 UTC, McFlyPartages reviewed
Update with fix orthographe

2023-10-08 08:50 UTC, McFlyPartages commented on src/content/docs/fr/guides/client-side-scripts.mdx
> +## Client-Side Scripts
```suggestion
## Script côté client
```

2023-10-08 08:50 UTC, McFlyPartages commented on src/content/docs/fr/guides/client-side-scripts.mdx
> +  // Les imports locales ne seront pas résolues et ne fonctionneront pas.
```suggestion
  // Les imports localaux ne seront pas résolus et ne fonctionneront pas.
```

2023-10-08 08:51 UTC, McFlyPartages commented
Une petite relecture ?

2023-10-10 07:56 UTC, pioupia commented
You need to close the script tag line 62:
https://github.com/McFlyPartages/docs_astro/blob/trans_fr_client_side_scripts/src/content/docs/fr/guides/client-side-scripts.mdx#L62

2023-10-10 08:34 UTC, McFlyPartages commented
> You need to close the script tag line 62: https://github.com/McFlyPartages/docs_astro/blob/trans_fr_client_side_scripts/src/content/docs/fr/guides/client-side-scripts.mdx#L62

c'est corrigé

2023-10-13 07:48 UTC, McFlyPartages commented
Je viens de balayer de nouveau pour le problème avec <script> je ne trouve pas

2023-10-23 17:57 UTC, Yan-Thomas commented on src/content/docs/fr/guides/client-side-scripts.mdx
> +Vous pouvez vouloir écrire vos scripts comme des fichiers `.js`/`.ts` séparés ou avoir besoin de référencer un script externe sur un autre serveur. Vous pouvez le faire en les référençant dans l'attr
```suggestion
Vous pouvez vouloir écrire vos scripts comme des fichiers `.js`/`.ts` séparés ou avoir besoin de référencer un script externe sur un autre serveur. Vous pouvez le faire en les référençant dans l'attribut src' d'une balise `<script>`.
```

2023-10-23 17:57 UTC, Yan-Thomas commented
The rendering of this page should be fixed now! 🙌

2023-10-23 18:23 UTC, dreyfus92 reviewed
Salut @McFlyPartages, pour fixer le problème avec le CI/CD, vous pouvez remplacer le fragment par le suivant: #utilisation-du-script-dans-astro

2023-10-23 20:24 UTC, McFlyPartages commented
> Salut @McFlyPartages, pour fixer le problème avec le CI/CD, vous pouvez remplacer le fragment par le suivant: `#utilisation-du-script-dans-astro`

Je regarde ca demain, merci

2023-10-24 19:34 UTC, thomasbnt requested changes
Une touuuuuuuute petite erreur, mais après ça me semble LGTM! 🚀🚀🚀

2023-10-24 19:34 UTC, thomasbnt commented on src/content/docs/fr/guides/client-side-scripts.mdx
> +  // Les imports localaux ne seront pas résolus et ne fonctionneront pas.
"localaux" -> "locaux"

2023-10-24 20:56 UTC, McFlyPartages commented on src/content/docs/fr/guides/client-side-scripts.mdx
> +  // Les imports localaux ne seront pas résolus et ne fonctionneront pas.
C'est fait

2023-10-24 20:56 UTC, McFlyPartages commented
> Salut @McFlyPartages, pour fixer le problème avec le CI/CD, vous pouvez remplacer le fragment par le suivant: `#utilisation-du-script-dans-astro`

C'est fait Merci

2023-10-24 21:01 UTC, dreyfus92 approved these changes
LGTM ✅

2023-10-24 23:20 UTC, thomasbnt approved these changes
LGTM!

2023-10-25 11:21 UTC, Yan-Thomas approved these changes
LGTM! Great work everyone 🙌

2023-10-25 11:21 UTC, merged