i18n(fr) Update and Translate render.mdx
withastro/docs pull request #4893
Opened 2023-09-30 20:23 UTC by McFlyPartages

#### What kind of changes does this PR include?
- Minor content fixes (broken links, typos, etc.)
- Updated and Translated content

2023-09-30 20:40 UTC, dreyfus92 requested changes
Super b @McFlyPartages, voici un mineur suggestion.

2023-09-30 20:40 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/render.mdx
> +3.Connectez votre dépôt [GitHub](https://github.com/) ou [GitLab](https://about.gitlab.com/) ou entrez l'URL publique d'un dépôt public.
```suggestion
3. Connectez votre dépôt [GitHub](https://github.com/) ou [GitLab](https://about.gitlab.com/) ou entrez l'URL publique d'un dépôt public.
```

2023-10-02 22:46 UTC, thomasbnt requested changes

2023-10-02 22:46 UTC, thomasbnt commented on src/content/docs/fr/guides/deploy/render.mdx
> +   - **Environment variables (advanced)**: (Variables d'environnement) Par défaut, Render utilise Node.js 14.17.0, mais Astro [nécessite une version supérieure](/fr/install/auto/#prérequis).  Ajoutez
`file to your project to specify a Node.js version.`
Hello ! Il manque de la traduction par ici!

2023-10-08 08:57 UTC, McFlyPartages commented
LGTM

2023-10-08 14:06 UTC, thomasbnt approved these changes
LGTM

2023-10-08 17:15 UTC, Yan-Thomas approved these changes
LGTM! Great work 🙌

2023-10-08 17:15 UTC, merged