i18n(fr) Update an translate environment variables.mdx
withastro/docs pull request #4902
Opened 2023-10-01 09:03 UTC by McFlyPartages

#### What kind of changes does this PR include?
- Updated and translated content

2023-10-02 22:38 UTC, thomasbnt commented
Miss two parts on the file.

- "Customising output filenames"
https://deploy-preview-4902--astro-docs-2.netlify.app/en/guides/configuring-astro/#customising-output-filenames

- "environnement variables"
https://deploy-preview-4902--astro-docs-2.netlify.app/en/guides/configuring-astro/#environment-variables

2023-10-08 09:09 UTC, McFlyPartages commented
> Miss two parts on the file.

Je ne comprends pas ce ne sont pas les mêmes fichiers ?

2023-10-08 14:13 UTC, thomasbnt commented
> > Miss two parts on the file.
> 
> Je ne comprends pas ce ne sont pas les mêmes fichiers ?

En anglais, il y a ces deux parties qu'y sont marqués, et pas dans cette traduction 😄

2023-10-08 17:47 UTC, McFlyPartages commented
> > > Miss two parts on the file.
> > 
> > 
> > Je ne comprends pas ce ne sont pas les mêmes fichiers ?
> 
> En anglais, il y a ces deux parties qu'y sont marqués, et pas dans cette traduction 😄
> 
> ![418o3](https://user-images.githubusercontent.com/14293805/273453724-de63414b-7a7e-44d2-b817-5fa3a867d9a1.png)
> 
> ![shndn](https://user-images.githubusercontent.com/14293805/273453746-4b21f09e-af8f-4c53-88be-561b4a3009f5.png)

Je n'ai pas ça dans la version officielle, https://docs.astro.build/en/guides/environment-variables/ tu m'indique une preview dans ton lien.

2023-10-09 12:05 UTC, thomasbnt commented
@McFlyPartages  Ah my bad, je suis allé sur une autre partie de documentation :joy:

2023-10-09 12:16 UTC, thomasbnt requested changes

2023-10-09 12:16 UTC, thomasbnt commented on src/content/docs/fr/guides/environment-variables.mdx
> +- `import.meta.env.BASE_URL` : L'URL de base à partir de laquelle votre site est servi. Elle est déterminée par l'option de configuration [`base`] (/fr/reference/configuration-reference/#base).
`[`base`] (/fr/reference/configuration-reference/#base)` erreur de lien

2023-10-09 12:16 UTC, thomasbnt commented on src/content/docs/fr/guides/environment-variables.mdx
> +Lorsque vous utilisez SSR, les variables d'environnement peuvent être accédées au moment de l'exécution en fonction de l'adaptateur SSR utilisé. Avec la plupart des adaptateurs, vous pouvez accéder a
`(/en/guides/guide-intégration/cloudflare` mettre le lien en `/fr/` comme indiqué sur le GH Actions Check Links

2023-10-09 14:55 UTC, McFlyPartages commented on src/content/docs/fr/guides/environment-variables.mdx
> +Lorsque vous utilisez SSR, les variables d'environnement peuvent être accédées au moment de l'exécution en fonction de l'adaptateur SSR utilisé. Avec la plupart des adaptateurs, vous pouvez accéder a
Merci je fais ca se soir

2023-10-09 14:56 UTC, McFlyPartages commented
> @McFlyPartages Ah my bad, je suis allé sur une autre partie de documentation 😂

Pasde souvis mais je commencaisa m'inquiéter lol

2023-10-10 08:02 UTC, McFlyPartages commented on src/content/docs/fr/guides/environment-variables.mdx
> +Lorsque vous utilisez SSR, les variables d'environnement peuvent être accédées au moment de l'exécution en fonction de l'adaptateur SSR utilisé. Avec la plupart des adaptateurs, vous pouvez accéder a
C'est fait Merci

2023-10-10 08:07 UTC, thomasbnt approved these changes
Lgtm!

2023-10-10 10:53 UTC, Yan-Thomas commented on src/content/docs/fr/guides/environment-variables.mdx
> +Lorsque vous utilisez SSR, les variables d'environnement peuvent être accédées au moment de l'exécution en fonction de l'adaptateur SSR utilisé. Avec la plupart des adaptateurs, vous pouvez accéder a
```suggestion
Lorsque vous utilisez SSR, les variables d'environnement peuvent être accédées au moment de l'exécution en fonction de l'adaptateur SSR utilisé. Avec la plupart des adaptateurs, vous pouvez accéder aux variables d'environnement avec `process.env`, mais certains adaptateurs fonctionnent différemment. Pour l'adaptateur Deno, vous utiliserez `Deno.env.get()`. Voir comment [accéder au runtime Cloudflare](/fr/guides/integrations-guide/cloudflare/#cloudflare-runtime) pour gérer les variables d'environnement lors de l'utilisation de l'adaptateur Cloudflare. Astro vérifiera d'abord l'environnement du serveur pour les variables, et si elles n'existent pas, Astro les cherchera dans les fichiers .env.
```

2023-10-10 16:09 UTC, McFlyPartages commented
Merge with PR #4892

2023-10-10 16:09 UTC, closed without merging