i18n(es): update `cloudflare.mdx`
withastro/docs pull request #4931
Opened 2023-10-03 11:20 UTC by Mardroide

#### What kind of changes does this PR include?
- New or updated content

#### Reference
- [69c3ebd](https://github.com/withastro/docs/commit/69c3ebd748889429cf1f1b1a42e02bd2b0281cd7)

2023-10-03 14:46 UTC, dreyfus92 requested changes
Buen trabajo @Mardroide, te dejo algunas sugerencias. Quería dejarte una tercera pero no me dejo github agregrar un comentario en la línea 97 el fragmento para arreglar el enlace es `#rutas-personalizadas-_routesjson` 😁

2023-10-03 14:46 UTC, dreyfus92 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +El Cloudflare Runtime incluye [Enlaces Cloudflare](https://developers.cloudflare.com/pages/platform/functions/bindings), [variables de entorno](https://developers.cloudflare.com/pages/platform/functi
```suggestion
El Cloudflare Runtime incluye [Enlaces Cloudflare](https://developers.cloudflare.com/pages/platform/functions/bindings), [variables de entorno](https://developers.cloudflare.com/pages/platform/functions/bindings/#environment-variables), y el [cf object](https://developers.cloudflare.com/workers/runtime-apis/request/#incomingrequestcfproperties). Más información sobre [acceso al tiempo de ejecución de Cloudflare](#tiempo-de-ejecución-de-cloudflare).
```

2023-10-04 00:48 UTC, Waxer59 requested changes
Buena PR 🤠, te dejo unas sugerencias. Aparte de la revisión tendrias que arreglar los enlaces

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Para compilar un paquete separado para cada página, establece la opción `functionPerRoute` en la configuración de tu adaptador de Cloudflare. Esta opción requiere un mantenimiento manual de la carpet
```suggestion
Para compilar un paquete separado para cada página, establece la opción `functionPerRoute` en la configuración de tu adaptador de Cloudflare. Esta opción requiere un mantenimiento manual de la carpeta `functions`. Los archivos emitidos por Astro sobrescribirán los archivos existentes con nombres idénticos en la carpeta `functions`, por lo que debes elegir nombres de archivo únicos para cada archivo que añadas manualmente. Además, el adaptador nunca vaciará la carpeta `functions` de archivos obsoletos, por lo que deberás limpiar la carpeta manualmente cuando elimines páginas.
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +El Cloudflare Runtime incluye [Enlaces Cloudflare](https://developers.cloudflare.com/pages/platform/functions/bindings), [variables de entorno](https://developers.cloudflare.com/pages/platform/functi
```suggestion
El Runtime de Cloudflare incluye [Cloudflare Bindings](https://developers.cloudflare.com/pages/platform/functions/bindings), [variables de entorno](https://developers.cloudflare.com/pages/platform/functions/bindings/#environment-variables), y el [objeto cf](https://developers.cloudflare.com/workers/runtime-apis/request/#incomingrequestcfproperties). Obtén más información sobre [cómo acceder al Runtime de Cloudflare](#tiempo-de-ejecución-de-cloudflare).
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +## Tiempo de ejecución de Cloudflare
```suggestion
## Runtime de Cloudflare
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Puedes acceder al tiempo de ejecución de los componentes Astro a través de `Astro.locals` dentro de cualquier archivo .astro\`.
```suggestion
Puedes acceder al runtime desde los componentes de Astro a través de `Astro.locals` dentro de cualquier archivo .astro\`.
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Te da acceso a [variables de entorno](https://developers.cloudflare.com/pages/platform/functions/bindings/#environment-variables).
```suggestion
Te proporciona acceso a [variables de entorno](https://developers.cloudflare.com/pages/platform/functions/bindings/#environment-variables).
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Puedes acceder al tiempo de ejecución desde los puntos finales de la API a través de `context.locals`:
```suggestion
Puedes acceder al runtime desde los endpoints de la API a través de `context.locals`:
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Puedes adjuntar [cabeceras personalizadas](https://developers.cloudflare.com/pages/platform/headers/) a tus respuestas añadiendo un archivo `_headers` en la carpeta `public/` de tu proyecto de Astro.
```suggestion
Puedes adjuntar [cabeceras personalizadas](https://developers.cloudflare.com/pages/platform/headers/) a tus respuestas añadiendo un archivo `_headers` en la carpeta `public/` de tu proyecto de Astro. Este archivo se copiará al directorio de salida de tu compilación.
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Puedes declarar [redirecciones personalizadas](https://developers.cloudflare.com/pages/platform/redirects/) utilizando Cloudflare Pages. Esto le permite redirigir las peticiones a una URL diferente.
```suggestion
Puedes declarar [redirecciones personalizadas](https://developers.cloudflare.com/pages/platform/redirects/) utilizando Cloudflare Pages. Esto te permite redirigir las peticiones a una URL diferente. Puedes añadir un archivo `_redirects` en la carpeta `public/` de tu proyecto de Astro. Este archivo se copiará en el directorio de salida de tu compilación.
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Puedes definir qué rutas invocan funciones y cuáles son activos estáticos, utilizando [Enrutamiento de Cloudflare](https://developers.cloudflare.com/pages/platform/functions/routing/#functions-invoca
```suggestion
Puedes definir qué rutas invocan funciones y cuáles son assets estáticos, utilizando el [enrutamiento de Cloudflare](https://developers.cloudflare.com/pages/platform/functions/routing/#functions-invocation-routes) a través de un archivo `_routes.json`. Este archivo es generado automáticamente por Astro.
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Por defecto, `@astrojs/cloudflare` generará un archivo `_routes.json` con reglas `include` y `exclude` basadas en las rutas dinámicas y estáticas de sus aplicaciones.
```suggestion
Por defecto, `@astrojs/cloudflare` generará un archivo `_routes.json` con reglas `include` y `exclude` basadas en las rutas dinámicas y estáticas de tu aplicación.
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Esto permitirá a Cloudflare servir archivos y procesar redirecciones estáticas sin una invocación de función. La creación de un `_routes.json` personalizado anulará esta optimización automática. Cons
```suggestion
Esto permitirá a Cloudflare servir archivos y procesar redirecciones estáticas sin una invocar una función. La creación de un `_routes.json` personalizado anulará esta optimización automática. Consulta [la documentación de Cloudflare sobre la creación de un `routes.json` personalizado](https://developers.cloudflare.com/pages/platform/functions/routing/#create-a-_routesjson-file) para más detalles.
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Además, deberás habilitar la Bandera de Compatibilidad en Cloudflare. La configuración de esta bandera puede variar según donde implementes tu sitio de Astro. Para obtener información detallada, cons
```suggestion
Además, deberás habilitar la Bandera de Compatibilidad en Cloudflare. La configuración de esta bandera puede variar según donde implementes tu sitio de Astro. Para obtener orientación detallada, consulta la [documentación de Cloudflare sobre cómo habilitar la compatibilidad con Node.js](https://developers.cloudflare.com/workers/runtime-apis/nodejs).
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Para utilizar [`wrangler`](https://developers.cloudflare.com/workers/wrangler/) para ejecutar tu aplicación localmente, actualiza el script de previsualización:
```suggestion
Para utilizar [`wrangler`](https://developers.cloudflare.com/workers/wrangler/) y ejecutar tu aplicación localmente, actualiza el script de vista previa:
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Si necesitas ayuda, visita el canal `#support` en [Discord](https://astro.build/chat). Nuestros amables miembros del equipo de soporte están aquí para ayudarte.
```suggestion
Para obtener ayuda, visita el canal `#support` en [Discord](https://astro.build/chat). ¡Nuestros amables miembros del equipo de soporte están aquí para ayudarte!
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +[`wrangler`](https://developers.cloudflare.com/workers/wrangler/) le da acceso a [Enlaces de Cloudflare](https://developers.cloudflare.com/pages/platform/functions/bindings), [variables de entorno](h
```suggestion
[`wrangler`](https://developers.cloudflare.com/workers/wrangler/) te proporciona acceso a [Cloudflare Bindings](https://developers.cloudflare.com/pages/platform/functions/bindings), [variables de entorno](https://developers.cloudflare.com/pages/platform/functions/bindings/#environment-variables), y al [objeto cf](https://developers.cloudflare.com/workers/runtime-apis/request/#incomingrequestcfproperties). Conseguir que la recarga en caliente o el servidor astro dev funcionen con Wrangler puede requerir una configuración personalizada. Consulta los [ejemplos de la comunidad](https://github.com/withastro/roadmap/discussions/590).
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +* `off`: no hay acceso al runtime de Cloudflare usando `astro dev`. También puedes usar [Vista previa con Wrangler](#preview-with-wrangler)
```suggestion
* `off`: no tiene acceso al runtime de Cloudflare usando `astro dev`. Alternativamente, puedes usar [Vista previa con Wrangler](#preview-with-wrangler).
```

2023-10-04 00:48 UTC, Waxer59 commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +* `local`: utiliza bindings mocking y placeholders localmente estáticos
```suggestion
* `local`: utiliza simulaciones de bindings y placeholders estáticos locales.
```

2023-10-04 09:14 UTC, Waxer59 approved these changes
Después de arreglar los enlaces LGTM ✅

2023-10-04 11:31 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps. I went ahead and fixed some links 🙌

2023-10-04 11:32 UTC, merged

2023-10-05 02:13 UTC, santiemanuel commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Determina como `routes.json` será generado si no se provee un [_routes.json](#rutas-personalizadas-_routesjson) personalizado.
Falta la tilde de cómo.

2023-10-05 02:18 UTC, santiemanuel commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Determina si y como el Runtime de Cloudflare es añadido a `astro dev`.
Falta la tilde de cómo.

2023-10-05 02:22 UTC, santiemanuel commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Puedes acceder al runtime desde los componentes de Astro a través de `Astro.locals` dentro de cualquier archivo .astro\`.
Aquí creo que el nombre de archivo tiene incompleto el estilo inline. En el source English también existe el problema:

> You can access the runtime from Astro components through `Astro.locals` inside any .astro` file.

2023-10-05 02:24 UTC, santiemanuel commented on src/content/docs/es/guides/integrations-guide/cloudflare.mdx
> +Esto permitirá a Cloudflare servir archivos y procesar redirecciones estáticas sin una invocar una función. La creación de un `_routes.json` personalizado anulará esta optimización automática. Consul
"...redirecciones estáticas sin una invocar una función." debería decir "...redirecciones estáticas sin invocar una función."