i18n(it): tutorial setup - page 4 and 5
withastro/docs pull request #4944
Opened 2023-10-04 12:15 UTC by csarnataro

#### What kind of changes does this PR include?

- Translated content

#### Description
    Added Italian translations for page 4 and 5 of the setup section of the tutorial

#### Related Issue / Implementation PR

- Closes Issue #

2023-10-04 19:57 UTC, lutaok requested changes

2023-10-04 19:57 UTC, lutaok commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +4. Ti verranno presentate altre opzioni per i passi successivi, ma non ne avrai bisogno, semplicemente prendi nota dell'URL del tuo repository. A questo  punto puoi uscire dalla pagina senza fare nie
Whitespace removal
```suggestion
4. Ti verranno presentate altre opzioni per i passi successivi, ma non ne avrai bisogno, semplicemente prendi nota dell'URL del tuo repository. A questo punto puoi uscire dalla pagina senza fare nient'altro.
```

2023-10-04 19:57 UTC, lutaok commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +3. Selezione <kbd>Add remote from GitHub</kbd>. Se necessario autenticati seguento le istruzioni, poi ritorna a VS Code e ripeti questa azione.
There are some typos:

```suggestion
3. Seleziona <kbd>Add remote from GitHub</kbd>. Se necessario autenticati seguendo le istruzioni, poi ritorna a VS Code e ripeti questa azione.
```

2023-10-04 19:57 UTC, lutaok commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +Per verificare se il tuo progetto è stato salvato su GitHub, visita GitHub.com e cerca all'interno del tuo account l'elenco dei tuoi repository. Scegli l'ultimo che hai creato e verifica che contiene
```suggestion
Per verificare se il tuo progetto è stato salvato su GitHub, visita GitHub.com e cerca all'interno del tuo account l'elenco dei tuoi repository. Scegli l'ultimo che hai creato e verifica che contenga i file del tuo progetto Astro.
```

2023-10-04 19:57 UTC, lutaok commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +- <p>[Utilizzare il sistema di controllo delle versioni Git in VS Code](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-support) <Badge>external</Badge></p>
```suggestion
- <p>[Utilizzare il sistema di versionamento Git in VS Code](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-support) <Badge>external</Badge></p>
```

2023-10-04 19:57 UTC, lutaok commented on src/content/docs/it/tutorial/1-setup/5.mdx
> +  - Aggiungi il tuo repository GitHub come nuova appliazione Netlify
Typo here
```suggestion
  - Aggiungi il tuo repository GitHub come nuova applicazione Netlify
```

2023-10-04 19:57 UTC, lutaok commented on src/content/docs/it/tutorial/1-setup/5.mdx
> +    Ti verrà richiesto di connetterti a un servizio Git. Scegli GitHub e segui i passi che ti vengono mostrati a video per autenticare il tuo accoung GitHub.
Typo here:

```suggestion
    Ti verrà richiesto di connetterti a un servizio Git. Scegli GitHub e segui i passi che ti vengono mostrati a video per autenticare il tuo account GitHub.
```

2023-10-04 20:17 UTC, itsmatteomanf requested changes
Not bad for a first PR! A few changes :)

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +i18nReady: true
```suggestion

```

This is just for the primary version... it's not really clear from the variable itself.

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +Nella sezione precedente hai fatto alcune modifiche al contenuto della pagina. Questo significa che i file del tuo progetto sono cambiati, quindi VS Code mosterà un numero sopa l'icona "Source" nel m
```suggestion
Nella sezione precedente hai fatto alcune modifiche al contenuto della pagina. Questo significa che i file del tuo progetto sono cambiati, quindi VS Code mosterà un numero sopa l'icona "Sorgente" nel menu. La scheda "Sorgente" ti sarà utile per fare il commit dei tuoi file periodicamente su GitHub.
```

VS Code is available in Italian, so we translate the menu names.

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +2. Fai clic sul menu <kbd>•••</kbd> "3 puntini" appena sopra il messaggio di commit e scegli <kbd>Remote</kbd> > <kbd>Add Remote</kbd>.
```suggestion
2. Fai clic sul menu <kbd>•••</kbd> "3 puntini" appena sopra il messaggio di commit e scegli <kbd>Repository remoto</kbd> > <kbd>Aggiungi repository remoto</kbd>.
```

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +1. Fai clic sulla scheda "Source Control" in VS Code per vedere un elenco di file che sono cambiati. Se vedi un messaggio che ti chiede di installare `git`, segui le istruzioni e poi riavvia VS Code.
```suggestion
1. Fai clic sulla scheda "Controllo del codice sorgente" in VS Code per vedere un elenco di file che sono cambiati. Se vedi un messaggio che ti chiede di installare `git`, segui le istruzioni e poi riavvia VS Code.
```

See above.

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +3. Selezione <kbd>Add remote from GitHub</kbd>. Se necessario autenticati seguento le istruzioni, poi ritorna a VS Code e ripeti questa azione.
```suggestion
3. Seleziona <kbd>Aggiungi repository remoto da GitHub</kbd>. Se necessario autenticati seguendo le istruzioni, poi ritorna a VS Code e ripeti questa azione.
```

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +6. Potresti vedere un messaggio che ti informa che non hai "staged commits", e che ti chiede se vuoi inserirli nell'area di stage. Fai clic su <kbd>Always</kbd> e continua.
```suggestion
6. Potresti vedere un messaggio che ti informa che non hai "commit preparate", e che ti chiede se vuoi inserirli nell'area di preparazione. Fai clic su <kbd>Sempre</kbd> e continua.
```

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +7. Infine, l'elenco dei file modificato dovrebbe essere sostituito da un pulsante <kbd>Publish</kbd>. Fai clic per inviare i tuoi file salavati su GitHub.
```suggestion
7. Infine, l'elenco dei file modificato dovrebbe essere sostituito da un pulsante <kbd>Pubblica</kbd>. Fai clic per inviare i tuoi file salvati su GitHub.
```

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/4.mdx
> +- <p>[Utilizzare il sistema di controllo delle versioni Git in VS Code](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-support) <Badge>external</Badge></p>
```suggestion
- <p>[Utilizzare il sistema di versionamento Git in VS Code](https://code.visualstudio.com/docs/sourcecontrol/overview#_git-support) <Badge>esterno</Badge></p>
```

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/5.mdx
> +    Prendi nota del tuo username. Potrai vedere il tuo pannello di controllo a tutti i siti che hai creato all'indirizzo `https://app.netlify.com/teams/username`
```suggestion

    Prendi nota del tuo username. Potrai vedere il tuo pannello di controllo a tutti i siti che hai creato all'indirizzo `https://app.netlify.com/teams/username`
```

Missing return.

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/5.mdx
> +    Poi scegli il repository GitHub del tuo progetto Astro dall'elenco mostrato.
Here you going to the next line, but you shouldn't.

```suggestion

```

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/5.mdx
> +    Ti verrà richiesto di connetterti a un servizio Git. Scegli GitHub e segui i passi che ti vengono mostrati a video per autenticare il tuo accoung GitHub.
```suggestion
    Ti verrà richiesto di connetterti a un servizio Git. Scegli GitHub e segui i passi che ti vengono mostrati a video per autenticare il tuo account GitHub. Poi scegli il repository GitHub del tuo progetto Astro dall'elenco mostrato.
```

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/5.mdx
> +Nell'anteprima del tuo sito su Netlify noterai che il tuo progetto avrà un nome generato casualmente, e l'URL del tuo sito sarà nella forma `https://project-name-123456.netlify.app`. Se vuoi puoi cam
```suggestion
Nell'anteprima del tuo sito su Netlify noterai che il tuo progetto avrà un nome generato casualmente, e l'URL del tuo sito sarà nella forma `https://nome-progetto-123456.netlify.app`. Se vuoi puoi cambiare il nome in qualcosa di più semplice da memorizzare, e l'URL si aggiornerà automaticamente di conseguenza.
```

It's not a massive change, but let's translate everything.

2023-10-04 20:17 UTC, itsmatteomanf commented on src/content/docs/it/tutorial/1-setup/5.mdx
> +- <p>[Una guida passo passo per pubblicare su Netlify](https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/) <Badge>external</Badge></p>
```suggestion
- <p>[Una guida passo passo per pubblicare su Netlify](https://www.netlify.com/blog/2016/09/29/a-step-by-step-guide-deploying-on-netlify/) <Badge>esterno</Badge></p>
```

2023-10-08 13:16 UTC, lutaok reviewed
LGTM

2023-10-08 16:46 UTC, lutaok approved these changes

2023-10-10 10:56 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 💜

2023-10-10 10:56 UTC, merged