i18n(fr): Add `deploy/deno.mdx`
withastro/docs pull request #4970
Opened 2023-10-05 20:49 UTC by thomasbnt

#### Description (required)

Adding `deploy/deno.mdx` in French translation.

I am participating in the Hacktoberfest!

- Add `deploy/deno.mdx` in French language https://github.com/withastro/docs/commit/94b4e2e63501c38c167e175ad374b34e02dccf2f
#### Related issues & labels (optional)

Nope.

2023-10-05 23:03 UTC, dreyfus92 requested changes
Bon travail @thomasbnt 😁. Voice je vous laisse quelques mineur suggestions.

2023-10-05 23:16 UTC, thomasbnt commented
> Bon travail @thomasbnt 😁. Voice je vous laisse quelques mineur suggestions.

Merci!

2023-10-06 08:04 UTC, Singebob approved these changes
Hello,
Bon travail thomas 👍 
J'ai juste une petite question 😄

2023-10-06 08:04 UTC, Singebob commented on src/content/docs/fr/guides/deploy/deno.mdx
> +Ce guide comprend des instructions pour le déploiement vers Deno Deploy via les actions sur GitHub ou le CLI de Deno Deploy.
C'est pas une CLI ? 🤔 

```suggestion
Ce guide comprend des instructions pour le déploiement vers Deno Deploy via les actions sur GitHub ou la CLI de Deno Deploy.
```

2023-10-06 10:48 UTC, thomasbnt commented on src/content/docs/fr/guides/deploy/deno.mdx
> +Ce guide comprend des instructions pour le déploiement vers Deno Deploy via les actions sur GitHub ou le CLI de Deno Deploy.
Si totalement

2023-10-06 14:07 UTC, thomasbnt commented
Merci @Singebob et @dreyfus92 pour les reviews!

2023-10-06 14:40 UTC, Singebob approved these changes
LGTM 👍

2023-10-08 09:44 UTC, McFlyPartages commented
LGTM

2023-10-08 16:31 UTC, Yan-Thomas approved these changes
LGTM! Thanks everyone 🙌

2023-10-08 16:31 UTC, merged