i18n(fr): Add `deploy/space` in French language
withastro/docs pull request #4972
Opened 2023-10-05 23:17 UTC by thomasbnt

#### Description (required)

Adding `deploy/space.mdx` in French translation.

I am participating in the Hacktoberfest!

- [i18n(fr): Add deploy/space in French language](https://github.com/withastro/docs/commit/384206f0808acb0673839eec0be59acf62c06ede)
#### Related issues & labels (optional)

Nope !

2023-10-05 23:30 UTC, dreyfus92 requested changes
Excellent travail @thomasbnt 😁.  Je vous ai laissé juste une petite suggestion

2023-10-05 23:30 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/space.mdx
> +description: Comment construire un site astro sur Space.
```suggestion
description: Comment construire un site Astro sur Space.
```

2023-10-05 23:35 UTC, thomasbnt commented on src/content/docs/fr/guides/deploy/space.mdx
> +description: Comment construire un site astro sur Space.
Owww !

2023-10-07 18:00 UTC, pioupia requested changes
Two little mistakes, but the rest LGTM

2023-10-08 09:53 UTC, McFlyPartages reviewed
I proposed two modifs also LGTM

2023-10-08 09:53 UTC, McFlyPartages commented on src/content/docs/fr/guides/deploy/space.mdx
> +	1. Changez le moteur en "statique".
```suggestion
	1. Changez le moteur (engine) en `static`.
```

2023-10-08 09:53 UTC, McFlyPartages commented on src/content/docs/fr/guides/deploy/space.mdx
> +	2. Ajoutez la commande de compilation d'Astro à la liste des `commandes`.
```suggestion
	2. Ajoutez la commande de compilation d'Astro à la liste des `commands`.
```

2023-10-08 14:12 UTC, thomasbnt commented
Thanks @McFlyPartage, @dreyfus92 @pioupia for reviews!

2023-10-09 11:22 UTC, pioupia approved these changes

2023-10-09 12:54 UTC, Yan-Thomas approved these changes
LGTM! Great work everyone 🙌

2023-10-09 12:55 UTC, merged