i18n(fr): Adding `deploy/gitlab` French translation
withastro/docs pull request #4975
Opened 2023-10-05 23:33 UTC by thomasbnt

#### Description (required)

Add `deploy/gitlab` in French language.

I am participating in the Hacktoberfest! 🎃
- [i18n(fr): Adding deploy/gitlab French translation](https://github.com/withastro/docs/commit/ec56817ed488a723d36cb556837f570337af32fb)

2023-10-05 23:59 UTC, dreyfus92 requested changes
Bon travail @thomasbnt 😁. Voici quelques suggestions pour fixer l’indentation.

2023-10-05 23:59 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/gitlab.mdx
> +});
```suggestion
   ```js
   import { defineConfig } from 'astro/config';
   
   export default defineConfig({
     sitemap: true,
     site: 'https://astro.build/',
     outDir: 'public',
     publicDir: 'static',
   });
```

2023-10-05 23:59 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/gitlab.mdx
> +    - main
```suggestion
   ```yaml
   # L'image Docker qui sera utilisée pour construire votre application
   image: node:lts
   
   pages:
     cache:
       paths:
         - node_modules/
     script:
       # Précisez ici les étapes de la construction de votre application
       - npm install
       - npm run build

     artifacts:
       paths:
         # Le dossier qui contient les fichiers construits à publier.
         # Il doit être appelé "public".
         - public

     only:
       # Déclencher un nouveau build et déployer uniquement lorsqu'il y a un push sur
       # la(les) branche(s) ci-dessous
       - main
```

2023-10-06 00:01 UTC, thomasbnt commented
> Bon travail @thomasbnt 😁. Voici quelques suggestions pour fixer l’indentation.

Oh merci ! Je ne comprends pas pourquoi l'indentation change comme ça, et pourtant je ne fais aucune modification concernant les espaces, seulement le texte.

2023-10-08 12:02 UTC, McFlyPartages commented
LGTM

2023-10-08 16:21 UTC, Yan-Thomas approved these changes
LGTM! Great work 💜

2023-10-08 16:22 UTC, merged