i18n(fr): Adding `deploy/surge` French translation
withastro/docs pull request #4976
Opened 2023-10-05 23:45 UTC by thomasbnt

#### Description (required)

Adding `deploy/surge` French translation

I am participating in the Hacktoberfest! ✨🌱

- [i18n(fr): Adding deploy/surge French translation](https://github.com/withastro/docs/commit/1a5216fbad1f30de0605c6be642ab813056b200d)

2023-10-06 00:02 UTC, dreyfus92 requested changes
Bon travail @thomasbnt 😁. Voici quelques suggestions.

2023-10-06 00:02 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/surge.mdx
> + npm install -g surge
```suggestion
    ```shell
    npm install -g surge
```

2023-10-06 00:02 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/surge.mdx
> + npm run build
```suggestion
    ```shell
    npm run build
```

2023-10-06 00:02 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/surge.mdx
> + surge dist
```suggestion
    ```shell
    surge dist
```

2023-10-06 00:03 UTC, thomasbnt commented
> Bon travail @thomasbnt 😁. Voici quelques suggestions.

Merci encore 😵😶

2023-10-06 15:27 UTC, thomasbnt commented
Je viens de m'apercevoir qu'une PR était déjà ouverte https://github.com/withastro/docs/pull/4968.

Ma faute. Cependant, quelques modifications sont tout de même possibles sur la récente PR. 
Par exemple "Déployer" → "Déployez", et de même pour tous les verbes.

2023-10-06 15:48 UTC, dreyfus92 commented
> Je viens de m'apercevoir qu'une PR était déjà ouverte #4968.
> 
> Ma faute. Cependant, quelques modifications sont tout de même possibles sur la récente PR. Par exemple "Déployer" → "Déployez", et de même pour tous les verbes.

Pas de soucis, vous pouvez ajouter les modifications correspondantes.

2023-10-06 15:56 UTC, thomasbnt commented
> > Je viens de m'apercevoir qu'une PR était déjà ouverte #4968.
> > Ma faute. Cependant, quelques modifications sont tout de même possibles sur la récente PR. Par exemple "Déployer" → "Déployez", et de même pour tous les verbes.
> 
> Pas de soucis, vous pouvez ajouter les modifications correspondantes.

Les corrections sont faites via https://github.com/withastro/docs/pull/4976/commits/0e95c595afc71418465c3d1445c2fb43b41fcab0

2023-10-08 18:37 UTC, McFlyPartages commented
Peut-être, on peut la fermer maintenant ?

2023-10-09 12:27 UTC, thomasbnt commented
Tiens bizarre, j'avais pourtant des modifications à apporter, et même après la récente PR. Et là ça indique qu'il n'y a plus rien à modifier, rien de comparable. Je ferme la PR, mais à tout moment une nouvelle se crée car il manquait quelque chose!

2023-10-09 12:27 UTC, closed without merging