i18n(fr): Adding `deploy/sst` French translation
withastro/docs pull request #4978
Opened 2023-10-05 23:52 UTC by thomasbnt

#### Description (required)

Adding `deploy/sst` French translation. That it!

I am participating in the Hacktoberfest! 🚀☕ (*Yes, I alternate emojis because it's always the same message.*)
- [i18n(fr): Adding deploy/sst French translation](https://github.com/withastro/docs/commit/d40b9a6347d2e0d146eb3ca6e65b3b946ee5ea61)

2023-10-06 00:46 UTC, dreyfus92 requested changes
Bon travail @thomasbnt. Voici un mineur suggestion pour être consistant avec le docs en anglais.

2023-10-06 00:46 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/sst.mdx
> +4. Une fois que vous êtes prêt pour le déploiement, vous pouvez lancer `npx sst deploy --stage=production`
```suggestion
1. Exécutez `npx create-sst`
1. Il devrait détecter que vous utilisez Astro et vous demander de confirmer.
1. Une fois que vous êtes prêt pour le déploiement, vous pouvez lancer `npx sst deploy --stage=production`
```

2023-10-08 12:11 UTC, McFlyPartages commented
LGTM

2023-10-08 16:12 UTC, Yan-Thomas approved these changes
LGTM! Great work everyone 🚀

2023-10-08 16:12 UTC, merged