i18n(fr) Update and translated `imports.mdx`
withastro/docs pull request #4997
Opened 2023-10-08 15:29 UTC by McFlyPartages

#### Description (required)
Update and translated imports.mdx

2023-10-08 17:35 UTC, McFlyPartages commented
J'ai remis les liens de la ligne 93 et 153 en anglais, car la doc n'est pas encore traduite mais en cours #4948

2023-10-09 12:45 UTC, pioupia requested changes

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +De plus, vous pouvez étendre Astro pour ajouter le support de différents [Frameworks UI ](/fr/core-concepts/framework-components/) comme React, Svelte et Vue. Vous pouvez également installer l'[intég
429 Too many _space_
```suggestion
De plus, vous pouvez étendre Astro pour ajouter le support de différents [Frameworks UI](/fr/core-concepts/framework-components/) comme React, Svelte et Vue. Vous pouvez également installer l'[intégration Astro MDX](/fr/guides/integrations-guide/mdx/) et utiliser les fichiers `.mdx` dans votre projet.
```

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +Vous pouvez placer n'importe quelle ressource statique dans le répertoire [`public/`](/fr/core-concepts/project-structure/#public) de votre projet, et Astro le copiera directement dans votre version
`par un chemin URL` sounds weird. I don't really have other suggestion, so don't take mine but I don't know if you have any idea.

```suggestion
Vous pouvez placer n'importe quelle ressource statique dans le répertoire [`public/`](/fr/core-concepts/project-structure/#public) de votre projet, et Astro le copiera directement dans votre version finale sans y toucher. Les fichiers dans le répertoire `public/` ne sont pas construits ou regroupés par Astro, ce qui signifie que n'importe quel type de fichier est supporté. Vous pouvez référencer un fichier `public/` par un chemin directement dans vos modèles HTML.
```

or maybe:
```suggestion
Vous pouvez placer n'importe quelle ressource statique dans le répertoire [`public/`](/fr/core-concepts/project-structure/#public) de votre projet, et Astro le copiera directement dans votre version finale sans y toucher. Les fichiers dans le répertoire `public/` ne sont pas construits ou regroupés par Astro, ce qui signifie que n'importe quel type de fichier est supporté. Vous pouvez référencer un fichier `public/` par un chemin d'URL directement dans vos modèles HTML.
```

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +Selon les [règles de résolution des modules TypeScript](https://www.typescriptlang.org/docs/handbook/module-resolution.html), les extensions de fichiers `.ts` et `.tsx` ne doivent pas être utilisées
I'm sorry for that :sweat_smile: :
```suggestion
Selon les [règles de résolution des modules TypeScript](https://www.typescriptlang.org/docs/handbook/module-resolution.html), les extensions de fichiers `.ts` et `.tsx` ne doivent pas être utilisées lors de l'importation de fichiers TypeScript. À la place, utilisez les extensions de fichiers `.js`/`.jsx` ou omettez complètement l'extension de fichier.
```

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +Si vous avez installé un paquetage NPM, vous pouvez l'importer dans Astro.
I'm not shure for the word "paquetage"
```suggestion
Si vous avez installé un paquet NPM, vous pouvez l'importer dans Astro.
```

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +Astro prend en charge l'importation de fichiers CSS directement dans votre application. Les styles importés n'exposent à aucune exportation, mais l'importation d'un style ajoutera automatiquement ce
I also have a problem with this sentence: `Les styles importés n'exposent à aucune exportation`. Maybe with `ne nécessitent pas d'exportation` that could be better.
But anyway, you duplicate the final dot `..`
```suggestion
Astro prend en charge l'importation de fichiers CSS directement dans votre application. Les styles importés ne nécessitent pas d'exportations, mais l'importation d'un style ajoutera automatiquement ce style à la page. Cela fonctionne pour tous les fichiers CSS par défaut, et peut prendre en charge les langages CSS compilés comme Sass et Less via des plugins.
```

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +Toutes les autres ressources qui ne sont pas explicitement mentionnés ci-dessus peuvent être importés via ESM `import` et renverront une référence URL à la ressource finale construite. Cela peut être
```suggestion
Toutes les autres ressources qui ne sont pas explicitement mentionnés ci-dessus peuvent être importés via l'`import` ESM et renverront une référence URL à la ressource finale construite. Cela peut être utile pour référencer des ressources non-JS par URL, comme créer un élément image avec un attribut `src` pointant vers cette image.
```

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +// imports all files that end with `.astro` in `./src/components/`
```suggestion
// importe tous les fichiers qui se terminent par `.astro` dans `./src/components/`
```

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +<!-- Display all of our components -->
```suggestion
<!-- Affiche tous nos composants -->
```

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +Pour être utilisé avec `Astro.glob()`, le pattern globale doit être une chaîne littérale et ne peut pas contenir de variables. Voir [le guide de dépannage](/fr/guides/troubleshooting/#astroglob---no-
```suggestion
Pour être utilisé avec `Astro.glob()`, le pattern global doit être une chaîne littérale et ne peut pas contenir de variables. Voir [le guide de dépannage](/fr/guides/troubleshooting/#astroglob---no-matches-found) pour une solution de contournement.
```

2023-10-09 12:45 UTC, pioupia commented on src/content/docs/fr/guides/imports.mdx
> +Referez-vous à la documentation de votre plugin pour connaître les options de configuration et savoir comment l'installer correctement.
With some French accent, that's always better!
```suggestion
Référez-vous à la documentation de votre plugin pour connaître les options de configuration et savoir comment l'installer correctement.
```

2023-10-10 08:20 UTC, McFlyPartages commented
PR mise a jour avec vos suggestions

2023-10-13 17:01 UTC, pioupia approved these changes

2023-10-14 13:14 UTC, Yan-Thomas commented on src/content/docs/fr/guides/imports.mdx
> +Astro permet de charger des fichiers WASM directement dans votre application en utilisant l'API [`WebAssembly`] (https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/WebAssem
```suggestion
Astro permet de charger des fichiers WASM directement dans votre application en utilisant l'API [`WebAssembly`](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly) du navigateur.
```

2023-10-14 13:15 UTC, Yan-Thomas approved these changes
LGTM! There was a broken link but I fixed it myself 🙌

2023-10-14 13:21 UTC, merged