i18n(fr) Update and Translate `integration-guide.mdx`
withastro/docs pull request #5001
Opened 2023-10-08 19:52 UTC by McFlyPartages

#### Description (required)
Update and Translate `integration-guide.mdx`

2023-10-24 19:31 UTC, thomasbnt requested changes
Deux trois suggestions, et souci avec deux liens dans la doc

2023-10-24 19:31 UTC, thomasbnt commented on src/content/docs/fr/guides/integrations-guide.mdx
> +    // 3. Dpuis un objet en ligne
"dpuis" -> "depuis"

2023-10-24 19:31 UTC, thomasbnt commented on src/content/docs/fr/guides/integrations-guide.mdx
> +Les intégrations sont presque toujours conçues comme des fonctions d'usine qui renvoient l'objet d'intégration proprement dit. Cela vous permet de passer des arguments et des options à la fonction d'
On traduit le mot `factory` dans ce cas ?

2023-10-28 18:12 UTC, McFlyPartages commented on src/content/docs/fr/guides/integrations-guide.mdx
> +    // 3. Dpuis un objet en ligne
C'est fait ;)

2023-10-28 18:12 UTC, McFlyPartages commented on src/content/docs/fr/guides/integrations-guide.mdx
> +Les intégrations sont presque toujours conçues comme des fonctions d'usine qui renvoient l'objet d'intégration proprement dit. Cela vous permet de passer des arguments et des options à la fonction d'
C'est fait ;)

2023-11-02 16:42 UTC, thomasbnt approved these changes
LGTM!

2023-11-02 16:59 UTC, thomasbnt requested changes
Devrait être changé en `#configuration-automatique-des-intégrations` L270, hormis ça, tout est bon!

2023-11-02 17:46 UTC, McFlyPartages commented
> Devrait être changé en `#configuration-automatique-des-intégrations` L270, hormis ça, tout est bon!

Je suis en déplacement, peux tu proposer la modif je la validerait. Stp

2023-11-09 14:34 UTC, thomasbnt approved these changes

2023-11-09 14:50 UTC, merged