i18n(pt-br): Updating entire /guides section
withastro/docs pull request #5012
Opened 2023-10-09 19:20 UTC by guidiego

#### Description
I am updating all `/guides` file outdated

🎃 I am in hackthoberfest! 🎃

2023-10-18 11:47 UTC, Yan-Thomas requested changes
Thanks @guidiego, this is an amazing piece of work! I've added a few suggestions for you to address and then we're good to go 🙌

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/images.mdx
> +Não forneça um valor para densidades ao usar este valor. Apenas um destes dois valores pode ser usado para gerar um srcset.
Quando a gente se refere a um atributo a gente sempre mantém a formatação em código
```suggestion
Não forneça um valor para `densities` ao usar este valor. Apenas um destes dois valores pode ser usado para gerar um `srcset`.
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/images.mdx
> +Utilize o componente <Picture /> do Astro para exibir uma imagem responsiva com vários formatos e/ou tamanhos.
```suggestion
Utilize o componente `<Picture />` integrado do Astro para exibir uma imagem responsiva com vários formatos e/ou tamanhos.
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/images.mdx
> +#### Properties
```suggestion
#### Propriedades
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/images.mdx
> +Por padrão, é configurado como `.png` para imagens estáticas, `.gif` para imagens animadas e `.svg para arquivos SVG.
```suggestion
Por padrão, é configurado como `.png` para imagens estáticas, `.gif` para imagens animadas e `.svg` para arquivos SVG.
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/images.mdx
Algumas mudanças ficaram faltando, marquei as linhas aqui: https://github.com/withastro/docs/commit/b91953c694b46b1488b0d7685dfe3be17163165d#diff-9ea5d63bc29a5a013378b352f2b77fffd61f773692ff6c329a3cc9292552ac23R629-R635 e aqui: https://github.com/withastro/docs/commit/b91953c694b46b1488b0d7685dfe3be17163165d#diff-9ea5d63bc29a5a013378b352f2b77fffd61f773692ff6c329a3cc9292552ac23R403

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/integrations-guide/deno.mdx
> +O adaptador deno anteriormente era mantido pelo time do Astro, mas agora é mantido pela própria equipe do Deno. O seu uso está documentado no [repositório do adaptador Deno](https://github.com/denola
```suggestion
O adaptador Deno anteriormente era mantido pelo time do Astro, mas agora é mantido pela própria equipe do Deno. O seu uso está documentado no [repositório do adaptador Deno](https://github.com/denoland/deno-astro-adapter).
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/server-side-rendering.mdx
Aqui ficou faltando as mudanças dos seguintes commits: https://github.com/withastro/docs/commit/a37a97ae3b5797c613d77affcccf904bb4ea86dd, https://github.com/withastro/docs/commit/91a669dc3c0ca0a53d86709cc9c95ebf9242c8f8 e https://github.com/withastro/docs/commit/56e8937fe5e10690a8182b605e707553ec3b2bfb

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/styling.mdx
>  Se você estiver utilizando Tailwind, o [plugin typography](https://tailwindcss.com/docs/typography-plugin) pode ser útil para estilizar Markdown.
Essa linha aqui pode ser removida, já que o conteúdo dela tá sendo mencionado abaixo.
```suggestion

```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/styling.mdx
> +Ao usar a estratégia de estilo isolado padrão, você também deve passar o atributo `data-astro-cid-*`. Você pode fazer isso passando o `...rest` das props para o componente. Se você alterou a propried
No resto da página a gente se refere a "scoped styles" como "estilos em escopo", portanto eu mudaria aqui para deixar consistente com o resto da página.
```suggestion
Ao usar a estratégia de estilo com escopo padrão, você também deve passar o atributo `data-astro-cid-*`. Você pode fazer isso passando o `...rest` das props para o componente. Se você alterou a propriedade `scopedStyleStrategy` para `'class'` ou `'where'`, a prop `...rest` não é necessária.
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/styling.mdx
> +:::note[Estilos isolados de componentes pais]
```suggestion
:::note[Estilos com escopo de componentes pais]
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/troubleshooting.mdx
> +console.log('Oi! Estou no cliente. Isso irá aparecer no console do seu browser.');
Geralmente a gente opta por "navegador" e "executando" nesses casos
```suggestion
console.log('Oi! Estou no servidor. Isso vai aparecer no terminal que o Astro está executando.');
---
<script>
console.log('Oi! Estou no cliente. Isso irá aparecer no console do seu navegador.');
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/troubleshooting.mdx
> +Uma instrução `console.log()` no frontmatter do Astro sempre produzirá saída no **terminal** em que o Astro CLI está sendo executado. Isso ocorre porque o Astro é executado no servidor e nunca no nav
```suggestion
Uma instrução `console.log()` no frontmatter do Astro sempre produzirá saída no **terminal** em que a CLI do Astro está sendo executada. Isso ocorre porque o Astro é executado no servidor e nunca no navegador.
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/typescript.mdx
Faltou as mudanças dessas linhas marcadas aqui: https://github.com/withastro/docs/commit/949749dcf0883fb579dadde3d2b369b9cd7e3784#diff-3326736e17eb78ddba38aacdf7709e5a5a4f2bc05d0db8d5fcf54088c6c0d532L273-L278

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/typescript.mdx
>  Você pode querer adicionar uma propriedade para o objeto global. Você pode fazer isso adicionando uma declaração global ao seu arquivo `env.d.ts`:
Esse parágrafo mudou um pouco no original
```suggestion
Você pode querer adicionar uma propriedade para o objeto global. Você pode fazer isso adicionando declarações de nível superior usando a palavra-chave `declare` ao seu arquivo `env.d.ts`:
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/view-transitions.mdx
> +Existem casos em que você não pode navegar via roteamento do lado do cliente, pois ambas as páginas envolvidas devem usar o roteador `<ViewTransitions />` para evitar uma recarga de página inteira. V
A palavra "rotação" é de rotacionar, ela não pode ser utilizada no contexto de routing (roteamento)
```suggestion
Existem casos em que você não pode navegar via roteamento do lado do cliente, pois ambas as páginas envolvidas devem usar o roteador `<ViewTransitions />` para evitar uma recarga de página inteira. Você também pode não querer o roteamento do lado do cliente em todas as mudanças de navegação e preferir uma navegação de página tradicional em rotas selecionadas.
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/view-transitions.mdx
> +O exemplo a seguir mostra a prevenção da rotação do lado do cliente ao navegar para um artigo apenas a partir da página inicial. Isso ainda permite que você tenha animações em elementos compartilhado
```suggestion
Você pode desativar o roteamento do lado do cliente em uma base de link por link, adicionando o atributo `data-astro-reload` a qualquer tag `<a>`. Este atributo substituirá qualquer componente `<ViewTransitions />` existente e, em vez disso, acionará uma atualização do navegador durante a navegação.

O exemplo a seguir mostra a prevenção do roteamento do lado do cliente ao navegar para um artigo apenas a partir da página inicial. Isso ainda permite que você tenha animações em elementos compartilhados, como uma imagem de destaque, ao navegar para a mesma página a partir de uma página de listagem de artigos:
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/view-transitions.mdx
> +O componente `<Formulario />` pode então ser rendenizado em um página Astro que usa um roteador `<ViewTransitions />`, com a seguinte diretiva:
```suggestion
O componente `<Formulario />` pode então ser renderizado em um página Astro que usa um roteador `<ViewTransitions />`, com a seguinte diretiva:
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/view-transitions.mdx
> +Habilitar a rotação do lado do cliente e animar transições de página traz desafios de acessibilidade, e o Astro tem como objetivo tornar os sites que optam por Transições de Visualização tão acessíve
```suggestion
Habilitar o roteamento do lado do cliente e animar transições de página traz desafios de acessibilidade, e o Astro tem como objetivo tornar os sites que optam por Transições de Visualização tão acessíveis por padrão quanto possível.
```

2023-10-18 11:47 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/view-transitions.mdx
> +Para adicionar um anúncio de rota à rotação do lado do cliente, o componente adiciona um elemento à nova página com o atributo `aria-live` definido como `assertive`. Isso informa à tecnologia assisti
```suggestion
O componente `<ViewTransitions />` inclui um anunciador de rota para navegação de página durante o roteamento do lado do cliente. Nenhuma configuração ou ação é necessária para habilitar isso.

Tecnologias assistivas informam aos visitantes que a página foi alterada ao anunciar o novo título da página após a navegação. Ao usar o roteamento do lado do servidor com atualizações tradicionais de página inteira no navegador, isso acontece por padrão após o carregamento da nova página. No roteamento do lado do cliente, o componente `<ViewTransitions />` realiza essa ação.

Para adicionar um anúncio de rota à rotação do lado do cliente, o componente adiciona um elemento à nova página com o atributo `aria-live` definido como `assertive`. Isso informa à tecnologia assistiva para anunciar imediatamente. O componente também verifica o seguinte, na ordem de prioridade, para determinar o texto do anúncio:
```

2023-10-21 16:26 UTC, guidiego commented on src/content/docs/pt-br/guides/deploy/netlify.mdx
Aqui você esta falando sobre o "/reference"? Eu ia criar um PR sequencial atualizando todo o /reference :)

2023-10-23 20:11 UTC, Yan-Thomas commented on src/content/docs/pt-br/guides/deploy/netlify.mdx
Tinha umas pequenas coisas de um PR anterior para esse arquivo, mas já resolvi :raised_hands:

2023-10-23 20:34 UTC, Yan-Thomas approved these changes
LGTM! I went ahead and added a few missing changes here and there, thanks for the great work 🙌

2023-10-23 20:48 UTC, merged