i18n(fr): Adding `integrations-guide.md` translations
withastro/docs pull request #503
Opened 2022-05-09 18:07 UTC by Chrissdroid

Adding `guides/integrations-guide.md` into the french translation.

Open and ready for review !

2022-05-18 01:42 UTC, sarah11918 commented
Just updating the branch, and pinging because this one's been sitting here a while! Anyone free to review?  @Olyno ? :)

2022-05-18 10:32 UTC, Olyno requested changes

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Dans cet exemple, nous allons installer l'intégration `@astrojs/react` pour ajouter le support React à votre projet Astro. Le processus pour ajouter un autre Framework (Preact, Vue, Svelte ou Solid.j
```suggestion
Dans cet exemple, nous allons ajouter l'intégration `@astrojs/react` pour ajouter le React à votre projet Astro. Le processus d'ajout de tout autre framework (Preact, Vue, Svelte ou Solid) est presque identique et peut être suivi en utilisant les mêmes étapes décrites ci-dessous.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Premièrement, vous devez installer l'intégration et les packages liés que vous attendez d'utiliser dans votre projet. Pour React, cela signifie installer l'intégration `@astrojs/react` ***et*** les p
```suggestion
Tout d'abord, vous devrez installer à la fois l'intégration et tous les modules liés que vous pensez utiliser dans votre projet. Pour React, cela signifie installer l'intégration `@astrojs/react` ****et*** les modules `react` + `react-dom`.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Une fois que vos packages ont été installés, ajoutez deux lignes au fichier de configuration de votre projet `astro.config.mjs`.
```suggestion
Une fois que vos modules ont été installés, ajoutez deux nouvelles lignes au fichier de configuration de votre projet `astro.config.mjs`.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +La première ligne est l'importation l'intégration dans votre fichier de configuration. La deuxième ligne appelle la fonction d'intégration (`react()`) et ajoute l'intégration pour que Astro sache qu'
```suggestion
La première ligne est l'importation de l'intégration dans votre fichier de configuration. La deuxième ligne appelle la fonction d'intégration (`react()`) et ajoute l'intégration pour qu'Astro sache l'utiliser.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +- ✅ supprimé toute configuration obsolète `renderers:` (avant la version 0.25)
```suggestion
Si vous voyez une erreur au démarrage, assurez-vous que vous avez :

- ✅ installé les modules requis avec npm
- ✅ importé l'intégration dans votre fichier `astro.config.mjs`
- ✅ appelé votre intégration comme une fonction (`[react()]`, pas `[react]`)
- ✅ supprimé toute configuration `renderers:` obsolète (avant la version 0.25)
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +> Nous allons toujours demander une confirmation avant de mettre à jour tous vos fichiers, mais il n'est jamais trop prudent de faire un backup de version juste pour être sûr.
```suggestion
> Nous vous demanderons toujours une confirmation avant de mettre à jour l'un de vos fichiers, mais il n'est jamais inutile de disposer d'une sauvegarde, au cas où.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +À la place de la configuration manuelle décrite ci-dessus, exécutez simplement `astro add [name]` et notre assistant d'intégration automatique mettra à jour votre fichier de configuration et installe
```suggestion
Au lieu de la configuration manuelle décrite ci-dessus, exécutez simplement `astro add [name]` et notre assistant d'intégration automatique mettra à jour votre fichier de configuration et installera toutes les dépendances nécessaires.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Quand vous installez une intégration Astro dans votre projet, gardez une oeil sur les avertissements `"missing peer dependencies"` que vous voyez pendant l'installation. Tous les gestionnaires de paq
```suggestion
Lorsque vous installez une intégration Astro dans votre projet, soyez attentif aux avertissements `"missing peer dependencies"` qui apparaissent au cours de l'étape d'installation. Tous les gestionnaires de modules n'installent pas automatiquement les dépendances pour vous. Si vous utilisez Node v16+ et npm, vous n'avez pas à vous soucier de cette section.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Si vous voyez un avertissement `"Cannot find package 'react'"` (ou similaire), cela signifie que vous devez installer ce package dans votre projet. React, par exemple, est une dépendance de la paquet
```suggestion
Si vous voyez un avertissement `"Cannot find package 'react'"` (ou un avertissement similaire) lorsque vous démarrez Astro, cela signifie que vous devez installer ce module dans votre projet. React, par exemple, est une dépendance de l'intégration `@astrojs/react`. Cela signifie que vous devez installer les modules officiels `react` et `react-dom` en même temps que votre intégration. L'intégration puisera automatiquement dans ces modules.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Si vous manquez cette étape, ne vous inquiétez pas, Astro vous avertira au démarrage si des dépendances en commun manquent mais ne sont pas dans votre projet.
```suggestion
Si vous manquez cette étape, ne vous inquiétez pas, Astro vous avertira au cours du démarrage si des dépendances peer manquantes sont requises mais non trouvées dans votre projet.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Gérer vos propres dépendances en commun peut être un peu plus de travail, mais il vous permet de contrôler précisément quelles versions de paquets vous utilisez pour les choses comme React, Tailwind,
```suggestion
La gestion de vos propres dépendances peer peut représenter un peu plus de travail, mais elle vous permet également de contrôler exactement les versions des modules que vous utilisez pour des choses comme React, Tailwind, et plus encore. Cela vous donne plus de contrôle sur votre projet.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Dans le futur, une commande utilitaire `astro add` pourrait gérer tout ce processus pour vous, et installer les dépendances correspondantes pour vos intégrations automatiquement.
```suggestion
À l'avenir, une commande utile `astro add` sera capable de gérer toute cette configuration pour vous, et d'installer automatiquement les dépendances correctes des peers pour vos intégrations.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Les intégrations Astro sont toujours ajoutées à l'aide de la propriété `integrations` dans votre fichier `astro.config.mjs`.
```suggestion
Les intégrations Astro sont toujours ajoutées par le biais de la propriété `integrations` dans votre fichier `astro.config.mjs`.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +> Vous voulez en savoir plus sur l'utilisation ou la configuration d'une intégration spécifique ? Consultez notre [répertoire des intégrations](https://astro.build/integrations/) et suivez le lien ve
```suggestion
> Vous souhaitez en savoir plus sur l'utilisation ou la configuration d'une intégration spécifique ? Trouvez-la dans notre [répertoire des intégrations](https://astro.build/integrations/) et suivez le lien vers son dépôt sur GitHub.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +3. Écrire votre intégration en ligne, directement dans votre fichier de configuration.
```suggestion
Il existe trois façons courantes d'importer une intégration dans votre projet Astro :

1. En installant une intégration à partir d'un module npm.
2. En important votre propre intégration à partir d'un fichier local dans votre projet.
3. En écrivant votre intégration en ligne, directement dans votre fichier de configuration.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Consultez l'[API d'intégration](/fr/reference/integrations-reference/) pour en savoir plus sur les différentes façons que vous pouvez écrire une intégration.
```suggestion
Consultez la référence à l'[API d'intégration](/fr/reference/integrations-reference/) pour connaître toutes les différentes façons d'écrire une intégration.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Les intégrations sont presque toujours écrites en tant que fonctions de fabrique qui renvoient l'objet intégration. Cela vous permet de passer des arguments et des options à la fonction de fabrique q
```suggestion
Les intégrations sont presque toujours conçues comme des fonctions "factory" qui renvoient l'objet d'intégration. Cela vous permet de passer des arguments et des options à la fonction afin de personnaliser l'intégration pour votre projet.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Les intégrations `false` sont ignorées, donc vous pouvez activer et désactiver les intégrations sans vous inquiéter de valeurs booléennes ou `undefined` qui restent.
```suggestion
Les intégrations `false` sont ignorées, ce qui vous permet d'activer et de désactiver les intégrations sans vous soucier des valeurs booléennes et des `undefined` restants.
```

2022-05-18 10:32 UTC, Olyno commented on src/pages/fr/guides/integrations-guide.md
> +Consultez l'[API d'intégration](/fr/reference/integrations-reference/) pour savoir ce que peut faire une intégration et comment la créer vous-même.
```suggestion
L'API d'intégration d'Astro est inspirée de Rollup et de Vite, et est conçue pour être familière à toute personne ayant déjà écrit un plugin Rollup ou Vite.

Consultez l'[API d'intégration](/fr/reference/integrations-reference/) pour savoir ce que les intégrations peuvent faire et comment en écrire une vous-même.
```

2022-05-25 21:39 UTC, sarah11918 commented
Merging, because I see all the edits resolved! If you have issues, reopen with another PR. But, The French-Brazilian Word War must go on!

2022-05-25 21:39 UTC, merged