i18n(es): Translate `modified-time.mdx`
withastro/docs pull request #5055
Opened 2023-10-12 18:06 UTC by Waxer59

#### Description (required)

Translate `modified-time.mdx`

#### Related issues & labels (optional)

- Suggested label: `18n`

2023-10-12 20:30 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59 😁, te dejo una sugerencias. Para arreglar el error que está arrojando el `CI/CD` cambia ruta de este archivo a `src/content/docs/es/recipes/modified-time.mdx` ya que la que usaste no coincide.

2023-10-12 20:30 UTC, dreyfus92 commented on src/content/docs/es/guides/modified-time.mdx
> +        Aunque se recomienda utilizar Git para obtener la marca de tiempo de última modificación de un archivo, es posible utilizar el tiempo de modificación del sistema de archivos.
```suggestion
      Aunque se recomienda utilizar Git para obtener la marca de tiempo de última modificación de un archivo, es posible utilizar el tiempo de modificación del sistema de archivos.
```

2023-10-12 21:45 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-10-14 14:45 UTC, K1ri86 approved these changes
LGTM ✅

2023-10-14 16:41 UTC, Yan-Thomas approved these changes
LGTM! Thanks for this peeps 🙌

2023-10-14 16:41 UTC, merged