i18n(es): Update `client-side-scripts.mdx`
withastro/docs pull request #5059
Opened 2023-10-13 01:30 UTC by K1ri86

#### Description (required)
- Update and translate `client-side-scripts.mdx`
- I am taking part in Hacktoberfest 2023

#### Related issues & labels (optional)
- Suggested label: `18n`
- f355283ad12709251ba7e0cb199ad1a593456dc1 #4974

2023-10-13 05:55 UTC, dreyfus92 requested changes
Buen trabajo @K1ri86 😁, te dejo unas sugerencias.

2023-10-13 05:55 UTC, dreyfus92 commented on src/content/docs/es/guides/client-side-scripts.mdx
> +El atributo `async` es valioso para scripts normales porque evita que bloqueen el renderizado. Sin embargo, los scripts del módulo ya tienen este comportamiento. Agregar `async` a un script del módul
```suggestion
El atributo `async` es valioso para scripts normales porque evita que bloqueen el renderizado. Sin embargo, los scripts del módulo ya tienen este comportamiento. Agregar `async` a un script del módulo hará que se ejecute antes de que la página se haya cargado por completo. Probablemente no es lo que deseas.
```

2023-10-13 05:55 UTC, dreyfus92 commented on src/content/docs/es/guides/client-side-scripts.mdx
> +### Procesado de scripts
```suggestion
### Procesamiento de scripts
```

2023-10-13 05:55 UTC, dreyfus92 commented on src/content/docs/es/guides/client-side-scripts.mdx
> +Astro empaquetará, optimizará y agregará estos scripts a la página por ti, siguiendo sus [reglas de procesado](#procesado-de-scripts).
```suggestion
Astro empaquetará, optimizará y agregará estos scripts a la página por ti, siguiendo sus [reglas de procesado](#procesamiento-de-scripts).
```

2023-10-13 05:55 UTC, dreyfus92 commented on src/content/docs/es/guides/client-side-scripts.mdx
> +## Incluye archivos javascript en tu página
```suggestion
## Incluye archivos de javascript en tu página
```

2023-10-13 05:56 UTC, dreyfus92 reviewed
Que no se te olvide quitar de esta PR las modificaciones del archivo `contribute.mdx` por que ya tienes una PR abierta.

2023-10-13 21:00 UTC, dreyfus92 approved these changes
LGTM ✅

2023-10-14 11:48 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-10-14 11:49 UTC, merged