i18n(ja) Translate `aws.mdx`
withastro/docs pull request #5097
Opened 2023-10-14 15:01 UTC by piro-hiroki

#### Description (required)

Translate `aws.mdx` into Japanese！

file: [guides/deploy/aws.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/deploy/aws.mdx)

#### Related issues & labels (optional)

- Closes #
- Suggested label:

2023-11-24 11:25 UTC, sarah11918 commented
Hi @piro-hiroki ! Just checking if this PR should still be marked as a draft?

If it's ready for editing, then please change the status so that it is ready for review! We are hoping to merge as many PRs by next week as we can before the docs site code migrates to Starlight. So if this is ready, we would like to be able to review it.  Thanks!

2023-12-17 01:03 UTC, sarah11918 commented
Hi @piro-hiroki ! Is this one ready for a review now?

2023-12-23 12:16 UTC, morinokami requested changes
@sarah11918 Added 23 suggestions, phew😅 I think we can merge this PR once those suggestions are merged.

@piro-hiroki Please let me know if you have anything to add!

2023-12-23 12:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/aws.mdx
> +
https://github.com/withastro/docs/pull/5511 was merged after this PR was created.

```suggestion

### CloudFrontのエラーページのセットアップ

S3はデフォルトで、ファイルが見つからなかった場合には404エラーを、ファイルがプライベートであった場合には403エラーを返します。いずれの場合でも、ユーザーは汚いXMLエラーページを見ることとなります。

これを変更するには、CloudFrontディストリビューションの**設定 > エラーページ**に**カスタムエラーレスポンス**を追加します。

1. 404エラーのためのカスタムエラーレスポンスを以下の値で設定します:
    * **HTTPエラーコード:** 404: Not Found
    * **エラーレスポンスをカスタマイズ:** Yes
    * **レスポンスページのパス:** `/index.html`
    * **HTTPレスポンスコード:** 200: OK

2. 403エラーのためのカスタムエラーレスポンスを以下の値で設定します:
    * **HTTPエラーコード:** 403: Forbidden
    * **エラーレスポンスをカスタマイズ:** Yes
    * **レスポンスページのパス:** `/index.html`
    * **HTTPレスポンスコード:** 200: OK

  :::tip
  ベストなユーザー体験のために、プロジェクトに[カスタム404エラーページを作成](/ja/core-concepts/astro-pages/#カスタム404エラーページ)し、**レスポンスページのパス**を`/404.html`にセットすることもできます。
  :::

```

2023-12-23 12:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/aws.mdx
> +AWSの継続的デプロイを設定する方法はたくさんある。GitHub 上でホストされているコードの場合、[GitHub Actions](https://github.com/features/actions) を使ってコミットをプッシュするたびにウェブサイトをデプロイする方法があります。
```suggestion
AWSで継続的デプロイを設定する方法はたくさんあります。GitHub 上でホストされているコードの場合、[GitHub Actions](https://github.com/features/actions) を使ってコミットをプッシュするたびにウェブサイトをデプロイする方法があります。
```

2023-12-23 12:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/aws.mdx
> +    `<DISTRIBUTION_ARN>` と `<BUCKET_NAME>` を忘れずに置き換えてください。ARN は**CloudFront > ディストリビューション > 詳細**で確認できます。
```suggestion
    `<DISTRIBUTION_ARN>`と`<BUCKET_NAME>`を忘れずに置き換えてください。ARN は**CloudFront > ディストリビューション > 詳細**で確認できます。
```

2023-12-23 12:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/aws.mdx
> +2. 新しい IAM ユーザーを作成し、そのユーザーにポリシーをアタッチします。これにより、`AWS_SECRET_ACCESS_KEY` と `AWS_ACCESS_KEY_ID` が提供されます。
```suggestion
2. 新しいIAMユーザーを作成し、そのユーザーにポリシーをアタッチします。これにより、`AWS_SECRET_ACCESS_KEY`と`AWS_ACCESS_KEY_ID`が提供されます。
```

2023-12-23 12:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/aws.mdx
> +3. このサンプルワークフローをあなたのリポジトリの `.github/workflows/deploy.yml` に追加し、GitHubにプッシュしてください。`AWS_ACCESS_KEY_ID`、`AWS_SECRET_ACCESS_KEY`、`BUCKET_ID`、および `DISTRIBUTION_ID` を、GitHubリポジトリの Settings（設定） > Secrets（シー
```suggestion
3. 以下のサンプルワークフローをあなたのリポジトリの`.github/workflows/deploy.yml`に追加し、GitHubにプッシュしてください。`AWS_ACCESS_KEY_ID`、`AWS_SECRET_ACCESS_KEY`、`BUCKET_ID`、および `DISTRIBUTION_ID`を、GitHubリポジトリの**Settings** > **Secrets** > **Actions**から"secrets"として追加する必要があります。<kbd>New repository secret</kbd>をクリックして、各値を追加します。
```

2023-12-23 12:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/aws.mdx
> +    `BUCKET_ID` は S3 バケットの名前です。`DISTRIBUTION_ID` はCloudFrontのディストリビューションIDです。CloudFrontのディストリビューションIDは**CloudFront > ディストリビューション > ID**で確認できます。
```suggestion
    `BUCKET_ID`はS3バケットの名前です。`DISTRIBUTION_ID`はCloudFrontのディストリビューションIDです。CloudFrontのディストリビューションIDは**CloudFront > ディストリビューション > ID**で確認できます。
```

2023-12-23 17:16 UTC, sarah11918 approved these changes
Thank you both @piro-hiroki and @morinokami ! I'm so happy to get all these new pages translated in docs! :tada:

2023-12-23 17:35 UTC, merged