i18n(ja): Add new `docker.mdx` translation
withastro/docs pull request #5103
Opened 2023-10-15 03:49 UTC by piro-hiroki

#### Description (required)

Translate `docker.mdx` into Japanese！
file: [recipes/docker.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/recipes/docker.mdx)

#### Related issues & labels (optional)

- Closes #
- Suggested label:

2023-10-15 05:13 UTC, piro-hiroki commented
`ja/guides/deploy/google-cloud/` の翻訳が最新の変更に追従してなさそう。。。/ The translation of `en/guides/deploy/google-cloud/` doesn't seem to follow the latest changes....

2023-11-24 11:25 UTC, sarah11918 commented
Hi @piro-hiroki ! Just checking if this PR should still be marked as a draft?

If it's ready for editing, then please change the status so that it is ready for review! We are hoping to merge as many PRs by next week as we can before the docs site code migrates to Starlight. So if this is ready, we would like to be able to review it.  Thanks!

2023-12-17 01:02 UTC, sarah11918 commented
Hi @piro-hiroki ! I think I fixed the links on this one! Is it ready for a review?

2023-12-23 14:42 UTC, morinokami requested changes
@sarah11918 Added some suggestions! I think we can merge this PR once those suggestions are merged.

@piro-hiroki Please let me know if you have anything to add!

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +プロジェクトのルートディレクトリに `Dockerfile` というファイルを作成します。このファイルにはあなたのニーズに応じて異なるサイトを構築するための指示が含まれています。このガイドではすべての可能なオプションを紹介することはできませんが、SSRと静的モードのスタートポイントを提供します。
```suggestion
プロジェクトのルートディレクトリに`Dockerfile`というファイルを作成します。このファイルにはサイトを構築するための指示が含まれおり、ニーズに応じて内容は異なります。このガイドではすべての可能なオプションを紹介することはできませんが、SSRと静的モードのスタートポイントを提供します。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +このDockerfileはNode.jsを使用してサイトを構築し、ポート `4321` でサービスを提供します。そのため、Astroプロジェクトに[Nodeアダプタ](/ja/guides/integrations-guide/node/)がインストールされている必要があります。
```suggestion
このDockerfileはNode.jsを使用してサイトを構築し、ポート`4321`でサービスを提供します。そのため、Astroプロジェクトに[Nodeアダプタ](/ja/guides/integrations-guide/node/)がインストールされている必要があります。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +プロジェクトに `.dockerignore` ファイルを追加するのがベストプラクティスです。このファイルには、Dockerの `COPY` コマンドや `ADD` コマンドで無視するファイルやフォルダを記述します。これはビルドプロセスを高速化し、最終的なイメージのサイズを小さくします。
```suggestion
プロジェクトに`.dockerignore`ファイルを追加するのがベストプラクティスです。このファイルには、Dockerの`COPY`コマンドや`ADD`コマンドで無視するファイルやフォルダを記述します。これはビルドプロセスを高速化し、最終的なイメージのサイズを小さくします。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +このファイルは `Dockerfile` 自体と同じディレクトリに置く必要があります。[詳しくは `.dockerignore` ドキュメントを読んでください](https://docs.docker.com/engine/reference/builder/#dockerignore-file)
```suggestion
このファイルは`Dockerfile`自体と同じディレクトリに置く必要があります。[詳しくは`.dockerignore`ドキュメントを読んでください](https://docs.docker.com/engine/reference/builder/#dockerignore-file)
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +以下のDockerfileはあなたのサイトを構築し、デフォルトの設定でポート `80` のApache htppdを使ってサービスを提供します。
```suggestion
以下のDockerfileは、サイトをビルドし、それをApache htppdによりデフォルトの設定でポート`80`にて配信します。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +上記のDockerfileをビルドするには、NGINX用の設定ファイルも作成する必要があります。プロジェクトのルートディレクトリに `nginx` というフォルダを作成し、その中に `nginx.conf` というファイルを作成します。
```suggestion
上記のDockerfileをビルドするには、NGINX用の設定ファイルも作成する必要があります。プロジェクトのルートディレクトリに`nginx`というフォルダを作成し、その中に`nginx.conf`というファイルを作成します。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +Dockerの[マルチステージビルド](https://docs.docker.com/build/building/multi-stage/)のおかげで、ソースコードのみが変更された場合にnpmの依存関係を再インストールしないことで、あなたのサイトのビルドプロセスを最適化する、より高度なDockerfileの例です。これにより、依存関係のサイズにもよりますが、ビルド時間を数分でも短縮することが
```suggestion
以下は、Dockerの[マルチステージビルド](https://docs.docker.com/build/building/multi-stage/)を用い、ソースコードのみが変更された場合にnpmの依存関係を再インストールしないようにすることで、サイトのビルドプロセスを最適化する、より高度なDockerfileの例です。これにより、依存関係のサイズにもよりますが、ビルド時間を場合によっては数分程度短縮できます。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +# したがって、ソースコードが変更されただけであれば、 `-deps` ステップはスキップされる。
```suggestion
# package.jsonとpackage-lock.jsonのみをここにコピーすることで、以下の`-deps`ステップがソースコードから独立していることが保証されます。
# したがって、ソースコードが変更されただけであれば、 `-deps`ステップはスキップされます。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +1. プロジェクトのルート・ディレクトリで以下のコマンドを実行してコンテナをビルドします。`<your-astro-image-name>` には任意の名前を使用してください。
```suggestion
1. プロジェクトのルートディレクトリで以下のコマンドを実行してコンテナをビルドします。`<your-astro-image-name>`には任意の名前を使用してください。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +2. イメージをローカル・コンテナとして実行するには、以下のコマンドを使用します。
```suggestion
2. イメージをローカルコンテナとして実行するには、以下のコマンドを使用します。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +`<local-port>` を自分のマシンで開いているポートに置き換えてください。また `<container-port>`をDockerコンテナが公開しているポートに置き換えてください(上記の例では`4321`、`80`、`8080`)。
```suggestion
`<local-port>`を自分のマシンの使用されていないポートに置き換えてください。また `<container-port>`をDockerコンテナが公開しているポートに置き換えてください（上記の例では`4321`、`80`、`8080`）。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +`http://localhost:<local-port>` でアクセスできるはずです。
```suggestion
`http://localhost:<local-port>`からサイトにアクセスできるはずです。
```

2023-12-23 14:42 UTC, morinokami commented on src/content/docs/ja/recipes/docker.mdx
> +3. これでウェブサイトが正常にビルドされ、コンテナにパッケージ化されたので、クラウドプロバイダにデプロイすることができます。[Google Cloud](/ja/guides/deploy/google-cloud/#cloud-run-ssrと静的配信)のデプロイガイドを参照し、Dockerドキュメントの[Deploy your app](https://docs.docker.com/la
```suggestion
3. これでウェブサイトが正常にビルドされ、コンテナにパッケージ化されたので、クラウドプロバイダにデプロイすることができます。例として[Google Cloud](/ja/guides/deploy/google-cloud/#cloud-run-ssrと静的配信)のデプロイガイドや、Dockerドキュメントの[Deploy your app](https://docs.docker.com/language/nodejs/deploy/)ページを参照してください。
```

2023-12-23 17:18 UTC, sarah11918 approved these changes
Thank you both @piro-hiroki and @morinokami ! I am so thankful for your contributions!

2023-12-23 17:36 UTC, merged