i18n(es): Fix typos in `guides/cms/`
withastro/docs pull request #5107
Opened 2023-10-15 09:44 UTC by Waxer59

#### Description (required)

Fix typos in `guides/cms/`

2023-10-15 14:19 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo una pequeña sugerencia 😁

2023-10-15 14:19 UTC, dreyfus92 commented on src/content/docs/es/guides/cms/wordpress.mdx
> +    <h1>¡Lista de Dinosaurios</h1>
```suggestion
    <h1>Lista de Dinosaurios</h1>
```

2023-10-15 20:26 UTC, Waxer59 commented
Gracias por la revisón 🤠

2023-10-16 18:38 UTC, Yan-Thomas approved these changes
LGTM! Thanks 🙌

2023-10-16 18:38 UTC, merged