i18n(ja): Add new `cloudflare.mdx`  translation
withastro/docs pull request #5109
Opened 2023-10-15 16:33 UTC by piro-hiroki

#### Description (required)

Translate `cloudflare.mdx` into Japanese！

file: [guides/deploy/cloudflare.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/deploy/cloudflare.mdx)

#### Related issues & labels (optional)

- Closes #
- Suggested label:

2023-11-24 11:24 UTC, sarah11918 commented
Hi @piro-hiroki ! Just checking if this PR should still be marked as a draft?

If it's ready for editing, then please change the status so that it is ready for review! We are hoping to merge as many PRs by next week as we can before the docs site code migrates to Starlight. So if this is ready, we would like to be able to review it.  Thanks!

2023-12-17 01:03 UTC, sarah11918 commented
Hi @piro-hiroki ! Is this one ready for a review now?

2023-12-23 15:16 UTC, morinokami requested changes
@sarah11918 Added some suggestions! I think we can merge this PR once those suggestions are merged.

@piro-hiroki Please let me know if you have anything to add!

2023-12-23 15:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/cloudflare.mdx
> +    モードが設定されていない場合、デフォルトは `"advanced"` です。
```suggestion
    モードが設定されていない場合、デフォルトは`"advanced"`です。
```

2023-12-23 15:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/cloudflare.mdx
> +2. **ディレクトリ**モード： つまり、アダプタはアプリのクライアントサイド部分を同じようにコンパイルしますが、ワーカースクリプトをプロジェクトルートの `functions` フォルダに移動します。アダプタはそのフォルダに `[[path]].js` を置くだけなので、プラグインやページのミドルウェアを追加して、バージョン管理でチェックすることができます。
```suggestion
2. **ディレクトリ**モード： 関数を`directory`モードで実行したい場合にこのモードを使用します。つまり、アダプタはアプリのクライアントサイド部分を同じようにコンパイルしますが、ワーカースクリプトをプロジェクトルートの`functions`フォルダに移動します。アダプタはそのフォルダに`[[path]].js`を置くだけなので、プラグインやページのミドルウェアを追加して、バージョン管理でチェックすることができます。
```

2023-12-23 15:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/cloudflare.mdx
> +### ページ関数の使用
```suggestion
### Pages Functionsの使用
```

2023-12-23 15:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/cloudflare.mdx
> +[ページ・ファンクション](https://developers.cloudflare.com/pages/platform/functions/)は、サーバーサイドのコードを実行することで、専用のサーバーを実行することなく動的な機能を実現します。
```suggestion
[Pages Functions](https://developers.cloudflare.com/pages/platform/functions/)により、専用のサーバーを実行することなしに、サーバーサイドのコードを実行して動的な機能を実現できます。
```

2023-12-23 15:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/cloudflare.mdx
> +📚 [SSR in Astro](/ja/guides/server-side-rendering/)についてもっと読む。
```suggestion
📚 [AstroでのSSR](/ja/guides/server-side-rendering/)についてもっと読む。
```

2023-12-23 15:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/cloudflare.mdx
> +エラーが発生する場合は、ローカルで使用している `node` のバージョン（`node -v`）が環境変数で指定しているバージョンと一致していることを再確認してください。
```suggestion
エラーが発生する場合は、ローカルで使用している`node`のバージョン（`node -v`）が環境変数で指定しているバージョンと一致しているかどうかを再確認してください。
```

2023-12-23 15:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/cloudflare.mdx
> +Cloudflareは[Node v16.13](https://miniflare.dev/get-started/cli#installation)を必要とします。このバージョンはAstroのアウトオブボックス最小値よりも新しいので、少なくともv16.13を使用していることを再確認してください。
```suggestion
Cloudflareは[Node v16.13](https://miniflare.dev/get-started/cli#installation)を必要とします。このバージョンはAstroが必要とする最小値よりも新しいので、少なくともv16.13を使用していることを再確認してください。
```

2023-12-23 15:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/cloudflare.mdx
> +CloudflareのAuto Minify設定の結果、クライアントサイドのハイドレーションが失敗することがあります。コンソールに `Hydration completed but contains mismatches` と表示されたら、Cloudflare settingsのAuto Minifyを無効にしてください。
```suggestion
CloudflareのAuto Minify設定の結果、クライアントサイドのハイドレーションが失敗することがあります。コンソールに`Hydration completed but contains mismatches`と表示されたら、Cloudflare settingsのAuto Minifyを無効にしてください。
```

2023-12-23 15:16 UTC, morinokami commented on src/content/docs/ja/guides/deploy/cloudflare.mdx
> +pnpm install wrangler --save-dev
https://github.com/withastro/docs/pull/5284

```suggestion
pnpm add wrangler --save-dev
```

2023-12-23 17:20 UTC, sarah11918 approved these changes
:rocket:

2023-12-23 17:50 UTC, merged