i18n(fr): Add `deploy/cleavr.mdx` in French language
withastro/docs pull request #5124
Opened 2023-10-17 13:02 UTC by thomasbnt

#### Description (required)

i18n(fr): Add `deploy/cleavr.mdx` in French language

I am participating in the Hacktoberfest! 🎃

- [i18n(fr): Add deploy/cleavr.mdx in French language](https://github.com/withastro/docs/commit/221472ad3ed1a36bb4cec8ba7b8d4b75f8c697b7)
#### Related issues & labels (optional)

Related to this issue https://github.com/withastro/docs/issues/4984, don't close it.

2023-10-17 14:08 UTC, dreyfus92 requested changes
Bon boulot @thomasbnt, voici quelques mineur suggestions. Fais-moi savoir ce que tu penses.

2023-10-17 14:08 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/cleavr.mdx
> +1. Dans Cleavr, naviguez au serveur auquel vous voulez ajouter votre projet Astro.
```suggestion
1. Dans Cleavr, naviguez vers le serveur auquel vous voulez ajouter votre projet Astro.
```

2023-10-17 14:08 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/cleavr.mdx
> +4. Pour les applications statiques, définissez **Artifact Folder** à `dist`.
```suggestion
4. Pour les applications statiques, définissez **Artifact Folder** sur `dist`.
```

2023-10-17 14:08 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/cleavr.mdx
> +- Définissez **Entry Point** à `entry.mjs`.
```suggestion
- Définissez **Entry Point** sur `entry.mjs`.
```

2023-10-17 14:08 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/cleavr.mdx
> +- Définissez **Artifact Folder** à `dist/server`.
```suggestion
- Définissez **Artifact Folder** sur `dist/server`.
```

2023-10-17 14:09 UTC, thomasbnt commented
Merci @dreyfus92 pour les corrections !

2023-10-21 12:50 UTC, Yan-Thomas approved these changes
LGTM! Great work 💜

2023-10-21 12:51 UTC, merged