i18n(es): Translate `add-view-transitions.mdx` `WIP`
withastro/docs pull request #5171
Opened 2023-10-21 05:49 UTC by Waxer59

#### Description (required)

Translate `add-view-transitions.mdx`

2023-10-31 05:04 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo unas pequeñas sugerencias.

2023-10-31 05:04 UTC, dreyfus92 commented on src/content/docs/es/tutorials/add-view-transitions.mdx
> +    Navega a cualquier entrada de blog en la vista previa de tu navegador, y verás que la descripción aparece con una transición más lenta que el resto del texto.
```suggestion
    Navega a cualquier entrada de blog en la vista previa de tu navegador y verás que la descripción aparece con una transición más lenta que el resto del texto.
```

2023-11-02 02:32 UTC, Waxer59 commented
Listo!, gracias por la revisión 🤠

2023-11-03 14:34 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-03 18:10 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🚀

2023-11-03 18:10 UTC, merged