i18n(es): Fix typos in `tutorial/`
withastro/docs pull request #5229
Opened 2023-10-29 17:27 UTC by Waxer59

#### Description (required)

Fix typos in `tutorial/`

2023-11-03 23:16 UTC, dreyfus92 requested changes
Muy buen trabajo @Waxer59, te dejo unas pequeñas sugerencias 😁

2023-11-03 23:16 UTC, dreyfus92 commented on src/content/docs/es/tutorial/3-components/3.mdx
> +    /* estilos del nav */
```suggestion
    /* estilos de la barra de navegación*/
```

2023-11-03 23:16 UTC, dreyfus92 commented on src/content/docs/es/tutorial/3-components/4.mdx
> +    /* estilos del nav */
```suggestion
    /* estilos de la barra de navegación*/
```

2023-11-03 23:16 UTC, dreyfus92 commented on src/content/docs/es/tutorial/6-islands/index.mdx
> +  Utiliza las islas de Astro para incorporar componentes de frameworks del lado del cliento en tu sitio de Astro.
```suggestion
  Utiliza las islas de Astro para incorporar componentes de frameworks del lado del cliente en tu sitio de Astro.
```

2023-11-04 00:20 UTC, kevinzunigacuellar reviewed
Gracias por la revisión @Waxer59 💜 , deje algunos comentarios

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/2.mdx
> +1. Añade la siguiente sentencia import al frontmatter de cada una de tus tres páginas de Astro (`index.astro`, `about.astro`, y `blog.astro`):
"sentencia" 💀 

```suggestion
1. Añade la siguiente import al frontmatter de cada una de tus tres páginas de Astro (`index.astro`, `about.astro`, y `blog.astro`):
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/3.mdx
> +title: Constrúyelo tu mismo - Cabezera
Por lo general he visto que usamos más encabezado que cabezera
```suggestion
title: Constrúyelo tu mismo - Encabezado
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/3.mdx
> +  Utiliza todo lo que has aprendido hasta ahora para construir una cabezera con navegación adaptable
```suggestion
  Utiliza todo lo que has aprendido hasta ahora para construir un encabezado con navegación adaptable
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/3.mdx
> +  - Crear una cabezera para tu sitio que contenga el componente de navegación
```suggestion
  - Crear un encabezado para tu sitio que contenga el componente de navegación
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/3.mdx
> +1. En cada página, sustituye el componente `<Navigation/>` existente por tu nueva cabezera.
```suggestion
1. En cada página, sustituye el componente `<Navigation/>` existente por tu nuevo encabezado.
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/3.mdx
> +2. Comprueba la vista previa de tu navegador y verifica que tu cabezera se muestra en todas las páginas. Todavía no se verá diferente, pero si inspeccionas la vista previa con las herramientas de des
```suggestion
2. Comprueba la vista previa de tu navegador y verifica que tu encabezado se muestra en todas las páginas. Todavía no se verá diferente, pero si inspeccionas la vista previa con las herramientas de desarrollo, verás que ahora tienes elementos como `<header>` y `<nav>` alrededor de los enlaces de navegación.
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/3.mdx
> +    - Utilizan una consulta `@media` para definir estilos diferentes para tamaños de pantalla mayores.
Podriamos usar [media query](https://developer.mozilla.org/es/docs/Web/CSS/CSS_media_queries/Using_media_queries) como en ndm
```suggestion
    - Utilizan una `@media` query para definir estilos diferentes para tamaños de pantalla mayores.
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/3.mdx
> +Cambia el tamaño de la ventana y comprueba si se aplican diferentes estilos a diferentes anchos de pantalla. Tu cabezera es ahora **responsiva** al tamaño de la pantalla mediante el uso de consultas
```suggestion
Cambia el tamaño de la ventana y comprueba si se aplican diferentes estilos a diferentes anchos de pantalla. Tu encabezado es ahora **responsiva** al tamaño de la pantalla mediante el uso de consultas `@media`.
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/4.mdx
> +Tu cabecera aún no es **interactiva** porque no puede responder a la entrada del usuario, como hacer clic en el menú hamburguesa para mostrar u ocultar los enlaces de navegación.
```suggestion
Tu encabezado aún no es **interactivo** porque no puede responder a la entrada del usuario, como hacer clic en el menú hamburguesa para mostrar u ocultar los enlaces de navegación. 
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/3-components/4.mdx
> +4. Añade la misma etiqueta `<script>` con la importación a tus otras dos páginas, `about.astro` y `blog.astro` y comprueba que tienes una cabecera responsiva e interactiva en cada página.
```suggestion
4. Añade la misma etiqueta `<script>` con la importación a tus otras dos páginas, `about.astro` y `blog.astro` y comprueba que tienes un encabezado responsivo e interactivo en cada página.
```

2023-11-04 00:20 UTC, kevinzunigacuellar commented on src/content/docs/es/tutorial/4-layouts/1.mdx
> +1. Un componente de Astro (archivo `.astro`) puede funcionar como un/a:
```suggestion
1. Un componente de Astro (archivo `.astro`) puede funcionar como una:
```

2023-11-04 01:36 UTC, Waxer59 commented
Listo! muchas gracias por la revisión @dreyfus92  y @kevinzunigacuellar 🤠!

2023-11-04 01:46 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-04 01:54 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/1.mdx
> +Para cambiar o añadir más contenido a tu página Acerca de, añade más etiquetas de elementos HTML que contengan contenido. Puedes copiar y pegar el código HTML siguiente entre las etiquetas `<body></b
```suggestion
Para cambiar o añadir más contenido a tu página 'Acerca de', añade más etiquetas de elementos HTML que contengan contenido. Puedes copiar y pegar el código HTML siguiente entre las etiquetas `<body></body>` existentes, o crear las tuyas.
```

2023-11-04 01:54 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/4.mdx
>  2. Añade el nombre de clase `skill` a los elementos `<li>` generados en tu página Acerca de, para que puedas aplicarles estilo. Tu código debería tener este aspecto:
```suggestion
2. Añade el nombre de clase `skill` a los elementos `<li>` generados en tu página 'Acerca de', para que puedas aplicarles estilo. Tu código debería tener este aspecto:
```

2023-11-04 01:54 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/4.mdx
>    4. Vuelve a visitar tu página Acerca de en tu navegador y comprueba, mediante inspección visual o herramientas de desarrollo, que cada elemento de tu lista de habilidades está ahora en verde y en n
```suggestion
  4. Vuelve a visitar tu página 'Acerca de' en tu navegador y comprueba, mediante inspección visual o herramientas de desarrollo, que cada elemento de tu lista de habilidades está ahora en verde y en negrita.
```

2023-11-04 01:54 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/5.mdx
>  Realiza cualquier cambio o adición que deseas en el contenido de tu página Acerca de añadiendo elementos HTML a la plantilla de la página, ya sea de forma estática o dinámica. Escribe cualquier JavaS
```suggestion
Realiza cualquier cambio o adición que deseas en el contenido de tu página 'Acerca de' añadiendo elementos HTML a la plantilla de la página, ya sea de forma estática o dinámica. Escribe cualquier JavaScript adicional en tu script frontmatter para proporcionarle valores para usar en tu HTML. Cuando estés satisfecho con esta página, confirma tus cambios en GitHub antes de pasar a la siguiente lección.
```

2023-11-04 01:54 UTC, Waxer59 commented on src/content/docs/es/tutorial/2-pages/5.mdx
>  Tu página Acerca de ahora tiene estilo usando *ambos* el archivo importado `global.css` *y* una etiqueta `<style>`.
```suggestion
Tu página 'Acerca de' ahora tiene estilo usando *ambos* el archivo importado `global.css` *y* una etiqueta `<style>`.
```

2023-11-04 02:07 UTC, Waxer59 commented
He arreglado un par de erratas más y he añadido comillas simples a 'Acerca de'

2023-11-04 04:55 UTC, kevinzunigacuellar commented
LGTM! Gracias @Waxer59 y @dreyfus92 🤠

2023-11-04 05:07 UTC, merged