i18n(es): Add `core-concepts/astro-components.md`
withastro/docs pull request #528
Opened 2022-05-11 03:30 UTC by agustinmulet

- [ ] Reviewed
- [ ] Updated
- [ ] Ready to go! 🧑‍🚀

2022-05-11 14:59 UTC, kevinzunigacuellar requested changes

2022-05-11 14:59 UTC, kevinzunigacuellar commented on src/pages/es/core-concepts/astro-components.md
> +> ⚠️ Los estilos definidos aquí serán aplicados únicamente en la plantilla del cponente. **No** se verán afectados componentes hijos ni cualquier componente importado por defecto.
```suggestion
> ⚠️ Los estilos definidos aquí serán aplicados únicamente en la plantilla del componente. **No** se verán afectados los componentes hijos ni cualquier otro componente importado por defecto.
```

2022-05-12 04:55 UTC, kevinzunigacuellar commented on src/pages/es/core-concepts/astro-components.md
> +Los componentes Astro son extremadamente flexibles. Muchas veces, un componente Astro va a contener **UI reutilizable en la página**, como puede ser un header o una profile card. Otras veces, un comp
Astro va a contener -> Astro puede contener

2022-05-12 05:09 UTC, kevinzunigacuellar approved these changes

2022-05-18 01:41 UTC, sarah11918 commented
Just updating the branch, because this is a few days old now, and checking in to see whether you all have come to an agreement on these suggestions!  :)

2022-05-22 22:35 UTC, readonlychild commented on src/pages/es/core-concepts/astro-components.md
> +Los componentes Astro son extremadamente flexibles. Muchas veces, un componente Astro va a contener **UI reutilizable en la página**, como puede ser un header o una profile card. Otras veces, un comp
de acuerdo con cambiar a "puede contener"

2022-05-26 14:00 UTC, kevinzunigacuellar commented
LGTM 🚀

2022-05-27 12:20 UTC, merged