i18n(ja) Translate kinsta.mdx
withastro/docs pull request #5310
Opened 2023-11-08 14:24 UTC by piro-hiroki

#### Description (required)

Translate `kinsta.mdx` into Japanese！

file: [guides/deploy/kinsta.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/deploy/kinsta.mdx)

#### Related issues & labels (optional)

- Closes #
- Suggested label:

2023-11-08 14:26 UTC, piro-hiroki commented on src/content/docs/ja/guides/deploy/kinsta.mdx
> +1. [MyKinsta](https://my.kinsta.com/)管理パネルにアクセスします。
原文は「`My Kinsta`」と空白が入っていますが、Kinstaに登録後、このURLにアクセスすると「MyKinsta」と表示されているので空白を除きました。
![Screen Shot 2023-11-08 at 23 25 36](https://github.com/withastro/docs/assets/103011756/a2e0b6ab-bc52-4f15-a76c-58d7c478d00d)

2023-11-08 14:28 UTC, piro-hiroki commented on src/content/docs/ja/guides/deploy/kinsta.mdx
> +4. **アプリケーション > アプリケーションを追加**ボタンを押します。
原文は「`4. Press the **Add service** > **Application** button.`」ですが、実際の画面の文言に合わせました。（直訳の方がよければコメントお願いします🙏）
![Screen Shot 2023-11-08 at 23 27 01](https://github.com/withastro/docs/assets/103011756/df087c14-19c9-4c20-8fcc-441bf8ed94ed)

2023-11-11 12:18 UTC, okonomi requested changes

2023-11-11 12:18 UTC, okonomi commented on src/content/docs/ja/guides/deploy/kinsta.mdx
> +- `package.json`に`build`スクリプトを含めます。(あなたのAstroプロジェクトは既にこれを含んでいるはずです。)
```suggestion
- `package.json`に`build`スクリプトを含めます。（あなたのAstroプロジェクトは既にこれを含んでいるはずです。）
```

カッコが上の行が全角でこの行が半角なので、どちらかに揃えたらいいかなと。

2023-11-11 12:18 UTC, okonomi commented on src/content/docs/ja/guides/deploy/kinsta.mdx
> +以下は、`package.json`ファイルに必要な行です.
```suggestion
以下は、`package.json`ファイルに必要な行です。
```
****

2023-11-11 12:18 UTC, okonomi commented on src/content/docs/ja/guides/deploy/kinsta.mdx
> +- `package.json`に`build`スクリプトを含めます。(あなたのAstroプロジェクトは既にこれを含んでいるはずです。)
```suggestion
- `package.json`に`build`スクリプトを含めます。（あなたのAstroプロジェクトは既にこれを含んでいるはずです。）
```

2023-11-11 12:18 UTC, okonomi commented on src/content/docs/ja/guides/deploy/kinsta.mdx
> +4. **アプリケーション > アプリケーションを追加**ボタンを押します。
```suggestion
4. **アプリケーション** > **アプリケーションを追加**ボタンを押します。
```

2023-11-23 22:21 UTC, sarah11918 commented
Hi @piro-hiroki , thank you so much for this contribution! It looks like there are some suggestions here to take a look at. We are hoping to get as many PRs merged before we convert to Starlight as possible, so if you are able to look at these suggestions, that would be very helpful!  🙌

2023-11-30 12:53 UTC, piro-hiroki commented on src/content/docs/ja/guides/deploy/kinsta.mdx
> +- `package.json`に`build`スクリプトを含めます。(あなたのAstroプロジェクトは既にこれを含んでいるはずです。)
全角に揃えます🙏

2023-11-30 13:17 UTC, piro-hiroki commented on src/content/docs/ja/guides/deploy/kinsta.mdx
> +4. **アプリケーション > アプリケーションを追加**ボタンを押します。
区切った方が良さそうですね、ありがとうございます！

2023-11-30 13:19 UTC, piro-hiroki commented on src/content/docs/ja/guides/deploy/kinsta.mdx
> +4. **アプリケーション > アプリケーションを追加**ボタンを押します。
区切った方が良さそうですね、ありがとうございます！

2023-11-30 13:22 UTC, piro-hiroki commented
@okonomi お疲れ様です！
レビュー内容を反映したので、お手隙で確認して頂ければと思います！🙏

2023-12-01 01:38 UTC, okonomi approved these changes
LGTMです！
ご対応ありがとうございます 🙌

2023-12-01 13:07 UTC, Yan-Thomas approved these changes
LGTM! Good work peeps 🙌

2023-12-01 13:07 UTC, merged