i18n(fr) Update fr translation astro-pages.mdx
withastro/docs pull request #5357
Opened 2023-11-11 16:12 UTC by McFlyPartages

#### Description (required)

Update documentation with multiple fix and add partial page

2023-11-11 18:02 UTC, dreyfus92 requested changes
Bon boulot @McFlyPartages, je vous laisse quelques suggestions mineurs 😁

2023-11-11 18:02 UTC, dreyfus92 commented on src/content/docs/fr/core-concepts/astro-pages.mdx
> +Une page doit produire un document HTML complet. S'il n'est pas explicitement inclus, Astro ajoutera la déclaration `<!DOCTYPE html>` et le contenu `<head>` nécessaires à tout composant `.astro` situ
```suggestion
Une page doit produire un document HTML complet. S'il n'est pas explicitement inclus, Astro ajoutera la déclaration `<!DOCTYPE html>` et le contenu `<head>` nécessaires à tout composant `.astro` situé dans `src/pages/` par défaut. Vous pouvez renoncer à ce comportement pour chaque composant en le marquant comme une page [partial](#page-partielle).
```

2023-11-11 18:02 UTC, dreyfus92 commented on src/content/docs/fr/core-concepts/astro-pages.mdx
> +Les partiels, lorsqu'ils sont associés à une bibliothèque de rendu, constituent une alternative aux [îles Astro](/fr/concepts/îles/) et aux [balises `<script>`](/fr/guides/client-side-scripts/) pour
```suggestion
Les partiels, lorsqu'ils sont associés à une bibliothèque de rendu, constituent une alternative aux [îles Astro](/fr/concepts/islands/) et aux [balises `<script>`](/fr/guides/client-side-scripts/) pour la création de contenu dynamique dans Astro.
```

2023-11-11 23:11 UTC, McFlyPartages commented
> Bon boulot @McFlyPartages, je vous laisse quelques suggestions mineurs 😁

Merci c'est fait

2023-11-11 23:33 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-12 20:27 UTC, thomasbnt approved these changes
LGTM ! 🙌

2023-11-12 22:55 UTC, Yan-Thomas approved these changes
LGTM! Thank you peeps 🚀

2023-11-12 22:56 UTC, merged