i18n(fr) Update markdown-content.mdx
withastro/docs pull request #5367
Opened 2023-11-11 19:55 UTC by McFlyPartages

#### Description (required)

Update and fix old translation and #5031 #5300 #5191

2023-11-11 20:55 UTC, McFlyPartages commented
I dont understand link problem

2023-11-11 23:14 UTC, McFlyPartages commented
I dont understand lug error

2023-11-12 15:48 UTC, sarah11918 commented on src/content/docs/fr/guides/markdown-content.mdx
> +<RecipeLinks slugs={["fr/recipes/reading-time"]} />
```suggestion
<RecipeLinks slugs={["fr/recipes/reading-time"]} />
```
No leading slash on this link.

2023-11-12 16:26 UTC, sarah11918 commented
Note: We discovered there's a space in the `recipes` folder name, so that should eventually fix some of these failing tests when the author can get back to this PR!  🚀

2023-11-12 16:37 UTC, McFlyPartages commented
I have fixed the blank on the folder name recipes

2023-11-12 18:08 UTC, McFlyPartages commented
Hey i add cli-reference file for fix link problem

2023-11-13 20:36 UTC, thomasbnt requested changes
Je ne suis pas sûr pour la dernière review à propos de `peuvent`.

2023-11-13 20:36 UTC, thomasbnt commented on src/content/docs/fr/guides/markdown-content.mdx
> +title: Bonjour à tous !
```suggestion
title: Hello, World
```
Je pense que c'est bien de laisser les phrases que nous pouvons retrouver un peu partout. C'est comme un repère.

2023-11-13 20:36 UTC, thomasbnt commented on src/content/docs/fr/guides/markdown-content.mdx
> +  <h2>Auteur du post: {frontmatter.author}</h2>
```suggestion
  <h2>Auteur de l'article : {frontmatter.author}</h2>
```

2023-11-13 20:36 UTC, thomasbnt commented on src/content/docs/fr/guides/markdown-content.mdx
> +  <slot /> <!-- Le contenu Markdown est injecté icie -->
```suggestion
  <slot /> <!-- Le contenu Markdown est injecté ici -->
```

2023-11-13 20:36 UTC, thomasbnt commented on src/content/docs/fr/recipes/reading-time.mdx
> +   Ce plugin utilise le paquet `mdast-util-to-string` pour obtenir le texte du fichier Markdown. Ce texte est ensuite transmis au paquet `reading-time` pour calculer le temps de lecture en minutes. .
```suggestion
   Ce plugin utilise le paquet `mdast-util-to-string` pour obtenir le texte du fichier Markdown. Ce texte est ensuite transmis au paquet `reading-time` pour calculer le temps de lecture en minutes.
```

2023-11-13 20:36 UTC, thomasbnt commented on src/content/docs/fr/reference/cli-reference.mdx
> +Ces API sont expérimentales et leur signature peut changer. Toute mise à jour sera mentionnée dans le [Astro changelog](https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md) et le
```suggestion
Ces API sont expérimentales et leur signature peuvent changer. Toute mise à jour sera mentionnée dans le [Astro changelog](https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md) et les informations ci-dessous montreront toujours les informations actuelles et à jour.
```

2023-11-13 20:44 UTC, McFlyPartages commented on src/content/docs/fr/guides/markdown-content.mdx
> +title: Bonjour à tous !
Moi ca me va, elles ont déjà était traduite dans d'autres

2023-11-13 20:48 UTC, McFlyPartages commented on src/content/docs/fr/reference/cli-reference.mdx
> +Ces API sont expérimentales et leur signature peut changer. Toute mise à jour sera mentionnée dans le [Astro changelog](https://github.com/withastro/astro/blob/main/packages/astro/CHANGELOG.md) et le
En faite non c'est leur signature au masculin donc ca doit rester comme ca je pense

2023-11-13 21:30 UTC, MoustaphaDev reviewed
Merci pour cette PR @McFlyPartages ! J'ai laissé quelles suggestions

2023-11-13 21:30 UTC, MoustaphaDev commented on src/content/docs/fr/guides/markdown-content.mdx
> +      // https://github.com/antfu/shikiji#lightdark-dual-themes
```suggestion
      // Alternativement, fournir plusieurs thèmes
      // https://github.com/antfu/shikiji#lightdark-dual-themes
```

2023-11-13 21:30 UTC, MoustaphaDev commented on src/content/docs/fr/reference/cli-reference.mdx
> +Similaire à [`astro build`](#astro-build), il construit votre site pour le déployer.
```suggestion
Similaire à [`astro build`](#astro-build), il construit votre site pour le deploiement.
```

2023-11-13 21:30 UTC, MoustaphaDev commented on src/content/docs/fr/reference/cli-reference.mdx
> +// Stop le serveur si besoin
```suggestion
// Arrêter le serveur si besoin
```

2023-11-13 21:30 UTC, MoustaphaDev commented on src/content/docs/fr/recipes/reading-time.mdx
> +Créez un [remark plugin](https://github.com/remarkjs/remark) qui ajoute une propriété de temps de lecture au frontmatter de vos fichiers Markdown ou MDX. Utilisez cette propriété pour afficher le tem
```suggestion
Créez un [plugin remark](https://github.com/remarkjs/remark) qui ajoute une propriété de temps de lecture au frontmatter de vos fichiers Markdown ou MDX. Utilisez cette propriété pour afficher le temps de lecture de chaque page.
```

2023-11-13 22:48 UTC, MoustaphaDev approved these changes
LGTM !

2023-11-13 23:11 UTC, merged