i18n(fr) Update `microsoft-azure.mdx`
withastro/docs pull request #5375
Opened 2023-11-12 15:26 UTC by McFlyPartages

#### Description (required)

Update with #5057

2023-11-12 17:16 UTC, dreyfus92 requested changes
Bon boulot @McFlyPartages, voici un suggestion mineur.

2023-11-12 17:16 UTC, dreyfus92 commented on src/content/docs/fr/guides/deploy/microsoft-azure.mdx
> +- [Documentation de Microsoft Azure Static Web Apps](https://learn.microsoft.com/en-us/azure/static-web-apps/)
```suggestion
- [Documentation de Microsoft Azure Static Web Apps](https://learn.microsoft.com/fr-fr/azure/static-web-apps/
```

2023-11-12 20:25 UTC, thomasbnt approved these changes
Lgtm!

2023-11-13 00:09 UTC, Yan-Thomas approved these changes
LGTM! Amazing work 🚀

2023-11-13 00:09 UTC, merged