i18n(fr) Fix several file for last PR #5364
withastro/docs pull request #5414
Opened 2023-11-15 09:17 UTC by McFlyPartages

#### Description (required)
Minor update for multiple file with PR #5364

2023-11-15 18:14 UTC, thomasbnt commented on src/content/docs/fr/core-concepts/routing.mdx
> +- `/astronauts/2` - Page 2: Affiche "Jean-Loup Chrétien" et "Thomas Pesquet"
Thomas Pesquet 💜

2023-11-15 18:15 UTC, thomasbnt requested changes

2023-11-15 18:15 UTC, thomasbnt commented on src/content/docs/fr/guides/imports.mdx
> +Nous encourageons les utilisateurs d'Astro à éviter les builtins Node.js (`fs`, `path`, etc.) dans la mesure du possible. Astro est compatible avec de nombreux moteurs d'exécution utilisant des [adap
```suggestion
Nous encourageons les utilisateurs d'Astro à éviter les "Built-in" Node.js (`fs`, `path`, etc.) dans la mesure du possible. Astro est compatible avec de nombreux moteurs d'exécution utilisant des [adaptateurs](/fr/guides/server-side-rendering/). Cela inclut [Deno](https://github.com/denoland/deno-astro-adapter) et [Cloudflare Workers](/fr/guides/integrations-guide/cloudflare/) qui ne supportent pas les modules intégrés de Node tels que `fs`.antes.
```

2023-11-15 19:10 UTC, dreyfus92 reviewed
LGTM ✅

2023-11-15 19:13 UTC, thomasbnt requested changes

2023-11-15 19:13 UTC, thomasbnt commented on src/content/docs/fr/guides/imports.mdx
> +Nous encourageons les utilisateurs d'Astro à éviter les "Built-in" Node.js (`fs`, `path`, etc.) dans la mesure du possible. Astro est compatible avec de nombreux moteurs d'exécution utilisant des [ad
```suggestion
Nous encourageons les utilisateurs d'Astro à éviter les "Built-in" Node.js (`fs`, `path`, etc.) dans la mesure du possible. Astro est compatible avec de nombreux moteurs d'exécution utilisant des [adaptateurs](/fr/guides/server-side-rendering/). Cela inclut [Deno](https://github.com/denoland/deno-astro-adapter) et [Cloudflare Workers](/fr/guides/integrations-guide/cloudflare/) qui ne supportent pas les modules intégrés de Node tels que `fs`.
```

2023-11-15 19:19 UTC, McFlyPartages commented on src/content/docs/fr/guides/imports.mdx
> +Nous encourageons les utilisateurs d'Astro à éviter les "Built-in" Node.js (`fs`, `path`, etc.) dans la mesure du possible. Astro est compatible avec de nombreux moteurs d'exécution utilisant des [ad
Il y est dans la page en anglais mais je ne sais pas ce que c'est lol

2023-11-16 11:21 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🙌

2023-11-16 11:21 UTC, merged