i18n(fr) Update auto.mdx
withastro/docs pull request #5415
Opened 2023-11-15 09:31 UTC by McFlyPartages

#### Description (required)

Updat french translation

2023-11-15 18:12 UTC, thomasbnt requested changes

2023-11-15 18:12 UTC, thomasbnt commented on src/content/docs/fr/install/auto.mdx
> +- **Console de terminal** - Astro est accessible via son interface par ligne de commande (CLI).
```suggestion
- **Interface de ligne de commande** - Astro est accessible via son interface par ligne de commande (CLI).
```

Suggestion liée avec le document https://github.com/withastro/docs/tree/main/src/i18n/fr#-traductions-courantes

2023-11-15 19:10 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-15 19:14 UTC, thomasbnt approved these changes
LGTM

2023-11-16 11:10 UTC, Yan-Thomas approved these changes
LGTM! Good work peeps 🙌

2023-11-16 11:10 UTC, merged