i18n(fr) Create rendering-modes.mdx
withastro/docs pull request #5436
Opened 2023-11-17 10:54 UTC by McFlyPartages

Add french translation for rendering-modes.mdx file

2023-11-17 16:48 UTC, dreyfus92 requested changes
Bon boulot @McFlyPartages, voici quelques suggestions mineures 😁

2023-11-17 16:48 UTC, dreyfus92 commented on src/content/docs/fr/core-concepts/rendering-modes.mdx
> +Les pages Astro, les routes et les points d'accès à l'API peuvent être soit [rendus au moment de la construction](#pré-rendu), soit [rendus à la demande par un serveur](#rendu-à-la-demande) lorsqu'un
```suggestion
Les pages Astro, les routes et les points de terminaison d'API peuvent être soit [rendus au moment de la construction](#pré-rendu), soit [rendus à la demande par un serveur](#rendu-à-la-demande) lorsqu'une route est demandée. Avec [Astro islands](/fr/concepts/islands/), vous pouvez également inclure un rendu côté client si nécessaire.
```

2023-11-17 16:48 UTC, dreyfus92 commented on src/content/docs/fr/core-concepts/rendering-modes.mdx
> +- **Points d'accès à l'API**: Créer des pages spécifiques qui fonctionnent comme des points de terminaison API pour des tâches telles que l'accès à la base de données, l'authentification et l'autoris
```suggestion
- **Points de terminaison d'API**: Créer des pages spécifiques qui fonctionnent comme des points de terminaison API pour des tâches telles que l'accès à la base de données, l'authentification et l'autorisation, tout en gardant les données sensibles cachées au client.
```

2023-11-17 16:48 UTC, dreyfus92 commented on src/content/docs/fr/core-concepts/rendering-modes.mdx
> +Les deux autres modes de sortie d'Astro peuvent être configurés pour permettre **un rendu à la demande de tout ou partie de vos pages, routes ou points d'extrémité d'API** :
```suggestion
Les deux autres modes de sortie d'Astro peuvent être configurés pour permettre **un rendu à la demande de tout ou partie de vos pages, routes ou points de terminaison d'API** :
```

2023-11-17 17:10 UTC, McFlyPartages commented
> Bon boulot @McFlyPartages, voici quelques suggestions mineures 😁

Voilà c'est validé, merci a toi

2023-11-18 01:39 UTC, thomasbnt approved these changes
LGTM!

2023-11-22 09:48 UTC, McFlyPartages commented
@dreyfus92 vos suggestions ont été ajoutées.

Un petit LGTM pour clôture la PR

2023-11-22 09:48 UTC, McFlyPartages commented
LGTM

2023-11-22 12:54 UTC, Yan-Thomas approved these changes
LGTM! Thanks for the great work 🚀

2023-11-22 12:55 UTC, merged