i18n(fr) Create rss.mdx
withastro/docs pull request #5438
Opened 2023-11-17 11:50 UTC by McFlyPartages

#### Description (required)

Add French translation for rss.mdx file

2023-11-17 20:00 UTC, dreyfus92 requested changes
Bon boulot @McFlyPartages, voici des suggestions 🥳

2023-11-17 20:48 UTC, McFlyPartages commented
> Bon boulot @McFlyPartages, voici des suggestions 🥳

Merci c'est corrigé

2023-11-18 01:06 UTC, thomasbnt approved these changes
LGTM!

2023-11-22 09:48 UTC, McFlyPartages commented
@dreyfus92 vos suggestions ont été ajoutées.

Un petit LGTM pour clôture la PR

2023-11-22 09:48 UTC, McFlyPartages commented
LGTM

2023-11-22 12:36 UTC, Yan-Thomas approved these changes
LGTM! Great work peeps 🙌

2023-11-22 12:37 UTC, merged