i18n(fr) Create `build-forms-api.mdx`
withastro/docs pull request #5440
Opened 2023-11-17 13:01 UTC by McFlyPartages

#### Description (required)

Add french translation for build-forms-api.mdx file

2023-11-17 23:33 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-18 01:19 UTC, thomasbnt requested changes

2023-11-18 01:19 UTC, thomasbnt commented on src/content/docs/fr/recipes/build-forms-api.mdx
> +Cette recette vous montre comment envoyer les données du formulaire au point de terminaison de l'API et comment traiter ces données.
```suggestion
Cette méthode vous montre comment envoyer les données du formulaire au point de terminaison de l'API et comment traiter ces données.
```

2023-11-18 01:33 UTC, dreyfus92 commented on src/content/docs/fr/recipes/build-forms-api.mdx
> +Cette recette vous montre comment envoyer les données du formulaire au point de terminaison de l'API et comment traiter ces données.
Je pense qu’il est correct de garder "recette" puisque Astro fait référence à toutes comme "recipes".

2023-11-18 01:35 UTC, thomasbnt commented on src/content/docs/fr/recipes/build-forms-api.mdx
> +Cette recette vous montre comment envoyer les données du formulaire au point de terminaison de l'API et comment traiter ces données.
J'ai fait cette review, car dans la doc actuelle, la partie "Recipes" se nomme "Méthodes". En soi dans le texte ça correspond bien à ce que le lecteur doit comprendre.

2023-11-18 01:40 UTC, thomasbnt approved these changes
LGTM!

2023-11-18 01:47 UTC, thomasbnt requested changes

2023-11-18 01:47 UTC, thomasbnt commented on src/content/docs/fr/recipes/build-forms-api.mdx
> +Cette recette vous montre comment envoyer les données du formulaire au point de terminaison de l'API et comment traiter ces données.
```suggestion
Cette méthode vous montre comment envoyer les données du formulaire au point de terminaison de l'API et comment traiter ces données.
```

2023-11-22 09:47 UTC, McFlyPartages commented
LGTM

2023-11-22 13:20 UTC, Yan-Thomas approved these changes
LGTM! Thanks 🙌

2023-11-22 13:20 UTC, merged