i18n(fr) Create `docker.mdx`
withastro/docs pull request #5445
Opened 2023-11-17 13:58 UTC by McFlyPartages

#### Description (required)

Add french translation for docker.mdx file

2023-11-18 01:30 UTC, thomasbnt approved these changes
LGTM! 🚀

2023-11-18 01:40 UTC, dreyfus92 requested changes
Bon travail @McFlyPartages, juste une suggestion mineure 😁

2023-11-18 01:40 UTC, dreyfus92 commented on src/content/docs/fr/recipes/docker.mdx
> +:::tip[Keep this in mind]
```suggestion
:::tip[Gardez cela à l’esprit]
```

2023-11-18 01:50 UTC, thomasbnt requested changes

2023-11-18 01:50 UTC, thomasbnt commented on src/content/docs/fr/recipes/docker.mdx
> +Les images et les conteneurs Docker peuvent être déployés sur de nombreuses plateformes différentes, comme AWS, Azure et [Google Cloud](/fr/guides/deploy/google-cloud/#cloud-run-ssr-et-statique). Cet
```suggestion
Les images et les conteneurs Docker peuvent être déployés sur de nombreuses plateformes différentes, comme AWS, Azure et [Google Cloud](/fr/guides/deploy/google-cloud/#cloud-run-ssr-et-statique). Cette méthode ne couvre pas le déploiement de votre site sur une plateforme spécifique, mais vous montre comment configurer Docker pour votre projet.
```

2023-11-18 01:50 UTC, thomasbnt commented on src/content/docs/fr/recipes/docker.mdx
> +## Recette
```suggestion
## Méthode
```

2023-11-22 09:45 UTC, McFlyPartages commented
LGTM

2023-11-22 09:46 UTC, McFlyPartages commented
@thomasbnt @dreyfus92 vos suggestions ont été ajoutées.

Un petit LGTM pour clôture la PR

2023-11-22 14:37 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-22 14:41 UTC, thomasbnt approved these changes
LGTM !

2023-11-22 15:16 UTC, Yan-Thomas approved these changes
LGTM! Great work 🙌

2023-11-22 15:16 UTC, merged