[WIP] i18n(fr) Create `external-links.mdx`
withastro/docs pull request #5446
Opened 2023-11-17 14:02 UTC by McFlyPartages

#### Description (required)

Add french translation for external-links.mdx file

2023-11-18 01:32 UTC, thomasbnt approved these changes
LGTM! (very cool this one)

2023-11-18 01:59 UTC, dreyfus92 requested changes
Bon boulot @McFlyPartages, juste une suggestion mineure 😁

2023-11-18 01:59 UTC, dreyfus92 commented on src/content/docs/fr/recipes/external-links.mdx
> +## Recette
```suggestion
## Méthode
```

2023-11-19 17:32 UTC, McFlyPartages commented
dreyfus92 tes suggestion ont été ajoutées merci a toi.

Un petit LGTM quand tu as du temps ;)

2023-11-19 22:52 UTC, dreyfus92 approved these changes
LGTM les gars ✅

2023-11-20 01:00 UTC, Yan-Thomas approved these changes
LGTM! Great work peeps 🚀

2023-11-20 01:00 UTC, merged