i18n(fr) Create `sharing-state.mdx`
withastro/docs pull request #5448
Opened 2023-11-17 14:42 UTC by McFlyPartages

#### Description (required)

Add french translation for sharing-state.mdx file

2023-11-18 01:28 UTC, thomasbnt requested changes

2023-11-18 01:28 UTC, thomasbnt commented on src/content/docs/fr/recipes/sharing-state.mdx
> +Lors de la création d'un site web Astro, il se peut que vous deviez partager l'état des composants. Astro recommande l'utilisation de [Nano Stores] (https://github.com/nanostores/nanostores) pour le
```suggestion
Lors de la création d'un site web Astro, il se peut que vous deviez partager l'état des composants. Astro recommande l'utilisation de [Nano Stores](https://github.com/nanostores/nanostores) pour le stockage partagé des clients.
```

2023-11-18 01:28 UTC, thomasbnt commented on src/content/docs/fr/recipes/sharing-state.mdx
> +2. Créez un magasin. Dans cet exemple, le magasin indique si un dialogue est ouvert ou non :
```suggestion
2. Créez un store. Dans cet exemple, le store indique si un dialogue est ouvert ou non :
```

2023-11-18 01:28 UTC, thomasbnt commented on src/content/docs/fr/recipes/sharing-state.mdx
> +2. Créez un magasin. Dans cet exemple, le magasin indique si un dialogue est ouvert ou non :
Je pense qu'on devrait laisser "store".

2023-11-18 01:28 UTC, thomasbnt commented on src/content/docs/fr/recipes/sharing-state.mdx
> +    // Écouter les changements dans le magasin et affiche/masque le dialogue en conséquence
```suggestion
    // Écouter les changements dans le sotre et affiche/masque le dialogue en conséquence    
```

2023-11-18 01:59 UTC, dreyfus92 commented on src/content/docs/fr/recipes/sharing-state.mdx
> +## Recette
```suggestion
## Méthode
```

2023-11-18 02:00 UTC, dreyfus92 commented on src/content/docs/fr/recipes/sharing-state.mdx
> +- [Nano Stores on NPM](https://www.npmjs.com/package/nanostores)
```suggestion
- [Nano Stores sur NPM](https://www.npmjs.com/package/nanostores)
```

2023-11-19 17:31 UTC, McFlyPartages commented
@thomasbnt, @dreyfus92 vos suggestion ont été ajouté merci a vous.

Un petit LGTM quand vous avez du temps ;)

2023-11-19 18:00 UTC, thomasbnt approved these changes
LGTM!

2023-11-22 09:45 UTC, McFlyPartages commented
LGTM

2023-11-22 13:30 UTC, merged