i18n(fr) Create `streaming-improve-page-performance.mdx`
withastro/docs pull request #5449
Opened 2023-11-17 14:51 UTC by McFlyPartages

#### Description (required)

Add french translation for streaming-improve-page-performance.mdx file

2023-11-18 01:37 UTC, thomasbnt approved these changes
LGTM! 🔨🚀

2023-11-18 02:04 UTC, dreyfus92 requested changes
Bon boulot @McFlyPartages, juste une petite suggestion 😁

2023-11-18 02:04 UTC, dreyfus92 commented on src/content/docs/fr/recipes/streaming-improve-page-performance.mdx
> +title: Utilisation de la diffusion en continu pour améliorer les performances des pages"
```suggestion
title: "Utilisation de la diffusion en continu pour améliorer les performances des pages"
```

2023-11-19 17:31 UTC, McFlyPartages commented
@dreyfus92 tes suggestions ont été ajouté merci.

Un petit LGTM quand tu as du temps ;)

2023-11-19 22:54 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-20 00:51 UTC, Yan-Thomas approved these changes
LGTM! Thanks peeps 🙌

2023-11-20 00:51 UTC, merged