[WIP] i18n(fr) Create multiple file errors
withastro/docs pull request #5454
Opened 2023-11-17 17:44 UTC by McFlyPartages

#### Description (required)
Add french translation for multiple errors file

2023-11-17 22:55 UTC, McFlyPartages commented
The link error is normal, we have to wait for the validation of PR #5438

2023-11-18 01:26 UTC, thomasbnt requested changes

2023-11-18 01:26 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/unknown-vite-error.mdx
> +Si vous pouvez provoquer cette erreur de manière fiable, nous vous serions reconnaissants de bien vouloir [ouvrir un issue] (https://astro.build/issues/).
```suggestion
Si vous pouvez provoquer cette erreur de manière fiable, nous vous serions reconnaissants de bien vouloir [ouvrir un issue](https://astro.build/issues/).
```

2023-11-18 01:26 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/no-client-only-hint.mdx
> +	<SomeReactComponent client:only="react" />
```suggestion
<SomeReactComponent client:only="react" />
```

2023-11-18 03:36 UTC, dreyfus92 requested changes
Incroyable travail @McFlyPartages, voici quelque suggestions mineures 😁

2023-11-18 03:36 UTC, dreyfus92 commented on src/content/docs/fr/reference/errors/expected-image.mdx
> +**See Also:**
```suggestion
**Voir aussi :**
```

2023-11-18 03:36 UTC, dreyfus92 commented on src/content/docs/fr/reference/errors/astro-glob-no-match.mdx
> +**Voir aussi:**
```suggestion
**Voir aussi :**
```

2023-11-18 03:36 UTC, dreyfus92 commented on src/content/docs/fr/reference/errors/get-static-paths-expected-params.mdx
> +**Voir aussi:**
```suggestion
**Voir aussi :**
```

2023-11-18 03:36 UTC, dreyfus92 commented on src/content/docs/fr/reference/errors/get-static-paths-invalid-route-param.mdx
> +**Voir aussi:**
```suggestion
**Voir aussi :**
```

2023-11-18 03:36 UTC, dreyfus92 commented on src/content/docs/fr/reference/errors/get-static-paths-required.mdx
> +**Voir aussi:**
```suggestion
**Voir aussi :**
```

2023-11-18 03:36 UTC, dreyfus92 commented on src/content/docs/fr/reference/errors/image-missing-alt.mdx
> +**Voir aussi:**
```suggestion
**Voir aussi :**
```

2023-11-22 09:49 UTC, McFlyPartages commented
@thomasbnt @dreyfus92 vos suggestions ont été ajoutées.

Un petit LGTM pour clôture la PR

2023-11-22 09:49 UTC, McFlyPartages commented
LGTM

2023-11-22 14:42 UTC, thomasbnt approved these changes
LGTM !

2023-11-22 14:51 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-22 15:26 UTC, merged