i18n(fr) Create `image-service-reference.mdx`
withastro/docs pull request #5456
Opened 2023-11-17 22:51 UTC by McFlyPartages

#### Description (required)

Add french translation for `image-service-reference.mdx` file

2023-11-18 01:16 UTC, thomasbnt requested changes

2023-11-18 01:16 UTC, thomasbnt commented on src/content/docs/fr/reference/image-service-reference.mdx
> +Pour les services locaux, ce crochet renvoie l'URL du point d'accès qui génère votre image (en mode SSR et dev). Il n'est pas utilisé pendant la construction. Le point d'accès local vers lequel `getU
```suggestion
Pour les services locaux, ce hook renvoie l'URL du point d'accès qui génère votre image (en mode SSR et dev). Il n'est pas utilisé pendant la construction. Le point d'accès local vers lequel `getURL()` pointe peut appeler à la fois `parseURL()` et `transform()`.
```

2023-11-18 01:16 UTC, thomasbnt commented on src/content/docs/fr/reference/image-service-reference.mdx
> +Pour les services externes, ce crochet renvoie l'URL finale de l'image.
```suggestion
Pour les services externes, ce hook renvoie l'URL finale de l'image.
```

2023-11-18 02:14 UTC, dreyfus92 requested changes

2023-11-18 02:14 UTC, dreyfus92 commented on src/content/docs/fr/reference/image-service-reference.mdx
> +      entrypoint: "your-entrypoint", // 'astro/assets/services/squoosh' | 'astro/assets/services/sharp' | string,
```suggestion
      entrypoint: "votre-point-d’entrée", // 'astro/assets/services/squoosh' | 'astro/assets/services/sharp' | string,
```

2023-11-19 17:28 UTC, McFlyPartages commented
@thomasbnt, @dreyfus92 vos suggestion ont été ajouté merci a vous.

LGTM

2023-11-19 18:00 UTC, thomasbnt approved these changes
LGTM!

2023-11-22 09:37 UTC, McFlyPartages commented
LGTM

2023-11-22 12:25 UTC, Yan-Thomas approved these changes
LGTM! Great work peeps 🙌

2023-11-22 12:26 UTC, merged