i18n(fr) Update `error-reference.mdx`
withastro/docs pull request #5488
Opened 2023-11-24 19:42 UTC by McFlyPartages

#### Description (required)
Update transltion for error-reference.mdx file

2023-11-24 20:22 UTC, dreyfus92 approved these changes
LGTM ✅

2023-11-24 20:24 UTC, dreyfus92 commented on src/content/docs/fr/reference/error-reference.mdx
> +- [**PrerenderDynamicEndpointPathCollide**](/fr/reference/errors/prerender-dynamic-endpoint-path-collide/)<br/Le point de terminaison dynamique généré entre en collision avec une autre route.
```suggestion
- [**PrerenderDynamicEndpointPathCollide**](/fr/reference/errors/prerender-dynamic-endpoint-path-collide/)<br/>Le point de terminaison dynamique généré entre en collision avec une autre route.
```

2023-11-24 20:33 UTC, dreyfus92 requested changes
encore 😅

2023-11-24 20:33 UTC, dreyfus92 commented on src/content/docs/fr/reference/error-reference.mdx
> +- [**RedirectWithNoLocation**](/fr/reference/errors/redirect-with-no-location/)<br/Une redirection doit recevoir un emplacement avec l'en-tête `Location`.
```suggestion
- [**RedirectWithNoLocation**](/fr/reference/errors/redirect-with-no-location/)<br/>Une redirection doit recevoir un emplacement avec l'en-tête `Location`.
```

2023-11-25 13:02 UTC, McFlyPartages commented
LGTM

2023-11-27 14:50 UTC, thomasbnt approved these changes
LGTM! 🚀

2023-11-27 15:17 UTC, dreyfus92 commented
LGTM les gars 🫡

2023-11-27 17:31 UTC, Yan-Thomas approved these changes
LGTM! Great work peeps 🚀

2023-11-27 17:32 UTC, merged