Glossary
withastro/docs pull request #5546
Opened 2023-12-02 04:07 UTC by tonyoconnell

#### Description (required)

Added 71 terms to the glossary. Total items now 73

#### Related issues & labels (optional)

- Closes #
- Suggested label:

2023-12-02 10:33 UTC, at-the-vr commented
it usually helps maintainers if you can edit the title more appropriately example https://github.com/withastro/docs/pull/5529 (you dont have to be specific like genteure did but give it a quick change for faster response)

2023-12-02 10:49 UTC, at-the-vr reviewed
I see you have also mentioned changes for [Using Bun with Astro](https://docs.astro.build/en/recipes/bun/) and its not huge so maintainers won't have trouble dealing with it.

Its generally better to stick to the topic in the PR (that is `update glossary.mdx` in this case) and create a separate PR for `update bun.mdx` from next time

2023-12-02 17:13 UTC, sarah11918 commented
(PS - As per the rules, I don't merge a glossary PR until I see some kind of approval and generalized consensus that you all want this merged!)

2023-12-02 17:18 UTC, sarah11918 commented
There we go! Updating main into this branch fixed it. 

Remember, with glossary branch comes glossary responsibility!  :smile:

2023-12-03 18:55 UTC, sarah11918 commented
@at-the-vr I didn't know whether you wanted them worked in, or separate since they'd been discussed and merged in separately... kind of like keeping the list at the bottom as "potential candidates to pull from." But yes, feel free! It's your glossary!

2023-12-12 06:27 UTC, VoxelMC requested changes
Here is my review of the first quarter of the file.

*In the future, can we only submit a handful of terms at once per PR?*
I am impressed with the amount of work it is, but it's a lot to read, and things might slip through the cracks!

The first quarter looks good; please review my comments and let me know what you think of them.

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +Adaptors are essential for deploying Astro projects to different hosting platforms. Each adaptor is tailored to a specific host, such as Netlify, Vercel, or Cloudflare Pages, ensuring compatibility a
```suggestion
## Adapters

Adapters are essential for deploying Astro projects to different hosting platforms. Each adapter is tailored to a specific host, such as Netlify, Vercel, or Cloudflare Pages, ensuring compatibility and streamlined deployment processes. Adapters handle the nuances of each platform, providing a seamless integration for Astro projects.
```

Just some typos :)

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +- [Astro Adaptor API Reference](https://docs.astro.build/en/reference/adapter-reference/)
```suggestion
- [Astro Adapter API Reference](https://docs.astro.build/en/reference/adapter-reference/)
```

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +## API
Not a change, but just a note that we will need to classify these based on Astro-relatedness at some point in the future.

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +- [Client Only Directive](https://docs.astro.build/en/reference/directives-reference/#clientonly)
```suggestion
- [`client:only` Directive](https://docs.astro.build/en/reference/directives-reference/#clientonly)
```
To follow suit with the docs.

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +- [Deploying on Cloudflare Guide](https://docs.astro.build/en/guides/deploy/cloudflare/)
```suggestion
Astro's integration with Cloudflare allows for deploying projects to Cloudflare's edge network, enhancing site performance and reliability. This integration benefits from Cloudflare's global distribution, offering faster content delivery to users.

For more details, see:
- [Guide: Deploying to Cloudflare](https://docs.astro.build/en/guides/deploy/cloudflare/)
```

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +- [Deploy your Astro Site](https://docs.astro.build/en/guides/deploy/)
```suggestion
- [Guide: Deploy your Astro Site](https://docs.astro.build/en/guides/deploy/)
```

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +A Collection Entry is a content piece within a collection directory, supporting formats like Markdown, MDX, YAML, and JSON. These entries are crucial for content organization and management projects.
```suggestion
A Collection Entry is a content piece within a collection directory, supporting formats like Markdown, MDX, YAML, and JSON. 
```

This definition should probably be more in-depth. Content collections and their parts are pretty `crucial` to the Astro experience! Perhaps we can include more about how a collection entry is rendered and more about what a `collection directory` is (and perhaps a re-wording of this).

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +## Components
```suggestion
## Component
```
I will ask others their opinion, but I think the terms should be singular - like a dictionary. LMK what you think of this.

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +## CSS
Perhaps change this to `Scoped Styles` in general
```suggestion
## Scoped Styles
```

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +## Content Collections
```suggestion
## Content Collection
```

2023-12-12 06:27 UTC, VoxelMC commented on contributor-guides/glossary.md
> +Content Collections refer to a method for organizing and managing content within an Astro project. A content collection is a top-level directory inside the `src/content` directory, like `src/content/
```suggestion
Content Collections are used to organize and manage content within an Astro project. A content collection is a top-level directory inside the `src/content` directory, like `src/content/newsletter` or `src/content/authors`. Collection entries can be in various formats, including Markdown, MDX, YAML, and JSON. These collections are integral for structuring documents, validating frontmatter, and providing TypeScript type-safety.
```

2023-12-12 14:51 UTC, sarah11918 commented
Hi everyone! I won't close this PR just yet, to let you grab whatever content and comments you want from it, but please see my comments in the Discord thread about how we'll proceed with this. This current system isn't working, and I've left a message there about what we'll do going forward as this gets off the ground.

So, please be prepared to snag whatever from this PR you want and incorporate it into the new direction, then we'll close this one!

2023-12-12 14:53 UTC, sarah11918 requested changes
This is to be closed once the content from here is incorporated in the new solution.

2023-12-16 02:31 UTC, sarah11918 commented
Hi @at-the-vr @VoxelMC ! I'm going to close this PR now, but of course you can still look at it for reference and snag stuff for HackMD!

2023-12-16 02:31 UTC, closed without merging