i18n(pt-BR): Add `routing.md` translation
withastro/docs pull request #555
Opened 2022-05-14 12:43 UTC by Yan-Thomas

#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [ ] New or updated content
- [x] Translated content
- [ ] Changes to the docs site code
- [ ] Something else!

#### Description

PT-BR translation for `routing.md`

2022-05-28 17:55 UTC, victor0x16 requested changes

2022-05-28 17:55 UTC, victor0x16 commented on src/pages/pt-BR/core-concepts/routing.md
> +Astro utiliza **roteamento baseado em arquivos** para gerar suas URLs na construção com base no layout dos arquivos no diretório `src/pages` do seu projeto. Quando um arquivo é adicionado ao diretóri
```suggestion
Astro utiliza **roteamento baseado em arquivos** para gerar suas URLs na construção com base no layout dos arquivos no diretório `src/pages` do seu projeto. Quando um arquivo é adicionado ao diretório `src/pages` do seu projeto, ele é automaticamente disponibilizado como uma rota baseada no seu nome de arquivo.
```

2022-05-28 17:55 UTC, victor0x16 commented on src/pages/pt-BR/core-concepts/routing.md
> +Componentes Astro que geram rotas dinamicamente tem acesso ao objeto `Astro.params` para cada rota. Isso te permite utilizar as partes geradas de uma URL em seu script e template do componente.ate.
```suggestion
Componentes Astro que geram rotas dinamicamente tem acesso ao objeto `Astro.params` para cada rota. Isso te permite utilizar as partes geradas de uma URL em seu script e template do componente.
```

2022-05-28 17:55 UTC, victor0x16 commented on src/pages/pt-BR/core-concepts/routing.md
> +Quando você utiliza a função `paginate()`, cada página na coleção passará seus dados através da prop `page`. A prop `page` tem diversas propriedades úteis, mas a mais importante é `page.data`. Esta é
```suggestion
Quando você utiliza a função `paginate()`, cada página na coleção passará seus dados através da prop `page`. A prop `page` tem diversas propriedades úteis, mas a mais importante é `page.data`. Esse é o array contendo os pedaços de dados da página que você passou para a função `paginate()`.
```

2022-05-28 17:55 UTC, victor0x16 commented on src/pages/pt-BR/core-concepts/routing.md
> +		/** url da página atuaç */
```suggestion
		/** url da página atual*/
```

2022-05-28 17:55 UTC, victor0x16 commented on src/i18n/pt-BR/nav.ts
> +	'core-concepts/routing': 'Regras de Roteamento',
Routing has been moved.

2022-05-28 18:02 UTC, victor0x16 commented
Just tiny typos!

File based routing makes static website so much more easier to build

2022-05-28 18:48 UTC, Yan-Thomas commented
I will take this opportunity and update the recent changes as well! Thanks for your review @victor0x16!

2022-05-29 12:20 UTC, victor0x16 approved these changes

2022-05-29 12:43 UTC, merged