Add tip for GitHub Private Pages
withastro/docs pull request #5635
Opened 2023-12-06 01:08 UTC by alvgaona

#### Description (required)

The current documentation does not completely take into account private GitHub Pages within organizations. GitHub will create a random URL that has a different treatment to public pages.

2023-12-06 03:40 UTC, dreyfus92 requested changes
Hey @alvgaona, thanks for tackling this 😁. I left a small suggestion.

2023-12-06 03:40 UTC, dreyfus92 commented on src/content/docs/en/guides/deploy/github.mdx
> +    Make sure you configure the `site` key with the given URL - no `base` needed.
```suggestion
    Make sure to set the `site` key to match the auto-generated URL. There's no need to specify a `base` key.
```

2023-12-06 11:49 UTC, alvgaona commented on src/content/docs/en/guides/deploy/github.mdx
> +    Make sure you configure the `site` key with the given URL - no `base` needed.
Awesome. Thank you!

2023-12-13 02:17 UTC, lilnasy commented on src/content/docs/en/guides/deploy/github.mdx
> +    Make sure to set the `site` key to match the auto-generated URL. There's no need to specify a `base` key.
What happens when the `site` config is not set or set to an incorrect origin?

2023-12-13 13:48 UTC, sarah11918 commented
Hi @alvgaona ! This is just a quick note to let you know I'll be looking at this submission this week!

I know it might seem like a small addition, and maybe shouldn't need much review, but even though you've only added a "tip"... when you look at your submission in the surrounding context of the page, it looks like this:

![notecautiontip](https://github.com/withastro/docs/assets/5098874/caabaebf-a55b-4ced-9cb2-bb58dc8d4c00)

This... does not make for good docs.  :sweat_smile: 

What this tells me is that we need to rework our actual documentation with better guidance on using `base`... just adding on more notes, cautions and tips is not the solution here. This is why I haven't yet had the time to review your PR (it's not a "quick win" for me during a busy launch week) and clearly is an indication of much bigger docs work that needs to happen. 

But, it is on my plate to address this! Thank you for your patience!

2023-12-20 18:56 UTC, sarah11918 commented
OK! Thank you for your patience @alvgaona !  :raised_hands: 

There were just too many notes and cautions etc. so that told me that this content needed to be restructured. In fact, I made sections for using a custom domain vs not, since that often determines what you do or don't have to set.

I did of course include the information you provided, just in a different place/way. Thank you for contributing to this page!

2023-12-20 19:04 UTC, alvgaona commented
> OK! Thank you for your patience @alvgaona ! 🙌
> 
> There were just too many notes and cautions etc. so that told me that this content needed to be restructured. In fact, I made sections for using a custom domain vs not, since that often determines what you do or don't have to set.
> 
> I did of course include the information you provided, just in a different place/way. Thank you for contributing to this page!

Thank you, @sarah11918! I

2023-12-20 20:20 UTC, merged