i18n(es): Translate `v4.mdx`
withastro/docs pull request #5717
Opened 2023-12-10 03:30 UTC by Waxer59

#### Description (required)

Translate `v4.mdx`

2023-12-10 04:37 UTC, Waxer59 commented on src/content/docs/es/guides/upgrade-to/v4.mdx
> +También puedes [actualizar tus integraciones de Astro manualmente](/en/guides/integrations-guide/#manual-upgrading) si es necesario, y puede que también necesites actualizar otras dependencias en tu
```suggestion
También puedes [actualizar tus integraciones de Astro manualmente](/en/guides/integrations-guide/#actualización-manual) si es necesario, y puede que también necesites actualizar otras dependencias en tu proyecto.
```

2023-12-10 04:37 UTC, Waxer59 commented on src/content/docs/es/guides/upgrade-to/v4.mdx
> +Astro v4.0 incluye [cambios potencialmente importantes](#breaking-changes), así como la [eliminación de algunas funciones obsoletas](#características-previamente-obsoletas-ahora-eliminadas).
```suggestion
Astro v4.0 incluye [cambios potencialmente importantes](#cambios-importantes), así como la [eliminación de algunas funciones obsoletas](#características-previamente-obsoletas-ahora-eliminadas).
```

2023-12-11 22:22 UTC, dreyfus92 requested changes
Buen trabajo @Waxer59, te dejo una sugerencia 😁

2023-12-11 22:22 UTC, dreyfus92 commented on src/content/docs/es/guides/upgrade-to/v4.mdx
> +También puedes [actualizar tus integraciones de Astro manualmente](/en/guides/integrations-guide/#actualización-manual) si es necesario, y puede que también necesites actualizar otras dependencias en
```suggestion
También puedes [actualizar tus integraciones de Astro manualmente](/es/guides/integrations-guide/#actualización-manual) si es necesario, y puede que también necesites actualizar otras dependencias en tu proyecto.
```

2023-12-11 22:25 UTC, Waxer59 commented
Gracias por la revisión 🤠

2023-12-12 00:28 UTC, sarah11918 approved these changes
Thank you, @waxer59 !

2023-12-12 00:29 UTC, merged