Create turso.mdx
withastro/docs pull request #6022
Opened 2024-01-01 19:01 UTC by MartinFerret

French translation of the turso.mdx

2024-01-01 19:01 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-01-01 22:10 UTC, MartinFerret commented
@florian-lefebvre , est-ce normal que j'ai un failed au niveau du deploy Bervel - docs ?

2024-01-01 22:36 UTC, florian-lefebvre commented
I'm not really active on this repo so I don't why that happens. Don't worry, if you need to do anything someone will tell while reviewing

2024-01-03 01:35 UTC, shuuji3 commented
Hi, I'm not a French translator but I think the cause of the error is because the frontmatter keys such as `title:` and `i18nReady` are translated.

This error message (https://vercel.com/astrodotbuild/docs/5NwrZMZhvB6f4CJq1cR1Bvx7Gs2D#L26) tells us that it cannot find an expected key `title:` in the header.

These headers have special meaning so when translating documentation, we should keep them in English though you can translate the right-hand text after `:`.

2024-01-03 01:39 UTC, shuuji3 requested changes
Could you try this change?

2024-01-03 01:39 UTC, shuuji3 commented on src/content/docs/fr/guides/backend/turso.mdx
> +titre: Turso & Astro
```suggestion
title: Turso & Astro
```

2024-01-03 04:35 UTC, MartinFerret commented
> I also put a comment on #6023 🙂

Thanks a lot for commenting and helping ! 😀

2024-01-03 10:27 UTC, VoxelMC approved these changes
Ça a l'air génial ! Thank you Martin!

`As a non-native speaker, I reviewed this PR using the Docs Translation Review Checklist and it LGTM!`

2024-01-03 17:17 UTC, McFlyPartages reviewed
Hey,

Thanks for good work, here are a few suggestions.

2024-01-03 17:17 UTC, McFlyPartages commented on src/content/docs/fr/guides/backend/turso.mdx
> +- Le [Turso CLI](https://docs.turso.tech/reference/turso-cli) installé et connecté
```suggestion
- [Turso CLI](https://docs.turso.tech/reference/turso-cli) installé et connecté
```

2024-01-03 17:17 UTC, McFlyPartages commented on src/content/docs/fr/guides/backend/turso.mdx
> +:::attention
```suggestion
:::caution
```

It's not necessary to translate this

2024-01-03 22:21 UTC, McFlyPartages approved these changes
LGTM

2024-01-03 22:42 UTC, Yan-Thomas approved these changes
LGTM! Great work y'all! 💜

2024-01-03 22:42 UTC, merged