i18n(fr): Add `integrations-guide/deno` in French language
withastro/docs pull request #6061
Opened 2024-01-02 23:04 UTC by thomasbnt

#### Description (required)
i18n(fr): Add `integrations-guide/deno` in French language

#### Related issues & labels (optional)

- Linked to https://github.com/withastro/docs/issues/6052
- Suggested label: i18n

2024-01-03 15:51 UTC, McFlyPartages reviewed
Several suggestions but good works.

2024-01-03 15:51 UTC, McFlyPartages commented on src/content/docs/fr/guides/integrations-guide/deno.mdx
> +You can deploy to Deno Deploy through GitHub Actions or using Deno Deploy’s CLI (command line interface).
```suggestion

```

2024-01-03 15:51 UTC, McFlyPartages commented on src/content/docs/fr/guides/integrations-guide/deno.mdx
> +1. Après avoir validé ce fichier YAML, et l'avoir poussé sur GitHub sur votre branche de déploiement configurée, le déploiement devrait commencer automatiquement !
```suggestion
1. Après avoir validé ce fichier YAML et l'avoir poussé sur votre branche de déploiement configurée, le déploiement devrait commencer automatiquement !
```

2024-01-03 15:51 UTC, McFlyPartages commented on src/content/docs/fr/guides/integrations-guide/deno.mdx
> +1) (Optionnel) Pour simplifier la construction et le déploiement en une seule commande, ajoutez un script `deploy-deno` dans `package.json`.
```suggestion
1. (Optionnel) Pour simplifier la construction et le déploiement en une seule commande, ajoutez un script `deploy-deno` dans `package.json`.
```

2024-01-03 15:55 UTC, thomasbnt commented on src/content/docs/fr/guides/integrations-guide/deno.mdx
> +You can deploy to Deno Deploy through GitHub Actions or using Deno Deploy’s CLI (command line interface).
Oh merci, j'ai oublié de supprimer la version anglaise..

2024-01-03 16:03 UTC, dreyfus92 approved these changes
LGTM ✅

2024-01-03 16:36 UTC, Yan-Thomas commented on src/content/docs/fr/guides/integrations-guide/deno.mdx
> +1. Installez le [Deno Deploy CLI] (https://docs.deno.com/deploy/manual/deployctl).
```suggestion
1. Installez le [Deno Deploy CLI](https://docs.deno.com/deploy/manual/deployctl).
```

2024-01-03 16:41 UTC, McFlyPartages commented
LGTM 😛

2024-01-03 16:50 UTC, Yan-Thomas requested changes
The translated page here is `/guides/deploy/deno`, but is in the place of the `integrations-guide/deno` place. The translation seems fine, but we need to move it to the correct file path.

2024-01-04 17:35 UTC, Yan-Thomas approved these changes

2024-01-04 17:43 UTC, Yan-Thomas approved these changes
LGTM! Thanks 🙌

2024-01-04 17:43 UTC, merged