i18n(fr): Add `integrations-guide/mdx` in French language
withastro/docs pull request #6125
Opened 2024-01-04 15:17 UTC by thomasbnt

#### Description (required)
Add `integrations-guide/mdx` in French language

#### Related issues & labels (optional)

- Linked to https://github.com/withastro/docs/issues/6052
- Suggested label: i18n

2024-01-04 15:28 UTC, pioupia requested changes

2024-01-04 15:29 UTC, thomasbnt commented
Merci @pioupia pour le lien!

2024-01-04 21:12 UTC, dreyfus92 reviewed
Bon boulot mec, voici une petite suggestion

2024-01-04 21:12 UTC, dreyfus92 commented on src/content/docs/fr/guides/integrations-guide/mdx.mdx
> +[astro-ui-frameworks]: /fr/core-concepts/framework-components/#using-framework-components
```suggestion
[astro-ui-frameworks]: /fr/core-concepts/framework-components/#utilisation-des-composants-de-framework
```

2024-01-04 21:39 UTC, thomasbnt commented
> Bon boulot @thomasbnt , voici une petite suggestion

Merci ! 🚀

2024-01-05 09:06 UTC, pioupia requested changes

2024-01-05 09:06 UTC, pioupia commented on src/content/docs/fr/guides/integrations-guide/mdx.mdx
> +Une propriété optionnelle de `optimize` pour empêcher l'optimiseur MDX de gérer tout [composant personnalisé passé au contenu MDX importé via la propriété components](/fr/guides/markdown-content/#com
L'`optimiseur` c'est français ? J'aurais plutôt dit [`optimisateur`](https://www.larousse.fr/dictionnaires/francais/optimiser/56254) personnellement
```suggestion
Une propriété optionnelle de `optimize` pour empêcher l'optimisateur MDX de gérer tout [composant personnalisé passé au contenu MDX importé via la propriété components](/fr/guides/markdown-content/#composants-personnalisés-avec-du-mdx-importé).
```

2024-01-05 09:06 UTC, pioupia commented on src/content/docs/fr/guides/integrations-guide/mdx.mdx
> +Vous devrez exclure ces composants de l'optimisation, car l'optimiseur convertit trop rapidement le contenu en une chaîne statique, ce qui brisera les composants personnalisés qui ont besoin d'être r
```suggestion
Vous devrez exclure ces composants de l'optimisation, car l'optimisateur convertit trop rapidement le contenu en une chaîne statique, ce qui brisera les composants personnalisés qui ont besoin d'être rendus dynamiquement.
```

2024-01-05 09:06 UTC, pioupia commented on src/content/docs/fr/guides/integrations-guide/mdx.mdx
> +        // Empêcher l'optimiseur de traiter les éléments `h1`.
```suggestion
        // Empêcher l'optimisateur de traiter les éléments `h1`.
```

2024-01-05 09:06 UTC, pioupia commented on src/content/docs/fr/guides/integrations-guide/mdx.mdx
> +Notez que si votre fichier MDX [configure les composants personnalisés en utilisant `export const components = { ... }`](/fr/guides/markdown-content/#affectation-de-composants-personnalisés-à-des-élé
```suggestion
Notez que si votre fichier MDX [configure les composants personnalisés en utilisant `export const components = { ... }`](/fr/guides/markdown-content/#affectation-de-composants-personnalisés-à-des-éléments-html), alors vous n'avez pas besoin de configurer manuellement cette option. L'optimisateur les détectera automatiquement.
```

2024-01-05 09:52 UTC, thomasbnt commented on src/content/docs/fr/guides/integrations-guide/mdx.mdx
> +      // seulement `remarkPlugin2` est appliquée.
Tout est modifié ! Merci !

2024-01-06 16:57 UTC, dreyfus92 approved these changes
LGTM ✅

2024-01-06 17:48 UTC, merged