i18n(fr) Update ` error-reference.mdx` and add `cant-render-page.mdx`, `missing-locale.mdx` and `unhandled-rejection.mdx`
withastro/docs pull request #6369
Opened 2024-01-13 12:55 UTC by McFlyPartages

#### Description (required)
Update ` error-reference.mdx` and add `cant-render-page.mdx`, `missing-locale.mdx` and `unhandled-rejection.mdx with last PR #6253

2024-01-13 22:17 UTC, thomasbnt requested changes

2024-01-13 22:17 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/unhandled-rejection.mdx
> +
```suggestion
---
title: Unhandled rejection
i18nReady: true
githubURL: https://github.com/withastro/astro/blob/main/packages/astro/src/core/errors/errors-data.ts





---
import DontEditWarning from '~/components/DontEditWarning.astro'

<DontEditWarning />


> **UnhandledRejection**: Astro a détecté un rejet non traité. Voici la trace de la pile:<br/>STACK

## Qu'est-ce qui n'a pas marché ?
Astro n'a pas pu trouver de code pour gérer une `Promise` rejetée. Assurez-vous que toutes vos promesses ont un gestionnaire `await` ou `.catch()`.
```

Manque le component et des lignes en trop, conformément à la doc originale https://github.com/withastro/docs/blob/main/src/content/docs/en/reference/errors/unhandled-rejection.mdx

2024-01-13 22:17 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/missing-locale.mdx
> +
```suggestion
---
title: The provided locale does not exist.
i18nReady: true
githubURL: https://github.com/withastro/astro/blob/main/packages/astro/src/core/errors/errors-data.ts





---
import DontEditWarning from '~/components/DontEditWarning.astro'

<DontEditWarning />


> **MissingLocale**: La locale/chemin `LOCALE` n'existe pas dans le fichier configuré `i18n.locales`.

## Qu'est-ce qui n'a pas fonctionné ?
Astro ne trouve pas la locale demandée. Toutes les locales supportées doivent être configurées dans [i18n.locales](/fr/reference/configuration-reference/#i18nlocales) et avoir des répertoires correspondants dans `src/pages/`.
```

2024-01-13 22:17 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/cant-render-page.mdx
> +Astro n'a pas pu trouver de fichier associé avec du contenu en essayant de rendre l'itinéraire. Il s'agit d'une erreur d'Astro et non d'une erreur de l'utilisateur. Si le redémarrage du serveur de dé
```suggestion
---
title: Astro ne peut pas restituer la route.
i18nReady: true
githubURL: https://github.com/withastro/astro/blob/main/packages/astro/src/core/errors/errors-data.ts





---
import DontEditWarning from '~/components/DontEditWarning.astro'

<DontEditWarning />


> **CantRenderPage**: Astro ne trouve aucun contenu à rendre pour cet itinéraire. Il n'y a pas de fichier ou de redirection associé à cette route.

## Qu'est-ce qui n'a pas fonctionné ?
Astro n'a pas pu trouver de fichier associé avec du contenu en essayant de rendre l'itinéraire. Il s'agit d'une erreur d'Astro et non d'une erreur de l'utilisateur. Si le redémarrage du serveur de développement ne résout pas le problème, veuillez déposer un problème.
```

2024-01-13 22:30 UTC, McFlyPartages commented on src/content/docs/fr/reference/errors/unhandled-rejection.mdx
> +
Humm le `<DontEditWarning />` doit être enlevé dans les traductions non ?, c'est le gros pavé de commentaire en début de fichier.

Ppour le reste Thanks ;)

2024-01-13 22:33 UTC, McFlyPartages commented on src/content/docs/fr/reference/errors/missing-locale.mdx
> +
```suggestion
---
title: The provided locale does not exist.
i18nReady: true
githubURL: https://github.com/withastro/astro/blob/main/packages/astro/src/core/errors/errors-data.ts





---
import DontEditWarning from '~/components/DontEditWarning.astro'




> **MissingLocale**: La locale/chemin `LOCALE` n'existe pas dans le fichier configuré `i18n.locales`.

## Qu'est-ce qui n'a pas fonctionné ?
Astro ne trouve pas la locale demandée. Toutes les locales supportées doivent être configurées dans [i18n.locales](/fr/reference/configuration-reference/#i18nlocales) et avoir des répertoires correspondants dans `src/pages/`.

```

2024-01-13 22:34 UTC, McFlyPartages commented on src/content/docs/fr/reference/errors/unhandled-rejection.mdx
> +
```suggestion
---
title: Unhandled rejection
i18nReady: true
githubURL: https://github.com/withastro/astro/blob/main/packages/astro/src/core/errors/errors-data.ts





---
import DontEditWarning from '~/components/DontEditWarning.astro'




> **UnhandledRejection**: Astro a détecté un rejet non traité. Voici la trace de la pile:<br/>STACK
> 
## Qu'est-ce qui n'a pas marché ?
Astro n'a pas pu trouver de code pour gérer une `Promise` rejetée. Assurez-vous que toutes vos promesses ont un gestionnaire `await` ou `.catch()`.
```

2024-01-13 22:35 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/unhandled-rejection.mdx
> +
Ah je sais pas... je demande dans le serveur Discord

2024-01-13 22:36 UTC, McFlyPartages commented on src/content/docs/fr/reference/errors/missing-locale.mdx
> +
```suggestion
---
title: The provided locale does not exist.
i18nReady: true
githubURL: https://github.com/withastro/astro/blob/main/packages/astro/src/core/errors/errors-data.ts





---
import DontEditWarning from '~/components/DontEditWarning.astro'




> **MissingLocale**: La locale/chemin `LOCALE` n'existe pas dans le fichier configuré `i18n.locales`.

## Qu'est-ce qui n'a pas fonctionné ?
Astro ne trouve pas la locale demandée. Toutes les locales supportées doivent être configurées dans [i18n.locales](/fr/reference/configuration-reference/#i18nlocales) et avoir des répertoires correspondants dans `src/pages/`.
```

2024-01-13 22:46 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/unhandled-rejection.mdx
> +
> Humm le `<DontEditWarning />` doit être enlevé dans les traductions non ?, c'est le gros pavé de commentaire en début de fichier.
> 
> ```
> # Translators, please remove this note and the <DontEditWarning/> component.
> ```
> 
> Pour le reste Thanks ;)

ok good tu peux close mes reviews

2024-01-13 22:59 UTC, thomasbnt approved these changes
LGTM

2024-01-13 23:55 UTC, dreyfus92 reviewed
Bon travail @McFlyPartages, voici quelques suggestions.

2024-01-13 23:55 UTC, dreyfus92 commented on src/content/docs/fr/reference/errors/cant-render-page.mdx
> +import DontEditWarning from '~/components/DontEditWarning.astro'
L'import n'est pas requis.

2024-01-13 23:55 UTC, dreyfus92 commented on src/content/docs/fr/reference/errors/missing-locale.mdx
> +import DontEditWarning from '~/components/DontEditWarning.astro'
L'import n'est pas requis

2024-01-13 23:55 UTC, dreyfus92 commented on src/content/docs/fr/reference/errors/unhandled-rejection.mdx
> +import DontEditWarning from '~/components/DontEditWarning.astro'
L'import n'est pas requis

2024-01-14 08:31 UTC, McFlyPartages commented
> Bon travail @McFlyPartages, voici quelques suggestions.

C'est règle merci

2024-01-14 17:47 UTC, dreyfus92 approved these changes
Merci à tous, LGTM ✅

2024-01-14 17:56 UTC, merged