i18n(fr) Update `client-side-scripts.mdx`
withastro/docs pull request #6371
Opened 2024-01-13 13:37 UTC by McFlyPartages

#### Description (required)

Update french translation for client-side-scripts.mdx with last PR #6267 and more old fix

2024-01-13 22:24 UTC, thomasbnt requested changes

2024-01-13 22:24 UTC, thomasbnt commented on src/content/docs/fr/guides/client-side-scripts.mdx
> +<ReadMore>📚 Pour en savoir plus sur les éléments personnalisés, consultez [le guide des composants Web réutilisables de web.dev (EN)](https://web.dev/custom-elements-v1/) et [l'introduction aux éléme
```suggestion
<ReadMore>Pour en savoir plus sur les éléments personnalisés, consultez [le guide des composants Web réutilisables de web.dev (EN)](https://web.dev/custom-elements-v1/) et [l'introduction aux éléments personnalisés de MDN](https://developer.mozilla.org/fr/docs/Web/API/Web_components/Using_custom_elements).</ReadMore>
```

https://github.com/withastro/docs/blob/c931bcf2f1903846cf6d88f8aefc86dc4f58e570/src/content/docs/en/guides/client-side-scripts.mdx#L195

2024-01-13 22:40 UTC, McFlyPartages commented on src/content/docs/fr/guides/client-side-scripts.mdx
> +<ReadMore>📚 Pour en savoir plus sur les éléments personnalisés, consultez [le guide des composants Web réutilisables de web.dev (EN)](https://web.dev/custom-elements-v1/) et [l'introduction aux éléme
C'est good merci

2024-01-14 00:03 UTC, dreyfus92 approved these changes
Merci les gars, LGTM ✅

2024-01-14 00:13 UTC, merged