i18n(fr) Big Update for `typescript.mdx`
withastro/docs pull request #6372
Opened 2024-01-13 14:38 UTC by McFlyPartages

#### Description (required)

Update french translation for typescript.mdx file with PR #2546 #2690 #2765 #2727 #2728 #2891 #2944 #2963 #2948 #2993 #3263 #4059 #4446 #4899 #5051 #5070 #5284 #5547 #4266 #5765 #6109 #6267

2024-01-13 22:11 UTC, thomasbnt requested changes

2024-01-13 22:11 UTC, thomasbnt commented on src/content/docs/fr/install/manual.mdx
> +📚 Lisez le [guide d'installation de TypeScript](/fr/guides/typescript/#configuration) d'Astro pour plus informations.
```suggestion
<ReadMore>Lisez le [guide d'installation de TypeScript](/fr/guides/typescript/#configuration) d'Astro pour plus informations.</ReadMore>
```

Et ne pas oublier d'importer ligne 9 `import ReadMore from '~/components/ReadMore.astro'`. Voir https://github.com/withastro/docs/blob/c931bcf2f1903846cf6d88f8aefc86dc4f58e570/src/content/docs/en/install/manual.mdx

2024-01-13 22:56 UTC, McFlyPartages commented
C'est validé @thomasbnt merci ;)

2024-01-14 00:08 UTC, thomasbnt requested changes

2024-01-14 00:08 UTC, thomasbnt commented on src/content/docs/fr/guides/typescript.mdx
> +import ReadMore from '~/components/ReadMore.astro'
```suggestion
```
https://github.com/withastro/docs/actions/runs/7515324553/job/20459129743?pr=6372

2024-01-14 16:39 UTC, thomasbnt approved these changes
LGTM!

2024-01-14 19:08 UTC, dreyfus92 approved these changes
LGTM 😁

2024-01-14 19:21 UTC, merged