i18n(fr) Big update for `testing.mdx`
withastro/docs pull request #6374
Opened 2024-01-13 15:23 UTC by McFlyPartages

#### Description (required)

Big update for testing.mdx file with PRs
#5941 #5822 #5572 #4722
#4514 #397 #3071 #2897 #2798 #2762 #2689 #2720

2024-01-13 22:07 UTC, thomasbnt requested changes

2024-01-13 22:07 UTC, thomasbnt commented on src/content/docs/fr/guides/testing.mdx
> +A la racine de votre projet, créez un fichier `cypress.config.js` avec le contenu suivant :
```suggestion
À la racine de votre projet, créez un fichier `cypress.config.js` avec le contenu suivant :
```

2024-01-13 22:07 UTC, thomasbnt commented on src/content/docs/fr/guides/testing.mdx
> +- [[Introduction à Cypress](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress)
```suggestion
- [Introduction à Cypress](https://docs.cypress.io/guides/core-concepts/introduction-to-cypress)
```

2024-01-13 22:07 UTC, thomasbnt commented on src/content/docs/fr/guides/testing.mdx
> +Vous pouvez exécuter les tests avec [NightwatchJS VSCode Extension] (https://marketplace.visualstudio.com/items?itemName=browserstackcom.nightwatch) ou en utilisant les étapes CLI ci-dessous :
```suggestion
Vous pouvez exécuter les tests avec [NightwatchJS VSCode Extension](https://marketplace.visualstudio.com/items?itemName=browserstackcom.nightwatch) ou en utilisant les étapes CLI ci-dessous :
```

2024-01-13 22:54 UTC, McFlyPartages commented
Merci @thomasbnt c'est corrigé

2024-01-13 23:00 UTC, thomasbnt approved these changes
LGTM!

2024-01-14 00:38 UTC, dreyfus92 reviewed
Bon boulot @McFlyPartages, voici une petite suggestion.

2024-01-14 00:38 UTC, dreyfus92 commented on src/content/docs/fr/guides/testing.mdx
> +- Démarrer avec Playwright](https://playwright.dev/docs/intro)
```suggestion
- [Démarrer avec Playwright](https://playwright.dev/docs/intro)
```

2024-01-14 08:33 UTC, McFlyPartages commented
> Bon boulot @McFlyPartages, voici une petite suggestion.

Merci pour l'erreur

2024-01-14 17:57 UTC, dreyfus92 approved these changes
Merci les gars, LGTM ✅

2024-01-14 18:06 UTC, merged