i18n(zh-CN): Add supabase.mdx
withastro/docs pull request #6395
Opened 2024-01-15 08:47 UTC by gxy5202

Add supabase.mdx

#### Description (required)
add supabase.mdx

#### Related issues & labels (optional)

- Closes #
- Suggested label:

2024-01-15 08:47 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-01-16 01:07 UTC, liruifengv commented
There is something in the backend that is not marked as i18nready: true. check if it needs to be translated? @Yan-Thomas

2024-01-16 01:15 UTC, liruifengv requested changes
Thanks for your contribution. I've submitted some suggestions, and waiting for Yan's confirmation.

2024-01-16 01:15 UTC, liruifengv commented on src/content/docs/zh-cn/guides/backend/supabase.mdx
> +- [一个已经初始化 Supabase 的 Astro 项目](#initializing-supabase-in-astro).
```suggestion
- [一个已经初始化 Supabase 的 Astro 项目](#在-astro-中初始化-supabase)。
```

2024-01-16 01:15 UTC, liruifengv commented on src/content/docs/zh-cn/guides/backend/supabase.mdx
> +  <p>Already have an account? <a href="/signin">Sign in</a></p>
We tend to translate the English in the code into Chinese as well.

2024-01-16 01:15 UTC, liruifengv commented on src/content/docs/zh-cn/guides/backend/supabase.mdx
> +- [Getting into the holiday spirit with Astro, React, and Supabase](https://www.aleksandra.codes/astro-supabase)
This needs to be translated as well.

2024-01-18 04:45 UTC, huyikai commented on src/content/docs/zh-cn/guides/backend/supabase.mdx
> +    <button type="submit">Login</button>
```suggestion
<Layout title="登录">
  <h1>登录</h1>
  <p>New here? <a href="/register">创建帐户</a></p>
  <form action="/api/auth/signin" method="post">
    <label for="email" for="email">电子邮件</label>
    <input type="email" name="email" id="email" />
    <label for="password">密码</label>
    <input type="password" name="password" id="password" />
    <button type="submit">登录</button>
```

2024-01-20 09:08 UTC, gxy5202 commented on src/content/docs/zh-cn/guides/backend/supabase.mdx
> +    <button type="submit">Login</button>
thanks

2024-01-20 09:08 UTC, gxy5202 commented on src/content/docs/zh-cn/guides/backend/supabase.mdx
> +- [Getting into the holiday spirit with Astro, React, and Supabase](https://www.aleksandra.codes/astro-supabase)
thanks

2024-01-20 09:27 UTC, gxy5202 commented
Thank you guys, I pushed a new commit to solve these issues.
@liruifengv @huyikai

2024-01-22 01:02 UTC, liruifengv commented
> Thank you guys, I pushed a new commit to solve these issues. @liruifengv @huyikai

Thanks, please resolve conversations abolve.

2024-01-22 01:03 UTC, liruifengv commented
> There is something in the backend that is not marked as `i18nready: true`. check if it needs to be translated? @Yan-Thomas

cc @Yan-Thomas @sarah11918

2024-01-22 07:40 UTC, gxy5202 commented
> > Thank you guys, I pushed a new commit to solve these issues. @liruifengv @huyikai
> 
> Thanks, please resolve conversations abolve.

Yes, i just did it, thanks again~

2024-01-23 18:43 UTC, Yan-Thomas commented
> There is something in the backend that is not marked as i18nready: true. check if it needs to be translated?

It should be good to be translated, thanks for checking!

2024-01-24 01:00 UTC, liruifengv approved these changes
So, I can write LGTM!

2024-01-24 15:08 UTC, Yan-Thomas approved these changes
LGTM! Good job, and welcome to Team Docs @gxy5202!

2024-01-24 15:08 UTC, merged