i18n(fr): Adding `data-fetching.md` translation
withastro/docs pull request #660
Opened 2022-05-26 06:52 UTC by Chrissdroid

#### What kind of changes does this PR include?

- [x] New or updated content
- [x] Translated content

#### Description

- What does this PR change? Adds `/fr/guides/data-fetching.md` to the french translation.

2022-05-26 13:26 UTC, naomiHauret requested changes

2022-05-26 13:26 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +description: Apprennez comment récupérer des données distantes avec Astro en utilisant l'API fetch.
description: Apprenez comment récupérer des données distantes avec Astro en utilisant l'API fetch.

2022-05-26 13:26 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +Les fichiers `.astro` peuvent récupérer des données distantes à l'étape de Build pour aider la génération de vos pages.
Les fichiers `.astro` peuvent récupérer des données distantes à l'étape de Build (assemblage) pour aider la génération de vos pages.

2022-05-26 13:26 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +Tous les [composants Astro](/fr/core-concepts/astro-components/) ont accès à la [fonction globale `fetch()`](https://developer.mozilla.org/fr/docs/Web/API/fetch) dans leur Script de composant pour ef
Tous les [composants Astro](/fr/core-concepts/astro-components/) ont accès à la [fonction globale `fetch()`](https://developer.mozilla.org/fr/docs/Web/API/fetch) dans leur Script de composant pour effectuer des requêtes HTTP vers des APIs. Cet appel de fonction sera exécuté à l'étape de Build, et les données seront disponibles pour le Template de composant afin de générer du HTML dynamique.

2022-05-26 13:26 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Prenez profit de la fonctionnalité "[**top-level await (EN)**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#top_level_await)" à l'intérieur de votre Script de
> 💡 Profitez de la fonctionnalité "[**top-level await (EN)**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await#top_level_await)" à l'intérieur de votre Script de composant Astro.

2022-05-26 13:26 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
> 💡 Passez les données distantes récupérées à la fois à Astro et aux composants de Framework comme props (propriétés).

2022-05-26 13:26 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +<!-- Données récupérées à l'étape de Build peuvent être affichées dans l'HTML -->
Les données récupérées à l'étape de build peuvent être affichées dans l'HTML

2022-05-26 13:26 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +<!-- Données récupérées à l'étape de Build peuvent être transmises aux composants comme des propriétés -->
Les données récupérées à l'étape de build peuvent être transmises aux composants comme props

2022-05-26 13:26 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +> 💡 N'oubliez pas, toutes les données dans les composants Astro sont récupérées lorsqu'un composant est rendu sur le serveur.
> 💡 N'oubliez pas que toutes les données d'uncomposant Astro sont récupérées lorsque celui-ci est rendu sur le serveur.

2022-05-26 13:58 UTC, Chrissdroid commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
Je vois l'idée de ce changement, mais ça fait pas une répétition pour rien au final ? 🤔

2022-05-26 13:59 UTC, Chrissdroid commented on src/pages/fr/guides/data-fetching.md
> +<!-- Données récupérées à l'étape de Build peuvent être transmises aux composants comme des propriétés -->
Je vois, c'était pour ça le changement plus haut, mais étant donné qu'on le montre avec un exemple, a-t-on vraiment besoin de faire cette précision ?

2022-05-26 15:18 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
certains termes sont assez difficiles à traduire en français (build, routing, props... j'ai hésité partout soit à mettre en français soit à garder en anglais, mais il faudrait uniformiser sans doute) :sweat_smile:

2022-05-26 20:12 UTC, Chrissdroid commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
Je pourrais prendre la doc de React comme exemple qui utilise beaucoup ça car c'est dans son coeur, mais dans le cas d'Astro c'est équivalent a des balises HTML utilisant des propriétés (Sauf si l'on parle de l'interface `Props` fournie pour l'autocomplétion. Je pense qu'il serais intérésant de faire la distinction entre le JSX et la syntaxe HTML améliorée fourni par Astro

2022-05-27 09:50 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +<!-- Données récupérées à l'étape de Build peuvent être transmises aux composants comme des propriétés -->
pas faux :+1:

2022-05-27 09:55 UTC, naomiHauret commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
dans ce cas si prend HTMLplutôt que JSX comme base on devrait utiliser [attribut](https://developer.mozilla.org/fr/docs/Web/HTML/Attributes) comme terme plutôt que propriété non :thinking: ? 

Ou alors on utilise `propriété` plutôt que `attribut` pour éviter la confusion entre attribut (= "natif" à HTML) et propriété (= pas "natif" à HTML, rajouté par le développeur) ?

2022-05-27 13:07 UTC, Chrissdroid commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
C'est une bonne question a creuser, c'est vrai. Je crois que dans la doc anglaise, seulement attribut est utilisé pour les valeurs HTML classique, mais je suis pas sûre, il faudrait demander, je vais vérifier tout ça

2022-06-03 09:14 UTC, delucis commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
Est-ce qu’on a une décision à ce sujet ? Il ne reste que ça pour avoir un LGTM, n’est-ce pas ?

2022-06-03 10:14 UTC, Chrissdroid commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
Je n'ai pas encore de décision prise a ce sujet, il reste plus que ça oui, mais si je devais prendre une décision je dirais qu'utiliser "Props" ne serais qu'en parlant de l'interface typescript pour les composants Astro pour éviter de confondre avec d'autres framework

2022-06-03 10:40 UTC, delucis commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
Donc on le laisse comme c’est maintenant et vous pouvez revenir sur ce sujet plus tard si vous voulez?

2022-06-03 10:42 UTC, Chrissdroid commented on src/pages/fr/guides/data-fetching.md
> +> 💡 Passez les données récupérées par Astro aux composants de Framework, comme des propriétés.
Je le gardes toujours dans un coin de ma tête, oui

De toutes façons il faut bien remplir ce glossaire 😅

On peut laisser comme ça avant de prendre une décision là dessus dans le futur

2022-06-03 10:54 UTC, delucis approved these changes
Approved! There’s some nitty-gritty discussion around “props” vs “propriétés” but that can be resolved later.

Thanks @Chrissdroid and thanks @naomiHauret for reviewing! 💜

2022-06-03 10:57 UTC, merged