i18n(fr): Adding `environment-variables.md` translation
withastro/docs pull request #661
Opened 2022-05-26 06:52 UTC by Chrissdroid

#### What kind of changes does this PR include?

- [x] New or updated content
- [x] Translated content

#### Description

- What does this PR change? Adds `/fr/guides/environment-variables.md` to the french translation.

2022-05-26 13:39 UTC, naomiHauret requested changes

2022-05-26 13:39 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +Astro utilise Vite pour les variables d'environnement, et permet d'utiliser [n'importe quelle de ses méthodes](https://vitejs.dev/guide/env-and-mode.html) pour obtenir et définir des variables d'envi
Astro utilise Vite pour les variables d'environnement, et permet d'utiliser [n'importe quelle méthode de Vite](https://vitejs.dev/guide/env-and-mode.html) pour obtenir et définir des variables d'environnement.

2022-05-26 13:39 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +Jetez un oeil à l'exemple officiel des [variables d'environnement](https://github.com/withastro/astro/tree/main/examples/env-vars) pour connaître des meilleures pratiques.
Jetez un oeil à l'exemple officiel des [variables d'environnement](https://github.com/withastro/astro/tree/main/examples/env-vars) pour un aperçu des pratiques à appliquer.

2022-05-26 13:39 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +  Dans cet exemple, <code>PUBLIC_ANYBODY</code> ( disponible en tant que <ImportMetaEnv path=".PUBLIC_ANYBODY" /> ) sera disponible dans le code côté serveur ou client, alors que <code>SECRET_PASSWOR
Dans cet exemple, <code>PUBLIC_ANYBODY</code> ( disponible en tant que <ImportMetaEnv path=".PUBLIC_ANYBODY" /> ) sera disponible à la fois dans le code côté serveur et côté client, alors que <code>SECRET_PASSWORD</code> ( disponible en tant que <ImportMetaEnv path=".SECRET_PASSWORD" /> ) ne sera disponible que côté serveur.

2022-05-26 13:39 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +Astro inclus quelques variables d'environnement par défaut :
Astro inclut quelques variables d'environnement par défaut :

2022-05-26 13:39 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +    <ImportMetaEnv path=".MODE" /> (<code>development</code> | <code>production</code>): Représente le mode dans lequel le site tourne actuellement. Définis à <code>development</code> en utilisant la
<ImportMetaEnv path=".MODE" /> (<code>development</code> | <code>production</code>): Représente le mode sous lequel le site tourne actuellement. Initialisé comme à <code>development</code> en utilisant la commande <code>astro dev</code> et comme <code>production</code> en utilisant <code>astro build</code>.

2022-05-26 13:39 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +    <ImportMetaEnv path=".BASE_URL" /> (<code>string</code>): Représente l'URL de base sur laquelle votre site est déployé. Ceci est déterminé par <a href="/fr/reference/configuration-reference/#base
<ImportMetaEnv path=".BASE_URL" /> (<code>string</code>): Représente l'URL de base sous laquelle votre site est déployé.  Déterminé par <a href="/fr/reference/configuration-reference/#base">l'option <code>base</code> dans votre configuration</a>.

2022-05-26 13:39 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +Vous pouvez aussi attacher un mode (soit `production` ou `development`) au nom du fichier, comme `.env.production` ou `.env.development`, qui font que les variables d'environnement n'ont d'effet que
Vous pouvez aussi ajouter un mode (soit production ou development) au nom du fichier, comme .env.production ou .env.development, qui rendent ces variables d'environnement uniquement actives dans ce mode.

2022-05-26 13:39 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +> Parce que Vite remplace statiquement <ImportMetaEnv />, vous ne pouvez pas l'accéder avec des clés dynamiques comme <ImportMetaEnv path="[key]" />.
> Étant donné que Vite remplace statiquement <ImportMetaEnv />, vous ne pouvez pas y accéder avec des clés dynamiques comme <ImportMetaEnv path="[key]" />.

2022-05-26 13:39 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +Vous pouvez aussi définir d'autres variables d'environnement dans les fichiers `.env.[mode]`, mais vous voulez surement obtenir l'autocomplétion pour les variables d'environnement définies par l'util
Vous pouvez aussi définir d'autres variables d'environnement dans les fichiers `.env.[mode]`, mais vous voulez sûrement accéder à l'autocomplétion pour les variables d'environnement définies par l'utilisateur qui commencent par `PUBLIC_`.

2022-05-26 14:12 UTC, Chrissdroid commented on src/pages/fr/guides/environment-variables.md
> +Vous pouvez aussi attacher un mode (soit `production` ou `development`) au nom du fichier, comme `.env.production` ou `.env.development`, qui font que les variables d'environnement n'ont d'effet que
je sais pas trop quoi penser du "ajouter", c'est certes correct et ça marche mais je ne sais pas trop ce qui passerais le mieux, attacher me convient toujours mieux dans ce contexte, mais libre a toi de détailler ta pensée là dessus !

2022-05-26 15:10 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +    <ImportMetaEnv path=".MODE" /> (<code>development</code> | <code>production</code>): Représente le mode dans lequel le site tourne actuellement. Définis à <code>development</code> en utilisant la
Pas faux en effet :+1: `Défini comme <code>development</code>` serait plus adapté

2022-05-26 20:08 UTC, Chrissdroid commented on src/pages/fr/guides/environment-variables.md
> +Vous pouvez aussi attacher un mode (soit `production` ou `development`) au nom du fichier, comme `.env.production` ou `.env.development`, qui font que les variables d'environnement n'ont d'effet que
que pense tu de ça ?
`
Vous pouvez aussi ajouter/attacher un mode (soit `production` ou `development`) en suffixe au nom du fichier, comme `.env.production` ou `.env.development`, qui rendent ces variables d'environnement uniquement actives dans ce mode.
`

2022-05-27 09:50 UTC, naomiHauret commented on src/pages/fr/guides/environment-variables.md
> +Vous pouvez aussi attacher un mode (soit `production` ou `development`) au nom du fichier, comme `.env.production` ou `.env.development`, qui font que les variables d'environnement n'ont d'effet que
parfait comme ça !  :raised_hands:

2022-05-27 14:43 UTC, merged