i18n(fr) Update french translation with last PRs
withastro/docs pull request #6683
Opened 2024-01-28 09:33 UTC by McFlyPartages

#### Description (required)

Update french translation for multiple file outdated

2024-01-28 20:18 UTC, thomasbnt requested changes
Two suggestions about space in a note and a duplication of the word "plugin"

2024-01-28 20:18 UTC, thomasbnt commented on src/content/docs/fr/install/manual.mdx
> +:::tip[Vous préférez une méthode plus rapide pour commencer?]
```suggestion
:::tip[Vous préférez une méthode plus rapide pour commencer ?]
```

2024-01-28 20:18 UTC, thomasbnt commented on src/content/docs/fr/guides/integrations-guide/alpinejs.mdx
> +L'exemple suivant ajoute le plugin [Alpine's Collapse plugin](https://alpinejs.dev/plugins/collapse)  pour développer et réduire le texte d'un paragraphe.
```suggestion
L'exemple suivant ajoute le plugin [Alpine's Collapse](https://alpinejs.dev/plugins/collapse)  pour développer et réduire le texte d'un paragraphe.
```
ça évite la répétition du mot "plugin"

2024-01-28 22:06 UTC, McFlyPartages commented
> Two suggestions about space in a note and a duplication of the word "plugin"

Thanks it's ok now

2024-01-28 22:43 UTC, thomasbnt approved these changes
LGTM!

2024-01-29 18:02 UTC, VoxelMC approved these changes
Lots of work! Thank you very much @McFlyPartages :)

I added 3 suggestions to remove the `DontEditWarning` component, as the import is not needed in the translated versions. 

Awesome work!!!

`As a non-native speaker, I reviewed this PR using the Docs Translation Review Checklist and it LGTM!`

2024-01-29 18:34 UTC, McFlyPartages commented
> Lots of work! Thank you very much @McFlyPartages :)
> 
> I added 3 suggestions to remove the `DontEditWarning` component, as the import is not needed in the translated versions.
> 
> Awesome work!!!
> 
> `As a non-native speaker, I reviewed this PR using the Docs Translation Review Checklist and it LGTM!`

Thanks

2024-01-31 21:05 UTC, dreyfus92 approved these changes
LGTM, merci à tous 😁

2024-01-31 23:58 UTC, merged