[WIP] i18n(fr) Add French translation for `content.mdx` `talks.mdx` and update `recipes.mdx` and `nav.ts`
withastro/docs pull request #6684
Opened 2024-01-28 09:55 UTC by McFlyPartages

#### Description (required)

Add French translation for `content.mdx` `talks.mdx` and update `recipes.mdx` and `nav.ts`

2024-01-28 18:22 UTC, thomasbnt requested changes
One link to fix, and LGTM!

2024-01-28 18:22 UTC, thomasbnt commented on src/content/docs/fr/recipes.mdx
> +<ReadMore>Vous trouverez encore plus de recettes rédigées et mises à jour par la communauté dans nos [recettes et guides de la communauté]](/fr/community-resources/content/#recipes-and-guides)</ReadM
```suggestion
<ReadMore>Vous trouverez encore plus de recettes rédigées et mises à jour par la communauté dans nos [recettes et guides de la communauté](/fr/community-resources/content/#recipes-and-guides)</ReadMore>
```

2024-01-28 22:05 UTC, McFlyPartages commented
> One link to fix, and LGTM!

Thanks it's ok

2024-01-28 22:43 UTC, thomasbnt approved these changes
LGTM!

2024-01-28 22:44 UTC, thomasbnt commented
Owh, miss CI Links and good!

2024-01-29 14:59 UTC, thomasbnt approved these changes
LGTM!

2024-01-29 17:51 UTC, VoxelMC commented
Thanks!!

`As a non-native speaker, I reviewed this PR using the Docs Translation Review Checklist and it LGTM!`

2024-02-01 00:00 UTC, dreyfus92 approved these changes
Merci les gars, LGTM 😁

2024-02-01 00:11 UTC, merged