i18n(zh-cn): Create builderio.mdx
withastro/docs pull request #6715
Opened 2024-01-30 06:03 UTC by huyikai

#### Description (required)

Create builderio.mdx

#### Related issues & labels (optional)

- #6677

2024-01-30 06:37 UTC, liruifengv requested changes

2024-01-30 06:37 UTC, liruifengv commented on src/content/docs/zh-cn/guides/cms/builderio.mdx
> +## 先决条件
```suggestion
## 前期准备
```

这个可以考虑在后续PR中统一改成`前期准备`

2024-01-30 06:37 UTC, liruifengv commented on src/content/docs/zh-cn/guides/cms/builderio.mdx
> +如果你希望你的环境变量具有 IntelliSense 功能，你可以在 `src/` 目录下创建一个 `env.d.ts` 文件，并按照以下方式配置 `ImportMetaEnv`：
```suggestion
如果你希望你的环境变量具有类型智能提示，你可以在 `src/` 目录下创建一个 `env.d.ts` 文件，并按照以下方式配置 `ImportMetaEnv`：
```

2024-01-30 06:37 UTC, liruifengv commented on src/content/docs/zh-cn/guides/cms/builderio.mdx
> +// Builder's API requires this field but for this use case the url doesn't seem to matter - the API returns the same HTML
这里注释也需要翻译

2024-02-01 15:12 UTC, TheOtterlord reviewed
Thanks for the PR! I've suggested a quick update to one of the links to keep it in check with the main branch

2024-02-01 15:12 UTC, TheOtterlord commented on src/content/docs/zh-cn/guides/cms/builderio.mdx
> +创建页面 `src/pages/posts/[slug].astro`，该页面将为每篇文章[动态生成一个页面](/zh-cn/core-concepts/routing/#动态路由)。
On `main` we've updated this route to `/guides/`. You'll also need to update branch when you update this
```suggestion
创建页面 `src/pages/posts/[slug].astro`，该页面将为每篇文章[动态生成一个页面](/zh-cn/guides/routing/#动态路由)。
```

2024-02-02 02:46 UTC, liruifengv approved these changes

2024-02-02 15:44 UTC, TheOtterlord approved these changes

2024-02-02 16:05 UTC, merged