i18n(fr): Adding `install/manual.md` translation
withastro/docs pull request #676
Opened 2022-05-27 18:14 UTC by Chrissdroid

#### What kind of changes does this PR include?

- [x] New or updated content
- [x] Translated content

#### Description

- What does this PR change? Adds `/fr/install/manual.md` to the french translation.

2022-05-27 18:21 UTC, Chrissdroid commented
It's normal if the Check link is failing, it's referencing #675 which is not merge at the moment

2022-05-27 18:51 UTC, hippotastic commented
By the way, I just noticed that your branch still uses an old version of the link checker. If you want to use the latest version, you need to go to your fork's `main` branch on GitHub and click on "Fetch upstream" -> "Fetch and merge", and then navigate to your open branch(es) and repeat the same step. Then they will use the latest version.

2022-05-27 19:02 UTC, Chrissdroid commented
I know, my main branch is completely full of merge conflicts and i ended up by ignoring changes and just use the main branch as a save for my old translation and the reworked ones

2022-05-28 09:15 UTC, naomiHauret commented on src/pages/fr/install/manual.md
> +title: Install Astro manually
Installer Astro manuellement

2022-05-28 09:16 UTC, naomiHauret commented on src/pages/fr/install/manual.md
> +description: How to install Astro manually with NPM, PNPM, or Yarn.
Comment installer Astro manuellement avec NPM, PNPM ou Yarn

2022-05-28 09:26 UTC, naomiHauret requested changes

2022-05-28 09:26 UTC, naomiHauret commented on src/pages/fr/install/manual.md
> +- **Node.js** - versions `14.15.0`, `v16.0.0`, ou supérieur.
- **Node.js** - version `14.15.0`, `v16.0.0`, ou supérieure.

2022-05-28 09:26 UTC, naomiHauret commented on src/pages/fr/install/manual.md
> +Maintenant que vous êtes dans votre nouveau répertoire, créez votre fichier `package.json`. C'est avec ce fichier que vous pourez gérer les dépendances de votre projet, y compris Astro. Si vous n'ête
Maintenant que vous êtes dans votre nouveau répertoire, créez votre fichier `package.json`. C'est avec ce fichier que vous pourrez gérer les dépendances de votre projet, y compris Astro. Si vous n'êtes pas familier avec ce format de fichier, lancez la commande suivante pour en créer un.

2022-05-28 09:26 UTC, naomiHauret commented on src/pages/fr/install/manual.md
> +Ensuite, remplacez la section "scripts" de votre `package.json` par le code suivante :
Ensuite, remplacez la section "scripts" de votre `package.json` par les lignes suivantes :

2022-05-28 09:26 UTC, naomiHauret commented on src/pages/fr/install/manual.md
> +     Ce n'est que du HTML, mais avec quelques pailettes et un peu de magie
Ce n'est que du HTML, mais avec quelques paillettes et un peu de magie

2022-05-28 09:26 UTC, naomiHauret commented on src/pages/fr/install/manual.md
> +Si vous souhaitez inclure un [composant de Framework](/fr/core-concepts/framework-components/) comme React, Svelte, etc... ou utiliser d'autres outils comme Tailwind ou Partytown dans votre projet, C
Si vous souhaitez inclure un [composant de Framework](/fr/core-concepts/framework-components/) comme React, Svelte, etc... ou utiliser d'autres outils comme Tailwind ou Partytown dans votre projet, c'est le bon endroit pour les [importer et configurer ces intégrations](/fr/guides/integrations-guide/).

2022-05-28 12:21 UTC, Chrissdroid commented on src/pages/fr/install/manual.md
> +title: Install Astro manually
Oops, my bad, j'ai oublié la trad pour le titre et la desc 😆

2022-05-28 13:26 UTC, merged