[WIP] i18n(fr) Add french transltion for Backend file
withastro/docs pull request #6766
Opened 2024-02-02 12:58 UTC by McFlyPartages

#### Description (required)

Add french translation for `appwriteio.mdx` & `supabase.mdx` & `tigris.mdx`

2024-02-02 18:26 UTC, thomasbnt requested changes
Some translations in examples and one link breaked

2024-02-02 18:26 UTC, thomasbnt commented on src/content/docs/fr/guides/backend/supabase.mdx
> +```
```suggestion
<Layout title="S'enregistrer">
  <h1>S'enregistrer</h1>
  <p>Vous avez déjà un compte ? <a href="/signin">Connexion</a></p>
  <form action="/api/auth/register" method="post">
    <label for="email" for="email">Email</label>
    <input type="email" name="email" id="email" />
    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password" />
    <button type="submit">Se connecter</button>
  </form>
</Layout>
```
```

2024-02-02 18:26 UTC, thomasbnt commented on src/content/docs/fr/guides/backend/supabase.mdx
> +```
```suggestion
<Layout title="Connexion">
  <h1>Connexion</h1>
  <p>Nouveau par ici ? <a href="/register">Se créer un compte</a></p>
  <form action="/api/auth/signin" method="post">
    <label for="email" for="email">Email</label>
    <input type="email" name="email" id="email" />
    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password" />
    <button type="submit">Se connecter</button>
  </form>
</Layout>
```
```

2024-02-02 18:26 UTC, thomasbnt commented on src/content/docs/fr/guides/backend/supabase.mdx
> +L'exemple suivant utilise GitHub comme fournisseur OAuth. Pour connecter votre projet à GitHub, suivez les étapes de la [documentation Supabase] (https://supabase.com/docs/guides/auth/social-login/au
```suggestion
L'exemple suivant utilise GitHub comme fournisseur OAuth. Pour connecter votre projet à GitHub, suivez les étapes de la [documentation Supabase](https://supabase.com/docs/guides/auth/social-login/auth-github).
```

2024-02-02 18:26 UTC, thomasbnt commented on src/content/docs/fr/guides/backend/supabase.mdx
> +</Layout>
```suggestion
<Layout title="Connexion">
  <h1>Connexion</h1>
  <p>Nouveau par ici ? <a href="/register">Créer un compte</a></p>
  <form action="/api/auth/signin" method="post">
    <label for="email" for="email">Email</label>
    <input type="email" name="email" id="email" />
    <label for="password">Mot de passe</label>
    <input type="password" name="password" id="password" />
    <button type="submit">Login</button>
    <button value="github" name="provider" type="submit">Se connecter avec GitHub</button>
  </form>
</Layout>
```

2024-02-02 18:26 UTC, thomasbnt commented on src/content/docs/fr/guides/backend/supabase.mdx
> +    return new Response("Email and password are required", { status: 400 });
```suggestion
    return new Response("L'adresse e-mail et le mot de passe sont nécessaires", { status: 400 });
```

2024-02-02 20:03 UTC, McFlyPartages commented
> Some translations in examples and one link breaked

Merci c'est corrigé

2024-02-03 10:28 UTC, thomasbnt approved these changes
LGTM!

2024-02-04 18:16 UTC, dreyfus92 approved these changes
Merci à tous, LGTM ✅

2024-02-04 20:24 UTC, merged