[WIP] i18n(fr) Add all file in CMS folder
withastro/docs pull request #6767
Opened 2024-02-02 14:44 UTC by McFlyPartages

#### Description (required)

Add french translation for CMS files.

- [] 
- []
- []
- []
- []
- []
- []
- []

2024-02-03 19:26 UTC, thomasbnt requested changes

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/payload.mdx
> +// If using SSR, you will not need this function.
```suggestion
// La fonction getStaticPaths() est nécessaire pour les sites statiques sous Astro.
// Si vous utilisez le SSR, vous n'aurez pas besoin de cette fonction.
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/payload.mdx
> +const res = await fetch("http://localhost:5000/api/posts") // http://localhost:4321/api/posts by default
```suggestion
const res = await fetch("http://localhost:5000/api/posts") // http://localhost:4321/api/posts par défaut
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/payload.mdx
> +<HomeLayout title='Astro Blog'>
```suggestion
<HomeLayout title='Blog Astro'>
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/payload.mdx
> +	<h2>Blog posts list:</h2>
```suggestion
	<h2>Liste d'articles de blog :</h2>
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/payload.mdx
> +1. **Un projet Astro** - Si vous n'avez pas encore de projet Astro, notre [Guide d'installation]( /fr/install/auto/) vous permettra d'être opérationnel en un rien de temps.
```suggestion
1. **Un projet Astro** - Si vous n'avez pas encore de projet Astro, notre [Guide d'installation](/fr/install/auto/) vous permettra d'être opérationnel en un rien de temps.
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/keystatic.mdx
> +- Check out [the official Keystatic guide](https://keystatic.com/docs/installation-astro)
```suggestion
- Consultez [le guide officiel de Keystatic](https://keystatic.com/docs/installation-astro)
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/keystatic.mdx
> +Pour afficher le contenu d'un article individuel, vous pouvez importer et utiliser le composant `<Content />` pour [rendre votre contenu en HTML](/fr/guides/collections de contenus/#rendering-content
```suggestion
Pour afficher le contenu d'un article individuel, vous pouvez importer et utiliser le composant `<Content />` pour [rendre votre contenu en HTML](/fr/guides/content-collections/#rendre-le-contenu-en-html) :
```
https://docs.astro.build/fr/guides/content-collections/#rendre-le-contenu-en-html

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/keystatic.mdx
> +:::note[Vous utilisez déjà des collections de contenu ?]]
```suggestion
:::note[Vous utilisez déjà des collections de contenu ?]
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/cloudcannon.mdx
> +- CloudCannon annonce la prise en charge officielle d'Astro](https://astro.build/blog/astro-cloudcannon-support/)
```suggestion
- CloudCannon [annonce la prise en charge officielle d'Astro](https://astro.build/blog/astro-cloudcannon-support/)
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/caisy.mdx
> +- Consultez l'exemple Caisy + Astro sur[GitHub](https://github.com/caisy-io/caisy-example-astro) ou [StackBlitz](https://stackblitz.com/github/caisy-io/caisy-example-astro?file=src%2Fpages%2Fblog%2F%
```suggestion
- Consultez l'exemple Caisy + Astro sur [GitHub](https://github.com/caisy-io/caisy-example-astro) ou [StackBlitz](https://stackblitz.com/github/caisy-io/caisy-example-astro?file=src%2Fpages%2Fblog%2F%5B...slug%5D.astro)
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/caisy.mdx
> +- Interrogez vos documents en [mode brouillon](https://caisy.io/developer/docs/external-api/localization-and-preview#preview-mode-15) et dans plusieurs [locales](https://caisy.io/developer/docs/exter
```suggestion
- Interrogez vos documents en [mode brouillon](https://caisy.io/developer/docs/external-api/localization-and-preview#preview-mode-15) et dans plusieurs [langues](https://caisy.io/developer/docs/external-api/localization-and-preview#localization-in-a-graphql-query-8).
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/builderio.mdx
> +:::tip[Official resource]
```suggestion
:::tip[Ressource officielle]
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/builderio.mdx
> +Les variables `builderModel` et `builderAPIpublicKey` doivent être créées deux fois, puisque [`getStaticPaths()` s'exécute dans sa propre portée isolée](/fr/reference/api-reference/#getstaticpaths).:
```suggestion
Les variables `builderModel` et `builderAPIpublicKey` doivent être créées deux fois, puisque [`getStaticPaths()` s'exécute dans sa propre portée isolée](/fr/reference/api-reference/#getstaticpaths).
```

2024-02-03 19:26 UTC, thomasbnt commented on src/content/docs/fr/guides/cms/builderio.mdx
> +// Builder's API requires this field but for this use case the url doesn't seem to matter - the API returns the same HTML
```suggestion
// L'API de Builder requiert ce champ, mais pour ce cas d'utilisation, 
// l'URL ne semble pas avoir d'importance - l'API renvoie le même HTML.
```

2024-02-03 22:51 UTC, McFlyPartages commented
Megvi @thomasbnt  c'est corrigé

2024-02-03 23:40 UTC, thomasbnt approved these changes

2024-02-04 20:34 UTC, dreyfus92 approved these changes
Excellent travail @McFlyPartages, et bravo également pour la remarquable revue réalisée par @thomasbnt. LGTM ✅

2024-02-04 20:49 UTC, merged