i18n (ja):created `/guides/integrations-guide/react/` translation.
withastro/docs pull request #6858
Opened 2024-02-11 11:48 UTC by SnowDingo

#### Description 

This pull request is for updating Japanese translations of the React-integration page. All context of https://docs.astro.build/ja/guides/integrations-guide/react/ got translated into Japanese. 

- Suggested label: 
* Japanese translation

 **I am a first-time contributor to Astro Docs. Please let me know if I made any errors.**

* My Discord Username: Snowdingo#7972

2024-02-11 11:48 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-02-15 14:11 UTC, morinokami requested changes
翻訳ありがとうございました！細かい点も含め全体的にレビューしましたので、ご確認をお願いします🙏

2024-02-15 14:11 UTC, morinokami commented on src/content/docs/ja/guides/integrations-guide/react.mdx
> +この場合、実験的な`experimentalReactChildren`フラグを立ててAstroに`ReactNode`として必ず渡すよう伝えることが出来ます。このフラグを立てることで起きる犠牲はありますが、互換性を向上させるのに役立ちます。
slot は追加というよりは挿入のほうがニュアンスとして近いかと思います。また、「ライブラリ」が複数回出現してしまっているため、書き方を工夫したほうが良さそうです。一部の語が欠落しまっている点や、同じ段落になってしまっているのも直す必要があります:

```suggestion
異なる場所に異なる要素を挿入する機能などのために、1つ以上の子要素が渡される事を*想定*しているライブラリを使用している場合、この機能が邪魔になるかも知れません。 

この場合、実験的な`experimentalReactChildren`フラグにより、子要素をReactにvnodeとして必ず渡すようAstroに伝えられます。ランタイム上のコストはありますが、互換性の確保に役立ちます。
```

2024-02-15 14:11 UTC, morinokami commented on src/content/docs/ja/guides/integrations-guide/react.mdx
> +[astro-ui-frameworks]: /en/guides/framework-components/#using-framework-components
日本語版へのリンクとする必要がありそうです:

```suggestion
[astro-integration]: /ja/guides/integrations-guide/

[astro-ui-frameworks]: /ja/guides/framework-components/#フレームワークコンポーネントを利用
```

2024-02-16 05:17 UTC, SnowDingo commented on src/content/docs/ja/guides/integrations-guide/react.mdx
> + Astroには標準で、公式にサポートされているインテグレーションのセットアップを自動で完了させる事が出来る`astro add`コマンドがあります。最初の方法を使用したくないユーザーは代わりにインテグレーションを[手動でインストール](#手動でのインストール) する事も出来ます。
@morinokami さん、レビューありがとうございます。
こちらのレビューを承認するには下記の画像のようなボタンを押せば良いですか？
<img width="172" alt="スクリーンショット 2024-02-16 14 13 58" src="https://github.com/withastro/docs/assets/101443426/f51b63f0-a9dd-44bd-8613-1fcff65b4758">

2024-02-19 06:21 UTC, morinokami commented
@SnowDingo 反映いただきありがとうございます！が、hidden conversations のところに隠れてしまっている他のコメントがありますので、すみませんがそちらもご確認をお願いします🙏

2024-02-19 06:24 UTC, morinokami commented on src/content/docs/ja/guides/integrations-guide/react.mdx
> +この**[Astroインテグレーション][astro-integration]**は[React](https://react.dev/)コンポーネントのサーバーサイドレンダリング（SSR）とクライアントサイドのハイドレーションを可能にします。
あとすみません、https://github.com/withastro/docs/pull/6858#discussion_r1490891196 で取り込んでいただいた修正なのですが、https://docs-41sbq7oq7-astrodotbuild.vercel.app/ja/guides/integrations-guide/react/ にて表示を確認すると懸念していた　`**` が表示されてしまっているようなため、やはりスペースを付与したほうが良さそうです（ローカルで表示確認できておらずすみません）:

```suggestion
この **[Astroインテグレーション][astro-integration]** は[React](https://react.dev/)コンポーネントのサーバーサイドレンダリング（SSR）とクライアントサイドのハイドレーションを可能にします。
```

2024-02-19 13:04 UTC, SnowDingo commented on src/content/docs/ja/guides/integrations-guide/react.mdx
> +(React, Preact, Solid)などの複数のJSXフレームワークを同一のプロジェクトで使用している場合、 AstroがそれぞれのコンポーネントがどのJSXフレームワークを使用するか判断するために設定の記載が必要です。JSXフレームワークを一つのみ導入している場合は特別な設定を記述する必要はありません。
了解しました。
次翻訳するときはニュアンスなどにも気をつけて翻訳したいと思います。

2024-02-19 15:10 UTC, morinokami approved these changes
色々対応いただきありがとうございました！LGTM👍

2024-02-19 19:09 UTC, Yan-Thomas approved these changes
LGTM! Good work, and welcome to Team Docs @SnowDingo! 🙌

2024-02-19 19:10 UTC, merged