i18n(es): Update `aws.mdx`
withastro/docs pull request #6923
Opened 2024-02-16 19:21 UTC by Waxer59

#### Description (required)

`aws.mdx` https://github.com/withastro/docs/commit/7ab279e252e03f369419412601253540473cb185

2024-02-16 20:48 UTC, AitorMT requested changes

2024-02-16 20:48 UTC, AitorMT commented on src/content/docs/es/guides/deploy/aws.mdx
> +Cuando conectas CloudFront a un endpoint de sitio web estático de S3, dependes de las políticas del bucket de S3 para el control de acceso. Consulta la sección de [hospedaje de sitio web estático de
```suggestion
Cuando conectas CloudFront a un endpoint de sitio web estático de S3, dependes de las políticas del bucket de S3 para el control de acceso. Consulta la sección de [hospedaje de sitio web estático de S3](/es/guides/deploy/aws/#s3-static-website-hosting) para obtener más información sobre las políticas del bucket.
```

2024-02-16 20:55 UTC, Waxer59 commented
Gracias por la revisión 🤠!

2024-02-16 21:13 UTC, AitorMT requested changes

2024-02-16 21:13 UTC, AitorMT commented on src/content/docs/es/guides/deploy/aws.mdx
> +Cuando conectas CloudFront a un endpoint de sitio web estático de S3, dependes de las políticas del bucket de S3 para el control de acceso. Consulta la sección de [hospedaje de sitio web estático de
```suggestion
Cuando conectas CloudFront a un endpoint de sitio web estático de S3, dependes de las políticas del bucket de S3 para el control de acceso. Consulta la sección de [Alojando contenido estático en S3](/es/guides/deploy/aws/#alojando-contenido-estático-en-s3) para obtener más información sobre las políticas del bucket.
```

2024-02-16 21:30 UTC, Waxer59 commented
Gracias por la revisión 🤠!

2024-02-16 21:43 UTC, AitorMT approved these changes

2024-02-17 01:08 UTC, dreyfus92 approved these changes
Gracias muchachos, LGTM ✅

2024-02-17 01:20 UTC, merged