i18n(hi): add `astro-pages.mdx`
withastro/docs pull request #7003
Opened 2024-02-24 07:01 UTC by at-the-vr

#### Description (required)

- adds translation for [Pages](https://docs.astro.build/hi/basics/astro-pages/) in hindi language
- minor change in nav.ts to match with title of Pages

#### Related issues & labels (optional)

- Suggested label: i18n

2024-02-24 07:12 UTC, at-the-vr reviewed
reviewing my own PR 😓

2024-02-24 07:12 UTC, at-the-vr commented on src/content/docs/hi/basics/astro-pages.mdx
> +- [`.astro`](#astro-pages)
```suggestion
- [`.astro`](#astro-पेज)
```

2024-02-24 07:12 UTC, at-the-vr commented on src/content/docs/hi/basics/astro-pages.mdx
> +- [`.md`](#markdownmdx-pages)
```suggestion
- [`.md`](#markdownmdx-पेज)
```

2024-02-24 07:12 UTC, at-the-vr commented on src/content/docs/hi/basics/astro-pages.mdx
> +- [`.html`](#html-pages)
```suggestion
- [`.html`](#html-पेज)
```

2024-03-03 06:09 UTC, Mayank-Malviya requested changes
leaving some suggestions, overall it seems good 👍

2024-03-03 06:09 UTC, Mayank-Malviya commented on src/content/docs/hi/basics/astro-pages.mdx
> +- `.js`/`.ts` (as [endpoints](/hi/guides/endpoints/))
```suggestion
- `.js`/`.ts` ([endpoints](/hi/guides/endpoints/) की तरह)
```

2024-03-04 10:23 UTC, Mayank-Malviya approved these changes
LGTM

2024-03-05 17:17 UTC, yanthomasdev approved these changes
LGTM! Good work 🙌

2024-03-05 17:17 UTC, merged