i18n(fr): Adding `troubleshooting.md` translation
withastro/docs pull request #728
Opened 2022-06-06 15:15 UTC by Chrissdroid

#### What kind of changes does this PR include?

- [x] New or updated content
- [x] Translated content

#### Description

- What does this PR change? Adds the translation from `/en/guides/troubleshooting.md` to the french translation

2022-06-08 11:18 UTC, naomiHauret commented on src/pages/fr/guides/troubleshooting.md
> +**Statut**: Limitation actuelle; Un fix est en cours de développement.
> **Statut**: Limitation actuelle; Un fix est en cours de développement.

Un correctif est en cours de développement

2022-06-08 11:52 UTC, naomiHauret requested changes
A few spelling mistakes to fix

2022-06-08 11:52 UTC, naomiHauret commented on src/pages/fr/guides/troubleshooting.md
> +Dans les composants Astro, les balises `<script>` sont hoistées et chargées comme des [modules JavaScript](https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules) par défaut. Si vous avez
Dans les composants Astro, les balises `<script>` sont hoistées et chargées comme des [modules JavaScript](https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Modules) par défaut. Si vous avez ajouté la directive [`is:inline`](/fr/reference/directives-reference/#isinline) ou n'importe quel autre attribut dans votre balise, ce comportement par défaut est désactivé.

2022-06-08 11:52 UTC, naomiHauret commented on src/pages/fr/guides/troubleshooting.md
> +Ceci peut-être causé par l'accès à l'objet `window` ou `document` au moment de la génération du composant. Par défaut, Astro génère votre composant [isomorphiquement](https://fr.wikipedia.org/wiki/Is
Ceci peut-être causé par l'accès à l'objet `window` ou `document` au moment de la génération du composant. Par défaut, Astro génère votre composant [isomorphiquement](https://fr.wikipedia.org/wiki/Isomorphisme), c'est-à-dire qu'il est exécuté sur le serveur où l'environnement du navigateur n'est pas disponible. Vous pouvez désactiver cette étape de pré-génération en utilisant [la directive `client:only`](/fr/reference/directives-reference/#clientonly).

2022-06-08 11:52 UTC, naomiHauret commented on src/pages/fr/guides/troubleshooting.md
> +Note : Les [composants Astro](/fr/core-concepts/astro-components/) sont des composants HTML sans éxecution sur le navigateur. Mais, vous pouvez utiliser une balise `<script>` dans votre Template de c
Note : Les [composants Astro](/fr/core-concepts/astro-components/) sont des composants HTML sans exécution sur le navigateur. Mais, vous pouvez utiliser une balise `<script>` dans votre Template de composant Astro pour envoyer du JavaScript au navigateur qui s'exécute globalement sur toute la page.

2022-06-08 11:52 UTC, naomiHauret commented on src/pages/fr/guides/troubleshooting.md
> +    Jetez un oeil a mon article favoris, <a href={myFeaturedPost.url}>{myFeaturedPost.frontmatter.title}</a> !
Jetez un oeil à mon article favori, <a href={myFeaturedPost.url}>{myFeaturedPost.frontmatter.title}</a> !

2022-06-10 14:01 UTC, Chrissdroid commented
@naomiHauret Je fait juste un commentaire pour les prochaines review, tu as une feature dans GitHub qui te permet de faire des suggestions depuis les commentaires, c'est tellement plus pratique pour moi car je vois les changements et modifications apportés d'un coup d'oeil et même les rajouter d'un coup dans avoir a passer sur mon éditeur de code, des fois c'est compliqué de voir quels changements tu apporte nottament quand c'est juste des "S" manquants, j'espère que ça pourras t'aider ! 👍 

![image](https://user-images.githubusercontent.com/29927270/173082347-60ee3d05-7d5b-4d82-8658-3ee1c680b32d.png)

2022-06-13 11:08 UTC, naomiHauret commented on src/pages/fr/guides/troubleshooting.md
> +Cette erreur peut-être levée lorsque vous essayez d'importer ou de rendre un composant invalide, ou un qui ne fonctionne pas correctement. (Ce message d'erreur apparaît car le fonctionnement de l'imp
```suggestion
Cette erreur peut être levée lorsque vous essayez d'importer ou de rendre un composant invalide, ou un qui ne fonctionne pas correctement. (Ce message d'erreur apparaît car le fonctionnement de l'importation d'un composant UI se fait d'une façon spécifique à Astro.)
```

2022-06-15 16:45 UTC, merged