i18n(ja): Add astro-db.mdx
withastro/docs pull request #7392
Opened 2024-03-14 15:08 UTC by morinokami

#### Description (required)

- Add astro-db.mdx.

#### Related issues & labels (optional)

2024-03-16 08:35 UTC, shuuji3 requested changes
3箇所だけレビューコメントを書きました。全体的にとても読みやすい翻訳でした :+1:

2024-03-16 08:35 UTC, shuuji3 commented on src/content/docs/ja/guides/astro-db.mdx
> +プロジェクトが成長するにつれて、テーブルスキーマは変化します。ローカルで設定の変更を安全にテストした上で、デプロイ時にAstro
ここだけ翻訳が途中になっているようでした。

```suggestion
プロジェクトが成長するにつれて、テーブルスキーマは変化します。ローカルで設定の変更を安全にテストした上で、デプロイ時にStudioのデータベースにプッシュできます。
```

2024-03-16 08:35 UTC, shuuji3 commented on src/content/docs/ja/guides/astro-db.mdx
> +Astro DBは、Astro Studioプラットフォームに[接続](/ja/recipes/studio/)して、ホストされたデータベースをプロジェクトに迅速に追加できます。Astro Studioのウェブポータルから、新しくホストされたデータベースを表示、管理、デプロイすることができます。
リンクテキストは原文 (connect to the Astro Studio platform) と同じにした方がリンク先のページの内容がわかりやすいかと思います。

```suggestion
Astro DBは、[Astro Studioプラットフォームに接続](/ja/recipes/studio/)して、ホストされたデータベースをプロジェクトに迅速に追加できます。Astro Studioのウェブポータルから、新しくホストされたデータベースを表示、管理、デプロイすることができます。
```

2024-03-16 08:35 UTC, shuuji3 commented on src/content/docs/ja/guides/astro-db.mdx
> +フォームからのリクエストを処理してリモートにホストされたデータベースにデータを挿入する場合のように、ユーザー入力を受け付けるためには、Astroプロジェクトを[オンデマンドレンダリング](/ja/basics/rendering-modes/#オンデマンドレンダリング)に設定し、デプロイ環境向けの[SSRアダプター](/ja/guides/server-side-rendering/)を追加して
原文のリンクテキストは「add an SSR adapter」なので、それに合わせて「を追加」を含めてみました。ただ、リンク先はアダプターリストのセクションへのリンクなので、元のままでもいいかもしれません。

```suggestion
フォームからのリクエストを処理してリモートにホストされたデータベースにデータを挿入する場合のように、ユーザー入力を受け付けるためには、Astroプロジェクトを[オンデマンドレンダリング](/ja/basics/rendering-modes/#オンデマンドレンダリング)に設定し、デプロイ環境向けの[SSRアダプターを追加](/ja/guides/server-side-rendering/)してください。
```

2024-03-16 08:37 UTC, shuuji3 commented on src/content/docs/ja/guides/astro-db.mdx
> +フォームからのリクエストを処理してリモートにホストされたデータベースにデータを挿入する場合のように、ユーザー入力を受け付けるためには、Astroプロジェクトを[オンデマンドレンダリング](/ja/basics/rendering-modes/#オンデマンドレンダリング)に設定し、デプロイ環境向けの[SSRアダプター](/ja/guides/server-side-rendering/)を追加して
比較用スクリーンショットです↓

![Screenshot from 2024-03-16 17-36-44](https://github.com/withastro/docs/assets/1425259/f69833b4-34d6-47ac-ad84-13fac49bd6b1)
![Screenshot from 2024-03-16 17-37-08](https://github.com/withastro/docs/assets/1425259/d7b63846-924b-4d81-8275-325d43b91c10)

2024-03-16 08:38 UTC, shuuji3 commented on src/content/docs/ja/guides/astro-db.mdx
> +Astro DBは、Astro Studioプラットフォームに[接続](/ja/recipes/studio/)して、ホストされたデータベースをプロジェクトに迅速に追加できます。Astro Studioのウェブポータルから、新しくホストされたデータベースを表示、管理、デプロイすることができます。
比較用スクリーンショットです↓

![Screenshot from 2024-03-16 17-36-28](https://github.com/withastro/docs/assets/1425259/4dd75bac-ed60-4a56-807f-2af4920b9f35)
![Screenshot from 2024-03-16 17-36-13](https://github.com/withastro/docs/assets/1425259/20dc1949-bdeb-4634-a9f8-d76b41c0aa24)

2024-03-16 11:08 UTC, shuuji3 commented
このPR作成後に1コミット更新があったみたいです。

https://github.com/withastro/docs/commit/bc1e565fc842dd5ccd9a0f2d9c43813dfce8da21#diff-42f5c102ac1f5946b0d9a0b8d3118315173239effffcd6a946326a0a7774f530

2024-03-16 13:24 UTC, morinokami commented
@shuuji3 こちらのミスにしっかり気付いていただきありがたいです、サジェストいただいた内容はそのまま取り込ませていただきました🙏 また、新しい変更についても対応しましたので、ご確認をお願いします！

2024-03-16 13:35 UTC, shuuji3 approved these changes
対応ありがとうございます！ LGTMです！ 💯

2024-03-18 16:53 UTC, yanthomasdev approved these changes
LGTM! Amazing work 🙌

2024-03-18 16:53 UTC, merged