i18n(ja): Update middleware.mdx
withastro/docs pull request #7442
Opened 2024-03-17 12:08 UTC by morinokami

#### Description (required)

- Update middleware.mdx.
  - [diff](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/middleware.mdx?since=2024-03-06T22:41:43.000Z)
    - https://github.com/withastro/docs/pull/7250

#### Related issues & labels (optional)

- Closes #
- Suggested label:

2024-03-17 14:43 UTC, shuuji3 requested changes

2024-03-17 14:43 UTC, shuuji3 commented on src/content/docs/ja/guides/middleware.mdx
>  ミドルウェアはSSGとSSRのAstroプロジェクトの両方で利用可能です。
上のパラグラフ(L10)の最後に「This object is available even when this middleware runs at build time.」という1文が足りないようです。

あと、ここからL20の前までは削除できますね。

それ以外の翻訳は完璧です💯

2024-03-17 16:00 UTC, shuuji3 approved these changes
LGTM! 🚀

2024-03-18 13:12 UTC, yanthomasdev approved these changes
LGTM! Thanks 🙌

2024-03-18 13:12 UTC, merged