i18n(de): add 0-introduction to german blog tutorial
withastro/docs pull request #7467
Opened 2024-03-18 16:34 UTC by josefineschaefer

#### Description (required)

Added German translation of the introduction-0 tutorial.

#### Related issues & labels (optional)

- Suggested label: i18n

#### First-time contributor to Astro Docs? --> Yes 🙈 
Discord: josefine.sch

2024-03-18 16:34 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-03-25 18:54 UTC, Because789 reviewed
Hey Josefine, erstmal vielen Dank für deine Arbeit! Bin deinen PR mal durchgegangen, bitte nicht erschrecken, der Teufel liegt bekanntlich im Detail 😄 Wäre wohl auch nicht schlecht, wenn du den PR zu "i18n(de): add 0-introduction to german blog tutorial" umbenennen könntest.

2024-03-25 18:54 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +(Diese Daten werden nur in dem lokalen Speicher deines Browsers gespeichert und nirgendwo sonst. Keine Daten werden von Astro verschickt oder gespeichtert.)
"werden nur _im_ lokalen Speicher"

"gespeichtert" --> "gespeichert"! Da der Satz so inhaltlich nicht wirklich dem Original entspricht, würde ich umformulieren, vielleicht: "Es werden keine Daten von Astro gesammelt."

2024-03-25 18:54 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +Du kannst die Lektionen von [Einheit 1](/en/tutorial/1-setup/) nutzen, um sicherzugehen, dass du die Entwicklungstools und Accounts hast, die du brauchst, um das Tutorial abzuschließen. Die Einheit b
"auf Netlify bereitzustellen" --> "auf Netlify zu veröffentlichen" (siehe Glossar)

2024-03-25 18:54 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +Wenn du [ein neues, leeres Astro-Projekt erstellst](/en/install/auto/) und mit dem Setup bereits vertraut bist, kannst du diese Einheit aber überspringen und direkt zu [Einheit 2](/en/tutorial/2-page
"mit dem Setup" --> "mit deinem Setup"

2024-03-25 18:54 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +Unser [Astro Discord Server](https://astro.build/chat) ist der beste Ort dafür.
"Astro-Discord-Server"
"beste Ort dafür _!_"

2024-03-25 18:54 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +In unserem Support Forum Channel kannst du Fragen stellen,  "Hallo" sagen oder mit uns in `#general` oder `#off-topic` chatten.
Das sollte man etwas umformulieren, vielleicht: 

"In unserem Support-Kanal kannst du Fragen stellen, oder du kannst in `#general` oder `#off-topic` "Hallo" sagen und chatten."

2024-03-25 18:54 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +Dieses Tutorial ist ein Projekt unseres Docs Teams. Du kannst uns auf Discord im `#docs` Channel finden oder direkt ein Issue im [Docs Repository](https://github.com/withastro/docs/issues) erstellen.
"Docs-Teams"
"`#docs`-Kanal"
"Docs-Repository"

2024-03-25 18:54 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +- [ ] Ich bin bereit loszulegen
"loszulegen _!_"

2024-03-25 19:08 UTC, Because789 commented
Ist mir erst jetzt aufgefallen, aber die Links müssten wohl auch alle noch von `/en/...` auf `/de/...` geändert werden.

2024-03-26 09:44 UTC, josefineschaefer commented
Vielen Dank @Because789 für das ausführliche Feedback - super hilfreich für die nächsten Übersetzungen 🙏 Hoffe ich habe beim Anpassen nichts übersehen.

2024-03-26 10:38 UTC, Because789 requested changes
Aber gerne doch @josefineschaefer! Habe noch drei kleine Dinge entdeckt, ansonsten LGTM!

2024-03-26 10:38 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +Du kannst auch einige Punkte der Checkliste erst mal nicht abhaken lassen, als Erinnerung, falls du später zurückkehren möchtest.
```suggestion
Du kannst auch einige Punkte der Checkliste erst mal nicht abhaken, als Erinnerung, falls du später zurückkehren möchtest. 
```

2024-03-26 10:38 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +Du kannst die Lektionen von [Einheit 1](/de/tutorial/1-setup/) nutzen, um sicherzugehen, dass du die Entwicklungstools und Accounts hast, die du brauchst, um das Tutorial abzuschließen. Die Einheit b
```suggestion
Du kannst die Lektionen von [Einheit 1](/de/tutorial/1-setup/) nutzen, um sicherzugehen, dass du die Entwicklungstools und Accounts hast, die du brauchst, um das Tutorial abzuschließen. Die Einheit begleitet dich dabei, dein erstes Astro-Projekt zu erstellen, auf GitHub zu speichern und auf Netlify zu veröffentlichen. 
```

2024-03-26 10:38 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +Du kannst die Lektionen von [Einheit 1](/de/tutorial/1-setup/) nutzen, um sicherzugehen, dass du die Entwicklungstools und Accounts hast, die du brauchst, um das Tutorial abzuschließen. Die Einheit b
Mich stört "bereitstellen" nicht, einfach weil gemäss Glossar "to deploy" mit "veröffentlichen" übersetzt werden soll.

2024-03-26 10:38 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +Dieses Tutorial ist ein Projekt unseres Docs-Teams. Du kannst uns auf Discord im `#docs`-Channel finden oder direkt ein Issue im [Docs-Repository](https://github.com/withastro/docs/issues) erstellen.
```suggestion
Dieses Tutorial ist ein Projekt unseres Docs-Teams. Du kannst uns auf Discord im `#docs`-Kanal finden oder direkt ein Issue im [Docs-Repository](https://github.com/withastro/docs/issues) erstellen. 
```

2024-03-26 10:38 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/1.mdx
> +Dieses Tutorial ist ein Projekt unseres Docs-Teams. Du kannst uns auf Discord im `#docs`-Channel finden oder direkt ein Issue im [Docs-Repository](https://github.com/withastro/docs/issues) erstellen.
Ich plane einen PR für ein Update des de-Glossars, Discord channel nehm ich da zur Diskussion drauf. Hier habe ich es geändert, weil oben schon "Kanal" steht.

2024-03-26 12:14 UTC, josefineschaefer commented
Perfekt, danke! Doch noch ein paar Sachen durchgerutscht 🙈

2024-03-26 12:23 UTC, Because789 commented
Super, habe nichts mehr einzuwenden, LGTM!

2024-03-27 23:53 UTC, dreyfus92 approved these changes
Thank you @Because789 for reviewing and  @josefineschaefer for your amazing contribution welcome to `astro-docs` 😁. LGTM ✅

2024-03-28 00:08 UTC, merged

2024-03-31 08:08 UTC, nicdun commented
sieht gut aus, LGTM 👍🏻

2024-03-31 08:09 UTC, nicdun reviewed
sieht gut aus, LGTM👍🏻