i18n(pt-BR): Update `troubleshooting.md` page based on #749 changes
withastro/docs pull request #753
Opened 2022-06-09 20:59 UTC by Yan-Thomas

#### What kind of changes does this PR include?

- [ ] Minor content fixes (broken links, typos, etc.)
- [ ] New or updated content
- [x] Translated content
- [ ] Changes to the docs site code
- [ ] Something else!

#### Description

Updated PT-BR `troubleshooting.md` page based on #749 changes.

2022-06-09 23:55 UTC, victor0x16 requested changes
A small change!

2022-06-09 23:55 UTC, victor0x16 commented on src/pages/pt-BR/guides/troubleshooting.md
> +Yarn 2+, também conhecido como Berry, utiliza uma técnica chamada [Plug'n'Play (PnP)](https://yarnpkg.com/features/pnp) para armazenar e gerenciar módulos Node e que pode [causar problemas](https://g
```suggestion
Yarn 2+, também conhecido como Berry, utiliza uma técnica chamada [Plug'n'Play (PnP)](https://yarnpkg.com/features/pnp) para armazenar e gerenciar módulos Node e que pode [causar problemas](https://github.com/withastro/astro/issues/3450) durante a inicialização de um novo projeto Astro utilizando `create-astro` ou enquanto você trabalha com Astro. Uma solução para este problema é definir a [propriedade `nodeLinker`](https://yarnpkg.com/configuration/yarnrc#nodeLinker) em `yarnrc.yml` para `node-modules`:
```

2022-06-10 08:45 UTC, Yan-Thomas commented
Thanks @victor0x16!!

2022-06-10 10:22 UTC, delucis approved these changes

2022-06-10 10:22 UTC, merged