i18n(zh-TW): update glossaries in translation guide
withastro/docs pull request #7559
Opened 2024-03-23 07:59 UTC by mingjunlu

#### Description

- Updates glossaries in Traditional Chinese translation guide

#### Related issues & labels

- Related PR: #4696
- Suggested label: i18n

2024-03-23 08:26 UTC, mingjunlu commented
很感謝 @NightFeather0615 先前用心整理了翻譯指南 🙏

我在閱讀 Astro Docs 正體中文翻譯以及實際投身翻譯的過程中，發現指南中有些詞彙跟網路上常用的詞還有我個人經驗存有些差異，因此參考了臺灣自由開源軟體在地化社群的[詞彙對照表](https://hackmd.io/@l10n-tw/glossaries)（感謝 Discord 社群的 altair7390 網友提供）和[大陸台灣計算機術語對照表](https://zh.wikibooks.org/zh-tw/大陸台灣計算機術語對照表)，對翻譯指南的術語和用詞作出一些調整。

另外我把 `1.2 中文用詞` 一部分內容刪掉了，主要考量是：

- 沒出現在《重編國語辭典修訂本》詞彙未必代表它是錯的（特別是軟體相關用語）
- 希望讓譯者在用字遣詞上有更大的發揮空間

2024-03-23 08:32 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> -|開發者           |而不使用「開發人員」  |
我認為兩者可以交換使用，並不會影響閱讀～

2024-03-23 08:38 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> -|甚麼             |「什麼」為異體字     |
老實說我只有印象在字典和學校第一次學到這個詞的時候看過「甚麼」，其他時候都是使用「什麼」😅

考慮到 Astro Docs 的主要受眾不是教育市場，我想使用臺灣人熟悉的「什麼」應該無傷大雅 🤔

2024-03-23 08:45 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> -|優化             |並無「最佳化」一詞   |
「移除」和「最佳化」雖然都沒收錄在《重編國語辭典修訂本》，但其實很常見（連政府都在用）：

- [`"移除" inurl:gov.tw`](https://www.google.com/search?q=%22%E7%A7%BB%E9%99%A4%22+inurl%3Agov.tw)
- [`"最佳化" inurl:gov.tw`](https://www.google.com/search?q=%22%E6%9C%80%E4%BD%B3%E5%8C%96%22+inurl%3Agov.tw)

2024-03-23 08:55 UTC, NightFeather0615 commented
感謝更新，當初沒什麼人在討論，所以就直接 merge 了，我也認為這套標準需要打磨。

大致看來沒有問題，但有幾點我想提出異議的，主要是以下這幾個用詞對照：
* `import`: 是否保留「引入」和「導入」，考量 MDN 文檔中是採用這兩個詞
* `package`: 是否保留「套件」，就目前線上資源看來「軟體包」似乎並不常被採用
* `docs`: 參考 MDN 使用「說明文件」和「技術文件」可能是個更好的選擇，避免與英文的「file」混淆
* `build`: 該譯為「建構/構建」還是「建置」

2024-03-23 08:57 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> -|甚麼             |「什麼」為異體字     |
這點主要是考量到同一篇文章中最好統一使用一種，不過確實沒有需要特別規定

2024-03-23 11:43 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> -|優化             |並無「最佳化」一詞   |
的確很常見，當初的想法是以官方辭典為基礎盡量統一用詞，現在看來有些矯枉過正了

2024-03-23 11:47 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> -|開發者           |而不使用「開發人員」  |
這點同「移除」與「最佳化」，那時的出發點是同個頁面內盡可能統一用詞，如果對這點有共識的話可以不用強制約束

2024-03-24 06:21 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> -|開發者           |而不使用「開發人員」  |
同意在同個頁面盡量使用一致的詞彙 🙌

2024-03-24 06:21 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> -|甚麼             |「什麼」為異體字     |
了解，感謝分享～

2024-03-24 07:05 UTC, mingjunlu commented
> 感謝更新，當初沒什麼人在討論，所以就直接 merge 了，我也認為這套標準需要打磨。
> 
> 大致看下來我沒有問題，但有幾點想提出異議，主要是以下這幾個用詞對照：
> 
> * `import`: 是否保留「引入」和「導入」，考量 MDN 文檔中採用這兩個詞
> * `package`: 是否保留「套件」，就目前線上資源看來「軟體包」似乎並不常被採用
> * `docs`: 參考 MDN 使用「說明文件」和「技術文件」可能是個更好的選擇，避免與英文的「file」混淆
> * `build`: 該譯為「建構/構建」還是「建置」，或是將兩者都列入規範

感謝回覆，以下是我的淺見：

- `import`：「引入」確實常見，我傾向只保留「引入」跟「匯入」。「導入」較不符合臺灣語境（詳見那兩份對照表）
- `package`：考慮到習慣，我也贊成保留「套件」
- `docs`：docs 應該算是 documentation 的縮寫或簡稱（至少大部分情況下兩者可交換使用），因此我提議將 docs 譯作「文件」，documentation 譯作「說明文件」或「技術文件」。至於 `file` 通常會翻成「檔案」，我想混淆的機會應該不大
- `build`：臺灣常用「建構」和「建置」，我的觀察是「構建」相對少見，因此傾向只將「建構」和「建置」列入

2024-03-24 17:57 UTC, NightFeather0615 commented
LGTM
其他部份我沒有問題，這些地方改完應該就能 merge 了，看看還有沒有人要 review 吧

2024-03-25 10:26 UTC, toto6038 commented
關於 hydrate/hydration 譯作「水合」，有種說不出的奇怪感😅不過若要用，可能中英並陳會更好。

另外關於 render 譯作「渲染」，我則持反對意見。在電腦圖形、3D繪圖的語境中，render 有譯為「算圖」的例子（Apple 慣例）；在網頁的語境中，server side rendering 本意為由伺服器端計算並產生 HTML。雖這兩個情境在簡體中文與英文都採同一詞彙，但基於 render 在正體中文已有針對電腦圖形領域的翻譯，將網頁領域的用詞分開處理應較妥適，此處若用「產生」應該沒什麼大問題。如果大家有更好的建議也很好～

cc @pan93412

2024-03-25 16:37 UTC, mingjunlu commented
> 關於 hydrate/hydration 譯作「水合」，有種說不出的奇怪感😅不過若要用，可能中英並陳會更好。

同感⋯⋯說不定這兩個詞保持使用原文會更好 💡

> 另外關於 render 譯作「渲染」，我則持反對意見。在電腦圖形、3D繪圖的語境中，render 有譯為「算圖」的例子（Apple 慣例）；在網頁的語境中，server side rendering 本意為由伺服器端計算並產生 HTML。雖這兩個情境在簡體中文與英文都採同一詞彙，但基於 render 在正體中文已有針對電腦圖形領域的翻譯，將網頁領域的用詞分開處理應較妥適，此處若用「產生」應該沒什麼大問題。如果大家有更好的建議也很好～

我對「渲染」沒有太大意見，可能看習慣了 😂

覺得「產生」很適合放在內文的句子意譯，但單獨放在標題時好像就沒那麼適合（總感覺「產生」後面要接個受詞）。印象中還有看過「算繪」，不過有點擔心讀者看不懂。如果翻成「繪製」呢？🤔

2024-03-25 18:26 UTC, NightFeather0615 commented
關於「水合」，請參見 [Discord](https://discord.com/channels/830184174198718474/973149689610371093/1145718715401388162)，當初是以這串討論為標準制定的，考量到繁體中文網上沒有共識，加上簡體中文版已經大量採用此用語，我覺得在兩個團隊沒有共識的情況下貿然更動是不合適的。

考量到 SSG（靜態網頁生成）和 SSR（伺服器端渲染）並非同一種技術，我個人偏好保留渲染，尤其原文的 render 也是後來才衍生出和前端有關的含意的，參考：
* Next.js: [SSG](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-static-props), [SSR](https://nextjs.org/docs/pages/building-your-application/data-fetching/get-server-side-props)
* Stack Overflow: [Static Site Generation (SSG) vs. Server-Side Rendering vs. Client-Side Rendering](https://stackoverflow.com/questions/75457090/static-site-generation-ssg-vs-server-side-rendering-vs-client-side-rendering)

2024-03-26 19:25 UTC, NightFeather0615 commented
SSR 的處境比較尷尬，繁體中文資源大多是按照簡體的「渲染」去翻譯的，雖然不甚準確，不過似乎已經成為一種共識了，如 [AWS](https://docs.aws.amazon.com/zh_tw/amplify/latest/userguide/What-is-server-side-rendering.html) 的文檔也是採用渲染一詞，加上簡體中文語境下該詞也有在電腦圖形領域中的解釋，但看來並不會造成混淆，個人認為這部分貿然更動是否會影響閱讀時的流暢度和理解難度是有待商榷的。

目前我的觀點是暫時保留「渲染」會比較合適，但要是大多數人有共識，修正成「繪製/算繪」也是個好決定。

2024-03-29 20:13 UTC, toto6038 requested changes
由於 GitHub code review 僅能對 diff 中有變更內容的部分留言，因此將建議統一整理在此，連結均有標記對應行號。

- document 文檔 -> 文件
	- R3 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R3
	- R7 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R7
	- R148 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R148
	- R153 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R153
- comment 註釋 -> 註解
	- R67 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R67
	- R111 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R111
- render 渲染 -> 算繪
	- R55 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R55
	- R87 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R87
	- R131 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R131
- code 代碼 -> 程式碼
	- R52 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R52
	- R90 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R90 （代碼內聯 -> 行內程式碼）
	- R103-R104 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R103-R104
	- R110-R112 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R110-R112
- call 調用 -> 呼叫
	- R93 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R93
- 建議將「創建 Issue」改成「發起 Issue」會更自然
	- R154 https://github.com/withastro/docs/pull/7559/files?diff=unified#diff-361f9d4cfad758967ad9404701167e9c9242f63bf0227b8f02bcf160297a1d01R154 


更：在連結前補充行號

2024-03-31 16:05 UTC, mingjunlu commented
感謝整理，已更新～

2024-03-31 21:20 UTC, NightFeather0615 requested changes
有些地方可能需要再更動，排版的部分改的有點多，段落被壓縮了，對閱讀節奏的影響挺嚴重的，空間足夠應該沒有必要更改目前的排版

2024-03-31 21:20 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +- 考慮到 `／` 在不同字體下算繪差異較大，分隔號應為前後包含空格的 `/`，如：`你好 / 世界`
字體渲染應該是圖形引擎中的術語，用算繪取代是否不太合適？

2024-03-31 21:20 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +呼叫 `window` 的 `alert()` 函式
「調用」若沒有爭議的話應該不需特別更改為「呼叫」，個人認為「調用」比較適合這個語境

2024-03-31 21:20 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +如果你對本指南有任何想法或勘誤建議，歡迎發起 issue 或是加入 [Discord 社群](https://astro.build/chat)中的 `#i18n-crew-zh` 頻道參與討論！
Issue 是否該保留大寫？

2024-03-31 21:20 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +本指南**並非**硬性規定，而是代表中文文件翻譯團隊共識的建議。
移除空格會破壞 Markdown 排版，無特殊理由不應更動

2024-03-31 21:20 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +可在句中加入如「然而」、「並且」或「即使……也……」等連接詞來使句子更加連貫。
移除空格會破壞 Markdown 排版，無特殊理由不應更動

2024-03-31 21:20 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +本指南旨在整理一份統一的格式及風格指南，使文件讀起來更流暢並易於理解。
移除空格會破壞 Markdown 排版，無特殊理由不應更動

2024-03-31 21:20 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +感謝你有興趣對 Astro 文件翻譯做出貢獻！
移除空格會破壞 Markdown 排版，無特殊理由不應更動

2024-03-31 21:20 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +像是「to match the order of the items」這樣的短語可以在**保證語意不變**的情況下簡化。
移除空格會破壞 Markdown 排版，無特殊理由不應更動

2024-04-01 02:40 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +像是「to match the order of the items」這樣的短語可以在**保證語意不變**的情況下簡化。
不好意思誤刪了，感謝提醒。已還原：https://github.com/withastro/docs/pull/7559/commits/e7f88026dbc7a3cd3f626252f08f8b02c5d3ead1

2024-04-01 02:40 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +感謝你有興趣對 Astro 文件翻譯做出貢獻！
不好意思誤刪了，感謝提醒。已還原：https://github.com/withastro/docs/pull/7559/commits/e7f88026dbc7a3cd3f626252f08f8b02c5d3ead1

2024-04-01 02:40 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +本指南旨在整理一份統一的格式及風格指南，使文件讀起來更流暢並易於理解。
不好意思誤刪了，感謝提醒。已還原：https://github.com/withastro/docs/pull/7559/commits/e7f88026dbc7a3cd3f626252f08f8b02c5d3ead1

2024-04-01 02:40 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +可在句中加入如「然而」、「並且」或「即使……也……」等連接詞來使句子更加連貫。
不好意思誤刪了，感謝提醒。已還原：https://github.com/withastro/docs/pull/7559/commits/e7f88026dbc7a3cd3f626252f08f8b02c5d3ead1

2024-04-01 02:40 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +本指南**並非**硬性規定，而是代表中文文件翻譯團隊共識的建議。
不好意思誤刪了，感謝提醒。已還原：https://github.com/withastro/docs/pull/7559/commits/e7f88026dbc7a3cd3f626252f08f8b02c5d3ead1

2024-04-01 02:50 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +如果你對本指南有任何想法或勘誤建議，歡迎發起 issue 或是加入 [Discord 社群](https://astro.build/chat)中的 `#i18n-crew-zh` 頻道參與討論！
Issue 不是專有名詞，想問大寫的原因是什麼呀？🤔

- Astro Docs 除了在句首和標題之外，issue 都用小寫。例外是提及 GitHub Issues 時（此時是專有名詞故首字大寫）
- [GitHub Issues 的說明文件](https://docs.github.com/en/issues/tracking-your-work-with-issues/about-issues)狀況也是如此

2024-04-01 02:54 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +呼叫 `window` 的 `alert()` 函式
「調用」是簡中用法喔，臺灣用「呼叫」，詳見：

- https://hackmd.io/@l10n-tw/glossaries#:~:text=Call-,%E5%91%BC%E5%8F%AB,-%E8%B0%83%E7%94%A8
- https://zh.wikibooks.org/zh-tw/%E5%A4%A7%E9%99%B8%E5%8F%B0%E7%81%A3%E8%A8%88%E7%AE%97%E6%A9%9F%E8%A1%93%E8%AA%9E%E5%B0%8D%E7%85%A7%E8%A1%A8#:~:text=Call-,%E5%91%BC%E5%8F%AB,-%E8%AA%BF%E7%94%A8

2024-04-01 03:06 UTC, toto6038 commented on src/i18n/zh-tw/README.md
> +呼叫 `window` 的 `alert()` 函式
我想從「調用」對應的英文來討論可能會更精準。如果是 call，則依循[維基百科資訊科技公共轉換組](https://zh.wikipedia.org/wiki/Module:CGroup/IT#C)使用「呼叫」；如果是 use，用「使用」應該較無爭議；如果是 invoke，正體中文則翻為「叫用」。另一方面，教育部字典中載明「調用」意為調配使用，在此可能不夠精準，且有與簡體中文術語混淆的疑慮。

Ref:
根據[百度百科](https://baike.baidu.com/item/%E8%B0%83%E7%94%A8/3351318)，簡體中文電腦程式術語中將 call 翻為「调用」

2024-04-01 03:09 UTC, toto6038 commented on src/i18n/zh-tw/README.md
> +- 考慮到 `／` 在不同字體下算繪差異較大，分隔號應為前後包含空格的 `/`，如：`你好 / 世界`
```suggestion
- 考慮到 `／` 在不同字體下算繪結果差異較大，分隔號應為前後包含空格的 `/`，如：`你好 / 世界`
```
這樣可能好一點

2024-04-01 05:28 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +呼叫 `window` 的 `alert()` 函式
調配使用我是認為沒問題，若要統一為「呼叫」也無妨，建議加入規範內

2024-04-01 05:32 UTC, NightFeather0615 commented on src/i18n/zh-tw/README.md
> +如果你對本指南有任何想法或勘誤建議，歡迎發起 issue 或是加入 [Discord 社群](https://astro.build/chat)中的 `#i18n-crew-zh` 頻道參與討論！
大寫是我個人將 GitHub 上的「Issue」視為專有名詞，不如統一翻譯為「議題 / 問題」？

2024-04-01 05:36 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +如果你對本指南有任何想法或勘誤建議，歡迎發起 issue 或是加入 [Discord 社群](https://astro.build/chat)中的 `#i18n-crew-zh` 頻道參與討論！
了解。我把它改回大寫好了，怕讀的人沒意會到指的是 GitHub Issue

2024-04-01 05:44 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +如果你對本指南有任何想法或勘誤建議，歡迎發起 issue 或是加入 [Discord 社群](https://astro.build/chat)中的 `#i18n-crew-zh` 頻道參與討論！
已還原：https://github.com/withastro/docs/pull/7559/commits/98b037d5643f8a78cbe1a8036dda2b93d0573f7c

2024-04-01 05:49 UTC, mingjunlu commented on src/i18n/zh-tw/README.md
> +呼叫 `window` 的 `alert()` 函式
已加入：https://github.com/withastro/docs/pull/7559/commits/9cb7b4123ad1457c0ee2076570a819c8e82a27de

2024-04-03 17:50 UTC, pan93412 approved these changes

2024-04-03 19:23 UTC, yanthomasdev approved these changes
LGTM! Nice work everyone 🙌

2024-04-03 19:24 UTC, merged