i18n(de): add integrations-guide/tailwind
withastro/docs pull request #7561
Opened 2024-03-24 14:33 UTC by DerTimonius

#### Description (required)

This PR adds the missing german translation for the tailwind integration guide. The page is rendering as it should, so no issues there 🙂 

For reviewers: I was a bit unsure if `Utility-Klassen` is the best translation, but I could not find a better one. I'm open for suggestions!

2024-03-25 03:24 UTC, mingjunlu reviewed
Nice work! Found a broken link and some typos here:

2024-03-25 03:24 UTC, mingjunlu commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Du kannst jetzt [deine eigene `base.css` Datei als lokales Stylesheet importieren](/en/guides/styling/#import-a-local-stylesheet).
```suggestion
Du kannst jetzt [deine eigene `base.css` Datei als lokales Stylesheet importieren](/de/guides/styling/#importiere-ein-lokales-stylesheet).
```

2024-03-25 03:24 UTC, mingjunlu commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Für weitere Hilfe, komme zu uns in den `#support` Kanal auf [Discord]((https://astro.build/chat)). Unsere freundlichen Support Squad Mitglieder helfen dir gerne!
```suggestion
Für weitere Hilfe, komme zu uns in den `#support` Kanal auf [Discord](https://astro.build/chat). Unsere freundlichen Support Squad Mitglieder helfen dir gerne!
```

2024-03-25 15:32 UTC, DerTimonius commented
@mingjunlu Thanks, should have checked every link, totally missed those!

2024-03-25 21:01 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Um dieses Standardverhalten auszuschalten, setze `applyBaseStyles` auf `false`. Dies kann hilfreich sein, wenn du deine eigene `base.css` Datei definieren musst (zum Beispiel um die [`@layer` Direkti
```suggestion
Um dieses Standardverhalten zu deaktivieren, setze `applyBaseStyles` auf `false`. Dies kann hilfreich sein, wenn du deine eigene `base.css`-Datei definieren musst (zum Beispiel um die [`@layer`-Direktive](https://tailwindcss.com/docs/functions-and-directives#layer) zu verwenden). Nützlich ist das auch, wenn du nicht willst, dass `base.css` in jeder Seite deines Projekts importiert wird.
```

2024-03-25 21:05 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Du kannst jetzt [deine eigene `base.css` Datei als lokales Stylesheet importieren](/de/guides/styling/#importiere-ein-lokales-stylesheet).
```suggestion
Du kannst jetzt [deine eigene `base.css`-Datei als lokales Stylesheet importieren](/de/guides/styling/#importiere-ein-lokales-stylesheet).
```

2024-03-25 21:07 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Setze es auf `true` um das [`tailwindcss/nesting` PostCSS plugin](https://tailwindcss.com/docs/using-with-preprocessors#nesting) zu verwenden. So kannst du auch verschachtelte CSS Deklarationen neben
```suggestion
Setze auf `true`, um das [`tailwindcss/nesting`-PostCSS-Plugin](https://tailwindcss.com/docs/using-with-preprocessors#nesting) zu verwenden. So kannst du auch verschachtelte CSS-Deklarationen neben dem Tailwind-Syntax verwenden. Diese Option ist standardmäßig auf `false` gesetzt.
```

2024-03-25 21:09 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +* Astros Homepage verwendet Tailwind. Schau dir die verwendete [Tailwind Konfigurationsdatei](https://github.com/withastro/astro.build/blob/main/tailwind.config.ts) oder eine [Beispielkomponente](htt
```suggestion
* Astros Homepage verwendet Tailwind. Schau dir die verwendete [Tailwind-Konfigurationsdatei](https://github.com/withastro/astro.build/blob/main/tailwind.config.ts) oder eine [Beispielkomponente](https://github.com/withastro/astro.build/blob/main/src/components/Checkbox.astro) an
```

2024-03-25 21:11 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +* Für mehr Beispiele, [suche nach Astro Tailwind Projekten auf GitHub](https://github.com/search?q=%22%40astrojs%2Ftailwind%22%3A+path%3A%2Fpackage.json\&type=code)!
```suggestion
* Für mehr Beispiele, [suche nach Astro-Tailwind-Projekten auf GitHub](https://github.com/search?q=%22%40astrojs%2Ftailwind%22%3A+path%3A%2Fpackage.json\&type=code)!
```

2024-03-25 21:12 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +* Mit dem [Astro Tailwind Starter](https://github.com/withastro/astro/tree/latest/examples/with-tailwindcss?on=github) kannst mit einer Basis für dein Projekt loslegen, die Tailwind für das Styling v
Weil "Astro Tailwind Starter" der englische Name ist, wohl eher keine Bindestriche.

2024-03-25 21:12 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +### Klasse existiert nicht mit `@apply` Direktive
```suggestion
### Klasse existiert nicht mit `@apply`-Direktive
```

2024-03-25 21:18 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Wenn du die `@apply` Direktive in dem `<style>` Tag einer Astro, Vue, Svelte oder anderer Komponenten verwendest, kann es vorkommen, dass ein Fehler wegen deiner definierten Tailwind Klasse, die nich
```suggestion
Wenn du die `@apply`-Direktive in dem `<style>`-Tag einer Astro-, Vue-, Svelte- oder anderen Komponente verwendest, kann es zu der Fehlermeldung kommen, dass die Tailwind-Klasse nicht existiert und der Build schlägt fehl.
```

2024-03-25 21:22 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +[Statt die `@layer` Direktive in deinem globalen Stylesheet zu verwenden](https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css), füge deine eigenen Styles als Plug
```suggestion
[Statt die `@layer`-Direktive in deinem globalen Stylesheet zu verwenden](https://tailwindcss.com/docs/functions-and-directives#using-apply-with-per-component-css), füge deine eigenen Styles als Plugin in der Tailwind-Konfiguration hinzu, um den Fehler zu beheben:
```

2024-03-25 21:24 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +### Klassenbasierte Modifikatoren funkionieren nicht mit der `@apply` Direktive
```suggestion
### Klassenbasierte Modifikatoren funkionieren nicht mit der `@apply`-Direktive
```

2024-03-25 21:27 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Bestimmte Tailwind-Klassen mit Modifikatoren basieren auf der Kombination von Klassen über mehrere Elemente hinweg. Beispielsweise wird `group-hover:text-gray` zu `.group:hover .text-gray` kompiliert
```suggestion
Bestimmte Tailwind-Klassen mit Modifikatoren basieren auf der Kombination von Klassen über mehrere Elemente hinweg. Beispielsweise wird `group-hover:text-gray` zu `.group:hover .text-gray` kompiliert. Wenn dies mit der `@apply`-Direktive in Astro-`<style>`-Tags verwendet wird, werden die kompilierten Styles aus dem Build entfernt, da sie mit keinem Markup in der `.astro`-Datei übereinstimmen. Das gleiche Problem kann auch bei Framework-Komponenten auftreten, die bereichsbezogene Styles unterstützen, wie etwa Vue und Svelte .
```

2024-03-25 21:35 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Für weitere Hilfe, komme zu uns in den `#support` Kanal auf [Discord](https://astro.build/chat). Unsere freundlichen Support Squad Mitglieder helfen dir gerne!
```suggestion
Für weitere Hilfe, komme zu uns in den `#support`-Kanal auf [Discord](https://astro.build/chat). Unsere freundlichen Support-Squad-Mitglieder helfen dir gerne!
```

2024-03-25 21:37 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Du kannst dich auch die [Astro Integration Dokumentation][astro-integration] für weitere Integrationen durchlesen.
```suggestion
Weitere Informationen zu Integrationen findest du in der [Astro-Integration-Dokumentation][astro-integration].
```

2024-03-25 21:41 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Wenn du diese Integration installierst, kannst du die Utility-Klassen von Tailwind sofort verwenden. Gehe zur [Tailwind Dokumentation](https://tailwindcss.com/docs/utility-first), um zu lernen, wie m
```suggestion
Wenn du diese Integration installierst, kannst du die Utility-Klassen von Tailwind sofort verwenden. Gehe zur [Tailwind-Dokumentation](https://tailwindcss.com/docs/utility-first), um zu lernen, wie man Tailwind verwendet. Wenn du eine Utility-Klasse findest, die du ausprobieren möchtest, füge sie einfach einem HTML-Element in einem Projekt hinzu!
```

2024-03-26 15:40 UTC, DerTimonius commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +### Klassenbasierte Modifikatoren funkionieren nicht mit der `@apply` Direktive
Beim ersten Mal hab ich noch überlegt, ob ich da einen Bindestrich einfügen soll oder nicht 😄

2024-03-26 15:46 UTC, DerTimonius commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Erstelle als nächstes eine `tailwind.config.mjs` Datei in deinem Projektstamm&shy;verzeichnis. Du kannst folgenden Befehl ausführen, um eine Konfigurationsdatei mit Basiseinstellungen für dich erstel
ich bin auch nicht 100% davon überzeugt, habe das aber so im [Guide gefunden](https://github.com/withastro/docs/blob/main/src/i18n/de/README.md)

2024-03-26 15:59 UTC, DerTimonius commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Standardmäßig importiert die Integration eine einfache `base.css`-Datei auf jeder Seite deines Projekts. Diese grundlegende CSS-Datei enthält die drei wichtigsten `@tailwind`-Direktiven:
wusste ich auch nicht, mit ein Grund bei den Translation mitzuwirken, man lernt immer was 🙂

2024-03-26 15:59 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Erstelle als nächstes eine `tailwind.config.mjs` Datei in deinem Projektstamm&shy;verzeichnis. Du kannst folgenden Befehl ausführen, um eine Konfigurationsdatei mit Basiseinstellungen für dich erstel
Ah Mist, das habe ich natürlich übersehen 🤦

2024-03-28 01:36 UTC, dreyfus92 commented
!coauthor

2024-03-28 10:46 UTC, Because789 requested changes
Hey @DerTimonius, vielen Dank für den Commit mit den Änderungen! Wenn ein PR von dir auf GitHub eine Review mit Änderungsvorschlägen bekommt, kannst du diese direkt aus dem GitHub-Interface committen. So sieht der Reviewer direkt, welche Vorschläge akzeptiert wurden, und welche nicht. So wie du es gemacht hast, musste ich mehr oder weniger den ganzen Text nochmals durchgehen (was den Vorteil mit sich gebracht hat, dass ich noch mehr fehlende Bindestriche gefunden habe 😁).

Um hier etwas Ordnung reinzubringen, schlage ich vor, dass du alle meine ersten Vorschläge oben _ohne_ Commit resolvest. Danach guckst du dir diese neuen Vorschläge an. Wenn du nichts gegen eine Änderung einzuwenden hast, committe und resolve sie direkt aus dem GitHub-Interface. Wenn dir eine Änderung nicht passt, löst du nicht auf und schreibst einen Kommentar dazu. Und ich antworte dann irgendwann mit meinem Senf 😄 

Bei Fragen, einfach fragen...

2024-03-28 10:46 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Setze auf `true`, um das [`tailwindcss/nesting` PostCSS-Plugin](https://tailwindcss.com/docs/using-with-preprocessors#nesting) zu verwenden. So kannst du auch verschachtelte CSS-Deklarationen neben d
```suggestion
Setze auf `true`, um das [`tailwindcss/nesting`-PostCSS-Plugin](https://tailwindcss.com/docs/using-with-preprocessors#nesting) zu verwenden. So kannst du auch verschachtelte CSS-Deklarationen neben dem Tailwind-Syntax verwenden. Diese Option ist standardmäßig auf `false` gesetzt.
```

2024-03-28 10:46 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/tailwind.mdx
> +Weitere Informationen zu Integrationen findest du in der [Astro-Integration-Dokumentation][astro-integration].
```suggestion
Weitere Informationen zu Integrationen findest du in der [Astro-Integrationen-Dokumentation][astro-integration].
```

2024-03-28 18:34 UTC, Because789 commented
Sehr schön, vielen Dank für deine Geduld! LGTM now! 🚀

2024-03-28 18:50 UTC, dreyfus92 approved these changes
Thanks everyone! LGTM 😁

2024-03-31 00:27 UTC, merged