i18n(de): add 1-setup to german blog tutorial
withastro/docs pull request #7602
Opened 2024-03-26 16:57 UTC by josefineschaefer

#### Description (required)

Deutsche Übersetzung des 1-Setup Teils vom Blog-Tutorial. 

War mir unsicher, ob wir "Terminal" in diesem Fall jedes Mal übersetzen und wie es mit "Dev Tools" aussieht. Ist "Werkzeuge" ok, oder zu "eingedeutscht"? 

Freu mich über Feedback! 

Danke 🙏

2024-03-27 17:04 UTC, Because789 requested changes
Hey @josefineschaefer, auf in die nächste Runde 😄

2024-03-27 17:04 UTC, Because789 commented on src/content/docs/de/tutorial/1-setup/1.mdx
> +- <p>[FreeCodeCamp.org](https://freecodecamp.org) <Badge>external</Badge> — eine kostenlose Bildungswebsite mit vollständigen Kursen oder schnellen Wiederholungen in HTML, CSS, JS und mehr.</p>
"mit schnellen Wiederholungen" dünkt mich etwas holprig.

2024-03-28 09:52 UTC, josefineschaefer commented
Danke für dein Feedback @Because789  - habe die Änderungen umgesetzt. Soll ich die Fehlermeldung doch lieber im Original lassen oder ist die deutsche Übersetzung in Ordnung?

2024-03-28 10:59 UTC, Because789 commented
@josefineschaefer danke dir vielmals! Ich würde die Fehlermeldung so lassen. Wenn das jemand bei Bedarf nicht übersetzen kann, hat er/sie wohl noch ganz andere Probleme 😄 

Wie ist deine Meinung zum Thema "Tools"/"Werkzeuge"? Bin inzwischen selbst nicht mehr sicher, ob das überhaupt einheitlich sein muss, schlicht, weil wohl beide Begriffe im Deutschen sehr geläufig sind. Hat sonst ev. noch jemand eine Meinung dazu, vielleicht @Maxframe?

2024-03-31 08:12 UTC, nicdun commented on src/content/docs/de/tutorial/1-setup/1.mdx
> +  Installiere die lokalen Tools die du brauchst, um das Tutorial abzuschließen
würde bei Tools bleiben, alles einzudeutschen ist nicht immer der beste Weg.

2024-03-31 08:12 UTC, nicdun commented on src/content/docs/de/tutorial/1-setup/1.mdx
> +Wenn der Befehl eine Fehlermeldung wie `Befehl 'node' nicht gefunden` oder eine Versionsnummer älter als `v18.14.1` zurückgibt, musst du [eine kompatible Node.js-Version installieren](https://docs.np
bei Fehlermeldungen würde ich im Original bleiben.

2024-03-31 09:03 UTC, Maxframe commented
Uii, schwierig... Grundsätzlich finde ich es nicht schlecht, gerade häufig verwendete Begriffe möglichst einheitlich zu halten :)
In diesem Fall würde ich mich auch für "Tools" entscheiden. Auch weil es eben in den deutschen Docs schon sehr geläufig zu sein scheint.

2024-04-02 08:20 UTC, nicdun approved these changes

2024-04-02 09:12 UTC, josefineschaefer commented on src/content/docs/de/tutorial/1-setup/1.mdx
> +Wenn der Befehl eine Fehlermeldung wie `Befehl 'node' nicht gefunden` oder eine Versionsnummer älter als `v18.14.1` zurückgibt, musst du [eine kompatible Node.js-Version installieren](https://docs.np
ok @nicdun ist angepasst :)

2024-04-02 09:20 UTC, Because789 commented on src/content/docs/de/tutorial/1-setup/1.mdx
> +## Hol dir alle Werkzeuge, die du brauchst
```suggestion
## Hol dir alle Tools, die du brauchst
```
Das wäre dann der letzte Punkt, "Tools" wird ja tendenziell bevorzugt.

2024-04-02 10:03 UTC, Because789 commented
Very nice, LGTM!

2024-04-04 18:51 UTC, yanthomasdev approved these changes
LGTM! Good work 🙌

2024-04-04 18:51 UTC, merged