i18n(fr): Update CloudFlare adapter docs for v10 from 7210e31
withastro/docs pull request #7653
Opened 2024-03-28 16:10 UTC by thomasbnt

#### Description (required)
Update CloudFlare adapter docs for v10 from 7210e31

#### Related issues & labels (optional)

- Closes #
- Suggested label: i18n

2024-04-07 20:25 UTC, pioupia requested changes

2024-04-07 20:25 UTC, pioupia commented on src/content/docs/fr/guides/integrations-guide/cloudflare.mdx
> +Cette option vous permet d'ajouter ou d'exclure des motifs personnalisés (par exemple `/fonts/*`) au fichier [`_routes.json`](#_routesjson-personnalisé) généré qui détermine quels itinéraires sont gé
```suggestion
Cette option vous permet d'ajouter ou d'exclure des motifs personnalisés (par exemple `/fonts/*`) au fichier [`_routes.json`](#_routesjson-personnalisé) généré qui détermine quelles routes sont générées à la demande. Cela peut être utile si vous avez besoin d'ajouter des modèles de route qui ne peuvent pas être générés automatiquement, ou d'exclure des routes pré-rendues.
```

2024-04-07 20:25 UTC, pioupia commented on src/content/docs/fr/guides/integrations-guide/cloudflare.mdx
> +Vous trouverez plus d'informations sur les modèles d'itinéraires personnalisés dans la [documentation de routing de Cloudflare](https://developers.cloudflare.com/pages/functions/routing/#functions-in
```suggestion
Vous trouverez plus d'informations sur les modèles de routes personnalisées dans la [documentation de routing de Cloudflare](https://developers.cloudflare.com/pages/functions/routing/#functions-invocation-routes). Les routes spécifiées ne sont pas automatiquement dédupliquées et seront ajoutées telles quelles aux routes existantes.
```

2024-04-07 21:40 UTC, thomasbnt commented
Merci @pioupia pour la review!

2024-04-08 06:13 UTC, pioupia approved these changes
LGTM!

2024-04-08 11:09 UTC, yanthomasdev commented
Heads up we got a few updates here, could you apply these changes to the PR? 🙌 https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/integrations-guide/cloudflare.mdx?since=2024-03-24T17:21:37.000Z

2024-04-16 14:35 UTC, thomasbnt commented
> Heads up we got a few updates here, could you apply these changes to the PR? 🙌 [`main`/src/content/docs/en/guides/integrations-guide/cloudflare.mdx?since=2024-03-24T17:21:37.000Z (commits)](https://github.com/withastro/docs/commits/main/src/content/docs/en/guides/integrations-guide/cloudflare.mdx?since=2024-03-24T17:21:37.000Z)

Just seen your mesage @yanthomasdev, don't hesitate to mention me. I pushed modifications!

2024-04-16 14:37 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| File                                                                                                                                                                                                                     | Note                                                  | Locale |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------- | ------ |
| [src/content/docs/fr/guides/deploy/cloudflare.mdx](https://github.com/withastro/docs/blob/8a7b3537e40e1dd69411a066cb6001a6fab3b623/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fdeploy%2Fcloudflare.mdx)                         | Localization changed, will be marked as complete.     | fr     |
| [src/content/docs/fr/guides/integrations-guide/cloudflare.mdx](https://github.com/withastro/docs/blob/8a7b3537e40e1dd69411a066cb6001a6fab3b623/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fintegrations-guide%2Fcloudflare.mdx) | Localization changed, will be marked as complete. 🔄️ | fr     |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-04-16 15:45 UTC, yanthomasdev approved these changes
LGTM! Thanks 🙌

2024-04-16 15:46 UTC, merged