[i18nIgnore] Fixes typo in closing </script> tag
withastro/docs pull request #7677
Opened 2024-03-29 21:00 UTC by pontuslofgren

#### Description (required)

Closing script tag is missing a forward slash.

Best,
Pontus
(atnop  on Discord)

2024-03-29 21:00 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-03-29 21:42 UTC, Fryuni requested changes
Hey @pontuslofgren, thanks for the PR! Nice catch on that typo.

Just one little thing, though. The `[i18nIgnore]` tag is for when a PR doesn't require changes in any translation.
If they do have the same typo, then this should not have that tag so our translation tracker can inform our translators that there is something to fix on this page.

Thanks again and **WELCOME TO TEAM DOCS!!**

2024-03-29 22:14 UTC, Fryuni commented
Confirming, this same typo is present in the translated pages, so this should not be `[i18nIgnore]`

2024-03-29 22:14 UTC, Fryuni approved these changes

2024-03-30 12:59 UTC, casungo approved these changes
LGTM

2024-04-01 13:13 UTC, TheOtterlord approved these changes

2024-04-01 13:20 UTC, merged