i18n(de): translate content/docs/de/guides/alpinejs.mdx.
withastro/docs pull request #7716
Opened 2024-03-31 13:23 UTC by nicdun

#### Description (required)

add translation for guides/alpinejs.mdx

#### Related issues & labels (optional)

#### First-time contributor to Astro Docs? 

Discord: nicdun

2024-04-01 16:08 UTC, DerTimonius reviewed
Hey @nicdun, well done! Ich habe vor allem fehlende Bindestriche eingefügt (learned my lesson the hard way here 😉 ) und ein paar kleine Grammatikfehler gefunden.
Bei einem bin ich mir selbst nicht sicher, ob `selbst manuell` nicht redundant ist oder nicht. Vielleicht hast du hier ja eine gute Idee 🙂

2024-04-01 16:08 UTC, DerTimonius commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Sobald die Integration installiert ist, kannst du [Alpine.js](https://alpinejs.dev/) Direktiven und Syntax in jeder Astro-Komponente verwenden. Das Alpine.js-Skript wird automatisch hinzugefügt und a
```suggestion
Sobald die Integration installiert ist, kannst du [Alpine.js](https://alpinejs.dev/)-Direktiven und Syntax in jeder Astro-Komponente verwenden. Das Alpine.js-Skript wird automatisch hinzugefügt und auf jeder Seite deiner Website aktiviert. Füge Plugin-Skripte in die Seite `<head>` ein.
```

2024-04-01 16:08 UTC, DerTimonius commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Das folgende Beispiel fügt [Alpine's Collapse plugin](https://alpinejs.dev/plugins/collapse) hinzu, um Absatztext ein- und auszublenden:
```suggestion
Das folgende Beispiel fügt [Alpines Collapse-Plugin](https://alpinejs.dev/plugins/collapse) hinzu, um Absatztext ein- und auszublenden:
```

2024-04-01 16:08 UTC, DerTimonius commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Die `@astrojs/alpine` Integration fügt `Alpine` zum globalen Fensterobjekt hinzu. Für die IDE-Autovervollständigung, füge das Folgende zur `src/env.d.ts` hinzu:
```suggestion
Die `@astrojs/alpine`-Integration fügt `Alpine` zum globalen Fensterobjekt hinzu. Für die IDE-Autovervollständigung, füge das Folgende zur `src/env.d.ts` hinzu:
```

2024-04-01 16:08 UTC, DerTimonius commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Die meisten Paketmanager installieren auch die zugehörigen Peer-Abhängigkeiten. Wenn du jedoch beim Starten von Astro die Warnung "Cannot find package 'alpinejs'" (oder eine ähnliche Meldung) erhälst
```suggestion
Die meisten Paketmanager installieren auch die zugehörigen Peer-Abhängigkeiten. Wenn du jedoch beim Starten von Astro die Warnung "Cannot find package 'alpinejs'" (oder eine ähnliche Meldung) erhältst, musst du Alpine.js manuell installieren:
```
Ich finde _selbst manuell_ klingt etwas redundant, was meinst du? Im Englischen ergibt `manually install Alpine.js yourself` Sinn, aber im Deutschen wirkt es auf mich irgendwie komisch

2024-04-01 16:08 UTC, DerTimonius commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +* Das [Astro Alpine.js Beispiel] (https://github.com/withastro/astro/tree/latest/examples/framework-alpine) zeigt, wie man Alpine.js in einem Astro-Projekt verwendet.
```suggestion
* Das [Astro-Alpine.js-Beispiel] (https://github.com/withastro/astro/tree/latest/examples/framework-alpine) zeigt, wie man Alpine.js in einem Astro-Projekt verwendet.
```

2024-04-02 08:30 UTC, nicdun commented
thanks @DerTimonius - ist alles eingepflegt :)

2024-04-02 12:11 UTC, josefineschaefer reviewed
Habe nur einen fehlenden Bindestrich gefunden, ansonsten LGTM! :)

2024-04-02 12:11 UTC, josefineschaefer commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +description: Lerne wie du die @astrojs/alpinejs-Integration in deinem Astro Projekt verwendest.
Astro-Projekt sollte mit Bindestrich geschrieben werden.

2024-04-02 16:41 UTC, Because789 requested changes
Du meine Güte, ich hoffe, ich habe niemandem Bindestrich-Albträume beschert 😄 

Habe 2 Vorschläge hinzugefügt, die noch nicht committet wurden, und zwei Links korrigiert.

2024-04-02 16:41 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Astro enthält einen `astro add`-Befehl, um die Einrichtung offizieller Integrationen zu automatisieren. Wenn du es bevorzugst, kannst du die Integrationen stattdessen auch manuell installieren (#manu
```suggestion
Astro enthält einen `astro add`-Befehl, um die Einrichtung offizieller Integrationen zu automatisieren. Wenn du es bevorzugst, kannst du die Integrationen stattdessen auch [manuell installieren](#manual-install).
```

2024-04-02 16:41 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Du kannst Alpine erweitern, indem du die Option `Einstiegspunkt` auf einen root-relativen Import-Spezifizierer setzt (z.B. `Einstiegspunkt: "/src/einstiegspunkt"`).
Unbedingt "entrypoint"!

2024-04-02 16:41 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +* Das [Astro-Alpine.js-Beispiel] (https://github.com/withastro/astro/tree/latest/examples/framework-alpine) zeigt, wie man Alpine.js in einem Astro-Projekt verwendet.
```suggestion
* Das [Astro-Alpine.js-Beispiel](https://github.com/withastro/astro/tree/latest/examples/framework-alpine) zeigt, wie man Alpine.js in einem Astro-Projekt verwendet.
```

2024-04-02 16:41 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +description: Lerne wie du die @astrojs/alpinejs-Integration in deinem Astro Projekt verwendest.
```suggestion
description: Lerne wie du die @astrojs/alpinejs-Integration in deinem Astro-Projekt verwendest.
```

2024-04-02 16:41 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Die meisten Paketmanager installieren auch die zugehörigen Peer-Abhängigkeiten. Wenn du jedoch beim Starten von Astro die Warnung "Cannot find package 'alpinejs'" (oder eine ähnliche Meldung) erhälts
Ich würde "selbst" weglassen, geht aber wohl beides.

2024-04-02 16:41 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Die `@astrojs/alpine`-Integration fügt `Alpine` zum globalen Fensterobjekt hinzu. Für die IDE-Autovervollständigung, füge das Folgende zur `src/env.d.ts` hinzu:
```suggestion
Die `@astrojs/alpine`-Integration fügt `Alpine` zum globalen window-Objekt hinzu. Für die IDE-Autovervollständigung, füge das Folgende zur `src/env.d.ts` hinzu:
```
Bin nicht 100% sicher, von welchem "window object" im Original genau die Rede ist, aber wenn es dieses ist: [window object](https://www.w3schools.com/jsref/obj_window.asp), sollte man es wohl nicht übersetzen.

2024-04-03 15:29 UTC, Because789 commented
@nicdun, täusche ich mich, oder hast du meine Vorschläge nur resolved und nicht committet? Jedenfalls sind sie in "Files changed" nicht ersichtlich. Kannst sie sonst einfach hier im GitHub-Interface committen (Unresolve conversation - Add to batch - Commit).

2024-04-03 16:07 UTC, nicdun commented
> @nicdun, täusche ich mich, oder hast du meine Vorschläge nur resolved und nicht committet? Jedenfalls sind sie in "Files changed" nicht ersichtlich. Kannst sie sonst einfach hier im GitHub-Interface committen (Unresolve conversation - Add to batch - Commit).

ist alles eingepflegt, ich arbeite lieber lokal und pushe dann die changes.

2024-04-03 18:55 UTC, Because789 requested changes
Alles klar! Habe leider doch noch zwei problematische Stellen entdeckt, aber dann sollte male endlich gut sein 😄

2024-04-03 18:55 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Sobald die Integration installiert ist, kannst du [Alpine.js](https://alpinejs.dev/)-Direktiven und Syntax in jeder Astro-Komponente verwenden. Das Alpine.js-Skript wird automatisch hinzugefügt und a
```suggestion
Sobald die Integration installiert ist, kannst du [Alpine.js](https://alpinejs.dev/)-Direktiven und Syntax in jeder Astro-Komponente verwenden. Das Alpine.js-Skript wird automatisch hinzugefügt und auf jeder Seite deiner Website aktiviert. Füge Plugin-Skripte in das `<head>`-Element der Seite ein.
```

2024-04-03 18:55 UTC, Because789 commented on src/content/docs/de/guides/integrations-guide/alpinejs.mdx
> +Die `@astrojs/alpine`-Integration fügt `Alpine` zum globalen `window`-Objekt hinzu. Für die IDE-Autovervollständigung, füge das Folgende zur `src/env.d.ts` hinzu:
```suggestion
Die `@astrojs/alpine`-Integration fügt `Alpine` zum globalen `window`-Objekt hinzu. Für die IDE-Autovervollständigung, füge das Folgende zu `src/env.d.ts` hinzu:
```

2024-04-03 19:07 UTC, nicdun commented
> Alles klar! Habe leider doch noch zwei problematische Stellen entdeckt, aber dann sollte mal endlich gut sein 😄

top, danke! the first is always the hardest ;) coden ist kein Problem, die Übersetzungsregeln dann doch eher :D

2024-04-03 19:39 UTC, Because789 commented
Beautiful, LGTM! 🚀

2024-04-04 06:05 UTC, DerTimonius commented
LGTM too 🚀

2024-04-04 15:33 UTC, Because789 approved these changes

2024-04-04 17:43 UTC, yanthomasdev approved these changes
LGTM! Thanks peeps 🙌

2024-04-04 17:43 UTC, merged