i18n(fr): ADD `reference/adapter-reference`
withastro/docs pull request #7719
Opened 2024-04-01 00:11 UTC by thomasbnt

#### Description (required)
i18n(fr): ADD `reference/adapter-reference`

#### Related issues & labels (optional)

- Closes #
- Suggested label: i18n

2024-04-08 13:46 UTC, pioupia requested changes

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +Un adaptateur est un type particulier d'[intégration](/fr/reference/integrations-reference/) qui fournit un point d'entrée pour l'affichage côté serveur. Un adaptateur a deux fonctions :
```suggestion
Un adaptateur est un type particulier d'[intégration](/fr/reference/integrations-reference/) qui fournit un point d'entrée pour le rendu côté serveur. Un adaptateur a deux fonctions :
```

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +L'objet passé dans `setAdapter` est défini comme suit :
Pour changer un peu de formulation légèrement
```suggestion
L'objet passé dans `setAdapter` est défini comme ceci :
```

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +	 * SSR uniquement. Chaque itinéraire devient sa propre fonction/fichier.
```suggestion
	 * SSR uniquement. Chaque route devient sa propre fonction/fichier.
```

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +   * L'adaptateur est capable de servir des pages statiques ou affichées par le serveur.
```suggestion
   * L'adaptateur est capable de servir des pages statiques ou rendues par le serveur.
```

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +#### Start
Peut-être traduire le titre par `démarrer` ou `lancer` ?

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +- exécuter une validation spécifique ;
```suggestion
- exécute une validation spécifique ;
```

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +La configuration suivante indique à Astro que cet adaptateur dispose d'un support expérimental pour les actifs, mais qu'il n'est pas compatible avec les services intégrés Sharp et Squoosh :
```suggestion
La configuration suivante indique à Astro que cet adaptateur dispose d'un support expérimental pour les ressources, mais qu'il n'est pas compatible avec les services intégrés Sharp et Squoosh :
```

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +et une erreur si le service utilisé pour les actifs n'est pas compatible avec l'adaptateur :
```suggestion
est une erreur si le service utilisé pour les ressources n'est pas compatible avec l'adaptateur :
```

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +Un ensemble de fonctionnalités qui modifient la sortie des fichiers émis. Lorsqu'un adaptateur opte pour ces fonctionnalités, il obtiendra des informations supplémentaires à l'intérieur de crochets s
```suggestion
Un ensemble de fonctionnalités qui modifient la sortie des fichiers émis. Lorsqu'un adaptateur opte pour ces fonctionnalités, il obtiendra des informations supplémentaires à l'intérieur de hooks spécifiques.
```

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +Chaque fichier émis n'affichera qu'une seule page. Les pages seront émises dans un répertoire `dist/pages/` (ou sous un répertoire `/pages/` dans le répertoire spécifié pour [`outDir`](/fr/reference/
```suggestion
Chaque fichier émis n'affichera qu'une seule page. Les pages seront émises dans un répertoire `dist/pages/` (ou sous un répertoire `/pages/` dans le répertoire spécifié pour [`outDir`](/fr/reference/configuration-reference/#outdir)), et les fichiers émis garderont le même chemin que le dossier `src/pages/`.
```

2024-04-08 13:46 UTC, pioupia commented on src/content/docs/fr/reference/adapter-reference.mdx
> +Chacun de ces itinéraires est soumis à un [démarrage à froid](https://azure.microsoft.com/fr-fr/blog/understanding-serverless-cold-start/) lorsque le gestionnaire s'exécute, ce qui peut entraîner un
```suggestion
Chacunes de ces routes sont soumises à un [démarrage à froid](https://azure.microsoft.com/fr-fr/blog/understanding-serverless-cold-start/) lorsque le gestionnaire s'exécute, ce qui peut entraîner un certain retard. Ce retard est influencé par différents facteurs.
```

2024-04-08 14:08 UTC, thomasbnt commented on src/content/docs/fr/reference/adapter-reference.mdx
> +#### Start
J'ai hésité car sur les autres traductions, le mot n'est pas traduit

2024-04-09 07:35 UTC, pioupia approved these changes

2024-04-09 12:08 UTC, yanthomasdev approved these changes
LGTM! Good work 🚀

2024-04-09 12:08 UTC, merged