i18n(ja): Add `upgrade-astro.mdx`
withastro/docs pull request #7725
Opened 2024-04-01 15:22 UTC by huyikai

#### Description (required)

Add `upgrade-astro.mdx`

#### Related issues & labels (optional)

- #7396

2024-04-02 16:07 UTC, morinokami requested changes
翻訳いただきありがとうございました！かなり多くなりましたが、修正が必要な箇所を指摘しましたので、ご確認をお願いします。

なお、https://github.com/withastro/docs/tree/main/src/i18n/ja に翻訳ガイドがあるため、ここに一度目を通し、他の訳文と大きな差異がないように翻訳していただけるとありがたいです🙏

2024-04-02 16:07 UTC, morinokami commented on src/content/docs/ja/upgrade-astro.mdx
> +- **ドキュメントの改善**（例：参照とエラーメッセージ）。これらは`docs`リポジトリのソースから構築されます。これにより、ドキュメントソースコンテンツがメインの`astro`リポジトリに格納されている場合、Astroはドキュメントの修正と改善を迅速に更新できます。
```suggestion
- **ドキュメントの改善**（例：リファレンスとエラーメッセージ）。これらは`docs`リポジトリのためにソースコードからビルドされます。これにより、ドキュメントのもととなるコンテンツがメインの`astro`リポジトリに格納されている場合、Astroはドキュメントの修正と改善を迅速に更新できます。
```

2024-04-02 23:27 UTC, huyikai commented on src/content/docs/ja/upgrade-astro.mdx
> +このガイドでは、Astroと関連する依存関係のバージョンを更新する方法、バージョン間で何が変更されたかを学ぶ方法、そしてAstroのバージョニングシステムとそれに対応するドキュメントの更新を理解する方法について説明します。
はい。ご指摘ありがとうございます

2024-04-02 23:28 UTC, huyikai commented on src/content/docs/ja/upgrade-astro.mdx
> +最新リリースのAstroは<Version pkgName="astro" />です。
確かにそうです。ありがとうございます

2024-04-02 23:37 UTC, huyikai commented on src/content/docs/ja/upgrade-astro.mdx
> +パッケージマネージャーを使用して、一つのコマンドでプロジェクトのAstroとすべての公式統合を最新バージョンに更新します：
ごめんなさい、用語集に沿って翻訳するべきでした。ご指摘ありがとうございます。

2024-04-02 23:50 UTC, huyikai commented on src/content/docs/ja/upgrade-astro.mdx
> +このドキュメントは、[マイナーリリース](#マイナーチェンジ)および[メジャーバージョンリリース](#主要な変更点)ごとに更新されます。新機能が追加されたり、既存の使用方法が変更されたりすると、ドキュメントは**現在のAstroの挙動**を反映するように更新されます。プロジェクトが更新されていない場合、最新のドキュメントと一部の挙動が一致しないことに気づくかもしれません。
なるほど。わかりました

2024-04-03 00:02 UTC, huyikai commented on src/content/docs/ja/upgrade-astro.mdx
> +以下のアップグレードガイドでは、新旧のバージョンを比較して変更点を説明しています。アップグレードガイドには、コードの変更を必要とする可能性のあるすべての内容が含まれています：破壊的変更、非推奨化、機能の削除や置換、および使用方法の更新ガイド。Astroへの各変更には、「何をすべきか？」セクションが含まれており、プロジェクトコードを成功裏に更新するための助けとなります。
はい。😂

2024-04-03 00:07 UTC, huyikai commented on src/content/docs/ja/upgrade-astro.mdx
> +古いバージョンのAstroのドキュメントはメンテナンスされていませんが、静的スナップショットとして利用可能です。プロジェクトをアップグレードできない場合でも、ガイドや参照資料を参照したい場合は、これらのバージョンのドキュメントを使用してください：
そうですか、 [:] のポイントについては記しておきました。

2024-04-03 02:45 UTC, huyikai commented
@morinokami レビューコードに感謝します。私はたくさん勉強しました。また、#7652 についての翻訳を補足しましたので、お暇なときに見てください🙏🏻

2024-04-03 14:19 UTC, morinokami reviewed
新しく追加された箇所に関してコメントしました、ご確認をお願いします！

2024-04-03 14:19 UTC, morinokami commented on src/content/docs/ja/upgrade-astro.mdx
> +- Node.jsの最小**_メンテナンス_ LTS**（同じメジャーレンジ内で、例：`v18.14.*`から`v18.20.*`へ）バージョンのアップグレードは、Astroの**マイナー**リリースで行われることがあります。
上では Maintainance LTS と英語で書いているため、統一したほうが良いと思います。これについては定訳がないため、一旦英語に合わせましょう。また、括弧の位置と中身がおかしいため、これも修正が必要そうです:

```suggestion
- Node.jsの最小**_ Maintenance_ LTS**バージョンのアップグレード（`v18.14.*`から`v18.20.*`へなど、同じメジャーレンジ内）は、Astroの**マイナー**リリースで行われることがあります。
```

2024-04-03 14:19 UTC, morinokami commented on src/content/docs/ja/upgrade-astro.mdx
> +  - セキュリティ例外：Node.jsのセキュリティ欠陥が公開され、それがAstroに**影響を与える**場合、コアチームは**パッチ**リリースで最小バージョンの**_メンテナンス_ LTS**を上げることができます。
「セキュリティ例外」や「セキュリティ欠陥」という言い方は一般的ではないため、わかりやすい表現に変えたほうがいいと思います:

```suggestion
  - セキュリティのための例外：Node.jsのセキュリティ上の欠陥が公開・修正され、それがAstroに**影響を与える**場合、コアチームは**パッチ**リリースで最小バージョンの**_ Maintenance_ LTS**を上げることができます。
```

2024-04-03 14:19 UTC, morinokami commented on src/content/docs/ja/upgrade-astro.mdx
> +  - セキュリティ例外：Node.jsのセキュリティ欠陥が公開され、それがAstroに**影響を与える**場合、コアチームは**マイナー**リリースで最小バージョンを上げることができます。
```suggestion
  - セキュリティのための例外：Node.jsのセキュリティ上の欠陥が公開・修正され、それがAstroに**影響を与える**場合、コアチームは**マイナー**リリースで最小バージョンを上げることができます。
```

2024-04-03 14:19 UTC, morinokami commented on src/content/docs/ja/upgrade-astro.mdx
> +コアチームは、以前のメジャーレベルの変更に対して**セキュリティ修正のみ**の長期メンテナンスを提供します。これは、現在のメジャーが`v4.*`である場合、コアチームがセキュリティ修正をバックポートし、新しい`v3.*`リリースを発行することを意味します。
こちらも少し誤訳が含まれているため、直したほうが良さそうです:

```suggestion
コアチームは、直前のメジャーバージョンに対して**セキュリティ上の修正のみ**のメンテナンスを延長して提供します。これは、現在のメジャーが`v4.*`である場合、コアチームがセキュリティ上の修正をバックポートし、新しい`v3.*`リリースを公開することを意味します。
```

2024-04-04 11:44 UTC, morinokami reviewed
最後に一点コメントしましたので、対応をお願いします🙏

2024-04-04 11:44 UTC, morinokami commented on src/content/docs/ja/upgrade-astro.mdx
> +  - セキュリティのための例外：Node.jsのセキュリティ上の欠陥が公開・修正され、それがAstroに**影響を与える**場合、コアチームは**パッチ**リリースで最小バージョンの**_ Maintenance_ LTS**を上げることができます。
この二行で `**_ Maintenance_ LTS**` の `__` が上手くパースされず、表示が乱れてしまっているようです。おそらくスペースを挿入することで直るので、ローカルで表示を確認しつつ修正をお願いします！

<img width="716" alt="Screenshot 2024-04-04 at 20 43 10" src="https://github.com/withastro/docs/assets/7889778/94772e78-6d1a-4f27-94c0-0bbf69d6b36b">

2024-04-04 13:31 UTC, huyikai commented on src/content/docs/ja/upgrade-astro.mdx
> +  - セキュリティのための例外：Node.jsのセキュリティ上の欠陥が公開・修正され、それがAstroに**影響を与える**場合、コアチームは**パッチ**リリースで最小バージョンの**_ Maintenance_ LTS**を上げることができます。
すみません、私は処理しました、お手数ですがご確認ください。

2024-04-04 14:34 UTC, morinokami approved these changes
かなり長くなりましたがお疲れ様でした、LGTM!! 👍

2024-04-04 17:53 UTC, yanthomasdev approved these changes
LGTM! Good work peeps 🚀

2024-04-04 17:53 UTC, merged