i18n(de): translate 0-introduction/index to German
withastro/docs pull request #7734
Opened 2024-04-02 12:56 UTC by josefineschaefer

#### Description (required)
Deutsche Übersetzung von 0-introduction/index.mdx
War nicht ganz sicher, wie mit der Übersetzung von "Tutorial" umgegangen wird, da es im Deutschen ja auch sehr geläufig ist. Bin gespannt auf euer Feedback :) 

#### Related issues & labels (optional)
- Suggested label: i18n

 
Discord name: josefine.sch

2024-04-02 17:24 UTC, Because789 requested changes
Habe diesmal nur zwei kleine Bemerkungen.

Bezüglich Tutorial: Ich habe noch einen PR offen hier https://github.com/withastro/docs/pull/7122 "Tutorial" habe ich nicht übersetzt und das war unkontrovers. Bei "Guides" und "Recipes" sieht es anders aus. Wäre super, wenn sich ein paar Leute dort dazu äussern könnten, damit es mit dem PR mal vorwärtsgeht.

2024-04-02 17:24 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/index.mdx
> +- Mit Astro-Komponenten bauen
```suggestion
- Astro-Komponenten verwenden
```
"Mit Astro-Komponenten bauen" klingt irgendwie schief, auch wenn es näher beim Original ist.

2024-04-02 17:24 UTC, Because789 commented on src/content/docs/de/tutorial/0-introduction/index.mdx
> +- [ ] Sieht gut aus! Ich bin bereit, loszulegen!
```suggestion
- [ ] Sieht gut aus! Ich bin bereit loszulegen!
```
Wenn ich mich nicht täusche, ist das Komma hier optional, würde ich weglassen.

2024-04-02 19:13 UTC, Because789 approved these changes
Very nice, LGTM! 🚀

2024-04-04 06:40 UTC, josefineschaefer commented
Hatte mich die ganze Zeit schon gefragt, was mit den Checks war 🙈 Danke @Because789  - hab die description angepasst und die Checks laufen nun durch ✅

2024-04-04 08:44 UTC, Because789 commented
Sehr schön, jetzt aber LGTM 😄

2024-04-04 18:14 UTC, yanthomasdev approved these changes
LGTM! Thanks peeps. We only merge the tutorial when it's fully translated, therefore I created a branch and a PR to merge the full thing when it's complete.

2024-04-04 18:15 UTC, merged