Enforce __session name for cookie
withastro/docs pull request #8014
Opened 2024-04-25 16:39 UTC by leoxs22

#### Description (required)

Docs snippets are saving a cookie called `session`

Firebase will remove all cookies except for `__session` https://firebase.google.com/docs/hosting/manage-cache#using_cookies

Using the current code in the docs will result in a 500 error. Adding a log in a middleware will show that no cookies are being received in the firebase function.

2024-04-25 16:39 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-04-25 16:41 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                                     | Note                                                       |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| en     | [guides/backend/google-firebase.mdx](https://github.com/withastro/docs/blob/f68685586d5e76527e268ed2854654e87f4b94dc/src%2Fcontent%2Fdocs%2Fen%2Fguides%2Fbackend%2Fgoogle-firebase.mdx) | Source changed, localizations will be marked as outdated.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-04-26 15:57 UTC, Fryuni requested changes
Hey @leoxs22, thanks for the PR, and welcome to the team 🎉 🎉 🎉 

The code seems to be working fine with the fix. I sent a suggestion to the text because it implies more than it should (at least to me, maybe I'm being a bit paranoid). Besides that LGTM

2024-04-26 15:57 UTC, Fryuni commented on src/content/docs/en/guides/backend/google-firebase.mdx
> +Cookie must be called '__session'. Firebase functions [will remove all cookies except for that one](https://firebase.google.com/docs/hosting/manage-cache#using_cookies).
To me, this reads like "a session cookie must have this name" when, in fact, it is the only cookie allowed _at all_. 

I think the warning should be a little stronger.

```suggestion
Firebase only allows the use of [one cookie, and it must be named `__session`](https://firebase.google.com/docs/hosting/manage-cache#using_cookies). Any other cookies the client sends will not be visible to your application.
```

2024-04-26 16:38 UTC, leoxs22 commented
Thanks! I agree, it looks better that way :smile:

2024-04-26 23:48 UTC, Fryuni approved these changes
LGTM!

2024-05-01 15:18 UTC, merged