i18n(fr) Update french translation for `aws.mdx` and `content.mdx`
withastro/docs pull request #8028
Opened 2024-04-26 14:09 UTC by McFlyPartages

#### Description (required)

Update french translation for `aws.mdx` and `community-ressources/content.mdx` files with PR #7902 #7991 and and a few omissions.

2024-04-26 14:12 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                             | Note                                               |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| fr     | [community-resources/content.mdx](https://github.com/withastro/docs/blob/ba9b5d176a72b64dfb730c4310db985f16be9e07/src%2Fcontent%2Fdocs%2Ffr%2Fcommunity-resources%2Fcontent.mdx) | Localization changed, will be marked as complete.  |
| fr     | [guides/deploy/aws.mdx](https://github.com/withastro/docs/blob/ba9b5d176a72b64dfb730c4310db985f16be9e07/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fdeploy%2Faws.mdx)                   | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-04-26 17:39 UTC, pioupia requested changes
Un panier ou un seau ?

2024-04-26 17:39 UTC, pioupia commented on src/content/docs/fr/guides/deploy/aws.mdx
> +CloudFront est un service web qui offre des capacités de réseau de diffusion de contenu (CDN). Il est utilisé pour mettre en cache le contenu d'un serveur web et le distribuer aux utilisateurs finaux
Il vaut mieux garder le mot en anglais non ?
```suggestion
CloudFront est un service web qui offre des capacités de réseau de diffusion de contenu (CDN). Il est utilisé pour mettre en cache le contenu d'un serveur web et le distribuer aux utilisateurs finaux. CloudFront facture la quantité de données transférées. L'ajout de CloudFront à votre bucket S3 est plus rentable et permet une diffusion plus rapide.
```

2024-04-26 17:39 UTC, pioupia commented on src/content/docs/fr/guides/deploy/aws.mdx
> +  - **Domaine d'origine:** Point d'arrivée de votre site web statique dans le seau S3. Vous pouvez trouver votre point de terminaison dans les **Propriétés > Hébergement de site web statique** de vot
"Seau"
```suggestion
  - **Domaine d'origine:** Point d'arrivée de votre site web statique dans le bucket S3. Vous pouvez trouver votre point de terminaison dans les **Propriétés > Hébergement de site web statique** de votre bucket S3. Vous pouvez également sélectionner votre bucket S3 et cliquer sur l'appel pour remplacer l'adresse de votre bucket par le point de terminaison statique de votre bucket.
```

2024-04-26 22:37 UTC, McFlyPartages commented
> Un panier ou un seau ?

Je laisserai l 'mot en Anglais, merci pour tes suggestions

2024-04-27 01:13 UTC, dreyfus92 approved these changes
Merci les gars! LGTM ✅

2024-04-27 01:22 UTC, merged