i18n(fr) Update french translation for `fonts.mdx`
withastro/docs pull request #8030
Opened 2024-04-26 14:24 UTC by McFlyPartages

#### Description (required)
Update french translation for `fonts.mdx` file and few omission

2024-04-26 14:27 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                               | Note                                               |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| fr     | [guides/fonts.mdx](https://github.com/withastro/docs/blob/2c3feedf33b2aa30345057823233809af448ef06/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Ffonts.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-04-26 17:43 UTC, pioupia requested changes

2024-04-26 17:43 UTC, pioupia commented on src/content/docs/fr/guides/fonts.mdx
> +  Vous souhaitez ajouter des polices de caractères personnalisées à un site Astro ? Utiliser Google Fonts
```suggestion
  Vous souhaitez ajouter des polices d'écritures personnalisées à un site Astro ? Utilisez Google Fonts 
```

2024-04-26 17:43 UTC, pioupia commented on src/content/docs/fr/guides/fonts.mdx
> +  avec Fontsource ou ajouter une police de votre choix.
Il vaut mieux tout conjuguer...
```suggestion
  avec Fontsource ou ajoutez une police de votre choix.
```

2024-04-27 01:23 UTC, dreyfus92 approved these changes
Merci les gars! LGTM ✅

2024-04-27 01:34 UTC, merged