i18n(fr) Update French translation `markdown-content.mdx`
withastro/docs pull request #8033
Opened 2024-04-26 14:42 UTC by McFlyPartages

#### Description (required)
Update French translation `markdown-content.mdx` file with PR #7462

2024-04-26 14:44 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                     | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| fr     | [guides/markdown-content.mdx](https://github.com/withastro/docs/blob/ab85857f60740aad98146fcf3573a91d6203ad2e/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmarkdown-content.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-04-26 17:46 UTC, pioupia requested changes
Le lien n'est pas au bon endroit.

2024-04-26 17:46 UTC, pioupia commented on src/content/docs/fr/guides/markdown-content.mdx
> +Astro fournit des [pages Markdown et MDX](/fr/basics/astro-pages/#pages-markdownmdx) (situées dans `src/pages/`) avec une propriété spéciale `layout` qui peut spécifier un chemin relatif (ou [alias](
```suggestion
Astro fournit des [pages Markdown et MDX](/fr/basics/astro-pages/#pages-markdownmdx) (situées dans `src/pages/`) avec une propriété spéciale `layout` qui peut spécifier un chemin relatif (ou [alias](/fr/guides/aliases/)) vers un [composant de mise en page](/fr/basics/layouts/#mises-en-page-markdownmdx) Astro.
```

2024-04-27 01:34 UTC, dreyfus92 approved these changes
LGTM ✅

2024-04-27 01:43 UTC, merged