i18n(fr): Add `guides/deploy/flyio.mdx`
withastro/docs pull request #8166
Opened 2024-05-02 15:49 UTC by thomasbnt

#### Description (required)
Add `guides/deploy/flyio.mdx` in French language

#### Related issues & labels (optional)

- Suggested label: i18n

🥳

2024-05-02 15:52 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                               | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| fr     | [guides/deploy/flyio.mdx](https://github.com/withastro/docs/blob/1daa1053866103c5e909f5f70ca087d2c8da4a69/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fdeploy%2Fflyio.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-05-03 12:01 UTC, pioupia requested changes

2024-05-03 12:01 UTC, pioupia commented on src/content/docs/fr/guides/deploy/flyio.mdx
> +Si vous n'avez pas encore de fichier Docker, `fly launch` va en générer un pour vous, ainsi que préparer un fichier `fly.toml`. Pour les projets `server` ou `hybrid`, ce fichier Docker inclura la com
```suggestion
Si vous n'avez pas encore de Dockerfile, `fly launch` va en générer un pour vous, ainsi que préparer un fichier `fly.toml`. Pour les projets `server` ou `hybrid`, ce Dockerfile inclura la commande de démarrage appropriée et les variables d'environnement.
```

2024-05-03 12:05 UTC, thomasbnt commented
Salut et merci pour ta review @pioupia ! 🚀

2024-05-04 06:15 UTC, pioupia approved these changes
LGTM

2024-05-04 21:09 UTC, dreyfus92 approved these changes
Merci les gars! LGTM ✅

2024-05-04 21:21 UTC, merged