Update contentful.mdx
withastro/docs pull request #8172
Opened 2024-05-03 06:51 UTC by masahirokjp

add line 224, 225, 383

#### Description (required)

#### Related issues & labels (optional)

- Closes #
- Suggested label:

2024-05-03 06:51 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-05-03 06:53 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                   | Note                                               |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| ja     | [guides/cms/contentful.mdx](https://github.com/withastro/docs/blob/fc2b9b8df64e248dd533bd1ab21140caca8e5570/src%2Fcontent%2Fdocs%2Fja%2Fguides%2Fcms%2Fcontentful.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-05-12 10:51 UTC, morinokami requested changes

2024-05-12 10:51 UTC, morinokami commented on src/content/docs/ja/guides/cms/contentful.mdx
> +import contentful, { type EntryFieldTypes } from "contentful";
この箇所は英文側で特に変更されておらず、変更不要なように思えます。https://github.com/withastro/docs/blob/main/src/content/docs/en/guides/cms/contentful.mdx?plain=1#L221-L222 を確認してください。

また、表示そのものも崩れてしまっています:

https://docs-git-fork-masahirokjp-patch-1-astrodotbuild.vercel.app/ja/guides/cms/contentful/#%E3%83%96%E3%83%AD%E3%82%B0%E8%A8%98%E4%BA%8B%E3%81%AE%E3%83%AA%E3%82%B9%E3%83%88%E3%82%92%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B

2024-05-12 10:51 UTC, morinokami commented on src/content/docs/ja/guides/cms/contentful.mdx
> +`params`内のプロパティは動的ルーティングの名前と一致させる必要があります。ファイル名が`[slug].astro`であるため、`slug`を利用します。
こちらは英文に存在しない文のようです。「params 無い」というタイポの修正であれば問題ないのですが、原文に存在しない文の追加は問題があるため、マージすることは難しいと思います。

2024-06-08 18:05 UTC, yanthomasdev commented
Thanks for making this PR @masahirokjp, I've seen @morinokami's comments haven't been addressed, so I'll be closing this one and you're welcome to reopen/make a new PR in case you have the time to take this contribution to the finish line! Also, regarding the comment made, we do not accept language-exclusive content in our translations, so if you do so, please remove any content that doesn't match the original.

2024-06-08 18:05 UTC, closed without merging