i18n(fr): Update some files from #8224
withastro/docs pull request #8251
Opened 2024-05-11 01:18 UTC by thomasbnt

Signed-off-by: Thomas Bonnet <thomasbnt@protonmail.com>

#### Description (required)
Update some files from #8224. 

- [i18n(fr): Update](https://github.com/withastro/docs/commit/99a115f63124358edabac81b85ed39fbe30b9a57) [mdx.mdx](https://github.com/withastro/docs/commit/99a115f63124358edabac81b85ed39fbe30b9a57) 
- [i18n(fr): Update](https://github.com/withastro/docs/commit/9edec37dc172ccd1c330cc5c0b6dbd5eba89b17b) [preact.mdx](https://github.com/withastro/docs/commit/9edec37dc172ccd1c330cc5c0b6dbd5eba89b17b)
- [i18n(fr): Update](https://github.com/withastro/docs/commit/04651fc63e40e6d7130a6dbd3635e95393bae3aa) [solid-js.mdx](https://github.com/withastro/docs/commit/04651fc63e40e6d7130a6dbd3635e95393bae3aa)
- [i18n(fr): Update](https://github.com/withastro/docs/commit/779fd571bf919a1d840ab524541fa94b8b2b44df) [vercel.mdx](https://github.com/withastro/docs/commit/779fd571bf919a1d840ab524541fa94b8b2b44df)
- [i18n(fr): Update](https://github.com/withastro/docs/commit/ce3d9ea0d608277faffdc89bbcec1b297ad920fd) [vue.mdx](https://github.com/withastro/docs/commit/ce3d9ea0d608277faffdc89bbcec1b297ad920fd) 
- [i18n(fr): Update](https://github.com/withastro/docs/commit/fd979f7717276c792ec541887637c4c6268b5fe7) [testing.mdx](https://github.com/withastro/docs/commit/fd979f7717276c792ec541887637c4c6268b5fe7)
- [i18n(fr): Update](https://github.com/withastro/docs/commit/2badf143a6a3de5ad34e8c19b63ac621d2e05231) [error-reference.mdx](https://github.com/withastro/docs/commit/2badf143a6a3de5ad34e8c19b63ac621d2e05231) 

#### Related issues & labels (optional)

- Closes #
- Suggested label: i18n

2024-05-11 01:20 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                                             | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | -------------------------------------------------- |
| fr     | [guides/integrations-guide/mdx.mdx](https://github.com/withastro/docs/blob/2badf143a6a3de5ad34e8c19b63ac621d2e05231/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fintegrations-guide%2Fmdx.mdx)           | Localization changed, will be marked as complete.  |
| fr     | [guides/integrations-guide/preact.mdx](https://github.com/withastro/docs/blob/2badf143a6a3de5ad34e8c19b63ac621d2e05231/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fintegrations-guide%2Fpreact.mdx)     | Localization changed, will be marked as complete.  |
| fr     | [guides/integrations-guide/solid-js.mdx](https://github.com/withastro/docs/blob/2badf143a6a3de5ad34e8c19b63ac621d2e05231/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fintegrations-guide%2Fsolid-js.mdx) | Localization changed, will be marked as complete.  |
| fr     | [guides/integrations-guide/vercel.mdx](https://github.com/withastro/docs/blob/2badf143a6a3de5ad34e8c19b63ac621d2e05231/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fintegrations-guide%2Fvercel.mdx)     | Localization changed, will be marked as complete.  |
| fr     | [guides/integrations-guide/vue.mdx](https://github.com/withastro/docs/blob/2badf143a6a3de5ad34e8c19b63ac621d2e05231/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fintegrations-guide%2Fvue.mdx)           | Localization changed, will be marked as complete.  |
| fr     | [guides/testing.mdx](https://github.com/withastro/docs/blob/2badf143a6a3de5ad34e8c19b63ac621d2e05231/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Ftesting.mdx)                                           | Localization changed, will be marked as complete.  |
| fr     | [reference/error-reference.mdx](https://github.com/withastro/docs/blob/2badf143a6a3de5ad34e8c19b63ac621d2e05231/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Ferror-reference.mdx)                     | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-05-11 08:38 UTC, pioupia requested changes

2024-05-11 08:38 UTC, pioupia commented on src/content/docs/fr/guides/testing.mdx
> +A partir d'Astro 4.8, si vous avez besoin de personnaliser la configuration Astro appliquée dans vos tests, passez un second argument à `getViteConfig()` :
Je trouve ça plus logique et plus clair "pour vos tests" que la traduction littérale "appliquée dans vos tests".
```suggestion
À partir d'Astro 4.8, si vous avez besoin de personnaliser la configuration Astro pour vos tests, passez un second argument à `getViteConfig()` :
```

2024-05-11 08:38 UTC, pioupia commented on src/content/docs/fr/guides/integrations-guide/vue.mdx
> +Vous pouvez activer [Vue DevTools](https://devtools-next.vuejs.org/) dans le développement en passant un objet avec `devtools : true` à votre configuration d'intégration `vue()` :
`in` -> `dans`
`in` -> `en` :white_check_mark: (`en développement en passant` c'est redondant)
donc `durant le développement` me semble plus clair.
```suggestion
Vous pouvez activer [Vue DevTools](https://devtools-next.vuejs.org/) durant le développement en passant un objet avec `devtools : true` à votre configuration d'intégration `vue()` :
```

2024-05-11 08:38 UTC, pioupia commented on src/content/docs/fr/guides/integrations-guide/solid-js.mdx
> +Vous pouvez activer [Solid DevTools](https://github.com/thetarnav/solid-devtools) dans le développement en passant un objet avec `devtools : true` à votre configuration d'intégration `solid()` et en
Même remarque qu'en dessous
```suggestion
Vous pouvez activer [Solid DevTools](https://github.com/thetarnav/solid-devtools) durant le développement en passant un objet avec `devtools : true` à votre configuration d'intégration `solid()` et en ajoutant `solid-devtools` aux dépendances de votre projet :
```

2024-05-11 08:38 UTC, pioupia commented on src/content/docs/fr/guides/integrations-guide/preact.mdx
> +Vous pouvez activer [Preact devtools](https://preactjs.github.io/preact-devtools/) dans le développement en passant un objet avec `devtools : true` à votre configuration d'intégration `preact()` :
```suggestion
Vous pouvez activer [Preact devtools](https://preactjs.github.io/preact-devtools/) durant le développement en passant un objet avec `devtools : true` à votre configuration d'intégration `preact()` :
```

2024-05-11 16:17 UTC, thomasbnt commented
Merci @pioupia pour la review!

2024-05-12 16:03 UTC, pioupia approved these changes
LGTM

2024-05-13 15:19 UTC, McFlyPartages approved these changes
LGTM

2024-05-14 17:35 UTC, merged