i18n(fr): Add route-not-found.mdx, incorrect-strategy-for-i18n.mdx and missing-middleware-for-internationalization.mdx with French translations
withastro/docs pull request #8356
Opened 2024-05-20 18:07 UTC by bengeois

Description (required)
Add route-not-found.mdx, incorrect-strategy-for-i18n.mdx and missing-middleware-for-internationalization.mdx with French translations

Related issues & labels (optional)
Suggested label: i18n

2024-05-20 18:09 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files


| Locale | File                                                                                                                                                                                                                                                 | Note                                               |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| fr     | [reference/error-reference.mdx](https://github.com/withastro/docs/blob/20ccb7a8c409f97b5849b10d635972b81db9b039/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Ferror-reference.mdx)                                                                         | Localization changed, will be marked as complete.  |
| fr     | [reference/errors/incorrect-strategy-for-i18n.mdx](https://github.com/withastro/docs/blob/20ccb7a8c409f97b5849b10d635972b81db9b039/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Ferrors%2Fincorrect-strategy-for-i18n.mdx)                                 | Localization added, will be marked as complete.    |
| fr     | [reference/errors/missing-middleware-for-internationalization.mdx](https://github.com/withastro/docs/blob/20ccb7a8c409f97b5849b10d635972b81db9b039/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Ferrors%2Fmissing-middleware-for-internationalization.mdx) | Localization added, will be marked as complete.    |
| fr     | [reference/errors/route-not-found.mdx](https://github.com/withastro/docs/blob/20ccb7a8c409f97b5849b10d635972b81db9b039/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Ferrors%2Froute-not-found.mdx)                                                         | Localization added, will be marked as complete.    |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-05-20 19:38 UTC, thomasbnt requested changes

2024-05-20 19:38 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/incorrect-strategy-for-i18n.mdx
> +> **IncorrectStrategyForI18n**: La fonction `FUNCTION_NAME` ne peut être utilisée que lorsque `i18n.routing.strategy` est défini sur `"manual"`.
Les erreurs ne se traduisent pas.

```suggestion
> **MissingMiddlewareForInternationalization**:The function `FUNCTION_NAME` can only be used when the `i18n.routing.strategy` is set to `"manual"`.
```

2024-05-20 19:38 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/missing-middleware-for-internationalization.mdx
> +> **MissingMiddlewareForInternationalization**: Votre paramètre de configuration `i18n.routing : 'manual'` exige que vous fournissiez votre propre fichier `middleware' i18n.
Même souci ici 
```suggestion
> **MissingMiddlewareForInternationalization**: Your configuration setting `i18n.routing: 'manual'` requires you to provide your own i18n `middleware` file.
```

2024-05-20 19:38 UTC, thomasbnt commented on src/content/docs/fr/reference/errors/route-not-found.mdx
> +> **RouteNotFound**: Astro n'a pas trouvé la route correspondante à celle que vous avez demandée.
```suggestion
> **RouteNotFound**: Astro could not find a route that matches the one you requested.
```

2024-05-20 19:57 UTC, bengeois commented
@thomasbnt Bien vu, je ne savais pas, je viens d'appliquer les suggestions 👍🏼

2024-05-20 19:59 UTC, thomasbnt approved these changes
LGTM!

2024-05-21 06:51 UTC, pioupia requested changes
Just a space was missing.

2024-05-21 06:51 UTC, pioupia commented on src/content/docs/fr/reference/errors/incorrect-strategy-for-i18n.mdx
> +> **MissingMiddlewareForInternationalization**:The function `FUNCTION_NAME` can only be used when the `i18n.routing.strategy` is set to `"manual"`.
```suggestion
> **MissingMiddlewareForInternationalization**: The function `FUNCTION_NAME` can only be used when the `i18n.routing.strategy` is set to `"manual"`.
```

2024-05-21 06:51 UTC, pioupia commented on src/content/docs/fr/reference/errors/incorrect-strategy-for-i18n.mdx
> +Certaines fonctions d'internationalisation ne sont disponibles que lorsque le routage i18n d'Astro est désactivé par le paramètre de configuration `i18n.routing` défini sur `"manual"`.
Phrase largement correcte. Mais je ne sais pas si la version anglaise n'est pas mieux :
```suggestion
Certaines fonctions d'internationalisation ne sont disponibles que lorsque le routage i18n d'Astro est désactivé par le paramètre de configuration `i18n.routing: "manual"`.
```

2024-05-21 07:41 UTC, bengeois commented on src/content/docs/fr/reference/errors/incorrect-strategy-for-i18n.mdx
> +Certaines fonctions d'internationalisation ne sont disponibles que lorsque le routage i18n d'Astro est désactivé par le paramètre de configuration `i18n.routing` défini sur `"manual"`.
Ca marche aussi comme ça, c'est peut-être plus simple à la lecture en effet 👍🏼

2024-05-21 10:21 UTC, McFlyPartages commented on src/content/docs/fr/reference/errors/missing-middleware-for-internationalization.mdx
> +Your configuration setting `i18n.routing: 'manual'` requires you to provide your own i18n `middleware` file.
```suggestion
Votre paramètre de configuration `i18n.routing: 'manual'` exige que vous fournissiez votre propre fichier `middleware` i18n.
```

2024-05-21 10:22 UTC, McFlyPartages commented on src/content/docs/fr/reference/errors/missing-middleware-for-internationalization.mdx
> +Your configuration setting `i18n.routing: 'manual'` requires you to provide your own i18n `middleware` file.
Salut,

À part cette traduction manquante, le reste est bon.
Merci à toi

2024-05-21 11:34 UTC, McFlyPartages approved these changes
LGTM

2024-05-21 19:03 UTC, yanthomasdev approved these changes
LGTM! Good work peeps 🙌

2024-05-21 19:04 UTC, merged