i18n(it): translate guides/deploy/zerops.mdx
withastro/docs pull request #8541
Opened 2024-06-16 06:02 UTC by vclemenzi

#### Description (required)

translate `guides/configuring-astro`

#### Related issues & labels (optional)

- Suggested label: i18n

2024-06-16 06:05 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                 | Note                                             |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| it     | [guides/deploy/zerops.mdx](https://github.com/withastro/docs/blob/697ddf4218c17cdca5de9427f0286b56d18dd804/src%2Fcontent%2Fdocs%2Fit%2Fguides%2Fdeploy%2Fzerops.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-06-16 16:13 UTC, casungo requested changes

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +title: Effetua il Deploy del tuo sito Astro su Zerops
```suggestion
title: Effettua il deploy del tuo sito Astro su Zerops
```

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +description: Come effetuare il deploy del tuo sito Astro usando Zerops.
```suggestion
description: Come effettuare il deploy del tuo sito Astro usando Zerops.
```

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +[Zerops](https://zerops.io/) è una piattaforma cloud oriantata a gli sviluppatori che può essere usata per eseguire il deploy del tuo sito SSR Astro.
```suggestion
[Zerops](https://zerops.io/) è una piattaforma cloud orientata agli sviluppatori che può essere usata per eseguire il deploy del tuo sito SSR Astro.
```

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +- **Un progetto Astro che usa [l'adattarore `@astrojs/node` per il SSR](/it/guides/integrations-guide/node/)**
```suggestion
- **Un progetto Astro che usa [l'adattatore `@astrojs/node` per il SSR](/it/guides/integrations-guide/node/)** 
```

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +- **Un account Zerops** - Se non ne hai gia uno, puoi [creare il tuo account Zerops](https://zerops.io/) gratuitamente.
```suggestion
- **Un account Zerops** - Se non ne hai già uno, puoi [creare il tuo account Zerops](https://zerops.io/) gratuitamente.
```

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +Il [Zerops per Astro - esempio per Node.js](https://github.com/zeropsio/recipe-astro-nodejs) può essere importato direttamente nella tua [Dashboard di Zerops](https://app.zerops.io/dashboard/projects
```suggestion
Il [Zerops per Astro - esempio per Node.js](https://github.com/zeropsio/recipe-astro-nodejs) può essere importato direttamente nella tua [Dashboard di Zerops](https://app.zerops.io/dashboard/projects), e distribuito con un clic!
```

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +Puoi creare un servizio Node.js per il tuo sito Astro attraverso il [Zerops `project add` wizard](https://app.zerops.io/dashboard/project-add), o importanto un sito Astro usando il `.yaml`.
```suggestion
Puoi creare un servizio Node.js per il tuo sito Astro attraverso il [Zerops `project add` wizard](https://app.zerops.io/dashboard/project-add), o importando un sito Astro usando il `.yaml`.
```

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +La struttura dello YAML sottostante servira per creare un progetto chiamato `my-astro-sites` con Node.js v20 con l'hostname `hellothere`. Un progetto Zerops può contenere più siti Astro.
```suggestion
La struttura dello YAML sottostante servirà per creare un progetto chiamato `my-astro-sites` con Node.js v20 con l'hostname `hellothere`. Un progetto Zerops può contenere più siti Astro.
```

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +Per configurare il processo di build e deploy quando si fa un push a un branch o si crea una nuova release, vai al tuo servizio di Node.js e connetti il servizio di Zerops a una repositoriy GitHub o
```suggestion
Per configurare il processo di build e deploy quando si fa un push a un branch o si crea una nuova release, vai al tuo servizio di Node.js e connetti il servizio di Zerops a una repository GitHub o GitLab.
```

2024-06-16 16:13 UTC, casungo commented on src/content/docs/it/guides/deploy/zerops.mdx
> +3. Esegui il log in usando il tuo access token usando il comando seguente:
```suggestion
3. Effettua il login usando il tuo access token usando il comando seguente:
```

2024-06-18 11:13 UTC, casungo approved these changes
LGTM!

2024-06-18 11:36 UTC, yanthomasdev approved these changes
LGTM! Good work peeps 💜

2024-06-18 11:37 UTC, merged