i18n(zh-cn): update 6-islands/3.mdx
withastro/docs pull request #8546
Opened 2024-06-17 02:24 UTC by liruifengv

#### Description (required)

update 6-islands/3.mdx

#### Related issues & labels (optional)

- Closes #
- Suggested label: 
- https://github.com/withastro/docs/pull/8507

2024-06-17 02:26 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                    | Note                                               |
| ------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [tutorial/6-islands/3.mdx](https://github.com/withastro/docs/blob/db317d54112e93a3eb75cb799551853d3b50f303/src%2Fcontent%2Fdocs%2Fzh-cn%2Ftutorial%2F6-islands%2F3.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-06-18 07:32 UTC, Nin3lee commented on src/content/docs/zh-cn/tutorial/6-islands/3.mdx
> +    description="在教程代码中添加视图过渡动画，自定义页面导航"
句尾需要补充一个缺失的句号“。”

2024-06-18 07:51 UTC, Nin3lee requested changes
78行，添加一处缺失的句号“。”

2024-06-18 07:51 UTC, Nin3lee commented on src/content/docs/zh-cn/tutorial/6-islands/3.mdx
> +    description="在教程代码中添加视图过渡动画，自定义页面导航"
```suggestion
    description="在教程代码中添加视图过渡动画，自定义页面导航。"
```

2024-06-18 07:53 UTC, liruifengv commented on src/content/docs/zh-cn/tutorial/6-islands/3.mdx
> +    description="在教程代码中添加视图过渡动画，自定义页面导航"
Thank you!

2024-06-18 08:09 UTC, Nin3lee approved these changes
LGTM!

2024-06-18 08:22 UTC, liruifengv commented
Thank you again @Nin3lee

2024-06-18 08:22 UTC, merged