i18n(zh-cn): update `install-and-setup.mdx`
withastro/docs pull request #8551
Opened 2024-06-17 02:59 UTC by liruifengv

#### Description (required)
update `install-and-setup.mdx`

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/8508
- https://github.com/withastro/docs/pull/8511
- https://github.com/withastro/docs/pull/8513
- https://github.com/withastro/docs/pull/8545

2024-06-17 03:02 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                          | Note                                               |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [install-and-setup.mdx](https://github.com/withastro/docs/blob/fa359fd6a2418f1e8c022d80fb249d062574bacc/src%2Fcontent%2Fdocs%2Fzh-cn%2Finstall-and-setup.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-06-18 10:04 UTC, Nin3lee requested changes
在110行处，缺失了一段解释性文本。

2024-06-18 10:04 UTC, Nin3lee commented on src/content/docs/zh-cn/install-and-setup.mdx
> +
```suggestion

要对项目进行更改，请在代码编辑器中打开项目文件夹。在开发服务器运行的开发模式下工作能允许您在编辑代码时查看站点的更新。

你还可以 [自定义开发环境的各个方面](#配置你的开发环境) ，例如配置 TypeScript 或者安装官方 Astro 编辑器扩展。

```

2024-06-19 02:34 UTC, liruifengv commented on src/content/docs/zh-cn/install-and-setup.mdx
> +
Thank you so much!

2024-06-19 09:05 UTC, merged