Correction of missing imports for the function 'translatePath'
withastro/docs pull request #8620
Opened 2024-06-21 08:08 UTC by fabriciodev26

Imports should have been added so that the "translatePath" function can be used.

#### Description

I have corrected the lack of required imports for the 'translatePath' function. This ensures that the code can correctly access and use the 'translatePath' function, thus improving the integrity and functionality of the project.

2024-06-21 08:09 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-06-21 08:11 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                               | Note                                               |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| es     | [recipes/i18n.mdx](https://github.com/withastro/docs/blob/63079f1afef285fae15a8e398563853f3b3c4ce8/src%2Fcontent%2Fdocs%2Fes%2Frecipes%2Fi18n.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-06-21 15:59 UTC, TheOtterlord reviewed
Thanks for the PR!

I like being more verbose here, although if we're adding the imports, we should also add the statement defining `translatePath` to complete the snippet, as it's not exported directly. I guess we could import the `defaultLang` as the value to pass to `useTranslatedPath` (it's only needed as it's a required typed param).

```ts
const translatePath = useTranslatedPath(defaultLang);
```

I've not made any code suggestions in GitHub because our translated pages source their content from the english versions, so any changes need to be made to the `en` version of this file. We accept the english version first, then translated versions as separate PRs.

2024-06-24 13:13 UTC, sarah11918 commented
Hi @fabriciodev26 - Just a reminder that if you'd like to contribute this change, it must be made to the `/en/` version of the file! (not `/es/`)

Please let us know if you're interested in making that change! :rocket:

2024-06-24 18:28 UTC, yanthomasdev requested changes
Thanks @fabriciodev26, I'll block this PR from being merged till you make these changes match whatever is merged on #8645.

2024-07-05 16:52 UTC, delucis requested changes
Thanks @fabriciodev26! I think this needs a small change.

2024-07-05 16:52 UTC, delucis commented on src/content/docs/es/recipes/i18n.mdx
> +    import { getLangFromUrl, useTranslatedPath, useTranslations } from '../i18n/utils';
Can you update this to match the change in #8645?

```suggestion
    import { getLangFromUrl, useTranslatedPath } from '../i18n/utils';
    
    const lang = getLangFromUrl(Astro.url);
    const translatePath = useTranslatedPath(lang);
```

2024-07-08 11:09 UTC, sarah11918 approved these changes
Thank you everyone! I've just gone ahead and committed the changes to match so this PR can be published and helping people!

2024-07-08 11:09 UTC, merged