i18n(ja): Add new recipes/sharing-state-islands.mdx translation
withastro/docs pull request #8708
Opened 2024-07-01 09:37 UTC by n-tong009

**Description**

Add a new Japanese translation to recipes/sharing-state-islands.mdx.

The original English version: [recipes/sharing-state-islands.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/recipes/sharing-state-islands.mdx)

2024-07-01 09:38 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-07-01 09:40 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                 | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| ja     | [recipes/sharing-state-islands.mdx](https://github.com/withastro/docs/blob/e1d8bbfdd58520764f3fd20ab0b1b8539f11534f/src%2Fcontent%2Fdocs%2Fja%2Frecipes%2Fsharing-state-islands.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-17 01:49 UTC, satoru2727 commented on src/content/docs/ja/recipes/sharing-state-islands.mdx
> +Astroのウェブサイトを [islands architecture / partial hydration](/en/concepts/islands/) で構築する際に、 **「コンポーネント間で状態を共有したい」** という問題に直面することがあります。
```suggestion
Astroのウェブサイトを [アイランドアーキテクチャ / パーシャルハイドレーション](/ja/concepts/islands/) で構築する際に、 **「コンポーネント間で状態を共有したい」** という問題に直面することがあります。
```

2024-07-17 02:25 UTC, satoru2727 requested changes
@n-tong009 原文と見比べてレビューをさせていただきました。全体的に読みやすく、翻訳は問題ないと思います。いくつか細かい修正点があったので、そちらについて修正をお願いします。

2024-07-17 02:25 UTC, satoru2727 commented on src/content/docs/ja/recipes/sharing-state-islands.mdx
> +  Astroは柔軟性を重視しているため、どのフレームワークを使用しても同様の開発者体験を提供するソリューションが好きです。
```suggestion
- **フレームワークに依存しません。** これにより、フレームワーク間での状態共有がシームレスになります！Astroは柔軟性を重視しているため、どのフレームワークを使用しても同様の開発者体験を提供するソリューションが好きです。
```
原文でもここに改行はないため改行を削除

2024-07-17 02:25 UTC, satoru2727 commented on src/content/docs/ja/recipes/sharing-state-islands.mdx
> +<summary>**🙋 なぜここで `useStore` ヘルパーではなく `.get()` を使用するのですか？ **</summary>
```suggestion
<summary>**🙋 なぜここで `useStore` ヘルパーではなく `.get()` を使用するのですか？**</summary>
```
[プレビュー](https://deploy-preview-8708--astro-docs-2.netlify.app/ja/recipes/sharing-state-islands/)を見るとここだけstrong（\*\*〜\*\*）が効いていないので、スペースを削除。以下のように\*\*〜\*\*のなかにスペースがあると太字にならないみたいです・
**example**
**example **

2024-07-17 07:01 UTC, satoru2727 approved these changes

2024-07-17 12:10 UTC, satoru2727 approved these changes

2024-07-17 13:08 UTC, satoru2727 commented on src/content/docs/ja/recipes/sharing-state-islands.mdx
> +<RecipeLinks slugs={["en/recipes/sharing-state"]} />
```suggestion
<RecipeLinks slugs={["ja/recipes/sharing-state"]} />
```
申し訳ありません。一つ見落としていました。

2024-07-17 13:15 UTC, yanthomasdev commented on src/content/docs/ja/recipes/sharing-state-islands.mdx
> +<RecipeLinks slugs={["en/recipes/sharing-state"]} />
oh thanks! I wasn't finding what link was wrong, don't worry about it!

2024-07-17 13:38 UTC, yanthomasdev approved these changes
LGTM! Thank you! 🙌

2024-07-17 13:38 UTC, merged