i18n(fr): Add `guides/migrate-to-astro/from-xx`
withastro/docs pull request #8732
Opened 2024-07-04 13:12 UTC by thomasbnt

#### Description (required)
- [x] [i18n(fr): Add guides/migrate-to-astro/from-create-react-app.mdx](https://github.com/withastro/docs/commit/a967d6016e71b02ff464c5f4928026b96e90a7e8) 
- [x] [i18n(fr): Add guides/migrate-to-astro/from-docusaurus.mdx](https://github.com/withastro/docs/commit/899dc5e598e675993bb205f602871bf90d688d68) 
- [x] [i18n(fr): Add guides/migrate-to-astro/from-eleventy.mdx](https://github.com/withastro/docs/commit/aecd7c2ebc18adcbe761ccd326976f66ffa868f0) 
- [x] [i18n(fr): Add guides/migrate-to-astro/from-gitbook.mdx](https://github.com/withastro/docs/commit/df46d36476a6390c1f642ae6a85bdec50b82d504) 
- [x] [i18n(fr): Add guides/migrate-to-astro/from-gridsome.mdx](https://github.com/withastro/docs/commit/662609fbb7cd1f2e22c688fc7daf4b9fee1a1e87) 
- [x] [i18n(fr): Add guides/migrate-to-astro/from-hugo.mdx](https://github.com/withastro/docs/commit/b1bdd7e73e787286642f362574158f1887a71056) 
- [x] [i18n(fr): Add guides/migrate-to-astro/from-jekyll.mdx](https://github.com/withastro/docs/commit/8ab0d940aeb8556f923fef4ed10c5af3bb967d2c) 
- [x] [i18n(fr): Add guides/migrate-to-astro/from-pelican.mdx](https://github.com/withastro/docs/commit/ca7bbbe9fa345fd15c9a12a9f6c7fb53d572acb0) 
- [ ] sveltekit
- [ ] vuepress

Gatsby, nuxtjs and nextjs will be not added.

#### Related issues & labels (optional)

- Suggested label: i18n

2024-07-04 13:15 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                                                   | Note                                             |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| fr     | [guides/migrate-to-astro/from-create-react-app.mdx](https://github.com/withastro/docs/blob/ca7bbbe9fa345fd15c9a12a9f6c7fb53d572acb0/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmigrate-to-astro%2Ffrom-create-react-app.mdx) | Localization added, will be marked as complete.  |
| fr     | [guides/migrate-to-astro/from-docusaurus.mdx](https://github.com/withastro/docs/blob/ca7bbbe9fa345fd15c9a12a9f6c7fb53d572acb0/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmigrate-to-astro%2Ffrom-docusaurus.mdx)             | Localization added, will be marked as complete.  |
| fr     | [guides/migrate-to-astro/from-eleventy.mdx](https://github.com/withastro/docs/blob/ca7bbbe9fa345fd15c9a12a9f6c7fb53d572acb0/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmigrate-to-astro%2Ffrom-eleventy.mdx)                 | Localization added, will be marked as complete.  |
| fr     | [guides/migrate-to-astro/from-gitbook.mdx](https://github.com/withastro/docs/blob/ca7bbbe9fa345fd15c9a12a9f6c7fb53d572acb0/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmigrate-to-astro%2Ffrom-gitbook.mdx)                   | Localization added, will be marked as complete.  |
| fr     | [guides/migrate-to-astro/from-gridsome.mdx](https://github.com/withastro/docs/blob/ca7bbbe9fa345fd15c9a12a9f6c7fb53d572acb0/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmigrate-to-astro%2Ffrom-gridsome.mdx)                 | Localization added, will be marked as complete.  |
| fr     | [guides/migrate-to-astro/from-hugo.mdx](https://github.com/withastro/docs/blob/ca7bbbe9fa345fd15c9a12a9f6c7fb53d572acb0/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmigrate-to-astro%2Ffrom-hugo.mdx)                         | Localization added, will be marked as complete.  |
| fr     | [guides/migrate-to-astro/from-jekyll.mdx](https://github.com/withastro/docs/blob/ca7bbbe9fa345fd15c9a12a9f6c7fb53d572acb0/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmigrate-to-astro%2Ffrom-jekyll.mdx)                     | Localization added, will be marked as complete.  |
| fr     | [guides/migrate-to-astro/from-pelican.mdx](https://github.com/withastro/docs/blob/ca7bbbe9fa345fd15c9a12a9f6c7fb53d572acb0/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmigrate-to-astro%2Ffrom-pelican.mdx)                   | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-04 15:13 UTC, ArmandPhilippot requested changes
Thanks @thomasbnt, this was a huge one! 👍🏽 

I added some suggestions:
* some missing translations,
* some rewording (mainly concerning the words order or missing articles),
* also you mistakenly translated a `:::caution` block.

I'm not sure about my proposal for `using Astro HTML templating components` (currently `les composants Astro HTML templating`)... but I think it should be reworded, this sounds weird.

2024-07-04 15:13 UTC, ArmandPhilippot commented on src/content/docs/fr/guides/migrate-to-astro/from-vuepress.mdx
> +VuePress, ou tout autre thème que vous avez installé, a probablement géré une grande partie de la mise en page et des métadonnées de votre site pour vous. Vous pouvez lire l'article sur [la construct
```suggestion
VuePress, ou tout autre thème que vous avez installé, a probablement géré une grande partie de la mise en page et des métadonnées de votre site pour vous. Vous pouvez lire l'article sur [la construction de Layouts Astro en tant qu'enveloppes de page Markdown](/fr/basics/layouts/#mises-en-page-markdownmdx) pour voir comment gérer vous-même le templating dans Astro, y compris votre page `<head>`.
```

2024-07-04 15:18 UTC, thomasbnt commented
> Thanks @thomasbnt, this was a huge one! 👍🏽
> 
> I added some suggestions:
> 
> * some missing translations,
> * some rewording (mainly concerning the words order or missing articles),
> * also you mistakenly translated a `:::caution` block.
> 
> I'm not sure about my proposal for `using Astro HTML templating components` (currently `les composants Astro HTML templating`)... but I think it should be reworded, this sounds weird.

Thanks for catching some bad translating @ArmandPhilippot !

2024-07-04 15:26 UTC, ArmandPhilippot approved these changes
LGTM! 🚀  Thanks for your quick updates @thomasbnt!

2024-07-08 18:31 UTC, yanthomasdev approved these changes
LGTM! This is a big one, thanks y'all!

2024-07-08 18:31 UTC, merged