i18n(fr): add migrate-to-astro/from-nextjs.mdx
withastro/docs pull request #8735
Opened 2024-07-05 10:11 UTC by ArmandPhilippot

#### Description (required)

* Add French translation for [Migrating from Next.js](https://docs.astro.build/en/guides/migrate-to-astro/from-nextjs/) (`migrate-to-astro/from-nextjs.mdx`), added in #2232

#### Related issues & labels (optional)

- Suggested label: i18n

2024-07-05 10:14 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                               | Note                                             |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| fr     | [guides/migrate-to-astro/from-nextjs.mdx](https://github.com/withastro/docs/blob/2cf60c38c5887066eab25f5400d4c3ccff07a71c/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fmigrate-to-astro%2Ffrom-nextjs.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-05 12:03 UTC, thomasbnt requested changes
One missed word, LGTM for the rest

2024-07-05 12:38 UTC, thomasbnt approved these changes
LGTM !

2024-07-08 17:28 UTC, yanthomasdev approved these changes
LGTM, amazing work peeps!

2024-07-08 17:28 UTC, merged