i18n(ja): Add new reference/api-reference.mdx translation
withastro/docs pull request #8888
Opened 2024-07-21 02:42 UTC by n-tong009

## Description

Add a new Japanese translation to src/content/docs/ja/reference/api-reference.mdx

The original English version: [src/content/docs/en/reference/api-reference.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/reference/api-reference.mdx)

2024-07-21 02:45 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                     | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| ja     | [reference/api-reference.mdx](https://github.com/withastro/docs/blob/e859fb1fae2104e102ad3af911f835f103291c98/src%2Fcontent%2Fdocs%2Fja%2Freference%2Fapi-reference.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-22 00:09 UTC, SnowDingo reviewed
翻訳への貢献、ありがとうございます！
まだレビューは完全に終わっていないので承認などは難しいですが、とりあえず読んだところで気になった所は変更点を挙げておきました。
👍

2024-07-22 07:14 UTC, SnowDingo commented
レビュー終わらせておきました！
文字数が多いのに、ここまで完璧に訳してくれてありがとうございます。僕が気になった点は小さなリンク（ウィキペディアやMozilla Docs）の変更と、ローケルをローカルに直したぐらいです。
一応、いくつかのページで今回の翻訳でリンクが壊れてしまうページがあるので、そちらを直せば完了だと思います。
翻訳ありがとうございました🚀

2024-07-23 00:34 UTC, n-tong009 commented
@SnowDingo 
チェックありがとうございます！
レビューが飛んできていないみたいなので、再度確認していただければです！🙇

2024-07-25 02:53 UTC, SnowDingo requested changes
レビュー承認お願いします🙏

2024-07-25 08:59 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +`Astro.preferredLocale` は、ユーザーが優先する言語（ロケール）を表す計算済みの値です。
@SnowDingo 
ロケール（locale）とローカル（local）の差なのかなと思ったので、今回はロケール（locale）を採用しました！
言語（ロケーションlocation）関連の内容になりますので、ロケール（locale）でいいのかなって思ったんですがいかがでしょうか？🤔

2024-07-25 09:47 UTC, n-tong009 commented
@SnowDingo 
ローカルだと `locale ` と `local ` の言葉が被ってしまうのと、[別ページ](https://docs.astro.build/ja/reference/configuration-reference/#i18ndefaultlocale) でロケールをすでに使用されているので、今回はロケールにしようかと思います！
ご意見ありがとうございました！

2024-07-25 09:48 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +現在のURLに設定された言語（ロケール）が含まれているかどうかを確認します。内部的にはこの関数は `APIContext#url.pathname` を使用します。
諸々を加味してロケールを採用します。

2024-07-25 09:48 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +- URLに言語（ロケール）が含まれていない場合
諸々を加味してロケールを採用します。

2024-07-25 09:48 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +言語（ロケール）の `path` に関連付けられた `code` を返す関数です。
諸々を加味してロケールを採用します。

2024-07-25 09:49 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +[`getAbsoluteLocaleUrl`](#getabsolutelocaleurl) と同様に使用して、すべてのロケールの絶対パスのリストを返します。
諸々を加味してロケールを採用します。

2024-07-25 09:51 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +[`getRelativeLocaleUrl`](#getrelativelocaleurl) と同様に使用して、すべてのロケールの相対パスのリストを返します。
諸々を加味してロケールを採用します。

2024-07-25 09:51 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +[`site`] に値が設定されている場合、言語（ロケール）の絶対パスを取得するためにこの関数を使用します。[`site`] が設定されていない場合、この関数は相対URLを返します。ロケールが存在しない場合、Astroはエラーをスローします。
諸々を加味してロケールを採用します。

2024-07-25 09:52 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +この関数を使用して、言語（ロケール）の相対パスを取得します。ロケールが存在しない場合、Astroはエラーをスローします。
諸々を加味してロケールを採用します。

2024-07-25 09:52 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +このモジュールは、プロジェクトで設定した言語（ロケール）を使用してURLを作成するための関数を提供します。
諸々を加味してロケールを採用します。

2024-07-25 09:52 UTC, n-tong009 commented on src/content/docs/ja/reference/api-reference.mdx
> +`Astro.preferredLocale` は、ユーザーが優先する言語（ロケール）を表す計算済みの値です。
諸々を加味してロケールを採用します。

2024-07-25 11:52 UTC, SnowDingo commented
> @SnowDingo ローカルだと `locale ` と `local ` の言葉が被ってしまうのと、[別ページ](https://docs.astro.build/ja/reference/configuration-reference/#i18ndefaultlocale) でロケールをすでに使用されているので、今回はロケールにしようかと思います！ ご意見ありがとうございました！

了解です👍
こちら側の知識不足だったので次からレビューするときは気を付けます！

2024-08-27 16:47 UTC, yanthomasdev reviewed
Good work peeps, could I ask you to make a commit fixing any broken links and updating this to the latest changes? See: https://github.com/withastro/docs/commits/main/src/content/docs/en/reference/api-reference.mdx

2024-10-08 16:59 UTC, yanthomasdev commented
I can see this PR got stale, anyone feel free to reopen the PR and update it according to my instructions, for the time being I'll be closing it!

2024-10-08 16:59 UTC, closed without merging