i18n(ja): Add new reference/directives-reference.mdx translation
withastro/docs pull request #8912
Opened 2024-07-24 07:12 UTC by n-tong009

## Description

Add a new Japanese translation to src/content/docs/ja/reference/directives-reference.mdx

The original English version: [src/content/docs/en/reference/directives-reference.mdx](https://github.com/withastro/docs/blob/main/src/content/docs/en/reference/directives-reference.mdx)

2024-07-24 07:15 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                   | Note                                             |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| ja     | [reference/directives-reference.mdx](https://github.com/withastro/docs/blob/f658c93a44834097b4a1453f2036ab1ad8288a37/src%2Fcontent%2Fdocs%2Fja%2Freference%2Fdirectives-reference.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-24 08:15 UTC, SnowDingo requested changes
@n-tong009様、引き続き高品質な翻訳をしていただき、誠にありがとうございます。
変更点につきましては小さな変更ですので、変更を承認していただけますと大変助かります。
最後に壊れたリンクを直していただければ、私が承認をさせていただきます。
翻訳ありがとうございました。

2024-07-24 08:15 UTC, SnowDingo commented on src/content/docs/ja/reference/directives-reference.mdx
> +UIフレームワークコンポーネントは、特に指定がない限り、クライアントサイドでは静的なHTMLとして扱われます。つまり、`client:*`というディレクティブを使わないと、JavaScriptを含まない単なるHTMLとしてページに表示されるだけです。
```suggestion
特に指定がない限り、UIフレームワークコンポーネントはクライアントサイドでは静的なHTMLとして扱われます。`client:*`ディレクティブを使用しない場合、JavaScriptを含まない単なるHTMLとしてページに表示されます。
```
少しこの部分が冗長な文章になっていたので修正しておきました👍

2024-07-24 09:30 UTC, d-kawabata-futurek commented
Sorry, I authenticated by mistake.

2024-08-06 16:59 UTC, yanthomasdev approved these changes
LGTM! Amazing work!

2024-08-06 17:00 UTC, merged