Add(i18n)/pl/install and setup
withastro/docs pull request #8916
Opened 2024-07-24 15:09 UTC by woolf1717

#### Description (required)

#### Related issues & labels (optional)

- Closes #
- Suggested label:

2024-07-24 15:10 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Vercel 🥳

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-07-24 15:12 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                       | Note                                             |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| pl     | [install-and-setup.mdx](https://github.com/withastro/docs/blob/96f858633cc5b40f3a8566ab109f8253425998cc/src%2Fcontent%2Fdocs%2Fpl%2Finstall-and-setup.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-24 21:25 UTC, RezixDev commented
**Błędna Kotwica markdown**

https://github.com/withastro/docs/blame/ce39d596e8b650daa43557e584557601d7366c6d/src/content/docs/pl/install-and-setup.mdx#L114

Powinno być: #skonfiguruj-swoje-środowisko-dewelperskie

a jest:

#dostosuj-swoje-środowisko-deweloperskie

2024-07-28 10:22 UTC, RezixDev commented on src/content/docs/pl/install-and-setup.mdx
> +3. Teraz możesz [uruchomić serwer developerski Astro](#uruchom-serwer-deweloperski-astro) i sprawdzać podgląd Twojego projektu na żywo, podczas tworzenia aplikacji!
deweloperski

2024-07-28 11:17 UTC, RezixDev commented on src/content/docs/pl/install-and-setup.mdx
> +8. Możesz teraz [uruchomić Astro dev serwer](#uruchom-astro-serwer-developerski) i sprawdzać podgląd Twojego projektu na żywo podczas tworzenia aplikacji!
sprawdzać czy "sprawdzić"?

2024-07-29 09:22 UTC, gacek1123 requested changes

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +Zwróć uwagę, że ten podgląd pokazuje kod w takiej formie, w jakiej istniał w momencie ostatniej kompilacji produkcyjnej. Ma to na celu umożliwienie podglądu tego, jak Twoja strona będzie wyglądać po
```suggestion
Zwróć uwagę, że ten podgląd pokazuje kod w takiej formie, w jakiej istniał w momencie ostatniej kompilacji na produkcję. Ma to na celu umożliwienie podglądu tego, jak Twoja strona będzie wyglądać po wdrożeniu na Internet. Wszelkie późniejsze zmiany w kodzie, dokonane po zbudowaniu nie będą widoczne podczas podglądu strony, dopóki ponownie nie uruchomisz polecenia budującego.
```

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +Sukces! Teraz jesteś gotowy, żeby rozpocząć budowanie z Astro! 🥳
```suggestion
Gratulacje! Jesteś teraz gotów, żeby rozpocząć budowanie z Astro! 🥳
```
Sounds a bit better + more gender neutral

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +Poniżej znajdziesz kilka tematów, z którymi polecamy się zapoznać. Możesz je czytać w dowolnej kolejności. Możesz też zostawić dokumentację na później i poeksperymentować trochę ze swoim nowym projek
```suggestion
Poniżej znajdziesz kilka tematów, z którymi polecamy się zapoznać. Możesz je czytać w dowolnej kolejności. Możesz też zostawić dokumentację na później i poeksperymentować trochę ze swoim nowym projektem Astro oraz wrócić do niej, kiedy pojawią się jakieś trudności bądź będziesz mieć pytania.
```

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +    title="Tworzenie kolekcji treści"
```suggestion
    title="Tworzenie Kolekcji Treści"
```
Name of a service, should be uppercase IMO. Open to discussion

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +    title="Dodaj przejścia pomiędzy widokami"
```suggestion
    title="Dodaj wsparcie View Transitions"
```
Name of a feature

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +    description="Twórz płynne przejścia stron i animacje."
```suggestion
    description="Twórz płynne przejścia między stronami i animacje."
```

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +    title="Naucz się o wyspach"
```suggestion
    title="Naucz się o Wyspach"
```
Name of a feature

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +Zbuduj w pełni funkcjonalny blog w Astro, rozpoczynając od pojedynczej pustej strony, korzystając z  [poradnika  wprowadzającego](/pl/tutorial/0-introduction/).
```suggestion
Zbuduj w pełni funkcjonalny blog w Astro, rozpoczynając od pojedynczej pustej strony, korzystając z [poradnika wprowadzającego](/pl/tutorial/0-introduction/).
```

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +Jest to świetny sposób, żeby sprawdzić, jak działa Astro i zrozumieć podstawowe zasady funkcjonowania stron, układów, komponentów, routingu, wysp i wiele więcej. Poradnik zawiera również opcjonalną,
```suggestion
Jest to świetny sposób żeby sprawdzić jak działa Astro i zrozumieć podstawowe zasady funkcjonowania stron, układów, komponentów, routingu, Wysp i wielu innych. Poradnik zawiera również opcjonalną, przyjazną dla początkujących sekcję, która wyjaśnia podstawowe pojęcia związane z tworzeniem stron internetowych. Przeprowadza ona przez proces instalacji niezbędnych aplikacji na Twoim komputerze, tworzenia konta na GitHub oraz wdrożenia Twojej strony na produkcję.
```

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +    Stwórz pusty folder z nazwą Twojego projektu, a później przejdź do niego.
```suggestion
    Stwórz pusty folder z nazwą Twojego projektu, a później do niego przejdź.
```
I think it sounds a little better

2024-07-29 09:22 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +    Użyjesz tych skryptów później w poradniku uruchamiania Astro i korzystania z różnych komend.
```suggestion
    Użyjesz tych skryptów później w poradniku uruchamiania Astro i korzystania z różnych poleceń.
```

2024-07-31 20:03 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +Jest to świetny sposób, żeby sprawdzić, jak działa Astro i zrozumieć podstawowe zasady funkcjonowania stron, układów, komponentów, routingu, wysp i wiele więcej. Poradnik zawiera również opcjonalną,
Wymieniamy tutaj rzeczy których zasady funkcjonowania chciałby użytkownik poznać, więc wydaje mi się że "wielu innych" pasuje lepiej w tym przypadku.

"zrozumieć podstawowe zasady funkcjonowania stron, układów, komponentów, routingu, Wysp i wielu innych"
zamiast
"zrozumieć podstawowe zasady funkcjonowania stron, układów, komponentów, routingu, Wysp i wiele więcej"

2024-07-31 20:08 UTC, woolf1717 commented on src/content/docs/pl/install-and-setup.mdx
> +Jest to świetny sposób, żeby sprawdzić, jak działa Astro i zrozumieć podstawowe zasady funkcjonowania stron, układów, komponentów, routingu, wysp i wiele więcej. Poradnik zawiera również opcjonalną,
Ok.

2024-08-01 05:04 UTC, gacek1123 requested changes
One last thing I found. Other than this, LGTM!

2024-08-01 05:04 UTC, gacek1123 commented on src/content/docs/pl/install-and-setup.mdx
> +    Możesz uruchomić polecenie `create astro` w dowolnym miejscu na swoim komputerze, więc nie więc nie musisz tworzyć nowego, pustego katalogu dla Twojego projektu przed rozpoczęciem. Jeżeli nie mas
```suggestion
    Możesz uruchomić polecenie `create astro` w dowolnym miejscu na swoim komputerze, więc nie musisz tworzyć nowego, pustego katalogu dla Twojego projektu przed rozpoczęciem. Jeżeli nie masz jeszcze pustego folderu na Twój nowy projekt, asystent inicjalizacji stworzy go automatycznie.
```

2024-08-02 11:39 UTC, gacek1123 approved these changes

2024-08-02 17:50 UTC, yanthomasdev commented
Good work here! @woolf1717, since your PR was opened we made a few changes to this page, could you update it so we can merge it? See: https://github.com/withastro/docs/commit/d4568c60e59902b2e05e9b88050fadd217563326

2024-08-06 21:01 UTC, yanthomasdev approved these changes
LGTM! Good work peeps 🙌

2024-08-06 21:03 UTC, merged