i18n(fr): Add `reference/api-reference.mdx`
withastro/docs pull request #8922
Opened 2024-07-25 12:47 UTC by thomasbnt

#### Description (required)
Add `reference/api-reference.mdx` with @ArmandPhilippot for the second part. 

#### Related issues & labels (optional)

- Suggested label: i18n

2024-07-25 12:50 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                     | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| fr     | [reference/api-reference.mdx](https://github.com/withastro/docs/blob/4d39cf9ea37f28c65fc0bedab482b17d9f085ff5/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Fapi-reference.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-25 13:36 UTC, thomasbnt commented
Pending merge at https://github.com/thomasbnt/docs/pull/1

2024-07-25 14:41 UTC, ArmandPhilippot requested changes
Some small changes, then I think we're good!

2024-07-25 14:41 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +`Astro.request` est un objet standard [Request](https://developer.mozilla.org/fr/docs/Web/API/Request). Il peut être utilisé pour obtenir le `url`, `headers`, `method`, et même le corps de la requête
```suggestion
`Astro.request` est un objet standard [Request](https://developer.mozilla.org/fr/docs/Web/API/Request). Il peut être utilisé pour obtenir les propriétés `url`, `headers`, `method`, et même le corps de la requête.
```

2024-07-25 14:41 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +Avec l'option par défaut `output : 'static', `Astro.request.url` ne contient pas de paramètres de recherche, comme `?foo=bar`, car il n'est pas possible de les déterminer à l'avance lors des construc
```suggestion
Avec l'option par défaut `output: 'static'`, `Astro.request.url` ne contient pas de paramètres de recherche, comme `?foo=bar`, car il n'est pas possible de les déterminer à l'avance lors des constructions statiques. Cependant, en mode `output: 'server'`, `Astro.request.url` contient les paramètres de recherche car ils peuvent être déterminés à partir d'une requête du serveur.
```
A closing `` ` `` was missing. Also, this is a code sample so no space before `:`.

2024-07-25 14:41 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +Analyse la valeur du cookie via `JSON.parse()`, retournant un objet. Lance si la valeur du cookie n'est pas un JSON valide.
```suggestion
Analyse la valeur du cookie via `JSON.parse()`, retournant un objet. Génère une erreur si la valeur du cookie n'est pas un JSON valide.
```

2024-07-25 14:41 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +If true, the cookie is only set on https sites.
```suggestion
Si c'est vrai, le cookie n'est défini que sur les sites https.
```

2024-07-25 14:41 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +Une page (et non un composant enfant) doit `return` le résultat de `Astro.redirect()` pour que la redirection ait lieu.
In this case, I think we can replace the inline code with a French word to be more readable:
```suggestion
Une page (et non un composant enfant) doit retourner le résultat de `Astro.redirect()` pour que la redirection ait lieu.
```

2024-07-25 14:41 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +  `Astro.self` permet aux composants Astro d'être appelés de manière récursive. Ce comportement vous permet d'afficher un composant Astro à partir de lui-même en utilisant `<Astro.self>` dans le modè
```suggestion
`Astro.self` permet aux composants Astro d'être appelés de manière récursive. Ce comportement vous permet d'afficher un composant Astro à partir de lui-même en utilisant `<Astro.self>` dans le modèle du composant. Cela peut être utile pour itérer sur de grands magasins de données et des structures de données imbriquées.
```

2024-07-25 14:41 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +La pagination va passer une propriété `page` à chaque page affichée qui représente une seule page de données dans la collection paginée. Cela inclut les données que vous avez paginées (`page.data`) a
```suggestion
La pagination va passer une propriété `page` à chaque page affichée qui représente une seule page de données dans la collection paginée. Cela inclut les données que vous avez paginées (`page.data`) ainsi que les métadonnées de la page (`page.url`, `page.start`, `page.end`, `page.total`, etc). Ces métadonnées sont utiles pour des choses comme un bouton "Page suivante" ou un message "Pages 1-10 sur 100".
```

2024-07-25 14:41 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +**Exemple de types:**
```suggestion
**Exemple de types :**
```

2024-07-25 14:41 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +- `headings` - Une liste générée de titres, [reflétant l'utilitaire `getHeadings()` d'Astro] (/fr/guides/markdown-content/#propriétés-exportées) sur les importations Markdown et MDX.
```suggestion
- `headings` - Une liste générée de titres, [reflétant l'utilitaire `getHeadings()` d'Astro](/fr/guides/markdown-content/#propriétés-exportées) sur les importations Markdown et MDX.
```

2024-07-25 15:03 UTC, ArmandPhilippot approved these changes
LGTM for me!

> [!caution]
> I translated the second part of the file so another reviewer could be useful.

2024-07-25 19:15 UTC, ArmandPhilippot commented
@thomasbnt Some small changes are required on `api-reference.mdx` in the `Astro.redirect` section since #8923 has been merged.

2024-07-25 19:25 UTC, thomasbnt commented
> @thomasbnt Some small changes are required on `api-reference.mdx` in the `Astro.redirect` section since #8923 has been merged.

Done!

2024-07-25 19:26 UTC, ArmandPhilippot commented
@thomasbnt Thanks, I didn't realized before that I could suggest changes on multiple lines. 😅

2024-07-25 19:31 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +Permet de rediriger vers une autre page, et optionnellement de fournir un [code de réponse avec un statut HTTP](https://developer.mozilla.org/fr/docs/Web/HTTP/Status) comme second paramètre.
```suggestion
Permet de rediriger vers une autre page, et optionnellement de fournir un [code de réponse avec un statut HTTP](https://developer.mozilla.org/fr/docs/Web/HTTP/Status#messages_de_redirection) comme second paramètre.
```

2024-07-30 10:24 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +#### Le prop `page` de pagination
```suggestion
#### La prop `page` de pagination
```
or:

```suggestion
#### La propriété `page` de pagination
```

But in any case **la**, not **le**. 😉

2024-07-31 09:56 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/api-reference.mdx
> +
The file has been updated in #8946, so we should add:
````suggestion

Les fonctions de rappel peuvent être transmises à des emplacements nommés à l'intérieur d'une balise d'élément HTML enveloppante avec un attribut `slot`. Cet élément est uniquement utilisé pour transférer la fonction de rappel à un emplacement nommé et ne sera pas rendu sur la page.

```astro
<Shout message="slots!">
  <fragment slot="message">
    {(message) => <div>{message}</div>}
  </fragment>
</Shout>
```

Utilisez un élément HTML standard pour la balise d'encapsulation ou toute balise en minuscules (par exemple `<fragment>` au lieu de `<Fragment />`) qui ne sera pas interprété comme un composant. N'utilisez pas l'élément HTML `<slot>` car il sera interprété comme un slot Astro.

````

2024-07-31 11:42 UTC, ArmandPhilippot approved these changes
LGTM! 👍🏽

2024-08-01 22:00 UTC, closed without merging