i18n(pl) Pages [astro-pages.mdx]
withastro/docs pull request #8938
Opened 2024-07-28 04:13 UTC by RezixDev

#### Description (required)
Updates the Polish translation of [Pages](https://docs.astro.build/pl/basics/astro-pages/) :
docs/src/content/docs/pl/basics/astro-pages.mdx
#### Related issues & labels (optional)
- Suggested label: i18n

2024-07-28 04:16 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                           | Note                                             |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| pl     | [basics/astro-pages.mdx](https://github.com/withastro/docs/blob/3a5ec60f4757901a15359131b7e28ea80f98bfc9/src%2Fcontent%2Fdocs%2Fpl%2Fbasics%2Fastro-pages.mdx) | Localization added, will be marked as complete.  |
| pl     | [concepts/islands.mdx](https://github.com/withastro/docs/blob/3a5ec60f4757901a15359131b7e28ea80f98bfc9/src%2Fcontent%2Fdocs%2Fpl%2Fconcepts%2Fislands.mdx)     | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-07-31 21:07 UTC, woolf1717 requested changes

2024-07-31 21:07 UTC, woolf1717 commented on src/content/docs/pl/basics/astro-pages.mdx
> +Strona musi produkować pełny dokument HTML. Jeśli nie zostanie to jawnie uwzględnione, Astro domyślnie doda niezbędną deklarację `<!DOCTYPE html>` i zawartość `<head>` do każdego komponentu `.astro`
(#częściowe-strony) - nie działa
trzeba dać coś typu
(#strony-częściowe)

2024-09-18 18:01 UTC, yanthomasdev commented
Hey @RezixDev, thanks for this! I can see there's a few comments/suggestions made here, could you address them? Also, I believe there have been a few updates to this page if you could take a look and update your PR 🙌

2024-09-18 19:57 UTC, RezixDev commented on src/content/docs/pl/basics/astro-pages.mdx
> +Strona musi produkować pełny dokument HTML. Jeśli nie zostanie to jawnie uwzględnione, Astro domyślnie doda niezbędną deklarację `<!DOCTYPE html>` i zawartość `<head>` do każdego komponentu `.astro`
Resolved Anchor Link :)

Thanks!

2024-09-18 20:00 UTC, RezixDev commented on src/content/docs/pl/basics/astro-pages.mdx
> +W fazie rozwoju aplikacji, przy obecności pliku `500.astro`, błąd rzucony w czasie wykonywania jest logowany w Twoim terminalu, w przeciwieństwie do pokazywania się w nakładce błędów.
Same as before:

Thrown -> rzucony
Returned -> zwrócony

2024-09-18 20:22 UTC, RezixDev commented
@yanthomasdev The Page got updated and Issues got resolved ;)

2024-09-19 15:40 UTC, yanthomasdev approved these changes
LGTM! Amazing work! 🙌

2024-09-19 15:41 UTC, merged