i18n(zh-cn): Update `api-reference.mdx`
withastro/docs pull request #8969
Opened 2024-08-01 01:48 UTC by huyikai

#### Description (required)

Update `api-reference.mdx`

#### Related issues & labels (optional)

#8946

2024-08-01 01:51 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                        | Note                                               |
| ------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [reference/api-reference.mdx](https://github.com/withastro/docs/blob/3881db567dd80e7d34477b9aed5c2a79b6d6a6dd/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Fapi-reference.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-01 02:30 UTC, Nin3lee requested changes
在543行，有一处待斟酌的翻译。

2024-08-01 02:30 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +回调函数可以通过带有 `slot` 属性的包装 HTML 元素标签传递给命名插槽。这个元素仅用于将回调传递给命名插槽，不会被渲染到页面上。
```suggestion
回调函数可以传递给带有 `slot` 属性并包装着 HTML 元素标签的具名插槽。这个元素仅用于将回调传递给具名插槽，而不会被渲染到页面上。
```
yikai，这样会不会更准确一些？

2024-08-01 02:33 UTC, huyikai commented on src/content/docs/zh-cn/reference/api-reference.mdx
> +回调函数可以通过带有 `slot` 属性的包装 HTML 元素标签传递给命名插槽。这个元素仅用于将回调传递给命名插槽，不会被渲染到页面上。
确实更好一些 thanks~

2024-08-02 06:25 UTC, liruifengv commented
4.13 发布了，有一些新的更新：https://github.com/withastro/docs/pull/8967

2024-08-02 07:18 UTC, liruifengv commented
> 4.13 发布了，有一些新的更新：#8967

我在 https://github.com/withastro/docs/pull/8992 更新了。 

当这两个PR准备好时同时合并就OK

2024-08-02 07:20 UTC, liruifengv approved these changes
LGTM. Merge this PR with https://github.com/withastro/docs/pull/8992 together.

2024-08-08 01:24 UTC, merged