i18n(zh-cn): Update docs for 4.13
withastro/docs pull request #8992
Opened 2024-08-02 07:17 UTC by liruifengv

#### Description (required)

Update docs for 4.13

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/8967

2024-08-02 07:20 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                                                                | Note                                               |
| ------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [guides/routing.mdx](https://github.com/withastro/docs/blob/a3efbf71138dc1dbd25cf0f88779c7f4a286f98a/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Frouting.mdx)                                                                           | Localization changed, will be marked as complete.  |
| zh-cn  | [reference/api-reference.mdx](https://github.com/withastro/docs/blob/a3efbf71138dc1dbd25cf0f88779c7f4a286f98a/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Fapi-reference.mdx)                                                         | Localization changed, will be marked as complete.  |
| zh-cn  | [reference/configuration-reference.mdx](https://github.com/withastro/docs/blob/a3efbf71138dc1dbd25cf0f88779c7f4a286f98a/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Fconfiguration-reference.mdx)                                     | Localization changed, will be marked as complete.  |
| zh-cn  | [reference/error-reference.mdx](https://github.com/withastro/docs/blob/a3efbf71138dc1dbd25cf0f88779c7f4a286f98a/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Ferror-reference.mdx)                                                     | Localization changed, will be marked as complete.  |
| zh-cn  | [reference/errors/action-query-string-invalid-error.mdx](https://github.com/withastro/docs/blob/a3efbf71138dc1dbd25cf0f88779c7f4a286f98a/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Ferrors%2Faction-query-string-invalid-error.mdx) | Localization added, will be marked as complete.    |
| zh-cn  | [reference/errors/actions-used-with-for-get-error.mdx](https://github.com/withastro/docs/blob/a3efbf71138dc1dbd25cf0f88779c7f4a286f98a/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Ferrors%2Factions-used-with-for-get-error.mdx)     | Localization added, will be marked as complete.    |
| zh-cn  | [reference/errors/rewrite-encountered-an-error.mdx](https://github.com/withastro/docs/blob/a3efbf71138dc1dbd25cf0f88779c7f4a286f98a/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Ferrors%2Frewrite-encountered-an-error.mdx)           | Localization changed, will be marked as complete.  |
| zh-cn  | [reference/errors/rewrite-with-body-used.mdx](https://github.com/withastro/docs/blob/a3efbf71138dc1dbd25cf0f88779c7f4a286f98a/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Ferrors%2Frewrite-with-body-used.mdx)                       | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-02 09:00 UTC, Nin3lee requested changes
一些小改动和句序调整。

2024-08-02 09:00 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/middleware.mdx
> +    // 重新执行中间件
```suggestion
    // 重新执行中间件。
```
对比源文档掉了一个小标点~

2024-08-02 09:00 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/error-reference.mdx
>  - [**RouteNotFound**](/zh-cn/reference/errors/route-not-found/)<br/>Route not found.
```suggestion

```
对比源文档发现这一行已经被移除了，但是我没有追溯到删除的改动历史。

2024-08-02 09:00 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/errors/rewrite-encountered-an-error.mdx
> +:::caution[废弃]
```suggestion
:::caution[已废弃]
```
其他 caution 组件的警示词也是 `已废弃`

2024-08-02 09:00 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/errors/actions-used-with-for-get-error.mdx
> +Action 被使用 GET 请求从表单调用，但只支持 POST 请求。这通常是因为表单上缺少 `method="POST"`。
```suggestion
使用 GET 请求从表单中调用 Action，但只支持 POST 请求。这通常是因为表单上缺少 `method="POST"`。
```
瑞丰，这样修改会更好一些吗？

2024-08-02 10:04 UTC, Nin3lee approved these changes
LGTM!

2024-08-02 17:48 UTC, yanthomasdev commented
Thanks @liruifengv, I believe we're missing both these commits that have been added after your PR: https://github.com/withastro/docs/commit/82b728323fdacb08eb35628bd8e41963773a8880 https://github.com/withastro/docs/commit/8cbc423fefad7c41eacf227bc6b51f142c89ec0f

2024-08-07 09:25 UTC, liruifengv commented
Thank you Yan! @yanthomasdev I have update all.

2024-08-07 16:19 UTC, yanthomasdev approved these changes
LGTM! Good job!

2024-08-07 16:19 UTC, merged