Update view-transitions.mdx
withastro/docs pull request #9017
Opened 2024-08-05 21:23 UTC by Dillonpw

Potential resolution to issue #8787 with an extended explanation of custom View Transitions

#### Description (required)

first iteration of an update to the View Transitions documentation, going into more detail on custom animations.

discord: dillonpw

#### Related issues & labels (optional)

- Closes Improve Custom Animations code example for View Transitions guide #8787
- Suggested label: [improve documentation](https://github.com/withastro/docs/labels/improve%20documentation)

2024-08-05 21:26 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                     | Note                                                       |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------- |
| en     | [guides/view-transitions.mdx](https://github.com/withastro/docs/blob/32a60bb788cb6e8f404553c249561140f24db188/src%2Fcontent%2Fdocs%2Fen%2Fguides%2Fview-transitions.mdx) | Source changed, localizations will be marked as outdated.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-06 11:16 UTC, sarah11918 commented
Thank you, @Dillonpw ! Will ask @martrapp for a technical review on this one!

2024-08-06 22:30 UTC, martrapp commented
Sure thing! Will do tomorrow.

2024-08-07 08:43 UTC, martrapp requested changes
A very cool and helpful example, @Dillonpw! 

My suggestions are mainly aimed at making the code blocks as similar as everywhere else in the docs: titles, single quotation marks, concentration on the essentials and omitting what is not directly related to the topic: How to make good layout components, for example, is already described elsewhere ;-)

It is important to me that the out-animation really takes out the old image and does not push it in.

And yes, even if 'crash' was meant to be fun, it does evoke rather unpleasant associations during software development ;-)  

In terms of content, I think these changes are a real enrichment. The wording in the body text should be approved by native speakers.

2024-08-07 08:47 UTC, martrapp commented on src/content/docs/en/guides/view-transitions.mdx
> +    name: "crash",
Please use single quotation marks in the frontmatter, as is usually done in the documents

2024-08-07 08:48 UTC, martrapp commented on src/content/docs/en/guides/view-transitions.mdx
> +In this instance, the custom animation `crash` is defined inside a `<style is:global>` tag in your root layout file:
"crash" sounds so destructive and somehow like "broken". Surely there's a more cheerful name?

2024-08-07 08:49 UTC, martrapp commented on src/content/docs/en/guides/view-transitions.mdx
> +    fillMode: "forwards",
```suggestion
    direction: "reverse",
```

2024-08-07 08:49 UTC, martrapp commented on src/content/docs/en/guides/view-transitions.mdx
> +    fillMode: "backwards",
```suggestion
```

2024-08-07 08:52 UTC, martrapp commented on src/content/docs/en/guides/view-transitions.mdx
> +
Maybe we should add a sentence saying that you can of course use different objects for forward and backward and different keframe names for old and new?

2024-08-07 14:29 UTC, martrapp approved these changes
Thank you very much, @Dillonpw! Looks good to me!

2024-08-07 16:15 UTC, sarah11918 commented
Thanks for the review, Martin! I'll do my docs review this week!

2024-08-12 11:56 UTC, sarah11918 reviewed
Thank you for this @Dillonpw , and thank you Martin for the helpful review comments to create this helpful example!

I've left a few tiny suggestions, see what you think!

2024-08-12 11:56 UTC, sarah11918 commented on src/content/docs/en/guides/view-transitions.mdx
> +In this instance, the custom animation `bump` is defined inside a `<style is:global>` tag in your root layout file:
```suggestion
The following example shows all the necessary properties to define a custom `bump` animation inside a `<style is:global>` tag in your root layout file:
```
Did we really need two sentences for this? Will this do?  :smile:

2024-08-12 11:56 UTC, sarah11918 commented on src/content/docs/en/guides/view-transitions.mdx
> +The following example shows all the necessary properties to define a custom transition animation.
```suggestion
```

2024-08-12 11:56 UTC, sarah11918 commented on src/content/docs/en/guides/view-transitions.mdx
> +Remember to define the animation behavior in the frontmatter of all the components using the animation:
```suggestion
The animation behavior's must be defined in the frontmatter of every component using the animation:
```

2024-08-12 11:56 UTC, sarah11918 commented on src/content/docs/en/guides/view-transitions.mdx
> +When customizing animations, take some time to experiment with different variations. You can use different objects for forward and backward, and your keyframe animations for old and new can be differ
```suggestion

You have great flexibility when defining custom animations. To achieve your desired result, you may wish to consider unusual combinations such as using different objects for forward and backward, or providing separate keyframe animations for old and new.
```

Is this sort of like what you were going for? It's not really docs' place to say "take some time to experiment", but I did try to make it sound like "you can probably do more than you think -- this feature isn't limiting"

2024-08-12 12:17 UTC, Dillonpw commented
@sarah11918 @martrapp Thank you both for your suggestions, guidance and your time with moving this PR forward!

2024-08-12 14:59 UTC, sarah11918 commented on src/content/docs/en/guides/view-transitions.mdx
> +The animation behavior's must be defined in the frontmatter of every component using the animation:
```suggestion
The animation's behavior must be defined in the frontmatter of every component using the animation:
```

2024-08-12 15:01 UTC, sarah11918 approved these changes
Looks good to me, @Dillonpw ! Thanks again, and welcome to Team Docs! :partying_face:

2024-08-13 06:41 UTC, liruifengv approved these changes
LGTM! 🎉

2024-08-13 06:50 UTC, merged