Create cloudflare.mdx（zh-tw）
withastro/docs pull request #9050
Opened 2024-08-09 09:21 UTC by ERIC-ZHAO-3366

#### Description (required)

Create zh-tw to deploy Astro Site To Cloudflare Pages

ZH-TW

#### Related issues & labels (optional)

- Closes #
- Suggested label: 

eric.zhao.3366（Eric Z.）

2024-08-09 09:21 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🥳.

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-08-09 09:24 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                            | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| zh-tw  | [guides/deploy/cloudflare.mdx](https://github.com/withastro/docs/blob/f4ef1343e47a8f75646bfb183d27d2d5d2c1d598/src%2Fcontent%2Fdocs%2Fzh-tw%2Fguides%2Fdeploy%2Fcloudflare.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-12 02:55 UTC, Nin3lee requested changes
哈喽，Eric！欢迎你给 Astro 繁中提的第一个 PR！

还有一些 `缩进、大小写、链接` 的小问题需要修改哦。

ps: 最后一次 commit 的 [`type: deploy` 那行代码](https://github.com/withastro/docs/pull/9050/commits/45e541df8704aeb6b031298e00e40da4df2493ee#diff-32d9fbd4d50bc36d1d77ff939c204909c5372059442af6e662ee46179da505e7L4) 应该也包含在文件里面，不用删掉。

2024-08-12 02:55 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +你可以將你的Astro項目部署在[Cloudflare Pages](https://pages.cloudflare.com/)，一個平臺供前端開發人員協作和部署靜態（JAMstack）或SSR網站的平臺
```suggestion
你可以將你的Astro項目部署在 [Cloudflare Pages](https://pages.cloudflare.com/)，一個供前端開發人員協作和部署靜態（JAMstack）或 SSR 網站的平臺。
```

2024-08-12 02:55 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +- [如何部署SSR站點](#如何部署SSR站點)
```suggestion
- [如何使用 Git 部署一個站點](#如何使用-Git-部署一個站點)
- [如何使用 Wrangler 部署一個站點](#如何使用-Wrangler-部署一個站點)
- [如何部署 SSR 站點](#如何部署-SSR-站點)
```

2024-08-12 02:55 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +## 如何使用Git部署一個站點
```suggestion
## 如何使用 Git 部署一個站點
```

2024-08-12 02:55 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +<steps>
```suggestion
<Steps>
```

日志中的报告描述了是这个组件的 `大小写问题`，导致了 `CI预览部署的失败`。

2024-08-12 02:55 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +3.登錄Cloudflare Dashboard並在 **Account Home** > **Workers & Pages** > **Overview** 中選擇你的賬戶
```suggestion
1. 在 Cloudflare Pages 創立一個新項目

2. 將你的代碼提交到一個 Git 倉庫中（Github，Gitlab）

3. 登錄 Cloudflare Dashboard 並在 **Account Home** > **Workers & Pages** > **Overview** 中選擇你的賬戶
```

序数后面需要一个空格，来保证步骤被解析成 `<Step>` 组件的一部分。

2024-08-12 02:55 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +title: 部署你的Astro網站至Cloudflare Pages
```suggestion
title: 部署你的 Astro 網站至 Cloudflare Pages
```

2024-08-12 02:55 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +你可以使用 [`@astrojs/cloudflare` 介面卡](/zh-cn/guides/integrations-guide/cloudflare/)將 Astro SSR 站點部署到 Cloudflare Pages。
```suggestion
你可以使用 [`@astrojs/cloudflare` 介面卡](/zh-tw/guides/integrations-guide/cloudflare/)將 Astro SSR 站點部署到 Cloudflare Pages。
```

2024-08-12 02:55 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +如果你正在構建一個使用 [Cloudflare 服務端渲染介面卡](/zh-cn/guides/integrations-guide/cloudflare/) 的按需渲染專案，並且伺服器在構建時失敗，出現如 `[Error] Could not resolve "XXXX. The package "XXXX" wasn't found on the file system but is bui
```suggestion
如果你正在構建一個使用 [Cloudflare 服務端渲染介面卡](/zh-tw/guides/integrations-guide/cloudflare/) 的按需渲染專案，並且伺服器在構建時失敗，出現如 `[Error] Could not resolve "XXXX. The package "XXXX" wasn't found on the file system but is built into node.` 的錯誤資訊：
```

2024-08-12 02:55 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +<ReadMore>閱讀更多關於 [Astro 中的 SSR（服務端渲染）](/zh-cn/guides/server-side-rendering/) 的資訊。</ReadMore>
```suggestion
<ReadMore>閱讀更多關於 [Astro 中的 SSR（服務端渲染）](/zh-tw/guides/server-side-rendering/) 的資訊。</ReadMore>
```

2024-08-13 09:46 UTC, Nin3lee requested changes
还有三处需要修改哈，原因我注释在其中了，欢迎你加入文档翻译的大家庭。

2024-08-13 09:46 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +i18nReady: true
```suggestion
title: 部署你的 Astro 網站至 Cloudflare Pages
description: 如何使用 Cloudflare Pages 將你的 Astro 網站部署到網路上。
type: deploy
i18nReady: true
```

这行 `type: deploy` 目的是用来表示属于 deploy（部署你的网站）文档的，不需要删除。

2024-08-13 09:46 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +- 你的代碼存儲在一個[Github](https://github.com/)或者[Gitlab](https://about.gitlab.com/)賬戶裡
```suggestion
- 一個 Cloudflare 賬戶，如果你沒有已經擁有一個，你可以創建一個免費的 Cloudflare 賬戶在過程中
- 你的代碼存儲在一個 [Github](https://github.com/) 或者 [Gitlab](https://about.gitlab.com/) 賬戶裡
```

2024-08-13 09:46 UTC, Nin3lee commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +```
```suggestion
```bash
# 安裝 Wrangler CLI（命令列）
npm install -g wrangler
# 在 CLI 中登陸 Cloudflare 賬號
wrangler login
# 執行你的構建命令
npm run build
# 建立新的部署
npx wrangler pages deploy dist
```
```
这里的 `#` 是 命令行的注释语法，最后会被渲染成注释。

2024-08-14 18:47 UTC, vrabe commented
這個用語似乎不太符合台灣習慣
建議照[術語表](https://github.com/withastro/docs/blob/main/src/i18n/zh-tw/README.md)修改
雖然我不是 maintainer 就是了

2024-08-14 18:49 UTC, vrabe commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +你可以將你的Astro項目部署在 [Cloudflare Pages](https://pages.cloudflare.com/)，一個供前端開發人員協作和部署靜態（JAMstack）或 SSR 網站的平臺。
```suggestion
你可以將你的 Astro 項目部署在 [Cloudflare Pages](https://pages.cloudflare.com/)，一個供前端開發人員協作和部署靜態（JAMstack）或 SSR 網站的平臺。
```
還有一點空格的小問題

2024-08-18 12:05 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +- [如何使用 Git 部署一個站點](#如何使用-Git-部署一個站點)
我看原文是 `How to deploy through the Cloudflare Pages Dashboard`，這邊的譯文是誤植了嗎？

2024-08-18 12:07 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +- [如何部署 SSR 站點](#如何部署-SSR-站點)
稍微調整得更符合臺灣用語～

```suggestion
- [如何使用 Wrangler 部署](#如何使用-Wrangler-部署)
- [如何部署 SSR 網站](#如何部署-SSR-網站)
```

2024-08-18 12:09 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +- 一個 Cloudflare 賬戶，如果你沒有已經擁有一個，你可以創建一個免費的 Cloudflare 賬戶在過程中
這句的語法感覺不那麼像中文，我調整了一下前後順序和一些用詞

```suggestion
- 一個 Cloudflare 帳號，如果還沒有的話，可以在過程中建立免費的 Cloudflare 帳號
```

2024-08-18 12:11 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +- 你的代碼存儲在一個 [Github](https://github.com/) 或者 [Gitlab](https://about.gitlab.com/) 賬戶裡
```suggestion
- 把程式碼推到 [Github](https://github.com/) 或者 [GitLab](https://about.gitlab.com/) 儲存庫
```

2024-08-18 12:11 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +## 如何使用 Git 部署一個站點
```suggestion
## 如何使用 Git 部署網站
```

2024-08-18 12:12 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +1. 在 Cloudflare Pages 創立一個新項目
```suggestion
1. 在 Cloudflare Pages 建立新專案
```

2024-08-18 12:12 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +2. 將你的代碼提交到一個 Git 倉庫中（Github，Gitlab）
```suggestion
2. 將程式碼推到 git 倉儲（GitHub、GitLab）
```

2024-08-18 12:13 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +3. 登錄 Cloudflare Dashboard 並在 **Account Home** > **Workers & Pages** > **Overview** 中選擇你的賬戶
```suggestion
3. 登錄 Cloudflare Dashboard 並在 **Account Home** > **Workers & Pages** > **Overview** 中選擇你的帳號
```

2024-08-18 12:15 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +4. 選擇 **Create application**，然後選擇 **Pages** 標籤頁，接著選擇 **Connect to Git** 選項。
```suggestion
4. 選擇 **Create application**，接著選 **Pages** 標籤，最後選 **Connect to Git** 選項。
```

稍微調整了一下，減少同一個詞「選擇」重複出現的狀況

2024-08-18 12:17 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +5. 選擇你想部署的 Git 專案並點選 **Begin setup**（初始設定）。
```suggestion
5. 選擇你想部署的 git 專案並點選 **Begin setup**（初始設定）。
```

2024-08-18 12:21 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +    - **Build output directory（構建輸出目錄）:** `dist`
```suggestion
6. 使用以下的建構設定：

    - **Framework preset:** `Astro`
    - **Build command:** `npm run build`
    - **Build output directory:** `dist`
```

專有的文字我傾向統一維持原文～

2024-08-18 12:23 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +7. 點選 **Save and Deploy**（儲存並部署）按鈕。
```suggestion
7. 點選 **Save and Deploy** 按鈕。
```

專有的文字我傾向統一維持原文～

2024-08-18 12:24 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> + 如何使用 Wrangler 部署一個站點
```suggestion
## 如何使用 Wrangler 部署網站
```

2024-08-18 12:26 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +4. 使用 `npx wrangler pages deploy dist` 進行部署。
```suggestion
1. 安裝 [Wrangler CLI](https://developers.cloudflare.com/workers/wrangler/get-started/)。

2. 使用 `wrangler login` 登錄 Cloudflare 帳號並授權 Wrangler。

3. 執行你的建構命令。

4. 使用 `npx wrangler pages deploy dist` 部署。
```

2024-08-18 12:28 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +npx wrangler pages deploy dist
```suggestion
# 安裝 Wrangler CLI（命令列）
npm install -g wrangler
# 透過 CLI 登入 Cloudflare 帳號
wrangler login
# 執行你的建構命令
npm run build
# 建立新的部署
npx wrangler pages deploy dist
```

2024-08-18 12:31 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +上傳完所有的檔案後，Wrangler 將為你提供一個預覽 URL 以檢查你的站點。當你登入 Cloudflare Pages 儀表板時，你將看到你的新專案。
```suggestion
上傳完所有檔案後，Wrangler 會提供一個預覽網址讓你檢查網站。登入 Cloudflare Pages 儀表板時，你就會看到新專案。
```

2024-08-18 12:32 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +要使預覽版正常工作，你必須安裝 `wrangler`
```suggestion
要使預覽正常運作，你必須安裝 `wrangler`
```

2024-08-18 12:33 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +## 如何部署 SSR 站點
```suggestion
## 如何部署 SSR 網站
```

2024-08-18 12:34 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +你可以使用 [`@astrojs/cloudflare` 介面卡](/zh-tw/guides/integrations-guide/cloudflare/)將 Astro SSR 站點部署到 Cloudflare Pages。
```suggestion
你可以使用 [`@astrojs/cloudflare` 轉接器](/zh-tw/guides/integrations-guide/cloudflare/)將 Astro SSR 站點部署到 Cloudflare Pages。
```

2024-08-18 12:34 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +請按照以下步驟設定介面卡。完成後，你可以使用上述文件中的任何方法進行部署。
```suggestion
請按照以下步驟設定轉接器。完成後，你可以使用上述文件中的任何方法進行部署。
```

2024-08-18 12:36 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +使用以下 `astro add` 命令新增 Cloudflare 介面卡以在你的 Astro 專案中啟用 SSR。這將安裝介面卡並一步對你的檔案 `astro.config.mjs` 進行適當的更改。
```suggestion
使用以下 `astro add` 命令新增 Cloudflare 轉接器以在你的 Astro 專案中啟用 SSR。這將安裝轉接器並一併對 `astro.config.mjs` 進行適當的更改。
```

2024-08-18 12:41 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +<ReadMore>閱讀更多關於 [Astro 中的 SSR（服務端渲染）](/zh-tw/guides/server-side-rendering/) 的資訊。</ReadMore>
```suggestion
如果你想要手動安裝轉接器，請完成以下兩個步驟：

<Steps>
1. 使用你喜歡的套件管理器將 `@astrojs/cloudflare` 加到專案的相依套件中。如果你使用 npm 或不確定是哪個管理器，請在終端機執行：

    ```bash
    npm install @astrojs/cloudflare
    ```

2. 將以下內容新增到 `astro.config.mjs` 檔案中：

    ```js title="astro.config.mjs" ins={2, 5-6}
    import { defineConfig } from 'astro/config';
    import cloudflare from '@astrojs/cloudflare';

    export default defineConfig({
      output: 'server',
      adapter: cloudflare()
    });
    ```
</Steps>

<ReadMore>進一步了解 [Astro 的 SSR（伺服器端算繪）](/zh-tw/guides/server-side-rendering/)。</ReadMore>
```

2024-08-18 12:42 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +由於 Cloudflare 的 Auto Minify（自動壓縮）功能，客戶端 Hydration 可能會失敗。如果你在控制檯中看到 `Hydration completed but contains mismatches`，請確保在 Cloudflare 設定中禁用 Auto Minify。
```suggestion
Cloudflare 的 Auto Minify（自動壓縮）功能可能導致客戶端 hydration 失敗。如果你在控制檯中看到 `Hydration completed but contains mismatches`，請確保在 Cloudflare 設定中停用 Auto Minify。
```

2024-08-18 12:51 UTC, mingjunlu commented on src/content/docs/zh-tw/guides/deploy/cloudflare.mdx
> +- 如果你匯入的包中包含了 Node.js 執行時 API，請檢查該包的作者是否支援 `node:*` 的匯入語法。如果不支援，你可能需要找到一個替代的包。
```suggestion
### Node.js runtime API

如果你用 [Cloudflare SSR 轉接器](/zh-tw/guides/integrations-guide/cloudflare/) 的隨需算繪建立專案，而伺服器在建構時失敗，出現如 `[Error] Could not resolve "XXXX. The package "XXXX" wasn't found on the file system but is built into node.` 的錯誤資訊：

- 這意味著你在伺服器端環境中使用的某個套件或匯入與 [Cloudflare runtime API](https://developers.cloudflare.com/workers/runtime-apis/nodejs/) 不相容。

- 如果你直接匯入 Node.js runtime API，請參考 Astro 關於 Cloudflare 的 [Node.js 相容性](/zh-cn/guides/integrations-guide/cloudflare/#nodejs-相容性)文件，瞭解如何進一步解決這個問題。

- 如果你匯入的套件中包含 Node.js runtime API，請檢查該套件的作者是否支援 `node:*` 的匯入語法。如果不支援，你可能需要找到其他替代套件。
```

2024-09-18 18:03 UTC, yanthomasdev commented
Thanks @ERIC-ZHAO-3366, I see Ming-ju Lu gave you a few suggestions, could you address them so we can proceed with the review and merge proccess?

2024-09-24 19:11 UTC, yanthomasdev approved these changes
LGTM! Amazing work! 🙌

2024-09-24 19:11 UTC, merged