i18n(de): add `rendering-modes` translation
withastro/docs pull request #9127
Opened 2024-08-18 10:10 UTC by DerTimonius

#### Description (required)

This PR adds the missing german translation for the `rendering-modes`. The links should all work if I haven't missed anything.

2024-08-18 10:13 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                   | Note                                             |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| de     | [basics/rendering-modes.mdx](https://github.com/withastro/docs/blob/d92391557f2ef30f05e846e29694749c558e0cb5/src%2Fcontent%2Fdocs%2Fde%2Fbasics%2Frendering-modes.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-09-16 14:42 UTC, trueberryless requested changes
Insgesamt tolle Arbeit! 

Ein paar Kleinigkeiten sind mir aufgefallen. Überlege, ob es immer Client-seitig oder Clientseitig, also mit oder ohne Bindestrich sein soll, damit es konsistent ist.

2024-09-16 14:42 UTC, trueberryless commented on src/content/docs/de/basics/rendering-modes.mdx
> +In Astro passieren die meisten Prozesse auf dem Server statt in dem Browser. Dies macht deine Seite oder App grundsätzlich schneller als durch reines client-seitiges Rendering, vor allem auf weniger
vielleicht: statt im Browser
Ich würd "Client-seitiges" schreiben
und dann "Server-seitig" damit es consistent ist

2024-09-16 14:42 UTC, trueberryless commented on src/content/docs/de/basics/rendering-modes.mdx
> +Standardmäßig sind Astro-Projekte so konfiguriert, dass sie beim Erzeugungszeitpunkt vorgerendert werden (also statisch generiert), um die schlankste Browser-Erfahrung zu gewährleisten. Der Browser m
"um eine möglichst schlanke Browser-Erfahrung" klingt glaube ich besser

2024-09-16 14:42 UTC, trueberryless commented on src/content/docs/de/basics/rendering-modes.mdx
> +Statische Seite können [Astro-Inseln](/de/concepts/islands/) für interaktive UI-Komponenten (oder sogar ganze eingebettete, clientseitig gerenderte Apps), geschrieben in einem [UI-Framework deiner Wa
Statische Seite**n**
client-seitig

2024-09-16 14:42 UTC, trueberryless commented on src/content/docs/de/basics/rendering-modes.mdx
> +Astros standardmäßiger `static`-Modus ist eine mächtige, moderne Wahl für Seiten mit vielen Inhalten, die nur selten ändern, und die den gleichen Inhalt an alle Besucher anzeigen.
"die **sich** nur selten ändern und den gleichen ..." ist glaub ich einfacher zum Lesen

2024-09-16 14:42 UTC, trueberryless commented on src/content/docs/de/basics/rendering-modes.mdx
> +Mit [einem SSR-Adapter](/de/guides/server-side-rendering/) können Astros beiden anderen Ausgabemodi konfiguriert werden, um **Rendering bei Bedarf (on-demand) auf einigen oder all deinen Seiten, Rout
"Astros andere beiden" vielleicht?

2024-09-16 14:42 UTC, trueberryless commented on src/content/docs/de/basics/rendering-modes.mdx
> +Da sie bei jedem Besuch neu generiert werden, können diese Routen für jeden Besucher personalisiert werden. So können zum Beispiel on-demand gerenderte Seiten einem eingeloggten deren Profilinformati
einem eingeloggten **Benutzer**
**server-seitiges** oder vorher bei Clientseitig ändern...

2024-09-16 14:42 UTC, trueberryless commented on src/content/docs/de/basics/rendering-modes.mdx
> +<ReadMore>Lies mehr über [mögliche Features mit on-demand Rendering](/de/guides/server-side-rendering/), wie zum Beispiel Cookies, Response- und Request-Objekte, HTML-Streaming, und mehr.</ReadMore>
"und so weiter" ist glaub ich besser, weil sonst zweimal "mehr" im Satz steht, klingt verwirrend...

Sonst super!

2024-09-16 14:42 UTC, trueberryless commented on src/content/docs/de/basics/rendering-modes.mdx
> +- **API-Endpunkte**: Erstelle spezifische Seiten, die als API-Endpunkte für Aufgaben wie Datenbankzugriff, Authentifizierung und Authorisierung funktionieren, während sensitive Daten vom Client gehei
sensible statt sensitive

geheim gehalten werde**n**

2024-09-18 16:24 UTC, trueberryless reviewed
lgtm

2024-09-18 17:02 UTC, yanthomasdev approved these changes
LGTM! Good job!

2024-09-18 17:02 UTC, merged