i18n(zh-cn): update `api-reference.mdx`
withastro/docs pull request #9143
Opened 2024-08-20 07:15 UTC by liruifengv

#### Description (required)

update `api-reference.mdx`

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/9081

2024-08-20 07:19 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                        | Note                                               |
| ------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [reference/api-reference.mdx](https://github.com/withastro/docs/blob/14a896cac48499c3e112d4f9ad009c85c513508e/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Fapi-reference.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-21 11:42 UTC, Nin3lee requested changes
有一些之前的旧翻译不太通顺，可以也在这其中更新吧？

2024-08-21 11:42 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/api-reference.mdx
>  [URL](https://developer.mozilla.org/zh-CN/docs/Web/API/URL )对象，由当前 `Astro.request.url` 的链接字符串值构成。对于与请求的链接的个别属性进行交互是有用的，如路径名和起源。
```suggestion
该 [URL](https://developer.mozilla.org/zh-CN/docs/Web/API/URL ) 对象，是由当前 `Astro.request.url` 的链接字符串值构造。对于与请求 URL 的各个属性进行交互时非常有用，例如路径名和来源。
```

2024-08-22 05:46 UTC, liruifengv commented on src/content/docs/zh-cn/reference/api-reference.mdx
>  [URL](https://developer.mozilla.org/zh-CN/docs/Web/API/URL )对象，由当前 `Astro.request.url` 的链接字符串值构成。对于与请求的链接的个别属性进行交互是有用的，如路径名和起源。
我改了一下

2024-08-22 06:13 UTC, Nin3lee approved these changes
LGTM!

2024-08-22 22:29 UTC, yanthomasdev approved these changes
LGTM! Good job! 🙌

2024-08-22 22:29 UTC, merged