i18n(zh-cn): update error-reference
withastro/docs pull request #9145
Opened 2024-08-20 07:31 UTC by liruifengv

#### Description (required)

update error-reference

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/9081

2024-08-20 07:34 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                                                    | Note                                               |
| ------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [reference/error-reference.mdx](https://github.com/withastro/docs/blob/acc544cc96588c7176a641c49d9a80d76c9d2e00/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Ferror-reference.mdx)                                         | Localization changed, will be marked as complete.  |
| zh-cn  | [reference/errors/get-entry-deprecation-error.mdx](https://github.com/withastro/docs/blob/acc544cc96588c7176a641c49d9a80d76c9d2e00/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Ferrors%2Fget-entry-deprecation-error.mdx) | Localization added, will be marked as complete.    |
| zh-cn  | [reference/errors/unknown-filesystem-error.mdx](https://github.com/withastro/docs/blob/acc544cc96588c7176a641c49d9a80d76c9d2e00/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Ferrors%2Funknown-filesystem-error.mdx)       | Localization added, will be marked as complete.    |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-21 11:51 UTC, Nin3lee requested changes
我把 instead 的意思翻译了进来。

2024-08-21 11:51 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/errors/get-entry-deprecation-error.mdx
> +`getDataEntryById` 和 `getEntryBySlug` 函数已弃用，不能用于查询内容层集合。请使用 `getEntry` 函数。
```suggestion
> **GetEntryDeprecationError**: `METHOD` 函数已弃用，不能用于查询 "COLLECTION" 集合。请改用 `getEntry`。

## 哪里出了问题？

`getDataEntryById` 和 `getEntryBySlug` 函数已弃用，不能用于查询内容层集合。请改用 `getEntry` 函数。
```

2024-08-22 06:20 UTC, Nin3lee approved these changes
LGTM~

2024-08-22 22:23 UTC, yanthomasdev approved these changes
LGTM! Amazing work!

2024-08-22 22:23 UTC, merged