i18n(zh-cn): update `integrations-reference.mdx`
withastro/docs pull request #9146
Opened 2024-08-20 07:56 UTC by liruifengv

#### Description (required)

update `integrations-reference.mdx`

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/9081

2024-08-20 07:59 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                          | Note                                               |
| ------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [reference/integrations-reference.mdx](https://github.com/withastro/docs/blob/a8d7b8dcb05a9df32cf15737f560996aa6084fad/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Fintegrations-reference.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-22 01:49 UTC, Nin3lee requested changes

2024-08-22 01:49 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/integrations-reference.mdx
> +如果在运行所有钩子后的最终值是 `undefined`，路由将根据 [`output` 选项](/zh-cn/reference/configuration-reference/#output) 的值进行预渲染：`hybrid` 模式下预渲染，`server` 模式下按需渲染。
```suggestion
如果在运行所有钩子后的最终值是 `undefined`，路由将根据 [`output` 选项](/zh-cn/reference/configuration-reference/#output) 回退到预渲染的默认值：`hybrid` 模式下预渲染，`server` 模式下按需渲染。
```
我把原文里 `回退` 和 `默认` 的句意都添加了进来。

2024-08-22 01:49 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/integrations-reference.mdx
> +      }) => void | Promise<void>;
```suggestion
      }) => void | Promise<void>;
      'astro:route:setup'?: (options: { route: RouteOptions; logger: AstroIntegrationLogger; }) => void | Promise<void>;
```
遗漏的一行已添加。

2024-08-22 01:49 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/integrations-reference.mdx
> +`component` 属性是一个相对于项目根的只读字符串路径，例如 `"src/pages/blog/[slug].astro"`。
```suggestion
`component` 属性是一个相对于项目根目录的只读字符串路径，例如 `"src/pages/blog/[slug].astro"`。
```
项目根 => 项目根目录

2024-08-22 06:18 UTC, Nin3lee approved these changes
LGTM!

2024-08-22 12:54 UTC, dreyfus92 approved these changes
Thank you peeps! LGTM ✅

2024-08-22 13:01 UTC, merged