i18n(zh-cn): update `configuration-reference.mdx`
withastro/docs pull request #9147
Opened 2024-08-20 08:45 UTC by liruifengv

#### Description (required)

update `configuration-reference.mdx`

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/9081

2024-08-20 08:48 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                            | Note                                               |
| ------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [reference/configuration-reference.mdx](https://github.com/withastro/docs/blob/2cc9dd2f51256b283c1d21a7de7b7c508f465d62/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Fconfiguration-reference.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-22 03:10 UTC, Nin3lee requested changes

2024-08-22 03:10 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +// 需要集合的名字和条目的 ID 作为参数
```suggestion
// 获取集合中的所有条目。
// 需要集合的名字作为参数。
const allBlogPosts = await getCollection('blog');

// 从集合中获取单个条目。
// 需要集合的名字和条目的 ID 作为参数。
```
英文源文档的最后一行漏掉了句号，还需要整一个 PR。

2024-08-22 03:10 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +3. **将引用从 `slug` 改成 `id`**。Content layer 集合不需要 `slug` 字段。相反，所有集合都使用 `id` 字段。
```suggestion
3. **将引用从 `slug` 改成 `id`**。Content layer 集合不需要 `slug` 字段。作为替代，所有集合都使用 `id` 字段。
```

2024-08-22 05:52 UTC, liruifengv commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +`file` loader 从单个本地文件中创建多个条目。当你的所有条目都存储在对象数组中时使用。
"当每个条目只有一个文件时使用此选项" 有歧义。我改成了"当每个条目对于一个文件时使用此选项"

2024-08-22 05:54 UTC, liruifengv commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +// 需要集合的名字和条目的 ID 作为参数
这无关紧要

2024-08-22 05:58 UTC, liruifengv commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +  // 默认情况下，ID 是从相对于 `base` 的文件路径生成的 slug
先折行吧

2024-08-22 06:16 UTC, Nin3lee approved these changes
LGTM!

2024-08-22 13:02 UTC, dreyfus92 approved these changes
Thanks everyone! LGTM ✅

2024-08-22 13:07 UTC, merged