feat: add `HookParameters` type to integrations
withastro/docs pull request #9270
Opened 2024-08-30 10:22 UTC by ematipico

#### Description (required)

This PR improves the reference of the integrations, by adding the types to each hook.

Astro exposes a utility type called `HookParameters<'<HOOK_NAME>'>` that allows for easy type inference.

2024-08-30 10:23 UTC, Princesseuh commented on src/content/docs/en/reference/integrations-reference.mdx
> +import { HookParameters } from 'astro';
```suggestion
import type { HookParameters } from 'astro';
```

2024-08-30 10:25 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                       | Note                                                       |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ---------------------------------------------------------- |
| en     | [reference/integrations-reference.mdx](https://github.com/withastro/docs/blob/2a5846c66bd28e2e3bfa2623df17c0c55e6e3a02/src%2Fcontent%2Fdocs%2Fen%2Freference%2Fintegrations-reference.mdx) | Source changed, localizations will be marked as outdated.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-08-30 10:34 UTC, ascorbic commented on src/content/docs/en/reference/integrations-reference.mdx
> +import {HookParameters} from "astro";
```suggestion
import type { HookParameters } from "astro"; 
```

2024-08-30 10:35 UTC, ascorbic commented
Nice improvement. I only discovered this type this week!

2024-08-30 10:49 UTC, delucis reviewed
I don’t think the way `HookParameters` has been added here is valid TypeScript, is it? You can’t type the parameter twice — you‘re basically doing: `(options: TypeA: TypeB) => ...`

I think I might suggest a separate heading rather than shoe-horning the type into this code block. That also aligns better with usage I think to explain when you might want `HookParameters`.

2024-08-30 11:29 UTC, sarah11918 commented
Just saying that I am going to let @delucis be the one to give final approval here!

2024-08-30 11:35 UTC, Fryuni requested changes

2024-08-30 11:35 UTC, Fryuni commented on src/content/docs/en/reference/integrations-reference.mdx
> +}: HookParameters<'astro:config:done'>) => void | Promise<void>;
It should remove the previous type, now it is `varName: oneType: anotherType`

Same with all of them

2024-09-12 09:36 UTC, delucis reviewed
Thanks again for kicking this off @ematipico! Cleaned this up to add a dedicated section for `HookParameters` to help explain how to use it.

2024-09-12 09:36 UTC, sarah11918 approved these changes

2024-09-12 09:38 UTC, merged