i18n(zh-cn): update `configuration-reference.mdx` & `internationalization.mdx`
withastro/docs pull request #9291
Opened 2024-09-03 01:52 UTC by liruifengv

…tion.mdx`

#### Description (required)

 update `configuration-reference.mdx` & `internationalization.mdx`

#### Related issues & labels (optional)

- https://github.com/withastro/docs/pull/9224

2024-09-03 01:55 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                            | Note                                               |
| ------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| zh-cn  | [guides/internationalization.mdx](https://github.com/withastro/docs/blob/cc9597fcf29c99f56b8bf8048afef592dc08fd27/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Finternationalization.mdx)             | Localization changed, will be marked as complete.  |
| zh-cn  | [reference/configuration-reference.mdx](https://github.com/withastro/docs/blob/cc9597fcf29c99f56b8bf8048afef592dc08fd27/src%2Fcontent%2Fdocs%2Fzh-cn%2Freference%2Fconfiguration-reference.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-09-03 09:43 UTC, Nin3lee requested changes

2024-09-03 09:43 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +默认情况下，Astro 的 i18n 路由会创建页面，将你的访问者重定向到基于你的回退配置的新目的地。浏览器将刷新并显示在 URL 栏中显示的目的地地址。
```suggestion
默认情况下，Astro 的 i18n 路由会创建页面，将你的访问者重定向到基于你的回退配置的新目的地。浏览器将刷新并在 URL 栏中显示目的地地址。
```

2024-09-03 09:43 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +当 `i18n.routing.fallback: "rewrite"` 配置时，Astro 将创建页面，将回退页面的内容重写到原始请求的 URL 上。
```suggestion
当 `i18n.routing.fallback: "rewrite"` 配置时，Astro 则会创建页面，并将回退页面的内容重写到原始请求的 URL 上。
```

2024-09-03 09:43 UTC, Nin3lee commented on src/content/docs/zh-cn/reference/configuration-reference.mdx
> +你的网站访问者将在 `https://example.com/fr/about/` 看到页面的英文版本  ，而不会被重定向。
```suggestion
使用以下配置，如果你有 `src/pages/en/about.astro` 这个文件，但没有 `src/pages/fr/about.astro` 时，`astro build` 命令将生成与 `dist/en/about.html` 页面相同内容的 `dist/fr/about.html` 页面。
你的网站访问者将在 `https://example.com/fr/about/` 看到页面的英文版本，而不会被重定向。
```

2024-09-04 01:58 UTC, Nin3lee approved these changes
LGTM!

2024-09-04 17:28 UTC, yanthomasdev approved these changes
LGTM! Good job! 🙌

2024-09-04 17:29 UTC, merged