i18n(zh-cn): translate guides/actions.mdx into Chinese(Simplified)
withastro/docs pull request #9439
Opened 2024-09-18 08:36 UTC by CaptainOfPhB

#### Description (required)

Translate the `/en/guides/actions` into Chinese(Simplified).

2024-09-18 08:39 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                      | Note                                             |
| ------ | --------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| zh-cn  | [guides/actions.mdx](https://github.com/withastro/docs/blob/c6ad2328f863ef7d2084773701068ba1bd569009/src%2Fcontent%2Fdocs%2Fzh-cn%2Fguides%2Factions.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-09-19 15:58 UTC, Nin3lee requested changes

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +下面的示例显示了一个验证过的 newsletter 注册表单，接受用户的电子邮件并要求“服务条款”复选框的同意。
```suggestion
下面的示例显示了一个验证过的 newsletter 注册表单，它接受用户的电子邮件并要求勾选“服务条款”复选框以同意。
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +    <ReadMore>请参阅 [“从 HTML 表单操作调用 action”](#从-html-表单操作调用-action) 了解提交表单数据的另一种方法</ReadMore>
```suggestion
    <ReadMore>请参阅 [“从 HTML 表单操作调用 action”](#从-html-表单操作调用-action) 以了解提交表单数据的另一种方法。</ReadMore>
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +为了检索输入错误，使用 `isInputError()` 工具函数检查错误是否由无效输入引起。输入错误包含一个 `fields` 对象，其中包含每个未能验证的输入名称的消息。你可以使用这些消息提示用户纠正他们的提交。
```suggestion
要检索输入错误，可以使用 `isInputError()` 工具函数来检查错误是否是由无效输入而引起的。输入错误包含一个 `fields` 对象，其中包含每个验证失败的输入名称的消息。你可以使用这些消息提示用户以纠正他们的提交。
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +  // Handle input errors.
```suggestion
  // 处理输入错误。
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +调用一个 action 时，Astro 会自动处理表单提交，并将结果返回给你的页面。这使得你可以在表单提交后更新 UI，重定向到一个新页面，或者处理任何错误。
```suggestion
你可以在任何 `<form>` 元素上使用标准属性启用零 JS 表单提交。无论是作为 JavaScript 加载失败时的回退，又或者你更喜欢仅从服务器来处理表单时，无需客户端 JavaScript 的表单提交都非常有用。

在服务器上调用 [Astro.getActionResult()](/zh-cn/reference/api-reference/#astrogetactionresult) 会返回表单提交的结果（`data` 或 `error`），并且可以用于动态重定向、处理表单错误、更新 UI 等。

要从 HTML 表单调用 action，可以为 `<form>` 添加 `method="POST"`，并设置表单的 `action` 属性使用你的 action，例如 `action={actions.logout}`。这会将 `action` 属性设置为使用服务器自动处理的查询字符串。
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +为了在一个 action 成功时导航到一个不同的页面，你可以在 `action` 属性中添加一个路径。
```suggestion
要在没有客户端 JavaScript 且 action 成功时导航到一个不同的页面，你可以在 `action` 属性中添加一个路径。
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +### 处理表单操作错误
```suggestion
### 处理表单 action 错误
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +由 `Astro.getActionResult()` 返回的结果是一次性的，每当页面刷新时都会重置为 `undefined`。这对于[处理表单操作错误](#处理表单操作错误)和在成功时向用户显示临时通知非常理想。
```suggestion
### 使用表单的 action 结果以更新 UI

由 `Astro.getActionResult()` 返回的结果是一次性的，每当页面刷新时都会重置为 `undefined`。这对于[处理表单操作错误](#处理表单-action-错误)和在成功时向用户显示临时通知非常理想。
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +          return `Hello, ${input.name}!`
```suggestion
          return `你好，${input.name}!`
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +      // Show alert pop-up with greeting from action
```suggestion
    <button>获取问候语</button>

    <script>
    const button = document.querySelector('button');
    button?.addEventListener('click', async () => {
      // 通过 action 弹出带有问候语的弹窗
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +      // Show alert pop-up with greeting from action
```suggestion
    <button>获取问候语</button>

    <script>
    import { actions } from 'astro:actions';

    const button = document.querySelector('button');
    button?.addEventListener('click', async () => {
      // 通过 action 弹出带有问候语的弹窗
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +        showLogin && <a href="/signin">Log in to like a post.</a>
```suggestion
        showLogin && <a href="/signin">登录后点赞文章。</a>
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +        Like
```suggestion
        // 因意外错误而提前终止
        else if (error) return;
        // 更新点赞数
      }}>
        点赞
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +      Logout
```suggestion
      退出登录
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +      <button>Sign up</button>
```suggestion
        我已同意服务条款
      </label>
      <button>注册</button>
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +      <button>Sign up</button>
```suggestion
        我已同意服务条款
      </label>
      <button>注册</button>
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +  <button>Log out</button>
```suggestion
  <button>退出登录</button>
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +  <button>Sign up</button>
```suggestion
  <button>注册</button>
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +  <button>Sign up</button>
```suggestion
  <p class="error">无法注册。请稍后再试。</p>
)}
<form method="POST" action={'/confirmation' + actions.newsletter}>
  <label>
    E-mail
    <input required type="email" name="email" />
  </label>
  <button>注册</button>
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +  <button>Sign up</button>
```suggestion
  <button>注册</button>
```

2024-09-19 15:58 UTC, Nin3lee commented on src/content/docs/zh-cn/guides/actions.mdx
> +  <p class="success">Added {result.data.productName} to cart</p>
```suggestion
  <p class="success">添加 {result.data.productName} 到购物车</p>
```

2024-10-16 12:49 UTC, liruifengv approved these changes
LGTM! Thank you all! @CaptainOfPhB @Nin3lee

2024-10-16 12:50 UTC, merged