i18n(fr): update `guides/deploy/sst.mdx`
withastro/docs pull request #9480
Opened 2024-09-24 22:55 UTC by ArmandPhilippot

#### Description (required)

Add changes from #9475 to French translation of `guides/deploy/sst.mdx`

> [!NOTE]
> I created a draft while waiting for feedback on #9479 (I haven't updated the highlighting yet)

#### Related issues & labels (optional)

- Suggested label: i18n

2024-09-24 22:58 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                           | Note                                               |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| fr     | [guides/deploy/sst.mdx](https://github.com/withastro/docs/blob/335f375132f2dcdbb6423d0e70be616513c97169/src%2Fcontent%2Fdocs%2Ffr%2Fguides%2Fdeploy%2Fsst.mdx) | Localization changed, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-09-25 10:27 UTC, thomasbnt requested changes
One typo error and for the rest is good!

2024-09-25 10:27 UTC, thomasbnt commented on src/content/docs/fr/guides/deploy/sst.mdx
> +Vous pouvez également utiliser des composants SST supplémentaires omme les Cron Jobs, les Buckets, les Queues, etc. tout en préservant la sûreté du typage.
```suggestion
Vous pouvez également utiliser des composants SST supplémentaires comme les Cron Jobs, les Buckets, les Queues, etc. tout en préservant la sûreté du typage.
```

2024-09-25 10:32 UTC, thomasbnt approved these changes

2024-09-25 21:14 UTC, yanthomasdev approved these changes
LGTM! Good work 🙌

2024-09-25 21:14 UTC, merged