i18n(pl): create astro-syntax.mdx
withastro/docs pull request #9522
Opened 2024-10-02 09:28 UTC by Panelinio

#### Description (required)

Translating Astro Syntax page to Polish.

Discord username: PaneL

#### Related issues & labels

- Suggested label: i18n

### Hacktoberfest-accepted

2024-10-02 09:32 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                             | Note                                             |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| pl     | [basics/astro-syntax.mdx](https://github.com/withastro/docs/blob/665309f824d58713fd38bade2010f042cdb2cf4f/src%2Fcontent%2Fdocs%2Fpl%2Fbasics%2Fastro-syntax.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-02 15:29 UTC, RezixDev requested changes
Kilka poprawek

2024-10-02 15:29 UTC, RezixDev commented on src/content/docs/pl/basics/astro-syntax.mdx
> +Składnia komponentu Astro jest nadzbiorem HTML. Została ona [zaprojektowana, aby ktokolwiek piszący HTML bądź JSX czuł się jak w domu](#różnice-między-astro-a-jsx), oraz aby wspierać dodawanie koment
Została zaprojektowana tak, aby była znajoma dla każdego, kto ma doświadczenie w pisaniu HTML lub JSX, i dodaje wsparcie dla włączania komponentów oraz wyrażeń JavaScript.

"komentarzy"? :D

2024-10-02 15:29 UTC, RezixDev commented on src/content/docs/pl/basics/astro-syntax.mdx
> +Zamiast tego, użyj skryptu po stronie klienta, aby dodać obsługę zdarzeń. Zupełnie jak byś to zrobił w czystym JavaScript:
„jak byś to zrobił”. Powinno być napisane łącznie, czyli „jakbyś to zrobił”.

2024-10-02 15:29 UTC, RezixDev commented on src/content/docs/pl/basics/astro-syntax.mdx
> +Astro może warunkowo wyświetlać HTML używając operatorów logicznych JSX oraz wyrażeń ternarnych.
wyrażeń ternarnych -> "wyrażeń warunkowych"

2024-10-02 15:29 UTC, RezixDev commented on src/content/docs/pl/basics/astro-syntax.mdx
> +{visible ? <p>Pokaż mi!</p> : <p>Również mi pokaż!</p>}
{visible ? <p>Pokaż mnie!</p> : <p>W innym przypadku pokaż mnie!</p>}

2024-10-02 15:29 UTC, RezixDev commented on src/content/docs/pl/basics/astro-syntax.mdx
> +- **[Dyrektywa define:vars](/pl/reference/directives-reference/#definevars) nie jest wspierana.** Jeśli nie możesz zawrzeć pochodnych za pomocą dodatkowego elementu (np. `<div>`), to możesz ręcznie d
Jeśli nie możesz owinąć elementów potomnych dodatkowym elementem (np. <div>), możesz ręcznie dodać style={--myVar:${value}} do swojego elementu.

2024-10-02 15:29 UTC, RezixDev commented on src/content/docs/pl/basics/astro-syntax.mdx
> +Fragmenty mogą być użyte do uniknięcia dodawania elementów otaczających, kiedy dodajesz [dyrektywy `set:*`](/pl/reference/directives-reference/#sethtml), jak w poniższym przykładzie:
otaczających -> pakujących

2024-10-02 15:29 UTC, RezixDev commented on src/content/docs/pl/basics/astro-syntax.mdx
> +Składnia komponentu Astro jest nadzbiorem HTML. Została ona zaprojektowana, aby ktokolwiek piszący HTML bądź JSX czuł się jak w domu, ale istnieje kilka kluczowych różnic między plikami `.astro` a JS
Została zaprojektowany tak, aby był znajomy dla każdego, kto ma doświadczenie w HTML lub JSX, jednak istnieje kilka kluczowych różnic między plikami .astro a JSX.

2024-10-02 15:29 UTC, RezixDev commented on src/content/docs/pl/basics/astro-syntax.mdx
> +<p>Astro wspiera wiele elementów korzeni w szablonie.</p>
<p>Astro wspiera wiele elementów root w szablonie.</p>

2024-10-04 14:06 UTC, RezixDev commented
Looks fine, LGTM :)

2024-10-06 22:04 UTC, yanthomasdev approved these changes
LGTM! Thanks!

2024-10-06 22:04 UTC, merged