i18n(pl): Create project-structure.mdx
withastro/docs pull request #9525
Opened 2024-10-02 12:27 UTC by Panelinio

#### Description (required)

I am translating the Project Structure page into Polish.
Discord username: PaneL

#### Related issues & labels (optional)

- Suggested label: i18n
- Hacktoberfest: hacktoberfest-accepted

2024-10-02 14:47 UTC, RezixDev commented
"opinionated" trochę dziwnie brzmi :D

Może: "Astro wykorzystuje z góry narzuconą strukturę folderów dla Twojego projektu."

conventions -> zasady/normy (u ciebie jest "pomysły")

<img width="609" alt="image" src="https://github.com/user-attachments/assets/48e49f3a-6294-4d7c-99e9-40840682f008">

regorganizować -> "zmienić układ"

2024-10-02 15:00 UTC, RezixDev requested changes
Kilka błędów stylistycznych

2024-10-04 14:09 UTC, RezixDev commented
Looks fine. 

LGTM :D

2024-10-06 21:56 UTC, yanthomasdev approved these changes
LGTM! Amazing work! 🙌

2024-10-06 21:57 UTC, merged