i18n(fr): add `components-reference.mdx`
withastro/docs pull request #9579
Opened 2024-10-07 10:13 UTC by ArmandPhilippot

#### Description (required)

Move "Built-in components" section from `api-reference.mdx` to `components-reference.mdx` (see #9465)

#### Related issues & labels (optional)

- Suggested label: i18n

2024-10-07 10:16 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                   | Note                                               |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | -------------------------------------------------- |
| fr     | [basics/astro-components.mdx](https://github.com/withastro/docs/blob/90484a6f68fd399fec0d4af2d90e9195d15b17bf/src%2Fcontent%2Fdocs%2Ffr%2Fbasics%2Fastro-components.mdx)               | Localization changed, will be marked as complete.  |
| fr     | [reference/api-reference.mdx](https://github.com/withastro/docs/blob/90484a6f68fd399fec0d4af2d90e9195d15b17bf/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Fapi-reference.mdx)               | Localization changed, will be marked as complete.  |
| fr     | [reference/components-reference.mdx](https://github.com/withastro/docs/blob/90484a6f68fd399fec0d4af2d90e9195d15b17bf/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Fcomponents-reference.mdx) | Localization added, will be marked as complete.    |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-08 07:55 UTC, pioupia requested changes

2024-10-08 07:55 UTC, pioupia commented on src/content/docs/fr/reference/components-reference.mdx
> +Un tableau de formats d'image à utiliser pour les balises `<source>`. Par défaut, ceci est défini sur `['webp']`.
Ceci ? Pas plutôt "elle" (l'option), ou "il" (le format) ?
```suggestion
Un tableau de formats d'image à utiliser pour les balises `<source>`. Par défaut, il est défini sur `['webp']`.
```

2024-10-08 10:16 UTC, pioupia approved these changes
LGTM

2024-10-08 13:00 UTC, yanthomasdev approved these changes
LGTM! Thanks 🙌

2024-10-08 13:01 UTC, merged