feat(next): tweak i18n
withastro/docs pull request #9756
Opened 2024-10-21 14:52 UTC by florian-lefebvre

#### Description (required)

Puts `locales` before `defaultLocale`

#### Related issues & labels (optional)

- Closes #
- Suggested label: 

#### For Astro version: `5.x`. See https://github.com/withastro/astro/pull/12243.

2024-10-21 17:45 UTC, casungo requested changes
just a minor tweak :)

2024-10-21 17:45 UTC, casungo commented on src/content/docs/en/guides/internationalization.mdx
> +Both a list of all supported languages ([`locales`](/en/reference/configuration-reference/#i18nlocales)) and a default language ([`defaultLocale`](/en/reference/configuration-reference/#i18ndefaultlo
```suggestion
Both a list of all supported languages ([`locales`](/en/reference/configuration-reference/#i18nlocales)) and a default language ([`defaultLocale`](/en/reference/configuration-reference/#i18ndefaultlocale)), which must be one of the languages listed in `locales`, need to be specified in an `i18n` configuration object. Additionally, you can configure more specific routing and fallback behavior to match your desired URLs.
```

Previously, it sounded a bit off to me. Tried to fix it

2024-10-22 00:18 UTC, casungo approved these changes
LGTM!

2024-10-22 11:10 UTC, sarah11918 approved these changes
LGTM! Thanks @florian-lefebvre !

2024-10-22 11:58 UTC, merged