docs: use `PackageManagerTabs` for `install-and-setup.mdx` code-blocks
withastro/docs pull request #9774
Opened 2024-10-22 20:46 UTC by m-krebs

#### Description (required)

- update `install-and-setup.mdx` to make use of the `PackageManagerTabs` component.

#### Related issues & labels (optional)
- Suggested label: design

2024-10-22 20:46 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🥳.

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-10-22 20:49 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                       | Note                                                       |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| en     | [install-and-setup.mdx](https://github.com/withastro/docs/blob/924a4c8e6a06cff219303dd16efaca0eecdfe93c/src%2Fcontent%2Fdocs%2Fen%2Finstall-and-setup.mdx) | Source changed, localizations will be marked as outdated.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-22 21:14 UTC, ArmandPhilippot requested changes
Hi @m-krebs! Thanks for this update and welcome to team Docs! 🎉
I think it makes sense since we have a dedicated component for that. However, you forgot to update most of the `Fragment` (the `label` prop must be converted to a `slot` prop like you did for the first one).

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="pnpm">
```suggestion
      <Fragment slot="pnpm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="yarn">
```suggestion
      <Fragment slot="yarn">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="npm">
```suggestion
      <Fragment slot="npm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="pnpm">
```suggestion
      <Fragment slot="pnpm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="yarn">
```suggestion
      <Fragment slot="yarn">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +  <Fragment label="npm">
```suggestion
  <Fragment slot="npm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +  <Fragment label="pnpm">
```suggestion
  <Fragment slot="pnpm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +  <Fragment label="yarn">
```suggestion
  <Fragment slot="yarn">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="npm">
```suggestion
      <Fragment slot="npm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="pnpm">
```suggestion
      <Fragment slot="pnpm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="yarn">
```suggestion
      <Fragment slot="yarn">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="npm">
```suggestion
      <Fragment slot="npm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="pnpm">
```suggestion
      <Fragment slot="pnpm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="yarn">
```suggestion
      <Fragment slot="yarn">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="npm">
```suggestion
      <Fragment slot="npm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="pnpm">
```suggestion
      <Fragment slot="pnpm">
```

2024-10-22 21:14 UTC, ArmandPhilippot commented on src/content/docs/en/install-and-setup.mdx
> +      <Fragment label="yarn">
```suggestion
      <Fragment slot="yarn">
```

2024-10-22 21:52 UTC, m-krebs commented
Interestingly it works even with the label prop, so I didn't notice my mistake. But thanks for correcting :)

2024-10-22 22:20 UTC, ArmandPhilippot approved these changes
LGTM! Thanks again for bringing consistency in the use of components!

> it works even with the label prop

Oh weird, in the preview it didn't work... that's why I thought there was a problem!

2024-10-23 15:08 UTC, Fryuni approved these changes
LGTM!

Thanks for the PR and welcome to Team Docs @m-krebs 🥳🎉

And thanks for the review @ArmandPhilippot

2024-10-23 16:46 UTC, yanthomasdev approved these changes
Nice work, thanks!

2024-10-23 16:47 UTC, merged