Update i18n.mdx
withastro/docs pull request #9780
Opened 2024-10-23 19:30 UTC by jeremyxgo

#### Description (required)

Add astro-react-i18next to the community libraries section in the i18n recipie.

The goal of astro-react-i18next is to integrate i18next and react-i18next into Astro seamlessly.

#### Related issues & labels (optional)

- Suggested label: add new content

2024-10-23 19:30 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🥳.

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-10-23 19:33 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                               | Note                                                       |
| ------ | -------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------- |
| en     | [recipes/i18n.mdx](https://github.com/withastro/docs/blob/ce57a2701bc1096645121fdb72e0bee2edf6decd/src%2Fcontent%2Fdocs%2Fen%2Frecipes%2Fi18n.mdx) | Source changed, localizations will be marked as outdated.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-24 04:01 UTC, apatel369 approved these changes
LGTM. Thanks for doing this. Welcome to Team Docs. 🥳

2024-11-12 22:27 UTC, casungo requested changes
Adjusted the description for consistency with the rest of the page content.

2024-11-12 22:27 UTC, casungo commented on src/content/docs/en/recipes/i18n.mdx
> +- [astro-react-i18next](https://github.com/jeremyxgo/astro-react-i18next) — Integrates i18next and react-i18next seamlessly into your Astro website to provide robust i18n support for React components
```suggestion
- [astro-react-i18next](https://github.com/jeremyxgo/astro-react-i18next) — An Astro integration that seamlessly enables the use of i18next and react-i18next in React components on Astro websites.
```

2024-11-13 20:50 UTC, merged