i18n(fr): create `reference/modules/astro-assets.mdx`
withastro/docs pull request #9824
Opened 2024-10-26 10:52 UTC by ArmandPhilippot

#### Description (required)

Translate the new `reference/module/astro-assets.mdx` file in French (see #9687 and #9820).

#### Related issues & labels (optional)

- Suggested label: i18n

2024-10-26 10:56 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                     | Note                                             |
| ------ | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------ |
| fr     | [reference/modules/astro-assets.mdx](https://github.com/withastro/docs/blob/0162fe63b79fe9c3dde9fc0fe86694ae8afa17ec/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Fmodules%2Fastro-assets.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-28 11:30 UTC, thomasbnt requested changes

2024-10-28 11:30 UTC, thomasbnt commented on src/content/docs/fr/reference/modules/astro-assets.mdx
> + Astro fournit des composants intégrés et des fonctions d'aide pour optimiser et afficher vos images. Pour des fonctionnalités et des exemples d'utilisation, [consultez notre guide d'images](/fr/guid
```suggestion
Astro fournit des composants intégrés et des fonctions d'aide pour optimiser et afficher vos images. Pour des fonctionnalités et des exemples d'utilisation, [consultez notre guide d'images](/fr/guides/images/).
```

2024-10-28 11:35 UTC, thomasbnt approved these changes
LGTM! :tada:

2024-10-28 12:38 UTC, yanthomasdev approved these changes
LGTM! Good work!

2024-10-28 12:38 UTC, merged