i18n(fr): create `reference/modules/astro-i18n.mdx`
withastro/docs pull request #9827
Opened 2024-10-26 12:31 UTC by ArmandPhilippot

#### Description (required)

Moves the Internationalization reference from `api-reference.mdx` to a new location `reference/modules/astro-i18n.mdx` (see #9687)

Note: I didn't remove the content in `api-reference.mdx` so at the moment the content is duplicated. I think it's better to do that in a separate PR to avoid conflicts.

#### Related issues & labels (optional)

- Suggested label: i18n

2024-10-26 12:34 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                 | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| fr     | [reference/modules/astro-i18n.mdx](https://github.com/withastro/docs/blob/3b444b8c203d23d2f95c74d12810760bbb9e74ac/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Fmodules%2Fastro-i18n.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-28 11:42 UTC, thomasbnt requested changes

2024-10-28 11:42 UTC, thomasbnt commented on src/content/docs/fr/reference/modules/astro-i18n.mdx
> +  return new Response("Not found", { status: 404 });
```suggestion
  return new Response("Non trouvée", { status: 404 });
```

2024-10-29 00:45 UTC, thomasbnt approved these changes

2024-10-29 16:40 UTC, yanthomasdev approved these changes
LGTM! Thanks!

2024-10-29 16:41 UTC, merged