i18n(fr): create `reference/modules/astro-middleware.mdx`
withastro/docs pull request #9828
Opened 2024-10-26 12:39 UTC by ArmandPhilippot

#### Description (required)

Moves the Middleware reference from `api-reference.mdx` to a new location `reference/modules/astro-middleware.mdx` (see #9687)

Note: I didn't remove the content in `api-reference.mdx` so at the moment the content is duplicated. I think it's better to do that in a separate PR to avoid conflicts.

#### Related issues & labels (optional)

- Suggested label: i18n

2024-10-26 12:42 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                                                             | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| fr     | [reference/modules/astro-middleware.mdx](https://github.com/withastro/docs/blob/d1d51d96e5948f30ffe45be2b6c5cda51f891396/src%2Fcontent%2Fdocs%2Ffr%2Freference%2Fmodules%2Fastro-middleware.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-10-28 11:37 UTC, thomasbnt requested changes
Miss two phrases to translate

2024-10-28 11:37 UTC, thomasbnt commented on src/content/docs/fr/reference/modules/astro-middleware.mdx
> +You can import and use the utility function `defineMiddleware()` to take advantage of type safety:
```suggestion
Vous pouvez importer et utiliser la fonction utilitaire `defineMiddleware()` pour bénéficier tout en sécurité le type :
```

2024-10-28 11:37 UTC, thomasbnt commented on src/content/docs/fr/reference/modules/astro-middleware.mdx
> +// `context` and `next` are automatically typed
```suggestion
// `context` et `next` sont automatiquement saisis
```

2024-10-28 12:20 UTC, ArmandPhilippot commented on src/content/docs/fr/reference/modules/astro-middleware.mdx
> +You can import and use the utility function `defineMiddleware()` to take advantage of type safety:
Par contre la fin de la phrase me semble étrange, que penses-tu de :
```suggestion
Vous pouvez importer et utiliser la fonction utilitaire `defineMiddleware()` pour bénéficier de la sûreté du typage :
```

2024-10-29 00:46 UTC, thomasbnt commented on src/content/docs/fr/reference/modules/astro-middleware.mdx
> +You can import and use the utility function `defineMiddleware()` to take advantage of type safety:
> Contributor

Oui c'est mieux!

2024-10-29 13:56 UTC, thomasbnt approved these changes
LGTM! Thanks!

2024-10-29 16:02 UTC, yanthomasdev approved these changes
LGTM!

2024-10-29 16:03 UTC, merged