i18n(ru): update translations for `imports.mdx`
withastro/docs pull request #9907
Opened 2024-11-04 13:30 UTC by Gennad-r

#### Description (required)

Russian translations for `imports.mdx`

#### First-time contributor to Astro Docs? 

yes

2024-11-04 13:31 UTC, astrobot-houston commented
Hello! Thank you for opening your **first PR** to Astro’s Docs! 🎉

Here’s what will happen next:

1. Our GitHub bots will run to check your changes.
   If they spot any broken links you will see some error messages on this PR.
   Don’t hesitate to ask any questions if you’re not sure what these mean!

2. In a few minutes, you’ll be able to see a preview of your changes on Netlify 🥳.

3. One or more of our maintainers will take a look and may ask you to make changes.
   We try to be responsive, but don’t worry if this takes a few days.

2024-11-04 13:34 UTC, astrobot-houston commented
<!-- lunaria-action-comment -->

## Lunaria Status Overview


🌕 **This pull request will trigger status changes.**

<details>
<summary>Learn more</summary>

By default, every PR changing files present in the [Lunaria configuration's `files` property](https://lunaria.dev/reference/configuration/#files-required) will be considered and trigger status changes accordingly.

You can change this by adding one of the keywords present in the [`ignoreKeywords` property in your Lunaria configuration file](https://lunaria.dev/reference/configuration/#ignorekeywords) in the PR's title (ignoring all files) or by [including a tracker directive](https://lunaria.dev/guides/tracking/#tracker-directives) in the merged commit's description. 
</details>

### Tracked Files




| Locale | File                                                                                                                                                   | Note                                             |
| ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------ | ------------------------------------------------ |
| ru     | [guides/imports.mdx](https://github.com/withastro/docs/blob/6ba855448256c390174c86b056b844481426513a/src%2Fcontent%2Fdocs%2Fru%2Fguides%2Fimports.mdx) | Localization added, will be marked as complete.  |

<details>
<summary>Warnings reference</summary>

| Icon | Description                                                                                                                                       |
| ---- | ------------------------------------------------------------------------------------------------------------------------------------------------- |
| 🔄️  | The source for this localization has been updated since the creation of this pull request, make sure all changes in the source have been applied. |

</details>

2024-11-12 08:21 UTC, jsparkdev reviewed
Welcome to your first contribution!

2024-11-12 08:21 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +Astro включает встроенную поддержку TypeScript. Вы можете импортировать `.ts` и `.tsx` файлы напрямую в ваш проект Astro и даже писать TypeScript-код прямо внутри [скрипта компонента Astro](/ru/basic
```suggestion
Astro включает встроенную поддержку [TypeScript](https://www.typescriptlang.org/). Вы можете импортировать `.ts` и `.tsx` файлы напрямую в ваш проект Astro и даже писать TypeScript-код прямо внутри [скрипта компонента Astro](/ru/basics/astro-components/#скрипт-компонента) и любых [тегах скриптов](/ru/guides/client-side-scripts/).
```

Fixed invalid links.

If a Russian-language page for the TypeScript site exists, please let me know! I think you can fix it with that.

2024-11-12 08:21 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +`Astro.glob()` принимает только один параметр: относительный [шаблон glob](/ru/guides/imports/#glob-patterns), соответствующий локальным файлам, которые вы хотите импортировать. Это асинхронная функц
```suggestion
`Astro.glob()` принимает только один параметр: относительный [шаблон glob](/ru/guides/imports/#шаблоны-glob), соответствующий локальным файлам, которые вы хотите импортировать. Это асинхронная функция, которая возвращает массив экспортов каждого соответствующего файла.
```

2024-11-12 08:21 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +// импортирует все файлы, оканчивающиеся на `.astro` в `./src/components/`
```suggestion
---
// импортирует все файлы, оканчивающиеся на `.astro` в `./src/components/`
```

2024-11-12 08:21 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +Например, шаблон glob `./pages/**/*.{md,mdx}` начинается в подкаталог�� pages, просматривает все его подкаталоги (`/**`) и соответствует любому имени файла (`/*`), которое заканчи��ается на `.md` или
Some strings don't seem to be rendering correctly.

2024-11-12 08:21 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +<ReadMore>Узнайте больше о [подключении коллекций](/ru/guides/content-collections/#querying-collections) и возврате записей контента.</ReadMore>
```suggestion
<ReadMore>Узнайте больше о [подключении коллекций](/ru/guides/content-collections/#запрос-к-коллекциям) и возврате записей контента.</ReadMore>
```

2024-11-13 07:26 UTC, jsparkdev requested changes
Thank you for your contribution.

A few things need to be corrected.

2024-11-13 07:26 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +Astro компоненты, импортированные с помощью `Astro.glob`, имеют тип [`AstroInstance`](/ru/reference/api-reference/#astro-files). Вы можете отобразить каждый экземпляр компонента, используя его свойст
```suggestion
Astro компоненты, импортированные с помощью `Astro.glob`, имеют тип [`AstroInstance`](/ru/reference/api-reference/#файлы-astro). Вы можете отобразить каждый экземпляр компонента, используя его свойство `default`:
```

2024-11-13 07:26 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +Astro компоненты, импортированные с помощью `Astro.glob`, имеют тип [`AstroInstance`](/ru/reference/api-reference/#astro-files). Вы можете отобразить каждый экземпляр компонента, используя его свойст
Fix invalid link.

2024-11-13 07:26 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +[Коллекции контента](/ru/guides/content-collections/) предоставляют API [`getCollection()`](/ru/reference/modules/astro-content/#getcollection) для загрузки нескольких файлов вместо `Astro.glob()`. Е
```suggestion
[Коллекции контента](/ru/guides/content-collections/) предоставляют API [`getCollection()`](/ru/reference/modules/astro-content/#getcollection) для загрузки нескольких файлов вместо `Astro.glob()`. Если ваши файлы контента (например, Mark загружает и инициализирует запрошенный файл коллекции в каталоге `src/content/`), используйте `getCollection()`, чтобы [запросить коллекцию](/ru/guides/content-collections/#запрос-к-коллекциям) и вернуть записи контента.
```

2024-11-13 07:26 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +<ReadMore>Узнайте больше о [подключении коллекций](/ru/guides/content-collections/#запрос-к-коллекциям) и возврате записей контента.</ReadMore>
Looks like I made a mistake!

This part doesn't seem to exist in the original documentation.

2024-11-13 07:26 UTC, jsparkdev commented on src/content/docs/ru/guides/imports.mdx
> +Astro поддерживает загрузку WASM файлов напрямую в ваше приложение, используя API браузера [`WebAssembly`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly
```suggestion
Astro поддерживает загрузку WASM файлов напрямую в ваше приложение, используя API браузера [`WebAssembly`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly).
```

2024-11-25 15:07 UTC, sarah11918 commented
Hi @Gennad-r ! Same comment here as the other PR! I'm sorry for the delay but we will wait to merge this one into v5 docs!

2024-11-27 21:02 UTC, sarah11918 requested changes
Just putting a block on this so it does not get accidentally merged into v4 docs!

See you in v5!  😄

2024-12-05 18:40 UTC, sarah11918 commented
OK @Gennad-r ! V5 is out, so I'm taking off the block, but please do update your branch because the site has changed A LOT since this PR was made. 😅  I'm sorry if there might be conflicts to deal with!

2025-01-03 18:47 UTC, closed without merging